### ISSUE TITLE
How do I implement a custom Serializer by Newtonsoft, used instead of Text.Json

### ISSUE THREAD

**Issue by yb12306** [dotnetcore/CAP#1005]
I want to implement  a custom Serializer by Newtonsoft,but i don't know how to write .please help me.thank you

        Message ISerializer.Deserialize(string json)
        {
            return JsonConvert.DeserializeObject<Message>(json);
        }

        object ISerializer.Deserialize(object value, Type valueType)
        {
            return JsonConvert.DeserializeAnonymousType(value, valueType);
        }

        Task<Message> ISerializer.DeserializeAsync(TransportMessage transportMessage, Type valueType)
        {
            if (valueType == null || transportMessage.Body == null)
            {
                return Task.FromResult(new Message(transportMessage.Headers, null));
            }

            var obj = JsonConvert.DeserializeAnonymousType(Encoding.UTF8.GetString(transportMessage.Body), valueType);

            return Task.FromResult(new Message(transportMessage.Headers, obj));
        }

        bool ISerializer.IsJsonType(object jsonObject)
        {
            return jsonObject is JObject;
        }

        string ISerializer.Serialize(Message message)
        {
            return JsonConvert.SerializeObject(message);
        }

        Task<TransportMessage> ISerializer.SerializeAsync(Message message)
        {
            if (message == null)
            {
                throw new ArgumentNullException(nameof(message));
            }

            if (message.Value == null)
            {
                return Task.FromResult(new TransportMessage(message.Headers, null));
            }

            var jsonBytes = JsonConvert.SerializeObject(message.Value);
            return Task.FromResult(new TransportMessage(message.Headers, Encoding.UTF8.GetBytes(jsonBytes)));
        }
  

like this?can you show me example?

**Comment by yang-xiaodong** [comment]
see https://github.com/dotnetcore/CAP/commit/e5607f09f184b23e6c33330c568c9082fd49c8d9#diff-06b0b1ce6bb0a834493bbdafd8a44a4ea322aeb9a724581ab39597051aa51269

**Comment by yb12306** [comment]
I get it ,thank you.
