### ISSUE TITLE
Dashboard request interface absolute path

### ISSUE THREAD

**Issue by girvs** [dotnetcore/CAP#1011]
Can it be modified to a relative path

`https://haokao-live-lz.oss-cn-beijing.aliyuncs.com/41633744067_.pic_hd.jpg?Expires=1633744670&OSSAccessKeyId=TMP.3Kdo2MQBoVEpUYzgTHb9d8pypf4ijxAZ1aED838Cd9b67mGWH7SeT3cqAAt5axGf9dTq1vgPTTcdJVrqsYAuuWXxQ5hkwT&Signature=%2BuFo1tFiSY2goDtnBscLr9OFBMY%3D`

**Comment by yang-xiaodong** [comment]
see https://cap.dotnetcore.xyz/user-guide/zh/monitoring/dashboard/#dashboard_2
