### ISSUE TITLE
能否支持多框架版本适配？

### ISSUE THREAD

**Issue by ldqk** [dotnetcore/CAP#1013]
目前我们有许多.NET Core的项目，但由于项目创建的起始日期有的比较早期，有.NET Core2.x的项目，有.NET Core3.x的项目，也有最新的.NET5的项目，由于历史原因，一些早期框架版本的项目也不便于直接升级.NET5，而.NET Core2.x的项目只能引用CAP 2.x的版本，无法安装最新的版本，.NET5的项目也无法引用比较早期的CAP 2.x的包，这就造成了CAP包版本不一致带来项目间消息发布订阅的一些错误，项目间通信无法正常联动，所以能否让CAP支持多版本的目标框架？
PS：我大概看了一下源码，CAP依赖的一些第三方包也没有强制要求目标框架是.netstandard2.1及以上，所以我想：CAP应该是可以做到多版本目标框架适配的，如果有需要的话，我也可以帮忙修改CAP的各个项目文件，以支持.netstandard2.0到.NET5的多版本适配？
期待您的回复~

**Comment by yang-xiaodong** [comment]
就算支持了 netstandard2.0， 2.x的项目也用不了哈，因为 Microsoft.Extension 相关包都不兼容

**Comment by ldqk** [comment]
Microsoft.Extension相关包可以在项目文件里面写条件的，像这样：
https://github.com/ldqk/Masuit.Tools/blob/5b5e5c3dae2162f89d8624e86d85e35ef868e6b8/Masuit.Tools.Abstractions/Masuit.Tools.Abstractions.csproj#L54

**Comment by yang-xiaodong** [comment]
我们马上支持 6.0 了，那你是引用 2.0，还是 3.0，还是 5.0 呢？

**Comment by ldqk** [comment]
![QQ图片20200807210328](https://user-images.githubusercontent.com/20254980/136746655-c3a3477b-1de1-4b15-9f38-d16dcd2c7a21.jpg)
追求最新的技术确实很好，但实际生产项目中总会有一些历史原因是没法短时间一起升级到最新技术上的，比如autofac、automapper、hangfire等这类项目是支持多框架版本适配的，做到在支持新框架版本的同时也兼顾到老版本的目标框架，而CAP这个项目我相信也是有非常多的项目用到了生产，其中肯定也有很多项目还不是基于.NET5/6的，所以我认为CAP这个项目有必要做多目标框架版本适配，而不是只能让.NET5/6项目才能引用安装最新的CAP包，期望大佬能够接受这个建议。
![QQ图片20210629141421](https://user-images.githubusercontent.com/20254980/136748352-6e93a8f2-b5d0-4059-ab8c-53bdede20b7e.gif)

**Comment by ldqk** [comment]
好吧，了解了
![QQ图片20181210202813](https://user-images.githubusercontent.com/20254980/136895268-b636ea41-1524-4729-8307-1df493b537cc.jpg)
