### ISSUE TITLE
how to call all subscribers by event locally inside server

### ISSUE THREAD

**Issue by giorgilekveishvili-meama** [dotnetcore/CAP#1017]
Hello , how can I publish event locally inside server across all subscribers without actually sending message to broker?

**Comment by yang-xiaodong** [comment]
Hello, do you means how to using CAP sending message without broker in Monolithic Architecture? I think [MediatR](https://github.com/jbogard/MediatR) is what you need.

**Comment by yang-xiaodong** [comment]
Why do you want to call all subscribers?

**Comment by giorgilekveishvili-meama** [comment]
For example when server goes offline and new instance is created after it , Im using EventStoreDB for storing events and re-executing not handled events which was not handled on this server , currently im finding this subscribers with my custom reflection logic , but it would be nice to call some kind of dispatcher method of CAP to call them with registered SubscribtionFilters

**Comment by yang-xiaodong** [comment]
You can inject `MethodMatcherCache` class and using `GetCandidatesMethodsOfGroupNameGrouped`  method to get all groupd subscriberes.
 
https://github.com/dotnetcore/CAP/blob/d1d771dcf1f6561038a1f8361e8c4fe593e9e7b8/src/DotNetCore.CAP/Internal/MethodMatcherCache.cs#L27

**Comment by giorgilekveishvili-meama** [comment]
As I see this method will return all subscriber method information and I can invoke it with reflection , but better way would be to Invoke this subscribers with its own subscriberfilters no?

**Comment by giorgilekveishvili-meama** [comment]
@yang-xiaodong  but if i dont have message stored ? how can I execute DispatchAsync
