### ISSUE TITLE
Communication between modules within monolithic application (single process)

### ISSUE THREAD

**Issue by dario-l** [dotnetcore/CAP#1027]
How to properly achieve communication between modules which resides in the same application (single process).

Each module can publish messages. Each module can receive messages. Strictly speaking I need pub/sub.
Each module can have one or more subscribers where some of them may handle the same type of message.

How should I configure producers/subscribers to handle the same type of message by different subscribers independently (in parallel - where the business code will be executed in different/independent transaction)?

**Comment by yang-xiaodong** [comment]
Because we are linearly placed in memory and then use multiple thread to consume

https://github.com/dotnetcore/CAP/blob/b194d60830421bf2d00e5bcf123707483a98799a/src/DotNetCore.CAP/Processor/IDispatcher.Default.cs#L67-L68

**Comment by dario-l** [comment]
> Because we are linearly placed in memory and then use one or multiple thread to consume, this is the design

On of my application modules handles a large workload. Because messages are processed linear (even if I have more than one subscriber and more than one queue) when one message is processed longer, the remaining messages must wait in the queue. This causes large lags in many business processes in my application.

That's why CAP is not usable in my scenario. I'm very disappointed. 😞 

Need to create own solution. Thanks that conversation.

**Comment by yang-xiaodong** [comment]
@dario-l  I have a question. If you want to ensure that messages are processed linearly, if a message fails, will it block the processing of all subsequent messages?

**Comment by dario-l** [comment]
@yang-xiaodong I never wanted processing messages linearly. You said that CAP is processing messages linearly
> Because we are linearly placed in memory

I would not like to CAP should decide for me how to process my data. Once again, so that you understand me where I see the problem.

**Not everyone do microservices!** An application may have more than one Bounded Context (BC) in it (I call it application module). Each BC should have at least one queue (RabbitMQ or Kafka topic) to receive the messages. I can do this by giving separate Group names for each BC. CAP will create separate queues for each BC and for each of them it will set up a dedicated/independent subscriber.

One of my BC's is a reporting system (module) where I want messages to be processed one by one (I don't want concurrent consumers). In other BC's, I may have more than one consumer per queue. Setting `ConsumerThreadCount=1` will cause each BC to wait for the reporting module to process the heavy and lengthy report before the remaining messages are consumed.

If I wanted to consume messages linearly, I would only make one queue for the entire application.

Unfortunately at present:
- I can't set `ConsumerThreadCount` per group (increasing `ConsumerThreadCount` will cause my reporting module to start processing messages concurrently)
- the CAP design is such that even if my application supports, say, 20 queues, after increasing `ConsumerThreadCount` to 2, the number of consumers per queue will also increase twice, unfortunately (from the code fragment you showed above) the CAP will still use a maximum of 2 threads which is weak (I will have 40 independent consumers and only 2 threads for processing messages)

Now, can You see it? 😃 

What I'm looking for?
[Each consumer group should have own Channel pipeline](https://github.com/dotnetcore/CAP/blob/b194d60830421bf2d00e5bcf123707483a98799a/src/DotNetCore.CAP/Processor/IDispatcher.Default.cs#L67) with own setting of `ConsumerThreadCount`.

That will give us freedom to decide how application should handle messages from all queues/topics.

**Comment by yang-xiaodong** [comment]
Hello,

Thanks for your explanation. Since my first language is not English, so I did't understand your meaning quickly.

I think I got your point now,  see PR #1035 , Is this what you want?

But we may not merge this PR in the short term because this is a big change and we need to investigate

**Comment by dario-l** [comment]
@yang-xiaodong Yes, that's it but I've implemented this today in PR #1034 😄 Check it out, there is a working sample.

**Comment by yang-xiaodong** [comment]
Oh, emmm

I was very busy during the day and didn't check my email. Before I started, I didn't notice that you have submitted a PR. It seems that we have done the same work.  :)

**Comment by dario-l** [comment]
> It seems that we have done the same work. :)
@yang-xiaodong Unfortunately yes. Mine is completed and working. Ready for verification and merging. 😃 

If You want I can also update the documentation with new settings.

**Comment by yang-xiaodong** [comment]
Ok, That will be nice

**Comment by dario-l** [comment]
Excellent 👍🏻 
Can I count on a new release version? 😃

**Comment by yang-xiaodong** [comment]
Fixed in version `5.2.0-preview-152861792`  , release to nuget a few minutes ago!
