### ISSUE TITLE
[Question] Cap kafka received empty message

### ISSUE THREAD

**Issue by akunitski** [dotnetcore/CAP#1030]
Publisher: .net 5.0(web api project) + dotnet core cap 5.1.3
Subscriber: .net5.0(console app) + dotnet core cap 5.1.3

Publisher publish message without any problem and retries. Row was added to published table.
Subscriber don't receive any message on debug and has exception on console:

2021-10-28 12:45:51,229 DEBUG DotNetCore.CAP.Internal.ConsumerRegister - Received message. id:, name: 
2021-10-28 12:45:51,254 ERROR DotNetCore.CAP.Internal.ConsumerRegister - An exception occurred when process received message. Message:'DotNetCore.CAP.Messages.TransportMessage'.
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern, RegexOptions options)
   at DotNetCore.CAP.Internal.ConsumerServiceSelector.MatchWildcardUsingRegex(String key, IReadOnlyList`1 executeDescriptor)
   at DotNetCore.CAP.Internal.ConsumerServiceSelector.SelectBestCandidate(String key, IReadOnlyList`1 executeDescriptor)
   at DotNetCore.CAP.Internal.MethodMatcherCache.TryGetTopicExecutor(String topicName, String groupName, ConsumerExecutorDescriptor& matchTopic)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass22_0.<RegisterMessageProcessor>b__0(Object sender, TransportMessage transportMessage)

My kafka deployed on external aws server. Publisher and subscriber deployed on other server.

1. Publisher action:
`await _capEventSender.SendAsync(TopicNames.ElasticEntityTopic,
                        new ElasticEntityEvent<UpdateEntityIncrementalIndexCommand>(
                            ElasticEventTypes.ElasticEntityIncrementUpdate,
                            new UpdateEntityIncrementalIndexCommand(task.Id))
                        );`

2. Subscriber: 
`public class IncrementalEntityConsumer : IIncrementalEntityConsumer, ICapSubscribe
    {
        [CapSubscribe(TopicNames.ElasticEntityTopic)]
        public Task IncrementalEntityConsumeAsync(ElasticEntityEvent @event)
        {
            ... do some action
            return Task.CompletedTask;
        }
    }`

3. Cap serializer:
`public class CapSerializer : ISerializer
    {
        private readonly ILogger<CapSerializer> _logger;
        public CapSerializer(ILogger<CapSerializer> logger)
        {
            _logger = logger;
        }

        public Task<TransportMessage> SerializeAsync(Message message)
        {
            if (message == null)
            {
                _logger.LogInformation($"Serialize Async with empty message");

                throw new ArgumentNullException(nameof(message));
            }

            if (message.Value == null)
            {
                _logger.LogInformation($"Serialize Async with empty message value");

                return Task.FromResult(new TransportMessage(message.Headers, null));
            }

            var json = JsonConvert.SerializeObject(message.Value);

            _logger.LogInformation($"Serialize Async with message: {json}");

            return Task.FromResult(new TransportMessage(message.Headers, Encoding.UTF8.GetBytes(json)));
        }

        public Task<Message> DeserializeAsync(TransportMessage transportMessage, Type valueType)
        {
            if (valueType == null || transportMessage.Body == null)
            {
                _logger.LogInformation($"Deserialize Async with empty TransportMessage");

                return Task.FromResult(new Message(transportMessage.Headers, null));
            }

            var json = Encoding.UTF8.GetString(transportMessage.Body);

            _logger.LogInformation($"Deserialize Async with TransportMessage: {json} and Type: {valueType}");

            return Task.FromResult(new Message(transportMessage.Headers, JsonConvert.DeserializeObject(json, valueType)));
        }

        public string Serialize(Message message)
        {
            var json = JsonConvert.SerializeObject(message);

            _logger.LogInformation($"Serialize with message: {json}");

            return json;
        }

        public Message Deserialize(string json)
        {
            _logger.LogInformation($"Deserialize with json: {json}");

            return JsonConvert.DeserializeObject<Message>(json);
        }

        public object Deserialize(object value, Type valueType)
        {
            if (value is JToken jToken)
            {
                _logger.LogInformation($"Deserialize with value: {jToken} and Type: {valueType}");

                return jToken.ToObject(valueType);
            }
            throw new NotSupportedException("Type is not of type JToken");
        }

        public bool IsJsonType(object jsonObject)
        {
            return jsonObject is JToken;
        }
    }`

Have any ideal why I got this exception?

**Comment by yang-xiaodong** [comment]
Did you call `BootstrapAsync` in your console application to start CAP?

https://github.com/dotnetcore/CAP/blob/4d510cd16e6b4571cbb23d2fb1a4b23661753135/samples/Sample.ConsoleApp/Program.cs#L32

**Comment by akunitski** [comment]
> Did you call `BootstrapAsync` in your console application to start CAP?
> 
> https://github.com/dotnetcore/CAP/blob/4d510cd16e6b4571cbb23d2fb1a4b23661753135/samples/Sample.ConsoleApp/Program.cs#L32

Now I call `BootstrapAsync` but still get the same exception. If I run publisher and subscriber locally and start kafka on docker locally I didn't get this exception early and after adding `BootstrapAsync` I also didn't get exception.

**Comment by yang-xiaodong** [comment]
We are unable to assist with environmental issues. From the perspective of the exception, the received message is caused by null

**Comment by akunitski** [comment]
> We are unable to assist with environmental issues. From the perspective of the exception, the received message is caused by null

Ok, thanks for your help.
