### ISSUE TITLE
DotNetCore.CAP.InMemoryStorage.MemoryMessage do not recycle memory

### ISSUE THREAD

**Issue by SurroundSea** [dotnetcore/CAP#1031]

**Comment by SurroundSea** [comment]
![image](https://user-images.githubusercontent.com/62426262/139785493-f8e814bf-66fd-4dbe-b99e-f94cc4b059c9.png)

**Comment by yang-xiaodong** [comment]
see #927

closed by https://zhuanlan.zhihu.com/p/25795393
