### ISSUE TITLE
Change DotNetCore.CAP.Processor.TransportCheckProcessor  from Debug to Inf?

### ISSUE THREAD

**Issue by KayakFisher205** [dotnetcore/CAP#1038]
Is it possible in the 5.2.0 -Preview to force the DotNetCore.CAP.Processor.TransportCheckProcessor  from Debug to Information in Serilog? I saw the issue https://github.com/dotnetcore/CAP/issues/913 where someone wanted to hide it but I like having it since it shows some action is occurring. There can be long pauses in messages for my application and having the message come through is like a heartbeat message. Otherwise, I'll have to use https://github.com/dotnetcore/CAP/issues/913 to go through each Debug message and hide the ones I don't need.

**Comment by yang-xiaodong** [comment]
Same as #913, you can set the default level to what you need, and set `TransportCheckProcessor` to `Debug`
```json
"Logging": {    
  "LogLevel": {
    "Default": "Warning",
    "DotNetCore.CAP.Processor.TransportCheckProcessor": "Debug"
  }
}
```
