### ISSUE TITLE
Message consumption in K8S is very slow, and stateName has lots of changes

### ISSUE THREAD

**Issue by dazhu6666** [dotnetcore/CAP#1041]
Using one POD to queue a lot of messages, running 5 pods and consuming very fast. Currently, the number of messages is very low, 1 per second Max. Trying to configure consumerThreadCount has no effect. Consumption is very slow, excluding the database level

**Comment by yang-xiaodong** [comment]
Closed by https://zhuanlan.zhihu.com/p/25795393
