### ISSUE TITLE
[Question] Handling error message.

### ISSUE THREAD

**Issue by horseznguyen** [dotnetcore/CAP#1042]
Hi,

The CAP will handle the error messages by reading these messages in the database and pushing again. but if I scale out many instance of service, so what happen in this case ? The message to be sent is duplicated or the Cap will lock messages during push and other instances have to wait or get unlocked messages.

Is there a way to configure separate retrieving of error messages and pushing again, I would like multiple instances to save messages to the database and only one instance to handle error messages.

Thanks.

**Comment by yang-xiaodong** [comment]
Hello, please see PR https://github.com/dotnetcore/CAP/pull/671#issuecomment-697071575
