### ISSUE TITLE
jetstream .* wildcard topic

### ISSUE THREAD

**Issue by lable** [dotnetcore/CAP#1047]
Nats Jetstream use “.” as a separator, but is replaced by "_" by the cap driver, and jetstream XXX.* wildcard cannot be used.

```
sample.console.showtime -> sample_console_showtime
```

**Comment by yang-xiaodong** [comment]
see https://docs.nats.io/running-a-nats-service/nats_admin/jetstream_admin/naming

**Comment by yang-xiaodong** [comment]
Fixed in v6.0
