### ISSUE TITLE
Snowflake algorithm time step back exception

### ISSUE THREAD

**Issue by handloong** [dotnetcore/CAP#1050]
```
if (timestamp < _lastTimestamp)
{ 
    throw new Exception($"InvalidSystemClock: Clock moved backwards, Refusing to generate id for {_lastTimestamp - timestamp} milliseconds");
}
```
                
linux好像做不到即同步时间又防止时间回拨问题，
能否优化雪花算法，或者提供接口，自己实现雪花算法。

参考：https://www.jianshu.com/p/057342b958e5

**Comment by yang-xiaodong** [comment]
这个不在我们考虑的范围，CAP用来发送业务消息，本身消息量不大，即使有时间回拨问题（也不采取stepback方案），出现重复的概率也是极低。而同时我们提供了`CAP_WORKERID`和`CAP_DATACENTERID`环境变量也可以一定程度解决问题。

**Comment by handloong** [comment]
> 这个不在我们考虑的范围，CAP用来发送业务消息，本身消息量不大，即使有时间回拨问题（也不采取stepback方案），出现重复的概率也是极低。而同时我们提供了`CAP_WORKERID`和`CAP_DATACENTERID`环境变量也可以一定程度解决问题。

能不能提供自定义的privoder，我们自己实现 

现在我们有多台服务器，时间不同步，用NTP同步就会出现回拨问题。

其实是单台服务器时间出现回拨。现在的临时办法我们是服务器时间不同步，

但是现在多台服务器的时间会有1-2秒的差异，影响到数据。

杨老板~ 这种应该怎么解决呢？

**Comment by yang-xiaodong** [comment]
“影响到数据” 指的是Id重复还是大小的问题？

**Comment by handloong** [comment]
> 
“影响到数据” 的意思是我们代码的DateTime.Now【创建时间】不一致。因为业务代码是在4台服务上轮询走的。

4台服务器现在不能使用NTP （回拨问题。）

**Comment by yang-xiaodong** [comment]
DateTime.Now不一致和雪花算法没关系啊，雪花算法用来生成的数据库Published和Received表Id主键

**Comment by handloong** [comment]
SnowflakeId.cs
 public virtual long NextId()
 其实我想做的就是重写这个方法。

**Comment by yang-xiaodong** [comment]
那你倒是把报的异常贴出来啊？

**Comment by handloong** [comment]
if (timestamp < _lastTimestamp)
                    throw new Exception(
                        $"InvalidSystemClock: Clock moved backwards, Refusing to generate id for {_lastTimestamp - timestamp} milliseconds");

**Comment by handloong** [comment]
异常就是这个

**Comment by yang-xiaodong** [comment]
可以采用ntpd此方案，则不会发生回拨，同时指定 -x 参数

https://docs.ntpsec.org/latest/ntp_conf.html

### tinker
#### stepback
The argument is the step threshold for the backward direction, which by default is 0.128 sec. It can be set to any positive number in seconds. If both the forward and backward step thresholds are set to zero, step adjustments will never occur. Note: The kernel time discipline is disabled if each direction of step threshold are either set to zero or greater than .5 second.

**Comment by handloong** [comment]
谢谢杨老板！我先试试此方案。同时我也提了一个PR，修改计算雪花ID的时候出现回退的异常。

**Comment by yang-xiaodong** [comment]
> 谢谢杨老板！我先试试此方案。同时我也提了一个PR，修改计算雪花ID的时候出现回退的异常。

不用谢，如果可行的话可以给个反馈哈

**Comment by Allen-dududu** [comment]
这个方法只能解决一次时间回拨问题，如果出现了两次时间回拨，那么就会生成重复的ID。

**Comment by PengYouLin** [comment]
这个问题最终解决了嘛？
