### ISSUE TITLE
同一个事务下（自动提交），多次publish会抛异常，事务只能被commit一次

### ISSUE THREAD

**Issue by Boy-boy** [dotnetcore/CAP#1054]
using (var connection = new MySqlConnection(ConnectionString))
        {
            using (var transaction = connection.BeginTransaction(_capBus, autoCommit: true))
            {
                //业务代码
                _capBus.Publish("xxx.services.show.time", DateTime.Now);
                _capBus.Publish("xxx.services.show.time", DateTime.Now);
            }
        }

**Comment by xiangxiren** [comment]
autoCommit: false

**Comment by Boy-boy** [comment]
If the user does not know the internal principles, continue to use AutoCommit: True, isn't it the framework not perfect?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/CAP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 中午1:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/CAP] 同一个事务下（自动提交），多次publish会抛异常，事务只能被commit一次 (Issue #1054)





 
autoCommit: false
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiangxiren** [comment]
https://github.com/dotnetcore/CAP/blob/65e0d448b4a09718abd454a7c29098daf856ea1f/src/DotNetCore.CAP.SqlServer/ICapTransaction.SqlServer.cs#L160

autoCommit: true时，调用Publish时就会提交事务，不适用于Publish后还有其他操作的情况。
怎么理解你说的' isn't it the framework not perfect?'

**Comment by Boy-boy** [comment]
从您的回复中，可以了解，我们默认认为publish之后没有其他操作（例如再次publish）。
但是对于使用者来说，若不遵守这个默认行为，此刻框架内部将会抛出异常，是否有更好的优化方案？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/CAP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 下午2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/CAP] 同一个事务下（自动提交），多次publish会抛异常，事务只能被commit一次 (Issue #1054)





 
https://github.com/dotnetcore/CAP/blob/65e0d448b4a09718abd454a7c29098daf856ea1f/src/DotNetCore.CAP.SqlServer/ICapTransaction.SqlServer.cs#L160
 
autoCommit: true时，调用Publish时就会提交事务，不适用于Publish后还有其他操作的情况。
 怎么理解你说的' isn't it the framework not perfect?'
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiangxiren** [comment]
首先，参数注释已经清楚的说明了参数的意义。其次，参数默认值是false即不自动提交事务。如果使用者不使用默认行为而修改为true，那他是否应该在此之前清楚此参数的意义呢？

**Comment by Boy-boy** [comment]
若该框架在执行事务commit方法后，AsyncLocal<ICapTransaction&gt; Transaction设置为null，是否更好？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/CAP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 下午2:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/CAP] 同一个事务下（自动提交），多次publish会抛异常，事务只能被commit一次 (Issue #1054)





 
首先，参数注释已经清楚的说明了参数的意义。其次，参数默认值是false即不自动提交事务。如果使用者不使用默认行为而修改为true，那他是否应该在此之前清楚此参数的意义呢？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiangxiren** [comment]
> 若该框架在执行事务commit方法后，AsyncLocal<ICapTransaction&gt; Transaction设置为null，是否更好？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dotnetcore/CAP" ***@***.***&gt;; 发送时间:&nbsp;2021年12月7日(星期二) 下午2:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [dotnetcore/CAP] 同一个事务下（自动提交），多次publish会抛异常，事务只能被commit一次 (Issue #1054) 首先，参数注释已经清楚的说明了参数的意义。其次，参数默认值是false即不自动提交事务。如果使用者不使用默认行为而修改为true，那他是否应该在此之前清楚此参数的意义呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

这显然不是合理的，设置为null后，后续的业务逻辑使用不到事务，这不符合预期。并且AsyncLocal的值是不会向上传递的，因此在父级任务中Transaction是仍然有值的。
现在的处理的是合理，抛出异常，使用者才会更早的发现使用上的问题，以便于修改。

**Comment by Boy-boy** [comment]
谢谢您，百忙之中解答疑惑，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/CAP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/CAP] 同一个事务下（自动提交），多次publish会抛异常，事务只能被commit一次 (Issue #1054)





  
若该框架在执行事务commit方法后，AsyncLocal<ICapTransaction&gt; Transaction设置为null，是否更好？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dotnetcore/CAP" @.&gt;; 发送时间:&nbsp;2021年12月7日(星期二) 下午2:38 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [dotnetcore/CAP] 同一个事务下（自动提交），多次publish会抛异常，事务只能被commit一次 (Issue #1054) 首先，参数注释已经清楚的说明了参数的意义。其次，参数默认值是false即不自动提交事务。如果使用者不使用默认行为而修改为true，那他是否应该在此之前清楚此参数的意义呢？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
这显然不是合理的，设置为null后，后续的业务逻辑使用不到事务，这不符合预期。并且AsyncLocal的值是不会向上传递的，因此在父级任务中Transaction是仍然有值的。
 现在的处理的是合理，抛出异常，使用者才会更早的发现使用上的问题，以便于修改。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
