### ISSUE TITLE
Where's the place to handle subscriber exception?

### ISSUE THREAD

**Issue by nicholasyin** [dotnetcore/CAP#1055]
It's not caught by the exception handling middleware.

**Comment by yang-xiaodong** [comment]
see https://cap.dotnetcore.xyz/user-guide/en/cap/filter

**Comment by nicholasyin** [comment]
Does it support dependency injection in constructor?

**Comment by yang-xiaodong** [comment]
https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/CAP.Builder.cs#L58

**Comment by nicholasyin** [comment]
What I mean is to retrieve other registered services from the subscriber filter constructor.

**Comment by yang-xiaodong** [comment]
This is the basic behavior of the service that is added to the dependency injection container, which is a basic knowledge

**Comment by nicholasyin** [comment]
会两句英语了不起了你，最多也就是个半罐水。中国的开源社区都是你这种人吗，好好学学吧你。

**Comment by yang-xiaodong** [comment]
@nicholasyin  我看了你的历史发言，那请问你对社区的贡献是什么？

下面是我对你的历史发言得出的结论：
1、只会问问题，而且问的问题都很弱智，往往都需要作者追问才提供进一步信息，连提issue的基本礼仪都不知道。
2、没有对开源社区提供任何贡献和内容的帮助，甚至连一个Start都没有给任何项目。
3、伸手党，不去做任何尝试，别人答案告诉你之后也不想动手，只想直接送到嘴里。
