### ISSUE TITLE
RabbitMQ Streams support

### ISSUE THREAD

**Issue by giorgilekveishvili-meama** [dotnetcore/CAP#1056]
Rabbitmq announced [Streams](https://blog.rabbitmq.com/posts/2021/07/rabbitmq-streams-overview) , will cap support this feature?

**Comment by yang-xiaodong** [comment]
Hello,  

I'm sorry to tell you that  we have no plans to directly support streams for RabbitMQ.

However, If you are willing to create an community extension,  we can add your implement repository to our document for anyone  can find it, you can submit a PR to modify the document here :

https://cap.dotnetcore.xyz/user-guide/en/transport/general/#community-supported-transport-extensions
