### ISSUE TITLE
RabbitMQ同一实例订阅多个主题发送失败

### ISSUE THREAD

**Issue by TangPe** [dotnetcore/CAP#1057]
我同一个实例同时订阅了2个主题(sample.rabbitmq.mysql,sample.CapPublish2)
第一次给sample.rabbitmq.mysql发送消息时能正常消费
第二次给sample.CapPublish2发送消息，没有被消费
第三次在给sample.CapPublish2发送消息时，能正常消费
第四次给sample.rabbitmq.mysql发送消息，数据库显示消费成功，但是实际没有被消费
第五次在给sample.rabbitmq.mysql发送消息能正常消费

这是数据库消费记录
![image](https://user-images.githubusercontent.com/27326690/145980341-b073d311-4bb1-4b8a-bdeb-aafb77199f33.png)

相关配置
![image](https://user-images.githubusercontent.com/27326690/145980503-d10367f7-763f-426a-a08c-261246b8d2ae.png)
![image](https://user-images.githubusercontent.com/27326690/145980565-7426645c-96d8-4e5f-967f-b09c72cbdafa.png)

**Comment by yang-xiaodong** [comment]
Please show the logs

**Comment by TangPe** [comment]
![image](https://user-images.githubusercontent.com/27326690/146108716-a6b3ff25-cdc3-455d-8d01-70cc4a51af6f.png)
Failed这里没有进断点，而且控制台也没有日志输出

**Comment by TangPe** [comment]
![image](https://user-images.githubusercontent.com/27326690/146111170-7fcf4714-043f-41d7-aedc-1e6dcf4c69a3.png)
还有一个问题，我第一次发布的时候，订阅程序没有执行，但是数据库显示接收成功，第二次发布的时候，订阅程序才执行，代码是这样的
![image](https://user-images.githubusercontent.com/27326690/146111336-92597962-2159-40e3-8493-2e97498834fb.png)
![image](https://user-images.githubusercontent.com/27326690/146111382-d3993da9-32f1-41da-8e0c-33fc7d32f172.png)

**Comment by yang-xiaodong** [comment]
> 第二次给sample.CapPublish2发送消息，没有被消费

I can't reproduce it, please give your error log, or clean up your RabbitMQ and retest

**Comment by TangPe** [comment]
我把Exchange和Queue删了之后，重新运行就没问题了
