### ISSUE TITLE
How to remove the suffix ".v1" of group name?

### ISSUE THREAD

**Issue by KongCon** [dotnetcore/CAP#1059]
打扰了，请问如何删除消费者中使用的group自动生成的后缀".v1"，或者如何修改这个默认值？

**Comment by yang-xiaodong** [comment]
Not support, This is required for versioning features

**Comment by KongCon** [comment]
好的，谢谢。主要是在使用阿里云的kafka产品的时候，对groupid的名称进行了限制，不可以使用.符号来创建。
阿里云kafka创建groupid:长度限制为 3 ~ 64 个字符，只能包含英文、数字、短横线（-）以及下划线（_），且至少包含一个英文或数字。
