### ISSUE TITLE
can i only use cap to subscribe topic?

### ISSUE THREAD

**Issue by walkmiao** [dotnetcore/CAP#1060]
i only use cap to subscribe topic,when i use kafka tools  to publish msg  to kafka topic,throw an error 。can i only use cap to subscribe topic without use customheader? thanks!

**Comment by yang-xiaodong** [comment]
Yes, see : https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#heterogeneous-system-integration

**Comment by walkmiao** [comment]
> Yes, see : https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#heterogeneous-system-integration

it works!thanks very much!
