### ISSUE TITLE
Azure Service Bus - How can I publish messages to multiple topics 

### ISSUE THREAD

**Issue by BBanoth** [dotnetcore/CAP#1064]
Hi

I am using Azure Service Bus as Transport.
As far I understand, can publish to only single topic from one application.

Publishing to multiple topics is possible with CAP ?

**Comment by yang-xiaodong** [comment]
An event is commonly published to a single topic and doesn’t need to be published to two. When a need is to fan out that event, , you could set up a subscription on the topic used group name.

Could you elaborate on what you are trying to achieve and how publishing to multiple topics would help your case?

**Comment by yang-xiaodong** [comment]
No response, closed!

**Comment by jonekdahl** [comment]
@yang-xiaodong Like the OP, I would like to know if it is possible to publish to multiple topics.

> An event is commonly published to a single topic and doesn’t need to be published to two.

For a single event, I would agree. However, my use case is that one type of event needs to be published to topic A, while another type of event needs be published to topic B. So I'm not looking for a way to fan out a single event to multiple subscribers, but some way to tell CAP how to route message in each case.

AFAICT, this would require setting up multiple instances of CAP with a database schema for each instance, which seems doable but not very convenient.

**Comment by yang-xiaodong** [comment]
@jonekdahl    The message name is the **Topic**, So you can publish twice. 

```
_cap.Publishe("Topic A", one type);
_cap.Publishe("Topic B", another type);
```

But I don't think you mean that, If you mean send the message to a different database or broker in one service, we currently do not provide direct support for publish one message to different database or broker, but there is a way to achieve it, you can check this comment to get details
[#998 (comment)](https://github.com/dotnetcore/CAP/issues/998#issuecomment-988659781)

**Comment by jonekdahl** [comment]
@yang-xiaodong The `name` parameter of the Publish method is described as _"the topic name or exchange router key"_ but using different names doesn't actually cause messages to be published to different Service Bus topics. The Service Bus transport only uses the name [as the message label](https://github.com/dotnetcore/CAP/blob/a67f9bc9ee33444a90ffd2a3cac578f5b7ffefea/src/DotNetCore.CAP.AzureServiceBus/ITransport.AzureServiceBus.cs#L45), using the configured [TopicPath](https://github.com/dotnetcore/CAP/blob/a67f9bc9ee33444a90ffd2a3cac578f5b7ffefea/src/DotNetCore.CAP.AzureServiceBus/ITransport.AzureServiceBus.cs#L92) for all messages.

I think #1074 is asking for the same thing and it looks like it has a draft PR that introduces a new message header to allow overriding the topic path.
