### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by c5racing** [dotnetcore/CAP#1069]
When submitting multiple messages in a transaction, Exception:

at DotNetCore.CAP.PostgreSql.DbConnectionExtensions.ExecuteNonQuery(IDbConnection connection, String sql, IDbTransaction transaction, Object[] sqlParams)

Here is sample code:

```
  [Route("~/ef/transaction")]
    public IActionResult EntityFrameworkWithTransaction([FromServices]AppDbContext dbContext)
    {
        using (var trans = dbContext.Database.BeginTransaction(_capBus, autoCommit: true))
        {
            //your business logic code

            _capBus.Publish("xxx.services.show.time", DateTime.Now);
            _capBus.Publish("xxx.services.show.time", DateTime.Now);
        }

        return Ok();
    }
```

The error occurs at the second publish.  If it's not wrapped in a transaction, no error occurs

**Comment by xiangxiren** [comment]
`autoCommit: false`
And Commit transaction manually；

**Comment by yang-xiaodong** [comment]
Setting `AutoCommit = true` means commit the transaction on publish, if you need to send multiple events, you need to switch to committing the transaction manually because we can't detect when the transaction needs to be committed
