### ISSUE TITLE
Share the same SQL server as CAP storage for multiple services

### ISSUE THREAD

**Issue by waterydan** [dotnetcore/CAP#1070]
Hi, I'm wondering if it's a good practice to share the same message storage for multiple services using CAP? For example, some of our microservices doesn't have a database, it just receives messages from azure service bus and process them. Can I just create a centralised SQL server as CAP message store and share them between these services? 

Thanks

**Comment by yang-xiaodong** [comment]
Yes, You can use `TableNamePrefix` option to specify that each service uses the different table.

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddCap(x =>
    {
        x.UseKafka("");
        x.UseMySql(opt =>
        {
            opt.ConnectionString = "connection string";
            opt.TableNamePrefix = "appone"; // different table name prefix here
        });
    });
}
```

**Comment by waterydan** [comment]
That worked perfectly. Thanks!

**Comment by dengyangxi** [comment]
@yang-xiaodong  
Does Microsoft's SQL Server support custom table prefixes         
TableNamePrefix
