### ISSUE TITLE
Cap tables are not created in sql server

### ISSUE THREAD

**Issue by ramanitha** [dotnetcore/CAP#1073]

**Comment by yang-xiaodong** [comment]
Closed by https://zhuanlan.zhihu.com/p/25795393

**Comment by nf313743** [comment]
Note that if it's a console app you will been to call the bootstrapper to invoke table creation:
https://github.com/dotnetcore/CAP/blob/6f0901b5feb05d4f3e81f20cd29ac43efd19878d/samples/Sample.ConsoleApp/Program.cs#L32
