### ISSUE TITLE
Enhancement - Dashboard - Support multiple applications

### ISSUE THREAD

**Issue by yiliu-tc** [dotnetcore/CAP#1075]
Dashboard feature is great feature in CAP, however, with current design, Dashboard is embedded inside app. 

To extend this feature, is it possible that we could add multiple applications supporting in dashboard feature. An good example to show how we can monitor messaging for multiple applications could be very nice.

**Comment by yang-xiaodong** [comment]
Supported, to view multiple applications, you need to configure a dependency on Consul for service discovery

see https://cap.dotnetcore.xyz/user-guide/en/monitoring/consul/
