### ISSUE TITLE
CAP Dashboard Authentication Bug - Challenge does not get triggered

### ISSUE THREAD

**Issue by gmishev02** [dotnetcore/CAP#1077]
Use ChallengeOnAuth and the DefaultChallengeScheme do not work when the user accessing the Dashboard is not authenticated.

      
            var isAuthenticated = context.User?.Identity?.IsAuthenticated;
            if (isAuthenticated == false && options.UseChallengeOnAuth)
            {
                await context.ChallengeAsync(options.DefaultChallengeScheme);

                return false;
            }

The problem is that the response status code always gets set to 401, even when a challenge gets fired.

                                if (!await Authentication(request.HttpContext, options))
                                {
                                    response.StatusCode = StatusCodes.Status401Unauthorized;
                                    return;
                                }

The overriding of the response status code stops the challenge from firing.

Possible solution might be to set the response.StatusCode to 401 directly in the Authentication method and only in the case that the Challenge does not get triggered.

**Comment by yang-xiaodong** [comment]
Fixed in v6.0.1
