### ISSUE TITLE
Incorrect messages order after kafka restart

### ISSUE THREAD

**Issue by amal7dp** [dotnetcore/CAP#1078]
The problem is related to stopping kafka.
After kafka is restored, messages with one topic with the Failed and Scheduled statuses accumulated in the repository in the published table are sent to kafka in the wrong order. Later Scheduled ones leave earlier than earlier Failed ones.
It is important for us not to lose any messages and that they are in the order in which they were created.

**Comment by yang-xiaodong** [comment]
Assess whether this is expected based on your scenario, retry thread to pick up messages with status `Scheduled` and `Failed` 4 minutes ago, maybe messages with status `Scheduled` are not picked up within 4 minutes, and the status is  `Failed` messages are picked up for more than 4 minutes, which will cause messages that exceed the time to be sent early.

Usually message-based architecture does not strictly guarantee messages sequence. #29 
If you need to strictly guarantee the order, I have a question, if a message sent fails, do you want to prevent all subsequent messages from being sent?

**Comment by amal7dp** [comment]
If I understood your case correctly, the error is also repeated.

Kafka guarantees the correct order of messages in one partition of one topic. For this case we need to receive messages in the correct order. Yes, we need this behavior, if one message is failed, the next one should not be processed until this message is succeded.

**Comment by amal7dp** [comment]
Hello. Are there any plans to implement our case?

**Comment by yang-xiaodong** [comment]
Hello, this is not in our plan to achieve
