### ISSUE TITLE
Message database persistance question

### ISSUE THREAD

**Issue by waterydan** [dotnetcore/CAP#1079]
Hi, I'd like to know how long does the messages get persisted in db? Is it possible to define the number of days the messages are kept after processing?
Thanks!

**Comment by yang-xiaodong** [comment]
Hi,  please see https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#data-cleanup

**Comment by waterydan** [comment]
Great, that answers my question... Cheers
