### ISSUE TITLE
Problem with publish event from a microservice and subscribe this event in another microservice

### ISSUE THREAD

**Issue by meysamhadeli** [dotnetcore/CAP#1082]
I have a problem with publish message and my consumer doesn't fire in another microservices! 
But this consumer work if be in own microservices like cap documentation!

`microservice 1 - publisher`
```csharp
 public async Task<ActionResult> CreateFlight([FromBody] CreateFlightCommand command, CancellationToken cancellationToken)
    {
        await _capPublisher.PublishAsync("test", DateTime.Now, cancellationToken: cancellationToken);

        return Ok();
    }
```
`microservice 2 - subscriber`
```csharp
public class SubscriberService: ICapSubscribe
{
    [CapSubscribe("test")]
    public void CheckReceivedMessage(DateTime datetime)
    {
        Console.WriteLine(datetime);
    }
}
```

**Comment by yang-xiaodong** [comment]
Can't get a valid judgment from the information you provided, you can try to run our example

**Comment by meysamhadeli** [comment]
> Can't get a valid judgment from the information you provided, you can try to run our example

I try again and it's work! 
Thanks.
