### ISSUE TITLE
Feature requests for `SubscribeFilter`

### ISSUE THREAD

**Issue by 3ldar** [dotnetcore/CAP#1086]
Hi,

`SubscribeFilter` is a nice addition to this great library. But I think it requires 2 crucial features:

1. an async version of SubscribeFilter. So we can execute async code inside.
2. Allow manipulation of control flow. As mentioned in the documents it is similar to ASP.NET MVC filters it would be nice to control whether a subscribe method is invoked or not as in action filters. Now I'm continuing followed workaround: Throw an exception from `OnSubscribeExecuting` and `ExceptionHandled` to `true` on `OnSubscribeException` so it bypasses the execution and prevents it from being processed again. But if that has a callback it will be fired no matter what. So in short it would be nice to have granular control over the Subscriber and Callback methods invocation.

**Comment by yang-xiaodong** [comment]
Hi,

> 2. Allow manipulation of control flow

Do you means like  ASP.NET MVC asynchronous filters  [`On-Stage-ExecutionAsync`](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-6.0#implementation) method?

```C#
public class SampleAsyncActionFilter : IAsyncActionFilter
{
    public async Task OnActionExecutionAsync(
        ActionExecutingContext context, ActionExecutionDelegate next)
    {
        // Do something before the action executes.
        await next();
        // Do something after the action executes.
    }
}
```
We provide `ActionExecutionDelegate` `next` which executes the subscriber method?

**Comment by 3ldar** [comment]
> Do you means like ASP.NET MVC asynchronous filters [`On-Stage-ExecutionAsync`](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-6.0#implementation) method?
> 
> We provide `ActionExecutionDelegate` `next` which executes the subscriber method?

Well, that might be too complex for now, as for ASP.NET there is a very complex pipeline but here we only execute a few steps (Execute the subscriber method and then publish a callback if exists). We might add a property on `ExecutingContext` and check it to skip further steps. If you plan to make the Subscriber Invocation more complex in the future your suggestion would be way more elegant than this.

**Comment by yang-xiaodong** [comment]
Aha, I see what you mean. yes, we ignored the problem when publish a callback if exists.

For now, I think you should have found a workaround to avoid the call by removing the callbackname header.

````cs
context.DeliverMessage.Headers.Remove(Headers.CallbackName);
````

Um..., It does need to be a more elegant way, let me think about it.  :)

If you have a good way, PR is welcome!
