### ISSUE TITLE
Api 水平扩容后的疑问

### ISSUE THREAD

**Issue by zivfuture** [dotnetcore/CAP#1090]
CAP是个不错的项目，但有个疑问还请解答，直接整中文了，
CAP会定时轮循需要重试的消息，但在API在水平扩容后（比如K8S）会有多个相同实例的进程，  进而有多个进程轮循同一个DB，这样是否会有问题？
1.同一个需要重试的消息可能同时会被多个进程拿到并重发， 这样增加了重发的概率（虽然有幂等）
2.多个进程轮循同一个表会对DB造成压力和资源浪费，按道理需要重试的数据由其中一个进程重发即可

感谢！

**Comment by yang-xiaodong** [comment]
Duplicate of #671,
please see the comment: https://github.com/dotnetcore/CAP/pull/671#issuecomment-697071575

**Comment by zivfuture** [comment]
> Duplicate of #671, 1、please see the comment: [#671 (comment)](https://github.com/dotnetcore/CAP/pull/671#issuecomment-697071575) 2、1分钟一次的轮询不会照成任何压力，就算有5个实例，平均也才20秒，DB对此毫无压力

thx!
