### ISSUE TITLE
How to implement authorization in the dashboard module

### ISSUE THREAD

**Issue by albertopm19** [dotnetcore/CAP#1097]
Thanks for this great library.

We are implementing it in our microservices and we understand how to authenticate users with the dashboard module, but... How can we limit their access, that is, how can we say who can access it specifically?
In the example it only shows how to configure the authentication but not the authorization to limit access to specific users of a company....

Thank you very much!!

**Comment by albertopm19** [comment]
Thank you very much for the suggestion, we will see if it can be applied to our SSO or we have to apply another alternative.

We will write down the final result in the incidence in case it can be useful for other companies

Once again, thank you very much for your work :)

**Comment by albertopm19** [comment]
We are testing  with the Auth example and our Identity server with this config:

        Startup.cs
		
       public void ConfigureServices(IServiceCollection services)
        {
            services
               .AddAuthorization()
               .AddAuthentication(options =>
               {
                   options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                   options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
               })
               .AddCookie()
               .AddOpenIdConnect(options =>
               {
                   options.Authority = "https://idsd.ifema.es/";
                   options.ClientId = "AdminCAPPrueba";
                   options.ClientSecret = "xxxxxxxxxx";
                   options.ResponseType = "code";
                   options.UsePkce = true;
                   options.Scope.Clear();
                   options.Scope.Add("openid");
                   options.Scope.Add("profile");                   
               });

            services.AddCap(cap =>
            {
                cap.UseDashboard(d =>
                {
                    d.UseChallengeOnAuth = true;
                    d.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                    d.UseAuth = true;
                    //d.DefaultAuthenticationScheme = "MyDashboardScheme";
                });
                cap.UseInMemoryStorage();
                cap.UseInMemoryMessageQueue();
            });

            services.AddControllers();
        }
		
		public void Configure(IApplicationBuilder app)
        {            
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseCookiePolicy();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }

But it does not work because the authentication is not being launched against our identity server. 

If we change the code of 

CAP.BuilderExtension.cs to this
		
	    internal static async Task<bool> Authentication(HttpContext context, DashboardOptions options)
        {
            if (options.UseAuth)
            {
                var result = await context.AuthenticateAsync(options.DefaultAuthenticationScheme);

                if (result.Succeeded && result.Principal != null)
                {
                    context.User = result.Principal;
                }
                // we have to comment these lines
                //else
                //{
                //    return false;
                //}
            }

            var isAuthenticated = context.User?.Identity?.IsAuthenticated;

            if (isAuthenticated == false && options.UseChallengeOnAuth)
            {
                await context.ChallengeAsync(options.DefaultChallengeScheme);
                await context.Response.CompleteAsync();

                return false;
            }

            return true;
        } 

now is working well.... Is this a bug or we are doing anything bad ?.

Thanks!!!

**Comment by yang-xiaodong** [comment]
Oh, I think It's a bug. Challenge should be executed first, I released a preview version to fix this in a few minutes ago.

You can test it with the version `6.1.0-preview-163077268`.

**Comment by albertopm19** [comment]
ok, ahora se entiende mejor el proceso.
Hemos probado el parche y funciona.
Muchas gracias!!
Seguimos con las alternativas de autorizacion y lo añadiremos a esta incidencia si te parece bien....
