### ISSUE TITLE
Why can't the exchangetype be modified?

### ISSUE THREAD

**Issue by shuangbaojun** [dotnetcore/CAP#1098]
Why can't the exchangetype be modified? Some business scenarios need to be dynamically set to direct, top, fanout, etc., as shown in the following figure:

![image](https://user-images.githubusercontent.com/64063254/156385754-b135c5c0-3ffa-431e-823c-fb6832b36aab.png)

**Comment by yang-xiaodong** [comment]
We don't support change ExcahgneType,  `Topic` type is CAP needs.
