### ISSUE TITLE
Question about transaction in consumer side

### ISSUE THREAD

**Issue by goodluckily** [dotnetcore/CAP#1099]
1.可能是我没理解透,或者我的使用错误
2.整体代码截图如下:
![image](https://user-images.githubusercontent.com/50984404/156750348-7104deb8-6de4-4c58-9587-67a3b3e8bde6.png)

![image](https://user-images.githubusercontent.com/50984404/156750470-b3e52df0-b4cd-4366-a462-95e1923de79c.png)

**疑问如下:**

问题一:为何我消费都失败了,在事物里面还是能 添加进去数据呢?  
1.是要我确定 **testSubCap1** 这里面的方法一定得是成功的吗?

问题二:这个失败重试间隔(FailedRetryInterval),如果我不需要这个,我该怎么设置,当我设置0时,是报错的
![image](https://user-images.githubusercontent.com/50984404/156750950-1f49418d-0144-4bb6-873c-b069af166cdb.png)

**Comment by yang-xiaodong** [comment]
消费端没有事务或需要[自己开启](https://www.cnblogs.com/savorboard/p/cap-auto-transaction.html#%E6%B6%88%E8%B4%B9%E7%AB%AF%E4%BA%8B%E5%8A%A1)，查看Readme架构图了解

**Comment by goodluckily** [comment]
好的 谢谢 谢谢 我看到您所提供的文章了,
我理解了  (消费者主要是通过SubscribeFilter过滤器对_dbContext一些回滚,提交之类的操作)

**Comment by goodluckily** [comment]
FailedRetryCount设置为0 我尝试过,项目跑不起来,所以我才改为int.MaxValue (当然确定可以的话,我明天再去试试)

**Comment by goodluckily** [comment]
您好, 如果我只想失败重试,但是我不想再次之后,再去间隔轮询跑这个失败的方法,  这个 FailedRetryCount 如何取消掉?
![image](https://user-images.githubusercontent.com/50984404/156863099-8f8b904f-8d5d-4559-8f44-67c44cdf851b.png)

**Comment by goodluckily** [comment]
不对呀 我按照你的 [消费端处理事务的方法](https://www.cnblogs.com/savorboard/p/cap-auto-transaction.html#%E6%B6%88%E8%B4%B9%E7%AB%AF%E4%BA%8B%E5%8A%A1) 还是没解决 在同一个Action 里面,如果我最后提交的消费端事件报错了,那么我的数据库SaveChanges()提交的数据,还是没回滚呀?

**Comment by yang-xiaodong** [comment]
> 不对呀 我按照你的 [消费端处理事务的方法](https://www.cnblogs.com/savorboard/p/cap-auto-transaction.html#%E6%B6%88%E8%B4%B9%E7%AB%AF%E4%BA%8B%E5%8A%A1) 还是没解决 在同一个Action 里面,如果我最后提交的消费端事件报错了,那么我的数据库SaveChanges()提交的数据,还是没回滚呀?

建议查看自己的代码，这已经和CAP没有关系了，在CAP只有发布端才有事务
