### ISSUE TITLE
Please add support for new MongoDb 4.4 Transactions getting WriteConflict error

### ISSUE THREAD

**Issue by devgig** [dotnetcore/CAP#1102]
The following article explains the issue.

https://finisky.github.io/2021/02/20/mongodbretrytransaction.en/#:~:text=The%20situation%20becomes%20worse%20in%20multi-document%20transaction%20which,write%20conflict%20happens%2C%20a%20MongoDBCommandException%20will%20be%20thrown%3A

**Comment by yang-xiaodong** [comment]
Hello, 

It seems that the error needs to be retried to resolve , Since Mongo.Drive uses `TransactionExecutor` to retry and the object is  `internal`, so we can't use it  directly. We recommend you manual retry, catch exception and retry in user code or use Polly to simplify code.
