### ISSUE TITLE
生产消息成功，但是没有订阅记录

### ISSUE THREAD

**Issue by cdefg198** [dotnetcore/CAP#1106]
我在测试环境和生产环境已经使用了很长一段时间，但是今天生产出现了一个问题，
我使用的是sqlserver和redis，多个生产者站点，一个订阅者站点，
今天的问题：
在生产者cap.Published中有记录，并且StatusName为Succeeded,
但是在消费者cap.Received中没有记录，redis里面有记录，
导致业务数据没有处理成功，然后我重启了订阅者站点，重新生产消息，新的消息正常处理了(旧的消息没有处理，因为cap.Published里面旧的消息状态已经是succeeded)，不知道什么情况。
麻烦抽空分析一下，谢谢。

**Comment by cdefg198** [comment]
1、数据库服务器每天凌晨4点会重启，这段时间会出现告警DotNetCore.CAP.Processor.MessageNeedToRetryProcessor，连不上数据库；
2、消费者站点每天凌晨5点回收应用程序池，今天回收时间节点出现异常，以前没关注过是否也出现

1. DotNetCore.CAP.RedisStreams.AsyncLazyRedisConnection：Server replied with error, BUSYGROUP Consumer Group name already exists, for endpoint
2. DotNetCore.CAP.Internal.ConsumerRegister：BUSYGROUP Consumer Group name already exists

**Comment by yang-xiaodong** [comment]
Hello, according to the information you provided, we cannot analyze it, it seems that it is caused by external reasons

If you think it's a CAP problem, please provide reproducible steps

**Comment by yang-xiaodong** [comment]
No response, closed!

**Comment by cdefg198** [comment]
大佬，这个问题在生产环境又重现了一次。
1、使用环境：IIS10、CAP 6.0.1、CAP.RedisStreams 6.0.1、CAP.SqlServer 6.0.1
2、CAP消费网站应用程序池每天凌晨5点回收加自启动
3、出现异常：
3.1   DotNetCore.CAP.RedisStreams.AsyncLazyRedisConnection：Server replied with error, BUSYGROUP Consumer Group name already exists, for endpoint
3.2   DotNetCore.CAP.Internal.ConsumerRegister：BUSYGROUP Consumer Group name already exists
4、出现问题：
CAP站点是正常启动的，在生产者cap.Published中有记录，并且StatusName为Succeeded,
但是在消费者cap.Received中没有记录，redis里面有记录，
导致业务数据没有处理成功，然后我重启了消费端站点，就正常了。
