### ISSUE TITLE
Any plan to support CloudEvents specification?

### ISSUE THREAD

**Issue by IlSocio** [dotnetcore/CAP#1109]
I'm wondering if there is any plan to adopt the cloudevents specification in the future: 
https://cloudevents.io/
https://github.com/cloudevents/sdk-csharp

By leveraging a common specification for the event-format, like cloudevents, we could improve interoperability across different libraries and technologies.
For instance, even if the subscriber side is java based, we could still use CAP on the publishing side and benefit from the outbox pattern.

**Comment by yang-xiaodong** [comment]
> For instance, even if the subscriber side is java based, we could still use CAP on the publishing side and benefit from the outbox pattern.

It‘s supported now , see https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#heterogeneous-system-integration

**Comment by IlSocio** [comment]
Thanks, I'll check it out
