### ISSUE TITLE
Question about upgrade from version 2.6 to 3.1

### ISSUE THREAD

**Issue by kisshexuxia** [dotnetcore/CAP#1111]
我们现在把cap版本从2.6升级到3.1
是不是要同时把所有微服务都一起升级到一个版本。
我现在发布的微服务还是2.6，接收的微服务升级到了3.1，发现接收表Cap.Received无数据。
后面去分析了下新版本3.1发送的Content和2.6的JOSN格式不一样。是不是造成接收服务解析失败。

**Comment by yang-xiaodong** [comment]
Yes, In this version, we have made major improvements to the code structure, which have introduced some destructive changes.

see https://github.com/dotnetcore/CAP/releases/tag/v3.0.0
