### ISSUE TITLE
Support .net core authorization in CAP Dasboard UI

### ISSUE THREAD

**Issue by albertopm19** [dotnetcore/CAP#1112]
Hello,

In order to securely use CAP Dashboard in our company, we needed to be able to use the .net authorization system, as we only use our identity server to authenticate company users.

This is a proposed change to be able to use the standard .net authorization system with CAP Dashboard.

If it seems good to you, we upload a change proposal to incorporate it as an improvement to the library.

In summary, we have added a new property to CAP DashboardOptions "AuthorizationPolicy"

and we have modified CAP.BuilderExtension.cs to include calls to the .net core authorization service in the api.

If it seems good to you, we can upload a change proposal to incorporate it as an improvement to the library. 

CAP.BuilderExtension.cs

// Copyright (c) .NET Core Community. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System;
using System.Reflection;
using System.Threading.Tasks;
using DotNetCore.CAP.Dashboard;
using DotNetCore.CAP.Dashboard.GatewayProxy;
using DotNetCore.CAP.Dashboard.NodeDiscovery;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Internal;
using Microsoft.Extensions.Options;

// ReSharper disable once CheckNamespace
namespace DotNetCore.CAP
{
    public static class CapBuilderExtension
    {
        public static IApplicationBuilder UseCapDashboard(this IApplicationBuilder app)
        {
            if (app == null)
            {
                throw new ArgumentNullException(nameof(app));
            }

            var provider = app.ApplicationServices;

            var options = provider.GetService<DashboardOptions>();
            if (options != null)
            {
                if (provider.GetService<DiscoveryOptions>() != null)
                {
                    app.UseMiddleware<GatewayProxyMiddleware>();
                }

                app.UseMiddleware<UiMiddleware>();

                app.Map(options.PathMatch + "/api", false, x =>
                {

                    IAuthorizationService authService = null;
                    if (!String.IsNullOrEmpty(options.AuthorizationPolicy))
                    {
                        authService= app.ApplicationServices.GetService<IAuthorizationService>();
                    }
                    
                    var builder = new RouteBuilder(x);

                    var methods = typeof(RouteActionProvider).GetMethods(BindingFlags.Instance | BindingFlags.Public);

                    foreach (var method in methods)
                    {
                        var executor = ObjectMethodExecutor.Create(method, typeof(RouteActionProvider).GetTypeInfo());

                        var getAttr = method.GetCustomAttribute<HttpGetAttribute>();
                        if (getAttr != null)
                        {

                            builder.MapGet(getAttr.Template, async (request, response, data) =>
                            {
                                if (!await Authentication(request.HttpContext, options))
                                {
                                    response.StatusCode = StatusCodes.Status401Unauthorized;
                                    return;
                                }

                                if (!await Authorize(request, response, options, authService))
                                {
                                    response.StatusCode = StatusCodes.Status401Unauthorized;
                                    return;
                                }

                                var actionProvider = new RouteActionProvider(request, response, data);
                                try
                                {
                                    await executor.ExecuteAsync(actionProvider, null);
                                }
                                catch (Exception ex)
                                {
                                    response.StatusCode = StatusCodes.Status500InternalServerError;
                                    await response.WriteAsync(ex.Message);
                                }
                            }); 
                        }

                        var postAttr = method.GetCustomAttribute<HttpPostAttribute>();
                        if (postAttr != null)
                        {
                            builder.MapPost(postAttr.Template, async (request, response, data) =>
                            {
                                if (!await Authentication(request.HttpContext, options))
                                {
                                    response.StatusCode = StatusCodes.Status401Unauthorized;
                                    return;
                                }

                                if (!await Authorize(request, response, options,authService))
                                {
                                     response.StatusCode = StatusCodes.Status401Unauthorized;
                                     return;
                                }

                                var actionProvider = new RouteActionProvider(request, response, data);
                                try
                                {
                                    await executor.ExecuteAsync(actionProvider, null);
                                }
                                catch (Exception ex)
                                {
                                    response.StatusCode = StatusCodes.Status500InternalServerError;
                                    await response.WriteAsync(ex.Message);
                                }
                            });
                        }
                    }

                    var capRouter = builder.Build();

                    x.UseRouter(capRouter);
                }); 
            }

            return app;
        }

        internal static async Task<bool> Authentication(HttpContext context, DashboardOptions options)
        {
            var isAuthenticated = context.User?.Identity?.IsAuthenticated;

            if (isAuthenticated == false && options.UseChallengeOnAuth)
            {
                await context.ChallengeAsync(options.DefaultChallengeScheme);
                await context.Response.CompleteAsync();
                return false;
            }

            if (isAuthenticated == false && options.UseAuth)
            {
                var result = await context.AuthenticateAsync(options.DefaultAuthenticationScheme);

                if (result.Succeeded && result.Principal != null)
                {
                    //If a cookie scheme is configured, the authentication result will be placed in a cookie to avoid re-authentication
                    var defaultOptions = context.RequestServices.GetService<IOptions<AuthenticationOptions>>();
                    if (defaultOptions != null && defaultOptions.Value.DefaultScheme == CookieAuthenticationDefaults.AuthenticationScheme)
                    {
                        await context.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, result.Principal);
                    }
                }
                else
                {
                    return false;
                }
            }

            return true;
        }

        internal static async Task<bool> Authorize(HttpRequest request, HttpResponse response,DashboardOptions options, IAuthorizationService authservice)
        {
            if (!String.IsNullOrEmpty(options.AuthorizationPolicy)&&(authservice!=null))
            {
                AuthorizationResult authorizationResult = await authservice.AuthorizeAsync(request.HttpContext.User, null, options.AuthorizationPolicy);
                if (!authorizationResult.Succeeded)
                {
                    return false;
                }
            }
            return true;
        }

    }
}

CAP.DashboardOptions.cs

// Copyright (c) .NET Core Community. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

// ReSharper disable once CheckNamespace

namespace DotNetCore.CAP
{
    public class DashboardOptions
    {
        public DashboardOptions()
        {
            PathMatch = "/cap";
            StatsPollingInterval = 2000;
        }

        /// <summary>
        /// When behind the proxy, specify the base path to allow spa call prefix.
        /// </summary>
        public string PathBase { get; set; }

        /// <summary>
        /// Path prefix to match from url path.
        /// </summary>
        public string PathMatch { get; set; }

        /// <summary>
        /// The interval the /stats endpoint should be polled with.
        /// </summary>
        public int StatsPollingInterval { get; set; }

        /// <summary>
        /// Enable authentication on dashboard request.
        /// </summary>
        public bool UseAuth { get; set; }

        /// <summary>
        /// Default scheme used for authentication. If no scheme is set, the DefaultScheme set up in AddAuthentication will be used.
        /// </summary>
        public string DefaultAuthenticationScheme { get; set; }

        /// <summary>
        /// Enable authentication challenge on dashboard request.
        /// </summary>
        public bool UseChallengeOnAuth { get; set; }

        /// <summary>
        /// Default scheme used for authentication challenge. If no scheme is set, the DefaultChallengeScheme set up in AddAuthentication will be used.
        /// </summary>
        public string DefaultChallengeScheme { get; set; }

        /// <summary>
        /// Authorization policy. If no policy is set, authorization will be inactive.
        /// </summary>
        public string AuthorizationPolicy { get; set; }

    }
}

**Comment by yang-xiaodong** [comment]
No, we're not going to provide a role or policy-based authorization model like ASP.NET Core, which complicates things with fine-grained control over the API for CAP.   We think if you have access to dashboard, then you can do anything.

**Comment by albertopm19** [comment]
Yes, of course if someone can access the dashboard they should be able to do everything, that's why we only propose the configuration of an access policy.

The problem that we have in our company and I imagine that in others as well, is that all employees are authenticated with our identity server, but only a few are administrators.

And we only use our identity server to authenticate users.

Once the identity of the user has been verified, each application checks whether the user has access to the required functionality.

The standard way in .net core to check if a user is authorized or not to access a feature is with the authorization service.

And that is why we propose this improvement to be able to use the CAP library, because we cannot allow any employee of the company to access the dashboard.

thanks for your help !!

**Comment by yang-xiaodong** [comment]
I just noticed this is a continuation of #1097,  okay, I choose to agree with you.  

Would you like to submit a PR?

**Comment by albertopm19** [comment]
ok, we will prepare the pr as soon as possible on the latest version of the library.

Once again thank you very much for your work and your help :) !!!

**Comment by yang-xiaodong** [comment]
Fixed in `6.1.0-preview-165373954`
