### ISSUE TITLE
Using Dispatcher in BusPublisher

### ISSUE THREAD

**Issue by mehdihadeli** [dotnetcore/CAP#1117]
Hi,
I have a question, 
Why do you use a [Dispatcher](https://github.com/dotnetcore/CAP/blob/9512640bc7f8c1b8a018242f303b5625e3dca509/src/DotNetCore.CAP/Processor/IDispatcher.Default.cs#L125) for sending message in your [CapPublisher](https://github.com/dotnetcore/CAP/blob/9512640bc7f8c1b8a018242f303b5625e3dca509/src/DotNetCore.CAP/Internal/ICapPublisher.Default.cs#L101), instead of directlty send it to broker with using a [Transport](https://github.com/dotnetcore/CAP/blob/9512640bc7f8c1b8a018242f303b5625e3dca509/src/DotNetCore.CAP.RabbitMQ/ITransport.RabbitMQ.cs#L32)?

**Comment by yang-xiaodong** [comment]
Because needs to be committed the transaction before the message can be sent

**Comment by mehdihadeli** [comment]
@yang-xiaodong Thanks
