### ISSUE TITLE
Subscriber can not be found when use ClassLibrary

### ISSUE THREAD

**Issue by charleypeng** [dotnetcore/CAP#1119]
I tried with a sample which created by myself use in-memory settings. It is a standard webapi project. When I put the controllers in the project main file, CAP is doing great and everything is fine,  but when I create a new classlibrary.dll  to put all my controller files together, the CAP now can only publish events, no subscriber showed up. Is this the CAP bug or the NUGET package bug? 

package I use
> <PackageReference Include="DotNetCore.CAP" Version="6.0.1" />
    <PackageReference Include="DotNetCore.CAP.Dashboard" Version="6.0.1" />
    <PackageReference Include="DotNetCore.CAP.InMemoryStorage" Version="6.0.1" />
    <PackageReference Include="Savorboard.CAP.InMemoryMessageQueue" Version="6.0.0" />

**Comment by charleypeng** [comment]
[https://github.com/charleypeng/CAPIssue](url)
this is my project code.  You can copy all the controllers back to main project and then the CAP works fine.

**Comment by charleypeng** [comment]
problem solved  😂
https://github.com/charleypeng/Furion.Extras.CAP

**Comment by yang-xiaodong** [comment]
If the subscribers are distributed among the dependent assemblies, we provide a new API to support finding subscribers from these assemblies.

```
services.AddCap(x =>
{
    //...
}).AddSubscriberAssembly([...assemblies]);
```
