### ISSUE TITLE
String MessageId issue when using MongoDB adapter

### ISSUE THREAD

**Issue by shkarface** [dotnetcore/CAP#1124]
Hello dears,

We're using CAP in a heterogenous system. all our messages are sent using a [CloudEvent ](https://github.com/cloudevents/spec) payload.

We're using UUIDs as our MessageId, but when publishing using the mongodb storage adapter, we have an issue:

```cs
System.FormatException: Input string was not in a correct format
         at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
         at System.Int64.Parse(String s)
         at DotNetCore.CAP.MongoDB.MongoDBDataStorage.StoreMessage(String name, Message content, Object dbTransaction)
```

Looking at the source code, both [ReceivedMessage and PublishedMessage](https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.MongoDB/StorageMessage.cs) classes use `long` number type.

**Comment by yang-xiaodong** [comment]
Hello Shkar,

As you can see, we use SnowflakeId as our message primary key.

If you're using RabbitMQ or Kafka or ASB, you can rewrite it before storing the message after receiving it.

see : https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#custom-headers

**Comment by shkarface** [comment]
Hello dear, 

The issue is not on the receive part because we can simple read it from the body using custom headers function.

The issue is with the publishing, if we publish a message with it's `cap-message-id` being set to a UUID this issue occurs.

**Comment by shkarface** [comment]
On another note, how does cap ensure idempotency in heterogeneous systems?

Imagine a scenario where an event is sent from system **A** with `id` set to **A1B2C3**, and now system **B** is using CAP and consumes this message. since there is no `cap-msg-id` it will generate a new ID for it using snowflake.

When this message is received, even when using a CustomHeaders function to turn `id` into `cap-msg-id`, the internally stored mongodb id is still of type `long` and self generated. so I'm not sure how does it make sure that the same event arriving from system **A** is only received once.

**Comment by yang-xiaodong** [comment]
No need to specify cap-msg-id in Header when publishing, CAP does not guarantee idempotency, it need users to ensure that

https://cap.dotnetcore.xyz/user-guide/en/cap/idempotence/#why-are-we-not-providingachieving-idempotency

**Comment by shkarface** [comment]
@yang-xiaodong what about on the consuming part? how does cap deal with idempotency on receiving end?
