### ISSUE TITLE
在使用netcore下的cap消息框架的时候，发现发送和接收消息容易造成拥堵，1条/1s

### ISSUE THREAD

**Issue by pwm812** [dotnetcore/CAP#1126]
在使用netcore下的cap消息框架的时候，发现发送和接收消息容易造成拥堵。

情况1：publish之后，本地库中待发记录在增多。然后重启应用后，每秒只能发送一条到消息中间件中，原因是cap源码中针对恢复型消息（也就是停机重启后，从数据库查询待发记录表）每处理一条，等待1s。因此积压消息的送出频率1条/s 。 且无法通过修改配置文件的方式调整；

情况2：消费者接收消息中间件的消息后写入本地数据库标记为待处理，然后由调度线程负责调用消费者函数，如果消费者这里处理速度慢，就会造成消息堆积到本地。这时候如果关闭程序重新启动，那么消费者处理消息的频率被设置为1条/s 。

**Comment by pwm812** [comment]
请问这个有办法解决吗？访问量大的时候影响很大。。。。

**Comment by yang-xiaodong** [comment]
所以你的问题都是出现在重启应用，你重启应用的原因是什么？

**Comment by pwm812** [comment]
感谢回复！！其实并没有刻意的去重启应用，我猜测是这样的：因为应用是部署在k8s中，当访问量大的时候会自动伸缩增长为多个pods（相当于多个应用），这时候可能Published表中已经积压了不少数据了，然后访问压力逐渐减少，所以相应的pods也释放了，所以是不是这个原因导致了重启应用一样的效果呢？
还有请问一下，这里每发送一条后需要wait 1s，这是出于什么原因呢？现目前有没有什么办法可以解决这个问题呢？
谢谢！

**Comment by yang-xiaodong** [comment]
由于CAP主要用于处理业务场景，并非ETL等。 所以正常场景下，缓存区应该都是空的，也就是说消息发送速度大于生产速度。

对于你描述的情况，生产速度大于发送速度，就是在缓存区产生堆积，当堆积到一定量的时候就会触发背压机制。此时应用重启会导致缓冲区的数据丢失在重新启动后从数据库拉取，并1s发送一条。

接下来我回答你的问题，或者说我认为你的场景存在的问题。

1、Pod的伸缩，当Pod数量增加时，一切正常。 那么为什么缓冲区还有数据的时候（我认为缓冲区有数据就说明生产压力还是比较大）Pod都会变少呢？ 是否设计或者伸缩策略不合理？ 这不符合正常场景！

2、1s一条其实主要处理的是失败的消息，对于Schedules的消息并不是我们的主要设计策略（不属于正常场景），当应用重启后，如果我们一次性将消息载入内存并进行高频发送，这可能会影响应用的正常吞吐和业务运作，很显然应用中正常的消息需要等待这批消息处理完才能被处理。

**Comment by pwm812** [comment]
感谢解答！！最近在压测，确实应该是生产速度大于了消费速度了，我去试试你说的那两个配置看看有没有帮助。谢谢
