### ISSUE TITLE
关于线性处理可能导致消息阻塞的问题

### ISSUE THREAD

**Issue by gong626035906** [dotnetcore/CAP#1127]
您好

目前项目使用RabbitMq作为消息中间件，期间遇到了一个问题目前没有找到合适的解决方案，遂来请教。

目前定义了多种CapName来区分不同的业务消息，但是默认情况下都使用以程序集命名的Group，并且由于消息处理是线性的，不同的业务消息要求的实时性各不一致，消息的处理速度也各不相同。可能会导致处理速度慢的消息，阻塞了实时性要求高的消息。

想问下有没有什么解决方案可以让不同的消息类型互不干扰嘛。

谢谢！！！

**Comment by gong626035906** [comment]
我尝试了分配不同的GroupName来区分不同的队列，但是后来发现它还是会往默认的Queue里写入数据。

我以为是框架会一直往默认的Queue中写入数据，后来发现是因为RabbitMq中原来的Exchange数据还保留在其中，需要手动删除才可以。

**Comment by yang-xiaodong** [comment]
可以设置 `UseDispatchingPerGroup` 

https://cap.dotnetcore.xyz/user-guide/zh/cap/configuration/#usedispatchingpergroup
