### ISSUE TITLE
控制台做消息发布的时候，提示找不到表，但是Web站点中同样只做发布，却可以自动创建表，我想知道应该差了什么命令？

### ISSUE THREAD

**Issue by zhangzw218** [dotnetcore/CAP#1130]
不知道该怎么简化问题描述，我就将整个情况描述一遍，抱歉有点长，期望能有解答：
一开始，我是将发布、订阅等操作，全部配到同一个数据库中，相同的前缀cap，但是偶然的，我遇到了下面的问题：
Message (Name:Serilog.Sinks.MonitorLogInsertEto,Group:cap.queue.console_2.v21) can not be found subscriber.
see: https://github.com/dotnetcore/CAP/issues/63
我先看到了[#63](https://github.com/dotnetcore/CAP/issues/63)的内容，然后关联找到了[#258](https://github.com/dotnetcore/CAP/issues/258)的问题，我觉得我发生的错误，应该就是这个多个实例引用相同的表导致的。
因此就想着拆分，每个实例都链接一个独立的数据表，那么现在就越到一个问题：
我现在有4个实例：Web1发布、Web2发布、Console1发布、Console2订阅。
1、Web1发布，启动的时候，我较早的使用Cap发布消息，这时候提示Table dbName.web_1.published doesn't exist错误，就是这个表不存在，一直到web完全启动，AppInit之后，表创建成功之后，这个错误才会消失。（其实我不确定表是什么时候创建的）
这里面，我关于Cap的代码，除了在ConfigureServices中做配置外，业务上只有一个发布操作： ICapPublisher.PublishAsync(key, eto);

2、Console_1发布，我这个控制台是一个简单的Demo，只做消息发布，一直提示 Table dbName.console_1.published doesn't exist， 永远不会自动创建这个表。
这里业务上也只有一个发布操作： ICapPublisher.PublishAsync(key, eto);
我不知道为什么这个控制台发布，不会自动去创建表。

3、Console_2订阅，这个控制台订阅了Web和Console_1发布所发布的内容，自动创建了2个表，console_2.published 和 console_2.received，消费正常（如果不管Console_1，不去修复的话，就一直只能订阅到Web的消息）
这个订阅服务，和Sample.ConsoleApp 这个差不多，因为订阅正常，就不多描述。

……
问题：
1、上面三个实例，主要针对Console_1做发布的问题，为什么不会自动创建表。我目前是等Console_2运行之后，手动将console_2.published重命名成console_1.published，反正对于console_2来说，发布的表也用不上，但我还是想知道，Cap有没有一个命令可以自动创建表，Web和控制台，为什么一个自动建表而另一个不会。

2、为什么Web端会出现 Message (Name:Serilog.Sinks.MonitorLogInsertEto,Group:cap.queue.console_2.v21) can not be found subscriber. 这个提示，我有点想不通，Web只做发布，应该只关注Key(Group)和交换机才对？不需要在乎订阅（RabbitMQ的队列），这里怎么会在Web提示一个队列的名称出来。
我刚才尝试改回相同的前缀，使用相同的数据表，但已经无法重现这个问题了，三个发布（Web1、Web2、Console1）和一个消费（Console2）使用相同的表运行良好(cap.published 和 cap.received)，不知道触发这个提示的条件是什么？
但是之前一旦触发，就怎么重启Web都没用了，就是会一直提示，一直到我清空了(cap.published 和 cap.received)之后才结束。

……
忘记说版本了，我现在使用的是：
.net 5.0
dotnetcore.cap 5.0.0
不过我看了下从dotnetcore.cap 5.0.0之后的一路更新，应该没有涉及这方面的更新内容？

**Comment by yang-xiaodong** [comment]
1、You need to manually bootstrap the cap in the console app.

see:
https://github.com/dotnetcore/CAP/blob/6f0901b5feb05d4f3e81f20cd29ac43efd19878d/samples/Sample.ConsoleApp/Program.cs#L32

2、Different services require different table prefixe table.

see: https://cap.dotnetcore.xyz/user-guide/zh/samples/faq/
```
section: How to use the same database for different applications?
```

**Comment by zhangzw218** [comment]
多谢，我看到了， sp.GetService<IBootstrapper>().BootstrapAsync();  但我之前一直以为，只有published操作的控制台不需要这个服务。
现在我添加上去之后，数据表可以自动创建了。
……
但我现在遇到了另一个问题：监控要怎么看？现在不同的服务有不同的前缀，Web自己有url地址，可以直接引用Dashboard来观看Web发布和订阅的记录。
但是Web发布、控制台订阅的，那么订阅的一部分因为不同的数据表前缀就看不到了。
控制台这边的数据要怎么看呢，它没有url地址，连注册到Consul都做不到，除非我给开放一个http页面，这方面有比较好的实践方案么。

**Comment by yang-xiaodong** [comment]
Console app does not support dashboard, you can see events in the database table.

**Comment by zhangzw218** [comment]
好的，那就没办法了。
我没有其他问题了。
多谢。
