### ISSUE TITLE
Ability to use Azure Cosmos DB as event storage

### ISSUE THREAD

**Issue by sreagleeye** [dotnetcore/CAP#1131]
Is there any planned support for Azure Cosmos DB as a new database source for event storage? The SDK for Cosmos includes transaction support using a `TransactionalBatch`. The events would have to be saved into the same container and partition key. Processing those events would require some sort of identifier within the document to distinguish the event from the actual entity.

**Comment by yang-xiaodong** [comment]
Hi, Since my Azure subscription has expired, I can't perform the test. so now we don't consider further improvements for Azure unless someone submits PR.

Would you like to create a PR for this?

**Comment by sreagleeye** [comment]
I won't be able to submit a PR any time soon. I am still trying to evaluate different outbox pattern libraries vs creating something custom. I just wanted to get a sense of roadmap.

If I end up writing something that can be adapted for this repo, I'll be sure to submit a PR. In the meantime, I'll close this issue.
