### ISSUE TITLE
Make the default CapPublisher public

### ISSUE THREAD

**Issue by wificlub-code** [dotnetcore/CAP#1132]
最近根据公司项目需求在原有功能基础上进行多租户扩展，但是发现其中有个障碍，先简述一下大概思路。
项目内有一个全局的TenantContext来保存租户信息，用户通过http请求时，会对TenantContext内的属性赋值，以TenantId为例。
计划写一个CapOptions扩展：
public static CapOptions UseMultiTenancy(this CapOptions options)
        {
            options.RegisterExtension(new MultiTenancyCapOptionsExtension());
            return options;
        }
MultiTenancyCapOptionsExtension 类里面通过IServiceCollection注册ISubscribeFilter，每次订阅消息时给TenantId赋值，注册自定义的ICapPublisher并替换原有的CapPublisher，每次发布消息时向headers内写入TenantId值。问题就在这里，发现原有的CapPublisher类无法进行重写，虽然通过以下扩展方法可以解决：
public static Task PublishAsync<T>(this ICapPublisher publisher, T contentObj, IDictionary<string, string> headers, CancellationToken cancellationToken = default)
        {
            var tenantContext = publisher.ServiceProvider.GetService<ITenantContextAccessor>()?.TenantContext;
            headers.Add("TenantId", tenantContext?.TenantId);
            return publisher.PublishAsync(typeof(T).Name, contentObj, headers, cancellationToken);
        }
但是这种做法是非常不好的，当不使用扩展方法进行推送消息时，就无法达到多租户的效果了
所以建议开发团队下一版本把CapPublisher类关键字改为plublic，最好还提供一个可重写的方法方便进行扩展

**Comment by yang-xiaodong** [comment]
You can copy the default implementation and modify it to your needs.

https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/Internal/ICapPublisher.Default.cs

**Comment by wificlub-code** [comment]
此方法尝试过，CapPublisher类依赖CapTransactionBase类的AddToSent方法也是受保护的，如果采用此方法，还必须要自定义ICapTransaction，继承CapTransactionBase来实现,，这样非必要的改动就越来越多了

**Comment by yang-xiaodong** [comment]
see  https://gist.github.com/yang-xiaodong/622a05b081f38d696a8fba100b5ec98c

**Comment by wificlub-code** [comment]
谢谢，目前也只能通过此代理模式解决问题，不过还是希望将来版本支持CapPublisher类的方法重写

**Comment by WangJunZzz** [comment]
@yang-xiaodong  当cap不满足需求，既然提供了接口出来，但是很多internal，外面又不能替换实现了。打个比方，我想重新实现IDataStorage，然后service.replace。很多地方都不做到。

**Comment by yang-xiaodong** [comment]
@WangJunZzz 你别说话说一半，IDataStorage怎么不能重新实现了，不能重新实现那些Storage扩展怎么写出来的。

**Comment by WangJunZzz** [comment]
@yang-xiaodong  扩展storege肯定是可以的。但是假设打个比方我只是单纯的想重写MySqlDataStorage的实现，但是我发现 EFOptions 的2个字段是internal。

**Comment by yang-xiaodong** [comment]
这2个字段就是内部用的，重写MySqlDataStorage用不上。

**Comment by WangJunZzz** [comment]
@yang-xiaodong  我知道是用不上，但是为了以后方便升级，或者你那边以后用上了，我升级了，可能会存在潜在问题。

**Comment by WangJunZzz** [comment]
@yang-xiaodong 打个比方，我不想再源码的基础上扩展一个新的数据库类型的支持，这些internal就导致我某些地方不能和你的标准版本一致。

**Comment by WangJunZzz** [comment]
@yang-xiaodong  这个我们排查一下
