### ISSUE TITLE
Statement problem in creating two default tables

### ISSUE THREAD

**Issue by GITHUBTOXZ** [dotnetcore/CAP#1133]
Cap is connected to opengauss without creating two default tables. After checking the source code, copy the statement to Navicat and execute the prompt:
> CREATE SCHEMA IF NOT EXISTS "gaussdb"
> ERROR:  syntax error at or near "NOT EXISTS"
>LINE 1: CREATE SCHEMA IF NOT EXISTS "gaussdb"

**Comment by yang-xiaodong** [comment]
We're not support opengauss now , this is the supported storages:

https://cap.dotnetcore.xyz/user-guide/en/storage/general/#supported-storages

**Comment by GITHUBTOXZ** [comment]
Opengauss is also a kind of PostgreSQL

**Comment by yang-xiaodong** [comment]
But PostgreSQL is support the sql `CREATE SCHEMA IF NOT EXISTS "gaussdb"`

![image](https://user-images.githubusercontent.com/8205994/168243360-73792503-8c05-48d4-a612-a4af0978d6d1.png)

**Comment by GITHUBTOXZ** [comment]
Opengauss really doesn't support "schema if not exists". I can't help it
![image](https://user-images.githubusercontent.com/40156185/168245426-0afa6b9a-4175-44f1-a633-a00f1b0101da.png)

**Comment by yang-xiaodong** [comment]
see #1026

**Comment by GITHUBTOXZ** [comment]
Hello, cap team, if I put the default two tables created by cap in mongdb and use opengauss database for transactions, will this affect the data consistency
![image](https://user-images.githubusercontent.com/40156185/168742594-2f13bcd3-bdaa-4915-bd00-3e6181714b6c.png)
![image](https://user-images.githubusercontent.com/40156185/168742651-206fa05a-fab6-4863-a59f-97add6d6ad58.png)

**Comment by yang-xiaodong** [comment]
> if I put the default two tables created by cap in mongdb and use opengauss database for transactions, will this affect the data consistency

Of course, local transactions cannot remain ACID on Mongo and Opengauss
