### ISSUE TITLE
Dashboard 401 unauthorized Error

### ISSUE THREAD

**Issue by alkanmurat** [dotnetcore/CAP#1135]
Hi,

My project is using 3.0.4 version. When i send request for dashboard panel i get error 401 unauthorized

![Screen Shot 2022-05-16 at 18 57 39](https://user-images.githubusercontent.com/40641040/168634985-c5dd9e66-c146-4d2e-a23f-f6f0aa42fe57.png)

**Comment by xiangxiren** [comment]
Please provide sample code and configuration for reproducing. Also your version is old.

**Comment by yang-xiaodong** [comment]
No response, closed!
