### ISSUE TITLE
Message Ordering [Kafka]

### ISSUE THREAD

**Issue by horseznguyen** [dotnetcore/CAP#1138]
Hi,

I have three Integration Events generated from Order 
+ ORDER_CREATE
+ ORDER_MODIFY
+ ORDER_CANCEL

In Kafka, the ordering is guaranteed for all messages in one Partition so, how to assign a special key (orderId) to the above events in code so that they send to a partition ? 

Many thanks.

**Comment by yang-xiaodong** [comment]
Hello

You can publish with `KafkaHeaders.KafkaKey`  header key, the Cap will use it as the kafka produce key.

**Comment by horseznguyen** [comment]
Hello 

> You can publish with KafkaHeaders.KafkaKey header key, the Cap will use it as the kafka produce key.

Thanks your answser


I am wondering what the CorrelationId and CorrelationSequence, MessageId are in the CapHeader for the events. I am new, so explaining what they are and what purpose they serve a little bit further would be helpful.

Many thanks.

**Comment by yang-xiaodong** [comment]
> I am wondering what the CorrelationId and CorrelationSequence, MessageId are in the CapHeader for the events

There is no practical use at the moment, it is intended for future features.
