### ISSUE TITLE
When RabbitMQ is reconnected due to network reasons, the reconnection log is occasionally triggered to continuously output

### ISSUE THREAD

**Issue by hanlinking** [dotnetcore/CAP#1140]
我们在使用过程出现了一个问题，就是当我们使用rabbitmq作为队列，并且在使用过程中中断队列，然后重新启动，有一定的概率导致无限的重连。
![image](https://user-images.githubusercontent.com/20954509/169764879-6d545a1c-c705-48da-b387-12fb69fad57c.png)
测试上是部署k8s环境，有两个pod，rabbitmq掉线重连后，其中一个pod正常了，但是另外一个pod一直都在尝试重连
使用代码也比较简单
``` C#
services.AddCap(option =>
        {
            // 消息存储
            option.UseEntityFramework<FrontDbContext>(o => o.Schema = "FRONT");
            // option.RegisterExtension(new CustomCapOptionExtension());
            // 消息队列
            option.UseRabbitMQ(cfg =>
            {
                cfg.HostName = configuration["Cap:RabbitMQ:HostName"];
                cfg.UserName = configuration["Cap:RabbitMQ:UserName"];
                cfg.Password = configuration["Cap:RabbitMQ:Password"];
                cfg.Port = configuration.GetValue("Cap:RabbitMQ:Port", 5672);
            });
            option.DefaultGroupName = configuration.GetValue<string>("Cap:DefaultGroupName", "cap.queue.hr.sbcc.esop.front");
            option.FailedRetryCount = configuration.GetValue("Cap:FailedRetryCount", 10);
            option.FailedRetryInterval = configuration.GetValue("Cap:FailedRetryInterval", 30);
            option.SucceedMessageExpiredAfter = configuration.GetValue("Cap:SucceedMessageExpiredAfter", 86400);
            option.ConsumerThreadCount = configuration.GetValue("Cap:ConsumerThreadCount", 1);
        });
```

CAP 版本：6.0.1
![image](https://user-images.githubusercontent.com/20954509/169768861-edc943f5-fa41-4f0e-b912-0d38fb8db78e.png)

**Comment by yang-xiaodong** [comment]
执行取消操作是什么意思？消费者抛出取消异常？

**Comment by hanlinking** [comment]
> 

![image](https://user-images.githubusercontent.com/20954509/169806450-b45b35e2-c650-4191-bdca-81045be3b9e3.png)

**Comment by yang-xiaodong** [comment]
你好，这个问题我这边无法重现。按照你的说明，短暂掉线也无法重现，请提供一下重现步骤。

如果你可以重现，请测试下取消后等待2秒是否可以解决？

```cs
public void Pulse()
{
    _cts.Cancel();
    _cts.Dispose();
    _compositeTask?.Wait(TimeSpan.FromSeconds(2));   //添加此行
}
```

**Comment by hanlinking** [comment]
> 你好，这个问题我这边无法重现。按照你的说明，短暂掉线也无法重现，请提供一下重现步骤。
> 
> 如果你可以重现，请测试下取消后等待2秒是否可以解决？
> 
> ```cs
> public void Pulse()
> {
>     _cts.Cancel();
>     _cts.Dispose();
>     _compositeTask?.Wait(TimeSpan.FromSeconds(2));   //添加此行
> }
> ```
目前我通过修改下图做法解决
![image](https://user-images.githubusercontent.com/20954509/172036004-8fc1dd0b-0f5f-4931-b829-2085d80d5191.png)

**Comment by yang-xiaodong** [comment]
Fixed in v6.1.0
