### ISSUE TITLE
Question about consumer idempotence when retrying.

### ISSUE THREAD

**Issue by youpangle** [dotnetcore/CAP#1144]
CAP版本 5.2.0  
数据库 PGSQL  消息队列 Kafka
 2个或以上的节点消费消息时，当消息消费失败后，在做重试消费时会出现已经消费完成，但是状态没更新
初步怀疑是第一个节点消费成功后更改了状态，但是第2个节点也拿到了消息消费，失败后又将状态（StatusName）更改为Failed

**Comment by yang-xiaodong** [comment]
This is by design!  Failure messages may be picked up by multiple nodes and executed repeatedly. So consumers should guarantee idempotence.

see : https://github.com/dotnetcore/CAP/pull/671#issuecomment-697071575

**Comment by yang-xiaodong** [comment]
We already add IsUseStorageLock option to solve the issue in version 7.1.0-preview-193202380.
