### ISSUE TITLE
Subscriber does not consume messages 订阅端不消费消息

### ISSUE THREAD

**Issue by Willxup** [dotnetcore/CAP#1145]
# Environment 环境

dotnet: `.NetCore3.1`
cap: `3.0.4`
kafka: `2.3.0`
mysql: `8.0.21`
CentOS: `7.7.1908`

# Code 代码

## Publish 发布端

```c#
foreach(var item in list){ //less than 1000
      _capBus.Publish("services.function", model);
}
```

## Subscribe 订阅端

```c#
[CapSubscribe("services.function")]
public async Task Function(FuncModel model)
{
    //Business Process
}
```

# Issues 问题

Hello, I have a problem that CAP has been unable to consume messages, and the messages were consumed only after the subscriber service was restarted. During this time, no error message was reported. After the service is restarted, there is no problem, the same problem occurs again after a period of time. The code is very simple, the publisher service publish the message in loop, even the messages is less than 1000, it is published successfully. However, the subscriber service does not consume the messages. The publishing service and the subscriber service are not one service, but they are deployed on the same centos server. Kafka is single deployed, and the configuration of Kafka is the default configuration. I have checked issues, and I don't seem to find the same problem, may be i did something wrong, but I can't find the reason, so i launched this issue ticket, thank you.

您好，我有一个问题是关于cap一直无法消费消息，再重启订阅端服务后，消息才被消费。在这期间，没有任何的报错信息。重启服务后，一段时间都不会有问题，过一段时间后，又会发生同样的问题。代码非常简单，就是发布端循环发布消息，消息量不是很大，不到1000条的情况下，消息都发布成功了。但订阅端一直不进行消费。发布端和订阅端不是同一个服务，分开但部署在同一台centos服务器上的。kafka也是单机部署，且kafka的配置也是默认配置，没有做过调整。我查看了issues，好像没有发现有同样的问题，这可能是我的问题，但我找不到原因，想请教一下，谢谢。

**Comment by Willxup** [comment]
show the message info in `cap.received` :
```json
{ "Headers" :
	{ 
		"cap-callback-name" : NULL,
		"cap-msg-id" : "1527519622303399936",
		"cap-msg-name" : "services.function",
		"cap-msg-type" : "FuncModel",
		"cap-senttime" : "5/20/2022 1:20:32 PM +08:00",
		"cap-corr-id" : "1527519622303399936",
		"cap-corr-seq" : "0",
		"cap-msg-group" : "MqDefaultGroup.v1" 
	},
	"Value" :{}
}
```
`Added: 2022-05-27 19:12:42`
`Retries: 0`
`StatusName: Succeeded`

Published time is 2022-05-20 13:20:32
Received time is 2022-05-27 19:12:42

**Comment by yang-xiaodong** [comment]
Hello,

I also can't find the reason based on your description, I think you have two options.

1. If you cannot upgrade to the latest version, please try to use 3.1.2 to see if the issue can be repeated?
2. Check the Kafka server log to see if there is any abnormal message on the server?

**Comment by Willxup** [comment]
Hello, thanks for your reply. I have checked kafka server already and could not find any error logs. I will upgrade the cap version to 3.1.2 and keep watching. Thanks.
