### ISSUE TITLE
CAP sql执行时间过长，导致数据库CPU异常升高

### ISSUE THREAD

**Issue by fanslead** [dotnetcore/CAP#1146]
CAP版本 5.2.0
数据库 PGSQL 消息队列 Kafka

数据库慢查询cap的sql占80%，CPU资源使用达到90%以上，清理数据后下降一点，加上索引后再次下降一点，但是后续同样现象还是会出来
![image](https://user-images.githubusercontent.com/22066473/170905618-422a0851-5bcf-43bc-a4ee-d652e18ab6c5.png)

![image](https://user-images.githubusercontent.com/22066473/170905128-98cbd4e0-9ff6-419f-a2a2-daee05b70827.png)

![image](https://user-images.githubusercontent.com/22066473/170905161-a50053a2-a615-4125-882f-cdcc7b433f26.png)

![image](https://user-images.githubusercontent.com/22066473/170905185-eb981702-1c94-45ab-a571-2fae40e3db57.png)

![image](https://user-images.githubusercontent.com/22066473/170905301-5de88e98-7333-4bc6-acd9-90fb5819499f.png)

**Comment by yang-xiaodong** [comment]
请报告你表的数据量以及慢SQL ?

**Comment by fanslead** [comment]
表数量100W
慢sql
```
SELECT "Id","Content","Retries","Added" FROM "cap"."received" WHERE "Retries"<50 AND "Version"='v1' AND "Added"<'2022-05-29T17:47:06.0350788+08:00' AND ("StatusName"='Failed' OR "StatusName"='Scheduled') LIMIT 200
```
```
DELETE FROM "cap"."received" WHERE "Id" IN (SELECT "Id" FROM "cap"."received" WHERE "ExpiresAt" < $1 LIMIT $2)
```

**Comment by yang-xiaodong** [comment]
这个SQL都很简单，没什么优化空间，请尝试添加索引或升级服务器配置。
或者可以将消息过期时间改短一些，保持表的数据量相对较小。

**Comment by fanslead** [comment]
数据库是华为云16C32G的PGSQL，已经尝试加了索引，情况缓解，但是还是会出现CPU飙高的情况

**Comment by yang-xiaodong** [comment]
这个你要自己分析下原因，按理说100w数据量不可能这么慢，看是不是其他因素导致！

**Comment by fanslead** [comment]
查询数据库的慢日志，出来的sql就是cap的这两条SQL。也联系华为云的人查询相关信息，他们反馈结果都是数据库进程占用。是否是集群下，多个节点频繁执行sql导致？

**Comment by yang-xiaodong** [comment]
不是，重试1分钟才触发一次，就算你部署60个节点，平均也才1次/s，对数据库来说可以忽略不计。

**Comment by fanslead** [comment]
![image](https://user-images.githubusercontent.com/22066473/170920729-d248c31b-3caa-4244-a4de-45b5c1e11a1c.png)

**Comment by yang-xiaodong** [comment]
把  "Retries" , "Version" 也加上试试

**Comment by fanslead** [comment]
我先试试，观察一段时间看看情况
