### ISSUE TITLE
站点回收自启动后，出现DotNetCore.CAP.Internal.ConsumerRegister：BUSYGROUP Consumer Group name already exists异常

### ISSUE THREAD

**Issue by cdefg198** [dotnetcore/CAP#1147]
大佬，这个问题在生产环境又重现了一次。上次也出现过一次，[上次的问题](https://github.com/dotnetcore/CAP/issues/1106)。上线8个月一共出现了两次。
1、使用环境：IIS10、CAP 6.0.1、CAP.RedisStreams 6.0.1、CAP.SqlServer 6.0.1
2、CAP消费网站应用程序池每天凌晨5点回收加自启动
3、出现异常：
3.1   DotNetCore.CAP.RedisStreams.AsyncLazyRedisConnection：Server replied with error, BUSYGROUP Consumer Group name already exists, for endpoint
3.2   DotNetCore.CAP.Internal.ConsumerRegister：BUSYGROUP Consumer Group name already exists
4、出现问题：
CAP站点是正常启动的，在生产者cap.Published中有记录，并且StatusName为Succeeded,
但是在消费者cap.Received中没有记录，redis里面有记录，
导致业务数据没有处理成功，然后我重启了消费端站点，就正常了。

Published表数据
![image](https://user-images.githubusercontent.com/3070114/171084328-754a66d2-f7af-47e8-a216-464e94e3f676.png)

Received表数据
![image](https://user-images.githubusercontent.com/3070114/171084422-cb2c1473-44c1-4864-aefa-0be21243db4d.png)

这个时间段出现的异常：
异常1：
![3](https://user-images.githubusercontent.com/3070114/171084489-d6a2754d-1a12-4d4c-b9ac-1952254a61db.jpg)

异常2：
![4](https://user-images.githubusercontent.com/3070114/171084560-b07374ce-f839-4d0c-8fed-56d0c7630940.jpg)

异常3：
![5](https://user-images.githubusercontent.com/3070114/171084595-5e4796bc-b694-4c8a-838c-3cc508cbf802.jpg)

**Comment by yang-xiaodong** [comment]
Hello,

Since our Redis Stream contributor are from English-speaking countries, so please describe your problem in English.

If you'd like to investigate this issue, that's welcome!
