### ISSUE TITLE
Received表中的数据比Published中的数据足足晚了将近一天

### ISSUE THREAD

**Issue by pwm812** [dotnetcore/CAP#1153]
你好，最近遇到这样一个问题，Received表中数据的Added时间比Published中的数据足足晚了将近一天，导致用户昨天提交的数据今天才收到，能否帮忙分析一下这种情况是怎么发生的呢？我暂时没有想明白这种情况是怎么发生的。谢谢！

**Comment by yang-xiaodong** [comment]
Please provide your version and configuration and logs

**Comment by pwm812** [comment]
你好，CAP版本号是5.1.0，我发现情况大概是这样：有可能是中途rabbitmq服务挂过，然后重启之后，其他服务重新连接到rabbitmq，rabbimq中的connection中也可以看到连接，连接这里没有问题，问题出在队列中的consumer是空的，按理说connection都连上了，consumer应该不会为空呢。目前发现大概就是这样，不知道CAP有没有重连机制呢？谢谢。
