### ISSUE TITLE
如何捕获Publish的异常

### ISSUE THREAD

**Issue by jue668** [dotnetcore/CAP#1159]
你好，在不使用事务的情况下，如何捕获Publish的异常。

 public async Task<IActionResult> CapDemo()
{
		 // do something ...
				
                // 发送消息给客户端时发生异常，如何捕获
                _capBus.Publish("kjframe.test", DateTime.Now);
				
                return Ok();
            }

**Comment by xiangxiren** [comment]
try catch

**Comment by jue668** [comment]
捕获不到，在执行Publish的时候若是失败或者异常都捕获不到，只有超过重试次数后在FailedThresholdCallback回调函数中可见

**Comment by xiangxiren** [comment]
Publish方法只保证消息成功插入到发送表中。发送到消息队列，并不会中断业务。重试线程会将消息多次发送到消息队列，直到发送成功为止，除非达到重试次数。
