### ISSUE TITLE
how to add health check for consul？

### ISSUE THREAD

**Issue by windcatcher** [dotnetcore/CAP#116]
how to add health check for consul？

**Comment by yuleyule66** [comment]
Health checks are provided by default in CAP of dashboard.
see: https://github.com/dotnetcore/CAP/blob/develop/src/DotNetCore.CAP/Dashboard/DashboardRoutes.cs#L38

**Comment by windcatcher** [comment]
我的consul和webapi的环境是部署在windows for docker的docker容器中，
我的配置是这样的

 "ConsulUrl": "http://localhost:8500",
  "UserServerUrl": "http://localhost:8802",


x.UseDiscovery(d =>
                {
                    d.DiscoveryServerHostName = consulUri.Host;
                    d.DiscoveryServerPort = consulUri.Port;
                    d.CurrentNodeHostName = userUri.DnsSafeHost;
                    d.CurrentNodePort = userUri.Port;
                    d.NodeId = 1;
                    d.NodeName = “User_Service”;
                    
                });

在consul和cap的UI上面，都可以看到服务的名称，但是发现健康检查还是有问题，下面是consul服务的日志信息

consulserver_1  |     2018/04/21 17:46:25 [WARN] agent: http request failed 'http://127.0.0.1:8802/cap/health': Get http://127.0.0.1:8802/cap/health: dial tcp 127.0.0.1:8802: connection refused

**Comment by windcatcher** [comment]
x.UseDashboard() 这一句一直有加在代码中，没有漏。

**Comment by windcatcher** [comment]
找到问题了，上面的代码是正确的，是docker容器之间网络互连的问题造成的。我的consul服务是部署在docker上面的，asp .net core的webapi服务也是部署在docker上面，使用的ip应该是docker网络里的ip，而不是localhost的ip
