### ISSUE TITLE
support TransactionScope？

### ISSUE THREAD

**Issue by bxjg1987** [dotnetcore/CAP#1164]
look this：https://docs.microsoft.com/zh-cn/previous-versions/dotnet/netframework-3.0/ms172152(v=vs.85)

**Comment by yang-xiaodong** [comment]
No, This is not in line with our goals

**Comment by bxjg1987** [comment]
I hope you can think more about that transactionscope is so important that it allows you to control transactions in the business logic layer, not in the data access layer.

**Comment by yang-xiaodong** [comment]
We don't provide support for TransactionScope because MSDTC is required to use TransactionScope in a distributed environment and CAP aims to get away from MSDTC

**Comment by bxjg1987** [comment]
. Net core 6 or less
Transactionscope does not support distributed transactions (DTC), it only supports local transactions. It allows you to control transactions in the business layer, rather than forcing them in the data access layer, which makes sense.
（. Net7, transactionscope plans to support distributed transactions only in MSSQL on windows）
