### ISSUE TITLE
Consumer message priority feature request

### ISSUE THREAD

**Issue by coolyuwk** [dotnetcore/CAP#1167]
实际业务场景下重要的订阅消息可能被大量低级别消息长时间阻塞，能否增加订阅队列权重优先处理高权重队列消息？

**Comment by yang-xiaodong** [comment]
You can place messages to different groups, and then set each group to have there own dispatcher to true( `UseDispatchingPerGroup=true` ) so that the message can be processed separately.

 See : #1027
