### ISSUE TITLE
SubscriberNotFoundException-->Message can not be found subscriber.

### ISSUE THREAD

**Issue by 276615100** [dotnetcore/CAP#1169]
找不到消费者吗？但有时候可以，有时候不可以的？不可以是值变成乱码    
"Value":  "data:String;base64,IjA4ZGE1ZTY0Njg1MGUxODk4MDg4ZjMwMDAxMDBjNzRiIg=="

**Comment by yang-xiaodong** [comment]
Please show your configuration and tell us how to reproduce?

**Comment by 276615100** [comment]
> Please show your configuration and tell us how to reproduce?

DefaultGroupName=null,   RabbitMq 的ExchangeName自定义，出现报错

**Comment by yang-xiaodong** [comment]
DefaultGroupName can not be null

**Comment by 276615100** [comment]
> DefaultGroupName can not be null

加了也会出现哦。SubscriberNotFoundException-->Message can not be found subscriber. Name:cap_tla_handle, Group:group_tla.. see: https://github.com/dotnetcore/CAP/issues/63

**Comment by yang-xiaodong** [comment]
Please see #63 

Closed by https://zhuanlan.zhihu.com/p/25795393
