### ISSUE TITLE
FailedCallback回调没有反应

### ISSUE THREAD

**Issue by windcatcher** [dotnetcore/CAP#117]
问下，我怎么才能回调到FailedCallback 的方法，或者有没有使用例子可以参看，以下是我的用法

首先，在service声明FailedCallback 的委托
services.AddCap(x =>
            {
                x.UseEntityFramework<ProductContext>();
                x.UseDashboard();
                x.UseRabbitMQ(Configuration["ConStrRabbitMq"]);
                x.FailedRetryCount = 2;
                x.FailedCallback = new Action<MessageType, string, string>(FailCallbackFoo);
            });

//FailCallbackFoo方式是FailedCallback 委托的实现
private void FailCallbackFoo(MessageType msgType, string name, string content)
        {
            Console.WriteLine($"fail msg Name:{name},content:{content}");
        }
`

然后，在消息生产方，发布消息
using (var transaction = _orderContext.Database.BeginTransaction())
            {
                _orderContext.SaveChanges();
                await _publisher.PublishAsync("Orderservices.Order.Create", orderCount, "FailCallbackFoo");
                transaction.Commit();
            }

  在消费订阅方，我设置了异常，让它不断重试，当它超过重试的次数后，发现FailedCallback 的委托定义的FailCallbackFoo方法没有产生回调效果

**Comment by yuleyule66** [comment]
FailedRetryCount 设置建议大于3，因为三次以内不走重试处理器，处理不到FailedCallback
