### ISSUE TITLE
多节点之间消息重复消费问题??

### ISSUE THREAD

**Issue by LCZQY** [dotnetcore/CAP#1170]
启动两个实例, 分别在不同的端口上发送消息,出现: 两个实例都收到了消息? 
![image](https://user-images.githubusercontent.com/35684519/177484396-ebfee6bd-a86e-46a1-b225-5a07effb5a0a.png)
![image](https://user-images.githubusercontent.com/35684519/177484852-fe5cd03c-cfa5-43ef-9c5d-c4fdd2ff26f1.png)

我要怎么做 才可以加快消息队列中消息的处理速度呢? 就想要到多个实例??

**Comment by yang-xiaodong** [comment]
Does your two instances have the same subscriber group? The default value is the assembly name

**Comment by LCZQY** [comment]
ok

**Comment by wdqzdd** [comment]
同问，多消费者，多队列，消息并行处理

**Comment by lxy0038** [comment]
同问，我也遇到相同问题

**Comment by lxy0038** [comment]
@yang-xiaodong 同问，我也到相同问题，只要部署两个实例（使用docker部署的） 就会出现消息重复消费问题。

**Comment by yang-xiaodong** [comment]
CAP默认使用程序集名称作为Group name, 确保你的实例程序集名称相同

https://github.com/dotnetcore/CAP/blob/master/README.zh-cn.md#%E8%AE%A2%E9%98%85%E8%80%85%E7%BB%84
