### ISSUE TITLE
Cap changes Json value to base64 when deserialization fails

### ISSUE THREAD

**Issue by mgutekunst** [dotnetcore/CAP#1171]
Hi, 
when using the json serializer, CAP somehow seems to change the content of the `Value` property from json to base64. This way, even after solving issue causing problems with the deserialization, the value still cannot be read because the format changed..

## Reproduction
To reproduce this, you can, for example, remove the default constructor of the receiving DTO. 

## Configuration
- Storage: Sql Server
- Transport: Azure Service Bus

Unfortunately, I currently can't tell you if the issue is specific to the configuration we use.

**Comment by yang-xiaodong** [comment]
Yes,  this is in line with design.

When the consumer receiving `byte[]` cannot be deserialized or subscriber can't be found, since we can't determine what type of the publishing object is, such type is number, array,  object, byte etc, so we encoded it into base64 for storage.

**Comment by mgutekunst** [comment]
Thanks for your quick repsonse. Your explanation makes a lot of sense, which is rather unfortunate for us 🙈. 

I'll close this issue, we'll manually translate the Value back into json...
