### ISSUE TITLE
performance question?

### ISSUE THREAD

**Issue by zitjubiz** [dotnetcore/CAP#1177]
I tested it with mysql+rabbitMQ, and it took 106 seconds to push and consume 10k records in a loop. It felt a bit slow. I sent MQ directly, it should be within 4 seconds. Is there any optimization method that can improve performance?

我用mysql+rabbitMQ做了测试,循环推送消费1w条记录,用时106秒,感觉有点慢, 我直接发MQ,应该是在4秒内, 有什么优化的方法,能提高性能?

_Originally posted by @zitjubiz in https://github.com/dotnetcore/CAP/issues/1155#issuecomment-1189617652_

**Comment by zitjubiz** [comment]
I sent MQ     4 seconds **without** publish confirm ;  30 seconds with  **enabled** pubish confirm

**Comment by zitjubiz** [comment]
Can channel confirm  using async method?

**Comment by zitjubiz** [comment]
https://www.rabbitmq.com/tutorials/tutorial-seven-dotnet.html

**Comment by yang-xiaodong** [comment]
In the scenario of publishing a large number of messages in a short time, I recommend using a dedicated thread to directly connect to the message queue for batching, and enable multiple consumer threads at the time of consumption to ensure consumption speed.

**Comment by zitjubiz** [comment]
compare with MQTT Qos1, it means at lease send once,   which one is better choice ?
