### ISSUE TITLE
When the transaction fails, the message is still sent

### ISSUE THREAD

**Issue by ajdwfnhaps** [dotnetcore/CAP#118]
Ｈi Savorboard,使用2.2.1版本，遇到一个问题，请教一下。

![image](https://user-images.githubusercontent.com/11205717/39026773-617e951c-4481-11e8-85ee-01b4559e7101.png)

代码逻辑主要是：
１.第一步发送消息
２.第二步处理我的业务逻辑　（ImportBrief方法）
３.提交事务

但是我发现，业务逻辑的方法还没处理完，第一步发送的消息就被消费的订阅方法处理完了。

按我的理解，应该直到事务提交后，才会真正publish消息到ＭＱ，但现在的情况好像不是的，不知道是否我的理解有问题？

ＰＳ：
![image](https://user-images.githubusercontent.com/11205717/39026829-a2a6307c-4481-11e8-9b90-1a7907b4788b.png)

**Comment by yuleyule66** [comment]
A more friendly approach is being conceived to implement this feature.

**Comment by ajdwfnhaps** [comment]
Great,looking forward to the update.

**Comment by 453495181** [comment]
我也遇到了同样的问题，请问修复了吗

**Comment by CleanCoder** [comment]
Here is our solution, before publish the message, check whether it has been committed to the DB. (Note: please do not use dirty read here):

**Dispatcher**:
while (!_publishedMessageQueue.IsCompleted)
                {
                    PublishedMessage message = null;
                    if (_publishedMessageQueue.TryTake(out message, 100, _cts.Token))
                    {
                        try
                        {
                            **bool messgeCommitted = _connection.CommittedMessage(message).GetAwaiter().GetResult();**
                            if (messgeCommitted)
                            {
                                _sender.SendAsync(message);
                            }
                            else
                            {
                                TimeSpan elapsedTime = DateTime.Now - message.LatestPublicStatusCheckTime;
                                if (elapsedTime < MAX_TIME_OF_WAITING_PUBLISH) // If not time out, re-enqueue the message
                                {
                                    if (elapsedTime < HALF_SECOND) // current limit control
                                    {
                                        System.Threading.Thread.Sleep(HALF_SECOND);
                                    }

                                    message.LatestPublicStatusCheckTime = DateTime.Now;
                                    _publishedMessageQueue.Add(message);
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            _logger.ExceptionOccuredWhileExecuting(message.Name, ex);
                        }
                    }

**Comment by DiggingSteve** [comment]
if consuming failed how to roll back

**Comment by witskeeper** [comment]
这个BUG还没修正吗？

**Comment by moyuanhui** [comment]
很多人遇到这个问题，作者还是尽快更新吧！！！

**Comment by moyuanhui** [comment]
@CleanCoder 提供的解决方案并不完整，问题还是存在。。

**Comment by yuleyule66** [comment]
This is a difficult problem to deal with, we will in version 2.3 to fix this problem, some api break change for this feature support.

The new API call like this :

![image](https://user-images.githubusercontent.com/8205994/43560788-bf6343fa-9646-11e8-91de-8bdc13244fd2.png)

With the new API, everyone can come up with their own ideas!

**Comment by hzr1348** [comment]
是不是可以考虑使用TransactionScope来控制事务

**Comment by CleanCoder** [comment]
恕我直言，很多场景是满足不了https://github.com/dotnetcore/CAP/issues/191里面提到的Publish Message须在业务末端调用。

**Comment by CleanCoder** [comment]
> @CleanCoder 提供的解决方案并不完整，问题还是存在。。

“方案并不完整”指的是这个方案有未考虑到的场景，还是指提供的代码不完整？
代码是没有全贴上来，但表达的意思都在那了，理解了自己填完整没难度。
