### ISSUE TITLE
Can consumption be triggered by manual publishing in the RabbitMQ admin interface?

### ISSUE THREAD

**Issue by AlexRen01** [dotnetcore/CAP#1180]
I want to trigger the consumption of the interface by manually publishing events in RabbitMQ's admin interface. However, I failed to trigger it after filling in the content according to the screenshot below. Is my parameter wrong?
Published interface：
![image](https://user-images.githubusercontent.com/48472715/182990159-100004b8-f9a4-459d-8182-b4d905c4a78d.png)

Consumer interface：
![image](https://user-images.githubusercontent.com/48472715/182990191-a5a5eba1-4c8e-4e22-8e77-06485fc143f1.png)

**Comment by yang-xiaodong** [comment]
Bcause the necessary metadata is missing on the header of the message

see: https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#custom-headers

**Comment by AlexRen01** [comment]
> Bcause the necessary metadata is missing on the header of the message
> 
> see: https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#custom-headers



sorry，It didn't seem to work
![Uploading 企业微信截图_20220805152910.png…]()
![Uploading 企业微信截图_20220805152918.png…]()

**Comment by AlexRen01** [comment]
> Bcause the necessary metadata is missing on the header of the message
> 
> see: https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#custom-headers

It didn't seem to work

![image](https://user-images.githubusercontent.com/48472715/183025997-3366bed3-489f-4953-ad8c-cebc3bd89cfe.png)

![image](https://user-images.githubusercontent.com/48472715/183026021-2b019548-5271-4679-a99e-660a179ea8f5.png)

**Comment by yang-xiaodong** [comment]
Don't set header in management if you already custom headers, and  please use sample configuration as the MessageId and MesasgeName value
