### ISSUE TITLE
I wana publish in the web project, and subscribe in the services project.

### ISSUE THREAD

**Issue by louieyu** [dotnetcore/CAP#1181]
I wana publish in the web project, and subscribe in the services project. But I can't find the configuration that implements this separate design.

**Comment by yang-xiaodong** [comment]
![image](https://user-images.githubusercontent.com/8205994/183053084-22126eee-94d2-4939-8b18-8e30eebe9e00.png)

**Comment by louieyu** [comment]
> ![image](https://user-images.githubusercontent.com/8205994/183053084-22126eee-94d2-4939-8b18-8e30eebe9e00.png)

Yes ，I do that way. The services library was referened in the web project and the background services. I found it was consumed in the web project and the background services.

**Comment by yang-xiaodong** [comment]
@louieyu  

```cs
services.AddCap(x =>
{
    // ...
}).AddSubscriberAssembly( ... );
```
