### ISSUE TITLE
[Question] How do we handle a situation where publish messages for the current microservice but need to subscribe to messages for another microservice?

### ISSUE THREAD

**Issue by fearless87** [dotnetcore/CAP#1183]
I looked at [#998](https://github.com/dotnetcore/CAP/issues/998#issuecomment-988659781)  it carefully,but it doesn't solve my problem.
My requirements are as follows, please help to answer.Very thanks!
**Publish**:Under the current microservice and maintain transaction consistency with the business of the current microservice.
**Consumer**:Consuming a message from another microservice while processing the business of the current microservice.

**Comment by yang-xiaodong** [comment]
What do you mean “Consuming a message from another microservice",  another broker?

**Comment by fearless87** [comment]
Microservice-A pulish a message to CAP,and B consumes A's message

**Comment by fearless87** [comment]
There are two microservice A and B(Different DB) :
A publish a message to CAP, and B consumes A's message,and B publish a message to CAP,and A's consumes B's message

**Comment by fearless87** [comment]
> What do you mean “Consuming a message from another microservice", another broker?
![image](https://user-images.githubusercontent.com/8747775/183290418-2915eecb-8b5e-4758-857d-b9b79efaa408.png)

**Comment by fearless87** [comment]
> What do you mean “Consuming a message from another microservice", another broker?

Very Thanks！It's not a problem anymore, it's actually a Borker.
