### ISSUE TITLE
Feature requests for subscribe by interface

### ISSUE THREAD

**Issue by jrlygdsj** [dotnetcore/CAP#1189]
Requirements: 
Subscribers want to subscribe to only messages related to themselves, which can greatly reduce the number of unrelated messages subscribed to. In order to achieve this, we will dynamically specify the message name when publishing the message, and the message name will contain some identifying characters. The subscriber will also subscribe according to the "identifying" characters when subscribing. However, when subscribing through Capsubscribe (name), the message name can only be a constant and cannot be dynamically specified. If cap support subscription through  interface, will solve this problem

**Comment by yang-xiaodong** [comment]
We do not support dynamic subscriptions.

Did you understand wildcards topic?

**Comment by jrlygdsj** [comment]
> We do not support dynamic subscriptions.
> 
> Did you understand wildcards topic?

 Wildcards topic can't solve my problem.  wildcard topic solves the flexibility of subscribing to messages, which can maximize the range of subscribed messages. In fact, I want to reduce the number of subscribed messages

**Comment by 3ldar** [comment]
@jrlygdsj I think you can resolve that on the MQ layer. Most major MQs support key-based dynamic routing (I guess you use RabbitMQ).

**Comment by jrlygdsj** [comment]
> @jrlygdsj I think you can resolve that on the MQ layer. Most major MQs support key-based dynamic routing (I guess you use RabbitMQ).

yes, that's right，but i also need transaction.  it's perfect  if cap support it

**Comment by yang-xiaodong** [comment]
In fact what you need is a dynamic subscriber, the queue is dynamically created and destroyed, the publisher messages to the dynamically created queue, and then there is only one consumer. using direct exchange type in rabbitmq.
