### ISSUE TITLE
这个库是解决了什么问题，大神请赐教

### ISSUE THREAD

**Issue by ww198643** [dotnetcore/CAP#119]
此库的使用逻辑是：处理业务，业务处理完了，再发布消息到队列，然后订阅消费消息，我不明白解决了什么问题，从哪里体现了是解决分布式事务？如果消息订阅方业务处理失败，需要回滚，那消息发布之前的业务逻辑怎么回滚，请大神赐教

**Comment by yuleyule66** [comment]
查看这个
http://www.cnblogs.com/savorboard/p/distributed-system-transaction-consistency.html
