### ISSUE TITLE
目前的CAP是把所有的消息都拉取到内存中，入队之后，再挨个去消费，这样造成内存消耗严重，有没有提供控制队列长度的选项

### ISSUE THREAD

**Issue by kukumaya** [dotnetcore/CAP#1194]
目前的CAP是把所有的消息都拉取到内存中，入队之后，再挨个去消费，这样造成内存消耗严重，有没有提供控制队列长度的选项
目前的配置：队列使用kafka，存储使用内存，本来是希望用kafka做到消峰的效果，结果并不如意

**Comment by yang-xiaodong** [comment]
并不是所有拉取到内存，在 5.1.1 版本中我们启用了背压机制，见 #935
