### ISSUE TITLE
can not get traceid from IEntrySegmentContextAccessor when message has been retry consume

### ISSUE THREAD

**Issue by sampsonye** [dotnetcore/CAP#1198]
whenever  meesage has been retry consume i can not get origin traceid(by skyapm) using `IEntrySegmentContextAccessor`
check the code,i find retry only invoke `TracingBefore`, so it lost entrySegment from the `CapTracingDiagnosticProcessor._contexts` dictionary

消息重试消费时会丢失原始的traceid，从`IEntrySegmentContextAccessor`中获取不到它。看了下源码，发现消费重试的方法仅触发了`TracingBefore`的诊断，导致他无法从`CapTracingDiagnosticProcessor._contexts`中获取正确的入口trace信息

**Comment by yang-xiaodong** [comment]
Is the traceid present in the message header and is it persisted?

**Comment by sampsonye** [comment]
cap.received表中Header有sw8

**Comment by sampsonye** [comment]
```json
{
    "Headers": {
        "cap-callback-name": null,
        "cap-msg-id": "10537107281100804",
        "cap-corr-id": "10537107281100804",
        "cap-corr-seq": "0",
        "cap-msg-name": "Cube.MessageCenter.SendAll",
        "cap-msg-type": "String",
        "cap-senttime": "2022/9/5 11:16:21 \u002B08:00",
        "UserId": "1",
        "sw8": "1-OGUyN2IzNGFjYTEwNDRmZmUyMTI3YTJjMWEyMTZjZjEuMzUuMTY2MjM0Nzc3OTU0ODAwMDc=-OGUyN2IzNGFjYTEwNDRmZmUyMTI3YTJjMWEyMTZjZjEuNDAuMTY2MjM0NzgyOTc0OTAwMDg=-0-Y3ViZS13ZWJhcGk=-MTcyLjE2LjEyLjUxQGU0NzlkMzBkZWM4NjRkMGVhNzlhYzc5ODQzZDYyOGY4-Q0FQL0N1YmUuTWVzc2FnZUNlbnRlci5TZW5kQWxsL1B1Ymxpc2hlcg==-MTkyLjE2OC45NS4xMTo1Njcy",
        "cap-msg-group": "cap.queue.cube.admin.messagecenter.v1"
    },
    "Value": //忽略
}
```

**Comment by yang-xiaodong** [comment]
你的意思是重试的时候 sw8 这个item 在头里面没有？  其他的都有怎么可能这个没呢？ 我手动添加了一个头这个是调试的结果

![image](https://user-images.githubusercontent.com/8205994/188601462-62358641-e505-43c4-87f0-aeeabf2fea65.png)

**Comment by yang-xiaodong** [comment]
我知道了，`SkyApm.Diagnostics.CAP` 中的问题。

要去那边提issue，在重试的时候忽略掉。

我先关掉这个issue了。
