### ISSUE TITLE
dashboard主页报错

### ISSUE THREAD

**Issue by daimeiquan** [dotnetcore/CAP#120]
环境：
asp.net core 2.0
rabbitmq
mssqlserver

发布订阅功能正常，进入dashboard提示：
An unhandled exception occurred while processing the request.

SqlException: 'FORMAT' 不是可以识别的 内置函数名称。
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)

System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, bool callerHasConnectionLock, bool asyncClose)
System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, out bool dataReady)
System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
System.Data.SqlClient.SqlDataReader.get_MetaData()
System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, string resetOptionsString)
System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, bool async, int timeout, out Task task, bool asyncWrite, SqlDataReader ds)
System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, TaskCompletionSource<object> completion, int timeout, out Task task, bool asyncWrite, string method)
System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, bool wasClosed, CommandBehavior behavior) in SqlMapper.cs
Dapper.SqlMapper+<QueryImpl>d__136.MoveNext() in SqlMapper.cs
System.Collections.Generic.List.AddEnumerable(IEnumerable<T> enumerable)
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
Dapper.SqlMapper.Query<T>(IDbConnection cnn, string sql, object param, IDbTransaction transaction, bool buffered, Nullable<int> commandTimeout, Nullable<CommandType> commandType) in SqlMapper.cs
DotNetCore.CAP.SqlServer.SqlServerMonitoringApi.GetTimelineStats(IDbConnection connection, string tableName, string statusName, IDictionary<string, DateTime> keyMaps)
DotNetCore.CAP.SqlServer.SqlServerMonitoringApi.GetHourlyTimelineStats(IDbConnection connection, string tableName, string statusName)
DotNetCore.CAP.SqlServer.SqlServerStorage.UseConnection<T>(Func<IDbConnection, T> func)
DotNetCore.CAP.Dashboard.Pages.HomePage.Execute()
DotNetCore.CAP.Dashboard.RazorPage.TransformText(string body)
DotNetCore.CAP.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by yuleyule66** [comment]
需要SQL Server 2012+ 版本
