### ISSUE TITLE
The version and node information are not displayed on the dashboard

### ISSUE THREAD

**Issue by zhangzw218** [dotnetcore/CAP#1202]
At present, there is no version information and node information at the bottom of the dashboard. May I ask if it has been removed after update or if I am missing some configuration?
Also, when I toggle Nodes through Nodes, the node name used to be displayed at the bottom of the page, but it's not there anymore.
I'm using version 6.1.0 now, and it was normal to use 3.x before.

In addition, my current dashboard is in English, can this configuration be changed into Chinese?
![1662534904570](https://user-images.githubusercontent.com/40768649/188813658-3ef61b0f-5b91-4af9-b9ae-acbf0de1c483.png)

**Comment by yang-xiaodong** [comment]
Yes, we're replaced to new dashboard after version 5.1.0

https://github.com/dotnetcore/CAP/pull/880

Chineses language will release in the new version
