### ISSUE TITLE
Ambiguity issue

### ISSUE THREAD

**Issue by yetangcun** [dotnetcore/CAP#1211]
First Install DotNetCore.CAP.MySql and DotNetCore.CAP.SqlServer in a same project  or library

Second use transaction as :
 using (var conn = new MySqlConnection(DbConnectionString))
  {
                using (var transaction = conn.BeginTransaction(_capBus, autoCommit: true))
                {
                    //业务代码
                    _capBus.Publish("xxx.services.show.time", DateTime.Now);
                }
 }

Last it'll report error: the function conn.BeginTransaction tips ambiguity

**Comment by yang-xiaodong** [comment]
No, You can't install two same storage at the same time. This is not supported

**Comment by yetangcun** [comment]
> No, You can't install two same storage at the same time. This is not supported

well ,i got it, thanks very much to your answer
