### ISSUE TITLE
Under pressure test, some topics have large message volume and other topics consume slowly

### ISSUE THREAD

**Issue by knowyi** [dotnetcore/CAP#1215]
hi，
The 5.1.4 service of the cap version I currently use subscribes to 8 topics. During online pressure testing, I will push a large number of messages to several topics. During the consumption of these topics, I found that the consumption of other topics with a small number will slow down. The CPU of the server itself is not high. Currently, the ConsumerThreadCount is set to 9. In this case, the message published at 11:19 was processed 15 minutes after 11:36, Sometimes the interval may exceed 2 to 3 hours. Is my configuration unreasonable? How can I adjust it better?

![image](https://user-images.githubusercontent.com/7392434/194992930-5f7efb99-19e0-416f-a3ea-a6505ec8791c.png)

![image](https://user-images.githubusercontent.com/7392434/194992841-35d2dce1-cf88-494b-9bde-34d0e0d47096.png)

**Comment by knowyi** [comment]
> What's your broker?

kafka 
When I separate the services, the speed of subscription will be significantly improved. The consumption efficiency of multiple topics subscribed to the same service will be greatly reduced. There is also a strange problem. At present, there is no backlog in the queue, but the messages in the cap that are more than 1:00 p.m. are still in the Scheduled status. Some data can be found in the published table. The data in the received table has not been implemented
![image](https://user-images.githubusercontent.com/7392434/195043084-cc1e8e31-0c7b-42c9-a430-9d685e21bb14.png)

**Comment by knowyi** [comment]
At present, there are about 3 million published and received data. This is because Mongo's slow SQL has been found by monitoring. I wonder if this has something to do with it?

{
	"op": "command",
	"ns": "wmscap.cap.received",
	"command": {
		"aggregate": "cap.received",
		"pipeline": [
			{
				"$match": {
					"StatusName": "Succeeded"
				}
			},
			{
				"$group": {
					"_id": 1,
					"n": {
						"$sum": 1
					}
				}
			}
		],
		"cursor": {},
		"$db": "wmscap",
		"lsid": {
			"id": {
				"$binary": "lAbJOl9QRt6BqhCgn6D79g==",
				"$type": "04"
			}
		},
		"$clusterTime": {
			"clusterTime": {
				"$timestamp": {
					"t": 1665393086,
					"i": 266
				}
			},
			"signature": {
				"hash": {
					"$binary": "lug6DlEkrs4mbiPbQkFrhj44Z20=",
					"$type": "00"
				},
				"keyId": {
					"$numberLong": "7095707644291186693"
				}
			}
		}
	},
	"keysExamined": 2281221,
	"keysExaminedBySizeInBytes": 0,
	"docsExamined": 0,
	"docsExaminedBySizeInBytes": 0,
	"cursorExhausted": true,
	"numYield": 17872,
	"nreturned": 1,
	"queryHash": "48DD39D7",
	"planCacheKey": "1BE56CEA",
	"locks": {
		"ParallelBatchWriterMode": {
			"acquireCount": {
				"r": {
					"$numberLong": "1"
				}
			}
		},
		"ReplicationStateTransition": {
			"acquireCount": {
				"w": {
					"$numberLong": "17875"
				}
			}
		},
		"Global": {
			"acquireCount": {
				"r": {
					"$numberLong": "17875"
				}
			}
		},
		"Database": {
			"acquireCount": {
				"r": {
					"$numberLong": "17874"
				}
			}
		},
		"Collection": {
			"acquireCount": {
				"r": {
					"$numberLong": "17874"
				}
			}
		},
		"Mutex": {
			"acquireCount": {
				"r": {
					"$numberLong": "2"
				}
			}
		}
	},
	"flowControl": {},
	"storage": {
		"data": {
			"bytesRead": {
				"$numberLong": "12792696"
			},
			"timeReadingMicros": {
				"$numberLong": "143587"
			}
		}
	},
	"responseLength": 257,
	"protocol": "op_msg",
	"millis": 8696,
	"planSummary": "COUNT_SCAN { StatusName: -1 }",
	"replRole": {
		"stateStr": "PRIMARY",
		"_id": 1
	}
}

**Comment by yang-xiaodong** [comment]
In fact, In an instance it is not a consumer thread corresponding to the topic queue, but an instance consumer subscribed to multiple different topic queues at the same time, and sent to the memory queue  when fetching from different topic queues. The advantage of this is that when there are a large number of topic in the application, it will not take up too much thread resources.

If you have only one instance, you can set topic to different groups and set `UseDispatchingPerGroup` to true to enable parallel consumption capabilities of the group level.

see:
https://cap.dotnetcore.xyz/user-guide/en/cap/configuration/#usedispatchingpergroup

**Comment by knowyi** [comment]
Hello, what I described may not be accurate. I subscribe to multiple topics for one application. The current phenomenon is that when the pressure on one topic subscribed is high, the consumption speed of other topics will decrease significantly. Some data in my pictures yesterday has been in the scheduled state, and it took five to six hours to execute. The last data is executed first. Would you like to ask whether a scheduling policy is last in, first out

**Comment by yang-xiaodong** [comment]
> The last data is executed first. Would you like to ask whether a scheduling policy is last in, first out

No, The behavior you describe does not match our design, are there any steps to reproduce it?

**Comment by knowyi** [comment]
At present, no detailed steps have been sorted out. My situation is that one web api subscribes to eight topics. During the pressure test, some queue messages have a large data volume of about two to three million. The consumption speed is not as fast as the push speed. At this time, the consumption of other queues will also slow down. Then I found this problem. I went to look at Mongodb and saw some slow queries, but they look like Dashboard's

**Comment by knowyi** [comment]
At present, no detailed steps have been sorted out. My situation is that one web api subscribes to eight topics. During the pressure test, some queue messages have a large data volume of about two to three million. The consumption speed is not as fast as the push speed. At this time, the consumption of other queues will also slow down. Then I found this problem. I went to look at Mongodb and saw some slow queries, but they look like Dashboard's

**Comment by yang-xiaodong** [comment]
I realize that you may have executed long-time consuming task in consumer method, you cannot execute long-time tasks in consumer methods, which will cause the polling thread to pick up messages older than 4 minutes and be limited in execution

**Comment by knowyi** [comment]
The consumption itself will slow down when the pressure is high, but it does not take 4 minutes. I can see from the log that the slowest consumption processing is more than ten seconds. How can I optimize it reasonably at present, and split the topic under great pressure?

**Comment by knowyi** [comment]
Hello, during the test, I deployed multiple identical api ports on the same server with different port numbers. In the case of concurrency, cap primary key generation conflicts occasionally occur, resulting in failed publishing. What can I do to avoid? must deploy on different servers？

**Comment by yang-xiaodong** [comment]
Can you open a separate issue describing your problem? I will close this issue related to the topic

**Comment by yang-xiaodong** [comment]
We improved this behavior in version 7.0, now default will not pre-fetch to memory to sovle the slow consumer issue.
