### ISSUE TITLE
Error connecting to redis

### ISSUE THREAD

**Issue by horseznguyen** [dotnetcore/CAP#1216]
Hi,

This error appears sporadically on my production environment. 
10 requests, there will be 1 or 2 with this error

![image](https://user-images.githubusercontent.com/28267489/195295268-176e2a4e-fd0d-4374-9087-e215815528d2.png)

The code it mentions here is

![image](https://user-images.githubusercontent.com/28267489/195295398-1bde686c-dd00-4bbe-8829-d954a4b99e12.png)

**Comment by yang-xiaodong** [comment]
Your exception code doesn't appear to be produced by the CAP library?
