### ISSUE TITLE
EnvironmentVariableTarget.Machine only supported on windows

### ISSUE THREAD

**Issue by alei78910** [dotnetcore/CAP#1219]
On macOS and Linux, the GetEnvironmentVariable(String, EnvironmentVariableTarget) method supports a target value of EnvironmentVariableTarget.Process only. Calls with a target value of EnvironmentVariableTarget.Machine or EnvironmentVariableTarget.User are not supported and return null. Please look at this https://learn.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=net-6.0.

#294

**Comment by yang-xiaodong** [comment]
Fixed in #1220

**Comment by yang-xiaodong** [comment]
Fixed in v6.2.1
