### ISSUE TITLE
多个服务,数据库怎么使用cap。

### ISSUE THREAD

**Issue by jakey188** [dotnetcore/CAP#122]
请问在cap中碰到这种场景怎么配置？对流程不是非常的清楚。

服务A1对应数据库D1,服务A2对应数据库D2. （D1，D2不在同一服务器）A1发布消息到A2,这时候A2操作数据库D2,这时候消费的消息是写到D1的received表中还是D2的received中呢。

**Comment by jakey188** [comment]
@yuleyule66 谢谢,已经懂了。

**Comment by jakey188** [comment]
@yuleyule66 还有个疑问,订阅的方法CapSubscribe如何确保我的订阅成功了呢？  是不是没有异常就认为订阅方法消费成功,写入received呢。

**Comment by yuleyule66** [comment]
从mq接收消息后，首先写入received表，如果写入失败，会拒绝消息，mq会重新推送过来继续写。订阅者执行失败会进行重试，重试3次仍然失败会将消息状态改为Failed，然后又重试处理器对状态为Failed的消息继续重试，当达到默认50次失败后，不再继续重试，此时可以选择邮件或者其他防刷通知然后人工介入
