### ISSUE TITLE
Mongodb Duplicate primary key

### ISSUE THREAD

**Issue by knowyi** [dotnetcore/CAP#1222]
Hello, during the test, I deployed multiple identical api ports on the same server with different port numbers. In the case of concurrency, the generation of primary keys will occasionally be the same, resulting in conflicts in the generation of cap primary keys. Mongodb cannot be saved, and message publishing fails. What can I do to avoid it? Must they be deployed on different servers?
cap version 6.1.0
![image](https://user-images.githubusercontent.com/7392434/195751666-86194fe9-1e9d-477d-a2fa-13b61cb3bb39.png)

**Comment by yang-xiaodong** [comment]
In the past, if the environment variable was not set, we used random numbers to generate the WorkerId, which may be duplicated in a distributed environment. In the new version, we use the Mac address to generate the WorkerId of the snowflake algorithm.

You can set an environment variable (CAP_WORKERID) for the instance to generate unique IDs on the same machine (Windows only, In Linux see #1219).

**Comment by knowyi** [comment]
At present, I am a Windows server, and the MAC address of the same machine is the same, so the primary key may also generate duplicates, right? I set CAP_ How to avoid duplicate primary keys when multiple APIs deployed by WORKERID on the same machine will get the same environment variables?

**Comment by yang-xiaodong** [comment]
WIth version 6.2.1

```ps
$env:CAP_WORKERID = 1;$env:ASPNETCore_Environment = "Staging"; dotnet Sample.RabbitMQ.MySql.dll --urls=http://*:5001
$env:CAP_WORKERID = 2;$env:ASPNETCore_Environment = "Staging"; dotnet Sample.RabbitMQ.MySql.dll --urls=http://*:5002
```
