### ISSUE TITLE
Redis subscription is not working - what I am missing

### ISSUE THREAD

**Issue by kalyankdas** [dotnetcore/CAP#1224]
I am just trying out a simple test with redis CAP, getting an error in the subscription side, plz help

  [CapSubscribe("event.airline.message")]
  public void SubscribeAirline(Airline airline)
  {
      Console.WriteLine("Airline " + airline.Name);
  }

**Cap configuration:**
   options.UseSqlServer("Initial Catalog=events; Data Source=(LocalDB)\\MSSQLLocalDB;Integrated Security=SSPI;");
   
    var configuration = new ConfigurationOptions
    {
        AbortOnConnectFail = false,
        //Ssl = true,
        ConnectRetry = 3,
        ConnectTimeout = 5000,
        SyncTimeout = 5000,
       // DefaultDatabase = 0,
        EndPoints = { { "127.0.0.1", 6379 } },

    };
    options.UseRedis(redisOptions =>
    {
        redisOptions.Configuration = configuration;
    });

**Error from console:**
DotNetCore.CAP.RedisStreams.AsyncLazyRedisConnection[0]
      Server replied with error, NOGROUP No such key 'event.airline.message' or consumer group 'cap.queue.capsubscriber.redis.v1' in XREADGROUP with GROUP option, for endpoint:127.0.0.1:6379
fail: DotNetCore.CAP.RedisStreams.RedisStreamManager[0]
      Redis error when trying read consumer group cap.queue.capsubscriber.redis.v1
      StackExchange.Redis.RedisServerException: NOGROUP No such key 'event.airline.message' or consumer group 'cap.queue.capsubscriber.redis.v1' in XREADGROUP with GROUP option
         at DotNetCore.CAP.RedisStreams.RedisStreamManager.TryReadConsumerGroupAsync(String consumerGroup, StreamPosition[] positions, CancellationToken token)
fail: DotNetCore.CAP.RedisStreams.AsyncLazyRedisConnection[0]

**When I run XRANGE in Redis I see the stream , so publisher published** 

# redis-cli
127.0.0.1:6379> XRANGE event.airline.message
(error) ERR wrong number of arguments for 'xrange' command
127.0.0.1:6379> XRANGE event.airline.message - +
 1) 1) "1666024747434-0"
    2) 1) "headers"
       2) "{\"cap-callback-name\":null,\"cap-msg-id\":\"514955326794715137\",\"cap-corr-id\":\"514955326794715137\",\"cap-corr-seq\":\"0\",\"cap-msg-name\":\"event.airline.message\",\"cap-msg-type\":\"Airline\",\"cap-senttime\":\"10/17/2022 11:38:58 AM -05:00\"}"
       3) "body"
       4) "\"eyJSYW5rIjowLCJOYW1lIjpudWxsLCJDb2RlIjoiQTQiLCJJZCI6ImV2ZW50LTAtNjM4MDE2MDM1Mzg3OTI4OTc1IiwiQ3JlYXRpb25EYXRlIjoiMjAyMi0xMC0xN1QxNjozODo1OC43OTI4OTQ1WiJ9\""
 2) 1) "1666024747455-0"

**Comment by unetcore** [comment]
我也遇到了类似的问题，是在运行一定时间后出现的，重启进程后又正常了。

DotNetCore.CAP.RedisStreams.RedisStreamManager[0]
      Redis error when trying read consumer group productclickhistory.v1
      System.ArgumentException: At least one object must implement IComparable.
         at System.Collections.Comparer.Compare(Object a, Object b)
         at System.Linq.CachingComparer`2.Compare(TElement element, Boolean cacheLower)
         at System.Linq.OrderedEnumerable`1.TryGetFirst(Boolean& found)
         at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
         at DotNetCore.CAP.RedisStreams.RedisConnectionPool.get_QuietConnection()
         at DotNetCore.CAP.RedisStreams.RedisConnectionPool.ConnectAsync()
         at DotNetCore.CAP.RedisStreams.RedisStreamManager.ConnectAsync()
         at DotNetCore.CAP.RedisStreams.RedisStreamManager.TryReadConsumerGroupAsync(String consumerGroup, StreamPosition[] positions, CancellationToken token)

**Comment by MahmoudSamir101** [comment]
Hi @kalyankdas  , 
Could you please define the version that you are using? 
I assumed this issue is similar to #1212 , it is fixed in version 6.2.1

**Comment by yang-xiaodong** [comment]
No response, closed!
