### ISSUE TITLE
Duplicate primary key

### ISSUE THREAD

**Issue by yyang1207** [dotnetcore/CAP#1225]
cap版本6.1.0
通过DockerSwarm集群部署了5个副本，压测600万数据最终写入published表的只有229万，查询日志发现大量db错误提示entry 'xxx' for key 'PRIMARY'。
docker集群部署，环境变量CAP_WORKERID指定workid好像没法用。
下一个版本是否考虑自定义雪花算法或者WorkId接口，通过依赖注入方式传入？

**Comment by yang-xiaodong** [comment]
CAP_WORKERID的环境变量在v6.2.1之前只在Windows机器配置生效，见 #1219

请使用6.2.1版本

**Comment by yang-xiaodong** [comment]
@Allen-dududu 理论上DockerSwarm中不同Docker容器的mac的低10位这个相同的概率应该很低吧？

**Comment by yang-xiaodong** [comment]
是否由 https://github.com/dotnetcore/CAP/pull/1163 导致？ 6.1.0不包含此PR

**Comment by Allen-dududu** [comment]
> 229
 https://github.com/dotnetcore/CAP/pull/1163 这个提交是对的。我刚刚试了一下，本地DockerSwarm部署5个，不设置workid，没有发现问题。如果是在一个机器内，不同Docker容器的mac的低10位基本上都是Docker顺序生成的，很难是一样的，如果是多台机器的话，有这个概率是一样的，但也很低。

**Comment by yang-xiaodong** [comment]
@Allen-dududu  感谢你的测试。不好意思让你误解了，我意思是否是由于 https://github.com/dotnetcore/CAP/pull/1163 没合并之前，读取到其他虚拟和回环网卡导致，因为他使用的 6.1.0 版本。

等待 @yyang1207 的回复  如果使用新版本不能重现这个问题，我们将关闭这个issue。

**Comment by Allen-dududu** [comment]
> 

没事。NewId这个包也会通过获取NetworkAddress和HostNameHashWorkerId设置workid。过滤条件看起来似乎更严谨，没有看到有人抱怨重复Id，如果他还是失败，我们可以使用这个 https://github.com/phatboyg/NewId/blob/e1e1364d2846c54fe930303a2c51aa4091abfe5c/src/NewId/NewIdProviders/BestPossibleWorkerIdProvider.cs#L16

**Comment by yyang1207** [comment]
不重复了
