### ISSUE TITLE
Will failed retries and newly received messages be processed at the same time?

### ISSUE THREAD

**Issue by li-zheng-hao** [dotnetcore/CAP#1226]
I currently have a consumer and need to ensure that only one is running at the same time，but I found that while this consumer was processing the first message (a long time, maybe 10 minutes), the second message would start to be consumed，this can cause business errors

I found that the interval between the sending time and the processing time of the second message is about 5 minutes. I guess it may be that the previously failed or unfinished message was scanned and then continued to process， log like this:

```
[Debug] Development 2022-10-21 15:19:46.615 FB.ProcessorControllerService.CapSubscriberService    下发任务:{"UserId":"148946","CNCPartCostId":"6350a8a9284ccae6ba27f58e","MachineName":"lizhenghao-dev","ReqType":1,"SendTime":"2022-10-21T15:14:27.4144175\u
002B08:00","TimeoutRetry":0}
```

so，my question is, after service startup, will unfinished or failed messages be processed in parallel with newly received messages?

**Comment by li-zheng-hao** [comment]
I am now very sure of this fact，after I start the service, it begin processing message that were previously in `Scheduled` state, and when I send a new message, it will receive and consume at the same time，this means that there are two messages being processed parallelly，is there any way to avoid this？

**Comment by li-zheng-hao** [comment]
maybe i need add a global thread lock

**Comment by yang-xiaodong** [comment]
Don't execute tasks or jobs in consumer for more than 10 seconds, what you need is Quartz or Hangfire!

**Comment by li-zheng-hao** [comment]
Can you please explain the reason? Our current scenario is as follows：

when webapi service receive a http request , it will push a computing task to  a random one of the compute nodes，and for some technical reasons, each compute node can only run one task at the same time，like below：

![image](https://user-images.githubusercontent.com/22129824/197306838-bf0bb876-7416-43f4-af74-3d32638675ee.png)

Honestly, if I were to switch to a timer for this, I would need to take into account a lot of issues such as retrying after failure, message distribution, etc., so why can't I use CAP here? Are there any problems with executing long tasks?

**Comment by yang-xiaodong** [comment]
CAP consumers are not designed for long-running tasks, which can lead to out-of-order and repeated execution

**Comment by li-zheng-hao** [comment]
> CAP consumers are not designed for long-running tasks, which can lead to out-of-order and repeated execution

I have considered these situations，below is my opinion：

1. order is not important to our task
2. in  business code, using a unique id can check whether the message has been consumed，and repeat consumption is not a problem for this task
3. the task processing time is not very long, about 20 seconds on average, and we are still continuing to optimize this speed

So  I think i dont need to use hangfire, anyway, thanks for your reminder
