### ISSUE TITLE
关于在.net core mvc 主线程中启用实时订阅的问题？

### ISSUE THREAD

**Issue by tiandao-dongguan** [dotnetcore/CAP#123]
首先，感谢cap微服务框架，我一直在关注这个框架的进展。现有一个问题请教：
关于在.net core mvc 主线程中启用实时订阅的问题？

目前我们的系统也有实时订阅发布机制，使用的是国外的一个库，采用的是redis的订阅发布机制，具体办法是在主项目的startup启动订阅，这样可以保证订阅的实时性：如下：
`subscriber.Subscribe<string>(channel, (value) =>
            {
                //cacheClient.Add("teststring", "222222", DateTimeOffset.Now.AddMinutes(10));
                loger.LogInformation("日志写入订阅的数据："+ value);
                try
                {   
                    JObject reciveMessage = JObject.Parse(value);
                    JToken reciveMessageData = reciveMessage.SelectToken("MesssageData");
                    JToken reciveMessageType = reciveMessage.SelectToken("MesssageType");
                    cacheClient.Add(reciveMessageType.ToString(), reciveMessageData.ToString());
                }
                catch (Exception e)
                {
                    loger.LogInformation("订阅异常：" + e.Message);
                }`

看到cap的例子，都是在controller中进行订阅的，这样没有实时特性，web应用本身就是多线程的，对于我们目前的解决方案(redis实时订阅)，redis订阅客户端是单例实现的，这样保证了在多线程环境中，始终只有一个redis连接，不会造成资源的浪费（对于.net web的回收，导致连接中断，我们有自己的解决方案）。

那么，想问问，
1.cap如何才能做到在.net core web中实现实时订阅的呢
2.为了避免重复tcp连接，如何保证多线程环境下连接的唯一性。
3.kakka或者rabbitmq，假如订阅端异常重新启动后，是如何终止会话，避免多次订阅造成的连接数过多的问题。
（场景：订阅服务器启动订阅后，会和消息服务器建立一个连接，当订阅端意外重启后，服务端的连接不会终止，而是产生一个新的连接。除非客户端主动发出取消订阅操作）

**Comment by yuleyule66** [comment]
首先，纠正一个问题，CAP不是微服务框架，而是微服务架构中的一个基础设施。
然后我开始回答你的问题：
1、我没有看明白实时订阅是什么意思？ 如果指的是动态增加消费者的话，CAP没有提供支持，因为在微服务中也不需要。

2,3 问题属于Kafka或者RabbitMQ C#客户端驱动的范畴了，具体可以去相应客户端驱动查找相关资料。

**Comment by tiandao-dongguan** [comment]
无语~
