### ISSUE TITLE
CAP仪表板消息超长UI展示问题

### ISSUE THREAD

**Issue by ZhaoYis** [dotnetcore/CAP#1231]
CAP仪表板消息超长UI展示问题
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/22954818/199641308-dac15c31-1c2b-40a9-9ea2-7f71b1ae8e37.png">

**Comment by yang-xiaodong** [comment]
Thanks for your feedback, but we have no plan to fix it now.

**Comment by ZhaoYis** [comment]
数量显示的小标签没有显示：
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/22954818/200117164-24af9ef7-c803-4c5b-b2e8-4137766e97aa.png">

另外查询数据的时候比较慢，数据库数据量：
<img width="498" alt="image" src="https://user-images.githubusercontent.com/22954818/200117486-e02dbf65-ebf0-48af-be93-476a0f158e63.png">
