### ISSUE TITLE
Messages are not getting consumed before the consumer class creation

### ISSUE THREAD

**Issue by dylangrijalva** [dotnetcore/CAP#1234]
I'm just wondering if there is a way to re-queue messages which are not consumed. I ask this since I have implemented the consumer class after publishing the message, and I expected that unhandled messages will be handled after they found a consumer implementation. But it seems not possible, you have to implement first the consumer before publishing the message. I know this is a dumb question and for sure I have to do it that way, but I just want to know if there's a way to handle those messages that were published before the ACTUAL creation of the consumer class.

**Comment by yang-xiaodong** [comment]
If you are using Kafka, the default behavior is what you said.

**Comment by dylangrijalva** [comment]
I'm not using Kafka, I tried with Redis Stream and Rabbit MQ, and messages are only consumed when there is a handler, but If I publish the messages before creating the handler, the messages won't be consumed after the handler is created, I didn't find any related in the official docs. The only approach is to manually find the unconsumed messages in the dashboard and re-queue them, but it's not practical.

**Comment by yang-xiaodong** [comment]
The publishing and consumption of CAP are separated, and the publisher does not know whether the consumer exists, so it depends on the default behavior of the Broker. For RabbitMQ, if the message reaches the Exchange and does not find the consumer queue, the message will be discarded. For RedisStreams, only options are provided from the beginning of the stream or from the newly arrived message, our default behavior is to start reading from the new message
