### ISSUE TITLE
Problems with multiple subscriptions

### ISSUE THREAD

**Issue by szlee** [dotnetcore/CAP#124]
```
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddTransient<ITestMessage, TestMessage>();
    //services.AddTransient<ITestMessage2, TestMessage2>();
    services.AddCap(x => {  });
}
```

The above code works well after commenting out one subscription. However,  there is a puzzling problem when I try to open two subscriptions. Publishers can publish successfully, but subscribers can't receive any messages, I'm very confused. Is it the wrong way I use it? 
See the code below：
```
private async Task SendRequest()
{
    using (var trans = context.Database.BeginTransaction())
    {
        await publisher.PublishAsync("Test.Message", "");
        ...
        trans.Commit();
    }
}

public interface ITestMessage
{
    void TestSubscriber(string text); 
}

public class TestMessage : ITestMessage, ICapSubscribe
{
    [CapSubscribe("Test.Message")]
    public void TestSubscriber(string text)
    {
    }
}
```

**Comment by yuleyule66** [comment]
@szlee  Hello,
If you have multiple subscribers you need to set up different groups like `CapSubscribe("Test.Message", Group = "test1")` and `CapSubscribe("Test.Message", Group = "test2")` , do you do that?

**Comment by szlee** [comment]
How do I set up the different groups for the subscriptions. Is it in the Cap Option. Can you put a sample code? Thanks

**Comment by yuleyule66** [comment]
```
public interface ITestMessage
{
    void TestSubscriber(string text); 
}

public class TestMessage : ITestMessage, ICapSubscribe
{
    [CapSubscribe("Test.Message", Group = "test1")]
    public void TestSubscriber(string text)
    {
    }
}
```
and 

```
public interface ITestMessage2
{
    void TestSubscriber(string text); 
}

public class TestMessage2: ITestMessage2, ICapSubscribe
{
    [CapSubscribe("Test.Message", Group = "test2")]
    public void TestSubscriber(string text)
    {
    }
}
```

**Comment by szlee** [comment]
Thanks for your reply. I tried the above methods, it seems that still can not... But I added the following line of Italic code, which works fine...
public void ConfigureMotionServices(IServiceCollection services)
{
    services.AddTransient<ITestMessage, TestMessage>();
    services.AddTransient<ITestMessage2, TestMessage2>();
    _services.AddCap(x => { x.DefaultGroup = "Test"; });_
}

I have a question, the above code only uses one group, if I need more than one group, how to set the options? Like this?
public void ConfigureMotionServices(IServiceCollection services)
{
    services.AddTransient<ITestMessage, TestMessage>();
    services.AddTransient<ITestMessage2, TestMessage2>();
    _services.AddCap(x => { x.DefaultGroup = "Test"; });_
    services.AddTransient<ITestMessage3, TestMessage3>();
    services.AddTransient<ITestMessage4, TestMessage4>();
    _services.AddCap(x => { x.DefaultGroup = "Test2"; });_
}

**Comment by yuleyule66** [comment]
No, You can't configuration like this. The `DefaultGroup ` represents a group in Kafka or a queue in RabbitMQ.

If you follow what I'm saying and it not works , please provide your environment and configuration.

**Comment by yuleyule66** [comment]
There are too many mistakes in your configuration.

**Startup.cs**

```
public void ConfigureMotionServices(IServiceCollection services)
{
    services.AddDbContext<McsDbContext>(option => option.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

    services.AddTransient<ITestMessage, TestMessage>();
    services.AddTransient<ITestMessage2, TestMessage2>();

    services.AddCap(x => { 
        x.UseEntityFramework<McsDbContext>();
        x.UseRabbitMQ("localhost");
    });

    services.AddMvc();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    if (env.IsDevelopment()) 
        app.UseDeveloperExceptionPage();
    
    app.UseMvc();

    app.UseCap(); 
}

```

**ITestMessage.cs** and **TestMessage.cs**

```
public interface ITestMessage
{
    void TestSubscriber(string text); 
}

public class TestMessage : ITestMessage, ICapSubscribe
{
    [CapSubscribe("Test.Message", Group = "test1")]
    public void TestSubscriber(string text)
    {
    }
}
```


**ITestMessage2.cs** and **TestMessage2.cs**

```
public interface ITestMessage2
{
    void TestSubscriber(string text); 
}

public class TestMessage2: ITestMessage2, ICapSubscribe
{
    [CapSubscribe("Test.Message", Group = "test2")]
    public void TestSubscriber(string text)
    {
    }
}
```

**Comment by szlee** [comment]
Yes, the above code can run perfectly. You solved my problem. Thanks a lot！
