### ISSUE TITLE
 _selector.GetCandidatesMethodsOfGroupNameGrouped()； There's a bug

### ISSUE THREAD

**Issue by HandsomeBoy01** [dotnetcore/CAP#1242]
If my project doesn't have the [CapSubscribe()] attribute, Rabbit won't connect, and when I send a message, no other project will receive it

Please confirm it.

**Comment by HandsomeBoy01** [comment]
no problem

**Comment by yang-xiaodong** [comment]
Closed by https://zhuanlan.zhihu.com/p/25795393
