### ISSUE TITLE
Pipelining of requests forbidden

### ISSUE THREAD

**Issue by wch66** [dotnetcore/CAP#1243]
发布消息时发生错误
场景使用：使用Jmeter测试接口，100个线程，10秒钟，循环10次，发生以下错误，降低线程数为10测试未报错，有改善方案么？
当前使用版本：6.2.0
错误信息如下：
2022-11-28 16:18:04.578 +08:00 [ERR] An exception occurred while publishing a message, reason:Failed : . message id:8594427798287806577
DotNetCore.CAP.Internal.PublisherSentFailedException: Pipelining of requests forbidden
 ---> System.NotSupportedException: Pipelining of requests forbidden
   at RabbitMQ.Client.Impl.RpcContinuationQueue.Enqueue(IRpcContinuation k)
   at RabbitMQ.Client.Impl.ModelBase.Enqueue(IRpcContinuation k)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_ConfirmSelect(Boolean nowait)
   at RabbitMQ.Client.Impl.ModelBase.ConfirmSelect()
   at RabbitMQ.Client.Impl.AutorecoveringModel.ConfirmSelect()
   at DotNetCore.CAP.RabbitMQ.RabbitMQTransport.SendAsync(TransportMessage message)
   --- End of inner exception stack trace ---

**Comment by wch66** [comment]
有重复多次消费的情况，发送数据总共1000组，最终消费入库数据有1328条

**Comment by wch66** [comment]
消息发布如下
![image](https://user-images.githubusercontent.com/36251958/204262717-db12b34a-17bb-4e73-8e6d-527b5f307144.png)

消费端如下：
![image](https://user-images.githubusercontent.com/36251958/204262804-b4189f42-467e-44a9-9fec-de574812e60f.png)

**Comment by yang-xiaodong** [comment]
you need add `await` if using PublishAsync

**Comment by wch66** [comment]
好的 谢谢  我测试一下

**Comment by wch66** [comment]
刚测了一下还是不行，是否还有其他的操作呢？还是我的写法有问题？
![image](https://user-images.githubusercontent.com/36251958/204266409-fdd2ae4b-7b8d-4c26-8cc1-fa8fde41c4a9.png)

![image](https://user-images.githubusercontent.com/36251958/204266227-27ffb2d7-c673-4c16-8e5b-d7de75486d98.png)

**Comment by yang-xiaodong** [comment]
你可能需要配合回答我们一下问题
1、你能在 7.0 版本重现吗？我需要确认是否由发布确认导致。
2、 RabbitMQ 控制台显示有多少Channels?
3、JMeter 命令提供一下？
4、 提供 service.AddCap 的配置内容

**Comment by wch66** [comment]
你好，
1.我当前使用的版本是6.2.0,若需要在7.0测试的话，我需要将项目整体升级
2.RabbitMQ 显示Channels是4条，如下
![image](https://user-images.githubusercontent.com/36251958/204269139-d915de20-75dc-46be-a91c-93003e2d4b5e.png)
3.Jemeter 配置如下
![image](https://user-images.githubusercontent.com/36251958/204269237-fd2caae5-70f4-4f83-a5fe-c7b7b956a041.png)
![image](https://user-images.githubusercontent.com/36251958/204269298-b7ca15f2-bf1e-47eb-a4ed-145f8d11b36f.png)
4.Cap基本上都是采用的默认配置
![image](https://user-images.githubusercontent.com/36251958/204269440-07e3cf39-cfc5-4c94-b798-8d29b8295739.png)

**Comment by wch66** [comment]
以上测试，只有请求很频繁时会出现，时间拉长就会好很多，CPU和内存皆未占满

**Comment by yang-xiaodong** [comment]
你不需要升级项目，升级CAP即可

**Comment by wch66** [comment]
你好，当前升级到7.0版本之后测了一次，没有上述问题，但是出现一个通道创建失败，这是不是因为电脑资源占满的原因？
![image](https://user-images.githubusercontent.com/36251958/204273548-da5521d8-ecc8-42f4-b37a-80d3177e66ce.png)
![image](https://user-images.githubusercontent.com/36251958/204273736-46d05db0-d7d2-4070-a956-316ebd389eb8.png)

**Comment by yang-xiaodong** [comment]
我这边无法复现，不过我大概预测是由于你的机器配置太低或网络太差导致的。

**Comment by wch66** [comment]
7.0版本 性能好很多，相同的配置环境，7.0版本处理效率高太多了，而且没有出现之前的问题了

**Comment by wch66** [comment]
好的，后续增加配置之后，我再进行同等测试，我上7使用

**Comment by yang-xiaodong** [comment]
OK, 那我先关掉了，后续如果出现可以reopen
