### ISSUE TITLE
Error when published Winform with 'Produce Single File'

### ISSUE THREAD

**Issue by KayakFisher205** [dotnetcore/CAP#1245]
Running the 7.0.0 Version, Net Core 7.0, Hybrid (Winform/WPF).

Before, the latest update, I didn't have any issues. With the current version, I get the following error:
System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at DotNetCore.CAP.CapMarkerService..ctor(String name)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddCap(IServiceCollection services, Action`1 setupAction)
   at MeltShopChemistry.Program.ConfigureServices()

When I publish, I have the Produce Single File checked.
If I copy the Build folder over, the program runs so it seems related to the Produce Single File. Maybe something is not being passed when its created.

If you need more info, let me know.

![image](https://user-images.githubusercontent.com/71768711/204317991-ce1d2b86-69ca-4b85-b4a6-1f9d2f9b2d2e.png)

**Comment by yang-xiaodong** [comment]
In your project, this line throw excetion, you can registe  `CapMarkerService`  manual
`FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).ProductVersion`

Add
`services.TryAddSingleton(new CapMarkerService("CAP"));` 
before `service.AddCap`

**Comment by KayakFisher205** [comment]
I tried adding the line but I still got the error. For now, I'm publish with all the files until the fix is available.

**Comment by KayakFisher205** [comment]
Any update when a Beta version or updated version might be released?

**Comment by yang-xiaodong** [comment]
Fixed in [7.0.1](https://github.com/dotnetcore/CAP/releases/tag/v7.0.1)
