### ISSUE TITLE
Exception when setting up Cap

### ISSUE THREAD

**Issue by paillave** [dotnetcore/CAP#1246]
By simply following the tutorial and running it, I get an exception by calling `AddCap`:
```
Exception thrown: 'System.TypeLoadException' in DotNetCore.CAP.dll: 'Method 'SendAsync' in type 'Savorboard.CAP.InMemoryMessageQueue.InMemoryMqTransport' from assembly 'Savorboard.CAP.InMemoryMessageQueue, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'
```

Here is the content of my Program.cs:

```csharp
using Savorboard.CAP.InMemoryMessageQueue;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
builder.Services.AddCap(x =>
    {
        x.UseInMemoryStorage(); // This works fine
        x.UseInMemoryMessageQueue(); //This works fine
    }); // <=============================THE EXCEPTION IS THROWN HERE

var app = builder.Build();
app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();
app.Run();
```

I joined source of `Savorboard.CAP.InMemoryMessageQueue` in my solution to debug it, and here is my finding:

 - `UseInMemoryMessageQueue` is correctly and successfuly called, with the `RegisterExtension` method properly called as well: https://github.com/yang-xiaodong/Savorboard.CAP.InMemoryMessageQueue/blob/95072bf3147e037d21f53370e320293e40b06f16/src/Savorboard.CAP.InMemoryMessageQueue/CAP.Options.Extensions.cs#L14
 - `AddServices` of `InMemoryMqOptionsExtension.AddServices` is never called. This is why the exception is raised by `AddCap` as `InMemoryMqTransport` is never injected: https://github.com/yang-xiaodong/Savorboard.CAP.InMemoryMessageQueue/blob/95072bf3147e037d21f53370e320293e40b06f16/src/Savorboard.CAP.InMemoryMessageQueue/CAP.InMemoryMqOptionsExtension.cs#L17

**Comment by yang-xiaodong** [comment]
Are you using CAP version 7.0?

`Savorboard.CAP.InMemoryMessageQueue` support CAP 7.0 just now.

**Comment by paillave** [comment]
> Are you using CAP version 7.0?
> 
> `Savorboard.CAP.InMemoryMessageQueue` support CAP 7.0 just now.

I used version 7.0 indeed, and I realised that the version of `Savorboard.CAP.InMemoryMessageQueue` (6.0) that happened to be the latest at the moment I tried could not work with version 7.0 of CAP. 
Important to mention in the doc to ensure this! :)
