### ISSUE TITLE
Add ability to support configurable  subscriber

### ISSUE THREAD

**Issue by charleypeng** [dotnetcore/CAP#1247]
If we have multiple workers in a swarm or Kubernetes,  is it possible to change the subscriber in a config file , case as below:

in normal Dotnet.Cap mode
`[CapSubscribe("store.**.data")]
Public Task StoreData(object data){...}`

In dynamic mode, add a subscriber dynamically in a config file when load the host app in appsetting.json:
`
{
    "subscribers":
    [
       {
            "topic" : "store.data1", 
            "group" : "v1",
            "bind-method" : "Namespace.SampleClass.StoreData"
       }
    ]
}
`

**Comment by yang-xiaodong** [comment]
We're not suppot it directly, but your can impl your own `IConsumerServiceSelector`  to find the subscriber from configuration file.
