### ISSUE TITLE
View other's instance dashboard

### ISSUE THREAD

**Issue by robert-han** [dotnetcore/CAP#1250]
Runtime : .net7.0
CAP : 7.0.0
Storage : SqlServer2019
Broker: RabbitMQ:3
Dashboard作为微服务独立部署时，“实时度量图表”和“订阅者”无数据显示。
我想用Dashboard同时监控多个微服务。

**Comment by xiangxiren** [comment]
Dashboard展示的是当前服务的订阅列表以及发送、消费数据

**Comment by robert-han** [comment]
可否支持独立部署一个dashboard监控EventBus运行情况呢，在每个微服务上跑一个dashboard似乎也不太合适。

**Comment by yang-xiaodong** [comment]
see https://cap.dotnetcore.xyz/user-guide/zh/monitoring/consul/
