### ISSUE TITLE
Question about ensuring order of messages

### ISSUE THREAD

**Issue by JasonWangCY** [dotnetcore/CAP#1251]
Hello there, thank you for developing CAP! I am using it to develop a project that requires at-least-once deliveries of some data messages to Kafka. My project creates messages in while loops (each loop producing one message). 

Now, my case is the following:
- my message A is saved to the database, but fails to publish to Kafka (maybe due to program crash)
- the StatusName of message A in the cap.Published table is "Scheduled"
- I restart my program, and let's say it moves to the next loop to send message B
- In this case, I noticed that in the CAP transaction scope, 
     1. it will publish message B first, 
     2. then it gets/queries for "Unscheduled" messages in cap.Published, 
     3. and then message A is published.

Hence, the original order of message A -> B now becomes message B -> A.

May I ask if there is some way to keep my original order or am I not implementing correctly? It would be nice if "Scheduled" messages can be published first (according to the "Added" date) before publishing newer messages.

Thank you!

**Comment by yang-xiaodong** [comment]
We cannot  guarantee the delivery order  and Idempotnce in the exception scenes

**Comment by JasonWangCY** [comment]
> We cannot guarantee the delivery order and Idempotnce in the exception scenes

I see, thanks for the prompt response
