### ISSUE TITLE
rabbitmq 挂了几个小时，请问怎么补偿消费消息？

### ISSUE THREAD

**Issue by mswinner** [dotnetcore/CAP#1252]
[CAP 3.1.1]    .net core 3.1  sqlserver2019数据库

昨天rabbitmq服务中断了几小时，导致没正常通讯
Published 有记录 都是successed状态，但Received 没有对应那几个小时的记录，也没有非successed的状态记录。
有没应急的办法，比如是不是 可以修改 Published 表 的successed状态为failed，就可以触发自动补偿机制，让received有记录，进而消费？

**Comment by yang-xiaodong** [comment]
Yes
