### ISSUE TITLE
Redis streams json serialize exception for version 7.0

### ISSUE THREAD

**Issue by zhangbo27** [dotnetcore/CAP#1254]
测试例子程序Samples.Redis.SqlServer时提示错误，调试时发现System.Text.Json序列化message.Body提示异常
The type 'System.ReadOnlySpan`1[System.Byte]' of property 'Span' on type 'System.ReadOnlyMemory`1[System.Byte]' is invalid for serialization or deserialization because it is a pointer type, is a ref struct, or contains generic parameters that have not been replaced by specific types.”
错误代码位置 DotNetCore.CAP.RedisStreams 下 TransportMessage.Redis 文件  private static RedisValue ToJson(object? obj) 方法中 return JsonSerializer.Serialize(obj, new JsonSerializerOptions(JsonSerializerDefaults.Web));

**Comment by yang-xiaodong** [comment]
Fixed in v7.0.2
