### ISSUE TITLE
7.0.2 Dashboard Re-execute NullReferenceException

### ISSUE THREAD

**Issue by coolyuwk** [dotnetcore/CAP#1259]
![image](https://user-images.githubusercontent.com/6112111/211508290-bd55f95c-6876-49e3-93f2-3771f786e7c5.png)

![1](https://user-images.githubusercontent.com/6112111/211507946-59995226-0222-4749-b685-5cc41fc90e9c.gif)

**Comment by yang-xiaodong** [comment]
Please show your message body json content.

**Comment by coolyuwk** [comment]
> 
**Description**
This problem was found on MSSQL

**Link to public reproduction project repository**

https://github.com/coolyuwk/DashboardRe-executeNullReferenceException.git

MSSQL Version

![image](https://user-images.githubusercontent.com/6112111/212013696-e60d1a92-bef2-4e2e-ab40-01e6ad5c3793.png)

**Comment by yang-xiaodong** [comment]
Thanks for your feedback , It's a bug.

SQL Server is [missing](https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.SqlServer/IMonitoringApi.SqlServer.cs#L286) set the `Origin` file value when get message from storage,

Would you like to submit a PR to fix it? Just like mysql 

https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.MySql/IMonitoringApi.MySql.cs#L268

**Comment by yang-xiaodong** [comment]
Fixed in  [v7.0.3](https://github.com/dotnetcore/CAP/releases/tag/v7.0.3)
