### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by Wscar** [dotnetcore/CAP#126]
我在我的程序中，先添加了Mysql的包，后来添加了dotnetcore.cap.Mysql的包，会报类型同时存在于mysql.Data和MysqlConnector中。
![image](https://user-images.githubusercontent.com/23281760/39534752-e63cd416-4e64-11e8-858f-a16136284bdc.png)

**Comment by yuleyule66** [comment]
MySql 驱动建议使用 [MySqlConnector](https://github.com/mysql-net/MySqlConnector)
