### ISSUE TITLE
关于cap.Redis连接池设计的疑问

### ISSUE THREAD

**Issue by BlackWhiteIce** [dotnetcore/CAP#1262]
cap.Redis发布订阅的实现基于StackExchange.Redis实现, StackExchange.Redis.现在CAP的连接池设计会初始化多个ConnectionMultiplexer.但是官方文档的推荐用法ConnectionMultiplexer 是被需要被设计为重复使用的,与官方文档中推荐的使用方法不符,会不会出问题? 
博客园某次的故障公告就是将ConnectionMultiplexer被设计成连接池,使用了多个ConnectionMultiplexer.,导致出现大量的StackExchange.Redis.RedisTimeoutException: Timeout awaiting response
博客园故障公告地址:https://www.cnblogs.com/cmt/p/16405164.html. 
而且可不可以参考一下 Microsoft.Extensions.Caching.StackExchangeRedis 的初始化设计, 
将ConnectionMultiplexer 的初始化交给外部来实现, 提供一个 类似于ConnectionMultiplexerFactory的委托.因为目前项目中存在其它缓存组件也在使用StackExchange.Redis的,同样会导致ConnectionMultiplexer被创建成多个.

**Comment by yang-xiaodong** [comment]
https://github.com/StackExchange/StackExchange.Redis/issues/1279#issuecomment-584679755

**Comment by BlackWhiteIce** [comment]
谢谢大佬的回复，我大概理解你在考虑什么了，先这样吧
