### ISSUE TITLE
How CAP works with multiple consumers to the same queue?

### ISSUE THREAD

**Issue by rafaelpadovezi** [dotnetcore/CAP#1268]
Hi all,

This is a great lib! Just want to understand how CAP works when I scale out my consumers (they all are consuming from the same queue). Each consumer will process different messages or they will try to process the name message? I'm using RabbitMQ as transport.

**Comment by yang-xiaodong** [comment]
Hi,

When you scale out consumers in RabbitMQ, each consumer consumes messages from the same queue in parallel. This means that multiple consumers can process messages from the same queue at the same time, increasing the overall throughput of your system.

In RabbitMQ, messages are sent to queues, and consumers subscribe to these queues to receive messages. When a message is sent to a queue, it remains in the queue until a consumer retrieves it and acknowledges that it has processed the message.

When you scale out consumers, each consumer will have its own connection to the RabbitMQ broker and will create its own channel to communicate with the broker. Each consumer will subscribe to the same queue and start consuming messages from the queue.

RabbitMQ will distribute the messages from the queue among the available consumers in a round-robin fashion, meaning that it will send each new message to the next available consumer. This ensures that each message is processed by a different consumer, avoiding duplicates and balancing the load across all consumers.

When a consumer processes a message, it acknowledges the message back to RabbitMQ, which removes the message from the queue. If a consumer fails to process a message, RabbitMQ will keep the message in the queue until another consumer retrieves it. This ensures that no messages are lost and that all messages are eventually processed.

In this way, RabbitMQ enables you to scale out your consumers to handle increasing message processing loads, improving the performance and reliability of your system.

**Comment by yang-xiaodong** [comment]
@rafaelpadovezi  Aha, I'm sorry the above answer is generated by ChatGPT :)

Multiple consumers process the same message because they are in different cap groups, which is the result of design. By default, the group name is the assembly name.  see https://github.com/dotnetcore/CAP#subscribe-group

In CAP, One group corresponds to a Queue of RabbitMQ. RabbitMQ messages will routed to multiple queues through the exchange.
