### ISSUE TITLE
In Dotnet CAP 5.2.0,Unable to resolve service for type 'DotNetCore.CAP.ICapPublisher'

### ISSUE THREAD

**Issue by lokyl** [dotnetcore/CAP#1269]
In ConfigureServices(IServiceCollection services),  I use this code :
    services.BuildServiceProvider().CreateScope().ServiceProvider 
to get ServiceProvider before services.AddCap() for some use, but it fail beacese 
    Unable to resolve service for type 'DotNetCore.CAP.ICapPublisher',as shown in below picture
How can i get correct ServiceProvider before services.AddCap()?Thank you!
![image](https://user-images.githubusercontent.com/31734979/217138950-5e86d38e-5671-4fe5-8650-b2565f457f52.png)

**Comment by yang-xiaodong** [comment]
Obviously, your class depends on `ICapPublisher` and does not use AddCap to inject the interface

**Comment by lokyl** [comment]
Hi,correctly,i have a class depends on ICapPublisher, i alse use AddCap to inject the interface,
but i have some code before AddCap in my ConfigureServices(IServiceCollection services) like below:
`
using var serviceScope = services.BuildServiceProvider().CreateScope();
await serviceScope.ServiceProvider.GetRequiredService<xxx>().xxx(); //(xxx is not realated to  ICapPublisher injected class)
services.AddCap(x =>{xxxx});
`
Before AddCap,"await serviceScope.ServiceProvider" may try to construct the ICapPublisher,it cause Exception because AddCap have not run,Can have a method to avoid construct the ICapPublisher when run "await serviceScope.ServiceProvider"?
Thank you

**Comment by yang-xiaodong** [comment]
How to reproduce? Did you have a demo?

**Comment by lokyl** [comment]
Hi,it's my mistake, i use a framwork named Furion which i tag my injected ICapPublisher class "ITransit" label This cause to autoly register my injected ICapPublisher class before services.AddCap(x =>{xxxx}) so causing the above exception.
But i have another question, can't use the await statement before services.AddCap(x =>{xxxx})?When i use await statement like `await serviceScope.ServiceProvider.GetRequiredService<xxx>().xxx();` before services.AddCap in    startup.cs, i can't see dotcap start log in console and can't open cap dashboard.
Thank you for patience.

**Comment by yang-xiaodong** [comment]
I don't want to answer questions about Microsoft DI here, it's not about CAP
