### ISSUE TITLE
EnableConsumerPrefetch not working for RabbitMQ

### ISSUE THREAD

**Issue by ricardochaves** [dotnetcore/CAP#1270]
According to the [documentation](https://cap.dotnetcore.xyz/user-guide/en/cap/configuration/#enableconsumerprefetch), the option EnableConsumerPrefetch when false (which is the default), should force the consumer to consume one message at a time.

We also saw your [comment in that PR](https://github.com/dotnetcore/CAP/pull/1267#issuecomment-1420196389).

We did a test with [this project](https://github.com/ricardochaves/test-cap) where we can easily see that this is not happening with RabbitMQ.

Please enlighten us on how this option would work for RabbitMQ.

**Comment by yang-xiaodong** [comment]
>When a consumer connects to the queue it gets a batch of messages to process. The amount is given in the prefetch size. While this consumer is working on the messages they get the status unacked.

> Unacked means that the consumer has promised to process them but has not acknowledged that they are processed. When the consumer crashed the queue knows which messages are to be delivered again when the consumer comes online. When you have multiple consumers the messages are distributed among them.

https://stackoverflow.com/questions/31915773/rabbitmq-what-are-ready-and-unacked-types-of-messages

This means that if a consumer is connected to the queue, the Ready message will become UnAcked, and if it is disconnected, the UnAcked message will return to Ready

**Comment by ricardochaves** [comment]
It happens, but it is only the correct scenario for some cases.
RabbitMQ has extensive [documentation](https://www.cloudamqp.com/blog/how-to-optimize-the-rabbitmq-prefetch-count.html#how-to-set-the-correct-prefetch-value) on the topic. See this sentence:

> If you have many consumers and/or long processing time, we recommend setting the prefetch count to one (1) so that messages are evenly distributed among all your workers.

It is essential that we can configure the CAP for unusual scenarios.
The PR I mentioned above can solve this.
