### ISSUE TITLE
collection of all messages in  Unacked in rabbitmq

### ISSUE THREAD

**Issue by cagataykiziltan** [dotnetcore/CAP#1275]
I am using dotnetcore cap with rabbitmq and try to process almost 30k message.As soon as 30 k messages are published, 30 k of them are transferred to Unacked instead of piling up in the queue, and problems are experienced when there is no response for a while. Is there a way to process these messages from rabbit mq ready status without putting them into memory queue?

**Comment by yang-xiaodong** [comment]
Yes, you can use `BasicQos` option to control the prefetch size, see #1267

**Comment by nunorelvao** [comment]
Hi @yang-xiaodong , any idea when can we expect 7.1.0 to be released fully as stable nuget? Currently updating projects and in need for this options but cannot use pre-release version in PRD. Thanks.

**Comment by cagataykiziltan** [comment]
we are getting while reexecuting and during retry

index.219b11d6.js:51          POST https://payment-payout-consumer.development.getirapi.com/

 Uncaught (in promise) Error: Request failed with status code 500
    at Bv (index.219b11d6.js:50:6981)
    at Lv (index.219b11d6.js:50:7164)
    at XMLHttpRequest.I (index.219b11d6.js:51:1659)
index.219b11d6.js:51

**Comment by yang-xiaodong** [comment]
> Hi @yang-xiaodong , any idea when can we expect 7.1.0 to be released fully as stable nuget? Currently updating projects and in need for this options but cannot use pre-release version in PRD. Thanks.

We're introducing new features, we released preview and need time to get feedback, maybe in the next week, I'm not sure

**Comment by yang-xiaodong** [comment]
Keep the thread clean, please open a new issue for other questions
