### ISSUE TITLE
reexecute error in 7.1 preview

### ISSUE THREAD

**Issue by cagataykiziltan** [dotnetcore/CAP#1277]
hi, when i try to reexecute failed messages with dashboard in 7.1 preview. ı am getting below error

index.219b11d6.js:51          POST https://xxxxxxx.xxxxxx.xxxxx.com/cap/api/received/reexecute 500
(anonymous) @ index.219b11d6.js:51
Uv @ index.219b11d6.js:51
j7 @ index.219b11d6.js:51
Promise.then (async)
Ju.request @ index.219b11d6.js:51
Ju.<computed> @ index.219b11d6.js:51
(anonymous) @ index.219b11d6.js:50
reexecute @ Received.65c094fb.js:1
wa @ index.219b11d6.js:5
r @ index.219b11d6.js:5
BB.a._wrapper @ index.219b11d6.js:5

index.219b11d6.js:50 Uncaught (in promise) Error: Request failed with status code 500
    at Bv (index.219b11d6.js:50:6981)
    at Lv (index.219b11d6.js:50:7164)
    at XMLHttpRequest.I (index.219b11d6.js:51:1659)

**Comment by yang-xiaodong** [comment]
Plseae show your server error log

**Comment by cagataykiziltan** [comment]
ı am using rabbitmq 6.4.0 and mongodb 2.18

DotNetCore.CAP.Processor.Dispatcher[0]
      An exception occurred when invoke subscriber. MessageId:3415318299566931969
      System.NullReferenceException: Object reference not set to an instance of an object.
         at DotNetCore.CAP.Messages.MessageExtensions.GetName(Message message)
         at DotNetCore.CAP.Internal.SubscribeExecutor.ExecuteAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)

**Comment by yang-xiaodong** [comment]
Same as [#1259](https://github.com/dotnetcore/CAP/issues/1259#issuecomment-1379980226),  would you like to submit a PR?

**Comment by yang-xiaodong** [comment]
Fixed in 7.1.0-preview-194230942
