### ISSUE TITLE
CAP的依赖与Winform的UI设计器依赖冲突

### ISSUE THREAD

**Issue by gudieaofei** [dotnetcore/CAP#1280]
版本
CAP：v7.0.1
Winform：.net6.0

一旦winform引用的类库依赖于CAP，winform的设计器就会报以下错误，并且界面一直显示：正在加载设计器...
fail: Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
fail: File name: 'Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
fail: at Microsoft.DotNet.DesignTools.Server.Program.Main(String[] args, IEnumerable`1 designTimeAssemblies, Action fixUpNetTypes)
fail: at DesignToolsServerX64.Program.Main(String[] args)

**Comment by yang-xiaodong** [comment]
![image](https://user-images.githubusercontent.com/8205994/221150163-00ad2a7e-bc9f-4289-98a3-54ea9a8d487b.png)

**Comment by gudieaofei** [comment]
确认问题了，是 DotNetCore.CAP.Dashboard 导致的，不引入这个就没事

**Comment by gudieaofei** [comment]
刚刚又试了下，即使不引入DotNetCore.CAP.Dashboard，仅仅引入了DotNetCore.CAP，但只要在代码中调用了AddCap()，就会出现同样的错误

**Comment by yang-xiaodong** [comment]
Dashboard is built based on asp.net core does not support winform

**Comment by gudieaofei** [comment]
哪怕仅仅引入了DotNetCore.CAP，但只要在代码中调用了AddCap()，就会出现同样的错误，说到底就是CAP与Winform设计器默认的Microsoft.Extensions.Logging.Abstractions版本不一样导致的

**Comment by yang-xiaodong** [comment]
Show me how to config CAP for winform in  your project?

**Comment by gudieaofei** [comment]
呃，是因为我在winform项目的csproj文件加了以下代码导致的
`<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>`
