### ISSUE TITLE
Configurating CAP to use Schema Registry with Kafka

### ISSUE THREAD

**Issue by RahulPariharPAR** [dotnetcore/CAP#1282]
Configurating CAP to use Schema Registry with Kafka. I was not able find anything in configuration

**Comment by yang-xiaodong** [comment]
Hi, We have no plans to support this feature

**Comment by esskar** [comment]
Is there a different best-practice to produce complex messages? I see that the kafka producer produces Message<string, byte[]> ... what is the best way to do protobuf serialization? just do the serialization and call ICapProducer with that byte[]?
what about complex keys?

**Comment by yang-xiaodong** [comment]
> Is there a different best-practice to produce complex messages? I see that the kafka producer produces Message<string, byte[]> ... what is the best way to do protobuf serialization? just do the serialization and call ICapProducer with that byte[]? what about complex keys?

@esskar 
Fully leveraging the features of a specific Broker is not our design goal. We aim to provide higher-level abstractions. If our implementation does not meet your needs (such as delayed sending with RabbitMQ), you will need to implement for customize.
