### ISSUE TITLE
[Help]How can I receive message from other app(e.g. using python ) ?

### ISSUE THREAD

**Issue by charleypeng** [dotnetcore/CAP#1284]
I have to exchange message between an python app and dotnet app, by using RabbitMQ,

is it possible to do this when the dotnet app is using dotnetcore.cap package?

Thanks ^_^

**Comment by mviegas** [comment]
Hi!

Kindly refer to the [Heterogenous System section](https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#heterogeneous-system-integration) of our docs. It is explained there how can CAP consume messages produced by external systems.

**Comment by charleypeng** [comment]
thanks   i made it work
