### ISSUE TITLE
[help]How to handle message over stock using CAP

### ISSUE THREAD

**Issue by charleypeng** [dotnetcore/CAP#1285]
Producer produced too much message that consumer can not store them properly, so in dotnetcore.cap, what is the best way to handle this situation and in the same time,  do not impact the order of the message to be store in database? 

thanks !

**Comment by yang-xiaodong** [comment]
Please use english

**Comment by yang-xiaodong** [comment]
see **https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#data-cleanup**
