### ISSUE TITLE
How to register to consul in console app

### ISSUE THREAD

**Issue by ZhaoYis** [dotnetcore/CAP#1287]
我有一个项目消息发布者使用的是webapi，消费者单独使用控制台应用程序开发的（主要是方便作为windows服务的方式安装），在注册到consul中时发现，必须要配置一个当前服务地址和端口，否则会使用默认的localhost:5000作为当前注册的节点（健康检查地址默认为/cap/api/health）
<img width="442" alt="image" src="https://user-images.githubusercontent.com/22954818/222968135-dc9d8840-361c-433c-af1d-f1bd15d887bd.png">
当然控制台也能够嵌入webapi，使其提供api服务，但是这种方式难免不太优雅，请问可以优化这种注册方式吗？

**Comment by yang-xiaodong** [comment]
Console app does not support dashboard and consul
