### ISSUE TITLE
file scoped namespaces

### ISSUE THREAD

**Issue by Revazashvili** [dotnetcore/CAP#1292]
currently project is partially using file scoped namespaces. 
only several projects: DotNetCore.CAP, DotNetCore.CAP.SqlServer and DotNetCore.CAP.AzureServiceBus.Test are converted to file scoped namespaces, 
should not all projects be converted to file scoped namespaces?

**Comment by yang-xiaodong** [comment]
Hello, this is not urgent and important, maybe a change will be made in a major version in the future
