### ISSUE TITLE
设置了 x.DefaultGroup 后，依然会消费另一个项目里默认组的消息

### ISSUE THREAD

**Issue by xj728** [dotnetcore/CAP#1298]
A，B两个项目，都通过依赖注入的方法注入了服务CAPService，
A项目用的默认Group
B项目用的自定义Group，设置了 x.DefaultGroup = “Group2

CAPService里有一个方法
 [CapSubscribe("test.create")]
  public void Create(Customer customer)
  {}

如果A项目执行： publisher.PublishAsync("test.create",

结果事A，B两个项目都会消费test.create这个方法，分组没有作用，不应该事默认组才消费的吗？

**Comment by Jameszyq** [comment]
我也遇到了这个问题，我的broker 用的是 redis

**Comment by yang-xiaodong** [comment]
设计如此。见：https://github.com/dotnetcore/CAP/blob/master/README.zh-cn.md#%E8%AE%A2%E9%98%85%E8%80%85%E7%BB%84
