### ISSUE TITLE
Kafka partitioning and consumer Client Id property.

### ISSUE THREAD

**Issue by 3ldar** [dotnetcore/CAP#1299]
Hi,
We are using this great library heavily in our projects. And our projects require heavy message processing. So we need multi-core processing. It is known that if you need concurrent processing you need to have partitions in kafka. When you set `ConsumerThreadCount` greater than 1 it will have no effect on the concurrency. As the topics will have just 1 partition created by the CAP. This part is manageable you can of course set the partition count manually via kafka command line tools. But when you do this you need to set the `client.id` for each thread that is consuming. Currently, the library only allows for passing config only in the startup stage, and this config is shared by all the consumers. So we need to be able to configure each consumer id individually. If you can provide a callback (it would be better if an async callback) kind of setting which will determine the client id of the consumer it will super useful. 
If anyone has the same issue as us, we are currently using a workaround that requires setting the `ConsumerThreadCount` to 1 and setting the client id at startup. Instead of having multi-threading in a single app, we are using multiple apps to consume concurrently. This is easy to implement in a k8s environment you can easily increase the pod count. But I don't know about self-hosted applications (In IIS you can also increase the worker process count.). Also, I don't know if it is as efficient as having multiple threads.

**Comment by yang-xiaodong** [comment]
Hi  @3ldar 

Thanks for your feedback, I think this is a feature that can be improved, but I need further clarification from you.

Do you mean that you manually changed the number of kafka partitions by the following command
```
kafka-topics.sh --bootstrap-server localhost:9092 --alter --topic first_topic --partitions 5
```

And you want to change the consumer thread corresponding to the topic partition at runtime ?

> But when you do this you need to set the `client.id` for each thread that is consuming

I know that Kafka specifies consumer thread strategies through `partition.assignment.strategy` configuration. How to specify at runtime by command?

**Comment by 3ldar** [comment]
Hi again,


>  kafka-topics.sh --bootstrap-server localhost:9092 --alter --topic first_topic --partitions 5

This is the exact command I have used. Setting this according to the consumer thread count (or providing another config, which would be way better if it was per-topic configurable) is nice. But the crucial part is `client.id`. The `partition.assignment.strategy` will determine how the clients in the same group will pick or rotate the partitions (and it is ok to set it once at the application startup) but when all the clients have the same id they will share the same offsets and no efficient concurrency will be applied here. (Concurrency would work for different topics well, but not on the same topic. There are many benchmarks about this for kafka.) `client.id` should be set before the consuming starts and it is not necessary to change it at runtime (maybe it should not it might mess up some offsets). 

A singleton service that implements the below interface would work here I think.
````
public interface IKafkaClientIdProvider {
    Task<string> GetClientId();
    Task<string> GetClientId(string groupId); //one of them can be pick here
}
```

 A default implementation like the one below would work :
```
public class DefaultKafkaClientIdProvider {
    int clientIdCounter = 0;
    Task<string> GetClientId() => Task.FromResult($"fancyClient_{i++}");
    Task<string> GetClientId(string groupId) => Task.FromResult($"{groupId}_client_{i++}");
}
```
Me personally will use some state store like redis to determine the clientId for the related group. Because I have a distributed environment, and have many instances accros the kubernetes clusters for the same service.

**Comment by yang-xiaodong** [comment]
Hello,

I did a test.

The `client.id` is not specified and set `ConsumerThreadCount = 3` and set 3 partitions for the test topic, the 3 consumer threads will automatically correspond to the 3 partitions, and the messages will be in concurrent consumption by 3 consumer threads within 3 partitions.


```cs
[CapSubscribe("sample.kafka.postgrsql")]
public void Test2(DateTime value, [FromCap] CapHeader header)
{
    var offset = header["my.kafka.offset"];
    var partition = header["my.kafka.partition"];
    var consumerId = header["ConsumerId"][^2..];
    Console.ForegroundColor = ConsoleColor.Red;
    Console.WriteLine("Subscriber output message: " + value);
    Console.WriteLine("ConsumerId: " + consumerId + ", Offset: " + offset + ", Partition: " + partition);
}
```
> header["ConsumerId"]  generated when the `KafkaConsumerClient` created and add to the header when received message.

The consumer output:
```
Subscriber output message: 2023/3/26 21:07:20
ConsumerId: 92, Offset: 28, Partition: [1]
Subscriber output message: 2023/3/26 21:07:20
ConsumerId: 92, Offset: 29, Partition: [1]
Subscriber output message: 2023/3/26 21:07:37
ConsumerId: 91, Offset: 22, Partition: [0]
Subscriber output message: 2023/3/26 21:07:38
ConsumerId: 91, Offset: 23, Partition: [0]
Subscriber output message: 2023/3/26 21:07:38
ConsumerId: 90, Offset: 14, Partition: [2]
Subscriber output message: 2023/3/26 21:07:38
ConsumerId: 92, Offset: 30, Partition: [1]
Subscriber output message: 2023/3/26 21:07:38
ConsumerId: 92, Offset: 31, Partition: [1]
Subscriber output message: 2023/3/26 21:07:38
ConsumerId: 92, Offset: 32, Partition: [1]
Subscriber output message: 2023/3/26 21:07:38
ConsumerId: 91, Offset: 24, Partition: [0]
Subscriber output message: 2023/3/26 21:07:39
ConsumerId: 90, Offset: 15, Partition: [2]
Subscriber output message: 2023/3/26 21:07:39
ConsumerId: 92, Offset: 33, Partition: [1]
```


When tha app startup and connect to the kafka server, the kafka server will create a new member id for the new consumer , the new consumer (dynamic member) will auto join the group and the server remove the old consumer.

Below is the kafka server log when app connect the the server.

```
2023-03-26 21:06:12 [2023-03-26 13:06:12,156] INFO [GroupCoordinator 1]: Dynamic member with unknown member id joins group cap.queue.sample.kafka.postgresql.v1 in Stable state. Created a new member id rdkafka-cc98ba5e-bd87-4a17-bd22-5f7df8fbbe6b and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
2023-03-26 21:06:12 [2023-03-26 13:06:12,161] INFO [GroupCoordinator 1]: Preparing to rebalance group cap.queue.sample.kafka.postgresql.v1 in state PreparingRebalance with old generation 11 (__consumer_offsets-8) (reason: Adding new member rdkafka-cc98ba5e-bd87-4a17-bd22-5f7df8fbbe6b with group instance id None) (kafka.coordinator.group.GroupCoordinator)
2023-03-26 21:06:12 [2023-03-26 13:06:12,204] INFO [GroupCoordinator 1]: Dynamic member with unknown member id joins group cap.queue.sample.kafka.postgresql.v1 in PreparingRebalance state. Created a new member id rdkafka-a8e28383-146d-4a72-8a22-2ed2b3f87120 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
2023-03-26 21:06:12 [2023-03-26 13:06:12,204] INFO [GroupCoordinator 1]: Dynamic member with unknown member id joins group cap.queue.sample.kafka.postgresql.v1 in PreparingRebalance state. Created a new member id rdkafka-b742d5ad-39cf-492c-949d-31172acbe275 and request the member to rejoin with this id. (kafka.coordinator.group.GroupCoordinator)
2023-03-26 21:06:37 [2023-03-26 13:06:37,223] INFO [GroupCoordinator 1]: Member rdkafka-22d4cb6a-592a-417b-b8e6-132346f96937 in group cap.queue.sample.kafka.postgresql.v1 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
2023-03-26 21:06:37 [2023-03-26 13:06:37,304] INFO [GroupCoordinator 1]: Member rdkafka-49cc36c8-51ce-43bb-b6e4-1c973e3ad508 in group cap.queue.sample.kafka.postgresql.v1 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
2023-03-26 21:06:37 [2023-03-26 13:06:37,304] INFO [GroupCoordinator 1]: Member rdkafka-fdaa4e1b-25f2-421e-b1e0-2bc43e780109 in group cap.queue.sample.kafka.postgresql.v1 has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
2023-03-26 21:06:37 [2023-03-26 13:06:37,305] INFO [GroupCoordinator 1]: Stabilized group cap.queue.sample.kafka.postgresql.v1 generation 12 (__consumer_offsets-8) with 3 members (kafka.coordinator.group.GroupCoordinator)
```

This seems to be exactly what you want, I don't know why you want to specifying the `client.id` ?

**Comment by 3ldar** [comment]
Thanks for all the effort you have done. The first mistake I made is: it should be `consumer.id` not the `client.id`. For the second one; you are right when you did not set a consumer id, the connector assigns a random consumer id and it solves the "consumer id must be unique among the group members". I probably misinterpreted the error I had before and started to overthink it.  The last question remains in my mind and not being so sure. When your consumer which has a randomly generated id is restarted an auto-reset offset situation happens because the new id will be different from the previous depending on the setting your consumer will process all the data again. Like I said I am not so sure about it, I might be messing the `group.id` with the `consumer.id`. If I can have some spare time in the morning I will try to simulate the behavior to prove myself wrong 😃

**Comment by yang-xiaodong** [comment]
#1303 as the subsequent for current issue.
