### ISSUE TITLE
Dashboard and JWT Authentication

### ISSUE THREAD

**Issue by dima-zhemkov** [dotnetcore/CAP#1304]
Hello,

I use JWT authentication and I don't use Cookie nor OpenID connect and it makes me almost impossible to use CAP Dashboard with authentication.

It would be awesome if dashboard home page accepted query parameter and saved them to local storage.

For instance: 
After opening URL `https://mydomain.com/cap/index.html?token=tokenValue...&refreshToken=refreshtokenValue...`
two local storage entries will be added/updated:
```
token = tokenValue...
refreshToken = refreshtokenValue...
```
After that send them in headers with each request.

**Comment by mviegas** [comment]
Hi @dima-zhemkov !

You can leverage ASP.NET Core flexible authentication mechanism to use any authentication and challenge schemes, including custom ones. Please look at the [Custom authentication section](https://cap.dotnetcore.xyz/user-guide/en/monitoring/dashboard/#custom-authentication) in the docs.

**Comment by dima-zhemkov** [comment]
Hi @mviegas!

I've tried it.

It doesn't work without cookies since CAP Dashboard doesn't send auth headers with requests

**Comment by yang-xiaodong** [comment]
Sounds reasonable, since our current `/cap/index.html` needs to be authenticated first, so we need to detect when the access_token is passed from query we need to cancel the authentication for index.html and write token to localstorage.

**Comment by dima-zhemkov** [comment]
Will work on it and prepare PR shortly.

**Comment by yang-xiaodong** [comment]
Fixed in `7.1.1-preview-197551401`
