### ISSUE TITLE
ISubscribeFilter能否支持跳过订阅执行

### ISSUE THREAD

**Issue by witskeeper** [dotnetcore/CAP#1309]
在一些场景，我需要过滤掉一些消息，不去执行订阅消费逻辑。类似这个issue  #1086 中提到类似SampleAsyncActionFilter 的情况。
或者有什么其它可行的方法？

**Comment by yang-xiaodong** [comment]
see https://cap.dotnetcore.xyz/user-guide/zh/cap/filter/#_3

**Comment by witskeeper** [comment]
感谢，问题解决
