### ISSUE TITLE
NATS transport infinity reconnect race condition

### ISSUE THREAD

**Issue by truecooler** [dotnetcore/CAP#1311]
Hi everyone, i have encountered race condition transport reconnect issue with stable reproduction.

**Problem details**
Looks like NATS transport occasionally looses the network connection.
![image](https://user-images.githubusercontent.com/34151727/231475266-aed5ff0e-e65a-4d98-bf4b-0496c53dae23.png)

Investigation showed that there is race condition between consumer restart process and native nats client callback.

1) TransportCheckProcessor occasionally checks transport for healthy: 
![image](https://user-images.githubusercontent.com/34151727/231484556-95412498-920b-4a64-bfce-851882821ae3.png)
https://github.com/dotnetcore/CAP/blob/3f91243458182273695a932bcfea961e6314d94f/src/DotNetCore.CAP/Processor/IProcessor.TransportCheck.cs#L36

2) IConsumerRegister.Default.ReStart calls method Pulse that cancels task cancellation token _cts , sets _isHealthy to true, and calls Execute in order to run consumer:
![image](https://user-images.githubusercontent.com/34151727/231484886-e8f1dafc-0802-4617-a287-1198c08de5f3.png)
https://github.com/dotnetcore/CAP/blob/3f91243458182273695a932bcfea961e6314d94f/src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs#L72

3) Meanwhile already running consumer thread receives _cts cancellation, then calls dispose that causes native nats client to be closed and disposed.
![image](https://user-images.githubusercontent.com/34151727/231486215-9eff0917-d961-4086-af97-835036ebcc49.png)
https://github.com/dotnetcore/CAP/blob/f0fad42b29bdf3994b52adda9161b533ff97e37a/src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs#L150

4) When native nats client closes, it triggers ConnectedEventHandler(looks like typo, Disconnected is implied) event, that calls OnLogCallback that reassigns _isHealthy value to false
![image](https://user-images.githubusercontent.com/34151727/231486735-9f3b7923-81fa-47ac-9509-bdddac5bf36d.png)
![image](https://user-images.githubusercontent.com/34151727/231487080-af2241de-281c-402b-92cb-7c4146d69f8b.png)
https://github.com/dotnetcore/CAP/blob/99c2a8ebe829b41be28908c1d9e625396ec82950/src/DotNetCore.CAP.NATS/NATSConsumerClient.cs#L180
https://github.com/dotnetcore/CAP/blob/3f91243458182273695a932bcfea961e6314d94f/src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs#L312

As a result of race, _isHealthy seems to be false almost the time, that causes infinity reconnect loop

**Reproduction**
See my repo for reproduction: Just set your nats server and run Worker2
https://github.com/truecooler/CAPTest/tree/master/Worker2

Excepted: consumer connects without problem, no network issues

Actual: consumer looses the connection and occasianally prints:
"NATS server connection error."

**Comment by In-Wake** [comment]
I have some problem

**Comment by yang-xiaodong** [comment]
Fixed in 7.1.2-preview-198398083

**Comment by yang-xiaodong** [comment]
Hello @truecooler ,

I see in NuGet that these packages you created incorrectly use the prefix `DotNetCore.CAP` as well as the author of the `Created By` display, would you be willing to remove/modify them in NuGet?

For correct package names you can use prefixes like `TrueCooler.CAP.XXX`

![image](https://github.com/dotnetcore/CAP/assets/8205994/446d96ef-aa2a-4777-a402-c4f04989ddb3)
