### ISSUE TITLE
bug in QueueArguments DotNetCore.CAP.RabbitMQ

### ISSUE THREAD

**Issue by hungvimanh** [dotnetcore/CAP#1312]
Thanks for your library. It's very good.

I have been using DotNetCore.CAP.RabbitMQ in my project that runs on .NET 6.

So I want to configure my queue runs with x-single-active-consumer mode. But I detected a bug in the library.

RabbitMQ's homepage guide the way to configure single active consumer:

Single active consumer can be enabled when declaring a queue, with the x-single-active-consumer argument set to true
```cs
Dictionary<string, object> arguments = new Dictionary<string, object>();
arguments.Add("x-single-active-consumer", true);
ch.QueueDeclare("my-queue", false, false, false, arguments);
But QueueArguments in your library has configured that:
if (!string.IsNullOrEmpty(_rabbitMQOptions.QueueArguments.QueueMode))
{
    arguments.Add("x-queue-mode", _rabbitMQOptions.QueueArguments.QueueMode);
}

if (!string.IsNullOrEmpty(_rabbitMQOptions.QueueArguments.QueueType))
{
    arguments.Add("x-queue-type", _rabbitMQOptions.QueueArguments.QueueType);
}
```
It not run when I configured my project with
opt.QueueArguments = new DotNetCore.CAP.RabbitMQOptions.QueueArgumentsOptions { QueueMode = "x-single-active-consumer" };

Following the guide of RabbitMQ homepage, we can configure RabbitMQ run with multiple x-queue-mode and x-queue-type. Could you help me fix the library to solve my problem.

In my opinion, data type of QueueArguments should is the `Dictionary<string, object?>` like the guide of RabbitMQ homepage to dynamic addition arguments and direct to configure Rabbit connection.

I wait your new version of the library from NCC to fix my problem.

**Comment by yang-xiaodong** [comment]
No, Not all configurations are supported.  x-single-active-consumer I think  you can just set one pod instance to consume the message, I don’t want to add this configuration item here
