### ISSUE TITLE
Support RabbitMQ pattern matching for consumer 

### ISSUE THREAD

**Issue by liuzhenyulive** [dotnetcore/CAP#132]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question 

___
### Question
- What do you want to know?

 我在测试Sample.RabbitMQ.MySql这个例子的时候发送了一个名称为sample.rabbitmq.mysql的消息，有一个#.rabbitmq.mysql的订阅，可是订阅收不到发出的消息，提示：message can not be found subscriber，CAP默认是使用Topic的Exchange吗？ 如果是的话，#能匹配多个字符，#.rabbitmq.mysql应该是能匹配到sample.rabbitmq.mysql的吧？ 谢谢

**Comment by yuleyule66** [comment]
目前查找消费者的时候是按照topic名字精确查找的，没有像RabbitMQ实现队列匹配模式来实现消费者匹配，但是因为RabbitMQ支持这个特性，需要考虑是否支持这个特性...

**Comment by liuzhenyulive** [comment]
好的  希望CAP越来越好！
