### ISSUE TITLE
About Event Link Tracking

### ISSUE THREAD

**Issue by dengyangxi** [dotnetcore/CAP#1321]
Example business scenario: 
![image](https://user-images.githubusercontent.com/30720784/235045492-85e11251-ed53-4363-8710-7bda57189109.png)

Can the dashboard provide a panorama of event link tracking with order number 123456 。

Similar to link tracking 

Enter a custom event ID to query the execution status of the entire event link 

However, the event may last for several days, not on the same HTTP request, or it may be triggered automatically by the service (such as calling other services through pub/sub for overdue payment).

**Comment by dengyangxi** [comment]
仪表板能否提供订单号为：123456  的事件链接跟踪全景  （类似于链接跟踪, 但是 是 跨事件链接跟踪 ）

输入自定义事件ID以查询整个事件链接的执行状态。
即： 自定义事件ID:123456 (订单号：123456)  一共有 5个事件， 能看到 他们的状态 （ 比如： 4个成功，1个失败）。 

然而，该事件可能会持续几天，而不是在同一个HTTP请求上，也可能会由服务自动触发（例如通过pub/sub呼叫其他服务以获得逾期付款，自动取消，发送短信）。

**Comment by dengyangxi** [comment]
**Chat GPT 的回答：** :
`
//1.首先，在发布事件时，需要添加自定义事件ID参数：
_capPublisher.Publish("event-name", eventData, new CapHeader()
{
    ["custom-event-id"] = "123456"
});


//2.在订阅事件时，需要订阅事件名和自定义事件ID，并将事件状态保存到数据库中：
[CapSubscribe("event-name")]
public async Task HandleEvent(EventData eventData)
{
    var customEventId = eventData.Headers["custom-event-id"];
    // 处理事件
    // ...
    // 保存事件状态
    await _eventStateService.SaveEventState(customEventId, eventData.Id, true);
}


//3.实现查询事件状态的接口：
[HttpGet("{customEventId}")]
public async Task<IActionResult> GetEventState(string customEventId)
{
    var eventStates = await _eventStateService.GetEventStates(customEventId);
    var totalEvents = eventStates.Count();
    var successEvents = eventStates.Count(s => s.Succeed == true);
    var failedEvents = eventStates.Count(s => s.Succeed == false);
    var result = new
    {
        CustomEventId = customEventId,
        TotalEvents = totalEvents,
        SuccessEvents = successEvents,
        FailedEvents = failedEvents
    };
    return Ok(result);
}


//4.在事件处理完成后，需要将事件状态保存到数据库中：
public async Task SaveEventState(string customEventId, long eventId, bool succeed)
{
    var eventState = new EventState()
    {
        CustomEventId = customEventId,
        EventId = eventId,
        Succeed = succeed
    };
    await _dbContext.EventStates.AddAsync(eventState);
    await _dbContext.SaveChangesAsync();
}


//5.在查询事件状态时，需要从数据库中获取事件状态信息：
public async Task<IEnumerable<EventState>> GetEventStates(string customEventId)
{
    var eventStates = await _dbContext.EventStates
        .Where(e => e.CustomEventId == customEventId)
        .ToListAsync();
    return eventStates;
}

//通过以上步骤，就可以实现自定义事件ID以查询整个事件链接的执行状态的功能。
`

**Comment by yang-xiaodong** [comment]
That is part of Saga capabilities, we do not support it at present. You can use us to provide OpenTelemetry to support tracing (you may encounter #1100 issue), or you can use the Diagnostics we provided to expand by yourself.
