### ISSUE TITLE
Change the SnowflakeId from static singleton to dependency injection singleton

### ISSUE THREAD

**Issue by 3ldar** [dotnetcore/CAP#1322]
Hi,
We are getting errors like below while both publishing and receiving events.

>SubscriberExecutionFailedException-->23505: duplicate key value violates unique constraint "published_pkey" DETAIL: Key ("Id")=(1613554411973534) already exists."

We run our application in a k8n cluster with 10 or more pods distributed to multiple nodes. (We use openshift 3.11 version if it helps). To my guess it is due to the `SnowflakeId` implementation. It uses mac addresses last 10 bits to generate a `workerId` if it is not provided in environmental variable `CAP_WORKERID`. There is a possibility that those 10 bits may be the same in a multi node cluster. In a single node cluster the OUI part is unique as the initial part is the same but when it comes to multiple nodes there is a possibility that the initial part of the mac is different but the last part is the same. When this happens and under a good load we get this kind of errors both while publising or receiving.  It is an option to set `CAP_WORKERID` for each pod but openshift gives you the only one environmental configuration per deployment config not per pod. (It doesn't make sense having multiple deployment configs for the same service as the number is dynamic due to load etc.) 

I have created a ugly  workaround like below. I have used redis to increment a number to assign as workerId and set it to  `CAP_WORKERID` env value.

```
private const string CapWorkerIdKey = "CAP_WORKERID";
private static void ConfigureWorkerId(IServiceCollection services)
        {
            var sp = services.BuildServiceProvider();
            var redis = sp.GetRequiredService<IRedisCacheClient>();
            var db = redis.Db3.Database;

            var workerId = db.StringIncrement(CapWorkerIdKey, 10);
            db.KeyExpire(CapWorkerIdKey, TimeSpan.FromMinutes(5));
            Environment.SetEnvironmentVariable(CapWorkerIdKey, workerId.ToString()); // Need to set EnvironmentTarget.Machine in older  versions like 6.x
        }
```

It seems to work for me. But a singleton service would be nicer to have for `SnowflakeId` where I can fiddle the `workerId` generation or entire `SnowflakeId` generation process.

**Comment by yang-xiaodong** [comment]
This has nothing to do with a single-node cluster or a multi-node cluster, the mac address is created and assigned by Docker.

Docker uses a virtual ethernet bridge (veth) to create network interfaces for containers and assigns a MAC address to each container's network interface. These MAC addresses are randomly generated and follow the standard MAC address format. In most cases, Docker uses MAC addresses in the format 02:42:xx:xx:xx:xx, where xx:xx:xx:xx is a randomly generated 4-byte value. This is done to ensure that each container's network interface has a unique and random MAC address.

This process happens during container creation. When the Docker daemon allocates network resources for a container, it generates a new MAC address and assigns it to the container's network interface. This assignment process is transparent to the user, who typically doesn't need to worry about the container's MAC address.

However, if you need to manually set a container's MAC address, you can use the `--mac-address` option when creating the container. For example:

```
docker run --mac-address="92:d0:c6:0a:29:33" -it ubuntu bash
```

**Comment by 3ldar** [comment]
Sorry for the confusion that I made. I am not saying that the assigned MAC addresses are not unique their last 10 bits have a probability to have the same value. I will try to explain it with the current MACs of my pods. I have 20 pods right now : 
```
0A:58:0A:80:09:93 <-- this
0A:58:0A:81:06:D8
0A:58:0A:80:09:92
0A:58:0A:80:04:7A
0A:58:0A:80:07:0E
0A:58:0A:83:01:79
0A:58:0A:83:01:78
0A:58:0A:80:07:0D
0A:58:0A:83:01:77
0A:58:0A:81:06:D6
0A:58:0A:82:04:95
0A:58:0A:82:07:66
0A:58:0A:82:07:65
0A:58:0A:82:04:94
0A:58:0A:80:07:0C
0A:58:0A:80:09:91
0A:58:0A:82:07:64
0A:58:0A:81:06:D5
0A:58:0A:82:05:93 <-- and this are dupes
0A:58:0A:80:04:79
```

The values `09:93` and `04:93` have the same 10 most right digits. 0000001`0110010011` and 000010`0110010011`. These kinds of MACs were causing our duplicate key values.

**Comment by yang-xiaodong** [comment]
OK. Would you like to submit a PR fot it?

**Comment by 3ldar** [comment]
> OK. Would you like to submit a PR fot it?

Yeap, I have implemented a singleton service.
