### ISSUE TITLE
Disabling cap logs

### ISSUE THREAD

**Issue by cagataykiziltan** [dotnetcore/CAP#1323]
hi,

while using cap library, it writes a lot of log in addition to my app's logs. Is there a way to disable cap's log?

**Comment by 3ldar** [comment]
Yeap you can do it by modifying `appsettings.json` files logging section like below :
```
"Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information",
      "DotNetCore.CAP" : "Warning
 
    }
  }
```

**Comment by cagataykiziltan** [comment]
thanks a lot @3ldar

**Comment by canperk** [comment]
We cannot do that in yaml files like

Logging__LogLevel__DotnetCore.CAP

**Comment by yang-xiaodong** [comment]
@canperk 
 
`Logging__LogLevel__DotnetCore.CAP`  -->  `Logging__LogLevel__DotNetCore.CAP` ？

n to N

**Comment by canperk** [comment]
Here is what I wrote in yaml for k8s

```
- name: Logging__LogLevel__DotNetCore.CAP
  value: Warning
- name: Logging__LogLevel__DotNetCore.CAP.RabbitMQ
  value: Warning
- name: Logging__LogLevel__DotNetCore.CAP.Internal.SubscribeExecutor
  value: Warning
```

RabbitMQ and Internal.* was my trials to see what will happen...
