### ISSUE TITLE
How to dynamic subscribe difference queue？

### ISSUE THREAD

**Issue by mowangzhang** [dotnetcore/CAP#1326]
你好，想问一下CAP可以在程序运行时动态的订阅队列吗？
队列名称示例“jt809_1111/jt809_2222/jt809_3333”我看了源码没发现相关的代码实现，我知道可以使用正则来做匹配“^jt809”。
程序会根据不同的租户消息写入对应的租户队列中，1111/222/3333表示不同租户，目前由于消息数量过大，单服务消费者无法满足业务量，由于其他因素干扰无法在开消费者归并到同一个消费者组；
所以想采取动态订阅方式，消费者1111只消费“jt809_1111”的消息，消费者2222只消费“jt809_2222”的消息等，后续新增租户“4444”时代码动态订阅队列“jt809_4444”的消息
请问CAP目前支持这样的操作吗？

**Comment by 3ldar** [comment]
Hi,  sadly CAP doesn't provide a dynamic subscription option. It needs to know all the event subscriptions before the configuration of DI. So you need to know the topic names beforehand. Or you can use a wild card subscription pattern like `jt809_*` that subscribes to anything that starts with `jt809_` and in your event handler you extract the topic name from CAP headers and get the tenant id from the topic name or you can move the tenant id into CAP headers and read the tenant Id from there. Instead of a service per tenant, you can have multiple services that work for every tenant.

**Comment by mowangzhang** [comment]
感谢您的答复，使用通配符多服务多租户这个方式我了解，只是由于其他原因每个租户只能限定在单服务。

新开启租户服务的时候用 System.Reflection.Emit 动态生成“ICapSubscribe”的实现对象并注入ICollection如何？
哈哈哈，还想过新启动租户服务的时候修改.cs文件重新编译

先折腾一下，确实比较曲折，最后的兜底方案就是直接用“Confluent.Kafka”来处理了

**Comment by 3ldar** [comment]
> 感谢您的答复，使用通配符多服务多租户这个方式我了解，只是由于其他原因每个租户只能限定在单服务。
> 
> 新开启租户服务的时候用 System.Reflection.Emit 动态生成“ICapSubscribe”的实现对象并注入IServiceCollection如何？ 哈哈哈，还想过新启动租户服务的时候修改.cs文件重新编译
> 
> 先折腾一下，确实比较曲折，最后的兜底方案就是直接用“Confluent.Kafka”来处理了

Yeap it is still doable with code generation + reflection. You can use code generation to generate the event handlers and then use the reflection to dynamically discover the related event handler and register it at the startup. But you will always need to restart or start a new service when a new tenant added.

**Comment by mowangzhang** [comment]
Yes，我新增了租户时调度管理程序会重新启动一个新的服务来消费消息
利用“Emit”我已经实现了我想要的功能，开心^_^

```
    public static class CapSubscribeExtensions
    {
        public static void AddSubscribe<T>(this IServiceCollection services, Func<T, CapHeader, Task> func, CapSubscribeAttribute capSubscribe)
        {
            // 创建动态程序集和动态模块
            AssemblyName assemblyName = new AssemblyName("DynamicAssembly");
            AssemblyBuilder assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(assemblyName, AssemblyBuilderAccess.Run);
            ModuleBuilder moduleBuilder = assemblyBuilder.DefineDynamicModule("DynamicModule");

            // 创建 Subscribe 类型
            TypeBuilder typeBuilder = moduleBuilder.DefineType("Subscribe" + Guid.NewGuid().ToString("N"), TypeAttributes.Public | TypeAttributes.Class);
            typeBuilder.AddInterfaceImplementation(typeof(ICapSubscribe));

            // 添加私有字段
            FieldBuilder funcField = typeBuilder.DefineField("_func", typeof(Func<,,>).MakeGenericType(typeof(T), typeof(CapHeader), typeof(Task)), FieldAttributes.Private);

            // 添加构造函数
            ConstructorBuilder constructorBuilder = typeBuilder.DefineConstructor(MethodAttributes.Public, CallingConventions.Standard, new Type[] { typeof(Func<,,>).MakeGenericType(typeof(T), typeof(CapHeader), typeof(Task)) });
            ILGenerator il = constructorBuilder.GetILGenerator();
            il.Emit(OpCodes.Ldarg_0);
            il.Emit(OpCodes.Call, typeof(object).GetConstructor(Type.EmptyTypes));
            il.Emit(OpCodes.Ldarg_0);
            il.Emit(OpCodes.Ldarg_1);
            il.Emit(OpCodes.Stfld, funcField);
            il.Emit(OpCodes.Ret);


            // 添加 OnMessage 方法
            MethodBuilder onMessageBuilder = typeBuilder.DefineMethod("OnMessage", MethodAttributes.Public | MethodAttributes.Virtual);
            onMessageBuilder.SetReturnType(typeof(Task));
            onMessageBuilder.SetParameters(typeof(T), typeof(CapHeader));
            // 添加 FromCapAttribute 到 CapHeader 参数
            ParameterBuilder headerParameter = onMessageBuilder.DefineParameter(2, ParameterAttributes.None, "header");
            Type fromCapAttributeType = typeof(FromCapAttribute);
            ConstructorInfo fromCapAttributeConstructor = fromCapAttributeType.GetConstructor(Type.EmptyTypes);
            CustomAttributeBuilder fromCapAttributeBuilder = new CustomAttributeBuilder(fromCapAttributeConstructor, new object[0]);
            headerParameter.SetCustomAttribute(fromCapAttributeBuilder);
            // 添加 CapSubscribeAttribute 到方法
            Type capSubscribeAttributeType = typeof(CapSubscribeAttribute);
            ConstructorInfo capSubscribeAttributeConstructor = capSubscribeAttributeType.GetConstructor(new Type[] { typeof(string), typeof(bool) });
            CustomAttributeBuilder capSubscribeAttributeBuilder = new CustomAttributeBuilder(
                capSubscribeAttributeConstructor,
                new object[] { capSubscribe.Name, capSubscribe.IsPartial },
                new PropertyInfo[] { capSubscribeAttributeType.GetProperty("Group") },
                new object[] { capSubscribe.Group }
            );
            onMessageBuilder.SetCustomAttribute(capSubscribeAttributeBuilder);
            il = onMessageBuilder.GetILGenerator();
            il.Emit(OpCodes.Ldarg_0);
            il.Emit(OpCodes.Ldfld, funcField);
            il.Emit(OpCodes.Ldarg_1);
            il.Emit(OpCodes.Ldarg_2);
            il.Emit(OpCodes.Callvirt, typeof(Func<,,>).MakeGenericType(typeof(T), typeof(CapHeader), typeof(Task)).GetMethod("Invoke"));
            il.Emit(OpCodes.Ret);

            // 创建 Subscribe 类型并返回
            Type subscribeType = typeBuilder.CreateType();
            dynamic instance = Activator.CreateInstance(subscribeType, func);

            services.AddTransient(typeof(ICapSubscribe), sp => instance);
        }
    }
```

**Comment by mowangzhang** [comment]
还有瑕疵
因为是用这个注入：services.AddTransient(typeof(ICapSubscribe), sp => instance);

![image](https://user-images.githubusercontent.com/46166610/236386665-f70e60f3-6828-40e1-ac8f-c02785f8e8ed.png)

**Comment by 3ldar** [comment]
>         Type subscribeType = typeBuilder.CreateType();
>          dynamic instance = Activator.CreateInstance(subscribeType, func);
>          services.AddTransient(typeof(ICapSubscribe), sp => instance);

Instead of creating the instance directly, it might be better to use a generic version of `AddTransient` method. If your event handler requires some services from DI it might be hard to resolve them here. So letting the instance creation part to the DI is a better solution. 
@yang-xiaodong adding these to the samples directory might be a good addition.

**Comment by mowangzhang** [comment]
是哦，Event handler肯定需要依赖其他services来进行逻辑处理，这样看来我这个扩展，在不改动CAP源码的情况下还实现不了

**Comment by mowangzhang** [comment]
在绕个弯，event handler收到的消息在转入到我一个本地队列里面，如此就只需要订阅本地队列消息处理即可，不过这样做的话当发生异常时就无法使用CAP的异常处理能力了(异常重试、持久化)

**Comment by 3ldar** [comment]
You were almost there you could actually do it like this :
```
Type subscribeType = typeBuilder.CreateType();
services.AddTransient(typeof(ICapSubscribe), sp => (ICapSubscribe)ActivatorUtilities.CreateInstance(sp,subscribeType));
```

`ActivatorUtilities` can create instances using `IServiceProvider`

**Comment by mowangzhang** [comment]
哇，没错，又学到了一招
