### ISSUE TITLE
cap 注册到Consul 切换到节点，点击 swatch 按钮后 页面一直处于加载中

### ISSUE THREAD

**Issue by JavaScript-zt** [dotnetcore/CAP#1329]
bug1：DiscoveryOptions  的MatchPath  设置了自定义路由还是拼接成 http:{ip:port}/{自定义健康检查路由} /api/health，
            期望拼成：http:{ip:port}/{自定义健康检查路由}
bug2：点击了 切换到 按钮后页面一直处于加载中，如下图：
 
![image](https://github.com/dotnetcore/CAP/assets/19992219/f1d05cca-428a-4dda-93f3-0d78f26e9e45)

控制台一直打印log：
[09:01:40 DBG] start calling remote endpoint...
[09:01:43 DBG] start calling remote endpoint...
[09:01:46 DBG] start calling remote endpoint...
[09:01:49 DBG] start calling remote endpoint...
[09:01:49 DBG] Transport connection checking...
[09:01:49 DBG] Transport connection healthy!
[09:01:52 DBG] start calling remote endpoint...
[09:01:55 DBG] start calling remote endpoint...

bug3：停掉vs重新打开node页面，连switch按钮都没有了，页面一直处于加载中

**Comment by yang-xiaodong** [comment]
Please show your version and configuration and consul dashboard

**Comment by JavaScript-zt** [comment]
version：
![image](https://github.com/dotnetcore/CAP/assets/19992219/87b76107-20c2-4ea6-b6c2-b5aaf8bb1179)

configuration：
![image](https://github.com/dotnetcore/CAP/assets/19992219/18046fbe-c916-4181-9242-b360e221bbce)

configuration value：
![image](https://github.com/dotnetcore/CAP/assets/19992219/d601f1db-fc67-42a2-9ca4-12b4ab2340ce)


dashboard：
![image](https://github.com/dotnetcore/CAP/assets/19992219/3a60b387-0af8-4b93-9756-fbc0a8aa870f)

consul：
![image](https://github.com/dotnetcore/CAP/assets/19992219/684bd327-c7d5-432b-b4ef-d377fedef07e)

**Comment by yang-xiaodong** [comment]
你就一个节点，切换什么？
