### ISSUE TITLE
[suggest] remove all ConfigureAwait(false)

### ISSUE THREAD

**Issue by sampsonye** [dotnetcore/CAP#1333]
![image](https://github.com/dotnetcore/CAP/assets/5895634/1a7a74a3-e93a-4be6-92ca-296fe64ea694)
`.ConfigureAwait(false)` will lost async context， it makes me crzy like：
1. `BeforeSubscriberInvoke` i save usercontext from header
2. `FailedThresholdCallback` i cant get usercontext

==
1. 在`BeforeSubscriberInvoke`中我将用户信息从Headers中取出并放到了异步上下文AsyncLocal中
2. 但是在`FailedThresholdCallback`中无法正确获取到用户信息

**Comment by yang-xiaodong** [comment]
这和ConfigureAwait(false)没关系吧，AsyncLocal本身就只能向下传播

**Comment by yang-xiaodong** [comment]
![image](https://github.com/dotnetcore/CAP/assets/8205994/940f170c-c53a-4ac0-9543-27af08e20e3f)

**Comment by 3ldar** [comment]
Subscriber invocation has no relationship with Asp.Net's request pipeline, there is no way to use a structure like `AsyncLocal`.  If you give an example of what you are trying we might help you.

**Comment by sampsonye** [comment]
现状是：
我在事件处理端写AsyncLocal值：
![image](https://github.com/dotnetcore/CAP/assets/5895634/444c8922-b64b-40cc-86ee-117c61aa30d5)

抛出异常后，在异常捕获端获取AsyncLocal时，获取不到了
![image](https://github.com/dotnetcore/CAP/assets/5895634/d64990de-b75a-4696-96e9-05008a5346c6)

**Comment by sampsonye** [comment]
https://stackoverflow.com/questions/42959056/whats-the-effect-of-asynclocalt-in-non-async-await-code/42959816#42959816

了解了 对AsyncLocal的“向下传播”有了新的认识
