### ISSUE TITLE
BackgroundService's backend service and opened two BackgroundServices,only one receive

### ISSUE THREAD

**Issue by PiaoYiQiang** [dotnetcore/CAP#1334]
中文：dalao你好，我用了BackgroundService的后台服务，开了2个BackgroundService（为了能加快业务接收处理能力），然后我发送了10条消息，一直是一个BackgroundService能接收到，另一个接收不到。
PS：但我单独发布两个独立文件去接受消息的话，两个独立文件会自己抢消息，不会出现这个问题。
英文翻译：Hello Dalao, I used BackgroundService's backend service and opened two BackgroundServices (in order to speed up business reception and processing capabilities). Then I sent 10 messages, one of which was able to receive and the other was unable to receive.
PS：But if I separately publish two independent files to receive messages, the two independent files will compete for messages themselves, and this problem will not occur.

![image](https://github.com/dotnetcore/CAP/assets/66508022/701656a4-5993-4031-9008-d6954de0d126)
![image](https://github.com/dotnetcore/CAP/assets/66508022/3493cb41-2d05-4443-9664-df3be8de60e5)
![image](https://github.com/dotnetcore/CAP/assets/66508022/15019717-6dd9-4878-af02-7264701ec274)
![image](https://github.com/dotnetcore/CAP/assets/66508022/35b2783d-d136-49ca-912b-d7493222ed9c)

**Comment by yang-xiaodong** [comment]
see https://github.com/dotnetcore/CAP#subscribe-group

**Comment by PiaoYiQiang** [comment]
中文：dalao，那个组的我之前看过，但是那个是重复消费，我的意思是，我不想重复消费，我想两个消费者合作消费一次就行了，为了加快业务处理能力。
英文：Dalao, I saw it before and what I mean is, I don't want to consume repeatedly. I want two consumers to collaborate and consume once, in order to speed up business processing capabilities
