### ISSUE TITLE
PublishAsync doesn't use DefaultGroupName

### ISSUE THREAD

**Issue by jmogera** [dotnetcore/CAP#1336]
We have one kafka instance that we are trying to use for QA, UAT, DEV enviornments.

I am setting DefaultGroupName like this: api.qa, api.uat, api.dev.

When we publish message FROM api that has DefaultGroupName as api.qa. I am hoping for the api instance that has api.qa group name to pick that up, but right now all api instance pick it up.

How can this be set up so publish only works api with matching DefaultGroupName

**Comment by 3ldar** [comment]
I am adding a sample configuration that adds the custom header and a `SubscribeFilter` serves the purpose: 

> Program.cs
```
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddCap(cap =>
                        cap.UseKafka(kafka => 
                                     kafka.CustomHeaders = (_) => 
                                        new () { new KeyValuePair<string, string>("ENV", builder.Configuration["ASPNETCORE_ENVIRONMENT"] ?? "Development") }))
                .AddSubscribeFilter<EnvSubscribeFilter>();
```

> EnvSubscribeFilter.cs
```
public class EnvSubscribeFilter : SubscribeFilter
    {
        private readonly IConfiguration configuration;

        public EnvSubscribeFilter(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        public override Task OnSubscribeExecutingAsync(ExecutingContext context)
        {
            var envName = this.configuration["ASPNETCORE_ENVIRONMENT"];
            var header = context.DeliverMessage.Headers["ENV"];

            if (header != envName)
            {
                throw new SkipExecutionExcepiton();
            }
            return base.OnSubscribeExecutingAsync(context);
        }

        public override Task OnSubscribeExceptionAsync(ExceptionContext context)
        {
            if (context.Exception is SkipExecutionExcepiton)
            {
                context.ExceptionHandled = true;
            }

            return base.OnSubscribeExceptionAsync(context);
        }

        private class SkipExecutionExcepiton : Exception
        {
        }
    }
```

**You should keep using different consumer group names to make this work as the message should be processed by all the environments otherwise if an environment processes a message the other environments won't get the message. And the message will exist in all the environments storages.** This is not an optimal solution but it should serve the purpose. There is another option which is to separate topics by environment. You can do it by conditional programming with processor directives and adding symbols at builds and checking those symbols like this 
```
#if ENV_DEV
[CapSbuscribe("my_topic_dev")]
#elif ENV_UAT
[CapSbuscribe("my_topic_uat")]
#elif ENV_QA
[CapSbuscribe("my_topic_qa")]
#else
[CapSbuscribe("my_topic")]
#endif
public async Task Process(string message) {}
```

There is another way to achieve this which is to use `IL Emit` to dynamically build topic attributes at the startup and register the event handlers which is mentioned in #1326

**Comment by jmogera** [comment]
@

> I am adding a sample configuration that adds the custom header and a `SubscribeFilter` serves the purpose:
> 
> > Program.cs
> 
> ```
> var builder = WebApplication.CreateBuilder(args);
> 
> builder.Services.AddCap(cap =>
>                         cap.UseKafka(kafka => 
>                                      kafka.CustomHeaders = (_) => 
>                                         new () { new KeyValuePair<string, string>("ENV", builder.Configuration["ASPNETCORE_ENVIRONMENT"] ?? "Development") }))
>                 .AddSubscribeFilter<EnvSubscribeFilter>();
> ```
> 
> > EnvSubscribeFilter.cs
> 
> ```
> public class EnvSubscribeFilter : SubscribeFilter
>     {
>         private readonly IConfiguration configuration;
> 
>         public EnvSubscribeFilter(IConfiguration configuration)
>         {
>             this.configuration = configuration;
>         }
> 
>         public override Task OnSubscribeExecutingAsync(ExecutingContext context)
>         {
>             var envName = this.configuration["ASPNETCORE_ENVIRONMENT"];
>             var header = context.DeliverMessage.Headers["ENV"];
> 
>             if (header != envName)
>             {
>                 throw new SkipExecutionExcepiton();
>             }
>             return base.OnSubscribeExecutingAsync(context);
>         }
> 
>         public override Task OnSubscribeExceptionAsync(ExceptionContext context)
>         {
>             if (context.Exception is SkipExecutionExcepiton)
>             {
>                 context.ExceptionHandled = true;
>             }
> 
>             return base.OnSubscribeExceptionAsync(context);
>         }
> 
>         private class SkipExecutionExcepiton : Exception
>         {
>         }
>     }
> ```
> 
> **You should keep using different consumer group names to make this work as the message should be processed by all the environments otherwise if an environment processes a message the other environments won't get the message. And the message will exist in all the environments storages.** This is not an optimal solution but it should serve the purpose. There is another option which is to separate topics by environment. You can do it by conditional compilation with processor directives and adding symbols at builds and checking those symbols like this
> 
> ```
> #if ENV_DEV
> [CapSbuscribe("my_topic_dev")]
> #elif ENV_UAT
> [CapSbuscribe("my_topic_uat")]
> #elif ENV_QA
> [CapSbuscribe("my_topic_qa")]
> #else
> [CapSbuscribe("my_topic")]
> #endif
> public async Task Process(string message) {}
> ```
> 
> There is another way to achieve this which is to use `IL Emit` to dynamically build topic attributes at the startup and register the event handlers which is mentioned in #1326

@3ldar I  tried adding EnvSubscribeFilter code, but when you produce the message both dev and qa environment pick up the same message.

my subscribe is like this: 
`[CapSubscribe("client.export")]` with no group name

and in Program.cs
`builder.Services.AddCap(options =>
{
    options.DefaultGroupName = builder.Configuration.GetValue<string>("Kafka:Environment");
    options.ConsumerThreadCount = 10;
    options.FailedRetryCount = 2;
    options.UseKafka(k =>
    {
        k.CustomHeaders = (_) => new() { new KeyValuePair<string, string>("Environment", builder.Configuration.GetValue<string>("Kafka:Environment") ?? "local") };
        k.Servers = builder.Configuration.GetConnectionString("Kafka");
        k.MainConfig.Add("allow.auto.create.topics", "true");
    });
    options.UseSqlServer(builder.Configuration.GetConnectionString("SqlServer"));
}).AddSubscribeFilter<EnvironmentSubscribeFilter>();`

No luck with this

**Comment by 3ldar** [comment]
> @3ldar I tried adding EnvSubscribeFilter code, but when you produce the message both dev and qa environment pick up the same message.
> 
> my subscribe is like this: `[CapSubscribe("client.export")]` with no group name
> 
> and in Program.cs `builder.Services.AddCap(options => { options.DefaultGroupName = builder.Configuration.GetValue<string>("Kafka:Environment"); options.ConsumerThreadCount = 10; options.FailedRetryCount = 2; options.UseKafka(k => { k.CustomHeaders = (_) => new() { new KeyValuePair<string, string>("Environment", builder.Configuration.GetValue<string>("Kafka:Environment") ?? "local") }; k.Servers = builder.Configuration.GetConnectionString("Kafka"); k.MainConfig.Add("allow.auto.create.topics", "true"); }); options.UseSqlServer(builder.Configuration.GetConnectionString("SqlServer")); }).AddSubscribeFilter<EnvironmentSubscribeFilter>();`
> 
> No luck with this

@jmogera I have managed to make it work on my local. (So it should work on your side too) As I said both ends will consume the message but only the one that has the correct environment value will actually process the message. Do not let the logs deceive you. It will log something like the below 
> info: DotNetCore.CAP.Internal.SubscribeExecutor[0]
>      Executing subscriber method 'FooConsumer.HandleFoo' on group 'cap.queue.consumerqa.v1'

but that doesn't mean it actually executes the handler.
