### ISSUE TITLE
hi @omeerkorkmazz   Subscriber life suggested in the cap document is transient. Did you overcome this problem when you made the membership life singleton? Does the problem of not receiving messages go away?

### ISSUE THREAD

**Issue by nrllhylmz** [dotnetcore/CAP#1342]
hi @hetaoos,

Thank you so much for your reply. We recognized that we have lots of connections. The reason was regarding the dependency injection lifetime. We changed lifetime to **_singleton_** and the problem was solved.

_Originally posted by @omeerkorkmazz in https://github.com/dotnetcore/CAP/issues/918#issuecomment-869482558_

**Comment by omeerkorkmazz** [comment]
Hey @nrllhylmz,sorry for the late response. During the use of CAP, we faced with duplicated many connections on the RabbitMQ side. When we changed it to the singleton lifecycle, it worked properly as expected. I didn't have a chance to follow next versions and improvements. This issue might be solved in the latest versions. Hope this helps you!

**Comment by nrllhylmz** [comment]
hi @omeerkorkmazz , I found the solution to my problem. 
I was doing the transaction management myself while publishing the message.
I left the transaction management with the 'autocommit' feature.
I found this solution in below url.
https://github.com/dotnetcore/cap/issues/191
Yang gave some hints about usage
