### ISSUE TITLE
Subscribers sometimes do not consume and queue is accumulating.

### ISSUE THREAD

**Issue by nrllhylmz** [dotnetcore/CAP#1343]
hi @yang-xiaodong 

Subscriber life suggested in the cap document is transient. 
Did you overcome this problem when you made the subscriber's life singleton? 
Does the problem of not consume  and queue is accumulating go away?

https://github.com/dotnetcore/CAP/issues/918#issuecomment-869482558 
is it right?

**Comment by yang-xiaodong** [comment]
Why do you take a try?

**Comment by nrllhylmz** [comment]
1

**Comment by nrllhylmz** [comment]
Thank you so much for your quick response.
I didn't try this, because , your cap document say dependency injection lifetime is transient.
I think this is bug
Subscriber does not receive messages after a while.
I stoped the connection from the rabbitmq dashboard.
The connection was automatically re-established.
Subscriberr started receive messages in queue.

**Comment by yang-xiaodong** [comment]
Closed by https://zhuanlan.zhihu.com/p/25795393
