### ISSUE TITLE
Why is there a noticeable pause when I publish again among a consumer?

### ISSUE THREAD

**Issue by xiaolipro** [dotnetcore/CAP#1344]
When I tried to continue circulating subtasks to MQ within a consumer method marked CapSubscribe, the code experienced a noticeable pause, and the subscribers of the subtasks did not receive any messages
``` c#
            if (voucherEntriesAmountIncurredList.Count > 10)
            {
                foreach (var item in voucherEntriesAmountIncurredList)
                {
                    var @event = new VoucherRedundantCalcItemEvent
                    {
                        LedgerId = ledgerId,
                        YearPeriod = yearPeriod,
                        IsAdd = isAdd,
                        VoucherEntriesAmountIncurred = item
                    };

                    await _capPublisher.PublishAsync(VoucherRedundantCalcItemCustomer.CapSubscribe, @event);
                }

                return false;
            }
```

After observing RabbitMQ, it was found that the message was in an unpacked state, the program was terminated, and the message was immediately thrown into a ready state.

What I want to know is how I can continue posting tasks among a consumer and hope to receive help!

**Comment by xiaolipro** [comment]
This is the content printed by the console during my debugging. Every time there is an exception, there will be an unacked message in the rabbitmq. It is obvious that there are many seconds between them
```shell
[2023-05-28 21:42:19 999 INF] CAP message 'SJZY.FMC.VoucherRedundantCalcItem' published, internal id '8054059977899454469'
[2023-05-28 21:42:35 878 DBG] Transport connection checking...
[2023-05-28 21:42:35 881 DBG] Transport connection healthy!
[2023-05-28 21:42:50 025 ERR] An exception occurred when sending a message to the MQ. Id:8054059977899454469
[2023-05-28 21:42:50 027 INF] CAP message 'SJZY.FMC.VoucherRedundantCalcItem' published, internal id '8054059977899454470'
[2023-05-28 21:43:05 889 DBG] Transport connection checking...
[2023-05-28 21:43:05 891 DBG] Transport connection healthy!
[2023-05-28 21:43:20 060 ERR] An exception occurred when sending a message to the MQ. Id:8054059977899454470
[2023-05-28 21:43:20 061 INF] CAP message 'SJZY.FMC.VoucherRedundantCalcItem' published, internal id '8054059977899454471'
[2023-05-28 21:43:35 898 DBG] Transport connection checking...
[2023-05-28 21:43:35 899 DBG] Transport connection healthy!
[2023-05-28 21:43:50 069 ERR] An exception occurred when sending a message to the MQ. Id:8054059977899454471
[2023-05-28 21:43:50 072 INF] CAP message 'SJZY.FMC.VoucherRedundantCalcItem' published, internal id '8054059977899454472'
[2023-05-28 21:44:05 908 DBG] Transport connection checking...
[2023-05-28 21:44:05 912 DBG] Transport connection healthy!
[2023-05-28 21:44:20 091 ERR] An exception occurred when sending a message to the MQ. Id:8054059977899454472
[2023-05-28 21:44:21 085 INF] CAP message 'SJZY.FMC.VoucherRedundantCalcItem' published, internal id '8054059977899454473'
[2023-05-28 21:44:35 919 DBG] Transport connection checking...
[2023-05-28 21:44:35 922 DBG] Transport connection healthy!
[2023-05-28 21:44:51 110 ERR] An exception occurred when sending a message to the MQ. Id:8054059977899454473
[2023-05-28 21:44:51 112 INF] CAP message 'SJZY.FMC.VoucherRedundantCalcItem' published, internal id '8054059977899454474'
```

**Comment by xiaolipro** [comment]
After observation, I retried 10 times, which is exactly the number of failed retries for the cap I set. Why is the exception not caught by me and why consumers cannot publish it

**Comment by 3ldar** [comment]
`PublishAsync` only ensures the database operation of the outgoing message. You may want to configure [FailedThresholdCallback](https://cap.dotnetcore.xyz/user-guide/en/cap/configuration/#failedthresholdcallback) setting to get detailed info about the error.

**Comment by xiaolipro** [comment]
> `PublishAsync` only ensures the database operation of the outgoing message. You may want to configure [FailedThresholdCallback](https://cap.dotnetcore.xyz/user-guide/en/cap/configuration/#failedthresholdcallback) setting to get detailed info about the error.

Sure, I configured it but it didn't work

```c#
options.FailedThresholdCallback = faileCalback =>
{
       LogHelper.Error($@"{faileCalback.MessageType} 失败了,消息名称: {faileCalback.Message.Value}");
 };
```
My code seems to have fallen into some kind of error. I just wanted to loop publish the tasks and they were indeed executed, but they were not successfully published

**Comment by yang-xiaodong** [comment]
@xiaolipro 
1. Please show your version and configuration
2. What is 'noticeable pause'?
3. What is 'message was in an unpacked state'?
4. What is your question?  'noticeable pause' or 'exception not caught by you'?

**Comment by xiaolipro** [comment]
> 



> @xiaolipro
> 
> 1. Please show your version and configuration
> 2. What is 'noticeable pause'?
> 3. What is 'message was in an unpacked state'?
> 4. What is your question?  'noticeable pause' or 'exception not caught by you'?
> 5. 你的英文不通顺，我看不懂。请同时写上中文。

Sorry, my English is not very good. I am using version 7.1.0

I have resolved the publishing issue and they are able to publish normally due to my use of TransactionScope on the outer layer, which seems to conflict with the transaction of sqlsugar. I changed it to sqlsugar's transaction to solve this problem. However, I am still confused by a phenomenon: during the transaction loop, publish events are pushed down the queue and consumed before submission. This will have serious consequences for my code, and I do not want to perform any consumption before it is fully released. Specifically, I hope that the publish can be rolled back. May I ask if this is possible? Here is my complete producer code
很抱歉我的英语不是很好，我使用的版本是7.1.0
我已经解决了发布问题，他们能够正常发布，是由于我外层使用了`TransactionScope`，他似乎与sqlsugar的事务产生冲突，我将其改成sqlsugar的事务就解决了这个问题，但是，我仍然为一个现象感到困惑：在事务中循环publish事件，循环的过程中，提交前，事件就已经有一部分被推倒了队列并且被消费。这将给我的代码造成严重的后果，我不希望在完全发布之前执行任何消费，准确来说，我希望publish多个消息时能够具有事务性。请问这是可能的吗？下面是我的生产者完整代码
```c#
public async Task PublishRedundantCalcSubTaskAsync(VoucherRedundantCalcEvent @event, bool isAdd, List<CalculateSumProcessAmountOutputVO> voucherEntriesAmountIncurredList)
        {
            try
            {
                SqlsugarScopeBasic.Db.GetConnectionScope(BasicRepository<object>.connectId).Ado.BeginTran();

                foreach (var item in voucherEntriesAmountIncurredList)
                {
                    var subEvent = new VoucherRedundantCalcItemEvent
                    {
                        PId = @event.TaskKey,
                        LedgerId = @event.LedgerId,
                        YearPeriod = @event.YearPeriod,
                        IsAdd = isAdd,
                        VoucherEntriesAmountIncurred = item
                    };

                    // 写日志
                    subEvent.TaskKey = await _voucherEntriesAllRepository.WriteLogAsync(new VoucherEntriesAllLogEntity
                    {
                        PId = @event.TaskKey,
                        CapSubscribe = VoucherRedundantCalcItemCustomer.CapSubscribe,
                        LedgerId = @event.LedgerId,
                        Content = subEvent.ToString(),
                        Status = HandleStatusEnum.Sended,
                        CreateTime = DateTime.Now
                    });
                    await _capPublisher.PublishAsync(VoucherRedundantCalcItemCustomer.CapSubscribe, subEvent);
                }

                SqlsugarScopeBasic.Db.GetConnectionScope(BasicRepository<object>.connectId).Ado.CommitTran();
            }
            catch (Exception)
            {
                SqlsugarScopeBasic.Db.GetConnectionScope(BasicRepository<object>.connectId).Ado.RollbackTran();
                throw;
            }
        }
```

**Comment by xiangxiren** [comment]
> > 
> 
> > @xiaolipro
> > 
> > 1. Please show your version and configuration
> > 2. What is 'noticeable pause'?
> > 3. What is 'message was in an unpacked state'?
> > 4. What is your question?  'noticeable pause' or 'exception not caught by you'?
> > 5. 你的英文不通顺，我看不懂。请同时写上中文。
> 
> Sorry, my English is not very good. I am using version 7.1.0
> 
> I have resolved the publishing issue and they are able to publish normally due to my use of TransactionScope on the outer layer, which seems to conflict with the transaction of sqlsugar. I changed it to sqlsugar's transaction to solve this problem. However, I am still confused by a phenomenon: during the transaction loop, publish events are pushed down the queue and consumed before submission. This will have serious consequences for my code, and I do not want to perform any consumption before it is fully released. Specifically, I hope that the publish can be rolled back. May I ask if this is possible? Here is my complete producer code 很抱歉我的英语不是很好，我使用的版本是7.1.0 我已经解决了发布问题，他们能够正常发布，是由于我外层使用了`TransactionScope`，他似乎与sqlsugar的事务产生冲突，我将其改成sqlsugar的事务就解决了这个问题，但是，我仍然为一个现象感到困惑：在事务中循环publish事件，循环的过程中，提交前，事件就已经有一部分被推倒了队列并且被消费。这将给我的代码造成严重的后果，我不希望在完全发布之前执行任何消费，准确来说，我希望publish多个消息时能够具有事务性。请问这是可能的吗？下面是我的生产者完整代码
> 
> ```cs
> public async Task PublishRedundantCalcSubTaskAsync(VoucherRedundantCalcEvent @event, bool isAdd, List<CalculateSumProcessAmountOutputVO> voucherEntriesAmountIncurredList)
>         {
>             try
>             {
>                 SqlsugarScopeBasic.Db.GetConnectionScope(BasicRepository<object>.connectId).Ado.BeginTran();
> 
>                 foreach (var item in voucherEntriesAmountIncurredList)
>                 {
>                     var subEvent = new VoucherRedundantCalcItemEvent
>                     {
>                         PId = @event.TaskKey,
>                         LedgerId = @event.LedgerId,
>                         YearPeriod = @event.YearPeriod,
>                         IsAdd = isAdd,
>                         VoucherEntriesAmountIncurred = item
>                     };
> 
>                     // 写日志
>                     subEvent.TaskKey = await _voucherEntriesAllRepository.WriteLogAsync(new VoucherEntriesAllLogEntity
>                     {
>                         PId = @event.TaskKey,
>                         CapSubscribe = VoucherRedundantCalcItemCustomer.CapSubscribe,
>                         LedgerId = @event.LedgerId,
>                         Content = subEvent.ToString(),
>                         Status = HandleStatusEnum.Sended,
>                         CreateTime = DateTime.Now
>                     });
>                     await _capPublisher.PublishAsync(VoucherRedundantCalcItemCustomer.CapSubscribe, subEvent);
>                 }
> 
>                 SqlsugarScopeBasic.Db.GetConnectionScope(BasicRepository<object>.connectId).Ado.CommitTran();
>             }
>             catch (Exception)
>             {
>                 SqlsugarScopeBasic.Db.GetConnectionScope(BasicRepository<object>.connectId).Ado.RollbackTran();
>                 throw;
>             }
>         }
> ```

Because SqlSugar's transaction is not associated with ICapPulisher.
https://github.com/dotnetcore/CAP/blob/9c133dc1d0b7e9a775b6c66800f24db20c7e66bc/src/DotNetCore.CAP/ICapPublisher.cs#L21

Transaction is null.Therefore, messages will be published in a non transactional form.

**Comment by xiaolipro** [comment]
> > > 
> > 
> > 
> > > @xiaolipro
> > > 
> > > 1. Please show your version and configuration
> > > 2. What is 'noticeable pause'?
> > > 3. What is 'message was in an unpacked state'?
> > > 4. What is your question?  'noticeable pause' or 'exception not caught by you'?
> > > 5. 你的英文不通顺，我看不懂。请同时写上中文。
> > 
> > 
> > Sorry, my English is not very good. I am using version 7.1.0
> > I have resolved the publishing issue and they are able to publish normally due to my use of TransactionScope on the outer layer, which seems to conflict with the transaction of sqlsugar. I changed it to sqlsugar's transaction to solve this problem. However, I am still confused by a phenomenon: during the transaction loop, publish events are pushed down the queue and consumed before submission. This will have serious consequences for my code, and I do not want to perform any consumption before it is fully released. Specifically, I hope that the publish can be rolled back. May I ask if this is possible? Here is my complete producer code 很抱歉我的英语不是很好，我使用的版本是7.1.0 我已经解决了发布问题，他们能够正常发布，是由于我外层使用了`TransactionScope`，他似乎与sqlsugar的事务产生冲突，我将其改成sqlsugar的事务就解决了这个问题，但是，我仍然为一个现象感到困惑：在事务中循环publish事件，循环的过程中，提交前，事件就已经有一部分被推倒了队列并且被消费。这将给我的代码造成严重的后果，我不希望在完全发布之前执行任何消费，准确来说，我希望publish多个消息时能够具有事务性。请问这是可能的吗？下面是我的生产者完整代码
> > ```cs
> > public async Task PublishRedundantCalcSubTaskAsync(VoucherRedundantCalcEvent @event, bool isAdd, List<CalculateSumProcessAmountOutputVO> voucherEntriesAmountIncurredList)
> >         {
> >             try
> >             {
> >                 SqlsugarScopeBasic.Db.GetConnectionScope(BasicRepository<object>.connectId).Ado.BeginTran();
> > 
> >                 foreach (var item in voucherEntriesAmountIncurredList)
> >                 {
> >                     var subEvent = new VoucherRedundantCalcItemEvent
> >                     {
> >                         PId = @event.TaskKey,
> >                         LedgerId = @event.LedgerId,
> >                         YearPeriod = @event.YearPeriod,
> >                         IsAdd = isAdd,
> >                         VoucherEntriesAmountIncurred = item
> >                     };
> > 
> >                     // 写日志
> >                     subEvent.TaskKey = await _voucherEntriesAllRepository.WriteLogAsync(new VoucherEntriesAllLogEntity
> >                     {
> >                         PId = @event.TaskKey,
> >                         CapSubscribe = VoucherRedundantCalcItemCustomer.CapSubscribe,
> >                         LedgerId = @event.LedgerId,
> >                         Content = subEvent.ToString(),
> >                         Status = HandleStatusEnum.Sended,
> >                         CreateTime = DateTime.Now
> >                     });
> >                     await _capPublisher.PublishAsync(VoucherRedundantCalcItemCustomer.CapSubscribe, subEvent);
> >                 }
> > 
> >                 SqlsugarScopeBasic.Db.GetConnectionScope(BasicRepository<object>.connectId).Ado.CommitTran();
> >             }
> >             catch (Exception)
> >             {
> >                 SqlsugarScopeBasic.Db.GetConnectionScope(BasicRepository<object>.connectId).Ado.RollbackTran();
> >                 throw;
> >             }
> >         }
> > ```
> 
> Because SqlSugar's transaction is not associated with ICapPulisher.
> 
> https://github.com/dotnetcore/CAP/blob/9c133dc1d0b7e9a775b6c66800f24db20c7e66bc/src/DotNetCore.CAP/ICapPublisher.cs#L21
> 
> Transaction is null.Therefore, messages will be published in a non transactional form.

I think that's exactly the case. Thank you very much for your guidance. By the way, I would also like to ask a question. I set ConsumerThreadCount to 8, and I observed RabbitMQ and found that it did bind 8 consumers, but it did not increase the consumption speed as I imagined? There is almost no difference in consumption speed compared to the default one consumer thread. There is a lot of message backlog in the queue, and there is no dependency between them. I hope more consumer threads can join. Strangely, I started a new application instance, but it can accelerate the consume of messages in MQ..
I hope to fully utilize multithreading. What should I do?

我想正是这样的，非常感谢您的指导。顺便我还想请教一个问题，我将ConsumerThreadCount设置成8，我观察了RabbitMQ，发现确实起了绑定了8个消费者，可他并没有像我想象的那样使得消费速度提高？和默认的1个消费者线程消费速度几乎没有差别甚至更慢。我们队列的消息积压的很多，他们之间没有依赖性，我希望能够有更多的消费线程加入。奇怪的是，我新开一个程序实例，又能够起到加速消费的效果。。我希望充分利用多线程，请问应该怎么做？

**Comment by yang-xiaodong** [comment]
> 我将ConsumerThreadCount设置成8，我观察了RabbitMQ，发现确实起了绑定了8个消费者，可他并没有像我想象的那样使得消费速度提高

我刚测试了，无法复现，请提供测试步骤

**Comment by yang-xiaodong** [comment]
No response, closed!
