### ISSUE TITLE
事务的问题

### ISSUE THREAD

**Issue by floweroflove** [dotnetcore/CAP#1346]
感觉简单，实用。
但我自己有事务工作单元。我编译看事务那里调用了database.begentransaction().
我觉得是不是应该在publish的时候指定一个事务会更好一点。

**Comment by floweroflove** [comment]
我的事务会存在嵌套，因为内部使用了database.begentransaction().会导致我的事务嵌套有两个事务上下文

**Comment by yang-xiaodong** [comment]
No response, closed!
