### ISSUE TITLE
Azure Service Bus transport: Subscription Auto-delete

### ISSUE THREAD

**Issue by StevenDevooght** [dotnetcore/CAP#1347]
We would like to configure the [AutoDeleteOnIdle](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.createsubscriptionoptions.autodeleteonidle?view=azure-dotnet#azure-messaging-servicebus-administration-createsubscriptionoptions-autodeleteonidle) option on Topic subscriptions created by cap. At the moment this is not possible. The AutoDeleteOnIdle can be set [when creating a subscription](https://github.com/dotnetcore/CAP/blob/9c133dc1d0b7e9a775b6c66800f24db20c7e66bc/src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs#LL199C33-L202C35).

For our use case we are using cap to broadcast messages to all our running instances of our app service. For each running instance we have a seperate topic subscription (using `Environment.MachineName`). When an instance is no longer required we would also like to clean up the subscription linked to it. Therefore the AutoDeleteOnIdle would come handy.

Is this a change you would allow/accept in cap?

**Comment by mviegas** [comment]
Sure, it would be a transport-specific feature! Feel free to submit a PR adding this to `AzureServiceBusOptions` and adjusting the subscription creation to activate this flag.
