### ISSUE TITLE
Dashboard is not working

### ISSUE THREAD

**Issue by ipogorelyi** [dotnetcore/CAP#1348]
Hello,

When navigating to /cap there's the following message in console: Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

index.html cannot access styles and scripts
<script type="module" crossorigin src="./assets/index.631dd52b.js"></script>
<link rel="stylesheet" href="./assets/index.b058bca8.css">

This is what returned from url https://localhost:47091/cap/assets/index.b058bca8.css (or https://localhost:47091/cap/assets/index.631dd52b.js):
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="" />
    <link rel="manifest" href="/manifest.json" />
    <title>Robin</title>
<script defer src="/static/js/bundle.js"></script></head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>`

I use version 7.1.3
Configuration is following:
`services.AddCap(options =>
        {
            var prefix = HostEnvironment.IsDevelopment()
                ? Environment.MachineName.ToLower()
                : HostEnvironment.EnvironmentName.ToLower();
            options.UseSqlServer(sqlServerOptions =>
            {
                sqlServerOptions.ConnectionString = connectionString;
            });
            options.UseAzureServiceBus(serviceBusOptions =>
            {
                serviceBusOptions.ConnectionString = serviceBusSettings.ConnectionString;
                serviceBusOptions.TopicPath = $"{prefix}.sbt-domain";
            });
            options.UseDashboard(dashboardOptions =>
            {
                dashboardOptions.UseAuth = true;
            });
            options.FailedRetryCount = 5;
        });`
I tried different auth options and no auth as well.

Is there anything I missed in the configuration?

**Comment by yang-xiaodong** [comment]
Hello, 

CAP uses ASP.NET Core for authentication with HttpContext.AuthenticateAsync. Please check your Default Authentication Scheme.

Out samples :https://github.com/dotnetcore/CAP/blob/master/samples/Sample.Dashboard.Auth/Startup.cs
