### ISSUE TITLE
RabbitMQ sometimes fails to reconnect

### ISSUE THREAD

**Issue by li517451737** [dotnetcore/CAP#1349]
Version:  6.2.1
Description:
We have found that occasionally the message queue connection is disconnected and cannot be reconnected during use.
After checking the logs and finding that the Transport connnection is unhealty log, there is no more output of the Transport connection checking log.
We are still unable to find out what is causing the problem, do you have any suggestions to troubleshoot the problem? Thanks!
Screenshots of the logs are as follows:
![image](https://github.com/dotnetcore/CAP/assets/19256832/ae3df682-4c6a-4443-9182-5b15c9abe7b2)

![image](https://github.com/dotnetcore/CAP/assets/19256832/ff994929-f666-4321-a6d8-4c78ebce11d0)

**Comment by yang-xiaodong** [comment]
Hello, 

Through Google search, it was discovered that there are tons of possible reasons that can lead to "Pipelining of requests forbidden." If you can reproduce the issue, please provide the steps. Otherwise, we won't be able to provide assistance.

https://github.com/dotnetcore/CAP/issues?q=+Pipelining+of+requests+forbidden

**Comment by li517451737** [comment]
I can't reproduce the problem now, it's only happened twice in a while.
When the connection is disconnected, I don't find "Transport connection checking..." in the log file in the log output.  I think the ProcessAsync method in the TransportCheckProcessor has stopped running or is blocked.
The "Pipelining of requests forbidden" error should not affect the operation of the health check method.

**Comment by yang-xiaodong** [comment]
> TransportCheckProcessor has stopped running or is blocked

Do you know how to reproduce ?

**Comment by li517451737** [comment]
> > TransportCheckProcessor has stopped running or is blocked
> 
> Do you know how to reproduce ?
Sorry, I can't reproduce it yet, still trying to troubleshoot. 
The problem only appears occasionally in the customer environment now, and it does not appear in any of the local development test environments.
For now we can only add some logs to locate the problem first.

**Comment by li517451737** [comment]
> > TransportCheckProcessor has stopped running or is blocked
> 
> Do you know how to reproduce ?

Sorry, I can't reproduce it yet, still trying to troubleshoot. 
The problem only appears occasionally in the customer environment now, and it does not appear in any of the local development test environments.
For now we can only add some logs to locate the problem first.

**Comment by yang-xiaodong** [comment]
Hi @li517451737  ,
Since you can't reproduce and I closed the issue. Fell free to reopen it if you find the  troubleshoot.
