### ISSUE TITLE
Whether it support multiple concurrency？

### ISSUE THREAD

**Issue by yilezhu** [dotnetcore/CAP#135]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Whether it support multiple concurrency？
Whether it support multiple concurrency？
___
### Bug
- Which version of CAP, OS and .NET Core?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yuleyule66** [comment]
unqualified issue, closed!
