### ISSUE TITLE
Send message to specific Kafka partition

### ISSUE THREAD

**Issue by SAhmadvand** [dotnetcore/CAP#1352]
Hello!
Is there any way to send a specific message to a specific partition in Kafka?

**Comment by yang-xiaodong** [comment]
Hi,
You can customize the `ITransport` interface, then read the partition ID you want to set from the Header, and use the overload of `ProduceAsync(TopicPartition topicPartition, Message<TKey, TValue> message, CancellationToken cancellationToken)` to send.
