### ISSUE TITLE
cap.lock LastLockTime up to 2026/02/02

### ISSUE THREAD

**Issue by sampsonye** [dotnetcore/CAP#1353]
too many receiveing event  blocking cause table `cap.lock.LastLockTime` too long

I think should change 
```
public async Task RenewLockAsync(string key, TimeSpan ttl, string instance, CancellationToken token = default)
    {
        var sql = $"UPDATE `{_lockName}` SET `LastLockTime`= date_add(`LastLockTime`, interval {ttl.TotalSeconds} second) WHERE `Key`=@Key AND `Instance`=@Instance;";
        var connection = new MySqlConnection(_options.Value.ConnectionString);
        await using var _ = connection.ConfigureAwait(false);
        object[] sqlParams =
        {
            new MySqlParameter("@Instance", instance),
            new MySqlParameter("@Key", key)
        };
        await connection.ExecuteNonQueryAsync(sql, sqlParams: sqlParams).ConfigureAwait(false);
    }
```
to 
```
public async Task RenewLockAsync(string key, TimeSpan ttl, string instance, CancellationToken token = default)
    {
        var sql = $"UPDATE `{_lockName}` SET `LastLockTime`=@LastLockTime  WHERE `Key`=@Key AND `Instance`=@Instance;";
        var connection = new MySqlConnection(_options.Value.ConnectionString);
        await using var _ = connection.ConfigureAwait(false);
        object[] sqlParams =
        {
            new MySqlParameter("@Instance", instance),
            new MySqlParameter("@Key", key),
            new MySqlParameter("@LastLockTime", DateTime.Now.Add(ttl)),
        };
        await connection.ExecuteNonQueryAsync(sql, sqlParams: sqlParams).ConfigureAwait(false);
    }
```

**Comment by yang-xiaodong** [comment]
Hi @li-zheng-hao ,

Can you investigate and focus on this issue? Thank you.

@sampsonye Please provide more info about why the lock time to 2026 years

**Comment by li-zheng-hao** [comment]
Normally, after CAP acquires the lock, it retrieves the messages that need to be retried from the database. After this batch of messages is consumed, the lock will be released and  LastLockTime will be reset to the minimum value.

The only scenario I can think of that could cause this issue is this batch of messages has not been completely consumed for a long time (the retry interval is 60 seconds and the lock holding time is 70 seconds) . If this is the case, I think you need to check your code. If it's a different scenario, please provide more information.

**Comment by sampsonye** [comment]
> Normally, after CAP acquires the lock, it retrieves the messages that need to be retried from the database. After this batch of messages is consumed, the lock will be released and LastLockTime will be reset to the minimum value.
> 
> The only scenario I can think of that could cause this issue is this batch of messages has not been completely consumed for a long time (the retry interval is 60 seconds and the lock holding time is 70 seconds) . If this is the case, I think you need to check your code. If it's a different scenario, please provide more information.

sure because of many 'Scheduled' message 
![企业微信截图_1685933193351](https://github.com/dotnetcore/CAP/assets/5895634/26e3e8cb-65e4-4fc4-aada-c13341789edb)

this lock time too long aggravate Message Stacking

**Comment by yang-xiaodong** [comment]
@sampsonye I noticed that you are using CAP to process long-running jobs in another issue , this issue's question is the continue of that issue?

**Comment by sampsonye** [comment]
> @sampsonye I noticed that you are using CAP to process long-running jobs in another issue , this issue's question is the continue of that issue?

yeah,the same reason

**Comment by yang-xiaodong** [comment]
OK, CAP is not support long-running jobs. 
Now I closed the issue.
