### ISSUE TITLE
Is it possible to have parallel subscribers to a topic?

### ISSUE THREAD

**Issue by xilapa** [dotnetcore/CAP#1363]
I've two subscribers methods on my application:

- One that receives some data to process, **which I want to enable a certain degree of parallelism**, to process five messages at a time on distinct scopes;
- Another subscriber that sends mail messages, **which I don't want to enable parallelism** because I have a limit to sending emails per minute. With only one instance of this subscriber, I can throttle this.

Currently on CAP, I can only have one instance of each subscriber using `UseDispatchingPerGroup=true` and different groups on `[CAPSubscribe]` attribute. I can't consume messages in parallel from a specific topic.

Is there a way to have some subscribers to work in parallel while others remain unique/singletons?

**Comment by yang-xiaodong** [comment]
CAP does not support setting the thread count separately for each consumer. One simple way is to enable multiple CAP instances to configure individual thread counts for each instance.

Program.cs
```cs
using DotNetCore.CAP;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

var uniqueSc = new ServiceCollection();
uniqueSc.AddLogging(x => x.AddConsole());
uniqueSc.AddSingleton<SendEmail>();
uniqueSc.AddCap(x =>
{
    x.DefaultGroupName = "Unique";
    x.UseRabbitMQ(aa =>
    {
        aa.HostName = "192.168.3.57";
        aa.UserName = "user";
        aa.Password = "wJ0p5gSs17";
    });
    x.UseInMemoryStorage();
    x.ConsumerThreadCount = 1;
});
await uniqueSc.BuildServiceProvider().GetRequiredService<IBootstrapper>().BootstrapAsync();

var parallelSc = new ServiceCollection();
parallelSc.AddLogging(x => x.AddConsole());
parallelSc.AddSingleton<ParallelProcess>();
parallelSc.AddCap(x =>
{
    x.DefaultGroupName = "Parallel";
    x.UseRabbitMQ(aa =>
    {
        aa.HostName = "192.168.3.57";
        aa.UserName = "user";
        aa.Password = "wJ0p5gSs17";
    });
    x.ConsumerThreadCount = 5;
    x.UseInMemoryStorage();
});
await parallelSc.BuildServiceProvider().GetRequiredService<IBootstrapper>().BootstrapAsync();

Console.ReadLine();

class SendEmail : ICapSubscribe
{
    [CapSubscribe("send.email")]
    public async Task Send()
    {
        await Task.Delay(1000);
        Console.WriteLine("Send Email: " + DateTime.Now);
    }
}

class ParallelProcess : ICapSubscribe
{
    [CapSubscribe("parallel.process")]
    public async Task Process()
    {
        await Task.Delay(1000);
        Console.WriteLine("Parallel Process: " + DateTime.Now);
    }
}
```

**Comment by xilapa** [comment]
Thx. I'll try that.
