### ISSUE TITLE
NATS No responders are available for the request.

### ISSUE THREAD

**Issue by kuiyu** [dotnetcore/CAP#1364]
-
控制台应用中，订阅者，发布者无论哪个先启动，正常收发消息
asp.net core web应用中，订阅者必须先启动，才能收到发布者的消息;否则，在发布者优先订阅者启动的情况下，发布消息报错：

DotNetCore.CAP.Internal.PublisherSentFailedException: No responders are available for the request.
 ---> NATS.Client.NATSNoRespondersException: No responders are available for the request.
   at NATS.Client.Connection.requestAsync(String subject, Byte[] headers, Byte[] data, Int32 offset, Int32 count, Int32 timeout, CancellationToken token)
   at NATS.Client.JetStream.JetStream.PublishAsyncInternal(String subject, Byte[] data, MsgHeader hdr, PublishOptions options)
   at DotNetCore.CAP.NATS.NATSTransport.SendAsync(TransportMessage message)
   --- End of inner exception stack trace ---

是bug还是改代码?

**Comment by yang-xiaodong** [comment]
No Responders means the server cannot find any stream with the subject you are publishing to. You need to create stream at first, Starting CAP consumers is a simple way to create stream.

**Comment by kuiyu** [comment]
还要修改什么吗？
当前代码是
```csharp
builder.Services.AddCap(x =>
{
    x.UseDashboard();
    x.UseMySql("Server=127.0.0.1;Uid=root;Pwd=123456;Database=rswl_cap;Port=3306");
    x.UseNATS(opt =>
    {
        opt.Servers = "nats://127.0.0.1:4222";
    });
    x.UseDiscovery();
});
```

**Comment by yang-xiaodong** [comment]
I think you need to understand the concept of JetStream in NATS in order to understand what I mean. Take a look [here](https://docs.nats.io/nats-concepts/jetstream) to learn more.
