### ISSUE TITLE
dashboard  question 

### ISSUE THREAD

**Issue by linjianpin136** [dotnetcore/CAP#1366]
实际使用过程中，还会存在CAP仪表显示推送成功，但是推送记录表状态为 Queued，消费端却没有收到消息，造成消息丢失的情况。这种时候无从查询错误原因，查看数据库状态也没有发现锁表超时的情况。要是能在成功列表反馈最终结果就好

![1688118065968](https://github.com/dotnetcore/CAP/assets/37535083/307da9a6-169d-4b8f-b767-ccb312e5ba13)

**Comment by yang-xiaodong** [comment]
Queued 代表延迟消息还没有发送，当然消费者收不到。 你可以在‘延迟’中点击立即发送。
