### ISSUE TITLE
Is it possible to disable consumers?

### ISSUE THREAD

**Issue by xilapa** [dotnetcore/CAP#1367]
I've a WebApi that only produce messages which are consumed by another service. This WebApi doesn't have consumers/subscribers registered and I'm getting an error message  `Message *** can not be found subscriber`.

I tried to set `ConsumerThreadCount` to zero but it didn't work.

Is there a way to disable the consumers and only produce messages?

**Comment by yang-xiaodong** [comment]
Have you seen #63 yet?

**Comment by xilapa** [comment]
> Have you seen #63 yet?

No, I've just looked it. In my case the problem is the shared database between services. CAP keeps reading the received table. 
I've found a work arround, using different schemas for CAP tables on each service seems to work.

**Comment by yang-xiaodong** [comment]
Yes, If all you services use one database, you need to using different schema for each service.


![image](https://github.com/dotnetcore/CAP/assets/8205994/b16aa98d-c565-4582-aecf-27abc553c2f0)
