### ISSUE TITLE
[BUG] CAP.AzureServiceBus Unable to complete a message if AutoCompleteMessages = false

### ISSUE THREAD

**Issue by Wiks00** [dotnetcore/CAP#1370]
The AutoCompleteMessages functionality is implemented incorrectly, it does not allow you to manually complete a message if set to false.  Since it is not possible to get [MessageReceiver](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.messagereceiver?view=azure-dotnet) in the subscriber. And for some reason `EnableSession `must be set to true to enable it.

https://github.com/dotnetcore/CAP/blob/11127e2b6d7b93812b66de07124d506a60450345/src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs#L204-L205

https://github.com/dotnetcore/CAP/blob/11127e2b6d7b93812b66de07124d506a60450345/src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs#L213-L218

**Comment by yang-xiaodong** [comment]
No plans and contributors, set to backlog, any PR is welcome.
