### ISSUE TITLE
kafka连接数瞬时飙高问题

### ISSUE THREAD

**Issue by ajdwfnhaps** [dotnetcore/CAP#1375]
# 我们发现每次重启集群服务时或批量生产发送消息时，kafka连接数都会飙高，请查看以下截图

![image](https://github.com/dotnetcore/CAP/assets/11205717/fbc38d2a-c833-4ae4-a7a6-1345e8f71f17)

有时候甚至上了几万，但是阿里云kafka有连接数限制，超出了会影响使用稳定性。

- 我们大概有65 deployments ，225 pods

![image](https://github.com/dotnetcore/CAP/assets/11205717/bacb9451-52e6-47d7-9dbb-11825b73e1c5)

- 连接配置如下：

![image](https://github.com/dotnetcore/CAP/assets/11205717/54c080a4-5b37-4c2c-a44d-bcca03de2e7a)

- 查看cap kafka连接池代码，有些疑问
  **是否当设置的连接池满了之后，有高并发请求时，会大量创建连接呢，当无用连接超时后 又自动释放，连接数就是又降下来了
  ，但是会造成瞬时连接数飙很高的问题，请问有没有什么解决方案？**
![image](https://github.com/dotnetcore/CAP/assets/11205717/cfad3370-1b2b-4adc-a793-92007cfea34e)

**Comment by yang-xiaodong** [comment]
连接池你设置的是1太小了，你可以你们的场景来决定连接池的大小

**Comment by ajdwfnhaps** [comment]
一开始全部服务都时默认连接池10，但是发现有这种飙高的情况，我们才把大部分小的服务都设置为1，但是还是会出现这个问题，创建连接时不是线程安全的，会不会加上控制好点？

**Comment by yang-xiaodong** [comment]
你是指 `if (Interlocked.Increment(ref _pCount) <= _maxSize)` 这个判断不是线程安全的吗？

**Comment by ajdwfnhaps** [comment]
那个是Return归还的时候，我是说租借时的以下这段代码
![image](https://github.com/dotnetcore/CAP/assets/11205717/7b9d9ada-b1fa-4fff-9bd5-c64778442df0)

在连接池满了之后，是不是会高并发时创建连接会有线程安全的问题

**Comment by yang-xiaodong** [comment]
BuildProducer里面直接new的新连接啊，你说线程安全指的是？

**Comment by yang-xiaodong** [comment]
你要想池满的时候，把生产者卡住等待连接释放，可以参考RabbitMQ里面的处理方式

https://github.com/dotnetcore/CAP/blob/11127e2b6d7b93812b66de07124d506a60450345/src/DotNetCore.CAP.RabbitMQ/IConnectionChannelPool.Default.cs#L54-L58

**Comment by ajdwfnhaps** [comment]
明白，刚看了RabbitMq的实现，是通过线程自旋等待连接池有空闲时 再租借，但是kafka的实现 是超过了连接池后 还会不断创建新的，而且没有一个封顶的限制，只有返还的时候判断超出池大小了会Dispose掉，如果我在超出了池大小后，有个批量循环发送10000条消息，kafka的连接数应该会很高。

我的想法是，超出了连接池后 继续创建是没问题的，但是没有封顶连接数，如果在一段时间内池还是满的，正好这个时候有大量的消息正在发送，会不断的创建新连接，能否池满了自动把池拉大一点 类似于List<T>的DefaultCapacity 默认容量的概念

**Comment by yang-xiaodong** [comment]
> 我的想法是，超出了连接池后 继续创建是没问题的，但是没有封顶连接数，如果在一段时间内池还是满的，正好这个时候有大量的消息正在发送，会不断的创建新连接，能否池满了自动把池拉大一点 类似于List的DefaultCapacity 默认容量的概念

对此你愿意提交一个PR吗？

**Comment by ajdwfnhaps** [comment]
好的，我想想具体实现方案，周末尝试提个PR
