### ISSUE TITLE
Consumer based retry process required

### ISSUE THREAD

**Issue by batgungor** [dotnetcore/CAP#1377]
Hi!
we need to provide consumer based retry limit for our process. We tried to implement custom solution in Filter (OnSubscribeException). There are 2 problems on here
1. How can we get the retry index? For example we need to get is this the 3rd retry? (We can implement our solution for here but I want to hear your suggestions also)
2. If I decide this limit reached, how can I mark this message as "Failed"? We need to see this message on dashboard as failed. Also we need to manule retry via interface after we decide why we get an exception.

We tried to use "ExceptionHandled = true" when we decide to reach limit, but when we do this, couldn't see this message as failed.

Thanks.

**Comment by yang-xiaodong** [comment]
Hi, Do you want to set the number of retries individually for each consumer?

**Comment by batgungor** [comment]
Hi, Yes we need to do this.

**Comment by batgungor** [comment]
@yang-xiaodong Do you have any suggestion or solution for that? Or do you working on it? Maybe we can work together or maybe I can try to contribute the package :)

**Comment by yang-xiaodong** [comment]
Hi @batgungor 

We don't support this feature yet, I'm busy lately, it would be great if you would like to contribute. 

Thanks very much.

**Comment by bschwehn** [comment]
@yang-xiaodong 
We have a somewhat similar requirement. While it is not a very clean solution, a fairly minimal change in CAP would allow us to accomplish what we want. If we add the `MediumMessage `to the `ConsumerContext`, for example like:

1. change ctor to
     ```
  public ConsumerContext(ConsumerExecutorDescriptor descriptor, MediumMessage message)
    {
        ConsumerDescriptor = descriptor ?? throw new ArgumentNullException(nameof(descriptor));
        MediumMessage = message ?? throw new ArgumentNullException(nameof(message));
    }
```

2. Add MediumMessage property:
   ```
    public Message DeliverMessage
    {
        get
        {
            return MediumMessage.Origin;
        }
    }
    public MediumMessage MediumMessage { get; }
```

    (keeping `DeliverMessage `for backwards compatibility)

3. Change to use the constructor in `SubscribeExecutor.InvokeConsumerMethodAsync`


This allows a `SubscribeFilter `to set the `MediumMessage.Retries` in `OnSubscribeExceptionAsync`.

Would this change be something you would accept as a PR?
