### ISSUE TITLE
MongoDB needs to add a Singleton pattern to support. netcore version 6.0

### ISSUE THREAD

**Issue by gogo1008** [dotnetcore/CAP#1379]
1. Some users only have a single computer, and the need MongoDB 4.0+cluster mode can cause memory overflow and MongoDB often stops

2. It is recommended to add a parameter, or if there are no multiple connections in the connection string, it means to use the Singleton pattern

**Comment by yang-xiaodong** [comment]
Only mongoDB cluster  support transaction. see https://www.digitalocean.com/community/tutorials/how-to-use-transactions-in-mongodb#step-1-converting-your-standalone-mongodb-instance-into-a-replica-set

**Comment by gogo1008** [comment]
@yang-xiaodong It's not a replica set issue. The replica set is configured, and if there is not enough memory, it will overflow, causing the mongodb process to be killed. Therefore, it is necessary to support a single mogodb, so that at least it will not die when there is not enough memory

**Comment by yang-xiaodong** [comment]
I mean without using mongodb cluster CAP will not work, because mongodb transactions need to be in cluster mode.
