### ISSUE TITLE
CAP.OpenTelemetry Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jakey188** [dotnetcore/CAP#1381]
<PackageReference Include="DotNetCore.CAP" Version="7.2.0" />
<PackageReference Include="DotNetCore.CAP.Dashboard" Version="7.2.0" />
<PackageReference Include="DotNetCore.CAP.MySql" Version="7.2.0" />
<PackageReference Include="DotNetCore.CAP.OpenTelemetry" Version="7.2.0" />
<PackageReference Include="DotNetCore.CAP.RedisStreams" Version="7.2.0" />
<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.5.1" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.5.1" />
<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.1-beta.1" />

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=DotNetCore.CAP.OpenTelemetry
  StackTrace:
   在 DotNetCore.CAP.OpenTelemetry.DiagnosticListener.OnNext(KeyValuePair`2 evt)

builder.Services.AddCap(cap =>
{
    cap.UseMySql(c =>
    {
        c.ConnectionString = "server=localhost;Database=test11;Uid=root;Pwd=123456;charset=utf8";
    });
    cap.UseRedis(c =>
    {
        c.Configuration = ConfigurationOptions.Parse("127.0.0.1");
        c.StreamEntriesCount = 10; //读取时从 stream 返回的条目数,默认10
        c.ConnectionPoolSize = 10; //连接池数,默认10
    });
    cap.UseDashboard();
});
//.AddSubscribeFilter<CapTestFilter>();

builder.Services.AddOpenTelemetry()
        .WithTracing(builder => builder
            .AddAspNetCoreInstrumentation()
            .AddCapInstrumentation()    // <-- 添加这行
            .AddConsoleExporter());

[HttpGet("p1")]
      public async Task<IActionResult> p1()
      {
          var user = new User { id = 1, name = "hello" };

          await _publisher.PublishAsync<User>("cap.test111", user);

          return Ok();
      }

      [NonAction]
      [CapSubscribe("cap.test111")]
      public void Sub1(User user)
      {
          Console.WriteLine(user?.name);
      }

**Comment by yang-xiaodong** [comment]
Closed by https://zhuanlan.zhihu.com/p/25795393
