### ISSUE TITLE
[System.Diagnostics] Opentelemetry and Dynatrace One Agent

### ISSUE THREAD

**Issue by phmonte** [dotnetcore/CAP#1387]
Is there any reason to use [_contexts](https://github.com/dotnetcore/CAP/blob/0d8e9357d26a57140528141b30feb926e6a53bdb/src/DotNetCore.CAP.OpenTelemetry/DiagnosticListener.cs#L24) instead of using [Propagator.Inject](https://github.com/dotnetcore/CAP/blob/0d8e9357d26a57140528141b30feb926e6a53bdb/src/DotNetCore.CAP.OpenTelemetry/DiagnosticListener.cs#L111) for this function?

In the [CapEvents.BeforePublish](https://github.com/dotnetcore/CAP/blob/0d8e9357d26a57140528141b30feb926e6a53bdb/src/DotNetCore.CAP.OpenTelemetry/DiagnosticListener.cs#L94) event, as the Context of a _contexts variable is retrieved, the [IsRemote ](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitycontext.isremote?view=net-8.0#system-diagnostics-activitycontext-isremote)property of Context is false by default, however this variable should be true([according to microsoft documentation](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitycontext.isremote?view=net-8.0#system-diagnostics-activitycontext-isremote)), as the [CapEvents.BeforePublish ](https://github.com/dotnetcore/CAP/blob/0d8e9357d26a57140528141b30feb926e6a53bdb/src/DotNetCore.CAP.OpenTelemetry/DiagnosticListener.cs#L94)event is not executed in the main thread, but in a background service .

When using Propagator.Inject automatically the IsRemote property is considered true.

Impact:
When using Dynatrace OneAgent we encountered problems when logging the Activity referring to the publish message, because without the variable IsRemote = true dynatrace is unable to create the necessary links.

**Comment by yang-xiaodong** [comment]
Hi,

I did not clearly understand what you meant; isn't it Propagator.Inject in CapEvents.BeforePublish? If you are willing to submit a PR, I will review it.

**Comment by yang-xiaodong** [comment]
No Response, Closed!

**Comment by phmonte** [comment]
Sorry for the delay, I opened the [PR](https://github.com/dotnetcore/CAP/pull/1402)
