### ISSUE TITLE
[Bug] Dashboard sqlserver case sensitive

### ISSUE THREAD

**Issue by anhuizf1** [dotnetcore/CAP#1389]
根据数据库语句如下：
exec sp_executesql N'select count(1) from cap.Published where 1=1  and statusname=@StatusName',
N'@StatusName nvarchar(9),@Group nvarchar(4000),@Name nvarchar(4000),@Content nvarchar(2)',@StatusName=N'succeeded',@Group=N'',@Name=N'',@Content=N'%%'
有些数据库安装时选择大小写敏感的，所以会报列名 'statusname' 无效。

**Comment by yang-xiaodong** [comment]
Would you like to submit a PR?
