### ISSUE TITLE
CAP初始化错误---> 从字符串转换日期和/或时间时，转换失败。

### ISSUE THREAD

**Issue by fayuanliu** [dotnetcore/CAP#139]
数据库，表结构已经生成，表示数据库连接 没有问题。
详细问题如图：
![image](https://user-images.githubusercontent.com/11306331/41025735-5050e3d2-69a5-11e8-84d9-77d14bc0d9c6.png)

**Comment by fayuanliu** [comment]
Task<IEnumerable<CapPublishedMessage>> GetPublishedMessagesOfNeedRetry()
var fourMinsAgo = DateTime.Now.AddMinutes(-4);
取出的时间包含了 中文：2018/6/6 下午 05:57:43
导致sql 出错：
SELECT TOP (200) * FROM [Cap].[Published] WITH (readpast) WHERE Retries<50 AND Added<'2018/6/6 下午 05:57:43' AND (StatusName = 'Failed' OR StatusName = 'Scheduled')
希望可以对datetime进行格式化

**Comment by yuleyule66** [comment]
是的，此处应该进行格式化处理，防止地域影响下的格式化的错误。 谢谢反馈

**Comment by yuleyule66** [comment]
Fixed in version `2.2.5-preview-45139132`
