### ISSUE TITLE
same message is consumed by different instances

### ISSUE THREAD

**Issue by cagataykiziltan** [dotnetcore/CAP#1390]
hi,
i am using cap with rabbit mq + mongodb. And my application runs on 10 pods in kubernetes. When a message fails and retries, more than one consumer instance catches same message and try to execute. Are there any configuration to prevent that?
thanks

**Comment by yang-xiaodong** [comment]
Hi,
Yes, you can config [UseStorageLock](https://cap.dotnetcore.xyz/user-guide/en/cap/configuration/#usestoragelock) option
