### ISSUE TITLE
Use typed const paramter to consume  instead of use string

### ISSUE THREAD

**Issue by shaoqilan** [dotnetcore/CAP#1401]
项目中使用过多的常量可能不方便维护，如果name参数使用type类型可以使用type.FullName来确定监听的name
类似以下写法
![image](https://github.com/dotnetcore/CAP/assets/29734798/c97bb6b8-f143-41e9-b29c-df6582091e6a)
这样可以减少定义常量出错的概率。

同样Publish也可以不用设置name的值，通过传入的参数类型来自动确定name的值

![image](https://github.com/dotnetcore/CAP/assets/29734798/26d2aee9-b28c-4b50-bc02-a026191ecfe1)

阅读了相关源码发现继承TopicAttribute可以自定义实现以上功能，但受限于TopicAttribute中的Name是只读属性，必须修改源码允许set才能满足要求。

希望可以调整TopicAttribute中的Name属性允许set操作，这样可以自定义该项功能。

**Comment by yang-xiaodong** [comment]
It's so easy

1. name parameter use type.FullName
```C#
  public class EventSubscribeAttribute : TopicAttribute
  {
      public EventSubscribeAttribute(Type type)
          : base(type.FullName)
      {
      }

      public override string ToString()
      {
          return Name;
      }
  }
```

2. Add ICapPublisher extension method for typed overload
