### ISSUE TITLE
RabbitMQ basicConsume TimeOutException

### ISSUE THREAD

**Issue by pandarun** [dotnetcore/CAP#1405]
Hi, I've noticed strange behavior:

If CAP library with RabbitMq transport gets TimeOutException while calling BasicConsume it won't resubscribe.

https://github.com/dotnetcore/CAP/blob/203bf5a621c7e794d0cdce36ebf02216cff45db0/src/DotNetCore.CAP.RabbitMQ/RabbitMQConsumerClient.cs#L73

 Exception then is propagated to logs and thread finishes

https://github.com/dotnetcore/CAP/blob/203bf5a621c7e794d0cdce36ebf02216cff45db0/src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs#L152

https://github.com/dotnetcore/CAP/blob/203bf5a621c7e794d0cdce36ebf02216cff45db0/src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs#L164

stack trace example attached

![image](https://github.com/dotnetcore/CAP/assets/1056050/086ce54d-add5-419c-b123-ac0a746cc5c1)

**Comment by yang-xiaodong** [comment]
We have performed a pre-check to confirm the reachability of the RabbitMQ service. It seems like your application terminated between the pre-check and the listening phase, is that correct?

https://github.com/dotnetcore/CAP/blob/203bf5a621c7e794d0cdce36ebf02216cff45db0/src/DotNetCore.CAP.RabbitMQ/RabbitMQConsumerClientFactory.cs#L28-L36

**Comment by pandarun** [comment]
>  It seems like your rabbitmq service terminated between the pre-check and the listening phase, is that correct?

Can be, but may be some other network glitch, or suspended process or something else. It just appeared TimeOutException in logs which is then leads to client disposal and error log entry.
