### ISSUE TITLE
Problem when Consume event in local

### ISSUE THREAD

**Issue by ductai202** [dotnetcore/CAP#1406]
Hi everyone, my team now are using CAP library (version 6.2.1.0) to control event bus with RabbitMQ, and using Visual Studio 2022. 
I got a problem when trying to debug a consume event bus after published that event. It cannot go to the debug, although that event still processed successfully. Than I check the dashboard that I see that event is consumed by my teammate computer (seems like he's running the code but not open debugging so he cannot see the event)
For example: I want to consume an event 
<img width="741" alt="WXWorkCapture_1696237834174" src="https://github.com/dotnetcore/CAP/assets/70333438/8d3f8bfa-5352-4096-9d13-e014f031e008">
but sometimes it executed by another computer
<img width="766" alt="WXWorkCapture_16962378574238" src="https://github.com/dotnetcore/CAP/assets/70333438/ac244b65-cb50-4735-a38b-8a3264c0b357">
<img width="671" alt="WXWorkCapture_16962378698953" src="https://github.com/dotnetcore/CAP/assets/70333438/5b1a0644-6738-484b-82c5-97f48dd9f2f0">
So sometimes it's hard for us to debug an event in local envirionment. I've tried to change DefaultGroupName variable in CapOptions setting, but seems not works. Do you guys have any suggestion ?

**Comment by xiangxiren** [comment]
Set different versions.

**Comment by ductai202** [comment]
Which version now is most stable ?

**Comment by jianxuanbing** [comment]
you can set up a custom version for local use.

**Comment by xiangxiren** [comment]
```
services.AddCap(setup =>
{
    setup.Version = "xxx"; //your customerversion
    ......
}
```

**Comment by ductai202** [comment]
So the version 7.x I think should be fine ha 🤒

**Comment by ductai202** [comment]
Seems not works

**Comment by ductai202** [comment]
Seems it's okay. But I just wonder why change GroupName or change QueueName not works, while change Version name is works

**Comment by xiangxiren** [comment]
> Seems it's okay. But I just wonder why change GroupName or change QueueName not works, while change Version name is works

Messages will not only be delivered to your newly created queue, but also to the old queue, where your colleague's computer can still consume through the old queue. In DotNetCore.CAP.RabbitMQ, setting GroupName is actually binding the same topic to another queue.

When setting the version, the internal system will check whether the version of the message is consistent with the current version of the service. If it is consistent, it will be consumed.

**Comment by ductai202** [comment]
Got it, thanks guys 😁
