### ISSUE TITLE
Using SqlConnection with AccessToken should be possible

### ISSUE THREAD

**Issue by t-zalewski** [dotnetcore/CAP#1408]
Hello,

Currently in our solution, to access our databases, we are using Entity Framework together with AccessToken for SqlConnection to SqlServer. We re trying to use your library as it seems to provide a lot of value, but we can't manage it to work with our setup. **x.UseEntityFramework** doesn't seem to take this access token from our context into the account and CAP is not able to connect to database. We also tried to use **x.UseSqlServer** method but alse we see no configuration option for AccessToken here. Is there any way to solve that issue?

Best regards,

**Comment by yang-xiaodong** [comment]
Hi,

Yes, our SqlConnection does not provide support for AccessToken. This authentication mode seems to be obsolete. Active Directory Default becomes the new replacement or you can use Azure Key Vault to manage connection.

**Comment by t-zalewski** [comment]
Hi,

Thanks for information. I dig deeper into the topic and your response helped me to re-think our solution. Thanks for quick reply!
