### ISSUE TITLE
DotNetCore.CAP.MySql.CapPublisher PrepareConnectionForEF Bug

### ISSUE THREAD

**Issue by mfemail8** [dotnetcore/CAP#141]
When _dbContext.Database.CurrentTransaction is null.  PrepareConnectionForEF will open a transaction by _dbContext.Database.BeginTransaction, this transaction should be commit through _dbContext.Database.CommitTransaction, but currenttly it is do in ClosedCap() of CapPublisherBase. This will cause issuse when other function try to use this DbContext.
If ClosedCap() of CapPublisherBase can be a virtual, and override it In DotNetCore.CAP.MySql.CapPublisher will avoid this. Or provide a virtual Commit function will be ok too.

**Comment by yuleyule66** [comment]
Why did you want to use CAP's opened transaction?

> This will cause issuse when other function try to use this DbContext.

What is the issue ? exception?

**Comment by mfemail8** [comment]
I used CapEventSink to connect CAP and IdentityServer4's Event

**Comment by mfemail8** [comment]
When IdentityServer4 use the same DbContext, for example v.ValidateAsync(context).Wait(); then will got this: InvalidOperationException: The transaction associated with this command is not the connection's active transaction; see https://github.com/mysql-net/MySqlConnector/issues/474

**Comment by yuleyule66** [comment]
Sorry , I don't quite understand what you mean~!

If you want to using EntityFramework to publish the events and control the transaction by your self, you can  do it like this:

```cs
[Route("~/publishWithTransactionUsingEF")]
public async Task<IActionResult> PublishMessageWithTransactionUsingEF([FromServices]AppDbContext dbContext, [FromServices]ICapPublisher publisher)
{
    using (var trans = dbContext.Database.BeginTransaction())
    {
        // your business code

        //If you are using EF, CAP will automatic discovery current environment transaction, so you do not need to explicit pass parameters.
        //Achieving atomicity between original database operation and the publish event log thanks to a local transaction.
        await publisher.PublishAsync("xxx.services.account.check", new Person { Name = "Foo", Age = 11 });

        trans.Commit();
    }
    return Ok();
}
```  
Because of you didn't show you configuration in the issues, so I can't recognition if you did something wrong or not. By the way,  you can using Chinese to write.

**Comment by yuleyule66** [comment]
>这个不太方便，mysql包里面打开事务的方法就白写了。
如果你的业务和Publish发送消息没有在一个事务环境中，是无法保证消息的可靠性的，所以这里要求必须是用户来开启事务，然后CAP检测当前环境中用户开启的使用然后加入到这个事务中去。 MySQL 包里面打开事务的方法白写了，这个我没有看明白？

>关键问题是你用dbcontext开事务，就应该用dbcontext提交事务

使用DbContext 开启事务，就用DbContext提交事务是什么意思呢？

**Comment by mfemail8** [comment]
dbcontext.database.committransaction
手机不方便贴代码

**Comment by mfemail8** [comment]
还有base类里面已经有ef的痕迹了，如果把dbcontext也放里面就省事了

**Comment by yuleyule66** [comment]
>dbcontext.database.committransaction 手机不方便贴代码

可以使用 `dbContext.Database.CommitTransaction();` 来提交，它和 `trans.Commit()` 是等价的。

>还有base类里面已经有ef的痕迹了，如果把dbcontext也放里面就省事了

这个是不能这么做的，因为你不知道用户在做业务的时候是先发消息还是后发消息

**Comment by mfemail8** [comment]
关于“ 可以使用 dbContext.Database.CommitTransaction(); 来提交，它和 trans.Commit() 是等价的。” 可能不是这样， 可以参看Pomelo.EntityFrameworkCore.MySql的MySqlRelationalTransaction， 这个是一个IDbContextTransaction的一个实现， 最关键的是在最后ClearTransaction(); 我在Base类里增加了一个CommitTransaction方法:
        protected virtual void CommitTransaction()
        {
            DbTransaction.Commit();
        }
在 CloseCAP里
private void ClosedCap()
        {
            if (IsCapOpenedTrans)
            {
                CommitTransaction();
                DbTransaction.Dispose();
            }
            if (IsCapOpenedConn)
            {
                DbConnection.Dispose();
            }
        }
 然后再MySql库里重写：
protected override void CommitTransaction()
        {
            if (IsUsingEF)
                _dbContext.Database.CommitTransaction();
            else
                base.CommitTransaction();
        }
然后就不抛异常了。

**Comment by yuleyule66** [comment]
>可能不是这样， 可以参看Pomelo.EntityFrameworkCore.MySql的MySqlRelationalTransaction， 这个是一个IDbContextTransaction的一个实现， 最关键的是在最后ClearTransaction();

能帖链接吗？

**Comment by mfemail8** [comment]
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Storage/Internal/MySqlRelationalTransaction.cs

**Comment by mfemail8** [comment]
Thanks
