### ISSUE TITLE
can you get capheader  more type 

### ISSUE THREAD

**Issue by liuzhixin405** [dotnetcore/CAP#1410]
the new code  like this  ,CapHeaderExt （i have not show more basic type,for eg string ,int ,string decimal ...） or CapHeaderGenerics<TKey,TValue> :
 public static class CapHeaderExtensions
    { 
        public static Int64 GetValueOrDefault<Int64>(this IReadOnlyDictionary<string, Int64> dictionary, string key)
        {
            return dictionary.GetValueOrDefault(key, default!);
        }
    }

    public class CapHeaderExt : ReadOnlyDictionary<string, Int64>
    {
        public CapHeaderExt(IDictionary<string, Int64> dictionary) : base(dictionary)
        {
        }
    }

    public class CapHeaderGenerics<TKey,TValue> : ReadOnlyDictionary<TKey, TValue>
    {
        public CapHeaderGenerics(IDictionary<TKey, TValue?> dictionary) :base(dictionary)
        {
            
        }
    }

**Comment by yang-xiaodong** [comment]
Closed by https://zhuanlan.zhihu.com/p/25795393
