### ISSUE TITLE
Add tags to ressources created with AWS UseAmazonSQS 

### ISSUE THREAD

**Issue by vhbfnet** [dotnetcore/CAP#1413]
Hello,

Is it possible to add an enhancement for the UseAmazonSQS configuration to allow adding tags to resources created automatically by CAP (topics, subscriptions, ...)?

Like so :
                o.UseAmazonSQS(opt =>
                {
                    **opt.Tags = { { "key1", "Val1" }, { "Key2", "Val2" } };**
                    opt.Region = Amazon.RegionEndpoint.EUWest3;
                    opt.Credentials = new BasicAWSCredentials("accessKey", "secretKey");
                });

Best regards.

**Comment by yang-xiaodong** [comment]
Hello,

Sure, Would you like to submit a PR?

**Comment by yang-xiaodong** [comment]
No response. closed
