### ISSUE TITLE
关于RabbitMQ替换为TongLINK/Q

### ISSUE THREAD

**Issue by kisshexuxia** [dotnetcore/CAP#1414]
目前在用的版本是CAP3.1.2
消息中间件用的是DotNetCore.CAP.RabbitMQ版本也是3.1.2
目前需要把消息中间件替换为TongLINK/Q，后续CAP会支持吗？

**Comment by yang-xiaodong** [comment]
No, it can be added to our documentation as a community extension

https://cap.dotnetcore.xyz/user-guide/zh/transport/general/#_4
