### ISSUE TITLE
Is there a valid reason or performance concern for using Descending index for MongoDB?

### ISSUE THREAD

**Issue by ustaserdar** [dotnetcore/CAP#1415]
Hello,

When I examined the IStorageInitializer.MongoDB.cs class, I noticed that a descending index was defined specifically for the fields for published and received collections in line 114. The DBOps team of the company I work for looked into the issue. He asked that these indexes cause performance loss and why they were not designed as ascending. Since it is a built-in definition, we cannot customize it. As I mentioned in the question, is there a special reason for the definition to be made this way? Does manipulating as ascending via DB cause problems?

**Reference:** https://github.com/dotnetcore/CAP/blob/9fe46e6b8238a8dc3d62844d6378ff67ce35517e/src/DotNetCore.CAP.MongoDB/IStorageInitializer.MongoDB.cs#L35

**Comment by yang-xiaodong** [comment]
Hi

The index is introduced from https://github.com/dotnetcore/CAP/pull/353. I think there is no special reason to use descending and it can be changed to ascending. 

Would you want to submit a PR?

**Comment by yang-xiaodong** [comment]
Fixed in 7.2.2
