### ISSUE TITLE
Feature Request: Possibility to consume and produce to multiple Message Queues

### ISSUE THREAD

**Issue by HeinrichvH** [dotnetcore/CAP#1417]
Hello Guys,

me and my team would need the following feature.

![image](https://github.com/dotnetcore/CAP/assets/65982226/016b9748-746e-4bab-b206-9323e57bf4c8)

Our suggestion would be:

1. Extend Attribute with Marker that indicates for which server the consumer / producer is made for
2. Extend Options to support Marker, for example unique naming
3. Update Registration Process
4. Evaluate Database - must be differentiatable between handlers

Thank you for your great Library 👍 

Greetings
Heinrich

**Comment by yang-xiaodong** [comment]
Hello, 

We have no plans for this feature. Your request has many places that need to be adjusted and is also very complex. We hope to keep this library simple and lightweight. 

Thanks for your feedback.
