### ISSUE TITLE
I encountered a duplicate consumption bug  👉 Subscribers consume multiple times

### ISSUE THREAD

**Issue by NingLiu1998** [dotnetcore/CAP#1419]
![消费面板2次](https://github.com/dotnetcore/CAP/assets/109678937/0802bb2d-ddf5-4113-947f-fc257bd46ae7)

The panel shows consumption twice

![第一次](https://github.com/dotnetcore/CAP/assets/109678937/9d63f8ea-8435-4070-9dd1-1b246d2b6bca)

![第二次](https://github.com/dotnetcore/CAP/assets/109678937/d8955858-12cb-4a56-8c13-b27f57340590)

Their ” cap-msg-id“  is consistent （这个属性都是一致的）

## And it was only published once 👇

![image](https://github.com/dotnetcore/CAP/assets/109678937/5ecbf6a5-ae7d-4c19-8c31-893961e606d7)

## This is my MQ configuration 👇

![image](https://github.com/dotnetcore/CAP/assets/109678937/a3bcb643-d531-4459-9620-54df0d77ba8f)

## This is my CAP configuration  👇

![image](https://github.com/dotnetcore/CAP/assets/109678937/ecfc4ba1-25c4-4164-92b6-908570728d52)

**It should be noted that this kind of repeated consumption only happens occasionally and does not happen most of the time.**

**Comment by NingLiu1998** [comment]
DotNet Version is  **dotNet6**
DotNetCore.CAP Version is **7.2.1**

**Comment by yang-xiaodong** [comment]
推测是由于发送测的重试导致了重复发送，证据是根据你的 “it was only published once” 图显示，添加时间是 `2023-10-31 19:14:58` 但过期时间是 `2023-11-01 19:19:xx` 中间间隔了超过1天4分钟的时间，正常过期时间是消息被设置为成功时刻的当前时间+SucceedMessageExpiredAfter 配置项，也就是说你的发布侧从存储消息到发送成功之间的间隔超过了4分钟，从而可以推断你的代码应该使用了事务，你的业务代码在事务提交之前执行了非常长的时间，这非常不合理。
