### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by kexxxfeng** [dotnetcore/CAP#143]
Please answer these questions before submitting your issue.
- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [x] Feature or performance improvement

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

MongoDB has been ready to supported [`ACID`](https://www.mongodb.com/blog/post/multi-document-transactions-in-mongodb), then I want to know if CAP has any plan to support it?

**Comment by yuleyule66** [comment]
We have no plan to supportt MongoDb, If possible, this should be a community supported repository, would you like to implement it and keeping the open source ?

**Comment by kexxxfeng** [comment]
I'll try it.

**Comment by yuleyule66** [comment]
Hi @kexxxfeng , thanks for your PR, I have been release a preview version of  `2.2.6-preview-49112414` to nuget , you can try it.
After sufficient testing, we will release the official version 2.3, which will include mongdb support.
