### ISSUE TITLE
Open telemetry subscriber thows null reference when using azure service bus without connection string

### ISSUE THREAD

**Issue by demorgi** [dotnetcore/CAP#1432]
Open telemetry diagnostic listener fails when Azure service bus is used without a connection string.
Azure service bus supports automatic connections when using managed identities, so you don't have to specify connection string. Diagnostic listener has this code that throws a null reference as `BrokerAddress.Endpoint` is null.
https://github.com/dotnetcore/CAP/blob/7ba52a8defa73f3866001dea6dd6af434574c3d2/src/DotNetCore.CAP.OpenTelemetry/DiagnosticListener.cs#L108C1-L109C1

Workaround #1
Explicitly set the connection string for Azure service bus to string empty when registering CAP

**Comment by yang-xiaodong** [comment]
Hi @demorgi ,

Thanks for your report, you're right , would you want to submit a PR to fix it?

**Comment by yang-xiaodong** [comment]
Fixed in version 8.0.0
