### ISSUE TITLE
Outbox pattern does not work when using DotNetCore.CAP.InMemoryStorage

### ISSUE THREAD

**Issue by davidterins** [dotnetcore/CAP#1439]
1. Create a subscriber and a publisher using DotNetCore.CAP.NATS and DotNetCore.CAP.InMemoryStorage where the publisher sends messages with an interval
2. Run the application and the nats-server
3. Shutdown nats-server
4. Keep the server shut down while some messages are being sent by the publisher.
5. Start nats-server

Expected behavior here is that the messages sent by the publisher during shutdown of the server should be received by the consumer when nats-server i started again, but they will get stuck in the publishers outbox due to exceptions since the Origin property is not set on the stored messages when retrieved from the outbox.

**Comment by davte-beijer** [comment]
Thank you, when can I expect this to be released @yang-xiaodong?

**Comment by yang-xiaodong** [comment]
Hi @davte-beijer ,

Fixed in version `7.2.3-preview-217562936`

**Comment by yang-xiaodong** [comment]
Fixed in version 8.0.0
