### ISSUE TITLE
[Question] How do I publish using partition key

### ISSUE THREAD

**Issue by ferdikosasih** [dotnetcore/CAP#1443]
Hi all, 

I'm using CAP 7.2.2 
Kafka
.NET 6
Working on my local notebook 

I'm testing publish using partition eg : 
I pass the value from cap header
`
public ActionResult<string> SubmitOrder(OrderRequest request)
{

    dbContext.Database.CanConnect();
    var headers = new Dictionary<string, string?>()
    {
        {"cap-partition-key",request.OrderId }
    };
    _publisher.Publish<OrderRequest>("OrderRequest", request,headers);
    return "Success";
}
`

However when I check my kafka, all my message goes to default partition. Partition 0
Here is my cap message : 

```

{
"Headers": 
{
"cap-partition-key": 
"3",
"cap-msg-id": 
"4505288858769231877",
"cap-corr-id": 
"4505288858769231877",
"cap-corr-seq": 
"0",
"cap-msg-name": 
"OrderRequest",
"cap-msg-type": 
"OrderRequest",
"cap-senttime": 
"11/29/2023 3:09:16 PM"
},
"Value": 
{
"OrderId": 
"3",
"Quantity": 
10,
"Item": 
"chatime milk tea"
}
}

```
Thank you for helping me

**Comment by yang-xiaodong** [comment]
We only support `cap-kafka-key`, 

Where did you see this configuration `cap-partition-key`?

**Comment by ferdikosasih** [comment]
Hi @yang-xiaodong 
my bad, I looked in the document https://cap.dotnetcore.xyz/user-guide/en/transport/kafka/#customheaders-options but can't figure it out the right key

Thanks, it works now

**Comment by yang-xiaodong** [comment]
@ferdikosasih 

Would you like to submit a PR to improve the docs of `cap-kafka-key` ?

Thanks

**Comment by ferdikosasih** [comment]
sure! will update soon
