### ISSUE TITLE
Rabbitmq client support multiple connections

### ISSUE THREAD

**Issue by yun6cc** [dotnetcore/CAP#1446]
如题：使用rabbitmq时，client能否支持多个connection?
现在一个服务一个connection 阿里那边会出现连接不均衡的问题。如果能多个的话，可以极大改善这个情况的出现。

**Comment by yang-xiaodong** [comment]
See 

https://www.rabbitmq.com/connections.html
and
https://www.alibabacloud.com/help/en/message-queue-for-rabbitmq/latest/connection-and-channel

> **Usage suggestions**
> Pay attention to the following suggestions on the usage of connections and channels:

> Use persistent connections. Do not frequently open or close a connection. You can frequently open or close a channel. For more information about the limits on the interfaces that are used to open connections and channels on a single instance, see [Limits](https://www.alibabacloud.com/help/en/message-queue-for-rabbitmq/latest/limits#concept-101627-zh).
Each process corresponds to a connection, and the threads of a process have a one-to-one mapping onto the channels of a connection.
> Producers and consumers use different connections to send and consume messages.
