### ISSUE TITLE
Understanding NATS and CAP permissions

### ISSUE THREAD

**Issue by smedjes** [dotnetcore/CAP#1448]
I'm building a solution where I have multiple services on a device that uses NATS for internal communication.
NATS uses the following configuration file:
```json
  {
	"server_name": "MessageBroker",
	"logtime": false,
	"logfile_size_limit": 500000000,
	"log_file": "C:/Services/MessageBroker/log.log",
	"jetstream": {
		"store_dir": "C:/Services/MessageBroker/Data",
		"max_mem": "100M",
		"max_file": "100M"
	},
	"tls": {
		"cert_file": "C:/Services/MessageBroker/Certificates/server-cert.pem",
		"key_file": "C:/Services/MessageBroker/Certificates/server-key.pem"
	},
	"accounts": {
		"MySolution": {
			"jetstream": "enabled",
			"users": [
				{
                                        // Receiver service
					"nkey": "UDZRKHMDAC4YZI6UR55AP3GARLYSTN5A3NIVESNF5PDCABUKPKXG5RRK",
					"permissions": {
						"subscribe": [
							"_INBOX.>",
							"sample.topic"
						],
						"publish": [
							"$JS.API.STREAM.INFO.VolatileStream",
							"$JS.API.STREAM.CREATE.VolatileStream",
							"$JS.API.STREAM.UPDATE.VolatileStream",
							"$JS.API.CONSUMER.INFO.VolatileStream.*",
							"$JS.ACK.VolatileStream.>",
							"$JS.API.CONSUMER.CREATE.VolatileStream.*.sample.topic"
						]
					}
				},
				{
                                        // Publisher service
					"nkey": "UDUCM4DR3UUDOQ64QB2OKSL3GGGXCGUV4HYEK65WD64Y7Q3TSL3LNOLZ",
					"permissions": {
						"subscribe": [
							"_INBOX.>"
						],
						"publish": [
							"sample.topic"
						]
					}
				}
			]
		}
	}
}
```

The services are written in C# and I'm using CAP as an abstraction layer.

I'm basically trying to publish `sample.topic` from one service  to another.
I have created a stream called `VolatileStream` that contains the `sample.topic` subject.

I have it working, but I'm a bit confused by how to set up the permissions, mainly for the receiver service.
I have added the `$JS.*`-permissions after getting errors when trying to start the service, for example:
```
[1] [ERR] 172.17.0.1:33000 - cid:6 - Publish Violation - Nkey "UDZRKHMDAC4YZI6UR55AP3GARLYSTN5A3NIVESNF5PDCABUKPKXG5RRK", Subject "$JS.API.STREAM.CREATE.VolatileStream"
[1] [ERR] 172.17.0.1:33010 - cid:7 - Publish Violation - Nkey "UDZRKHMDAC4YZI6UR55AP3GARLYSTN5A3NIVESNF5PDCABUKPKXG5RRK", Subject "$JS.API.CONSUMER.INFO.VolatileStream.cap_queue_receiver_v1-sample_topic"
[1] [ERR] 172.17.0.1:40152 - cid:6 - Publish Violation - Nkey "UDZRKHMDAC4YZI6UR55AP3GARLYSTN5A3NIVESNF5PDCABUKPKXG5RRK", Subject "$JS.API.STREAM.CREATE.VolatileStream"
```

It looks like the `$JS.*`-publish-permissions are needed because CAP will access and modify streams.

But the subscribe-permissions `sample.topic` requires `$JS.API.CONSUMER.CREATE.VolatileStream.*.sample.topic` publish-permission which in turn seems to override the `sample.topic` subscribe-permission. 
So I can basically remove `sample.topic` from subscribe-permissions but keep `$JS.API.CONSUMER.CREATE.VolatileStream.*.sample.topic` in publish-permissions and I will still be able to subscribe to and receive the message.

The expected result here would be that I should not be able to subscribe to a topic that is not defined in the subscribe-permissions.

I guess I'm wondering if I'm I doing something wrong here or is this how it is supposed to be configured?

**Comment by yang-xiaodong** [comment]
Hi @smedjes ,

I am not familiar with NATS permissions, but I can provide the following information: CAP lookup all registered consumers when it starts up, and then creates or updates a stream in NATS based on the name of the subscription. The subject name is the name of all consumers (the name comes from the assembly name or configuration). I think it would be helpful to review the subscription code.

https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.NATS/NATSConsumerClient.cs

**Comment by yang-xiaodong** [comment]
Set as backlog and consider this issue sometime in the future.
