### ISSUE TITLE
Configure Kafka for outbox in runtime

### ISSUE THREAD

**Issue by mnovikov-mindbox** [dotnetcore/CAP#1451]
Hi! We have environment with several independent Kafka servers. In some cases we need to send message using outbox pattern to kafka-1, in other to kafka-2.

Is there a way to do it with CAP? As I can see now I can configure only one server using:
```c#
builder.Services.AddCap(x =>
{
   ...
    x.UseKafka(c =>
    {
        c.Servers = "kafka-a-1-v1:9092,kafka-b-1-v1:9092";
    });
});
```
And I want something like
```c#
builder.Services.AddCap(x =>
{
   ...
    x.UseKafka(c =>
    {
        c.ServersProvider = (topic, context) => ...;
    });
});
```

**Comment by mnovikov-mindbox** [comment]
@yang-xiaodong thanks for answering! 
I don't see stop and start as a solution, because I can have several parallel requests part of with need to be publish to kafka-1 and other part to kafka-2 and `IBootstrapper` is Singletone.

>We don't support connecting multiple non-clustered Kafka Brokers

Do you have any plans to support it? Or it's totaly against CAP logic?

**Comment by yang-xiaodong** [comment]
No plan to support, you can create  a proxy or bridge project at front for your case.
