### ISSUE TITLE
How to make the global tran implement?

### ISSUE THREAD

**Issue by Austin-codeviewr** [dotnetcore/CAP#1458]
Just some question in I actual operate,
I found that when the publisher business processing and message had successful submit, but the consumer consume the message faid,and it had over the retry count, the publisher database not rollback, so cap has this function like seata having global tran?
Thanks alot if u can reply my question.

**Comment by xiangxiren** [comment]
The success or failure of message consumption will not affect the submitter's transactions.

**Comment by yang-xiaodong** [comment]
@Austin-codeviewr  see: https://www.cnblogs.com/savorboard/p/distributed-system-transaction-consistency.html
