### ISSUE TITLE
how to user AppPath

### ISSUE THREAD

**Issue by wdqzdd** [dotnetcore/CAP#1463]
![image](https://github.com/dotnetcore/CAP/assets/27991992/3cb5f23f-c731-4edd-90ea-0992b0e004de)

**Comment by wdqzdd** [comment]
做了代理。原始地址PathMatch为/capdashboard。
代理转为/erp/capdashboard。
![image](https://github.com/dotnetcore/CAP/assets/27991992/b144ec50-9458-4ef1-891d-c0f84acbac3e)

**Comment by yang-xiaodong** [comment]
Version 3.1.2 is not supported now.
