### ISSUE TITLE
Can the CAP data persistence database and business database be of different types

### ISSUE THREAD

**Issue by List8378** [dotnetcore/CAP#1465]
Can the CAP data persistence database and business database be of different types?
For example:

Using SqlServer for CAP data persistence dababase

Business dababase using MySql

But I must use database transactions to ensure strong consistency between messages and business

Because I am using multiple tenants, there will be different types of databases

If I don't use a database for CAP persistence and use NoSql (ex: MongoDB), but also use different databases type for multi tenancy, can I still ensure strong consistency between messages and business

**Comment by yang-xiaodong** [comment]
> Can the CAP data persistence database and business database be of different types?
No, See [transactional outbox pattern](https://microservices.io/patterns/data/transactional-outbox.html)

> If I don't use a database for CAP persistence and use NoSql (ex: MongoDB), but also use different databases type for multi tenancy, can I still ensure strong consistency between messages and business

Not support database isolated multi-tenancy. See #699

**Comment by List8378** [comment]
> > Can the CAP data persistence database and business database be of different types?
> 
> No, See [transactional outbox pattern](https://microservices.io/patterns/data/transactional-outbox.html)
> 
> > If I don't use a database for CAP persistence and use NoSql (ex: MongoDB), but also use different databases type for multi tenancy, can I still ensure strong consistency between messages and business
> 
> Not support database isolated multi-tenancy. See #699

Okay, thank you, I'll try another way
