### ISSUE TITLE
FailedCallback 提问

### ISSUE THREAD

**Issue by xsharkx** [dotnetcore/CAP#147]
DotNetCore.CAP 2.1.4
使用了之后有一些疑问想请赐教。
1.请问使用cap什么情况下会调用此回调？试了各种情况都不会出现。
2.订阅方抛出异常，发布方如何知道？

**Comment by yuleyule66** [comment]
>1.请问使用cap什么情况下会调用此回调？

当发送失败或接收执行失败重试50次时触发此回调

>2.订阅方抛出异常，发布方如何知道？

订阅方抛出异常，会进行重试，发送方不会知道，消息是fire-and-forgot模式

**Comment by xsharkx** [comment]
谢谢
