### ISSUE TITLE
Authentication challenges with k8s discovery.

### ISSUE THREAD

**Issue by 3ldar** [dotnetcore/CAP#1471]
Hi, I am trying to utilize CAP Dashboard JWT auth within a k8s environment and want to use ks8 node discovery and manage the other services from the single dashboard. I have managed to make them work separately but not combined. The first challenge was: 
 - I was utilizing JWT auth over the cookies, and had a tiny middleware that converts the cookie into bearer token. Since the default `IRequestMapper` service ignores the `cookie` headers it fails to authenticate the foreign service because it lacks the cookie header (It is reasonable, that it might be ignored due to security reasons). This was easy to handle: I made a custom `IRequestMapper` that handles the auth header.
 - The second challenge is where the services nodes are listed if you want to make a switch to a service it pings the service and then sets the cookie so far so good. Despite all the other methods uses the `GatewayProxyAgent` `Ping` method uses directly `HttpClient` and doesn't pass any headers to the client so if your endpoint is authorized the ping will fail and you won't switch when the ping fails. There is a workaround for that too: you can manually set the cookie named `cap.node` to your desired service and it will start to work but not a great user experience 😄 

Here is the related [line](https://github.com/dotnetcore/CAP/blob/186910f4882be8303b7a32f5de38e6fc3148cdfb/src/DotNetCore.CAP.Dashboard/RouteActionProvider.cs#L377) in the code.

If I can find a gap in my timeline I would like to submit a PR for this. Also, a little guidance would be nice on whether to use or not to use `GatewayProxyAgent` in the `Ping` method.

**Comment by yang-xiaodong** [comment]
Hi,

The `/api/health` interface should be anonymous by default, it is not controlled by the `AllowAnonymousExplicit` option, would you like to submit a PR?
