### ISSUE TITLE
消息消费失败后重试的异常

### ISSUE THREAD

**Issue by TrashTillDie** [dotnetcore/CAP#1473]
hi ，目前在使用中。我发现配置的FailedRetryInterval失败重试的延迟时间不生效。
当失败后会立即发送3次重试
![image](https://github.com/dotnetcore/CAP/assets/108500733/2eac0bd6-9ba5-4037-a7ad-0d4ece83ccbf)

**Comment by yang-xiaodong** [comment]
This is by design, see https://cap.dotnetcore.xyz/user-guide/zh/cap/configuration/#failedretryinterval

**Comment by TrashTillDie** [comment]
这里的立即重试3次是否也可以进行配置呢。
目前我们的业务场景涉及到积分，金额的操作。接口会有一定的风控拦截。
这里的重试次数会导致的接口返回操作频繁

**Comment by yang-xiaodong** [comment]
> 这里的立即重试3次是否也可以进行配置呢

Not support, you shoule schedule the task in somewhere with the retry policy in your subscriber
