### ISSUE TITLE
希望通过环境变量限制消费端执行

### ISSUE THREAD

**Issue by longjie12315** [dotnetcore/CAP#1474]
我有一个需求，同一套代码部署到多台服务器。我希望通过环境变量控制不同服务器进行不同的事件消费。
例：
我的系统中现在有三个消息发送和三个消费，分别是 A、B、C。
我想在第1台服务器 消费A ，第2台服务消费B，第3台服务消费C。
代码都是同一个系统。

有现成的解决方案吗？如果有请告知实现方式。
如果没有，会有开发计划吗？

**Comment by yang-xiaodong** [comment]
You can use group to fonout the message and use filter to ignore by the env.
