### ISSUE TITLE
Set EnableConsumerPrefetch option to true and the  application crashed

### ISSUE THREAD

**Issue by 2009011133** [dotnetcore/CAP#1479]
升级CAP8.0 设置EnableConsumerPrefetch=true ,高并发的情况下会导致.net网站崩掉，有什么解决方案吗？使用kestrel作为服务器。
![20240129153640991](https://github.com/dotnetcore/CAP/assets/105468958/3a6b99e1-0912-488a-a1eb-1e2f4e0282af)

![20240129153726455](https://github.com/dotnetcore/CAP/assets/105468958/9d0db59b-71a3-48c2-834a-df4bce3a4b48)

**Comment by yang-xiaodong** [comment]
把你的Subscriber代码放到MVC的Action中，然后benckmark测试是否会出现相同错误？

**Comment by 2009011133** [comment]
目前使用的是动态api
![20240130135920401](https://github.com/dotnetcore/CAP/assets/105468958/3af8a0ff-e958-425d-8763-38c76960df74)

**Comment by yang-xiaodong** [comment]
把在不使用CAP的情况下benckmark测试你的Subscriber代码是否会出现相同错误？

**Comment by yang-xiaodong** [comment]
No response, closed!
