### ISSUE TITLE
Unavailability of flexible group (queue) names

### ISSUE THREAD

**Issue by DuleDimitrov123** [dotnetcore/CAP#1482]
Hi, I am trying to create some flexible queue names in RabbitMQ since I am using it with CAP library. I would like to have queue name like: "test".

As I can see, CAP is creating queue name with the Group from [CapSubscribe] attribute and adds version.

If I set [CapSubscribe("someEvent", Group = "test")], I will get queue: test.v1.

Additionaly, if I set version to string.Empty with the following code when registering CAP, I will get: "test." (with "." after test).

```
  services.AddCap(options =>
  {
      options.Version = string.Empty;

      options.UseEntityFramework<DbContext>();

      options.UseRabbitMQ(options =>
      {
          ...
      });
  });
```

Could I somehow set queue name in RabbitMQ to "test" and use it like that?

Thanks!

**Comment by yang-xiaodong** [comment]
Hi, You can override this method 

https://github.com/dotnetcore/CAP/blob/e3cffd1e668aff48715a9c34ce147dbf213c3880/src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs#L169

**Comment by DuleDimitrov123** [comment]
Thanks @yang-xiaodong. Closing the issue!
