### ISSUE TITLE
Question about retrieving message info in filter or consumer

### ISSUE THREAD

**Issue by PoteRii** [dotnetcore/CAP#1484]
Hello,
Is there any way to get `MediumMessage.DbId` and `MediumMessage.Retries` in filter (from `ExecutingContext`) or consumer?
I can see that in `ExecuteAsync` method there is a line
`message.Origin.Headers[Headers.ExecutionInstanceId] = _hostName;` and you can get instance info from headers later in filter or consumer.
Can something similar be done to get `DbId` or `Retries`?

**Comment by PoteRii** [comment]
looks like it`s covered by https://github.com/dotnetcore/CAP/pull/1464

**Comment by yang-xiaodong** [comment]
Hi,

PR #1464 has been merged and will be release in v8.1.0
