### ISSUE TITLE
Small issue with SQL Server infrastructure initialization having UseStorageLock = true

### ISSUE THREAD

**Issue by alex-dolzhok** [dotnetcore/CAP#1486]
Hi guys.
There is a small issue in services configuration if we set UseStorageLock = true.
During tables initialization I'm having errors:
_Violation of PRIMARY KEY constraint 'PK_cap.Lock'. Cannot insert duplicate key in object 'cap.Lock'. The duplicate key value is (publish_retry_v1)_
_Violation of PRIMARY KEY constraint 'PK_cap.Lock'. Cannot insert duplicate key in object 'cap.Lock'. The duplicate key value is (received_retry_v1)_

As a solution I propose to add a check for Lock records existence here:
src/DotNetCore.CAP.SqlServer/IStorageInitializer.SqlServer.cs

IF NOT EXISTS(SELECT 1 FROM {GetLockTableName()} WHERE [Key] = @PubKey)
    INSERT INTO {GetLockTableName()} ([Key],[Instance],[LastLockTime]) VALUES(@PubKey,'',@LastLockTime);
IF NOT EXISTS(SELECT 1 FROM {GetLockTableName()} WHERE [Key] = @RecKey)
    INSERT INTO {GetLockTableName()} ([Key],[Instance],[LastLockTime]) VALUES(@RecKey,'',@LastLockTime);

**Comment by yang-xiaodong** [comment]
Why ** IGNORE_DUP_KEY = ON ** not working?

**Comment by alex-dolzhok** [comment]
Sorry, my bad: I was creating Lock table myself, didn't pay attention on IGNORE_DUP_KEY = ON parameter in create table instruction.
Thanks!
