### ISSUE TITLE
是否考虑让CAP的持久化的时候,可配置orm框架

### ISSUE THREAD

**Issue by 0xblack** [dotnetcore/CAP#1489]
如题:CAP的持久存储部分使用的是.net core的ef,有些项目可能各种原因,使用了其他的orm产品,作为维护栈考虑,在接入CAP的时候是否考虑可以使用其他orm配置接管对应的操作,谢谢.

**Comment by yang-xiaodong** [comment]
没看懂，你指的使用其他持久化什么东西？

**Comment by 0xblack** [comment]
不好意思,我描述有误,我是在使用DotNetCore.CAP.MySq这个库进行持久化配置的时候,它是依赖efcore的,我是想说,这个部分是否可以在orm这一层进行抽象,让它可以轻松的切换到其他的orm框架呢?

**Comment by yang-xiaodong** [comment]
为什么要切换？
