### ISSUE TITLE
Question about multiple consumers in an assembly

### ISSUE THREAD

**Issue by xsharkx** [dotnetcore/CAP#149]
我在一个程序集里面订阅了同一个主题多次，好像只有第一个订阅有效。最初的设计是这样的吗？如果是这样，我有个困扰，一个程序集里面如果只能订阅一次，那么是否可以启动检测到两个时输出错误或警告，甚至抛出异常。
因为如果无感的，很容易弄错。

**Comment by yuleyule66** [comment]
同一个程序集默认属于相同的Group，在接收到消息的时候一个Group的只会被消费一次。你可以使用 `[CapSubscribe("",Group="xx“)] ` 这种这种显式指定不同Group方式来触发广播模式。

>检测到两个时输出错误或警告，甚至抛出异常。 

这个只有编译器才能做到

**Comment by xsharkx** [comment]
我说的是  一个程序集的两个controller  都订阅了[CapSubscribe("CreateOrder")]

**Comment by xsharkx** [comment]
有时候一个程序集可能比较大，以前订阅过，后来又加了一个

**Comment by yuleyule66** [comment]
比如第一次是 `[CapSubscribe("CreateOrder")]`, 后来又加了一个就可以是 `[CapSubscribe("CreateOrder",Group="GroupTwo")]`

**Comment by xsharkx** [comment]
明白了，谢谢
