### ISSUE TITLE
Integration Testing Approch

### ISSUE THREAD

**Issue by dandcg** [dotnetcore/CAP#1491]
When calling Publish in an integration test harness, the code will finish before the subscriber has received and processed the message. If I add a slight delay at the end, then it does. 

In light of this, I'm Looking for options or guidance on the possibility of following approaches for firming up integration tests through CAP.

1. In Memory Transport - is there a way of making this synchronous so that each subscriber is run in series?
2. Awaiting completion of subscribers - are there any events I can use to hook into the completion of the subscriber executor? A way of asserting that the subscription has run without modifying the subscriber's behaviour?

I hope this makes sense.

Cheers,

Dan

**Comment by dandcg** [comment]
I may have solved this already - unless there is a best way :)

I've created a custom filter that counts messages completed, which I can check completion against.

**Comment by yang-xiaodong** [comment]
> In Memory Transport - is there a way of making this synchronous so that each subscriber is run in series?

Yes, you can use [Savorboard.CAP.InMemoryMessageQueue](https://github.com/yang-xiaodong/Savorboard.CAP.InMemoryMessageQueue) , the subscriber is in series run.

**Comment by dandcg** [comment]
Hi, yes, I am using that - but the tasks are run asynchronously. I have a reasonably neat solution now using ISubscribeFilter registered as a singleton and channels to await the arriving executed context.

**Comment by yang-xiaodong** [comment]
Sorry, messages are sent to the memory queue first and then pushed to the Broker.
