### ISSUE TITLE
Why my message parameters is auto convert to base64

### ISSUE THREAD

**Issue by DayDreamdd** [dotnetcore/CAP#1495]
when i publish a message ,the parameters is a entity, the consumer will get a base64 parameter.so i convert the entity to json,then publish the json, the consumer recived message parameter also is base64. i do not know why.

![1709609473833](https://github.com/dotnetcore/CAP/assets/113971057/d41175d8-d0e8-413b-ae3a-3e181781ff0e)
![1709609521781](https://github.com/dotnetcore/CAP/assets/113971057/276cc76e-0273-4301-8a4f-87825bc8da83)

**Comment by yang-xiaodong** [comment]
See: https://github.com/dotnetcore/CAP/issues/63#issuecomment-841659904

**Comment by DayDreamdd** [comment]
resolved ,  thanks

**Comment by tuohaibei** [comment]
Hi,how you fix it?could you show more detail?
