### ISSUE TITLE
How to config connection RabbitMQ cluster

### ISSUE THREAD

**Issue by hao15239129517** [dotnetcore/CAP#1499]
如何连接同一个ip不同端口的集群(192.168.13.100:5672,192.168.13.100:5673,192.168.13.100:5674)这种，并且需要自定义账号密码、vhost

**Comment by yang-xiaodong** [comment]
CAP support rabbitmq client native conntionfactory, you can use it to config.

**Comment by hao15239129517** [comment]
Can you give an example? I didn't find how to use it

**Comment by yang-xiaodong** [comment]
> Can you give an example? I didn't find how to use it

How do you config use RabbitMQ.Client?
