### ISSUE TITLE
关于失败后重新消费的问题

### ISSUE THREAD

**Issue by xsharkx** [dotnetcore/CAP#150]
实验环境
A=订单，B=支付，C=库存
流程1是A下单时B创建支付单，C检查库存
流程2是A被支付了A确认订单，B设置状态支付完成，C扣库存

我在B支付完成时加了10%的概率抛出异常
用Jmeter模拟200个请求过来

结果
![image](https://user-images.githubusercontent.com/1161677/42193407-e368a050-7ea0-11e8-92ed-3190c4aab14e.png)

有一个失败

然后再操作了重新消费了那个失败的消息
但看板里面的消息数貌似不太对，没有把重新消费的消息数补上去
![image](https://user-images.githubusercontent.com/1161677/42193512-629ffcec-7ea1-11e8-8754-e82a36ab33f5.png)

还有发现在这里重新消费时是不会回调给A的”CreateOK“，请问是设计如此还是bug。
![image](https://user-images.githubusercontent.com/1161677/42193533-83cf866c-7ea1-11e8-9429-c25649932a10.png)

**Comment by yuleyule66** [comment]
符合预期，这个是消息接收的数量，并不是执行的次数。

**Comment by xsharkx** [comment]
进一步实验知道原因了，重新消费时没有重置消息的重试次数，导致不会被重新执行。我手动更改数据库的重试次数就会被重复执行然后就正常了。我可以贡献点代码。等会提交给你看看。

**Comment by xsharkx** [comment]
#152 已提交

**Comment by yuleyule66** [comment]
#158 Fixed the message re-queue or re-executed operate not works as expected bug.

**Comment by yuleyule66** [comment]
Fixed in v2.2.5
