### ISSUE TITLE
Configurable NATS acknowledge wait time

### ISSUE THREAD

**Issue by valdasss** [dotnetcore/CAP#1500]
Hi there,

I've been using this package with NATS and have observed that messages are consumed multiple times when the consumption time exceeds 10 seconds. Upon inspecting the NATS client configuration in the CAP library, I noticed that the "acknowledge wait" is hardcoded to 10,000 milliseconds [link to code](https://github.com/dotnetcore/CAP/blob/f0646a3f1067939d4ddcd221e1c0e773be2da781/src/DotNetCore.CAP.NATS/NATSConsumerClient.cs#L105C34-L105C45).

I'm curious if there's a specific reason for this value. Additionally, would it be possible to make this value configurable? In the case of long-running operations, having the ability to adjust this setting could prevent messages from being rehandled multiple times.

Thanks

**Comment by yang-xiaodong** [comment]
Fixed in version 8.1.0
