### ISSUE TITLE
Does CAP support dynamic subscriber?

### ISSUE THREAD

**Issue by lvcao99** [dotnetcore/CAP#1501]
CapSubscribe的Name属性是否支持动态赋值？
目前是Attribute只能给固定值，是否支持动态赋值？

**Comment by yang-xiaodong** [comment]
HI,

Simply put, we do not support that.

I don't know your use case, but dynamic subscribers mean you might also need to dynamically consumer handlers. Perhaps issue #1326 might help you, but that's beyond our scope of support.

We do support dynamic stopping and starting, so maybe you can do something when registering the subscriber context.
