### ISSUE TITLE
Add Cosmos DB as storage

### ISSUE THREAD

**Issue by NikiforovAll** [dotnetcore/CAP#1503]
Hi, 

I would like to use Cosmo DB as outbox storage. 

How do I contribute? Do you want me tor create separate package?

**Comment by yang-xiaodong** [comment]
Hi,

Thanks, But we're use the AWS and I don't have an Azure subscription, so if anything goes error I can't fix it or improve it, so I thought being a community extension would be a better option and we can put your repository into our docs.
