### ISSUE TITLE
An item with the same key has already been added. Key: traceparent

### ISSUE THREAD

**Issue by ferdikosasih172147** [dotnetcore/CAP#1504]
Hi, 

I'm using ver 8.0.0 in my local I got subscription error. 
```
<ItemGroup>
  <PackageReference Include="DotNetCore.CAP" Version="8.0.0" />
  <PackageReference Include="DotNetCore.CAP.Dashboard" Version="8.0.0" />
  <PackageReference Include="DotNetCore.CAP.Kafka" Version="8.0.0" />
  <PackageReference Include="DotNetCore.CAP.PostgreSql" Version="8.0.0" />
</ItemGroup>
```

`[10:38:18 ERR] An item with the same key has already been added. Key: traceparent
System.ArgumentException: An item with the same key has already been added. Key: traceparent
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at DotNetCore.CAP.Kafka.KafkaConsumerClient.Listening(TimeSpan timeout, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass21_1.<Execute>b__2()`

Would you suggest which are I need to check

**Comment by yang-xiaodong** [comment]
Please show how to reproduce?

**Comment by ferdikosasih172147** [comment]
configuration : 
`services.AddJutsuCap(options =>
{
    var name = Assembly.GetEntryAssembly()?.GetName().Name;
    if (name == null)
    {
        throw new InvalidOperationException(nameof(name));
    }
    options.DefaultGroupName = name;
    options.UseEntityFramework<TDbContext>();
    options.UseKafka(opt => JutsuKafkaOptions(opt,kafkaServer));
    options.ConsumerThreadCount = 50;
    options.UseDashboard();
})`

`opt.Servers = bootstrapServer;
opt.TopicOptions = new KafkaTopicOptions()
{
    NumPartitions = 3
};
opt.CustomHeadersBuilder = (message, serviceProvider) =>
{
    var snowFlakeId = serviceProvider.GetRequiredService<ISnowflakeId>();
    return new List<KeyValuePair<string, string>>()
    {
        //generate OperationId for each message
        new(DotNetCore.CAP.Messages.Headers.MessageId,snowFlakeId.NextId().ToString()),
        //align message name with topic 
        new(DotNetCore.CAP.Messages.Headers.MessageName, message.Topic),
        //passing message key as kafka key in the CAP custom header
        new("cap-kafka-key",message.Message.Key.ToString())
    };
};
return opt;`

`_capHeaders.Add(new KeyValuePair<string, string?>(CapHeader.KafkaKey,key));
_capHeaders.Add(new KeyValuePair<string, string?>(CapHeader.TraceIdentifier, _httpContext.HttpContext?.TraceIdentifier));

return _capPublisher.PublishAsync<T>(
    name: topicName,
    contentObj: message,
    headers: _capHeaders);`
    
    
 `builder.Services.AddScoped<ICapSubscribe, PostSubscriber>();`
 
 
 when I starting my app, subscribe was not working due to this error

**Comment by ferdikosasih172147** [comment]
Sample Json Message
```
[
    {
        "partitionID": 0,
        "offset": 0,
        "timestamp": 1711509492477,
        "compression": "uncompressed",
        "isTransactional": false,
        "headers": [
            {
                "key": "traceparent",
                "value": {
                    "payload": "00-ccf419185ac325d0a86c874ff54166bc-76b566d1c141f679-01",
                    "encoding": "text",
                    "schemaId": 0
                }
            },
            {
                "key": "cap-kafka-key",
                "value": {
                    "payload": "1e77b71f-2516-4a58-8fcb-e7f1c20ecbdf",
                    "encoding": "text",
                    "schemaId": 0
                }
            },
            {
                "key": "cap-corr-seq",
                "value": {
                    "payload": "0",
                    "encoding": "text",
                    "schemaId": 0
                }
            },
            {
                "key": "cap-corr-id",
                "value": {
                    "payload": "4505330901987684353",
                    "encoding": "text",
                    "schemaId": 0
                }
            },
            {
                "key": "cap-msg-name",
                "value": {
                    "payload": "demoapi-posts",
                    "encoding": "text",
                    "schemaId": 0
                }
            },
            {
                "key": "cap-msg-type",
                "value": {
                    "payload": "PostContract",
                    "encoding": "text",
                    "schemaId": 0
                }
            },
            {
                "key": "cap-senttime",
                "value": {
                    "payload": "3/27/2024 10:18:12 AM",
                    "encoding": "text",
                    "schemaId": 0
                }
            },
            {
                "key": "TraceIdentifier",
                "value": {
                    "payload": "0HN2E1HLP3JGG:00000009",
                    "encoding": "text",
                    "schemaId": 0
                }
            },
            {
                "key": "cap-msg-id",
                "value": {
                    "payload": "4505330901987684353",
                    "encoding": "text",
                    "schemaId": 0
                }
            }
        ],
        "key": {
            "payload": "1e77b71f-2516-4a58-8fcb-e7f1c20ecbdf",
            "encoding": "text",
            "schemaId": 0
        },
        "value": {
            "payload": {
                "EventName": "Post.Created",
                "Key": "1e77b71f-2516-4a58-8fcb-e7f1c20ecbdf",
                "Title": "Title 1",
                "Content": "HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello"
            },
            "encoding": "json",
            "schemaId": 0
        }
    }
]
```

**Comment by yang-xiaodong** [comment]
Hello, I can't reproduce with your steps. 

CAP does not add `traceparent` to the message header. Only when publisher `CallbackName` exists, traceparent will be tried to modify instead of added if it is detected.

https://github.com/dotnetcore/CAP/blob/494650f3294f60f107917400d078c2232d6b5623/src/DotNetCore.CAP/Internal/ISubscribeExector.Default.cs#L194-L195

**Comment by yang-xiaodong** [comment]
No response, closed

**Comment by dongfo** [comment]
_capPublisher.PublishAsync<T>(
    name: topicName,
    contentObj: message,
    headers: _capHeaders);  
CAP will add item to _capHeaders，Make sure that the _capHeaders you pass to the PublishAsync function is new and not shared
