### ISSUE TITLE
订阅服务尚未启动一次时消息丢失

### ISSUE THREAD

**Issue by 6933** [dotnetcore/CAP#1508]
程序分为两个部份：消息发布服务和消息订阅服务。
当消息订阅服务尚未启动一次时，此时rabbitmq队列尚未创建。
这时，消息发布服务发布的消息丢失，但在Published表中标识为Succeeded。
此时再启动消息订阅服务，也无法收到此前发布的消息。

尝试启用 opt.PublishConfirms = true;  也无效。

**Comment by yang-xiaodong** [comment]
请查看 “注意事项”

https://cap.dotnetcore.xyz/user-guide/zh/transport/rabbitmq/
