### ISSUE TITLE
Workshops for dev

### ISSUE THREAD

**Issue by ferdikosasih172147** [dotnetcore/CAP#1510]
Hi @yang-xiaodong, 

Currently, we are quite new in Message Broker Technology and also CAP with distributed transactions. 
I was wondering if you as the author of Dotnet CAP could help us to learn CAP and Kafka architecture so my developers can maximize the technologies.
If you are open, probably we could arrange online meetings to discuss this further.

**Comment by yang-xiaodong** [comment]
Is there any budget for this training, since I can only speak in Chinese, perhaps I could ask our contributors.

**Comment by ferdikosasih172147** [comment]
Hi @yang-xiaodong ,
No problem, we could arrange google meet for further details. Would you share your email?
Thank you

**Comment by yang-xiaodong** [comment]
Hi @mviegas @demorgi @3ldar @MahmoudSamir101 ,

If anyone is interested for this, please leave your email

**Comment by demorgi** [comment]
> Hi @mviegas @demorgi @3ldar @MahmoudSamir101 ,
> 
> If anyone is interested for this, please leave your email

You can reach me out via linkedin in my profile (https://www.linkedin.com/in/rakhmanovdd/), I can cover message broker tech itself and azure service bus integration with CAP (English or Ukrainian language), also kafka integration is also on a table

**Comment by mviegas** [comment]
Hi folks! Feel free to reach out via [Linkedin](https://www.linkedin.com/in/mateus-viegas-65287223/). Happy to help with CAP and Azure Service Bus as a transport.

**Comment by ferdikosasih172147** [comment]
Hi folks! Thank you for your response. I will reach you out in this week. 
@yang-xiaodong Can I reach you via email?

**Comment by yang-xiaodong** [comment]
@ferdikosasih172147 Ok, My email: yangxiaodong1214@gmail.com
