### ISSUE TITLE
batch publish ,set enablePublishParallelSend=true error in SQL Server

### ISSUE THREAD

**Issue by syp10000** [dotnetcore/CAP#1516]
When I batch publish subscriptions, if I set enablePublishParallelSend=true, the program will report an error
![image](https://github.com/dotnetcore/CAP/assets/76423924/1711619f-0cb4-4ee7-b9af-a19acdcc680d)

**Comment by yang-xiaodong** [comment]
How to reproduce?

**Comment by yang-xiaodong** [comment]
No response , closed!
