### ISSUE TITLE
batch publish  more events，Repeated publish data

### ISSUE THREAD

**Issue by syp10000** [dotnetcore/CAP#1517]
batch publish  more events，Repeated publish data
![image](https://github.com/dotnetcore/CAP/assets/76423924/e9c42f49-e1c8-4cb6-a081-7a71e8c05abb)
![ecca49b956049f4ce1621f49b5e3eb4](https://github.com/dotnetcore/CAP/assets/76423924/f19b290f-419b-4f7f-877b-072c554b14d4)
![image](https://github.com/dotnetcore/CAP/assets/76423924/54be0de6-5bd9-4a74-92f1-97a4144ef9cd)
config 
![image](https://github.com/dotnetcore/CAP/assets/76423924/5585bb9b-0a78-4942-9450-76e0747ced5b)

**Comment by yang-xiaodong** [comment]
Closed by https://zhuanlan.zhihu.com/p/25795393
