### ISSUE TITLE
NATS can not be configure cap-msg-id if receiving messages

### ISSUE THREAD

**Issue by wi-chrfaber** [dotnetcore/CAP#1519]
The problem is, when the NATS server issues messages that do not have "cap-msg-id"/"cap-msg-name", the CAP library has trouble receiving the messages. And I didn't find any configuration options to put it (like Kafka for example).

Error Messages
`An exception occurred when process received message. Message:'DotNetCore.CAP.Messages.TransportMessage'.
System.Collections.Generic.KeyNotFoundException: The given key 'cap-msg-id' was not present in the dictionary.
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass22_0.<<RegisterMessageProcessor>b__0>d.MoveNext()`

**Comment by yang-xiaodong** [comment]
Hi @wi-chrfaber ，

NATS does not provide CustomHeadersBuilder option yet, would you like to submit a PR?  Just like Kafka or RabbitMQ.

https://github.com/dotnetcore/CAP/blob/4c2feebb00185f92e4209729bd482ec47140c042/src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs#L122-L129


Thank you in advance.

**Comment by yang-xiaodong** [comment]
Fixed in version 8.2.0.
