### ISSUE TITLE
PostgreSQL/SQL Server as Transport?

### ISSUE THREAD

**Issue by geekox86** [dotnetcore/CAP#1520]
Greetings,

Is there an existing library to use PG/MSSQL as both transport and storage?

Thank you.

**Comment by yang-xiaodong** [comment]
No, it's strange requests

**Comment by geekox86** [comment]
[NServiceBus SQL Server Transport](https://docs.particular.net/transports/sql/)

The point is to simplify the messaging infrastructure in trade of scalability, which is suitable for many small systems that require asynchronous message processing.
