### ISSUE TITLE
请问 Cap.MySql这个provider的驱动是否可以从mysqlConnector换成MySql.Data

### ISSUE THREAD

**Issue by NickJane** [dotnetcore/CAP#1523]
我们的mysql是使用了mysql router的数据库.  
![企业微信截图_17139409557698](https://github.com/dotnetcore/CAP/assets/15319138/d9990bc6-d911-4f56-8201-7068c39b76d6)

结果cap一直报错, 经过排查问题, 发现是mysqlConnector在每次打开事务的时候就会报错

报错 MySqlConnector.MySqlProtocalException: Packet reviced out-of-order. Excepted 1; got 2.

换成MySql.Data就没问题.

请问是否能直接切换成MySql.data作为底层驱动, 或者是否有现成可用的第三方的cap.provider.mysql驱动

**Comment by xiangxiren** [comment]
可以把代码clone下来然后自己更换驱动。

**Comment by xiangxiren** [comment]
https://github.com/mysql-net/MySqlConnector/issues/496
