### ISSUE TITLE
集群部署时需要多个实例都接受消息如何处理

### ISSUE THREAD

**Issue by JavaScript-zt** [dotnetcore/CAP#1525]
在集群部署时2套一样的程序如何配置，看文档说是配置不同的group就可以了，同一套代码如何配置不同的group，group参数必须是常量，也没办法通过读取当前机器标识生成

**Comment by yang-xiaodong** [comment]
You can use `DefaultGroupName`  option to configure it globally.

```
x.DefaultGroupName = Helper.GetInstanceHostname();
```
