### ISSUE TITLE
How to implement transaction Pub/Sub using CAP & FreeSql using demo?

### ISSUE THREAD

**Issue by zfchai** [dotnetcore/CAP#1526]
How to implement transaction Pub/Sub using CAP & FreeSql using demo?

- FreeSql.Provider.PostgreSQL
- DotNetCore.CAP.RabbitMQ
- DotNetCore.CAP.PostgreSql

Can you give us a demo of how to use the above package?
 I'd like to thank you for your help.

**Comment by yang-xiaodong** [comment]
Do you have any questions about the examples in https://github.com/dotnetcore/FreeSql/discussions/1202 ?

**Comment by yang-xiaodong** [comment]
I closed this issue, please reply in https://github.com/dotnetcore/FreeSql/discussions/1202 to keep the thread focused!
