### ISSUE TITLE
Question about parallel execution

### ISSUE THREAD

**Issue by PoteRii** [dotnetcore/CAP#1528]
Hello,
Scenario: Service is consuming events from multiple topics (A and B). I need to retain order and sequential processing for topic A, but need to execute events in parallel for topic B.
How can this be achieved?

**Comment by yang-xiaodong** [comment]
Hello,

CAP's parallel execution configuration is global and does not support separate settings for subscribers.

**Comment by PoteRii** [comment]
any plans to add this feature? or any hints how we can do it?

**Comment by yang-xiaodong** [comment]
These are some hints that might be useful for your short-term solution, we still need to investigate whether to add this feature or not.

1. Place subscribers that require parallel execution into one or more groups, e.g., `parallel-group-1`, `parallel-group-2`.
```cs
[CapSubscribe("A", Group="parallel-group-1")]
public void SubA(){
}

[CapSubscribe("B", Group="parallel-group-2")]
public void SubA(){
}
```

2. Set the `UseDispatchingPerGroup` option to true.
3. Modify `IDispatcher.PerGroup.cs` line 203 as follows :
```cs
if (_enableParallelExecute || key =="parallel-group-1.v1" || key== "parallel-group-2.v1"){

}
```

**Comment by yang-xiaodong** [comment]
We plan to support consumer concurrent in v8.2.0, please check out the PR #1537 !

**Comment by yang-xiaodong** [comment]
@PoteRii Version  [8.2.0-preview-233720681](https://www.nuget.org/packages/DotNetCore.CAP/8.2.0-preview-233720681) is released, take a try.
