### ISSUE TITLE
我想在自己封装的EFContext中同时支持SQL Server,MySQL,PostgreSQL，这三种数据库类型的事务，出现二义性，不知如何弄比较好

### ISSUE THREAD

**Issue by syp10000** [dotnetcore/CAP#1531]
![image](https://github.com/dotnetcore/CAP/assets/76423924/3ebb58fd-6e5e-4cdf-9dac-d75eb319ccf4)
项目同时引用了这三个库
![image](https://github.com/dotnetcore/CAP/assets/76423924/274d748d-f7e8-4bf1-ae3f-785edea4edeb)
由于命名空间和参数一致问题，无法这么使用，不知道如何处理

**Comment by yang-xiaodong** [comment]
虽然我认为你不应该这样做，但我无权干涉你。

`BeginTransactionAsync` 只是一个扩展方法你可以自行编写。

https://github.com/dotnetcore/CAP/blob/18ffd1885a03e8d41ab9bdde0e0f6a97e013d440/src/DotNetCore.CAP.SqlServer/ICapTransaction.SqlServer.cs#L166C47-L173
