### ISSUE TITLE
单个队列与多实例

### ISSUE THREAD

**Issue by 907080752** [dotnetcore/CAP#1535]
你好，我有几个问题想请教

使用RabbitMQ：

1、cap采用了单个队列（如：cap.queue.XXXX.v1）来处理所有的消息，这对性能是否有影响。
比如在两个场景中，场景1中有10w个消息，场景2中有10个消息，但他们都会投递到同一个队列，造成场景2的无故等待。我可以如何处理这种情况

2、我可以如何注入多个实例
项目中我可能会使用多个CAP，在对接多个项目时，可能项目A使用MQ1实例，项目B使用MQ2实例，我可以如何注入并获取到不同的实例来发送或处理消息

**Comment by yang-xiaodong** [comment]
1、没有影响，RabbitMQ单个队列性能可以达到数万到数十万条消息每秒。同时我们支持指定设置Group来将消息投递到独立的队列。
2、不支持。简单来说数据收集项目不是CAP要支持的场景，这种场景不需要使用发件箱模式。你可以使用前置工具聚合后再使用CAP处理。

**Comment by 907080752** [comment]
ok，明白。谢谢
