### ISSUE TITLE
Feature Request: Per-Queue Configuration for BasicQos and ConsumerThreadCount

### ISSUE THREAD

**Issue by ajdwfnhaps** [dotnetcore/CAP#1536]
Description
Currently, it seems that RabbitMQ's BasicQos and ConsumerThreadCount parameters can only be configured globally across the entire service in CAP. It would be highly beneficial to have the ability to configure these parameters individually for each queue. This would allow for more granular control over the message processing behavior, tailored to the specific needs of different queues.

Proposed Solution
Introduce the capability to configure BasicQos and ConsumerThreadCount on a per-queue basis within CAP's configuration. This could be achieved by extending the current configuration options to accept settings for each queue.

Use Case
In scenarios where different queues have different performance and concurrency requirements, being able to specify `BasicQos

**Comment by yang-xiaodong** [comment]
We plan to support consumer concurrent in v8.2.0, please check out the PR https://github.com/dotnetcore/CAP/pull/1537 !

**Comment by yang-xiaodong** [comment]
@ajdwfnhaps Version  [8.2.0-preview-233720681](https://www.nuget.org/packages/DotNetCore.CAP/8.2.0-preview-233720681) is released, take a try.

**Comment by ajdwfnhaps** [comment]
got it, Thanks
