### ISSUE TITLE
一个进程内可以创建多个CAP吗？

### ISSUE THREAD

**Issue by 13822287367** [dotnetcore/CAP#1544]
我的业务场景是，一个进程内会存在不同的业务(插件)服务，不同的业务服务使用的数据库有可能不一样，后续也有可能进行拆分。因此我想使用CAP来处理不同业务服务间的事务，因此需要在一个进程内创建不同的CAP来进行通信。请问是否支持在一个进程内可以创建多个CAP？

**Comment by yang-xiaodong** [comment]
Duplicate of #998
