### ISSUE TITLE
Feature Request:Subscribers can batch process messages

### ISSUE THREAD

**Issue by XyJoinIt** [dotnetcore/CAP#1553]
Description: When the message sender sends a large amount of data, my RabbitMQ has accumulated a lot of messages. I configured [CapSubscribe("sample.rabbitmq.hello", Group = "A", GroupConcurrent = 3)], but even after opening multiple threads on the consumer side, it still can't keep up with the consumption. After checking the documentation, it seems that there is no configuration available for batch reading. My idea is whether it is possible to set up a thread to batch read the messages in the queue for consumption, so that the messages do not accumulate in the queue.

**Comment by yang-xiaodong** [comment]
No plan for this, consumer need to ack for each message.

**Comment by wf-soft** [comment]
Even if each message is confirmed, batch writing is better for tasks such as database writing and cache writing, and message confirmation alone cannot be considered
