### ISSUE TITLE
DeleteExpiresAsync sql Datetime auto format AM/PM

### ISSUE THREAD

**Issue by pccai** [dotnetcore/CAP#1564]
DELETE FROM cap.published WHERE ExpiresAt < '7/17/2024 11:56:57 AM' AND (StatusName='Succeeded' OR StatusName='Failed') limit 1000;

This Causing some database incompatibility.

Ubuntu 22.04/Net8

**Comment by yang-xiaodong** [comment]
What's your database type?

**Comment by pccai** [comment]
DM8

**Comment by yang-xiaodong** [comment]
这和CAP无关，DateTime我们并没有格式化为string然后拼接的sql，而是使用的 SqlParameter 传递的 DateTime 类型，所以对于DateTime的使用这取决于数据库驱动的实现问题。
