### ISSUE TITLE
It seems to be impossible to customize AMQP "subject" header when sending message to Azure Service Bus

### ISSUE THREAD

**Issue by pawel-cyb** [dotnetcore/CAP#1566]
It seems that "subject" header from AMQP 1.0 (section 3.2.4) cannot be customized when using Azure Service Bus - it will always be the type name of the message body - because of two interacting pieces of code - one that prepares message for sending, and one that creates message producer based on config. 

In [ITransport.AzureServiceBus.cs](https://github.com/dotnetcore/CAP/blob/2afd3065a6b68b9c896658d9b9335e065e260ba0/src/DotNetCore.CAP.AzureServiceBus/ITransport.AzureServiceBus.cs#L66) the message subject is set based on message name given when publishing:

```cs
            var message = new ServiceBusMessage(transportMessage.Body.ToArray())
            {
                MessageId = transportMessage.GetId(),
                Subject = transportMessage.GetName(),
                CorrelationId = transportMessage.GetCorrelationId()
            };
```

When looking at the above code, it seems that it would be enough to use [ICapPublisher.Publish function](https://github.com/dotnetcore/CAP/blob/2afd3065a6b68b9c896658d9b9335e065e260ba0/src/DotNetCore.CAP/ICapPublisher.cs#L50), which has a signature as pasted below,  passing subject as first parameter:

```cs
    /// <summary>
    /// Publish an object message.
    /// </summary>
    /// <param name="name">the topic name or exchange router key.</param>
    /// <param name="contentObj">message body content, that will be serialized. (can be null)</param>
    /// <param name="headers">message additional headers.</param>
    void Publish<T>(string name, T? contentObj, IDictionary<string, string?> headers);
```

However, this is not the case. Why? Because this parameter cannot have arbitrary value - is required to always be equal to the dotnet type name of the message (something like `message.GetType().Name`).

Why only dotnet type name is accepted as message name? Because producer for message type is registered under a key which is a dotnet type name of the message - and when choosing producer for message, it is retrieved by message name given when publishing (`p => p.MessageTypeName == transportMessage.GetName()` from code below in [ITransport.AzureServiceBus.cs](https://github.com/dotnetcore/CAP/blob/2afd3065a6b68b9c896658d9b9335e065e260ba0/src/DotNetCore.CAP.AzureServiceBus/ITransport.AzureServiceBus.cs#L43) - the same name that is later used as message subject.
 
 ```cs
    public IServiceBusProducerDescriptor CreateProducerForMessage(TransportMessage transportMessage)
    {
        return _asbOptions.Value
                   .CustomProducers
                   .SingleOrDefault(p => p.MessageTypeName == transportMessage.GetName())
               ??
               new ServiceBusProducerDescriptor(
                   transportMessage.GetName(),
                   _asbOptions.Value.TopicPath);
    }
 ```
 
 As a result, subject is currently always equal to dotnet type of the message.
 
 I also tried passing the `headers` parameter with "subject" key and custom value, however value passed in such way is not used for broker property - only additional custom property is added.
 
 Would it be possible to add any way of customizing the message subject, or maybe correcting the way message producers are retrieved so that message name does not have to be equal to message type name?

**Comment by yang-xiaodong** [comment]
@pawel-cyb  Thank you for your feedback.

Initially, we only supported a single topic. The contribution to support different producers for different topics comes from PR #1283. @mviegas is more familiar with this matter, and I believe he will provide an answer once he has time.

CC @jonekdahl
