### ISSUE TITLE
dotnet cap aws lose connection to database postgres in aws

### ISSUE THREAD

**Issue by Totot0** [dotnetcore/CAP#1568]
I have a dotnet 7 api deploy on an aws container. This api uses dotnet cap 7.2.2 to use the RAbbitMq bus. At times I have an interruption to my bdd postgress and cap can not reconnect this. I am obliged to shut down my service and restart it

**Comment by yang-xiaodong** [comment]
The database operation is creating connections every time, you may need to check your network.

**Comment by Totot0** [comment]
The problem is with the use of o.UsePostgresSql
`            services.AddCap(o =>
            {
                o.UseDashboard(opt => opt.PathMatch = "/outbox");
                o.DefaultGroupName = "myApi";
                o.TopicNamePrefix = configuration.GetValue<string>("ENV");
                o.GroupNamePrefix = configuration.GetValue<string>("ENV");

                // Outbox storage
                o.UsePostgreSql(connectionString);
.....
`

How do I know if I had a network outage on aws? Why is it not reconnecting automatically if the network is restored?

**Comment by yang-xiaodong** [comment]
No response, closed!
