### ISSUE TITLE
What is the use of Traceparent in the header?

### ISSUE THREAD

**Issue by xiaolipro** [dotnetcore/CAP#1570]
I want to know what the "tracepoint" in the "Header" is for and when it was set. I looked through the source code and didn't find out when it was assigned a value.
我想知道Header中的tracepoint是用于什么目的，何时赋值的。我查看了源代码，没有发现它被赋值，只找消费者从header中解析的逻辑，他在哪里被赋值呢？我希望伪造一份header以便仍然在使用cap的消费者无缝兼容
![image](https://github.com/user-attachments/assets/3ff94603-c551-4f4d-9121-597899dfba4d)

**Comment by yang-xiaodong** [comment]
Traceparent is for OpenTelemetry trace contexts, just `cap-msg-id` and `cap-msg-name` are required when processing event for external systems.

https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#heterogeneous-system-integration

**Comment by yang-xiaodong** [comment]
Traceparent is for OpenTelemetry trace contexts, just `cap-msg-id` and `cap-msg-name` are required when processing event for external systems.

https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#heterogeneous-system-integration
