### ISSUE TITLE
support CDC

### ISSUE THREAD

**Issue by ductai202** [dotnetcore/CAP#1574]
Hi,
I just ask do we will support CDC (change data capture) with tools like Debezium in the future, and when working with RabbitMQ, can we  more flexible config exchange type like Direct, Fanout or Header, now I see we currently only use Topic Exchange. Thanks.

**Comment by yang-xiaodong** [comment]
Hi,

> I just ask do we will support CDC (change data capture) with tools like Debezium in the future.

No plan and no support in the future, that doesn't fit our design.

> when working with RabbitMQ, can we more flexible config exchange type like Direct, Fanout or Header, now I see we currently only use Topic Exchange.

We provide an upper level abstraction for the Broker, if you want to be flexible you should use other libraries specialized for RabbitMQ such as EasyNetQ

**Comment by ductai202** [comment]
> We provide an upper level abstraction for the Broker

what does it really means, can you explain more information

**Comment by yang-xiaodong** [comment]
The feature we provide requires ensuring that all brokers are available, which may involve utilizing specific functions of a particular broker. This means that when you switch between any supported brokers, the code does not need to be changed, similar to how EF database providers work.

**Comment by ductai202** [comment]
I see, thanks for your answer !
