### ISSUE TITLE
Add index in received table

### ISSUE THREAD

**Issue by maisa92** [dotnetcore/CAP#1575]
We are experiencing a significant performance issue with the following DELETE query on our PostgreSQL database

`DELETE FROM "cap"."received" WHERE "Id" IN (SELECT "Id" FROM "cap"."received" WHERE "ExpiresAt" < $1 AND ("StatusName"='Succeeded' OR "StatusName"='Failed') LIMIT $2)`

This query requires a full table scan instead of utilizing an index scan, leading to high I/O and longer execution times.

To improve the query performance, I think adding an index on the ExpiresAt column will be helpful

**Comment by yang-xiaodong** [comment]
Would you want to make a PR like #426 ?

**Comment by yang-xiaodong** [comment]
Adding indexes means a decline in write and update performance. Considering that most users may not have large amounts of data (our main focus is on solving transaction consistency issues), we did not build in indexes but instead suggest that users with large data volumes manually add indexes.

This is my initial thought.

**Comment by maisa92** [comment]
got it, we will add on our side
