### ISSUE TITLE
Question about support for RabbitMQ RPC

### ISSUE THREAD

**Issue by 18108296886** [dotnetcore/CAP#1578]
亲爱好的开发者你们好
     首先感谢你们为开源社区做的贡献，让我们愉快地使用这款优秀的中间件，我在学习过程中遇到一个问题，那就是我所涉及的场景会使用到RabbitMQ的RPC模式，请问在CAP中支持使用RPC模式吗，我现在使用的是最新版本的CAP8.2.0 又仔细查看了官方文档，没有相关的介绍，所以过来咨询一下。

**Comment by yang-xiaodong** [comment]
Hi,

We do not support the Request-Response mode. In fact, messages are always delivered asynchronously, the RPC mechanism in RabbitMQ is essentially similar to our callback-based publishing.

In your case, I think using gRPC would be a more suitable choice!
