### ISSUE TITLE
我将UseInMemoryStorage改成SQL server，会导致包源码报错

### ISSUE THREAD

**Issue by tangxiaoqi-tangxiao** [dotnetcore/CAP#1579]
我将UseInMemoryStorage改成SQL server，会导致包源码报错
我使用UseInMemoryStorage来代替SQL server正常运行
![image](https://github.com/user-attachments/assets/b6f0724c-e041-4069-98f7-b1f4d8f3db6b)

对象为空的报错，变量_publishedChannel为空

![image](https://github.com/user-attachments/assets/f5e56f20-b41b-4710-b7d2-4aae4f36d831)

数据库没有问题，可以连接上自动创建了表

![image](https://github.com/user-attachments/assets/bdb2d66a-4e81-43b0-b469-1cd164776e5c)

**Comment by tangxiaoqi-tangxiao** [comment]
使用版本
![image](https://github.com/user-attachments/assets/7c24d1ac-7e2f-4ede-bf9a-82004add324b)

**Comment by tangxiaoqi-tangxiao** [comment]
我经过测试发现services.AddHostedService<MyService>();和UseSqlServer一起使用就会产生这个错误

**Comment by yang-xiaodong** [comment]
> 我经过测试发现services.AddHostedService();和UseSqlServer一起使用就会产生这个错误

无法复现

**Comment by tangxiaoqi-tangxiao** [comment]
这是我的测试代码
[CAP2.zip](https://github.com/user-attachments/files/17001607/CAP2.zip)

**Comment by yang-xiaodong** [comment]
MyService.cs

_timer = new Timer(PublishMessage, null, TimeSpan.FromSeconds(2), TimeSpan.FromSeconds(1));

timer第3个参数添加延迟启动2秒，需要等CAP准备就绪。
