### ISSUE TITLE
Too few ACKs

### ISSUE THREAD

**Issue by liu9jian0she** [dotnetcore/CAP#1581]
The queue used is RabbitMQ.

![image](https://github.com/user-attachments/assets/239d279b-de0e-4b11-ba82-412347cfb87a)

The source code is as follows.

![image](https://github.com/user-attachments/assets/356f9080-1cef-44cb-a6d3-f67ff55fa5e9)
![image](https://github.com/user-attachments/assets/c3dd8f8d-be47-40cc-a6cd-0fb37a787931)

```[tasklist]
### Tasks
```

**Comment by yang-xiaodong** [comment]
Closed by https://zhuanlan.zhihu.com/p/25795393

**Comment by liu9jian0she** [comment]
bureaucratic jargon
