### ISSUE TITLE
The subscriber cannot receive the message

### ISSUE THREAD

**Issue by pinzi** [dotnetcore/CAP#1589]
Hello,I have a webapi for publish messages, and a another webapi for receive messages.The subscriber cannot receive the message After the program running normally for a period of time. But everything is ok When I deleted all keys which related to cap.
Here are some key information:

**Windows Server 2012
.NET 6.0
CAP 8.2
Storage: InMemory
Transport: RedisStreams
Redis 5.0.14.1**

**Comment by yang-xiaodong** [comment]
Did you try running our Sample [Samples.Redis.SqlServer](https://github.com/dotnetcore/CAP/tree/master/samples/Samples.Redis.SqlServer) to see if it works?

**Comment by pinzi** [comment]
> Did you try running our Sample [Samples.Redis.SqlServer](https://github.com/dotnetcore/CAP/tree/master/samples/Samples.Redis.SqlServer) to see if it works?

Ok,I will try what you said.
The problem occurred after the program ran for several months.
This is an occasional issue and it is uncertain whether it can be reproduced.

**Comment by yang-xiaodong** [comment]
@pinzi 

You need to check the Redis Server logs and the logs of the client driver StackExchange at the time of the problem to determine what happened.

In addition to this, you need to check the context of the consumer group and messages to be consumed in the Redis Stream. You can try using the client command to check if you are able to consume properly.
