### ISSUE TITLE
Consumer stops consuming events when poll timeout is exceeded

### ISSUE THREAD

**Issue by APMIFEMA** [dotnetcore/CAP#1591]
@APMIFEMA 

We have added more retryable error codes to the `RetriableErrorCodes` configuration, as follows:

```
ErrorCode.Local_Retry,
ErrorCode.RequestTimedOut,
ErrorCode.LeaderNotAvailable,
ErrorCode.NotLeaderForPartition,
ErrorCode.RebalanceInProgress,
ErrorCode.NotCoordinatorForGroup,
ErrorCode.NetworkException,
ErrorCode.GroupCoordinatorNotAvailable,
```

However, I believe that `Local_MaxPollExceeded` should not be added. This exception is caused by the `max.poll.interval.ms` configuration. This error is not suitable for retries because it indicates that the consumer’s behavior does not meet expectations. Typically, this means that the consumer logic needs to be optimized to ensure that the `poll()` method is called within the specified interval to prevent the consumer from being considered unresponsive.

Setting the `Local_MaxPollExceeded` error to be retried could cause the same message to be repeatedly polled by the consumer due to processing timeout.

In response to your error, I believe that the application design should be adjusted to ensure that each message is processed within Kafka’s maximum polling interval or that the `max.poll.interval.ms` configuration value is increased. 

As for timeouts caused by CPU overload, as discussed earlier, it seems there isn't a good solution for that scenario.

_Originally posted by @yang-xiaodong in https://github.com/dotnetcore/CAP/issues/1587#issuecomment-2401157586_
            
Hello,

Thanks for the reply. :)

In our case it is not a problem of high CPU consumption in the consumer.

The problem is that we have to call an API that sometimes takes longer than expected (it runs complicated processes that depend on third parties...), and even in some cases, when retrying the call, the maximum polling time is exceeded.

But that only happens in very specific cases.

The desired behavior would be that the event would be registered as a dead event, and the consumer would continue consuming the next Kafka event, but in our case the consumer stops and does not consume any event again, and we lose reliability and trust in the service...

**Comment by yang-xiaodong** [comment]
For your specific cases, I think you have a couple options:

* Add `Local_MaxPollExceeded` to RetriableErrorCodes to make the consumer retry.
* Specify a timeout for the external API you're calling.
* Set `max.poll.interval.ms` config for kafka consumer.

**Comment by APMIFEMA** [comment]
Hi,

Thanks for responding so quickly :).

I hadn't quite understood that the list of errors that are considered good for continuing to try to consume events was configurable....

We will use this configuration to adapt it to our needs.

Thank you very much for your work, making it possible for all of us to use this fantastic library to provide resilience to our event-oriented integrations.!!
