### ISSUE TITLE
cap.rabbitmq  消息问题

### ISSUE THREAD

**Issue by FuYan** [dotnetcore/CAP#1593]
发布端的消息是匿名类型，接收端的消息变成了base64格式 很奇怪，前几天又正常，能正常解析成对象
![image](https://github.com/user-attachments/assets/8ba5d482-155a-4f9f-8a77-cdcb7223ce65)
![image](https://github.com/user-attachments/assets/8881b1d3-9579-4bef-a105-44769d176dcc)

**Comment by yang-xiaodong** [comment]
Please show your consumer code and replacing your base64 with text (no screenshots please)

**Comment by FuYan** [comment]
文件解决了， ChargingVehicleId 我用了long接收，导致消费消息时报错json序列化错误，然后我一直重新消费错误的消息，一直不成功，改类型后，重新发布新消息，消费成功了
{
"Headers": 
{
"cap-callback-name": 
null,
"cap-msg-id": 
"4478380436136554499",
"cap-corr-id": 
"4478380436136554499",
"cap-corr-seq": 
"0",
"cap-msg-name": 
"StartTransaction.Accepted",
"cap-msg-type": 
"<>f__AnonymousType1`7",
"cap-senttime": 
"2024/10/14 11:22:13"
},
"Value": 
{
"ChargingVehicleId": 
"36293757499205",
"ChargePointId": 
"36208522319941",
"TransactionId": 
48,
"ConnectorId": 
1,
"StartTagId": 
"B4A63CDF",
"StartResult": 
"Accepted",
"MeterStart": 
0
}
}
