### ISSUE TITLE
cap-msg-type not correct when derived base class

### ISSUE THREAD

**Issue by muratyuceer** [dotnetcore/CAP#1595]
Hi, 

When I publish message from my generic publisher method the cap-msg-type value shows the name of the base class, as seen in the image below.

`    public Task PublishAsync<T>(
        T contentObj,
        CancellationToken cancellationToken = default)
    where T : IntegrationEvent
    {
        return capPublisher.PublishDelayAsync( contentObj, ncellationToken);
    }`

![image](https://github.com/user-attachments/assets/cf34677f-6e20-4f3c-86a4-567a4dae058e)

**Comment by yang-xiaodong** [comment]
Hello,

We use `typeof(T).Name` to get the type name, and by default, it does not retrieve the base class name. In your case, it returns the base class name because you added a constraint on `T` with `where T : IntegrationEvent`. 

For your use case, we recommend adding your custom type header to the event header information.

**Comment by muratyuceer** [comment]
> Hello,
> 
> We use `typeof(T).Name` to get the type name, and by default, it does not retrieve the base class name. In your case, it returns the base class name because you added a constraint on `T` with `where T : IntegrationEvent`.
> 
> For your use case, we recommend adding your custom type header to the event header information.

Thank you for your response. I understand that I can add a custom header, but can I also override the built-in 'cap-msg-type' header? What I'm really curious about is whether the improper processing of the 'cap-msg-type' header would affect the functionality of the CAP structure.

**Comment by yang-xiaodong** [comment]
> but can I also override the built-in 'cap-msg-type' header

Yes you can, this header is only used to provide for user to view the type, no side effects.
