### ISSUE TITLE
期待当配置RabbitMQ时cap.published支持至少消费指定1个或多个订阅服务后才能定时清除

### ISSUE THREAD

**Issue by rocleegithub** [dotnetcore/CAP#1602]
以保证消费端异常或延迟未启动成功且发布者发送Exchange时没有队列，当消息过多或超出清楚时间后，相当于消费白发送了也就是没有达到CAP；
或者支持配置不通过Exchange发送消息，可以配置指定队列发送。

**Comment by yang-xiaodong** [comment]
There are no plans for this.
Broker-based senders usually follow the Fire-and-forget guideline, and if you need to know the result of consumption to do something, it's better to use rpc instead of messages!

**Comment by rocleegithub** [comment]
那我的临时解决方案：

1. 根据实体状态手动或定时扫描补偿发送消息事件。

2. 首次使用应用前得提前启动消费端，消费端队列 `durable:true` （持久的）保证异常情况下重启消费端后这个队列还在（生产者继续发送消息到这个队列），当再次启动后继续消费这个队列。
