### ISSUE TITLE
Does CAP support sending messages to oneself?

### ISSUE THREAD

**Issue by jrlygdsj** [dotnetcore/CAP#1603]
Does CAP support sending messages to oneself? 
That is, a service that published a message and it can reveive this message too
I remember earlier versions didn't seem to support it，there were some issues

**Comment by yang-xiaodong** [comment]
Of course, why don't you do a test?

**Comment by jrlygdsj** [comment]
> Of course, why don't you do a test?

yes have done， he number of received messages is less than the number of sent messages，I have encountered it twice
