### ISSUE TITLE
RabbitMQ Transport Reject Function Call Error

### ISSUE THREAD

**Issue by LuckyZhangWeiwei** [dotnetcore/CAP#1608]
public void Reject(object? sender)
 {
     _consumer!.BasicAck((ulong)sender!);
 }

should be 

 public void Reject(object? sender)
 {
    _consumer!.BasicReject((ulong)sender!);
 }

**Comment by yang-xiaodong** [comment]
上引用或截图我看看

**Comment by LuckyZhangWeiwei** [comment]
![image](https://github.com/user-attachments/assets/e28bfb00-c635-42cb-b13d-4c8036c05a0e)

**Comment by LuckyZhangWeiwei** [comment]
\CAP\src\DotNetCore.CAP.RabbitMQ\RabbitMQConsumerClient.cs

**Comment by yang-xiaodong** [comment]
你这是最新代码么

**Comment by LuckyZhangWeiwei** [comment]
是  我刚有查了一下您现在的main 分支 也是这种代码
  public void Commit(object? sender)
    {
        _consumer!.BasicAck((ulong)sender!);
    }

    public void Reject(object? sender)
    {
        _consumer!.BasicAck((ulong)sender!);
    }

**Comment by yang-xiaodong** [comment]
确认Bug，由8.2.0版本引入，感谢你的报告！

**Comment by yang-xiaodong** [comment]
Fixed in version 8.3.1
