### ISSUE TITLE
duplicate header error

### ISSUE THREAD

**Issue by PoteRii** [dotnetcore/CAP#1620]
Hello, we are getting following exception: An item with the same key has already been added. Key: cap-msg-group

 at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at DotNetCore.CAP.Kafka.KafkaConsumerClient.Consume(ConsumeResult`2 consumerResult)
   at DotNetCore.CAP.Kafka.KafkaConsumerClient.Listening(TimeSpan timeout, CancellationToken cancellationToken)
   at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass21_1.<Execute>b__2()

![image](https://github.com/user-attachments/assets/238fcb9b-1b73-4888-96da-50d10dccb36d)

This causes consumer to crash, decreases members of kafka consumer and thus increases lag (messages behind). We are not modifying headers and I could not find a message in DB with duplicate cap-msg-group header

any ideas for the cause?

**Comment by PoteRii** [comment]
turn out one of our provider produced an invalid message, which already contained cap-msg-group header. Can we move CustomerHeadersBuilder on top of other logic so such cases can be handled by it?

**Comment by yang-xiaodong** [comment]
Each has its own benefits, and placing them on top offers the possibility of rewriting Group.

Whether or not to place the `headers.Add(Headers.Group, _groupId)` to `headers[Headers.Group] =_groupId` looks good?

**Comment by PoteRii** [comment]
yes, that is also an option, since other implementations (e.g. Redis) use that approach as well

**Comment by yang-xiaodong** [comment]
> yes, that is also an option, since other implementations (e.g. Redis) use that approach as well

Would you want to make a PR？

**Comment by PoteRii** [comment]
sure

**Comment by yang-xiaodong** [comment]
Fixed in v8.3.2
