### ISSUE TITLE
Dot Net 8 High Memory Consumption While Stress Testing (1000 Message * 1 MB)

### ISSUE THREAD

**Issue by MohamedOssama** [dotnetcore/CAP#1621]
I am using CAP with Dot Net 8 (SQL Server + KAFKA)

I have created a controller to push 1000 messages each message is 1MB in size as follows:
[big_file_size_1mb.json](https://github.com/user-attachments/files/18004462/big_file_size_1mb.json)
![image](https://github.com/user-attachments/assets/1be3a6e4-348e-4f9f-acaf-7e5655cc039e)

I have High Memory Consumption using VS diagnostics tools:
![image](https://github.com/user-attachments/assets/6e5c1881-d3dd-4429-88c0-a9107afe3533)

The memory consumption remains high, but it reaches 70-80 MB after a while (30-40 min) from sending the last message.

I am using the following CAP Options:
![image](https://github.com/user-attachments/assets/b569e84f-e844-47fc-8c32-21184a4214fb)

Am I missing the correct options or is there a way to optimize the memory consumption?

**Comment by yang-xiaodong** [comment]
I ran it with the `dotnet run -c relaese ` command and monitored it with dotMemory, and everything looks fine!

![image](https://github.com/user-attachments/assets/8747154a-5ca1-455e-ad6e-177df1bc6228)

**Comment by yang-xiaodong** [comment]
![无标题](https://github.com/user-attachments/assets/0793296c-4855-4c1a-b480-0ebba52e0146)

**Comment by yang-xiaodong** [comment]
No response, closed!
