### ISSUE TITLE
循环发送消息时，出现消息已发出，但是数据库保存未完成，导致消息消费时找不到记录的情况

### ISSUE THREAD

**Issue by dangzhenjiuhao** [dotnetcore/CAP#1622]
`using (var connection = tempContext.Ado.Connection)
{
    using (var transaction = connection.BeginTransaction(_capPublisher, autoCommit: false))
    {
        if (connection.State != ConnectionState.Open)
        {
            connection.Open();
        }

        tempContext.Ado.Transaction = transaction;

        var tempMessageList = new Dictionary<string, string>();
        foreach (var item in useList)
        {
            item.FStatus = "B";
            tempMessageList.Add(item.FId, $"aaa1");
        }

        //更新数据
        await tempContext.Fastest<AAA>()
                .BulkUpdateAsync(useList, new string[] { nameof(IEntity.FId) }, new string[] { nameof(IEntity.FStatus) });

        //发送消息
        foreach (var item in tempMessageList)
        {
            await _capPublisher.PublishAsync(item.Value, item.Key);
        }

        tempContext.Ado.Transaction.Commit();
    }
}`

**Comment by yang-xiaodong** [comment]
提交事务的方式错误，请查看我们的示例

**Comment by dangzhenjiuhao** [comment]
我按你们的示例试过了也一样
`
using (var trans = tempContext.BeginCapTransaction(_capPublisher, autoCommit: false))
{
    try
    {
        var tempMessageList = new Dictionary<string, string>();
        foreach (var item in useList)
        {
            item.FStatus = "B";
            tempMessageList.Add(item.FSysIdentityId, $"XXXX_Run1");
        }

        //更新数据
        tempContext.Fastest<SourceEntity>()
                .BulkUpdate(useList, new string[] { nameof(IEntity.FId) }, new string[] { nameof(IEntity.FStatus) });

        //发送消息
        foreach (var item in tempMessageList)
        {
            _capPublisher.Publish(item.Value, item.Key);
        }

        trans.Commit();
    }
    catch (Exception)
    {
        trans.Rollback();
    }
}
`

**Comment by yang-xiaodong** [comment]
使用我们的ADO.NET的示例，不要加入你的任何代码，如果问题依旧请提供版本信息

**Comment by yang-xiaodong** [comment]
FreeSql和CAP集成

https://github.com/dotnetcore/FreeSql/discussions/1202

**Comment by dangzhenjiuhao** [comment]
我使用的是sqlserver，现在的问题是消费的时候，根据消息中的数据从数据库加载数据时，找不到数据，即消费早于数据的保存

**Comment by yang-xiaodong** [comment]
Please open a new issue to describe your new problem so that we can focus on the thread, and remember that if you're reporting a bug please provide the version you're using, the configuration, and the steps to reproduce it!
