### ISSUE TITLE
Support Request for MongoDB.EntityFrameworkCore

### ISSUE THREAD

**Issue by AdemCatamak** [dotnetcore/CAP#1624]
Hi,

I really like your package. I use it with EntityFramework when using data storage environments like Postgres and SqlServer.

Are you planning to add EntityFramework (MongoDB.EntityFrameworkCore) support to your MongoDb package?

**Comment by yang-xiaodong** [comment]
Hi,

For this library, not seeing any benefit from using EntityFrameworkCore, we need to provide more customization using the native syntax.
