### ISSUE TITLE
Does CAP really support sending messages to oneself?

### ISSUE THREAD

**Issue by jrlygdsj** [dotnetcore/CAP#1625]
I have test, 
the number of received messages is less than the number of published messages.
I have encountered it twice in one month,
some message are in the cap.published table, but not in the received table

Does CAP really support sending messages to oneself? 
For example, a service sends a message and later it receives the message

@yang-xiaodong

**Comment by yang-xiaodong** [comment]
If you can't provide the steps to reproduce it, I can't be of any assistance

**Comment by jrlygdsj** [comment]
1、use cap like this
![393460559-aa1cd1db-3481-4cf6-8707-54b9f86cb832](https://github.com/user-attachments/assets/fe092de3-1671-4e14-b012-528841f1c485)

2、handler
![1](https://github.com/user-attachments/assets/b04955b9-c049-46bf-a3fa-2d6dc8c34fb2)

3、publish
![企业微信截图_17335353983162](https://github.com/user-attachments/assets/c1524c43-6489-4698-b828-896b5d07d64c)

**Comment by jrlygdsj** [comment]
The method Commit  is the same as Reject, this is a  bug? @yang-xiaodong 

![企业微信截图_17335462458759](https://github.com/user-attachments/assets/05d8831b-f412-470c-8504-e2c892480582)

**Comment by yang-xiaodong** [comment]
> The method Commit is the same as Reject. So, is this a bug? When write cap.Received table failed, the message is lost @yang-xiaodong

It's already fixed in v8.3.1
