### ISSUE TITLE
Delayed message causing OOM

### ISSUE THREAD

**Issue by manongLein** [dotnetcore/CAP#1627]
In our company's products, cap is used.
There  many delayed messages every day, and when the web server restart, the StatusName of the messages changes from 'Delayed' to 'Queued'
As time goes on, the number of 'Queued' messages increases, ultimately leading to OOM

The time interval for restarting the server is approximately 1-2 minutes
the databases for storage is Sql Server,transport is rabbitMQ

**Comment by yang-xiaodong** [comment]
The delay in CAP is lightweight. When the service starts abruptly, it loads and processes messages from the past minute and earlier into memory. Therefore, if your application needs to process a large volume of messages in a short time within a memory-constrained environment, it may lead to unexpected exceptions. We recommend creating a batch processing plan to handle data in an orderly manner in memory-constrained environments, using CAP only to trigger your batch processing plan.

**Comment by manongLein** [comment]
Thanks for your detailed reply,I will consider using other methods to reduce the number of delayed messages.
