### ISSUE TITLE
Dashboard Requeue and Re-execute

### ISSUE THREAD

**Issue by PoteRii** [dotnetcore/CAP#1628]
Is there any way to hide Requeue and Re-execute buttons on production in Dashboard? (for succeeded messages only)
Or is there any way to tell if the message publish/re-execute is triggered from the Dashboard?

**Comment by yang-xiaodong** [comment]
If you're willing to contribute PRs, it might be possible to add a new configuration item to the Dashboard.

**Comment by PoteRii** [comment]
solved by using IHttpContextAccessor to determine if the call was made from dashboard or not
