### ISSUE TITLE
RabbitMQ定期维护重启后，系统无法恢复正常

### ISSUE THREAD

**Issue by qingxuanjiao** [dotnetcore/CAP#1631]
Hi,

我们在系统中使用了CAP，以下是系统中所使用的版本：
![image](https://github.com/user-attachments/assets/03a10ea2-7bc9-4862-a956-e1912f51af60)

背景：
1. RabbitMQ我们使用了AWS的RabbitMQ产品，每周会定期进行维护且无法关闭
![9503ba80ec875249580bf6b7b56edf9](https://github.com/user-attachments/assets/3af6f2f7-d645-46bb-bf7b-44c1689ed641)
2. RabbitMQ重启时间，预计在5分钟之内完成

问题描述：
1. RabbitMQ重启之后，CAP无法恢复正常，间隔30s报“RabbitMQ channel model create failed!”
![image](https://github.com/user-attachments/assets/36a5c130-d7e6-4b2e-b6db-a4d6a176d0c6)
2. RabitMQ异常后，MySQL持久化存储也出现了问题
![image](https://github.com/user-attachments/assets/778b413f-513e-47a8-9183-b15cce9be7e0)
3. 服务需要手动重启，才能恢复正常

期待您的宝贵建议，非常感谢！

**Comment by yang-xiaodong** [comment]
此类问题需自行排查，因为无法复现，只看异常信息不够。
