### ISSUE TITLE
Could I configure connectionStrings one times to use anywhere

### ISSUE THREAD

**Issue by yilezhu** [dotnetcore/CAP#169]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement
___
### Question
- What do you want to know?

Could I configure connectionStrings one times to use anywhere?
I user mysql +dapper  and configure like this 

```
services.AddCap(x =>
{     
    x.UseMySql(Configuration.GetConnectionString("hn_datasync"));
}

//then In my controller I must to use like this
using (var connection = new MySqlConnection(_configuration.GetConnectionString("hn_datasync")))
{
    connection.Open();
    using (var transaction = connection.BeginTransaction())
    {
        await _publisher.PublishAsync(CapEventKeys.GA_RY_CSDJXXBAddEvent, Datas, transaction);
        transaction.Commit();
    }
}

```

so I use 'Configuration.GetConnectionString("hn_datasync"))' two times, could I configure connectionStrings one times to use In up two ways.

**Comment by yuleyule66** [comment]
You can completely encapsulation the code to your liking. CAP only provides a piece of demo code that uses the simplest logic to tell you that it needs an `IDbTransaction` object to send the message.
