### ISSUE TITLE
无法发布、订阅字符串类型消息

### ISSUE THREAD

**Issue by xbfspace** [dotnetcore/CAP#17]
1、无法发布订阅字符串类型消息
        [Route("~/publish")]
        public IActionResult PublishMessage()
        {
            //_capBus.Publish("sample.kafka.sqlserver", "消息内容"); //不能直接发布string类型的消息 得搞个实体
            _capBus.Publish("sample.kafka.sqlserver", new MyMessage { Title = "your dd" });

            return Ok();
        }
 [NonAction]
        [CapSubscribe("sample.kafka.sqlserver")]
        //订阅消息，消息参数为string无法接收
        public void ReceiveMessage1(string data)
        {
            Console.WriteLine($"receive data{data}");
            Debug.WriteLine($"receive debug data{data}");
        }
2、先注释掉订阅的action,运行程序，然后发布一条消息a。重新启用订阅action，运行程序，消息a无法被消费
3、core 2.0 还无法使用，异常：
An error occurred while starting the application.
MissingMethodException: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.

DotNetCore.CAP.MySqlCapOptionsExtension.TempBuildService(IServiceCollection services)

    MissingMethodException: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
        DotNetCore.CAP.MySqlCapOptionsExtension.TempBuildService(IServiceCollection services)
        DotNetCore.CAP.MySqlCapOptionsExtension.AddServices(IServiceCollection services)
        Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddCap(IServiceCollection services, Action<CapOptions> setupAction)
        Core2Website.Startup.ConfigureServices(IServiceCollection services) in Startup.cs

                services.AddCap(c =>

System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by yuleyule66** [comment]
Thanks for your feedback. I'll check it.   CAP unsupported .NET Core 2.0 now. Can you provide your 
 environment?  Mysql or sql server?　RabbitMQ or Kafka?

**Comment by xbfspace** [comment]
.net core 1.1 , mysql , rabbitmq. 
  public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<AppDbContext>();

            services.AddCap(x =>
            {
                x.UseEntityFramework<AppDbContext>();
                // x.UseKafka("localhost:9092");
                x.UseRabbitMQ(options =>
                {
                    options.HostName = "localhost";
                    options.Port = 9203;
                    options.UserName = "guest";
                    options.Password = "guest";
                    options.VirtualHost = "/";
                   
                });
            });

            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();
            loggerFactory.AddDebug();

            app.UseMvc();

            app.UseCap();
        }

public class AppDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseMySql("server=localhost;userid=root;pwd=123456;port=3306;database=Sample;sslmode=none;");
        }
    }
@yuleyule66

**Comment by yuleyule66** [comment]
Fixed at v1.1.0
