### ISSUE TITLE
several instances with a single table

### ISSUE THREAD

**Issue by darkspring1** [dotnetcore/CAP#170]
### Question
I'm planning to deploy several instances of web service.
Each instance will store events in a single Table.
One table for all instances.

Another microservice will read messages from this table and push them to the Message Queue.

Is it posible with CAP?

**Comment by yuleyule66** [comment]
Yes.

The same microservice instance can use the same database table when deploying multiple copies.

Another scenario is that different microservice instances need to use different table names if they use the same database table to store messages.
