### ISSUE TITLE
Multiple events in 1 transaction

### ISSUE THREAD

**Issue by fireya** [dotnetcore/CAP#171]
___

### Bug
- Which version of CAP, OS and .NET Core?
CAP: 2.2.5, OS: windows 10, >net core: 2.1.2

- What happen?

Hello! I am experimenting with your great library. and using slightly modified sample:
```C#
[Route("~/publishWithTransactionUsingEF")]
        public async Task<IActionResult> PublishMessageWithTransactionUsingEF([FromServices]MyDbContext dbContext,[FromServices]ICapPublisher publisher, int n)
        {
            using (var transaction=dbContext.Database.BeginTransaction())
            {
                for (int i = 0; i < n; i++)
                {
                    await publisher.PublishAsync("xxx.services.account.check", new Person { Name = "Foo"+ i });
                }
                transaction.Commit();
            }
            return Ok();
        }
```

I use kafka, postgres and entity framework.
When sending n=10, all 10 messages are almost immediatly inserted into kafka and are received, but in database i have this state:
![image](https://user-images.githubusercontent.com/19556590/43259100-c9837918-90dd-11e8-9f10-cc6beb906c18.png)
4 messages with succeeded state and 6 with scheduled. After a couple of minutes, they are changed to Succeeded state and were resent. So i am getting duplicates.

I suggest, that it is a bug, or am i using library wrong way?

**Comment by kexxxfeng** [comment]
Have you try Publish with `transaction`
```c#
await publisher.PublishAsync("xxx.services.account.check", new Person { Name = "Foo"+ i }, transaction);
```

**Comment by yuleyule66** [comment]
You should not use this way to send a message for testing because the transaction is not committed, which may result in failure to get the message when changing the state of the message.

The correct way is to use a concurrent test tool, such as `wrk` or `apache benchmark`, and then invoke api url.

E.g:
`wrk -t 4 -d 20 http://localhost:5000/publish`

**Comment by fireya** [comment]
i am simulating some business case: for example, master-details, when i need produce events for all detail lines when updating master line.

I need to produce strictly one event in 1 transaction?
