### ISSUE TITLE
How to send a message correctly in a logic that needs to be executed sequentially?

### ISSUE THREAD

**Issue by xruihu** [dotnetcore/CAP#173]
逐层发布，如果最后一步订阅业务错误怎么回滚前面步骤？

**Comment by yuleyule66** [comment]
In a project that using the microservice, if your business context is closely related and heavily dependent, as you call this sequential dependency, you should not break them up into many services to handle, but rather they should be aggregated into one service.

Event messages are the medium through which services communicate with each other,  the expected outcome of this service communication should be consistent with the final consistency.

**Comment by xruihu** [comment]
简单举例：比如订单业务，需要分别发布修改库存和修改金额的事件消息
那么如果修改库存成功，修改金额失败，我只能callback发布者（订单回滚），库存怎么解决？

**Comment by yuleyule66** [comment]
After the order is created, the amount of the order should not be modified. The inventory is pre-deducted when the order is placed, so I cannot explain your example

**Comment by yuleyule66** [comment]
Making business process sequential execution or broadcast mode based on your business needs. CAP does not limit the way you perform business logic.
You need to make an assessment based on your business scenario.

**Comment by xruihu** [comment]
非常感谢您的耐心回复，顺序执行的话，如果用顺序队列我需要一级一级的发布再一级一级往上callback我这个理解对吗？

**Comment by yuleyule66** [comment]
Yes
