### ISSUE TITLE
能不能开放一些internal的接口

### ISSUE THREAD

**Issue by DillonHuang** [dotnetcore/CAP#175]
### Question
- DotNetCore.CAP.Internal 的接口和实现很多是Internal，是不是写成public的比较好，这样更容易扩 
  展。至少可以把接口开放出来。

**Comment by yuleyule66** [comment]
What interface are you referring to, and how do you want to expand it?

**Comment by DillonHuang** [comment]
比如说可以通过接口 IConsumerServiceSelector找到事件处理的方法，类必须继承ICapSubscribe，方法必须打上TopicAttribute。我想用自己的接口IEventHandler(IEventHandler在抽象层并不依赖第三方库)，
这样每个EventHandler必须同时实现IEventHandler，ICapSubscribe，感觉不太舒服。

**Comment by yuleyule66** [comment]
你的这个需求好像和是否开放internal并无关系啊
