### ISSUE TITLE
MongoDB.Driver.MongoCommandException: Command findAndModify failed: WriteConflict

### ISSUE THREAD

**Issue by yf84503974** [dotnetcore/CAP#176]
在使用Mongodb做为消息可靠保证过程中示例中ValuesController下PublishWithTrans()中代码，我用压力测试工具试下性能，报错很多，Mongodb写入冲突错误，我感觉是并发造成的，报错内容:MongoDB.Driver.MongoCommandException: Command findAndModify failed: WriteConflict,希望提供下解决办法，非常感谢

**Comment by kexxxfeng** [comment]
Could you provide your test repo?

**Comment by yf84503974** [comment]
测试聚合报告:
Label	# Samples	Average	Median	90% Line	95% Line	99% Line	Min	Max	Error %	Throughput	Received KB/sec	Sent KB/sec
HTTP	150	13	8	30	42	60	7	70	9.33%	73.71007	248.86	9.07
TOTAL	150	13	8	30	42	60	7	70	9.33%	73.71007	248.86	9.07
150个请求出错率高达几十个，不知道您有没有用工具测试遇到过这种情况？
`[Route("~/publish")]
        public async Task<IActionResult> PublishWithTrans()
        {
                using (var trans = await _mongoTransaction.BegeinAsync())
                {
                    var collection = _client.GetDatabase("TEST").GetCollection<BsonDocument>("test");
                    collection.InsertOne(trans.GetSession(), new BsonDocument { { "hello", "world" } });

                    await _capPublisher.PublishWithMongoAsync("sample.rabbitmq.mongodb", DateTime.Now, trans);
                }

            return Ok();
        }`

**Comment by yuleyule66** [comment]
Thanks for your feedback at first time, MongoDB is still in the preview version, we will make some adjustments before the official release, so stay tuned.

**Comment by lx4556332** [comment]
2.5.0 版本还存在这个问题。
