### ISSUE TITLE
model bind for type like datetime guid always failed.

### ISSUE THREAD

**Issue by Eilyyyy** [dotnetcore/CAP#18]
when you send message type that can simplely convert from string like guid, datetime, you always get a format exception that not valid value for this type. the problem is than you publish message always use json string , but you can't just  use typeconvert convert json string to a object.

**Comment by Eilyyyy** [comment]
i think you can fix this problems by serialize simple type of message just use to string method, or always treat as complex type.

**Comment by yuleyule66** [comment]
Hi @Eilyyyy , thanks for your feedback.

I have already fix this bug at commit [297cecf](https://github.com/dotnetcore/CAP/commit/297cecfacbd35f1a55d87c706346cfb84a27fa9c).

I will release a new version later.

**Comment by Eilyyyy** [comment]
![tim 20170727155751](https://user-images.githubusercontent.com/9607459/28660123-617c9402-72e4-11e7-9e22-63e6ce177ee4.png)
i'm sure i'm on this commit but the problem is still here.

**Comment by yuleyule66** [comment]
you mean that you are using this `void Publish<T>(string name, T contentObj)` overload method to publish message with datetime or guid?

**Comment by Eilyyyy** [comment]
yes, PublishAsync

**Comment by Eilyyyy** [comment]
i think the problem is here 
`var isComplexType = !TypeDescriptor.GetConverter(type).CanConvertFrom(typeof(string));`

this type can convert from string , so you treat it as simple type.you serialize a 134 you got 123, but you serialize a guid you got a "xxxx-xxxxxx-xxxx", notice you have a quotation marks and this cause you can't convert from the content.

**Comment by yuleyule66** [comment]
Yes, I didn't consider this kind of situation, I will fix it later, thank you.

**Comment by yuleyule66** [comment]
Hi @Eilyyyy
I fixed this problem and removed the overloaded method of publishing string content.

**Comment by yuleyule66** [comment]
fixed at v1.1.0
