### ISSUE TITLE
Startup exception when using Autofac

### ISSUE THREAD

**Issue by fayuanliu** [dotnetcore/CAP#184]
___
### Bug
- cap版本：2.2.6-preview-50057154，尝试了2.25版本也一样有这个问题，运行直接报错：
![image](https://user-images.githubusercontent.com/11306331/44334559-73d91b00-a4a4-11e8-94c1-0356ee79e096.png)

**Comment by yuleyule66** [comment]
This may be related to the Autofac you use, I have not done more testing on Autofac compatibility.

**Comment by yuleyule66** [comment]
No response, close the issue.
