### ISSUE TITLE
Is there any plan to support more .net platforms

### ISSUE THREAD

**Issue by fanruinet** [dotnetcore/CAP#185]
我在官方文档中只看到了MVC的支持与示例，请问是否支持Console、WinForm、WPF、WebForm、Windows Service等其他类型的程序？我的项目中没有MVC。
如果支持，请补充一下示例代码。如果暂时还不支持，请考虑新增对以上类型程序的支持。
谢谢！

**Comment by yuleyule66** [comment]
Can you tell me why you need this component in WinForm, WPF, WebForm?

**Comment by fanruinet** [comment]
For WebForm, it has the same reason to support mvc.
For WinForm/WPF, our client app is a internal application which uses the queue as RPC. I'm not aware of the current support of console app (no sample code provided). In most cases if console is supported, WinForm/WPF can be supported too. I'll try it later.

**Comment by yuleyule66** [comment]
We didn't more test for .net framework, let me konw if you have any question
