### ISSUE TITLE
consul 添加自定义TAG  

### ISSUE THREAD

**Issue by xxyss** [dotnetcore/CAP#187]
consul 注册时 添加自定义TAG。  否则不能使用 FABIO 做负载 或者有其他的 解决方案？

**Comment by yuleyule66** [comment]
I can't understand what you mean , please describe your problem in detail.

What is `自定义TAG`, `不能否则`? I don't know about FABIO.

**Comment by xxyss** [comment]
当前版本 注册consul 的时候 Tags = new[] {"CAP", "Client", "Dashboard"}, 直接赋值 ，是否可以改可以配置，有些情况会用到Tag，例如使用Fabio 负载的时候需要指定Tag ”urlprefix-*“ ，作者可否允许开发者自定义consul  Tag。

**Comment by yuleyule66** [comment]
This feature is not currently on our plan list
