### ISSUE TITLE
How to ensure idempotency of message consumption?

### ISSUE THREAD

**Issue by Lightgogogo** [dotnetcore/CAP#189]
首先非常感谢你们的开源项目，但是在我阅读源码的过程中，没有看到任何有关幂等性以及防分布式并发的代码。不清楚CAP是如何实现在高可用集群微服务架构中，保障同一条消息只被消费一次。在我测试过程中，可以将同一条信息多次发送，消费者也会进行多次消费，这样会产生一个很严重的业务问题。打个比喻，银行转账服务推送了一个A转账给B 100美金的消息，由于消息重复消费，很可能会产生结果给B转账200美金的情况。按照我的了解，如果利用MQ实现最终一致性，由于主流MQ不支持分布式事务消息，未保障消息可靠性，要么是牺牲性能利用MQ自带的事务，要么是允许发送消息的重复，但是保障幂等性。

**Comment by Lightgogogo** [comment]
另外补充说明下，我的版本是2.2。
以下是DefaultSubscriberExecutor中的一段代码：` private async Task<(bool, OperateResult)> ExecuteWithoutRetryAsync(CapReceivedMessage message)
        {
            if (message == null)
            {
                throw new ArgumentNullException(nameof(message));
            }

            try
            {
                var sp = Stopwatch.StartNew();

                await InvokeConsumerMethodAsync(message);

                sp.Stop();

                await SetSuccessfulState(message);

                _logger.ConsumerExecuted(sp.Elapsed.TotalSeconds);

                return (false, OperateResult.Success);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"An exception occurred while executing the subscription method. Topic:{message.Name}, Id:{message.Id}");

                return (await SetFailedState(message, ex), OperateResult.Failed(ex));
            }
        }`
可见消费的事件处理于消息消费状态的更改不是在同一个事务上下文中执行，或许会这里又会引发隐患。

**Comment by yuleyule66** [comment]
The framework cannot guarantee idempotency 100%, this requires the consumer to guarantee, please see: https://github.com/dotnetcore/CAP/wiki/2.API%E6%8E%A5%E5%8F%A3#22-%E8%AE%A2%E9%98%85%E6%B6%88%E8%B4%B9

**Comment by yuleyule66** [comment]
In some scenarios where strict idempotency is required, users can design their own log records to ensure idempotence. These logs can be placed in storage such as Redis or MongoDB, using their atomic operations to ensure idempotency.
