### ISSUE TITLE
2.3 Migration Questions/Issues 

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnetcore/CAP#190]
Consolidated thread for any migration questions and issues for CAP

Doc: https://www.cnblogs.com/savorboard/p/cap.html

Migration sql scripts: 

* MySQL

```sql
ALTER TABLE `cap.published` MODIFY Id BIGINT NOT NULL;
ALTER TABLE `cap.received` MODIFY Id BIGINT NOT NULL;
```

* PostgreSql

```sql
ALTER TABLE cap.published ALTER COLUMN "Id" TYPE BIGINT;
ALTER TABLE cap.published ALTER COLUMN "Id" DROP DEFAULT;

ALTER TABLE cap.received ALTER COLUMN "Id" TYPE BIGINT;
ALTER TABLE cap.received ALTER COLUMN "Id" DROP DEFAULT;
```

* SQLServer

```sql
ALTER TABLE Cap.[Published] DROP CONSTRAINT [PK_Cap.Published];
ALTER TABLE Cap.[Published] ALTER COLUMN Id BIGINT NOT NULL;
ALTER TABLE Cap.[Published] ADD CONSTRAINT [PK_Cap.Published] PRIMARY KEY(Id);

ALTER TABLE Cap.[Received] DROP CONSTRAINT [PK_Cap.[Received];
ALTER TABLE Cap.[Received] ALTER COLUMN Id BIGINT NOT NULL;
ALTER TABLE Cap.[Received] ADD CONSTRAINT [PK_Cap.Received] PRIMARY KEY(Id);
```

**Comment by wmowm** [comment]
最新版2.3里面移除了Dapper吗,没有看到Dapper的相关信息了? ORM框架是否可以支持NHibernate?

**Comment by yang-xiaodong** [comment]
> 最新版2.3里面移除了Dapper吗,没有看到Dapper的相关信息了?

No, Dapper is still on the database extension library of CAP

>ORM框架是否可以支持NHibernate?

We have no plans for  NHibernate at now !

**Comment by mahonecode** [comment]
Whether there are plans to support the oracle database

**Comment by yang-xiaodong** [comment]
@mahonecode  We have no plans to support Oracle database now, you can implement Oracle database extension by yourself

**Comment by yang-xiaodong** [comment]
@guxing2  Would like to describe your scenario of using SQLLite?

**Comment by guxing2** [comment]
> @guxing2 Would you like to describe your scenario of using SQLite?
@yang-xiaodong ,As we know, EFCore support  SQLite database and the SQLite is enough to some tiny site , but   mail notification ,SMSS notification ,pay callback and so on are also necessary for these sites , all of these need event notification    
  too . Once the CAP can support the SQLite ,we can develope site with minimal dependence and have no dependencies on the server .

**Comment by zeekay18** [comment]
how can I add the initial migration for Sql Server?
