### ISSUE TITLE
Question about message queue not available

### ISSUE THREAD

**Issue by yjqGitHub** [dotnetcore/CAP#195]
非常有幸能够看到如此好的作品。我在深入学习cap的过程中，整理了下cap整个操作逻辑：
      先开启一个事务，然后执行数据库操作，接着插入一个待发送的事件到数据库里面，然后将事件写入到缓存，再更改事件为已发送，然后提交事务，接下来就是通过mq发送事件了。
在这样的情况下 假如mq发生宕机的话，那么该事件是不是就不会被订阅消费了？
不知道是不是我看代码之后自己的理解有问题?

**Comment by yang-xiaodong** [comment]
Here is a message sent flow chart, when the transaction is committed success, we will submit the buffer data to the message queue, if the process of sending message to MQ failed, then the message will be processing by `MessageRetryProcessor` to process.

```
                   +-------------+
 +---------+       |             |      +---------+
 | publish +------>+ Transaction +----->+ Commit  |
 +---------+       |             |      +---------+
                   +-------------^          X
                          |                 X
                          |   XXXXXXXXXXXXXXX
                          |   X
                          v   X
                   +-------------+      +---------+
                   | BufferList  +----->+ Queue   |
                   +-------------+      +---------+

```
