### ISSUE TITLE
事务回收问题

### ISSUE THREAD

**Issue by xueandfeng** [dotnetcore/CAP#197]
### @- [ ] 
我使用cap版本为2.3
目前我用的cap是使用手动提交事务。没有用cap的自动提交事务。我事务提交的地方不是在业务方法里面。而是在进行Dispose()的地方进行统一事务提交的。
然后只要我下面的图的构造方法的参数调换下位置。就会先把事务进行回收了。导致DbContext的事务没办法提交事务了。

![qq 20180905165117](https://user-images.githubusercontent.com/20178645/45082486-05df5580-b12c-11e8-89b1-f169b1b67dd5.png)

**Comment by yang-xiaodong** [comment]
I don't quite understand what you mean, but committing a transaction in Dispose is definitely a bad design.

The `CapTransaction` will dispose the database transaction object  when `Dispose()` invoke, see https://github.com/dotnetcore/CAP/blob/develop/src/DotNetCore.CAP.SqlServer/ICapTransaction.SqlServer.cs#L101
