### ISSUE TITLE
编译错误,调用方法不明确

### ISSUE THREAD

**Issue by wmowm** [dotnetcore/CAP#200]
`public static IDbContextTransaction BeginTransaction(this DatabaseFacade database, ICapPublisher publisher, bool autoCommit = false);
public static ICapTransaction BeginTransaction(this IDbConnection dbConnection, ICapPublisher publisher, bool autoCommit = false);
`
使用mysql的示例,这两个方法不明确,编译报错

**Comment by yang-xiaodong** [comment]
not found

**Comment by wmowm** [comment]
![tim 20180908094851](https://user-images.githubusercontent.com/16713889/45249080-795fad80-b34c-11e8-9411-3d71d39be455.png)

**Comment by yang-xiaodong** [comment]
你检查下你环境吧，我这里正常编译。这两个扩展方法扩展的是不同的对象，理论上不会有编译的问题

**Comment by royfu** [comment]
如果项目中同时引用了DotNetCore.CAP.MySql和DotNetCore.CAP.SqlServer，就会出现这个问题，建议对这两个扩展方法所属类的命名空间做下区分
