### ISSUE TITLE
Does CAP support ASP.NET MVC？

### ISSUE THREAD

**Issue by bluetianx** [dotnetcore/CAP#202]
我现在有个项目是用 传统的asp.net mvc 框架进行开发的，框架是 netframework 4.6 。cap提供了像支持asp.net core 那样对 asp.net mvc 框架提供了支持了吗？
 PS:我们项目用kafka作为了消息队列

**Comment by yang-xiaodong** [comment]
Because CAP depends on DI container , so it does not support .net framework asp.net mvc.

**Comment by bluetianx** [comment]
alright ，thanks
