### ISSUE TITLE
关于监听队列得到信息之后，此时数据库是宕机的情况 Questions

### ISSUE THREAD

**Issue by yjqGitHub** [dotnetcore/CAP#203]
- [ question] 在学习CAP的过程中，我发现当消费者监听得到消息时，会把消息存储到数据库当中，然后再处理。当存储到数据库这一步失败的时候，然后就直接不接收这条信息了。假如这时消费者的数据库发生宕机了，那这些消息该怎么处理呢？

**Comment by yang-xiaodong** [comment]
没有不接收啊，在RabbitMQ和Kafka中处理方式是不一样的。
RabbitMQ：拒绝掉
Kafka：偏移量-1
该消息会被重新推送过来

**Comment by yjqGitHub** [comment]
对，不好意思，我在RabbitMQ这里的拒绝里面，把一个是否重新入队的参数看错了，我本地测试的时候，参数给的是false，所以拒绝了没有入队。但是CAP是true，会重新入队。
