### ISSUE TITLE
怎么把CAP集成到 Abp 中呢？

### ISSUE THREAD

**Issue by bawfgfhv** [dotnetcore/CAP#208]
怎么把CAP集成到 Abp 中呢？

**Comment by yang-xiaodong** [comment]
I don't know much about ABP, it needs you to explore it yourself.

**Comment by bxjg1987** [comment]
值得关注的问题哈，我用的abp5.9想集成，不知从何下手

**Comment by yang-xiaodong** [comment]
releated issue #616
