### ISSUE TITLE
CAP连接mysql报错

### ISSUE THREAD

**Issue by wmowm** [dotnetcore/CAP#210]
![image](https://user-images.githubusercontent.com/16713889/45729413-edc50700-bbfe-11e8-8305-8739ab462e4a.png)
已确保连接是可以使用的,配置如下
![image](https://user-images.githubusercontent.com/16713889/45729451-15b46a80-bbff-11e8-86b1-2183a95378cf.png)

**Comment by yang-xiaodong** [comment]
please ensure `connection.BeginTransaction()`  is working correct without CAP's `BeginTransaction` ?

**Comment by wmowm** [comment]
按照WIKI进行编写的,_capBus对象存在,不使用事务,直接_capBus.Publish("xxx.services.bar", DateTime.Now);
也报错,mysql链接无法访问,实际上是可用访问的

**Comment by yang-xiaodong** [comment]
@wmowm  我的意思是，直接使用 connection.BeginTransaction() 开启事务是否正常，不要使用CAP提供的BeginTransaction扩展方法 ？

**Comment by wmowm** [comment]
解决了,SQL链接问题,从库里的表被删除了.....................
