### ISSUE TITLE
rabbitmq消费问题

### ISSUE THREAD

**Issue by xueandfeng** [dotnetcore/CAP#214]
@yang-xiaodong 
使用cap2.3版本。
rabbitmq服务端一台
本地应用一， 分组名group.test 订阅名为 sample.rabbitmq.test1
本地应用二， 分组名group.test 订阅名为 sample.rabbitmq.test2

发送消息订阅名为sample.rabbitmq.test2 这个时候 本地应用一会把sample.rabbitmq.test2 进行消费
导致消息是失败的
下面是Dashboard界面图。 

订阅界面：
![default](https://user-images.githubusercontent.com/20178645/46927141-93d12900-d066-11e8-84ca-ebc48d63ddb5.png)
![default](https://user-images.githubusercontent.com/20178645/46927161-a6e3f900-d066-11e8-8f17-906be2b714dd.png)

发送界面
![default](https://user-images.githubusercontent.com/20178645/46927235-f88c8380-d066-11e8-9eee-743e9a4c8563.png)

接收界面
![default](https://user-images.githubusercontent.com/20178645/46927257-0fcb7100-d067-11e8-8a3b-2640caa3a881.png)
![default](https://user-images.githubusercontent.com/20178645/46927261-16f27f00-d067-11e8-9c4e-28a6c710c6f5.png)

**Comment by yang-xiaodong** [comment]
本地应用一会把sample.rabbitmq.test2 进行消费

看不懂？

**Comment by xueandfeng** [comment]
同一台服务端rabbitmq ，同一个分组名称 。2个不同的程序 ，一个程序上订阅名称是sample.rabbitmq.test2。一个订阅名称是sample.rabbitmq.test1。发布端发送消息的时候是sample.rabbitmq.test2 这个时候另外一个程序(sample.rabbitmq.test1)会直接进行消费(sample.rabbitmq.test2)的消息

**Comment by yang-xiaodong** [comment]
意思是，同一个Group，发出去是 “sample.rabbitmq.test2”， 使用“sample.rabbitmq.test1”订阅到了？

**Comment by xueandfeng** [comment]
不是。 sample.rabbitmq.test1 这个程序上没有订阅名sample.rabbitmq.test2 只有订阅名sample.rabbitmq.test1。但是这个程序会把消息标识为失败
![default](https://user-images.githubusercontent.com/20178645/46927879-625a5c80-d06a-11e8-9c83-8ce774df48e9.png)

我正常的应该是发送出去的sample.rabbitmq.test2，需要在sample.rabbitmq.test2这个订阅方法上进行消费的

**Comment by yang-xiaodong** [comment]
下面不是有issue链接么，#63 描述了你遇到的问题

**Comment by yang-xiaodong** [comment]
最新预览版nuget包修复了这个问题，详见：#205

**Comment by yang-xiaodong** [comment]
关闭此issue，如有新的其他类型的问题，请新开issue，以便于我们一个issue专注一个问题
