### ISSUE TITLE
Only if the program subscribed some topics, the messages of subscribed topics could be sent to RabbitMQ successfully.

### ISSUE THREAD

**Issue by keith-leung** [dotnetcore/CAP#215]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
Only if the program subscribed some topics, the messages of subscribed topics could be sent to RabbitMQ successfully.

只有当程序订阅某个主题的时候，这些被订阅的主题发送到RabbitMQ的消息才会成功。如果没有被订阅，主题消息发出后无法在其他系统中监听到。

先运行一个Sample.RabbitMQ.MySql进程A，在Demo：https://github.com/dotnetcore/CAP/blob/develop/samples/Sample.RabbitMQ.MySql/Controllers/ValuesController.cs 里面修改一下，[CapSubscribe("#.rabbitmq.mysql")] 注释掉，然后运行起来。然后再复制一个这个项目到另外一个解决方案B里面运行，保留[CapSubscribe("#.rabbitmq.mysql")] 没有注释，B运行起来。

然后在A程序里面调用ValuesController.cs的WithoutTransaction方法，B程序[CapSubscribe("#.rabbitmq.mysql")]标记的Subscriber没有能够接收到A发出的消息。

如果在A里面增加[CapSubscribe("#.rabbitmq.mysql")]，则消息能够发送成功。

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
The code in https://github.com/dotnetcore/CAP/blob/develop/src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs may not be suitable for RabbitMQ channel building.

https://github.com/dotnetcore/CAP/blob/develop/src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs 这里面扫描CAP相关消费者类的代码不一定合适，如果这里扫描的结果返回空，则发布的消息到了RabbitMQ，另一个子系统订阅也收不到。建议修改一下逻辑，只需要程序里带有发布的topic或者订阅的topic都可以成功处理，否则分布式系统消息通知只能通知系统本身，将没有意义。

**Comment by keith-leung** [comment]
> There is no such problem as you said. The systems depend on the message queue. They can communicate with each other, Are you sure that your two projects are connected to the same message queue?

Absolutely the same RabbitMQ's IP, port, username, password and topic. One side published, the other side subscribed. It only worked when both two sides were subscribing the same topic, they could receive messages.

**Comment by yang-xiaodong** [comment]
Are you using the same assembly name?

**Comment by keith-leung** [comment]
> Are you using the same assembly name? Are you using the different database? I can't get any infomation about your project and the configuration.
> 
> You can upload you project to github , I can have a look

When I opened the solution for test this morning, it continued sending previous message yesterday posted. And the subscriber works now. I guess there is a re-send attempt, the message was not post successfully yesterday. 
Is there any logs to show whether the messages were posted to RabbitMQ successfully?

**Comment by yang-xiaodong** [comment]
see :https://github.com/dotnetcore/CAP/wiki/5.%E5%AE%9E%E7%8E%B0
