### ISSUE TITLE
[English]When you use second databases, you cannot create two tables of cap.[中文]当使用第二个数据库时，不能创建两个CAP表。

### ISSUE THREAD

**Issue by mingyanzhen** [dotnetcore/CAP#218]
Hi @yang-xiaodong 
[中文] 大佬好，要用英文啊，好尴尬，赶紧把我的百度翻译拿了出来。
[中文] 我的第一个mysql的数据库是可以生成cap的那两张表的，所以'_capBus.Publish'的时候也是对的，到后边第二个数据库的时候，就生成不了cap的那两张表了，‘_capBus.Publish’也出错了。
[English] My first MySQL database can generate the two cap tables, so it's also true for'_capBus.Publish', and by the time I get to the second database, I can't generate the two cap tables, and'_capBus.Publish'is wrong.
![image](https://user-images.githubusercontent.com/6066974/47250842-a9c25d80-d45b-11e8-94ca-4e7dafd92fc7.png)

**Comment by yang-xiaodong** [comment]
Hello, 
We does not support multiple EntityFramework DbContext in one application.
