### ISSUE TITLE
Data insertion for multiple databases

### ISSUE THREAD

**Issue by mingyanzhen** [dotnetcore/CAP#219]
Hi @yang-xiaodong 
[中文]  我之前试了单个数据库的，插入是没有问题的，后边弄多个数据库的时候。我这样处理，然后只存进去了后边那个数据库内容，前边那个没有存进去。
           因为没有找到有例子存多个数据库的(我之前没有过分布式的经验)，所以冒昧来问下您。希望能够解决这个问题，谢谢！
[English]  I have tried a single database before, and insert is no problem. I did this, and then I only saved the database content in the back.
                Since I haven't found an example of storing multiple databases (I haven't had any previous experience of over-distributing), I'd venture to ask you. Hope to solve this problem, thank you!

![image](https://user-images.githubusercontent.com/6066974/47252757-5280b500-d47c-11e8-9774-3481ef917f71.png)

**Comment by yang-xiaodong** [comment]
CAP does not support multiple EntityFramework DbContext in one application, You can using ado.net to do it.

**Comment by mingyanzhen** [comment]
> CAP does not support multiple EntityFramework DbContext in one application, You can using ado.net to do it.

Thinks @yang-xiaodong 
[中文] 这样啊，那我用ado.net 试下先。
[English] Well, then I'll try ado.net first.
