### ISSUE TITLE
Not retry at specified interval time with FailedRetryInterval?

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/CAP#222]
Received表格消息记录Added的值2018-10-30 10:59:54.5233333
订阅消息执行出现异常,默认重试三次之后
ExpiresAt的值就更新为2018-11-14 10:59:58.5900000
再次重试间隔也未免太长了吧?
`services.AddCap(x =>
            {
                x.FailedRetryInterval = 10;
                x.DefaultGroup = "test";
                x.UseSqlServer("xxxxxxx");
                x.UseRabbitMQ("xxxxxxx");
            });`
即使配置了FailedRetryInterval=10,理论下不是应该间隔10秒再次重试吗?
求解答

**Comment by yang-xiaodong** [comment]
So your question is "Not retry at specified interval time with FailedRetryInterval? "

You also need to show you version num of CAP

**Comment by yang-xiaodong** [comment]
English is the official language of Github, My answer is not for you alone, but for anyone else who might be able to find it from any source.

> About `ExpiresAt`

You need reading the wiki doc first: https://github.com/dotnetcore/CAP/wiki/5.%E5%AE%9E%E7%8E%B0#55-%E6%95%B0%E6%8D%AE%E6%B8%85%E7%90%86

> About for redis storage

You need to understand what problem does CAP solved first.

**Comment by bao2314483** [comment]
我调试过去发现订阅消息在首次接收的时候,出现异常并且重试3次,是符合文档说明,
但是之后配置了FailedRetryInterval=10之后,发现并不可以10秒后再次触发,反而发现如果我关闭demo,然后再次启动调试偶尔会发现能再次接收消息,但是不是每次成功,也没有发现规律可言

**Comment by yang-xiaodong** [comment]
The message published time and retry start time have a 4-minute offset. 
see: https://github.com/dotnetcore/CAP/wiki/5.%E5%AE%9E%E7%8E%B0#51-%E6%B6%88%E6%81%AF%E8%A1%A8
