### ISSUE TITLE
Question about message lost in RabbitMQ 

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/CAP#223]
发送端
`
[HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            _capBus.Publish("test3", Guid.NewGuid());
            return new string[] { "value1", "value2" };
        }
`
订阅端
`
[CapSubscribe("test2")]
        public void UserDriveLicenseApplyAdd(Guid Id)
        {
            Console.WriteLine(Id.ToString());
        }
`

根据代码可以看到发送端发送名为test3消息,数据库表Published也记录整条消息Succeeded,但是问题订阅端没有订阅test3,导致这条test3消息丢失了,这是为什么呢?

反观如果发送端先启动服务,刚好业务调用了这个test3消息推送,同时假设订阅端服务有监听test3,可惜订阅端还没有在test3消息发送之前启动监听test3,这时候就会出现这条消息丢失,请问有什么办法解决

**Comment by yang-xiaodong** [comment]
see https://github.com/dotnetcore/CAP/wiki/2.API%E6%8E%A5%E5%8F%A3#221-%E4%BE%8B%E5%A4%96%E6%83%85%E5%86%B5

**Comment by bao2314483** [comment]
② 消息没有任何订阅者
如果你发送了一条个没有被任何订阅者订阅的消息，那么此消息将被立即标记为失败，并且不会进行任何重试。

但是在Published表里面是标记为Succeeded的

**Comment by yang-xiaodong** [comment]
wiki doc updated and removed ②
