### ISSUE TITLE
how to use cap/eventbus when DI is autofac?

### ISSUE THREAD

**Issue by sampsonye** [dotnetcore/CAP#224]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- I have replace DI with Autofac,all business services was registered by autofac,eventbus  doesn't work fine. init code like this:
```
 public IServiceProvider ConfigureServices(IServiceCollection services){
    var builder = new ContainerBuilder();
    builder.Populate(service);
    var allclass = GetAllImplementClasses<IService>(alltypes).ToArray();
    builder.RegisterTypes(allclass).AsImplementedInterfaces().InstancePerLifetimeScope();

     service.AddCap(options =>
     {
        options.UseMySql("server=localhost;port=3306;Initial Catalog=cap;user id=root;password=123456;SslMode=None");
        options.UseRabbitMQ("localhost");
     });
     var builder = new ContainerBuilder();
     builder.Populate(service);
     return new AutofacServiceProvider(builder.Build());
 }
```

**Comment by yang-xiaodong** [comment]
We did not test the third-party DI container, there may be have some compatibility issues. Would you like to do some testing and submit an improved PR to us?

**Comment by yang-xiaodong** [comment]
@sampsonye I can't reproduce your issue,  and in my example autofac works properly

**Comment by yang-xiaodong** [comment]
Autofac examples:

**Startup.cs**

```cs
public IServiceProvider ConfigureServices(IServiceCollection services)
{
	services.AddMvc();

	services.AddTransient<ISub, Subs>();

	services.AddCap(x =>
	{
		x.UseInMemoryStorage();
		x.UseAzureServiceBus("");
		x.UseDashboard();
	});

	var container = new ContainerBuilder();
	container.Populate(services);

	return new AutofacServiceProvider(container.Build());
}
```

```cs
    public class Subs : ISub, ICapSubscribe
    {
        [CapSubscribe("sample.azure.mysql2")]
        public void ShowTime(DateTime time)
        {
            Console.WriteLine("Now time:" + time);
        }
    }

    public interface ISub
    {
        void ShowTime(DateTime time);
    }
```

**Comment by sampsonye** [comment]
this is not work for core 3.1
···
System.NotSupportedException:“ConfigureServices returning an System.IServiceProvider isn't supported.”
···

**Comment by AlphaYu** [comment]
@yang-xiaodong 
上面的例子 这一段代码 `services.AddTransient<ISub, Subs>();` Subs 还是通过IServiceCollection 注册的，并不是通过autofac注册。

如果用autofac注册，代码如下。确实不能生效。
`autofacBuilder.RegisterType<Subs>().As<ISub>().SingleInstance();`

因为订阅者都在应用层创建，想在应用层使用autofac注册订阅者。
然后在startup.cs 文件中,注册该模块。
```
 public void ConfigureContainer(ContainerBuilder builder)
  {
            //注册依赖模块
            builder.RegisterModule(AdncWarehouseApplicationModule());
  }
```

**Comment by zhanghaiboshiwo** [comment]
这个问题有好的解决方案？
