### ISSUE TITLE
event ID 总是 2147483647。 使用Mysql

### ISSUE THREAD

**Issue by mfemail8** [dotnetcore/CAP#225]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of CAP, OS and .NET Core?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yang-xiaodong** [comment]
We have been using MySQL for several months in our production environment without your problem.

We cannot ascertain anything with one asentence.

**Comment by mfemail8** [comment]
SnowflakeId.Default().NextId() 总是返回 2147483647， 是和我环境设置有关吗？

**Comment by yang-xiaodong** [comment]
`SnowflakeId.Default().NextId()` 返回的是19位的long类型，你的结果 2147483647 位数都不对。

![image](https://user-images.githubusercontent.com/8205994/47828270-48847d80-ddbd-11e8-8393-07bf4847099d.png)

**Comment by mfemail8** [comment]
知道了。原来Id字段类型需要由int(127) -> bigint(20)

**Comment by mfemail8** [comment]
Solved

**Comment by yang-xiaodong** [comment]
#190
