### ISSUE TITLE
There no publisher message on Dashboad.

### ISSUE THREAD

**Issue by DiYin** [dotnetcore/CAP#228]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ x] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The dashboard not show the publisher 
___
### Bug
- Which version of CAP, OS and .NET Core?
CAP.2.3.1
OS Windows 10
.NET Core 2.1.1
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
1. I Use your sample Sample.RabbitMQ.MySql to create another sample Sample.RabbitMQ.SqlServer.
2. I have run the API and check the database, there is 5 publisher messages
![image](https://user-images.githubusercontent.com/11624543/47972056-f2c60480-e04c-11e8-819d-0f78e1b4b1d6.png)
3. However,  when I open the dashboard, there is nothing show on the published job.
![image](https://user-images.githubusercontent.com/11624543/47972071-1a1cd180-e04d-11e8-8c83-4aa4e04702ad.png)
4. Is there something wrong or I am not understand correctly.
5. Maybe my RabbitMQ is not configurate correctly. But the configuration is very simple, x.UseRabbitMQ("localhost"); This what I like.

 
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yang-xiaodong** [comment]
Your message status is `Scheduled` , Only Scccessed and Faield can be seen on the dashboard.
