### ISSUE TITLE
 [Question] how can we config CAP with multi RabbitMQ server in one ASPNETCORE application 

### ISSUE THREAD

**Issue by joeiren** [dotnetcore/CAP#229]
### Question
- How can we config CAP with RabbitMQ, we will pub/sub from multi MQ server that have different mq server endpoint(maybe different server, different virtual host or exchange, etc.). 
So how can we config in one ASPNETCORE application?
***CAP如何配置RabbitMQ的选项？我们需要和多个MQ服务器进行订阅/发布操作，可能这些服务器有不同的地址或则VHost、exchange不一样. 所以想知道如何在一个ASPNETCORE的启动应用中配置CAP呢？***

**Comment by yang-xiaodong** [comment]
If you want connect to the rabbitmq  cluster, you can set `HostName` like “192.168.1.111,192.168.1.112”.

If you want to connect different rabbitmq servers , we does not support. In microservices, you need to keep the message bus server unified.

**Comment by joeiren** [comment]
If config different virtual host on one rabbitmq server,  can it  be supported?

**Comment by yang-xiaodong** [comment]
No, different virtual host is same as different servers

**Comment by joeiren** [comment]
opps, it's so bad
