### ISSUE TITLE
send messages without persistent

### ISSUE THREAD

**Issue by chrcao** [dotnetcore/CAP#23]
一些低到达率要求的场景，是否可以设定跳过数据库存储消息这个过程，直接由kafka/rabbitmq将消息发送出去。

**Comment by yuleyule66** [comment]
这不是CAP的职责。

这种情况不需要使用CAP，自己简单封装一下MQ的客户端即可。

**Comment by chrcao** [comment]
@yuleyule66 cap已经封装了MQ的调用方式，如果能支持就简便很多，不需要单独再做封装了。

**Comment by chenxjiao** [comment]
cap的目的是为了处理分布式事务，而不是为了简单的消息传递，如果你只需要一个订阅机制，那么不应该用CAP。
