### ISSUE TITLE
The tables of Cap.published and received cannot created

### ISSUE THREAD

**Issue by jimmy-1216** [dotnetcore/CAP#231]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of CAP, OS and .NET Core?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by jimmy-1216** [comment]
开发环境window10+vs2017+mysql+MQ，Cap.published and received 两张表无法生成

**Comment by BruceProject** [comment]
> 开发环境window10+vs2017+mysql+MQ，Cap.published and received 两张表无法生成

me too
