### ISSUE TITLE
CAP存在的缺陷及bug

### ISSUE THREAD

**Issue by zjlhope** [dotnetcore/CAP#234]
请允许我用中文描述一下，谢谢。
1.当前的消息发送将数据库登记和发送到MQ绑在了一起（见CapPublisherBase的PublishAsyncInternal方法），这样会有如下问题：我在A系统里面完成了本地的一个任务（不一定是数据库操作）或者事务提交，调用上面接口，接口先进行数据库登记，然后推送到MQ，这个过程如果数据库登记失败了（目前有一个异常抛出）或者准备数据库登记的时候系统挂了，但是你本地任务又完成了，导致没有地方可以查到本地当初做了什么，其他系统也再也收不到一个通知，虽然出现这个问题概率比较小。

**改进意见**：拆分数据库登记和发送到MQ，完成一个本地消息发送的步骤变成：a.数据库登记，b.完成本地任务（不一定会操作数据库哦）c.推送到MQ，同时想办法提供一个后台任务，扫描数据库，调用开发人员提供的回查接口，再决定是否发送到MQ,或者不用回查，由其他系统保证幂等

2.发现的一个bug.
IConsumerServiceSelector的默认实现DefaultConsumerServiceSelector里的SelectBestCandidate方法
MatchAsteriskUsingRegex和MatchPoundUsingRegex不能简单的通过判断_asteriskList == null或者_poundList == null然后复用缓存下来的list,因为key可能属于的group不一样，第一次调用该方法没问题，但是第二次调用传递的key可能和第一次调用的key所属的group不一样，导致第二次会从错误的缓存中寻找匹配的方法。

**改进意见**：这里判断要考虑group

**Comment by zjlhope** [comment]
> Hello, Thanks for your feedback, let me answer your question.
> 
> 以下我也用中文回答吧。
> 
> Question 1 : 你说的情况是可能的，但是一般情况下本地任务（单纯CPU计算，非数据库操作）一般不考虑这种情况，因为如果考虑这种情况，你调用的任何一个方法也都一样会存在这个问题，可能会执行到一半发生宕机或者停电。这种情况你可以将本地任务放在发送消息的前面，这样可以保证本地任务顺利执行完成。一般我们说的一致性，是不包含你说的这种本地任务（无状态的）这种情况的。
> 
> Question 2: 什么情况下，会第二次调用传递的key为什么和第一次的Group不一样呢？是怎么做得到呢？CAP是不支持消费端动态更换Group的。



> Hello, Thanks for your feedback, let me answer your question.
> 
> 以下我也用中文回答吧。
> 
> Question 1 : 你说的情况是可能的，但是一般情况下本地任务（单纯CPU计算，非数据库操作）一般不考虑这种情况，因为如果考虑这种情况，你调用的任何一个方法也都一样会存在这个问题，可能会执行到一半发生宕机或者停电。这种情况你可以将本地任务放在发送消息的前面，这样可以保证本地任务顺利执行完成。一般我们说的一致性，是不包含你说的这种本地任务（无状态的）这种情况的。
> 
> Question 2: 什么情况下，会第二次调用传递的key为什么和第一次的Group不一样呢？是怎么做得到呢？CAP是不支持消费端动态更换Group的。

以rabbitMQ为例，比如订阅时指定了队列的名称
 A订阅：   [CapSubscribe("#.rabbitmq.mysql")]，绑在方法A上
 B订阅：   [CapSubscribe("#.rabbitmq.mysql",Group ="zjlCap")]，绑在方法B上
发送消息：await _capBus.PublishAsync("test.rabbitmq.mysql", "this is test1")
这时候，消息的key是一样的，并且满足两个订阅的正则，现在这两个订阅写在一个系统里，部署的时候进程是同一个，那么调用方法时就会乱掉，本来应该调用A方法的可能会调用B方法，调用B方法的调用A方法，具体是第二次以后的调用会出问题，你看看代码就知道了，因为存在缓存复用。


**再提一个建议哈：
路由key能不能支持数字呢，现在只支持大小写字母**

**Comment by zjlhope** [comment]
其实简单理解，以rabbitmq为例，你用的topic交换机，两个group就有两个队列，会同时绑到这个交换机上，那么发送的消息会同时路由到这个队列上（当key同时满足时），那么那两个订阅的方法应该各调一次，因为group不一样，但现在做不到，除非这两个订阅拆分到两个系统里（因为缓存不会复用了）

**Comment by yang-xiaodong** [comment]
是的，我明白了你的意思，确实存在这个Bug。
我创建了一个新的 issue #235 来跟踪此问题

**Comment by yang-xiaodong** [comment]
> 路由key能不能支持数字呢，现在只支持大小写字母

能说明你的情况吗？曾经有人反馈过这个问题，但是我在 #181 没有重现。

**Comment by zjlhope** [comment]
希望加上消息确认功能，以rabbitMQ为例，发送的消息没有匹配到队列是不会报错的，而kafka上却不会有这种问题，rabbitMQ希望加上消息确认和打开return事件，在大并发时，这个很重要

**Comment by yang-xiaodong** [comment]
> 不支持数字的原因由以下代码引起：
> 
> 1. Name = ("^" + x.Attribute.Name + "$").Replace("*", "[a-zA-Z]+").Replace(".", "\."),
> 2. Name = ("^" + x.Attribute.Name + "$").Replace("#", "[a-zA-Z\.]+"),
> 
> 改进：
> [a-zA-Z]--->[0-9a-zA-Z]

你愿意提交一个PR来改进此问题吗？

**Comment by zjlhope** [comment]
> > 希望加上消息确认功能，以rabbitMQ为例，发送的消息没有匹配到队列是不会报错的，而kafka上却不会有这种问题，rabbitMQ希望加上消息确认和打开return事件，只有消息真的保存到了MQ，数据库才标记完成，在大并发时，这个很重要哦
> 
> 你是指的发送端的消息确认? 消费端 RabbitMQ和Kafka都具有确认功能。
> 
> 发送端的消息确认如果是事务消息，是和数据库本地事务在一个Transaction，所以不存在你说的问题。
> 
> 如果你指的是发送端本地消息到消息队列的这个过程，我们是不考虑这种情况的，因为一般情况下，消息队列发生宕机或者连接不上，我们都会收到消息，而针对你说的匹配不到队列的问题，是CAP的使用者需要考虑的问题。
> 
> 如果考虑发送端确认这会导致几个问题：
> 
> 1. 发送端的吞吐量会显著降低。
> 2. 数据库操作会变得很多，进一步降低性能。
> 3. 逻辑结构变得复杂，CAP主要是考虑轻量级和性能问题。

嗯。我指的是本地到MQ的过程，其实加上确认，只要不是同步等待的方式性能其实还好，oneway发的方式虽然快，但生产环境，有些linux系统优化不到位，会存在接受了消息没落盘的情况，我在rocketMQ中测试过。rocketMQ生产环境非日志型的消息基本会有确认机制，如果集群部署，tps就上去啦

**Comment by zjlhope** [comment]
> > 不支持数字的原因由以下代码引起：
> > 
> > 1. Name = ("^" + x.Attribute.Name + "$").Replace("*", "[a-zA-Z]+").Replace(".", "."),
> > 2. Name = ("^" + x.Attribute.Name + "$").Replace("#", "[a-zA-Z.]+"),
> > 
> > 改进：
> > [a-zA-Z]--->[0-9a-zA-Z]
> 
> 你愿意提交一个PR来改进此问题吗？

可以，针对#235我一块改了把

**Comment by yang-xiaodong** [comment]
@zjlhope  可以的，但是你本地需要开2个分支，并提交2个PR，以便于我们一个PR跟踪一个issue。
有几点需注意：
1. 提交PR的Commit需要使用英文呢
2. PR需要关联issue。 这两个PR分别关联 #235 #181  在提交PR的时候需要关联一下。

**Comment by zjlhope** [comment]
> @zjlhope 可以的，但是你本地需要开2个分支，并提交2个PR，以便于我们一个PR跟踪一个issue。
> 有几点需注意：
> 
> 1. 提交PR的Commit需要使用英文呢
> 2. PR需要关联issue。 这两个PR分别关联 #235 #181  在提交PR的时候需要关联一下。

好的。

**Comment by zjlhope** [comment]
> @zjlhope 可以的，但是你本地需要开2个分支，并提交2个PR，以便于我们一个PR跟踪一个issue。
> 有几点需注意：
> 
> 1. 提交PR的Commit需要使用英文呢
> 2. PR需要关联issue。 这两个PR分别关联 #235 #181  在提交PR的时候需要关联一下。

**Comment by yjqGitHub** [comment]
我想问下 在使用RabbitMQ当作中间件的时候，当发生网络闪断的时候，监听者会自动重新对原先的Topic进行监听吗？我看代码当中好像没有这块处理。Connection会自动重新连接，但是不会自动对Topic进行绑定监听吧？

**Comment by yjqGitHub** [comment]
> @yjqGitHub
> Topic的绑定是在RabbitMQ服务端的Exchange上，只要建立连接就会推送

我在代码上看到客户端监听是绑定在channel上面，当Connection断开的时候，这个channel也会被释放的吧。然后当你重新自动连接上了Connection，那么此时客户端监听也会自动生效吗？
