### ISSUE TITLE
Are there any plans to support other MQ, such as NetMQ?

### ISSUE THREAD

**Issue by huazhenhz** [dotnetcore/CAP#236]
Besides Rabbit MQ and Kafka, I'm looking forward that CAP can support other Message Queues which are implemented in .NET Core, such as NetMQ.
So I wonder whether there are any relevant plans in the future...

I hope .NET Core can have an entire Solution to Distributed Transaction which doesn't depend on the technical platforms based on other languages like Java, Erlang.

That's only my personal advice and expectation.
Thanks a lot!

The reference website about NetMQ:
https://github.com/zeromq/netmq
https://netmq.readthedocs.io/en/latest/

**Comment by yang-xiaodong** [comment]
@huazhenhz  I don't have much energy to maintain support for many message queues. You can extend the CAP with reference to the current implementation of the message queue, and open source as a community-supported extension project. I would like to link your project at the CAP's home page. Would you like to do it?
