### ISSUE TITLE
负载均衡之后如何防止消息被重复发送？

### ISSUE THREAD

**Issue by BennetWang** [dotnetcore/CAP#239]
负载均衡之后如何防止消息被重复发送？以前的版本我记得是用的是一个数据库队列，还是说对于本来需要轮询发送的消息本来就少，重复发送这点消耗被忽略掉？

**Comment by yang-xiaodong** [comment]
What did you mean about load balancing publish message repeated? You means failed message ?

**Comment by BennetWang** [comment]
是的，当消息失败重试时，由于部署多台机子，可能会对消息进行重复发送，没看到锁或者其它协调机制存在

**Comment by yang-xiaodong** [comment]
This leads to additional complexity, such as distributed lock or database lock, so we didn't consider about it. Because consumers need to ensure idempotency

**Comment by zjlhope** [comment]
我认为，只要使用消息中间件，应用如果对重复消费敏感，就需要应用自己做幂等，没有消息中间件会做仅发送一次的保证。消费重复可能和生产端有关，也可能和消费端有关，但集中在消费端做幂等会简单很多

**Comment by yang-xiaodong** [comment]
Yes, I agree with you

**Comment by BennetWang** [comment]
非常感谢。。明白了。。
