### ISSUE TITLE
can the message support persistence when use rabbitmq?

### ISSUE THREAD

**Issue by zjlhope** [dotnetcore/CAP#240]
Now,the message be sended to mq without persistence support when use rabbitmq，I hope to support it

**Comment by yang-xiaodong** [comment]
I just looked at the documentation [here](https://www.rabbitmq.com/tutorials/tutorial-two-python.html)., you are right , when send the message, also need to specify `delivery_mode` again. but  I did some tests several months ago, I found that it can still persistence the message without specifying this value. What have I missed?

**Comment by zjlhope** [comment]
> I just looked at the documentation [here](https://www.rabbitmq.com/tutorials/tutorial-two-python.html)., you are right , when send the message, also need to specify `delivery_mode` again. but I did some tests several months ago, I found that it can still persistence the message without specifying this value. What have I missed?

non persistence message can still save to disk temporarily when the memory used by mq reached the vm_memory_high_watermark_paging_ratio*vm_memory_high_watermark value，but when you restart mq，these messages can miss.

**Comment by yang-xiaodong** [comment]
fixed in v2.4.0
