### ISSUE TITLE
如何统一执行事务操作

### ISSUE THREAD

**Issue by 2821840032** [dotnetcore/CAP#243]
在看完并跑完一些案例后，CAP给我的感觉就像是一个没有返回值并且无状态的RPC，如果些案例就是我了解的全部。
我有一个需求：
用户在订单服务单击确认订单后，进入确认订单流程，
首先访问用户服务，检查余额是否足够，如果不够如何通知订单服务回滚事务？足够的话如何等待其他服务调用完成然后统一执行事务？
商品服务也是一样的，检查库存，不够如何回滚用户服务的操作？通过的话如何通知用户服务执行事务？

其实问题就两个
1、如何统一执行事务
2、如何统一回滚事务

我没有找到相关的教程或者案例。

**Comment by zjlhope** [comment]
> 在看完并跑完一些案例后，CAP给我的感觉就像是一个没有返回值并且无状态的RPC，如果些案例就是我了解的全部。
> 我有一个需求：
> 用户在订单服务单击确认订单后，进入确认订单流程，
> 首先访问用户服务，检查余额是否足够，如果不够如何通知订单服务回滚事务？足够的话如何等待其他服务调用完成然后统一执行事务？
> 商品服务也是一样的，检查库存，不够如何回滚用户服务的操作？通过的话如何通知用户服务执行事务？
> 
> 其实问题就两个
> 1、如何统一执行事务
> 2、如何统一回滚事务
> 
> 我没有找到相关的教程或者案例。

如果直接回滚，目前很少分布式事务这么干的，太复杂，可以间接通过新开一个事务来解决，就是发一个撤销的事务操作，其他服务订阅处理。
先后顺序性，通过传递callbackName参数解决

**Comment by 2821840032** [comment]
你的意思是需要保存事务对象并且在发布消息的时候带上这个事务ID，并由订阅服务发布消息决定回滚还是执行？如果是这样的话我感觉还需要对CAP进行一次封装。我以为CAP会封装好这一块的，没想到只是做了通讯层的封装。
感谢的你回复。

**Comment by zjlhope** [comment]
发布消息时，你消息体带个ID，一般就是业务ID，需要“回滚”时，发布一条新的消息，消息体含有业务ID，其他程序订阅这个回滚主题，进而处理

**Comment by 2821840032** [comment]
太感谢你了，解决了我的麻烦。
