### ISSUE TITLE
两个服务，只启用一个dashboard的情况下。未启用dashboard的服务会因为cap/health失败，无法在consul注册。

### ISSUE THREAD

**Issue by Shinetaku** [dotnetcore/CAP#248]
如题

**Comment by yang-xiaodong** [comment]
yes, It's an expect desgin

**Comment by Shinetaku** [comment]
那和之前去中心化的设计不一致了。多个服务多个dashboard。每个服务都有自己的dashboard，切换目标实例的意义就不大了啊。

**Comment by yang-xiaodong** [comment]
Dashboard 提供路由中间件查询数据，要不然数据从哪里来？配置一下Dashboard并不会带来额外的性能开销

**Comment by yang-xiaodong** [comment]
为什么没有意义？ 在集群环境下，通过反向代理暴漏一个地址到外网，然后通过这个地址就可以看所有的了，要不然你每个实例配置一个地址，挨个点开看?

**Comment by Shinetaku** [comment]
就是因为在某一个服务下可以看到所有的信息，所以不需要每个服务都开启dashboard了。各服务只需要开启discovery就可以了。具体指定哪个服务开启dashboard就ok了。现在是dashboard和discovery绑在一起，要开discovery就必须要开dashboard。感觉这样不是很合理。
