### ISSUE TITLE
Missing figure in readme.md

### ISSUE THREAD

**Issue by StarkShang** [dotnetcore/CAP#249]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
The figure, cap.png, in File readme.md cannot be loaded, which is also occur in Chinese version. 
___
### Bug
- Which version of CAP, OS and .NET Core?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yang-xiaodong** [comment]
I can't reproduce, I can see it
