### ISSUE TITLE
cap在Publish完成之后published表和received表状态为Scheduled

### ISSUE THREAD

**Issue by yhxwyzm** [dotnetcore/CAP#251]
cap版本是2.3.1
.net Core版本是2.2
DotNetCore.CAP.RabbitMQ 2.3.1

- [x] Question or discussion

        [HttpGet("WithoutTransaction")]
        public IActionResult WithoutTransaction()
        {
            _capBus.PublishAsync(QueueMessage.MessageProcessing,
                new QueueMessage
                {
                    MessageType = MessageType.叫料,
                    MessageObject = "消息内容！"
                }, DateTimeOffset.Now.ToString());
            return Ok("发送");
        }

        [HttpGet("CheckReceivedMessage")]
        [CapSubscribe(QueueMessage.MessageProcessing)]
        public IActionResult CheckReceivedMessage()
        {
            return Ok("订阅者");
        }

而且在published表中会直接出现两条数据

![unnamed](https://user-images.githubusercontent.com/37857613/49844932-ae721500-fdff-11e8-85e5-409885c9fd86.png)

以下是配置文件

![unnamed](https://user-images.githubusercontent.com/37857613/49844985-d3ff1e80-fdff-11e8-822f-c756e12ef19d.jpg)

**Comment by yang-xiaodong** [comment]
Is your MongoDB is 4.0+ cluster?

**Comment by yhxwyzm** [comment]
> Is your MongoDB is 4.0+ cluster?

 is 3.4

**Comment by yang-xiaodong** [comment]
Only MongoDB  4.0+ cluster are support ACID transaction, see https://www.mongodb.com/blog/post/mongodb-multi-document-acid-transactions-general-availability

**Comment by yhxwyzm** [comment]
> Only MongoDB 4.0+ cluster are support ACID transaction, see https://www.mongodb.com/blog/post/mongodb-multi-document-acid-transactions-general-availability

thx，Let me check it out.

**Comment by yhxwyzm** [comment]
> Only MongoDB 4.0+ cluster are support ACID transaction, see https://www.mongodb.com/blog/post/mongodb-multi-document-acid-transactions-general-availability

why Cap.Published table Two data appear.
Is the second data a log?

**Comment by yang-xiaodong** [comment]
we suggest you using lasted version to reproduce the problem

**Comment by yang-xiaodong** [comment]
Here is an example about how to using CAP in mongodb:
https://github.com/dotnetcore/CAP/blob/develop/samples/Sample.RabbitMQ.MongoDB/Controllers/ValuesController.cs
