### ISSUE TITLE
请问cap如何用cousel配置UseDashboard

### ISSUE THREAD

**Issue by 3zengzz** [dotnetcore/CAP#257]
您在项目里只提了cap本地的配置，然后说安装cousel，就没有具体的步骤，应该如何配置cousel实现，多个Dashboard切换查看

**Comment by yang-xiaodong** [comment]
https://learn.hashicorp.com/consul/getting-started/install
```
// Register to Consul
    x.UseDiscovery(d =>
    {
        d.DiscoveryServerHostName = "localhost";
        d.DiscoveryServerPort = 8500;
        d.CurrentNodeHostName = "localhost";
        d.CurrentNodePort = 5800;
        d.NodeId = 1;
        d.NodeName = "CAP No.1 Node";
    });
```

**Comment by 3zengzz** [comment]
你好，我配置了，但是链接无法跳转

**Comment by 3zengzz** [comment]
在cap 的节点列表页出现了2个服务器列表，但是淡季其中一个节点的切换连接的时候，无法切换，我看了源码似乎没有跳转呀这个方法：

**Comment by 3zengzz** [comment]
@foreach (var node in Nodes)
                    {
                        <tr class="@(CurrentNodeId == node.Id ? "active" : null)">
                            <td>@node.Id</td>
                            <td>@node.Name</td>
                            <td>@node.Address</td>
                            <td>@node.Port</td>
                            <td>@node.Tags</td>
                            <td>
                                @Html.NodeSwitchLink(node.Id)
                            </td>
                        </tr>
                    }

**Comment by yang-xiaodong** [comment]
Clicking on “switch” button is not a jump link, it used to set the current context variable to target node so that subsequent requests can be forwarded.

**Comment by 3zengzz** [comment]
那单击之后没有效果是什么原因呢？是配置的问题吗？
