### ISSUE TITLE
can CAP support for RocketMQ？

### ISSUE THREAD

**Issue by xingwen1987** [dotnetcore/CAP#259]
请问咱们的 CAP 能对 RocketMQ 进行支持吗？
[RocketMQ 官网](http://rocketmq.apache.org/)
[第三方支持库](https://github.com/NewLifeX/NewLife.RocketMQ)

**Comment by yang-xiaodong** [comment]
会长，你可以搞个第三方CAP扩展啊，我给你首页加链接，我这没时间，而且用这个的太少

**Comment by xingwen1987** [comment]
> 会长，你可以搞个第三方CAP扩展啊，我给你首页加链接，我这没时间，而且用这个的太少

我这段时间忙过了，迅速上手杨总的代码，到时候杨总要全力支持我呀。

**Comment by yang-xiaodong** [comment]
@xingwen1987 anytime
