### ISSUE TITLE
请问有CAP学习群吗？

### ISSUE THREAD

**Issue by caspnet** [dotnetcore/CAP#26]
如题，因为小弟运行过程中有碰到一些问题，想在群里咨询各位大神，帮忙解决下，谢谢！

**Comment by yuleyule66** [comment]
你好，CAP没有群。 
原因是我希望培养大家独立思考和遇到问题时候的解决能力。
使用时候遇到问题先尝试看文档和独立解决，如果解决不了，可以提ISSUE或者发邮件。
QQ群有效沟通太低，浪费时间。
