### ISSUE TITLE
Is there an api to compress content data

### ISSUE THREAD

**Issue by Shinetaku** [dotnetcore/CAP#262]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ x] Requirement
- [ ] Feature or performance improvement

___
### Requirement or improvement
- whether you can consider adding compressed data API in the transmission of big data, ex: gzip
能否加入数据压缩的API，或自定义Provider的入口，如Gzip

**Comment by yang-xiaodong** [comment]
Sorry, I can't catch your point.

**Comment by Shinetaku** [comment]
传输过程中的数据较大，能否启用压缩进行数据传输。比如使用gzip协议。

**Comment by yang-xiaodong** [comment]
Sure, you can customize `IContentSerializer` interface at `DotNetCore.CAP.Abstractions` namespace.

Then, configure like this:
```
services.AddCap(x => { }).AddContentSerializer<MyContentSerializer>();
```
