### ISSUE TITLE
取消usecap后，cap的启动时机不合适

### ISSUE THREAD

**Issue by chaiziqi** [dotnetcore/CAP#263]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [√ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
取消usecap扩展方法后，cap的启动时机不合适，开发者不能根据自身情况自由的选择cap启动的时间。比我们采用了ABP等开发框架的项目，业务类注入到IOC容器的时机并非在ConfigureServices内，而是延后处理的，在2.3.1版本以前我们可以在框架将IOC容器初始化完毕后，再调用Usecap扩展方法灵活启用，现在却做不到了。您可能会建议我们把IOC容器初始化的时机提前到AddCap之前，但是像ABP这类的框架在初始化IOC容器时，由于没有注入Publisher接口的实现，那么对于依赖了IPublisher接口的业务类，又会因为没有满足IPublisher这个依赖而无法实现初始化，也就是循环依赖的。
      综上所述，考虑实际应用技术栈的复杂项和cap的普适性，能否保留显式的usecap方法供开发者自主决定开启时间，您可以采用隐式默认的在addcap中启用呢？
___
### Bug
- Which version of CAP, OS and .NET Core?
 .NET Core  ABP开发框架
- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yang-xiaodong** [comment]
> ABP这类的框架在初始化IOC容器时，由于没有注入Publisher接口的实现，那么对于依赖了IPublisher接口的业务类，又会因为没有满足IPublisher这个依赖而无法实现初始化，也就是循环依赖的

这个没看懂？ `没有注入Publisher接口的实现` 是什么意思？ CAP 不要求使用者实现什么Publisher接口

**Comment by chaiziqi** [comment]
是这样的：

我理解cap确实不要求使用者实现IPublisher接口，cap是在AddServices时自己内部注入了例如SqlServerPublisher对象的，这没有问题。

但是我们的应用程序某一个类classA。它在发送消息时是需要在构造函数内注入IPublisher这个接口的，而classA实际应用中还需要依赖很多其他接口，如IRepository和IUnitOfWork，更为关键的classA可能还是一个Consumer。对于cap2.3.0以后的版本，要求我们必须先向IOC注入Consumer，然后addCap时cap内部会调用ConsumerHandler.Start()并解析ICapSubscribe的实现类，进而开始消费监听。

所以我们向IOC注入classA时必须先满足如IPublisher、IRepository和IUnitOfWork等一大堆接口依赖，那么由于在addcap之前还没有注入IPublisher的实现SqlServerPublisher，所以造成了循环依赖，除非我们必须把Consumer方法从classA单独移除到另一个类classB。

即使把Consumer的订阅方法单独摘除了classB，往往classB也是需要依赖IRepository和IUnitOfWork等很多接口的，至于像ABP这类框架，它是采用约定大于配置的方式向IOC注入的。放在addcap之后注入IOC，classB依赖的IRepository和IUnitOfWork等无法被满足。放在addcap之前注入IOC，classA的IPublisher还是无法被满足。

在2.3.0版本以前，我可以在所有对象都被注入到IOC之后再usecap()启动cap，而现在我无法控制

**Comment by yang-xiaodong** [comment]
难道 Abp IOC的注册时间，比 Microsoft.AspNetCore.Hosting 的 `IStartupFilter` 还要晚？ 是在 `public void Configure()` 里面？

**Comment by yang-xiaodong** [comment]
现在CAP的启动时间是，先启动CAP然后开始执行在 `Configure` 中注册的中间件。

```cs
sealed class CapStartupFilter : IStartupFilter
{
    public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
    {
        return app =>
        {
            app.UseCap();

            next(app);
        };
    }
}
```

**Comment by chaiziqi** [comment]
没错，ABP是在 public void Configure() 里面，框架提供UseAbp来启动这个ABP框架加载的

**Comment by chaiziqi** [comment]
所以从cap普适性的角度来考虑，由于我们不能完全确定开发者所采用的框架和机制，希望能保留usecap()显示开启cap，或者有更合理的办法，当然因为不了解取消usecap的初衷，可能需要您综合考虑。

**Comment by yang-xiaodong** [comment]
那Abp这个设计真的丑陋，违反了 ASP.NET Core 的最佳实践，不在正确的时间干正确的事，是一个反模式。

你先试试这样调整代码看看行不行？
```
return app =>
{
     next(app);    
    app.UseCap();     // 调整到后面
};
```

**Comment by chaiziqi** [comment]
我试过了，很遗憾仍然无法解决

**Comment by yang-xiaodong** [comment]
我们将尝试改进启动CAP的方式，见 #265

**Comment by chaiziqi** [comment]
非常感谢！

**Comment by smilecoder** [comment]
> 那Abp这个设计真的丑陋，违反了 ASP.NET Core 的最佳实践，不在正确的时间干正确的事，是一个反模式。
> 
> 你先试试这样调整代码看看行不行？
> 
> ```
> return app =>
> {
>      next(app);    
>     app.UseCap();     // 调整到后面
> };
> ```

最佳实践准备工作与启用是2个不同的操作，由开发来决定顺序的，现在cap的设计我觉得才是丑陋的
