### ISSUE TITLE
Dashboard sql query bug of using SQLServer

### ISSUE THREAD

**Issue by xueandfeng** [dotnetcore/CAP#266]
消息搜索直接页面报错。追踪了代码。https://github.com/dotnetcore/CAP/blob/develop/src/DotNetCore.CAP.SqlServer/IMonitoringApi.SqlServer.cs#L84
数据库关键字。希望修复下

**Comment by yang-xiaodong** [comment]
@xueandfeng  Hi, thanks for your feedback , would you like to submit a PR to fix this bug?

**Comment by yang-xiaodong** [comment]
Fixed in v2.4.2, released!
