### ISSUE TITLE
app.UseCap()提示未包含定义？看源码也没有UseCap()

### ISSUE THREAD

**Issue by haihaigo** [dotnetcore/CAP#269]
你好，app.UseCap()提示未包含定义？看源码也没有UseCap()

**Comment by yang-xiaodong** [comment]
see https://www.cnblogs.com/savorboard/p/cap-2-3.html#%E7%A7%BB%E9%99%A4%E4%BA%86cap-%E4%B8%AD%E9%97%B4%E4%BB%B6%E6%B3%A8%E5%86%8C

**Comment by haihaigo** [comment]
速度很快，谢谢。
