### ISSUE TITLE
[V2.4.2 ConsoleApp]No service for type 'DotNetCore.CAP.IBootstrapper' has been registered.

### ISSUE THREAD

**Issue by BenDerPan** [dotnetcore/CAP#275]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [√] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I try to build a console app with cap, I tested with advices of  #75 #111 #127 .  and it works with version2.3.1(with no params in `container.GetRequiredService<IBootstrapper>().BootstrapAsync()`), but exception with version 2.4.1.

___
### Bug
- Which version of CAP, OS and .NET Core?
.net core 2.2.102  
- Which company or project?
None, Just personal test.
- What happen?
it works with version2.3.1(with no params in `container.GetRequiredService<IBootstrapper>().BootstrapAsync()`), but exception with version 2.4.1

```
Unhandled Exception: System.InvalidOperationException: No service for type 'DotNetCore.CAP.IBootstrapper' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)

```

my test code:
```C#
static void Main(string[] args)
        {
            var ioc = new ServiceCollection();
            ioc.AddLogging();
            ioc.AddSingleton<IDemoSub,DemoSubscriber>();
            ioc.AddSingleton<IApplicationLifetime, ApplicationLifetime>();
            ioc.AddCap(x =>
            {
                x.UseMySql("Server。。。");
                x.UseRabbitMQ(rabbitmqOptions =>
                {
                    。。。
                });
                x.FailedRetryCount = 5;
                x.FailedThresholdCallback = (type, name, content) =>
                {
                    Console.WriteLine($@"[Error]A message of type {type} failed after executing {x.FailedRetryCount} several times, requiring manual troubleshooting. Message name: {name}, message body: {content}");
                };
                
            });
            var container = ioc.BuildServiceProvider();
          
            var cancel = new CancellationToken();
            //Exception here!!!!!
            container.GetRequiredService<IBootstrapper>().BootstrapAsync(cancel);

            container.GetService<ILoggerFactory>()
                .AddConsole(LogLevel.Debug);
            var logger = container.GetService<ILoggerFactory>().CreateLogger<Program>();
            logger.LogInformation("Start App...");
            
            var pub = container.GetService<ICapPublisher>();
            pub.PublishAsync("aaa.test.mysql", "HI");

            Console.WriteLine("Finished!");
            Console.ReadLine();
```

**Comment by yang-xiaodong** [comment]
In version 2.4.2, we optimized the CAP startup mode, we are using the `IHostedService` provided by .NET Core now, so it needs to be able to run normally with the hosted service.

In the Console App, you can use CAP like this:

**Program.cs**
```cs
public static async Task Main(string[] args)
{
     await new HostBuilder()
       .UseEnvironment("Development")
       .ConfigureLogging((hostContext, configLogging) =>
       {
           configLogging.AddConsole();
           configLogging.AddDebug();
       })
       .ConfigureServices((hostContext, services) =>
        {
            //This is your console background service, I named `PublishMessageEvery5Seconds` here
            services.AddHostedService<PublishMessageEvery5Seconds>();

            services.AddDbContext<AppDbContext>();
            services.AddCap(x =>
            {
                x.UseEntityFramework<AppDbContext>();
                x.UseRabbitMQ("localhost");
                x.FailedRetryCount = 5;
            });
        })
       .RunConsoleAsync();
}
```

**PublishMessageEvery5Seconds.cs**
```cs
public class PublishMessageEvery5Seconds : IHostedService, ICapSubscribe
{
    private Timer _timer;
    private readonly ICapPublisher _eventBus;
    private readonly ILogger _logger;

    public PublishMessageEvery5Seconds(ICapPublisher eventBus,
        ILogger<PublishMessageEvery5Seconds> logger)
    {
        _eventBus = eventBus;
        _logger = logger;
    }

    public Task StartAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("Timed Background Service is starting.");

        _timer = new Timer(Publish, null, TimeSpan.Zero,
            TimeSpan.FromSeconds(5));

        return Task.CompletedTask;
    }

    private void Publish(object state)
    {
        _eventBus.Publish("sample.rabbitmq.mysql.test", DateTime.Now);
    }

    [CapSubscribe("sample.rabbitmq.mysql.test")]
    public void Subscribe(DateTime time)
    {
        Console.WriteLine($@"{DateTime.Now}, Subscriber invoked, Sent time:{time}");
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("Timed Background Service is stopping.");
        _timer?.Change(Timeout.Infinite, 0);
        return Task.CompletedTask;
    }
}
```

please let me know if you need any further information.

**Comment by BenDerPan** [comment]
@yang-xiaodong thanks, great help 👍

**Comment by KondratenkoAndrey** [comment]
Hello!
I try to use CAP in consoleApp
When i try to resolve dependency of ICapPublisher i get an exception:

`System.InvalidOperationException: "No service for type 'DotNetCore.CAP.ICapPublisher' has been registered.`

```c#
public static void Main(string[] args)
{
    var services = new ServiceCollection();
    services.AddCap(x =>
    {
        x.UseRabbitMQ("localhost");
    });
    var provider = services.BuildServiceProvider();
    var eventBus = provider.GetRequiredService<ICapPublisher>(); //<- exception
}
```
What i'm doing wrong?

**Comment by yang-xiaodong** [comment]
@KondratenkoAndrey 
You are missing a configuration item for the database

```c#
services.AddCap(x => {
   x.UseRabbitMQ("localhost");
   x.UseSqlServer() // missing
});
```

**Comment by KondratenkoAndrey** [comment]
> @KondratenkoAndrey
> You are missing a configuration item for the database
> 
> ```cs
> services.AddCap(x => {
>    x.UseRabbitMQ("localhost");
>    x.UseSqlServer() // missing
> });
> ```

Welcome! Thanks for the reply!

From description is not obvious that the database is required.
If I understand correctly, it is used exclusively for logging, right?
If it is true, I might want to use a different logging, or use not supported database, so the built-in logging will probably need to make optional.

**Comment by yang-xiaodong** [comment]
@KondratenkoAndrey 
We use logging to ensure that messages are not lost and that messages and business code are in one transaction, not just for logging.

For example, when an order is created and a message needs to be sent to the message queue, if the order is created successfully but fails when the message is sent, this will result in an error in data consistency.

**Comment by KondratenkoAndrey** [comment]
I see. thank you.
And i have one more question - How should I prepare the postgres database?
When i try to publish message, i get an db error: 
`ERROR:  relation "cap.published" does not exist at character 13`

**Comment by yang-xiaodong** [comment]
@KondratenkoAndrey 
The best way to get started is to create an asp.net core project instead of the console project.

**Comment by qgxcry** [comment]
> ```cs
> services
> ```

I use Orleans.Hosting.ISiloHost,How to using CAP in Orleans?
        private static async Task<ISiloHost> InitialiseSilo()
        {

            var builder = new SiloHostBuilder()
                // Membership
                .UseAdoNetClustering(options =>
                {
                    options.Invariant = Invariant;
                    options.ConnectionString = ConnectionString;
                })
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = ClusterId;
                    options.ServiceId = ServiceId;
                })
                .ConfigureEndpoints(siloPort: 11111, gatewayPort: 30000)
                .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(DemoGrain).Assembly).WithReferences())
                .ConfigureLogging(log => log.SetMinimumLevel(LogLevel.Warning).AddConsole());

            var host = builder.Build();
            await host.StartAsync();

            return host;
        }

**Comment by duyanming** [comment]
mark

**Comment by virtualbiz** [comment]
> In version 2.4.2, we optimized the CAP startup mode, we are using the `IHostedService` provided by .NET Core now, so it needs to be able to run normally with the hosted service.
> 
> In the Console App, you can use CAP like this:
> 
> **Program.cs**
> 
> ```cs
> public static async Task Main(string[] args)
> {
>      await new HostBuilder()
>        .UseEnvironment("Development")
>        .ConfigureLogging((hostContext, configLogging) =>
>        {
>            configLogging.AddConsole();
>            configLogging.AddDebug();
>        })
>        .ConfigureServices((hostContext, services) =>
>         {
>             //This is your console background service, I named `PublishMessageEvery5Seconds` here
>             services.AddHostedService<PublishMessageEvery5Seconds>();
> 
>             services.AddDbContext<AppDbContext>();
>             services.AddCap(x =>
>             {
>                 x.UseEntityFramework<AppDbContext>();
>                 x.UseRabbitMQ("localhost");
>                 x.FailedRetryCount = 5;
>             });
>         })
>        .RunConsoleAsync();
> }
> ```
> 
> **PublishMessageEvery5Seconds.cs**
> 
> ```cs
> public class PublishMessageEvery5Seconds : IHostedService, ICapSubscribe
> {
>     private Timer _timer;
>     private readonly ICapPublisher _eventBus;
>     private readonly ILogger _logger;
> 
>     public PublishMessageEvery5Seconds(ICapPublisher eventBus,
>         ILogger<PublishMessageEvery5Seconds> logger)
>     {
>         _eventBus = eventBus;
>         _logger = logger;
>     }
> 
>     public Task StartAsync(CancellationToken cancellationToken)
>     {
>         _logger.LogInformation("Timed Background Service is starting.");
> 
>         _timer = new Timer(Publish, null, TimeSpan.Zero,
>             TimeSpan.FromSeconds(5));
> 
>         return Task.CompletedTask;
>     }
> 
>     private void Publish(object state)
>     {
>         _eventBus.Publish("sample.rabbitmq.mysql.test", DateTime.Now);
>     }
> 
>     [CapSubscribe("sample.rabbitmq.mysql.test")]
>     public void Subscribe(DateTime time)
>     {
>         Console.WriteLine($@"{DateTime.Now}, Subscriber invoked, Sent time:{time}");
>     }
> 
>     public Task StopAsync(CancellationToken cancellationToken)
>     {
>         _logger.LogInformation("Timed Background Service is stopping.");
>         _timer?.Change(Timeout.Infinite, 0);
>         return Task.CompletedTask;
>     }
> }
> ```
> 
> please let me know if you need any further information.

This sample code doesn't work anymore. Got the error that IStorage can't be resolved. The source code of RabbitMQ implementation does't seem to inject IStorage either.
