### ISSUE TITLE
python integration support

### ISSUE THREAD

**Issue by BenDerPan** [dotnetcore/CAP#278]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirement
- [√] Feature or performance improvement

___
### Question
- if the subscribe or publish operation is coming from python client(other client languages), how can I Integrated  it with cap? Especially with 'callbackName' feature, any advices is much help, thanks

**Comment by yang-xiaodong** [comment]
There is no official implementation of any language other than C#

**Comment by yang-xiaodong** [comment]
Of course, If you are willing to do a community CAP extension, I am happy to help, you can check the format description of the message here, and I suggest you use the second way.

https://github.com/dotnetcore/CAP/wiki/5.%E5%AE%9E%E7%8E%B0#52-%E6%B6%88%E6%81%AF%E6%A0%BC%E5%BC%8F

**Comment by BenDerPan** [comment]
thanks, trying

**Comment by yang-xiaodong** [comment]
Hello , Is there any progress on this project?

I will close this issue and open it when needed

**Comment by BenDerPan** [comment]
@yang-xiaodong  too much work to do now, I am lack of free time to do that :(
