### ISSUE TITLE
使用Castle.Windsor.MsDependencyInjection,dashboard访问不了

### ISSUE THREAD

**Issue by huangz888** [dotnetcore/CAP#280]
我用了第三方的DI容器Castle.Windsor.MsDependencyInjection。消息队列没有问题，但访问DashBoard时候报错。跟踪源码发现是在MiddleWare里面，HttpContext.RequestService没有赋值

**Comment by yang-xiaodong** [comment]
We currently not testing the third-party DI, if you are interested you can submit a PR, thanks your feedback

**Comment by huangz888** [comment]
已解决这个问题，如果使用Castle.Windsor,需要在Container.Resolve(serviceType)时候，微软DI，如果没有注入，会返回null，而castle是抛异常。所以需要在之前，需要判断有没有注入，没有的话，返回null。第二就是插入一个自定义MiddleWare，在GatewayProxyMiddleware和DashboardMiddleware之前执行。自定义MIddleWare，手动给HttpContext.RequestService赋值。代码片断如下：
      public object GetService(Type serviceType)
        {
            try
            {
                if (IsEnumerable(serviceType))
                    return GetServices(serviceType);
                if (Common.IocHasRegister(serviceType))
                {
                    return Container.Resolve(serviceType);
                }
                return null;
            }
            catch (Exception ex)
            {
                Logger.Error("服务失败", ex);
                throw;
            }
        }

  public class PerWebRequestLifestyleMiddleware
    {
        private readonly RequestDelegate _next;
        /// <summary>
        /// 构造函数
        /// </summary>
        /// <param name="next"></param>
        public PerWebRequestLifestyleMiddleware(RequestDelegate next)
        {
            _next = next;
        }
        /// <summary>
        /// 执行
        /// </summary>
        /// <param name="context"></param>
        /// <param name="provider"></param>
        /// <returns></returns>
        public Task Invoke(HttpContext context,IServiceProvider provider)
        {
            context.RequestServices = provider;
            // Call the next delegate/middleware in the pipeline
            return _next(context);
        }
    }
}
