### ISSUE TITLE
Is there any template for zabbix to monitor CAP

### ISSUE THREAD

**Issue by kexxxfeng** [dotnetcore/CAP#281]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?
I'd like to monitor CAP via zabbix instead of the dashboard of CAP. Have anyone ever have a template?
___
### Bug
- Which version of CAP, OS and .NET Core?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.
If not, I'll try to create one myself.

**Comment by yang-xiaodong** [comment]
As far as I know, there are currently no related plugins of zabbix . If you are willing to provide it, that would be great. Please let me know if you need any help.
