### ISSUE TITLE
Exception in Dashboard

### ISSUE THREAD

**Issue by kexxxfeng** [dotnetcore/CAP#283]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of CAP, OS and .NET Core?
 CAP 2.4.2 for MongoDB
 Linux
 .NET Core 2.2

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.
 There was an error in Chrome console on accessing Dashboard and, nothing displayed in graph.
```
Uncaught stacked series cannot have differing numbers of points: 24 vs 25; see Rickshaw.Series.fill()
```
It's in MongoDB only, others are ok.
___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yang-xiaodong** [comment]
@kexxxfeng  I can't reproduce your exception, it works well in my environment.

 `Rickshaw.Series.fill()`  It looks like the third-party library's exception ?

**Comment by kexxxfeng** [comment]
Previously, the error was in both development environment and production environment.
And now it works well in development environment, but in production environment.
I have to debug in my production environment. 
Thanks for your response.
