### ISSUE TITLE
一个group(Queue)可以有多个Consumer吗？

### ISSUE THREAD

**Issue by onzz1900** [dotnetcore/CAP#286]
如题，一个group(Queue)可以有多个Consumer吗？如何配置？谢谢。

**Comment by yang-xiaodong** [comment]
Hello, 

Group is a consumer side concept. Topic and Queue are equivalent in CAP. A Topic will create a Queue at the MQ. If a Topic wants to be consumed by multiple consumers, you can set them with different group name. 

See more information [here](https://github.com/dotnetcore/CAP#subscribe-group).

**Comment by onzz1900** [comment]
thanks!
