### ISSUE TITLE
订阅服务无法正确消费数据

### ISSUE THREAD

**Issue by chaiziqi** [dotnetcore/CAP#288]
节日快乐！
我现在遇到一个问题，我的消费者服务是2个服务实例的集群，我发现有些业务数据无法被正确消费，received表中Retries=0，StatusName=Scheduled，而且我发现是每跳过一条数据会消费成功，每跳过一条数据就是失败，这让我怀疑是不是其中一个服务实例出现了什么问题？怎样能确认cap从received表解析数据的线程是正常运行的呢？或是可能有其它原因？
![image](https://user-images.githubusercontent.com/12622920/52993158-27b86480-344e-11e9-9faa-bfa9d22d4eee.png)

我的cap  版本是2.4.2，服务是docker部署在centos上，消息队列使用的rabbitmq

**Comment by yang-xiaodong** [comment]
检查日志是否正常了吗？

**Comment by chaiziqi** [comment]
两个实例连接的是同一个表，我把订阅者服务依次重启之后恢复了，但是问题原因比较奇怪，日志确实还没检查，我马上复查一下，另外交代一下cap和rabbitmq集群是通过阿里云负载均衡器的ip连接的，有负载均衡，我不清楚cap中订阅者集群是怎么协调只消费一次的，不确定是否相关。

**Comment by chaiziqi** [comment]
没错，我是两个完全一样的服务组成的双服务集群，所以是要一张表啊

**Comment by chaiziqi** [comment]
好的，我这面在留意一下此问题，非常感谢
