### ISSUE TITLE
Enable multiple consumer threads in a single instance

### ISSUE THREAD

**Issue by jakechan2012** [dotnetcore/CAP#295]
If CAP could give `prefetch` option, my consumers will not overload during high concurrently,
then I just need to raise up more consumers to solve the backlogs.

Is this a right way?

**Comment by yang-xiaodong** [comment]
I think that's a good idea, but I think we need to do consider the implementation of all message queues, not just RabbitMQ

**Comment by yang-xiaodong** [comment]
Hello @jakechan2012 ,

We supported this feature in in version `2.6.0-preview-80821564`. you can found `ConsumerThreadCount` configuration item in `CapOptions`.

Welcome your test feedback

Thanks
