### ISSUE TITLE
put prefixes in the parameters

### ISSUE THREAD

**Issue by xXjoakinXx** [dotnetcore/CAP#297]
https://github.com/dotnetcore/CAP/blob/0a1d6f802ef8d74363bb5cbed0a4a63bcc55da9b/src/DotNetCore.CAP.RabbitMQ/RabbitMQConsumerClient.cs#L106

Better to put prefixes in the parameters, it is more descriptive. Example:
```
_channel.QueueDeclare(_queueName, passive: true, durable: false, autoDelete: false, arguments);
```

**Comment by yang-xiaodong** [comment]
Can you submit a PR to fix ?

**Comment by xXjoakinXx** [comment]
https://github.com/dotnetcore/CAP/pull/300
Submitted 👍
