### ISSUE TITLE
A deadly Bug：DotNetCore.CAP.ConsumerHandler.Dispose

### ISSUE THREAD

**Issue by zhenlei520** [dotnetcore/CAP#298]
## dependencies version：
   DotNetCore.CAP：2.2.5
   DotNetCore.CAP.MySql：2.2.5
   DotNetCore.CAP.RabbitMQ：2.2.5	

	System.NullReferenceException: Object reference not set to an instance of an object.
		   at DotNetCore.CAP.ConsumerHandler.Dispose()
		   at Autofac.Core.Disposer.Dispose(Boolean disposing)
		   at Autofac.Util.Disposable.Dispose()
		   at Autofac.Core.Lifetime.LifetimeScope.Dispose(Boolean disposing)
		   at Autofac.Util.Disposable.Dispose()
		   at Autofac.Core.Container.Dispose(Boolean disposing)
		   at Autofac.Util.Disposable.Dispose()
		   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.Dispose(Boolean disposing)
		   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.Dispose()
		   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Dispose()
		   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
		   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
		   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
		   at UserCard.API.Program.Main(String[] args)

   &emsp; &emsp; The problem occurred when the project started, but I was unable to reproduce the error locally, and everything was fine locally，the same configuration information has been successfully deployed on other servers, and many services using the same configuration have experienced the same problems. Sometimes they succeed, sometimes they fail, and the running service may reappear this error after updating the project.

   &emsp; &emsp; After reading the source code, Using is used, which will release the connection after use, and there is no error, but this problem does occur, and very serious, the following is the configuration information

   &emsp; &emsp;We consume messages via controller injection

            services.AddDbContext<UserDbContext>(); 
            services.AddCap(x =>
            {
                x.UseEntityFramework<UserDbContext>(); 
                x.UseDashboard();
                x.UseRabbitMQ(options =>
                {
                    options.HostName = Configuration.GetSection("RabbitMqConfig")["HostName"];
                    options.Port = Configuration.GetSection("RabbitMqConfig")["Port"].ConvertToInt(0);
                    options.UserName = Configuration.GetSection("RabbitMqConfig")["UserName"];
                    options.Password = Configuration.GetSection("RabbitMqConfig")["Password"];
                    options.VirtualHost = Configuration.GetSection("RabbitMqConfig")["VirtualHost"];
                }); 
                x.FailedThresholdCallback = (type, name, content) =>
                {
                    LogCommon.Error("CAP Exception",
                        "MessageType：" + type + "\n" + "Name：" + name + "\n" + "Content：" + content);
                };
            });

**Comment by zhenlei520** [comment]
&emsp; &emsp; The Autofac container is also used in the project。

 #### dependencies version：
&emsp; &emsp; Autofac.Extensions.DependencyInjection：4.3.0

**Comment by yang-xiaodong** [comment]
Thanks for your feedback 

From the stack information of the exception,  I found that Autofac releases the object and invokes the Disponse() method of the ConsumerHandler, so it means that your application was aborted on startup, What causes it?

**Comment by zhenlei520** [comment]
&emsp; &emsp;In the Startup class's ConfigureServices method, there is a method for automatic injection，The complete code is as follows

	 services.AddDbContext<UserDbContext>(); 
        services.AddCap(x =>
        {
            x.UseEntityFramework<UserDbContext>(); 
            x.UseDashboard();
            x.UseRabbitMQ(options =>
            {
                options.HostName = Configuration.GetSection("RabbitMqConfig")["HostName"];
                options.Port = Configuration.GetSection("RabbitMqConfig")["Port"].ConvertToInt(0);
                options.UserName = Configuration.GetSection("RabbitMqConfig")["UserName"];
                options.Password = Configuration.GetSection("RabbitMqConfig")["Password"];
                options.VirtualHost = Configuration.GetSection("RabbitMqConfig")["VirtualHost"];
            }); 
            x.FailedThresholdCallback = (type, name, content) =>
            {
                LogCommon.Error("CAP Exception",
                    "MessageType：" + type + "\n" + "Name：" + name + "\n" + "Content：" + content);
            };
        });
	this._serviceProvider = new EInfrastructure.Core.AutoFac.MySql.AspNetCore.AutofacAutoRegister().Build(services,(builder) => { });

AutofacAutoRegister:

	/// <summary>
    /// Autofac Register
    /// </summary>
    public class AutofacAutoRegister
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="services"></param>
        /// <param name="action"></param>
        /// <returns></returns>
        public virtual IServiceProvider Build(IServiceCollection services,
            Action<ContainerBuilder> action)
        {
            var builder = new ContainerBuilder();
            var assemblys = AppDomain.CurrentDomain.GetAssemblies().ToArray();
            
            var perRequestType = typeof(IPerRequest);
            builder.RegisterAssemblyTypes(assemblys)
                .Where(t => perRequestType.IsAssignableFrom(t) && t != perRequestType)
                .PropertiesAutowired()
                .AsImplementedInterfaces()
                .InstancePerLifetimeScope();

            var perDependencyType = typeof(IDependency);
            builder.RegisterAssemblyTypes(assemblys)
                .Where(t => perDependencyType.IsAssignableFrom(t) && t != perDependencyType)
                .PropertiesAutowired()
                .AsImplementedInterfaces()
                .InstancePerDependency();

            var singleInstanceType = typeof(ISingleInstance);
            builder.RegisterAssemblyTypes(assemblys)
                .Where(t => singleInstanceType.IsAssignableFrom(t) && t != singleInstanceType)
                .PropertiesAutowired()
                .AsImplementedInterfaces()
                .SingleInstance();

            action(builder);

            builder.Populate(services);

            var container = builder.Build();

            var servicesProvider = new AutofacServiceProvider(container);

            return servicesProvider;
        }
    }

&emsp; &emsp;Reference is a simple class library I wrote myself:
		&emsp; &emsp;https://github.com/zhenlei520/System.Extension.Core

**Comment by yang-xiaodong** [comment]
The CAP configuration looks correct. I have tested the CAP with Autofac, it works fine, maybe you need to streamline your code to troubleshoot problems

**Comment by zhenlei520** [comment]
I can't reproduce this mistake locally. Everything was normal before, but it is a recent problem. I don't know whether it is because of business growth or other reasons

**Comment by zhenlei520** [comment]
Most indignantly, a working project may have problems after it is updated, and a failing project may revert to normal after it is updated

**Comment by zhenlei520** [comment]
In addition, I would like to ask whether the encoding format of the table automatically generated by cap needs to be set in cap. Since users like to use special expressions in messages, the messages cannot be sent normally, so it must be changed to utf8mb4 in mysql

**Comment by yang-xiaodong** [comment]
CAP has no encoding requirements for database tables and you can modify the encoding of the generated tables to your liking

**Comment by zhenlei520** [comment]
After careful examination revealed or automatic injection errors, DotnetCore is lazy loading DLL library, so automatic injection, injection delay existing may cause the failure of project startup, since each load order is not fixed, so didn't show up sometimes succeed, sometimes the failure problem, this tip is not so obvious, updated revised, now start to normal

**Comment by zhenlei520** [comment]
Finally, thank you for your reply. Thank you very much @yang-xiaodong
