### ISSUE TITLE
Storage 和 MessageQueue 子项目能否区分开

### ISSUE THREAD

**Issue by zwq000** [dotnetcore/CAP#299]
1. 队列存储和发布订阅 能否区分开呢
让人很迷惑,为社么 UseEntityFramework 之后还需要 UseRabbitMQ

比如 存储组件改为 DotnetCore.Cap.Store.MySql/DotnetCore.Cap.Store.EntityFramework
消息组件 改为 DotnetCore.Cap.MQ.RubbitMQ/DotnetCore.Cap.MQ.Kafka

2. 使用类型化的 DbContext
Microsoft.Extensions.Identity.Stores 项目中通过预制一个 DbContext,使用EFCore方式处理存储,这样就不需要支持每种数据库类型,只需要用户使用现有方式集成进来就能使用. 通常我会单独处理 消息存储的数据连接,不会放在业务数据库中,虽然会使用同一台服务器,但一定会单独建立一个数据库. 

3. Dashboard 和服务发现 剥离
我认为 Dashboard 服务需要拆分,在小型或者紧密的架构中,不是每个消息接收者都需要查看仪表盘,虽然可以不启用 dashboard 但是组件中还是占据了空间和依赖关系. 导致会增加很多不必要的类库.(依赖的组件已经很多了)

我准备在下一个项目中采用,但是很犹豫,代码会增加狠多重量

**Comment by yang-xiaodong** [comment]
你说的这些问题我们一开始都考虑过，目前的结构是我们综合评定的结果，感谢你的反馈
