### ISSUE TITLE
Some questons about CAP develop version

### ISSUE THREAD

**Issue by zzyykk123456** [dotnetcore/CAP#30]
@yuleyule66,
(1)In CAP develop version,The Sample Sample.Kafka.SqlServer is based on Kafka and SqlServer,but why 
is " _capBus.Publish("sample.rabbitmq.mysql", "");” and "await _capBus.PublishAsync("sample.rabbitmq.mysql", "");" in valuesController .
(2)How subscribe happens?It means how the following code run?
        [NonAction]
        [CapSubscribe("sample.kafka.sqlserver", Group = "test")]
        public void KafkaTest()
        {
            Console.WriteLine("[sample.kafka.sqlserver] message received");
            Debug.WriteLine("[sample.kafka.sqlserver] message received");
        }
Thank you!

**Comment by yuleyule66** [comment]
Hi, I suggest you read the wiki first.
https://github.com/dotnetcore/CAP/wiki
