### ISSUE TITLE
多数据库，只建了一个库的表的问题

### ISSUE THREAD

**Issue by cheetahing** [dotnetcore/CAP#304]
使用了两个数据库，只有其中一个数据库自动创建了数据表，另一个需要手工创建数据表
x.UseSqlServer(ConnnectionFactory.ConnectionString);
x.UseSqlServer(ConnnectionFactory.ConnectionString2);

能看到CapOptions.Extensions有两个数据库的对像，按我的理解应该是支持多数据库建表的

**Comment by yang-xiaodong** [comment]
Multiple databases in one instance is not supported

**Comment by cheetahing** [comment]
1.我需要支持多个sql server我该从哪里入手，如何进行改造，有什么建议，我有时间可以贡献代码
2.我的事务性的业务放在sql server里，非事务(历史数据)通过消息总线进行同步，他们会处于同一个微服务中，有什么建议

**Comment by yang-xiaodong** [comment]
@cheetahing  你的思路可能有点问题，我帮你理一下。

你想的是事务消息写SQL Server， 其他不重要的历史消息写入其他数据库，这样分工职责比较明确，场景比较清晰，你的想法大概是这样吧？

那么我们可以从两方面来分析。
1、假如你们业务量很大，消息数量可能达到每秒几千或者几万，那么为什么还要使用数据库或者在内存中做一次存储呢，这么大的吞吐量应该直接连到消息队列，不经过任何处理发送即可，使消息队列达到最大峰值，使用CAP反而会降低吞吐量，因为CAP需要处理以及存储。
2、假如你们业务量很小，消息数量可能就每秒几十或者几百甚至可能还要更少一些，那么使用SQL Server存储（包括历史数据消息）又有什么关系呢，CAP会定期清理这些成功的数据，这些事件数据仅仅是为了保证数据一致性的临时存储介质而已，你可以把过期事件设置小一点，这样CAP就会更加积极的清理这些数据。
3、需要事务的场景在发消息的时候开启事务就行了，像历史数据这种直接发就行了，这是我能够告诉你的解决方案。

以上，希望你能明白我想表达意思的核心思想。

**Comment by cheetahing** [comment]
完全理解了，非常，非常感谢！
我上面上表达的意思是，sql server存储的业务数据是实时事务性的数据，例如订单数据。
当订单关闭后，通过消息总线把关闭的订单的业务数据推到mongodb的历史数据微服务里，我原来的想法是这件事要全部完成。

经过您的提示，我发现我的想法是错的，我完全可以在mongodb的微服务里，写完历史数据，再去删sql server里的数据。

还是非常感谢您！

### 我还是有一个疑惑，sql server如果自已做水平分库，能否解决分库的问题，
业务场景：
我们公司做的酒店saas系统，完全可以按门店进行水平切分
id为1-100的门店的所有数据放在db1
101-200的门店的数据放在db2
这种场景能否处理，由于历史原因，现在只能用sql server

我们现在单体asp.net mvc站点的做法是，业务层把门店的id传进来，跟据门店id映射连接字符串，生成不同连接串的connection，如果改为微服务，回到刚才多库的问题了

**Comment by yang-xiaodong** [comment]
不好意思，这里只会讨论和CAP有关的话题，你的问题已经超出此范围了。

**Comment by d4ilys** [comment]
@cheetahing 我也遇到saas系统，根据每次的请求动态生成不同连接串的connection，现在无奈只能改成按表隔离租户，请问你这个问题解决了吗
