### ISSUE TITLE
Questions about SkyWalking integration

### ISSUE THREAD

**Issue by ajdwfnhaps** [dotnetcore/CAP#306]
Hi,

When I tried to integrate SkyWalking with CAP, found that can't find any trace records of the screenshots below mentioned in SW UI, 

![image](https://user-images.githubusercontent.com/11205717/55226495-0ff3ad80-5250-11e9-9483-4d9a33df058f.png)
---
just can see about http or db trace info

![image](https://user-images.githubusercontent.com/11205717/55227212-d3c14c80-5251-11e9-87cd-5d2b0c3917b1.png)

![image](https://user-images.githubusercontent.com/11205717/55227230-de7be180-5251-11e9-8ca3-b79f6721eb86.png)

here's how I integrated SW:
![image](https://user-images.githubusercontent.com/11205717/55227537-b771df80-5252-11e9-8db1-1d0e36f370ca.png)

how can I view the time consuming information about MQ send and consume and subscriber method execution.

Help pls.
Thank you in advance.

**Comment by yang-xiaodong** [comment]
I think this issue should be submitted at https://github.com/SkyAPM/SkyAPM-dotnet
I  transferred this issue to https://github.com/SkyAPM/SkyAPM-dotnet/issues/177
