### ISSUE TITLE
[Question] Any plans to support Azure CosmosDb?

### ISSUE THREAD

**Issue by markphillips100** [dotnetcore/CAP#308]
I know MongoDb is supported but just wondering if CosmosDb is on any roadmap?

I'm not sure if CosmosDb even supports the required transactional semantics so any insight on this would be useful.

**Comment by yang-xiaodong** [comment]
@markphillips100 
I don't know much about CosmosDb, I need to spend some time to learn.

**Comment by markphillips100** [comment]
Thanks @yang-xiaodong.  I'll close for now.
