### ISSUE TITLE
When consumer throws an exception, and the consumer will receives the message again

### ISSUE THREAD

**Issue by iexapl** [dotnetcore/CAP#309]
同一微服务同时部署多个节点时

`
private async Task ProcessReceivedAsync(IStorageConnection connection, ProcessingContext context)
        {
            var messages = await connection.GetReceivedMessagesOfNeedRetry();

            foreach (var message in messages)
            {
                await _subscriberExecutor.ExecuteAsync(message);

                context.ThrowIfStopping();

                await context.WaitAsync(_delay);
            }
        } `
如果先前执行一次有异常时，就会重试，这样会让同一 Received，执行多次的

**Comment by yang-xiaodong** [comment]
This is expected, see #29 

Document at here : http://cap.dotnetcore.xyz/user-guide-cn/api-interface/#_4

By the way , please describe issue in English to make it easier for others to search for this issue.
