### ISSUE TITLE
消息优先级

### ISSUE THREAD

**Issue by chrcao** [dotnetcore/CAP#31]
系统中经常会有2种消息类型存在，一种是控制消息，一种数据消息。
一般控制消息的到达优先级会比数据消息高。
按目前cap的实现，数据和控制消息会被同等对待。
是否可以考虑加入消息优先级的支持？

**Comment by yuleyule66** [comment]
什么叫控制消息？ 什么叫数据消息？

**Comment by chrcao** [comment]
@yuleyule66 
一些配置类的消息可以算是控制消息
举例一个场景，A，B两个系统，A系统向B系统发送消息，消息包含配置消息和数据消息。
当A达到某些条件后，向B发送一个配置消息停止A向B发送的消息的接收和处理。
这个时候，需要A发送的配置消息要先于A已经给B发送的数据消息先到达B。

**Comment by yuleyule66** [comment]
不懂， 不过我觉得你不应该这么做。 配置信息为什么要通过消息队列发送。
