### ISSUE TITLE
Publish in batches or multiple publishers

### ISSUE THREAD

**Issue by denisulmer** [dotnetcore/CAP#311]
Hello,

I'd like to request a feature for publishing multiple events at once (batches) or as alternative make the publish method thread-safe. We have a scenario where we publish a lot of messages (few millions) in a short time and want to speed up the process by either publishing the messages in batches (using EF core, this is a lot faster than calling `SaveChanges()` after each insert) or by having multiple publishers working on the data at once.

We have tested the second scenario and it seems that the CAP publisher is not thread-safe at the moment as we run into a `InvalidOperationException: Colleciton has been modified` when we are using multiple publishers.

**Comment by yang-xiaodong** [comment]
Hi @denisulmer 

Thank you for your feedback.

In the scenario of publishing a large number of messages in a short time, I recommend using a dedicated thread to directly connect to the message queue for batching, and enable multiple consumer threads at the time of consumption to ensure consumption speed.

The CAP persists the message to ensure reliability, but this sacrifices performance. Currently, CAP does not support enabling multiple threads for consumption in one instance, so it may not be able to satisfy your scenario.

I will try to solve the thread safety problem, thanks your report.

**Comment by yang-xiaodong** [comment]
Fixed in v2.5.1
