### ISSUE TITLE
The consumption problem of multiple consumers in the same topic

### ISSUE THREAD

**Issue by 491134648** [dotnetcore/CAP#312]
Agree to topic when multiple consumers when his spending rules are like, similar to load balancing, when my message processing does not come over, while opening two consumer programs CapSubscribe ("dtulog.recive.cardhistory")

**Comment by yang-xiaodong** [comment]
Sorry, I may not fully understand what you mean.
Do you mean broadcast consuming?

**Comment by 491134648** [comment]
Three copies of the same consumer program

**Comment by yang-xiaodong** [comment]
Waht is your question?

**Comment by yang-xiaodong** [comment]
No response, close it
