### ISSUE TITLE
 NodeId type change of DiscoveryOptions for Consul 

### ISSUE THREAD

**Issue by visionding** [dotnetcore/CAP#314]
存在多个服务或者服务有多个实例的时候，整型的NodeId不容易确保唯一，改成字符串类型后可以根据IP地址+端口号生成

**Comment by wu-yafeng** [comment]
GetHashCode may works to you

**Comment by yang-xiaodong** [comment]
Thank you for your report,
We have updated the NodeId to a string type, which may cause some unknown problems, but I think keeping the data type of Consul will not cause too much trouble.
