### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type 'DotNetCore.CAP.ICapPublisher' while attempting to activate 'ZLHP.User.Grains.UserGrain'.

### ISSUE THREAD

**Issue by qgxcry** [dotnetcore/CAP#317]
An unhandled exception occurred while processing the request.

InvalidOperationException: Unable to resolve service for type 'DotNetCore.CAP.ICapPublisher' while attempting to activate 'ZLHP.User.Grains.UserGrain'.
 
public class UserGrain : GrainBase, IUserGrain
    {
        private ICapPublisher _capPublisher;

        public UserGrain(ICapPublisher capPublisher)
        {
            _capPublisher = capPublisher;
        }
}

**Comment by ramyasrimantripragada** [comment]
what's the solution for this error?

**Comment by yang-xiaodong** [comment]
> what's the solution for this error?

Ensure you inject the ICapPublisher by `services.AddCap()`
