### ISSUE TITLE
Question of delayed message

### ISSUE THREAD

**Issue by penjay** [dotnetcore/CAP#319]
请问延时消息应该如何处理？
例如发布一条消息，希望消费者30分钟后消费？或者您有什么建议吗，谢谢。

**Comment by yang-xiaodong** [comment]
Please describe your issues in English so that others can search for the same questions.

CAP does not support delayed messages, you need to use a third-party job tasks framework to do this, such as Hangfire or Quarz.NET

**Comment by penjay** [comment]
> Please describe your issues in English so that others can search for the same questions.
> 
> CAP does not support delayed messages, you need to use a third-party job tasks framework to do this, such as Hangfire or Quarz.NET

Ok, thank you for your reply.
There is one more question. If multiple consumers subscribe to the same queue message, can the consumption be distributed?For example, can a message queue sending marketing SMS messages to tens of thousands of people be sent simultaneously by multiple consumers?

**Comment by yang-xiaodong** [comment]
Sure,broadcast message docs at here :
https://github.com/dotnetcore/CAP#subscribe-group

**Comment by penjay** [comment]
I'm sorry, maybe I'm describing the wrong scene.The actual scenario is as follows: for example, if you have a message queue "test.message.sms" and 10,000 messages are published, can you deploy multiple consumers to subscribe to it and consume at the same time?
They might be deployed on different servers, and because of the server configuration, they might end up with 10,000 messages, 3,000 consumed by SendSMS1, and 7,000 consumed by SendSMS2.But they do it in parallel.

//Server1 or console1
[CapSubscribe("test.message.sms")]
public void SendSMS1(SMSModel model)
{
      //do send sms
}

//Server2 or console2 or controller2
[CapSubscribe("test.message.sms")]
public void SendSMS2(SMSModel model)
{
     //do send sms
}

**Comment by yang-xiaodong** [comment]
Are you mean [consumer priority](https://www.rabbitmq.com/consumer-priority.html)?

**Comment by penjay** [comment]
My main problem is that multiple consumers share the consumption pressure, and by deploying multiple consumers, the backlog of messages can be consumed as soon as possible

**Comment by yang-xiaodong** [comment]
> My main problem is that multiple consumers share the consumption pressure, and by deploying multiple consumers, the backlog of messages can be consumed as soon as possible

That's the default

**Comment by penjay** [comment]
![image](https://user-images.githubusercontent.com/23008915/56106551-521d2e80-5f74-11e9-94c3-4a73e51397c6.png)
![image](https://user-images.githubusercontent.com/23008915/56106564-5ea18700-5f74-11e9-9cde-8542b4d1bb61.png)

But the test result is that only CheckReceivedMessage is consuming all the time, and CheckReceivedMessage1 is not consuming.How do you do that?

**Comment by yang-xiaodong** [comment]
You need start two instances instead of writing two consumer methods.

if you want writing two consumer methods in one instancec, you need set them with the same group. like:
```
public void ConsomerOne(){
}

```

**Comment by penjay** [comment]
Thank you so much, Deploying multiple consumer instances to consume concurrently, the test was successful.

**Comment by penjay** [comment]
![image](https://user-images.githubusercontent.com/23008915/56116340-27dd6800-5f98-11e9-94ee-f1234d629c83.png)
