### ISSUE TITLE
Dashboard授权

### ISSUE THREAD

**Issue by zouql** [dotnetcore/CAP#320]
自定义CapDashboardAuthorizationFilter实现了IDashboardAuthorizationFilter，通过以下代码实现注入，x.UseDashboard(m => { m.Authorization = new[] { new CapDashboardAuthorizationFilter() }; });
CapDashboardAuthorizationFilter如下：
private class CapDashboardAuthorizationFilter : IDashboardAuthorizationFilter
        {
            bool IDashboardAuthorizationFilter.Authorize(DashboardContext context)
            {
                var currentPrincipal = (context as CapDashboardContext)?.HttpContext?.User;

                var isValid = currentPrincipal?.Identity?.IsAuthenticated ?? false;

                return isValid;
            }
        }

IDashboardAuthorizationFilter.Authorize方法始终返回false，类似的配置，hangfire的控制面板是正常的。
浏览器cookie如下：
cookie:__guid=111872281.3251847391157828600.1555422130531.7417; .AspNetCore.Identity.Application=CfDJ8BdZl-M84FNHu6iV5cefP-tRKGtg1ErLdZLE6eMt7FP9Fv0nGX3yTTrawpaP6-4rBCcyMc0kb_l2Ys7H93bGSDgXRfNIHnN0cTjmop6zSND4gmAnki5e7ObYlK35SsZbsewSNwZ3zre8HPtYixRVhB_Y_fSWWem4eiP3RDLO5hw7J13_5cLxHoMS7zIaWC7prSFsobUvHQyy9qEVoUV2U9MeELMKHP-CTQKNG7YqAH1Ady_vjDfvqOCe-7zSx28QVpZC6GbqvxzOHN_ipshNGCdQIDK_9FJo9FHm8vU5qetNwPkFo_PddZNgJH2MKSrSY0-YOGoXRk2CrflZm0dTW1PaXmgmjvhZeHc0g06T986GdHT9gec-Zl_w1CDJmuRWuDKvLqQxmNH0xp6khNL8lKtqaJfuLKu-_xpPVSDXQzoAo1vArseb88MrHN1RLSk79_69Ql3ie9zwCtZLKEH_m3aT383g6GtTaB1Hg0km7EtkW6b27a4EAWJmKXzGpV6wDvwPHltmNBBIq3QGhh0flIB_d_52HxYEq6Y2seJbMxA4Pz2Jew55SE2xZpIQojWZ01KqNfAoASItBVUBdg4rz2WrmtP--_uIhFhVDM8tYLnKChzAp0j9Bra0PfnJX-bmvXJxYD9zyXLZ-If69-XMzvqVScRxzH3u8zgK-LtzFdCrHsSY_ppEia1IIZ1oV-_LjFjjDMBInitGFxam48P7kQbeVogCBuB9OAQ4PUytN2pMwvsOdG-NcUCW6Ucz7-Fk4eLnl2-dO0viUvHdr6dWGW4smL7a10LZ2Thjx-HYBqxC_4UZoAPoB8qCjescFhVPwXDjV-P5-YvasXMmjk6uoYQ; monitor_count=126

**Comment by yang-xiaodong** [comment]
HttpContext comes from middleware, you need to check the authentication order status by yourself

**Comment by wuzixiao** [comment]
@zouql , we just had the same issue. Have you managed to figure out the solution?
Thanks in advance.
