### ISSUE TITLE
sub的接收消息一直为空

### ISSUE THREAD

**Issue by xewn** [dotnetcore/CAP#321]
我用的rabbitmq，手动新建了cap.default.topic, cap.default.group，也都给了权限。
现在是pub消息在数据库和rabbitmq都成功了。
但是接收消息一直是空的。这个是什么地方没配置对呢？

**Comment by xewn** [comment]
我用essynetQ测试了下，会根据dto自动创建Exchanges和绑定queues。
但是CAP没有自动创建这些，手动创建的是不是对应不到呢？
我手动创建了一个Queues  cap.default.group 是不是不对呢？

**Comment by xewn** [comment]
Consumers在rabbitmq里的channels中没记录。这个是为什么？

**Comment by xewn** [comment]
最后查到原因，是在abp vnext中的applictionservice中不能使用。放在没实现applictionservice的类里，就可以了。

**Comment by yang-xiaodong** [comment]
#616
