### ISSUE TITLE
[Question] Any way to unsubscribe a message?

### ISSUE THREAD

**Issue by wu-yafeng** [dotnetcore/CAP#322]
I have a question about is there any way to unsubscribe a message?

I have following consumer:

``` csharp
    public class CapConsumer : ICapSubscribe
    {
        private readonly IMediator _mediator;

        public CapConsumer(IMediator mediator)
            => _mediator = Check.NotNull(mediator, (nameof(mediator)));

        [CapSubscribe(nameof(OrderStatusChangedToCanceledIntegrationEvent))]
        public Task ProcessOrderCanceledAsync(OrderStatusChangedToCanceledIntegrationEvent notification)
            => _mediator.Publish(notification);
}
```

I remove the method `ProcessOrderCanceledAsync()`

But queue in **RabbitMQ** also bind **OrderStatusChangedToCanceledIntegrationEvent**

Can I unbind the message without in **RabbitMQ Management UI** manual?

**Comment by yang-xiaodong** [comment]
Yes, you can using [management cli](https://www.rabbitmq.com/management-cli.html) to unbind the queue

**Comment by wu-yafeng** [comment]
Use **RabbitMQ dotnet client library** with following codes: 

``` csharp
using (var channel = _connection.CreateModel())
{
     channel.QueueUnbind(_queueName, exchangeName, routingKey);
}
```

**Comment by yang-xiaodong** [comment]
@wu-yafeng I know how to unbind, I means how to get the existed queues that CAP has been previously bound and deleted

**Comment by wu-yafeng** [comment]
I use following code:

``` csharp

services.AddCap(options=>{
options.Version="v2"
});

```

It's a better way to unsubscribe a message.
