### ISSUE TITLE
Feature request: Add option to prefix topics

### ISSUE THREAD

**Issue by naymore** [dotnetcore/CAP#323]
**Motivation**
We have different environments which we need to maintain. As we do not want to run the same infrastructure multiple times (e.g. one kafka cluster for each environment or even for each developer) we are looking for a way to share a single instance.

**Suggestion**
My suggestion would be to make this a (optional) configuration option (e.g. "topic.prefix").

It could be as simple as

`
protected TopicAttribute(string name)
        {
            Name = StaticConfiguration.TopicPrefix + name;
        }
`

(Unfortunately Attributes are a bit cumbersome when it comes to IoC and ctor() injections)

What do you think? Maybe this even relates to #57? (language barrier ahead)

**Comment by yang-xiaodong** [comment]
For `TopicAttribute`, you can customize to extend it, for example

```C#
public class MySubscribeAttribute : TopicAttribute
{
    public CapSubscribeAttribute(string name)
      :base(StaticConfiguration.TopicPrefix + name)
    {
      
    }
}
```
Then ,you can init the `StaticConfiguration.TopicPrefix` at application startup

**Comment by naymore** [comment]
True.

I thought about actually moving this into its own class solely responsible for extending topic/queue names and injecting it into the class responsible for tieing consumers to topics but you are right, I will try that first and see how I like it in the long run :)
