### ISSUE TITLE
是否考虑支持 Autofac

### ISSUE THREAD

**Issue by duyanming** [dotnetcore/CAP#325]
你好，是否考虑支持 Autofac。或者有demo参考吗

**Comment by yang-xiaodong** [comment]
CAP does not depend on the IOC container. Do you have any exceptions?

**Comment by duyanming** [comment]
我是想在 consoleapp里面用，除了servicecollection.addcap 初始化之外。我该怎么初始化。

**Comment by yang-xiaodong** [comment]
You need using the [Autofac.Extensions.DependencyInjection](https://github.com/autofac/Autofac.Extensions.DependencyInjection) to  adaptation microsoft ioc
