### ISSUE TITLE
RabbitMQ 连接字符串配置Bug

### ISSUE THREAD

**Issue by duyanming** [dotnetcore/CAP#326]
x.UseRabbitMQ(options =>
                        {
                            options.HostName = "192.168.1.9";
                            options.Port = 5672;
                            options.UserName = "dym";
                            options.Password = "123456";
                            options.VirtualHost = "dym_vhost";
                        });
这种配置方法可以连接到 rabbitMQ 
----------------------------------------------------------------------
 public static RabbitMQOptions rabbitMQOptions = new RabbitMQOptions()
        {
            HostName = "192.168.1.9",
            Port = 5672,
            UserName = "dym",
            Password = "123456",
            VirtualHost = "dym_vhost"
        };

                        x.UseRabbitMQ(options =>
                        {
                           options=loaderCap.Cfg.rabbitMQOptions;
                        });
这种就连接不上

**Comment by yang-xiaodong** [comment]
this is expected , you can view the source code
