### ISSUE TITLE
Always consume same message for three times immediately

### ISSUE THREAD

**Issue by xiaotupansy** [dotnetcore/CAP#327]
Here's the code:
startup.cs
            ```
services.AddCap(x =>
            {
                x.UseDashboard();
                x.UseEntityFramework<StudyDBContext>();
                x.UseRabbitMQ(a =>
                {
                    a.HostName = Configuration["AppSettings:rabbitMQ:host"];
                    a.UserName = Configuration["AppSettings:rabbitMQ:user"];
                    a.Password = Configuration["AppSettings:rabbitMQ:password"];
                });
                x.FailedRetryCount = 3;
                x.DefaultGroup = Configuration["capgroup"];

            });

```
controller

`
        [CapSubscribe(MessageDto.DefaultQueue)]
        public async Task PublishAsync(MessageDto messageDto)
        {
            // handle code
        }`

**Comment by yang-xiaodong** [comment]
Because your consumer raise an exception, CAP will retry three times at first time

**Comment by xiaotupansy** [comment]
Maybe I found the resaon.

 public async Task PublishAsync(MessageDto messageDto)
vs
public void PublishAsync(MessageDto messageDto)

After change method from async Task to  void, I find it works.
So I wonder if CAP only supports synchronization method.

Here's log:

An exception occurred while executing the subscription method. Topic:DomainQueue, Id:1119462733891620864 | URL :  | QueryString :  | Agent :  |    at DotNetCore.CAP.DefaultSubscriberExecutor.InvokeConsumerMethodAsync(CapReceivedMessage receivedMessage) in C:\projects\cap\src\DotNetCore.CAP\ISubscribeExecutor.Default.cs:line 194
   at DotNetCore.CAP.DefaultSubscriberExecutor.ExecuteWithoutRetryAsync(CapReceivedMessage message) in C:\projects\cap\src\DotNetCore.CAP\ISubscribeExecutor.Default.cs:line 88

**Comment by yang-xiaodong** [comment]
CAP supports both synchronous and asynchronous methods, I can't not reproduce your issues

https://github.com/dotnetcore/CAP/blob/de04d99cdc28849f2ee1d26b745a1a4b8b31c777/src/DotNetCore.CAP/Internal/IConsumerInvoker.Default.cs#L64-L69
