### ISSUE TITLE
About the IConsumerServiceSelector access modifier

### ISSUE THREAD

**Issue by colinin** [dotnetcore/CAP#330]
I integrated ABP & CAP in a microservice project, but found that the dynamic class of ABP was not very
 friendly with subscribers of CAP, because CAP could not get the CapSubscribeAttribute of the dynamic class.

When I tried to override IConsumerServiceSelector, I found that the interface was an internal class, 
which meant that I needed to customize the CAP myself instead of getting the latest Nuget package

![image](https://user-images.githubusercontent.com/35512826/56796836-fbea9e00-6845-11e9-85ca-56276504ba8e.png)

**Comment by yang-xiaodong** [comment]
Hello,

I think we can make `IConsumerServiceSelector` to public , would you want to submit a PR to do that ?

By the way, if we set `IConsumerServiceSelector` to public , we need move it to the parent folder for code standards, thankss

**Comment by colinin** [comment]
I personally think that only the public is enough, because the third party dynamic proxy library has a lot of kinds, reflecting different types need different means, the user only needs to inherit DefaultConsumerServiceSelector by using the reflection of the third party's dynamic proxy can rewrite SelectCandidates method...

**Comment by colinin** [comment]
moving to root directory is a good idea

**Comment by yang-xiaodong** [comment]
well, would you want to submit a PR ?

**Comment by colinin** [comment]
https://github.com/dotnetcore/CAP/pull/333#issue-274105528

**Comment by yang-xiaodong** [comment]
Fixed in PR #333
