### ISSUE TITLE
Question about SubscriberNotFoundException

### ISSUE THREAD

**Issue by xueandfeng** [dotnetcore/CAP#331]
现在想项目A只使用发布  项目B只进行订阅。然而现在配置队列都是同一个。
现在会发生情况是有些消息会被项目A消费掉导致会这个错误
![image](https://user-images.githubusercontent.com/20178645/56809144-be960880-6865-11e9-88cd-e91e689a1d2c.png)
所有我想问问。我需要怎么配置可以让项目B正常消费

**Comment by yang-xiaodong** [comment]
Please describe your problem in English so that others can search.

If you don't want to consume in Project A, you can cancel the subscription. This exception is because you have subscribed to the A project , see issue #63  how to cancel subscriber in RabbitMQ.

**Comment by xueandfeng** [comment]
不好意思。英文不好.我还是中文描述吧。
因为我项目A中进行配置了cap信息。但是项目A中没有任何的订阅方法. 订阅的方法都是在项目B中。
因为使用的队列都是相同的。所有会导致上面#63的问题。实际来说。我项目A只需进行消息发布就可以了。
所有我想问下我需要怎么配置可以让项目A只进行消息发布。而不会让我发布出去的消息进行订阅到。

**Comment by yang-xiaodong** [comment]
项目A中没有任何的订阅方法仍然收到了消息有两种原因导致，请排查。

1、项目A曾经订阅过这个Topic的消息，没有在RabbitMQ手动取消。
2、项目A和项目B程序集名称相同，并且使用的相同的数据库和表。

**Comment by xueandfeng** [comment]
我的是项目A曾今订阅过。现在是移除了把订阅方法移除了。项目B和项目A的程序集不同。但是我是相同的数据库和表.。现在是我要么用不同的表。或者是不同的队列名。或者是版本控制吗？

**Comment by yang-xiaodong** [comment]
@xueandfeng issue 63 已经说的非常清楚如何操作了。 

最简单方法是你换个 name 发消息，之前订阅过的那个 name 不要再用了。

**Comment by xueandfeng** [comment]
了解。谢谢
