### ISSUE TITLE
How to change default serializer?

### ISSUE THREAD

**Issue by Arsmn1996** [dotnetcore/CAP#334]
I want to use Protobuf as a protocol for sending messages.
Is it possible to change Newtonsoft.Json?

**Comment by yang-xiaodong** [comment]
Since our message needs to be stored in the database and displayed on the Dashboard, CAP currently supports serializing the message to a String type, which you can customize with `IContentSerializer`

We will consider introducing the support of the byte[] serializer in the next major release.

**Comment by yang-xiaodong** [comment]
This feature has been implemented
