### ISSUE TITLE
Registering a consumer method without decorator

### ISSUE THREAD

**Issue by mvarga6** [dotnetcore/CAP#336]
Working on a project using queue based micro-service communication and CAP has been great for getting up and running. I'm interested in abstracting out the actually implementation of messaging into it's own assembly which is simple from a producer perspective but not from a consumer perspective (using CAP). Looking for a way to register a consumer function without using the `CapSubscribeAttribute`. Is this currently possible? 

This would be nice so the apps can depend on an internal package/set of interfaces and not explicitly on CAP types. This has advantages when defining repeated custom logic during publish/subscribe invocations.

**Comment by yang-xiaodong** [comment]
Hello @mvarga6 ,

We just merged PR #333 , it allows a custom consumer selector, I added a unit test example ([CustomConsumerSubscribeTest.cs](https://github.com/dotnetcore/CAP/blob/master/test/DotNetCore.CAP.Test/CustomConsumerSubscribeTest.cs)) that shows how to use it.

You can download the latest preview package(`2.5.1-preview-73792921`) from NuGet for testing.
