### ISSUE TITLE
消费者部署到k8s无法消费消息

### ISSUE THREAD

**Issue by shuxinqin** [dotnetcore/CAP#337]
问题描述：
将消费者（asp.net core2.0应用）部署到测试环境（k8s）能消费到消息，部署到生产环境（k8s）消费不到消息。
订阅服务代码：
![image](https://user-images.githubusercontent.com/11437679/57290288-afc61600-70ef-11e9-96d2-911231efc008.png)
启动CAP消费者代码：
![image](https://user-images.githubusercontent.com/11437679/57290326-c3717c80-70ef-11e9-8cc3-e7e05192fb99.png)

在测试环境运行消费正常（启动后能看到创建好的交换机和队列）），控制台打印出的信息如下：
![image](https://user-images.githubusercontent.com/11437679/57290618-5d392980-70f0-11e9-903d-c7a0528fe32f.png)
在生产环境启动程序成功，但消费不到消息（启动后没创建交换机，也没创建队列），控制台打印出的信息如下：
![image](https://user-images.githubusercontent.com/11437679/57290742-a12c2e80-70f0-11e9-803b-869d6a13e5f6.png)
很明显打印的信息从Application started. Press Ctrl+C to shut down.那行开始后面的就没有了。

注：目前已经确定在容器内手动创建mq和db连接是可以连上的，可以排除连接字符串问题。同时，在本地开发环境运行应用（连生产环境的mq）是可以消费消息的。排查了很久，实在不知道是哪里的问题了。
CAP 版本：2.5.0

**Comment by shuxinqin** [comment]
问题已经解决了。下载源码来调试，原来是我们线上连数据库用的帐号没有执行 create table 命令的权限。
也就是执行创建表脚本时报错了
![image](https://user-images.githubusercontent.com/11437679/57348024-1ea27e00-7187-11e9-919c-6b0ff18b5158.png)
要是像这种错误，能打印出个日志就好了，这样比较方便排错。

**Comment by yang-xiaodong** [comment]
这个地方报错异常没有吃掉，应该是会抛出来的，你们没有全局异常处理器吗？

**Comment by shuxinqin** [comment]
我们只有http请求相关的异常处理器。看了下，运行这段代码是由IHostedService执行，可能拦截不到吧。我是在源码里打印日志跟踪发现异常的
![image](https://user-images.githubusercontent.com/11437679/57356420-f9236d80-71a2-11e9-8911-988783d30eaf.png)

**Comment by hessonsu** [comment]
> 报错异常没有吃掉，应该是会抛出来的，

生产环境一般不会给创建表的权限，这个地方不优化下吗？

**Comment by yang-xiaodong** [comment]
@shuxinqin @hessonsu We have added logging if database initialization failed！
