### ISSUE TITLE
kafka2.11-2.0.0版本连接一直积极拒绝

### ISSUE THREAD

**Issue by kingflyok** [dotnetcore/CAP#338]
今天我使用CAP连接kafka2.11版本服务器一直提示：由于目标计算机积极拒绝，无法连接，后更新依赖库Confluent.Kafka版本到1.0.0之后，可以进行连接并消费，是否可以升级版本，谢谢！
升级前错误信息：
![image](https://user-images.githubusercontent.com/29110971/57505297-5f86c800-732a-11e9-86e6-b6da4d2cf175.png)
升级后成功消费：
![image](https://user-images.githubusercontent.com/29110971/57505312-72010180-732a-11e9-8d18-76cb23df32a7.png)

**Comment by yang-xiaodong** [comment]
We will upgrade Confluent.Kafka to 1.0 in the version 2.5.1 ,and we have already completed the upgrade, but we need more tests.

**Comment by yang-xiaodong** [comment]
Hello @kingflyok , v2.5.1 has been released to NuGet.
