### ISSUE TITLE
One message can be consumed twice

### ISSUE THREAD

**Issue by Bingjian-Zhu** [dotnetcore/CAP#339]
If a message is queued twice, it can be consumed twice!

**Comment by yang-xiaodong** [comment]
so what is your question?

**Comment by Bingjian-Zhu** [comment]
这样潜在很多问题，特别在交易场景，加入一条转账信息发处理了两次，这肯定不能接受

**Comment by wuzhenda** [comment]
这个他有提到的，不保证唯一，不过不明白为什么。

**Comment by wuzhenda** [comment]
`注意：框架无法做到100%确保消息只执行一次，所以在一些关键场景消息端在方法实现的过程中自己保证幂等性。`

[http://cap.dotnetcore.xyz/user-guide-cn/api-interface/](url)

**Comment by Bingjian-Zhu** [comment]
> `注意：框架无法做到100%确保消息只执行一次，所以在一些关键场景消息端在方法实现的过程中自己保证幂等性。`
> 
> [http://cap.dotnetcore.xyz/user-guide-cn/api-interface/](url)

能否尝试改成received表主键就为消息ID，接收消息时候先把消息写库，然后再处理消息，这样能解决这个问题？

**Comment by chaiziqi** [comment]
作者已经详细的解答了：https://github.com/dotnetcore/CAP/issues/94#issuecomment-374179744
cap的received是会定期清理的，自然无法用他保证完全的一致性

**Comment by Bingjian-Zhu** [comment]
> 作者已经详细的解答了：[#94 (comment)](https://github.com/dotnetcore/CAP/issues/94#issuecomment-374179744)
> cap的received是会定期清理的，自然无法用他保证完全的一致性

好吧，自己处理消息幂等性也不难
