### ISSUE TITLE
IConsumerInvokerFactory lifetime cause unexpected subscription callback function exceptions

### ISSUE THREAD

**Issue by standardcore** [dotnetcore/CAP#34]
IConsumerInvokerFactory的生命周期为单例，导致消费者回调函数中注入的依赖对象全部都是单例，一旦销毁某个对象，将导致后续所有回调全部失败。

Sample:

```
public async Task<bool> SampleCallback()

{
    using(var connection = _dbContext.Database.GetDbConnection())
    {
        await connection.OpenAsync();
    }
    return true;
}

```

以上代码中，`_dbContext` 通过构造函数注入进来，并在函数执行离开using域时销毁数据库连接，导致第二次进入此函数时抛出异常。

**Comment by yuleyule66** [comment]
"消费者回调函数" 指的是什么？

**Comment by yuleyule66** [comment]
version 2.0 preview published, the problem has now been solved.
