### ISSUE TITLE
MySqlException: Table 'testcapdb.cap.published' doesn't exist

### ISSUE THREAD

**Issue by BruceProject** [dotnetcore/CAP#341]
all code copied from sample, but cap.published didnt created automatically.
identical using EF ORM.

![Startup](https://user-images.githubusercontent.com/2168698/58142698-ba011c00-7c7a-11e9-8b7a-41c9d758e58d.png)

![error](https://user-images.githubusercontent.com/2168698/58142653-94741280-7c7a-11e9-99dd-2fc32ef4dba7.png)

**Comment by yang-xiaodong** [comment]
Hello,

I can't reproduce your issues. Can you show your configuration, And confirm two things ?

1. Is the CAP table generated in the database?
2. Is there a log that failed of create cap table?

**Comment by BruceProject** [comment]
> Hello,
> 
> I can't reproduce your issues. Can you show your configuration, And confirm two things ?
> 
> 1. Is the CAP table generated in the database?
> 2. Is there a log that failed of create cap table?

1. no cap table generated in db.
2. no fail log
3. i run the "Sample.RabbitMQ.MySql" in vs2017 (updated corresponding connectionstring)
4. i created table manually in db ,it works.  

now it can send msg to RabbitMQ, but cannot receive any msg.
I have rised a new issue#`[https://github.com/dotnetcore/CAP/issues/342](https://github.com/dotnetcore/CAP/issues/342)`

**Comment by yang-xiaodong** [comment]
Does your connection string of database user have permission to create tables?

**Comment by BruceProject** [comment]
> Does your connection string of database user have permission to create tables?

yes, use root user.

**Comment by yang-xiaodong** [comment]
Which CAP version are you using?

Because of I can't reproduce your issues, so you can using source code and debug what happend?

**Comment by BruceProject** [comment]
> Which CAP version are you using?
> 
> Because of I can't reproduce your issues, so you can using source code and debug what happend?

OK, thanks. 
Do you have time to take a look at issue#[342](https://github.com/dotnetcore/CAP/issues/342)?

**Comment by BruceProject** [comment]
fixed issue by updating mysql5.1 to mysql 5.7
thanks @yang-xiaodong .
