### ISSUE TITLE
rabbmit消息发布很慢

### ISSUE THREAD

**Issue by xueandfeng** [dotnetcore/CAP#343]
英文不好。我用中文说明
版本：  DotNetCore.CAP -Version 2.5.1-preview-73792921 
mysql：5.7

![image](https://user-images.githubusercontent.com/20178645/58148734-7c0ff200-7c92-11e9-91f4-21fbd8da07a1.png)
数据库cap.published表记录

rabbmit 控制台也是有连接在线的
![image](https://user-images.githubusercontent.com/20178645/58148773-a9f53680-7c92-11e9-9e76-1718c3384d4e.png)
我发现在消息基本需要4-5分钟才会发送到rabbmit去。然后才能消费

**Comment by xueandfeng** [comment]
之前在sqlserver数据库的是时候正常的。我把数据迁移到mysql就是现在情况。published有记录。但是消费的时候需要过4-5分钟 published记录才会更改状态。

**Comment by xueandfeng** [comment]
![图片](https://user-images.githubusercontent.com/20178645/58160263-acff1f80-7cb0-11e9-8ec4-f79cf651753c.png)

用自己的事务进行提交的情况下。在sqlserver数据库下。就是会自动进去消息队列。如果是mysql的情况不会自动进消息队列。https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.MySql/ICapTransaction.MySql.cs#L32 需要进行

https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.SqlServer/ICapTransaction.SqlServer.cs#L73 sqlserver就不需要

**Comment by yang-xiaodong** [comment]
@xueandfeng 这是符合预期的，在SQL Server 和 MySQL 中使用的技术手段不一样，SQL Server 我们可以检测到事务的提交事件，从而可以做到自动 Flush 到 MQ

**Comment by xueandfeng** [comment]
看到了，在想这么处理这个提交。之前因为sqlserver的时候只要给个事务对象到cap就可以了。sqlserver会有监听。现在MySQL没有监听，需要cap的commit才行

**Comment by yang-xiaodong** [comment]
我们建议你使用CAP封装的扩展来进行提交事务操作

**Comment by xueandfeng** [comment]
好的，谢谢你的建议
