### ISSUE TITLE
CapSubscribe allows only Names up to 51 characters

### ISSUE THREAD

**Issue by LeonhardFischl** [dotnetcore/CAP#344]
We are using DotNetCore.CAP in combination with Azure service bus.

I determind that event names (CapSubscribe("this name here") does only allow up to 51 characters. 
We`ve used it like shown in the code snippet

`[CapSubscribe(nameof(SuperLongNameWithMoreThanFiftyCharactersIntegrationEvent))]`

If we use it with less than 51 characters it works fine.

Can you fix it that this name is able to have more than 51 characters. 
A good idea is the database column size of nvarchar(200) which means it should work with up to 200 characters.

Thanks in advance
Leonhard

**Comment by yang-xiaodong** [comment]
Hello @LeonhardFischl ,

The length of the CAP `name` depends on the length of the column fields in the database. I just looked at Azure Service Bus because it limits the length of the Rule Name and you can see the code comments here : 
https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/Filters/RuleDescription.cs#L85

**Comment by enterprisebug** [comment]
It would be absolutely desireable to have a validation for each provider Implementation which validates the event name length.

You have implementation for the different providers, so you could validate each:
- [ ] DotNetCore.CAP.RabbitMQ
- [ ] DotNetCore.CAP.MySql
- [ ] DotNetCore.CAP.Kafka
- [ ] DotNetCore.CAP.SqlServer
- [ ] DotNetCore.CAP.PostgreSql
- [ ] DotNetCore.CAP.MongoDB
- [x] DotNetCore.CAP.AzureServiceBus 
(max length: 50 chars)
- [ ] DotNetCore.CAP.InMemoryStorage

**Comment by yang-xiaodong** [comment]
@enterprisebug  nice advice, I can make validate in the code ahead of time.

**Comment by enterprisebug** [comment]
that would improve stability very much. @LeonhardFischl would have saved days finding the problem. Main problem was that the error reg. 50 chars with AzureServiceBus was hidden. We never saw an exception giving us a hint pointing to the event name length.

**Comment by yang-xiaodong** [comment]
Hello @enterprisebug ,

I have fixed in version `2.5.1-preview-75824665` , because of my azure free account subscription is expired so i can't test it.  Any feedback is welcome!  :)

Thanks
