### ISSUE TITLE
消费方顺序执行

### ISSUE THREAD

**Issue by shrekjxf** [dotnetcore/CAP#346]
消费方是否可以有顺序执行，如果中途一条消息执行失败，后一条消息是否可以不执行，知道这条消息执行成功后再执行之后消息？是否可以通过组来区分，一个组内得消息是顺序消费执行得，中途出错，不执行这个组内得后面消息？

**Comment by yang-xiaodong** [comment]
Message-based architecture does not strictly guarantee messages sequence.
Duplicated  of #29
