### ISSUE TITLE
可否在消费方读取到Cap消息体的内容

### ISSUE THREAD

**Issue by one-sword** [dotnetcore/CAP#347]
Cap的消息体是在用户自定义Event上进行了一次封装，本身有一个Id，Event封装在Content里。请教下，这个Id是否是确保唯一的？另外，有没有办法让订阅方法访问到？如果是唯一且可访问，是不是就可以基于这个去实现用户自己的幂等性校验？

**Comment by wu-yafeng** [comment]
> Cap的消息体是在用户自定义Event上进行了一次封装，本身有一个Id，Event封装在Content里。请教下，这个Id是否是确保唯一的？另外，有没有办法让订阅方法访问到？如果是唯一且可访问，是不是就可以基于这个去实现用户自己的幂等性校验？

translate from google:
> The message body of the Cap is encapsulated once on the user-defined Event. It has an Id and the Event is encapsulated in the Content. Ask, is this Id sure to be unique? Also, is there a way to get access to the subscription method? If it is unique and accessible, can you implement the user's own idempotency check based on this?

Seems reasonable,may add class like
``` csharp
public class CapMessage<TContent> : CapMessage
{
    public TContent ContentObject { get; }
}
```

and subscriber like this:

``` csharp
public class CapSubscriber : ICapSubscribe
{
    public void HandleCapMessage(CapMessage<DateTime> message)
    {

    }

    public void HandleCapMessageWithoutWrapper(DateTime message)
    {

    }
}
```

may add options `SubscriberHandlePolicy` in `CapOptions` with values `CapMessage` `ContentMessage`

**Comment by one-sword** [comment]
> may add options SubscriberHandlePolicy in CapOptions with values CapMessage ContentMessage

sorry，i cannot found “SubscriberHandlePolicy” in the "CapOptions"， is something i missed? @wu-yafeng

**Comment by wu-yafeng** [comment]
> > may add options SubscriberHandlePolicy in CapOptions with values CapMessage ContentMessage
> 
> sorry，i cannot found “SubscriberHandlePolicy” in the "CapOptions"， is something i missed? @wu-yafeng

I mean CAP should probably provide a design like the one above to achieve your needs.

**Comment by yang-xiaodong** [comment]
There are no plans to open it up to consumer, we will consider it in version 3.0

**Comment by yang-xiaodong** [comment]
This feature is implemented with the  [FromCap] attribute
