### ISSUE TITLE
Aws Sqs support    

### ISSUE THREAD

**Issue by jovi-Li** [dotnetcore/CAP#349]
can we add Aws Sqs support ? 
if not ,and can I get any help  if I want to add a  Aws Sqs  provider myself.
翻译:
可以考虑支持Aws Sqs队列吗？
如果不行，有没有帮助我自己实现Aws队列的文档或者更详细的说明吗

**Comment by yang-xiaodong** [comment]
Hello @jovi-Li ,

We have no plans to support Amazon Simple Queue Service now. 
If you want to implementation it , you You can refer to the current implementation of Azure Service Bus or Kafka. Any PR is welcome~
