### ISSUE TITLE
使用tidb作为数据库时出现错误

### ISSUE THREAD

**Issue by Tuoboc** [dotnetcore/CAP#351]
使用的cap版本：2.5.0
我在尝试把cap集成到现有的系统中，现在系统使用的数据库是tidb(一个兼容mysql的分布式数据库)，在配置完成后，访问http://localhost:port/cap 地址查看控制台时出现http500错误，错误信息：
MySql.Data.MySqlClient.MySqlException (0x80004005): ERROR 1105 (HY000): command 31 not supported now
后来我将cap使用的数据库改为mysql后，可以正常访问界面，请问是因为现在cap还不支持tidb吗？

**Comment by yang-xiaodong** [comment]
We have not tested Tidb and do not plan to support it in the near future.
You can implement extended storage for tidb by yourself.

**Comment by Tuoboc** [comment]
> We have not tested Tidb and do not plan to support it in the near future.
> You can implement extended storage for tidb by yourself.
thanks
