### ISSUE TITLE
Allow URI connection

### ISSUE THREAD

**Issue by nicolataddei94** [dotnetcore/CAP#355]
Sometimes it would be convenient to be able to connect directly with the uri.

Like:

`private static string url = ConfigurationManager.AppSettings["CLOUDAMQP_URL"];
static readonly ConnectionFactory connFactory = new ConnectionFactory();
connFactory.Uri = new Uri(url.Replace("amqp://", "amqps://"));`

**Comment by yang-xiaodong** [comment]
Hello, we have improved RabbitMQOptions to provide extensions option to configure the client original configuration, you can see at https://github.com/dotnetcore/CAP/issues/350#issuecomment-501946857

**Comment by yang-xiaodong** [comment]
duplicate of #350
