### ISSUE TITLE
RabbitMQ  Federation : SubscriberNotFoundException

### ISSUE THREAD

**Issue by kls121** [dotnetcore/CAP#361]
开启RabbitMQ的Federation插件在A B不同节点按照相同queue名进行传输时（为了跨网过安全网闸），遇到问题
1.在B节点创建一个A节点的Federation Upstreams
2.在B节点创建exchangeA以及queueB，RoutingkeyC
3.在B节点创建一个依赖queuesB的policy
4.在A节点创建exchangeA以及queueB，RoutingkeyC
通过以上操作从A节点可以将queueB队列传输传输到B节点，我已经通过程序测试通过
但是当使用cap时问题，读取B节点queueB队列消息时遇到https://github.com/dotnetcore/CAP/issues/63的提示，我已经在cap手动创建group，如果删掉B段的policy设置就不会出现问题

另外，请问一个应用程序中可以设置2个ExchangeName吗
非常感谢

**Comment by yang-xiaodong** [comment]
Sorry, I don't know about RabbitMQ Federation and can't help you.

CAP is designed to provide abstraction of message queues. If you rely on the specific functionality of a message queue, you can customize the implementation.

CAP does not support multiple ExchangeNames.
