### ISSUE TITLE
Any plan to support ActiveMQ?

### ISSUE THREAD

**Issue by lukazh** [dotnetcore/CAP#363]
Would be great for both self hosted ActiveMQ and Amazon MQ.

**Comment by expcat** [comment]
And redis stream?

**Comment by yang-xiaodong** [comment]
@lukazh ActiveMQ no C# client driver

**Comment by lukazh** [comment]
@yang-xiaodong https://www.nuget.org/packages/Apache.NMS.ActiveMQ/ isn't this?

**Comment by yang-xiaodong** [comment]
@lukazh  Does it support  .net standard?

**Comment by lukazh** [comment]
@yang-xiaodong oops, didn't notice that. https://www.nuget.org/packages/Apache.NMS.ActiveMQ.NetStd/ this one seems good.

**Comment by yang-xiaodong** [comment]
Hello @lukazh ,

I think we can list Amazon MQ as one of our plans, but ActiveMQ has fewer people to use, so I think it can be provided as a community extension.

Would you like to provide a community library for ActiveMQ extensions? We will provide you with links to the CAP home page and documentation.

**Comment by lukazh** [comment]
Actually, Amazon MQ is for ActiveMQ. LOL.

**Comment by yang-xiaodong** [comment]
got it , I think i means  `Amazon Simple Queue Service(SQS)`,

**Comment by lukazh** [comment]
:) I'll give it a try.

**Comment by yang-xiaodong** [comment]
Thank you for your community implementation, anyone who needs can find it here

https://github.com/lukazh/Lukaz.CAP.ActiveMQ
