### ISSUE TITLE
关于自动事务的问题

### ISSUE THREAD

**Issue by wangyue2017** [dotnetcore/CAP#364]
public class ServiceA : IServiceA
    {
        private readonly CustomAContext _customAContext;
        private readonly ICapPublisher _capBus;

        public ServiceA(CustomAContext customAContext, ICapPublisher capBus)
        {
            _customAContext = customAContext;
            _capBus = capBus;
        }
        public async Task Add()
        {
            using (var trans = _customAContext.Database.BeginTransaction(_capBus))
            {
                _customAContext.Test1s.Add(new Test1() { Name = "11111" });
               _customAContext.SaveChange();
                await _capBus.PublishAsync("CustomBService", new Test2() { Name = "222" });
                trans.Commit();
            }
        }
    }

    public class ServiceB : IServiceB, ICapSubscribe
    {
        private readonly CustomBContext _customBContext;
        private readonly ICapPublisher _capBus;
        public ServiceB(CustomBContext customBContext, ICapPublisher capBus)
        {
            _customBContext = customBContext;
            _capBus = capBus;
        }
        [CapSubscribe("CustomBService")]
        public async Task Add(Test2 test2)
        {
            _customBContext.Test2s.Add(test2);
            throw new System.Exception("1111");
            await _customBContext.SaveChangesAsync();
        }
    }

ServiceB 的订阅服务执行后会产生异常 commit提交时 A 服务的数据依然写入了表。 是因为异步导致先Commit执行后再 执行的ServiceB方法导致的？。 只有自动Commit的时候好像内部才是一个同步执行的结果 ,可以正常的回滚？？

**Comment by yang-xiaodong** [comment]
CAP采用的是最终一致性和本地消息表这种分布式事务解决方案。

建议先看下[这篇文章](https://www.cnblogs.com/savorboard/p/distributed-system-transaction-consistency.html)了解下分布式事务
