### ISSUE TITLE
Question: Returned already disposed transaction

### ISSUE THREAD

**Issue by Alksar** [dotnetcore/CAP#365]
https://github.com/dotnetcore/CAP/blob/8b821000c35101f3badb8734beb42ddcac802730/src/DotNetCore.CAP/Abstractions/CapPublisherBase.cs#L49

it seems to me that the disposed transaction object is returning, because MS DI disposing all resolved disposable object when scope is disposing

**Comment by yang-xiaodong** [comment]
Yes, this is a new issue introduced in 2.6.0 that we haven't fully tested yet

**Comment by yang-xiaodong** [comment]
Fixed in version `2.6.0-preview-80821564`
