### ISSUE TITLE
并发高的时候使用MYSQL作为持久化问题

### ISSUE THREAD

**Issue by k-yaobo** [dotnetcore/CAP#368]
并发高的时，CAP会操作Mysql频繁。导业务也受到影响。请问除了替换In-Memory Storage琮替代外。设置消息过期时间：SucceedMessageExpiredAfter 为5天。是不是可以减少对DB的操作？

或有什么好的方式。可以减小CAP对DB的操作？

谢谢

**Comment by yang-xiaodong** [comment]
你使用CAP的场景是什么，以及你的并发是什么业务产生的？ 抛开具体场景谈怎么优化没有意义。

**Comment by k-yaobo** [comment]
场景：公司员工在运营后台。选择广东地区100W用户，推送一条消息。  使用CAP。生产消息，订阅消息 处理推送。推送失败后重试5次。

**Comment by yang-xiaodong** [comment]
你这个是实现层面有问题，实际上推送给100W用户只应该产生一条消息。这个消息内容是生产这个消息的上下文参数。

比如你把用户信息存储到某个地方比如Redis，然后消息内容携带Redis参数，让消费者去消费Redis即可。

另外，我们做消息推送也并不是一下子把所有消息都发给100w用户，而是只推送在线用户，对于非在线用户在其登录或者在线的时候再去拉消息。
