### ISSUE TITLE
It can not receive message by `UseInMemoryMessageQueue`

### ISSUE THREAD

**Issue by chinaq** [dotnetcore/CAP#370]
It can not receive message by `UseInMemoryMessageQueue`

``` cs
// Startup.cs
...... 
            services.AddTransient<NBMeterDataArrivedIntegrationEventHandler>();
            services.AddCap(x => 
            {
                x.UseInMemoryStorage();
                x.UseInMemoryMessageQueue();
                x.UseDashboard();
            });
```

``` cs
// NBMeterDataArrivedIntegrationEventHandler.cs

    public class NBMeterDataArrivedIntegrationEventHandler : ICapSubscribe
    {
       ......

        [CapSubscribe(nameof(NBMeterDataArrivedIntegrationEvent))]
        public async Task HandleAsync(NBMeterDataArrivedIntegrationEvent @event)
        {
            _logger.LogInformation("######## handle data arrived event ########");
           ......
        }
    }
```

![Subscribers](https://user-images.githubusercontent.com/6382133/61604181-0e247e80-ac73-11e9-8411-654aab19350f.png)

![Published messages](https://user-images.githubusercontent.com/6382133/61604187-12509c00-ac73-11e9-9d2a-73d9e651288b.png)

![Received Messages](https://user-images.githubusercontent.com/6382133/61604270-6c516180-ac73-11e9-99b3-d1389fb1e25f.png)

**Comment by chinaq** [comment]
I copied the [Quick Start](http://cap.dotnetcore.xyz/user-guide/zh/getting-started/quick-start/), which did not receive any message as well.

**Comment by yang-xiaodong** [comment]
Issue copied to https://github.com/yang-xiaodong/Savorboard.CAP.InMemoryMessageQueue/issues/1 repo.
