### ISSUE TITLE
Receive kafka offset and partition of message 

### ISSUE THREAD

**Issue by cruisade** [dotnetcore/CAP#374]
Hello, is there a way to get kafka offset and partition from cap subscriber?
I want to store offset and partition to read message later from another process.

**Comment by yang-xiaodong** [comment]
Hello, there is no way to get it now, I think this can be used as an improvement.

**Comment by cruisade** [comment]
Do you have any thoughts about when you plan to add this feature?

**Comment by yang-xiaodong** [comment]
Hello,

I will consider how to implement this feature recently and apply it to version 2.7.

There are some preliminary ideas, we provide a message context object so that consumers can get some extra information, such as the following sample code:

```c#
[CapSubscribe("xxx.xxx")]
public void Consumer ([FromCap]MessageContext context)
{
    var offset =  context.Additional[KafkaConstant.Offset];
    var partition  =  context.Additional[KafkaConstant.Partition];
}
```

Do you have some better ideas? PR is welcome!

**Comment by yang-xiaodong** [comment]
In version 3.0, we added a custom header option in `KafkaOptions`. You can use this feature to add additional header in the consumption process. 

For example, you can add Offset or Partition by this way:

```C#
x.UseKafka(opt =>
{
    //...

    opt.CustomHeaders = kafkaResult => new List<KeyValuePair<string, string>>
    {
        new KeyValuePair<string, string>("my.kafka.offset", kafkaResult.Offset.ToString()),
        new KeyValuePair<string, string>("my.kafka.partition", kafkaResult.Partition.ToString())
    };
});

```

At the consumers, you can using `[FromCap]` inject `CapHeader` to get it.

```C#
[CapSubscribe("sample.kafka.postgrsql")]
public void HeadersTest(DateTime value, [FromCap]CapHeader header)
{
    var offset = header["my.kafka.offset"];
    var partition = header["my.kafka.partition"];
}
```

**Comment by yang-xiaodong** [comment]
v3.0 nuget package is released!
