### ISSUE TITLE
运行时错误，An exception occurred while executing the subscription method. Topic:toqo.services.down.card.result, Id:1156446939241656320

### ISSUE THREAD

**Issue by gooesfly** [dotnetcore/CAP#375]
本地环境没有错误，部署阿里云测试平台也没错误。在部署生产环境后，运行时出错。
错误信息如下：
 `warn: DotNetCore.CAP.DefaultSubscriberExecutor[0]
      The 1th retrying consume a message failed. message id: 1156448344459325440
fail: DotNetCore.CAP.DefaultSubscriberExecutor[0]
      An exception occurred while executing the subscription method. Topic:toqo.services.down.card.result, Id:1156448344459325440
DotNetCore.CAP.Internal.SubscriberExecutionFailedException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at WebAPIServer.Services.CardHelper.DownCardResult(DownAndDeleteResult result) in /src/WebAPIServer/Services/CardHelper.cs:line 67
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.<>c__DisplayClass30_0.<WrapVoidMethod>b__0(Object target, Object[] parameters)
   at DotNetCore.CAP.Internal.DefaultConsumerInvoker.ExecuteWithParameterAsync(ObjectMethodExecutor executor, Object class, String parameterString)
   at DotNetCore.CAP.Internal.DefaultConsumerInvoker.InvokeAsync(ConsumerContext context)
   at DotNetCore.CAP.DefaultSubscriberExecutor.InvokeConsumerMethodAsync(CapReceivedMessage receivedMessage)
   --- End of inner exception stack trace ---
   at DotNetCore.CAP.DefaultSubscriberExecutor.InvokeConsumerMethodAsync(CapReceivedMessage receivedMessage)
   at DotNetCore.CAP.DefaultSubscriberExecutor.ExecuteWithoutRetryAsync(CapReceivedMessage message)`

DotCore版本:2.2
DotNetCore.CAP版本：2.5.1
RabbitMQ使用： rabbitmq:3.7.7

求助，这个问题是怎么引起的？

已检查代码：Topic:toqo.services.down.card.result的信息无误。

其他相关代码
`         services.AddSingleton<IPublishService, PublishService>();
            services.AddSingleton<ISubscriberService, SubscriberService>();
            services.AddCap(x =>
            { 
                x.UseMySql(GloadBase.CAPMySqlConStr);
                x.UseRabbitMQ(r =>
                {
                    r.HostName = MQ_HostName;
                    r.Port = Convert.ToInt32(MQ_Port);
                    r.UserName = MQ_UserName;
                    r.Password = MQ_Password;
                });
                x.UseDashboard(); 
                x.FailedRetryCount = 5;
            });`

**Comment by gooesfly** [comment]
`   public class SubscriberService : ISubscriberService, ICapSubscribe
    {
        CardHelper card = new CardHelper();
    
        [CapSubscribe("toqo.services.delete.card.result")]
        public void DeleteCardResult(DownAndDeleteResult result)
        {
            card.DeleteCardResult(result);

        }
        [CapSubscribe("toqo.services.down.card.result")]
        public void DownCardResult(DownAndDeleteResult result)
        {
            card.DownCardResult(result);
        }
`

CardHelper 
`
        public void DownCardResult(DownAndDeleteResult result)
        {
            if (result == null)//为啥提示这行错误？不应该啊？
            {
                Console.WriteLine("DownCardResult=null");
                return;
            }
            //Console.WriteLine(result.ToString());
            try
            {
              //这里是我的业务代码
            }
            catch (Exception ex)
            {
                Console.WriteLine("DownCardResult="+ex.Message);
            }
          
        }`

**Comment by yang-xiaodong** [comment]
`SubscriberExecutionFailedException: Object reference not set to an instance of an object.`

看起来像是空指针异常导致，运行环境问题需要你自己排查哦，我帮不到你
