### ISSUE TITLE
CAP的默认实现的是生产者消费者模式？

### ISSUE THREAD

**Issue by a14907** [dotnetcore/CAP#376]
消息队列选择的是rabbitmq

我在使用中发现，默认的是生产者消费者模式！也就意味着当同一个key的消息有两个订阅者的时候，只有一个订阅能收到消息！

这不符合我的预期，我希望的是发布订阅模式。

我看了你的文档，发现你这里有group的概念，于是我在[CapSubscribe]这个特性里指定不同的group值：
[CapSubscribe("TestMsg", Group = "1")]
[CapSubscribe("TestMsg", Group = "2")]
这种情况下就都可以收到消息了！！

我这边想要知道并且确认的只有一件事：请问这个CAP的组件默认实现的是生产者消费者模式吗？

**Comment by yang-xiaodong** [comment]
这个不知道怎么解释，其实没必要纠结概念。

如果以 RabbitMQ 这边的概念来讲的话，参考：https://www.rabbitmq.com/getstarted.html ，CAP使用的第5种Topics模式。 

CAP和 Kafka 那边的概念是一致的，Topic 模式。

我不知道你所说的生产者消费者指的是不是 RabbitMQ那边的第三种发布订阅模式？

所有基于MQ的模式，他们都包含生产者和消费者... ， 那我问你能不能都叫生产者消费者模式呢？

**Comment by a14907** [comment]
我了解了。

发一个消息，每个服务只消费
