### ISSUE TITLE
TracingHeaders message field 

### ISSUE THREAD

**Issue by gfx687** [dotnetcore/CAP#378]
Hello, I am trying to integrate CAP with OpenTracing. 

I have found the `Helper.AddTracingHeaderProperty` method that looks like exactly for this purpose, but any data added as `TracingHeaders` will be overwritten in `BasePublishMessageSender.SendWithoutRetryAsync` with just empty `TracingHeaders` object. How can I add tracing metadata to messages? Or should I just add my logic and content field for it?

P.S. 
1. Here new TracingHeaders object are set to `eventData.Headers` (https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/IPublishMessageSender.Base.cs#L160)
2. And here my TracingHeaders data in Content overwritten because `tracingResult.Item2 != null` always true (because of p.1) (https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/IPublishMessageSender.Base.cs#L72)

**Comment by yang-xiaodong** [comment]
Hello ,

I need some time to get familiar with the OpenTracing part again. Here is an example that was tested last year. Maybe it works for you?

https://github.com/yang-xiaodong/OpenTracing.Contrib.CAP

PR is welcome!

**Comment by gfx687** [comment]
Yes, I got it now. Thanks!

**Comment by gfx687** [comment]
Hello again (reopened this issue instead of creating a new one)

I want to add tracing metadata to Content before saving it to a database (`CapDiagnosticListenerExtensions.WritePublishMessageStoreBefore`) so I will be able to create a new Span based on saved in DB. This way I will have the same TraceId for a whole process (from controller logic to consuming message by subscriber).
But the problem is: `WritePublishMessageStoreBefore` method sends content as a direct property of an anonymous object, so I cannot change it (add tracing metadata to message)
Is there any way to change `Content` value without writing additional layer of logic before sending a message to CapBus?

**Comment by gfx687** [comment]
Hello again!

In the last comment, I meant that I want to be able to add TracingHeaders to message on `CapDiagnosticListenerExtensions.WritePublishMessageStoreBefore` event, just like in `CapBeforePublish` and `CapBeforeConsume`.
I added small Pull Request with an example of what I want. I hope these changes won't break any backward compatibility

link: https://github.com/dotnetcore/CAP/pull/380

**Comment by yang-xiaodong** [comment]
Hello,

Thanks for your PR, it looks good!

The extra information I want you to know :

We will make some major updates in v2.7 (maybe named v3.0) with additional header information and code refactoring.

But it still takes a while time, I think we can merge the PR #380 and release it in the v2.6  so that it can be used for you.

Regarding the latest version about the tracing changes you can subscribe this issue to receive notice.

Thanks

**Comment by yang-xiaodong** [comment]
@gfx687  I have release version `2.6.0-preview-82001197` to NuGet, you can try it

**Comment by gfx687** [comment]
Great, thanks! Now everything works for me
(I am not sure if I should close an issue with an "enhancement" label by myself, so I will leave it to you if needed)

**Comment by yang-xiaodong** [comment]
Hello  @gfx687 ,

In v3.0, we have refactoring the Diagnostics. You can see how to connect APM at the Skywalking C# agent code.

**Agent code:**

https://github.com/yang-xiaodong/SkyAPM-dotnet/tree/master/src/SkyApm.Diagnostics.CAP

**SkyWalking UI:**

![image](https://user-images.githubusercontent.com/8205994/71006463-51025980-2120-11ea-82dc-bffa5530d515.png)
![image](https://user-images.githubusercontent.com/8205994/71006589-7b541700-2120-11ea-910b-7e0f2dfddce8.png)

**Comment by yang-xiaodong** [comment]
v3.0 nuget package is released!
