### ISSUE TITLE
纠正wiki中CAP仪表盘路径修改的问题

### ISSUE THREAD

**Issue by LouieGuo** [dotnetcore/CAP#379]
原文：仪表盘默认的访问地址是：http://localhost:xxx/cap，你可以在**d.MatchPath**配置项中修改cap路径后缀为其他的名字。

修改为：仪表盘默认的访问地址是：http://localhost:xxx/cap，你可以在UseDashnoard中**d.PathMatch**配置项中修改cap路径后缀为其他的名字。

**Comment by yang-xiaodong** [comment]
Would you want to submit a PR to improve it?
