### ISSUE TITLE
Throwing an exception using multiple ICapSubscribe services

### ISSUE THREAD

**Issue by jex518** [dotnetcore/CAP#38]
see CAP/src/DotNetCore.CAP/CAP.ServiceCollectionExtensions.cs

private static void AddSubscribeServices(IServiceCollection services)
        {
            var consumerListenerServices = new Dictionary<Type, Type>();
            foreach (var rejectedServices in services)
            {
                if (rejectedServices.ImplementationType != null
                    && typeof(ICapSubscribe).IsAssignableFrom(rejectedServices.ImplementationType))
                   **// here throw exception**
                    consumerListenerServices.Add(typeof(ICapSubscribe), rejectedServices.ImplementationType);
            }

**Comment by yuleyule66** [comment]
How can I reproduce this exception?

**Comment by jex518** [comment]
i used :
public class CabSubsService : ICabSubsService, ICapSubscribe
public class CabSubsService2 : ICabSubsService2, ICapSubscribe

in startup.cs
services.AddTransient<ICabSubsService, CabSubsService>();
services.AddTransient<ICabSubsService2, CabSubsService2>();

i  ran app，throw an error：
ArgumentException: An item with the same key has already been added. Key: DotNetCore.CAP.ICapSubscribe

**Comment by yuleyule66** [comment]
Thanks for your feedback, this is a bug.
I have fixed it on version `2.0.0-preview-20091963`
