### ISSUE TITLE
Passing Retries count to DiagnosticSource events

### ISSUE THREAD

**Issue by gfx687** [dotnetcore/CAP#383]
Hello! I have a problem with CAP logs + tracing

I cannot find error logs by TraceId because error/retries logs are written outside of `ActiveSpan` (it is disposed in `CapAfter*` and `CapError*` diagnostic source event observer https://github.com/yang-xiaodong/OpenTracing.Contrib.CAP/blob/master/src/DotNetCore.OpenTracing.CAP/CapDiagnostics.cs#L62) 
So I decided to write my own log in DS event observer but found out that Retries count is not passed as a parameter in DS events `CapErrorSubscriberInvoke` and `CapErrorPublish`

Is it possible to add Retries cound to these events' payload? It shouldn't break any backward compatibility

Pull Request link as an example of what I want: https://github.com/dotnetcore/CAP/pull/382

**Comment by yang-xiaodong** [comment]
Merged! 
We are adding extra header in the next version, thanks

**Comment by gfx687** [comment]
Where can I find a new version? Or I need to build a local package myself?

**Comment by yang-xiaodong** [comment]
I have pushed version `2.6.0-preview-82454970` to NuGet and contains PR #382
