### ISSUE TITLE
Multiple transports in same service

### ISSUE THREAD

**Issue by Alksar** [dotnetcore/CAP#384]
Hello,

In my service I have integrations with both rabbitmq and kafka. I want to use CAP for publish and consume messages. 

Is it possible to use CAP for simultaneous work of rabbitmq and kafka?
Do you have any suggestions to achieve this?

**Comment by yang-xiaodong** [comment]
Hello,

CAP not support using multiple transport at the same time.

Why do you need to use RabbitMQ and Kafka both?

**Comment by Alksar** [comment]
My service is inside big microservices architecture where the technologies suit each service the best way. My service is the integration service with [hexagonal architecture](https://alistair.cockburn.us/hexagonal-architecture/), so different transports are just diffenerent "ports". CAP works with rabbitmq and kafka the same way and that is very convinient. I also want to use CAP features such as outbox and retries.

**Comment by yang-xiaodong** [comment]
There is no plan to add this feature yet. 

Add the backlog label, It may be supported in future releases

**Comment by mviegas** [comment]
@yang-xiaodong would be happy to contribute to this, if necessary. We could make use of the native DI to inject multiple transports. On the other hand, using the outbox, the problem would lie on what do we do if one transport fails to publish when we have multiple.

**Comment by yang-xiaodong** [comment]
> the problem would lie on what do we do if one transport fails to publish when we have multiple.

Yes, I haven't thought of a good solution yet

**Comment by mviegas** [comment]
A possible solution would be to have a ‘sent’ flag per transport on the outbox. When one it’s published, set its flag.

**Comment by yang-xiaodong** [comment]
https://github.com/dotnetcore/CAP/issues/998#issuecomment-988659781
