### ISSUE TITLE
How to subscribe multiple message in console app

### ISSUE THREAD

**Issue by tuongntk** [dotnetcore/CAP#386]
Hi yang-xiaodong

 Follow by issues #275.
 I'd like to ask you how to subscribe multiple message in console app?

Tks so much

**Comment by yang-xiaodong** [comment]
You can add multiple consumer method to subscribe multiple message.

```cs
[CapSubscribe("sample.rabbitmq.mysql.test1")]
public void Subscribe1(DateTime time)
{
Console.WriteLine($@"{DateTime.Now}, Subscriber1 invoked, Sent time:{time}");
}

[CapSubscribe("sample.rabbitmq.mysql.test2")]
public void Subscribe2(DateTime time)
{
Console.WriteLine($@"{DateTime.Now}, Subscriber2 invoked, Sent time:{time}");
}
```

**Comment by tuongntk** [comment]
Tks yang
 But in your sample code i found that:
 public Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Timed Background Service is starting.");

            _timer = new Timer(Publish, null, TimeSpan.Zero, TimeSpan.FromSeconds(5));
return Task.CompletedTask;
        }

You start timer with Publish callback.
Is it right if i implement more and more subcribers methods. Does it affect to any method ?
Tks so much

**Comment by yang-xiaodong** [comment]
Timeer is just to show for example, you can publish or subscribe  messages wherever you want.

**Comment by tuongntk** [comment]
tks so much
