### ISSUE TITLE
Manual disable worker remove expired message

### ISSUE THREAD

**Issue by tuongntk** [dotnetcore/CAP#387]
Hi yang

 - I implemented CAP library to my api but I'd like to have 1 question relate to application performance because every 1 hour (default succeeded message expiration time span) the worker'll trigger and remove expired message. So does it affect to the app performance ? and if has is there any options to disable this worker and manual remove expired message by my own.

Tks you so much.

**Comment by yang-xiaodong** [comment]
The default `SucceedMessageExpiredAfter`  is one day, not one hour.

Docs at here:
http://cap.dotnetcore.xyz/user-guide/en/cap/configuration/#succeedmessageexpiredafter

You can change the default value by you want.

By the way, why did you think it will affect the app performance ?

**Comment by tuongntk** [comment]
Tks for ur supports.
- In my application has already included so many business logic, transactions commit to db. If i integrate to this libs also handle some background worker commit to persistent storage db. So i just consider it if whether am i wrong ? Or if u have the benchmark results would be great. Anyway, tks so much

**Comment by yang-xiaodong** [comment]
Your fears are superfluous, and the performance overhead of CAP relative to the application to the database is very small, enough to ignore

**Comment by tuongntk** [comment]
Tks yang-xiaodong
