### ISSUE TITLE
Does CAP support the rabbitmq image cluster?

### ISSUE THREAD

**Issue by woshiyongkai** [dotnetcore/CAP#389]
My rabbitmq is a mirror cluster of three nodes.
The result I hope is that when one of the node is down, There is no effect to the Application
Does CAP support the rabbitmq mirror cluster? and how should I configure it.

**Comment by yang-xiaodong** [comment]
using comma split connection string, like this:

```
x=>x.UseRabbitMQ("localhost:5672,localhost:5673,localhost:5674")
```

**Comment by woshiyongkai** [comment]
Hi Savorboard,
Thanks for your reply, this is the same as rabbitmq.client,that's great.
But how can I capture the consume ConnectionShutdown event?
In the rabbitmq.client is like this:
          var connection = factory.CreateConnection(new string[3] { "10.86.8.1", "10.86.8.2", "10.86.8.3" });
          **connection.ConnectionShutdown += Connection_ConnectionShutdown;**

**Comment by yang-xiaodong** [comment]
I think  `ConnectionFactoryOptions`  maybe is your demand.

http://cap.dotnetcore.xyz/user-guide/en/transports/rabbitmq/#connectionfactory-options
