### ISSUE TITLE
Cap's message queue keeps getting Scheduled

### ISSUE THREAD

**Issue by zhenlei520** [dotnetcore/CAP#392]
After cap sent the message, the message state was Scheduled and it took about 5 minutes to change it to success. Mysql database was used and C# transaction was adopted to handle the submission.
![image](https://user-images.githubusercontent.com/9740886/64013108-ad317580-cb51-11e9-8136-eae36f4c4664.png)
![image](https://user-images.githubusercontent.com/9740886/64013118-b15d9300-cb51-11e9-9daf-dc4ef850cbc9.png)
![image](https://user-images.githubusercontent.com/9740886/64013138-bae6fb00-cb51-11e9-8771-a497e9a438c8.png)

**Comment by yang-xiaodong** [comment]
You need start  the begin transaction using CAP's extension method `BeginTransaction`.

```
   using (var trans = dbContext.Database.BeginTransaction(_capBus, autoCommit: true))
        {
            //your business logic code

            _capBus.Publish("xxx.services.show.time", DateTime.Now);
        }

```

**Comment by zhenlei520** [comment]
Many thanks for your reply.

Changing the upload block to this will make the status as success, but occasionally the context has been released, I need to check again some time

![image](https://user-images.githubusercontent.com/9740886/64141888-6044ec00-ce3c-11e9-8f67-0dac346194bc.png)
