### ISSUE TITLE
It is recommended to add an automatic registration ICapSubscribe service feature

### ISSUE THREAD

**Issue by beefsteak** [dotnetcore/CAP#393]
Ex:AddCapSubscribes(typeof(Startup).GetTypeInfo().Assembly)

**Comment by yang-xiaodong** [comment]
You can extend your own consumer finder with the default  implementation provided by CAP.

https://github.com/dotnetcore/CAP/blob/47b1dc5c3e8dbc3196c03df2d2ebd2afe4cb6713/src/DotNetCore.CAP/IConsumerServiceSelector.Default.cs#L75

Override the `FindConsumersFromInterfaceTypes` method by yourself.

**Comment by beefsteak** [comment]
yes，it can work，thank you。but it would be more elegant to provide code like this
AddFluentValidation(config => config.RegisterValidatorsFromAssemblyContaining<Startup>())
or
AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies())
or
AddMediatR(typeof(Startup).GetTypeInfo().Assembly)

**Comment by John0King** [comment]
why not just register `ICapSubscriber` so CAP  can just consume   `IEnumerable<ICapSubscriber>`

https://github.com/dotnetcore/CAP/blob/47b1dc5c3e8dbc3196c03df2d2ebd2afe4cb6713/src/DotNetCore.CAP/IConsumerServiceSelector.Default.cs#L81-L92

+1 for @beefsteak

**Comment by yang-xiaodong** [comment]
@beefsteak  The goal of CAP is to keep it clean and small. Adding this non-specific requirement is not the core goal of CAP. CAP is flexible enough to allow users to expand rather than include all.

**Comment by beefsteak** [comment]
Suddenly I had an idea, CAP.Extensions.Microsoft.DependencyInjection  ;-)
