### ISSUE TITLE
CAP Dashboard missing files

### ISSUE THREAD

**Issue by DKincer87** [dotnetcore/CAP#398]
When running CAP Dashboard in Docker I get errors of missing js260 and cs260 files

![image](https://user-images.githubusercontent.com/13723162/64970300-7ce91700-d873-11e9-83c8-48aff4788358.png)

**Comment by yang-xiaodong** [comment]
How can I reproduce? Please report if you have the same issue in a non-Docker environment

**Comment by yang-xiaodong** [comment]
No response,  close
