### ISSUE TITLE
支持web配置HTTP方式消费，以及API接口发送消息，实验中~~

### ISSUE THREAD

**Issue by hu372197979** [dotnetcore/CAP#399]
![微信图片_20190919185041](https://user-images.githubusercontent.com/5925372/65238035-6c080200-db0e-11e9-90f1-a77737243a85.jpg)
![微信图片_20190919185046](https://user-images.githubusercontent.com/5925372/65238039-6f9b8900-db0e-11e9-8217-fea577a537a2.jpg)

**Comment by yang-xiaodong** [comment]
looks good
