### ISSUE TITLE
实例的代码我为什么运行不起来啊？

### ISSUE THREAD

**Issue by wang2650** [dotnetcore/CAP#40]
startup.cs

    public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<AppDbContext>();

            services.AddCap(x =>
            {
                x.UseEntityFramework<AppDbContext>();
                x.UseRabbitMQ("localhost:9092");
                x.UseSqlServer("Data Source=127.0.0.1;Initial Catalog=cap;User Id=sa;Password=123456;Connect Timeout=120;MultipleActiveResultSets=True");

            });

            services.AddMvc();
        }

controller

  public ValuesController(ICapPublisher producer, AppDbContext dbContext)
        {
            _capBus = producer;
            _dbContext = dbContext;
        }

        // GET api/values
        [Route("Publish")]
        [HttpGet]
        public IEnumerable<string> Publish()
        {

            _capBus.Publish("Web", "");
          
            return new string[] { "Web", "value2" };
        }

AppDbContext 

 public class AppDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //optionsBuilder.UseSqlServer("Server=192.168.2.206;Initial Catalog=Test;User Id=cmswuliu;Password=h7xY81agBn*Veiu3;MultipleActiveResultSets=True");
            optionsBuilder.UseSqlServer("Server=127.0.0.1;Initial Catalog=cap;User Id=sa;Password=123456;MultipleActiveResultSets=True");
        }
    }
执行的时候，_dbContext  是null啊。 
 public ValuesController(ICapPublisher producer, AppDbContext dbContext)
        {
            _capBus = producer;
            _dbContext = dbContext;
        }  这个是不是缺东西啊，还是有注入的地方要写啊。  我是用core2新建了网站测试的，代码扒实例的代码， 数据库的表生成了，mq也没问题。

**Comment by yuleyule66** [comment]
startup.cs `Configure `方法贴一下

**Comment by wang2650** [comment]
public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<AppDbContext>();

            services.AddCap(x =>
            {
                x.UseEntityFramework<AppDbContext>();
                x.UseRabbitMQ("localhost:9092");
                x.UseSqlServer("Data Source=127.0.0.1;Initial Catalog=cap;User Id=sa;Password=123456;Connect Timeout=120;MultipleActiveResultSets=True");

            });

            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvc();

            app.UseCap();
        }

**Comment by yuleyule66** [comment]
综上，看不出来有什么问题呀。。。
你调试一下，看 HttpContext.RequestServices 里面有没有AppDbContext

**Comment by wang2650** [comment]
![qq 20170821140814](https://user-images.githubusercontent.com/3048544/29953773-6a6b2e74-8f05-11e7-9402-57b60a25d4e9.png)    
option的conn链接字符串是有值的，但是   DbContextType 是没有值的，是不是和这个有关？

**Comment by yuleyule66** [comment]
![image](https://user-images.githubusercontent.com/8205994/29953904-5973d048-8f06-11e7-92db-57bb0dbd20a3.png)

不好意思，上次没看到。

**Comment by wang2650** [comment]
哦  谢谢 问题解决了。 我以为使用哪种数据库是通过x.UseSqlServer来判断的呢。
