### ISSUE TITLE
Cannot resolve scoped service 'xxDbContext' from root provider for version v2.6

### ISSUE THREAD

**Issue by ShenZZ** [dotnetcore/CAP#402]
#### 开发环境:
```
<PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP.RabbitMQ" Version="2.6.0" />
    <PackageReference Include="DotNetCore.CAP.SqlServer" Version="2.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.6" />
  </ItemGroup>
```

#### 数据库: sqlserver localdb 2016

经测试DotNetCore.CAP.SqlServer 2.5.1可以通过 而2.6.0会报错 100%重现

![cap2 6 0bug](https://user-images.githubusercontent.com/13758896/65816246-eb42b780-e22b-11e9-8702-bdd74da79fd8.jpg)

#### 错误堆栈:
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Cannot resolve scoped service 'Sample.RabbitMQ.SqlServer.AppDbContext' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at DotNetCore.CAP.SqlServerCapTransaction..ctor(IDispatcher dispatcher, IServiceProvider serviceProvider) in C:\projects\src\DotNetCore.CAP.SqlServer\ICapTransaction.SqlServer.cs:line 27
--- End of stack trace from previous location where exception was thrown ---

**Comment by yang-xiaodong** [comment]
It looks like a bug, I will fix it later, thanks for your report

**Comment by yang-xiaodong** [comment]
Hello, I am testing works normally, and can't reproduce your issue.

**Comment by yang-xiaodong** [comment]
The extension method `BeginTransaction` are not inject the DbContext service
```C#
        public static IDbContextTransaction BeginTransaction(this DatabaseFacade database,
            ICapPublisher publisher, bool autoCommit = false)
        {
            var trans = database.BeginTransaction();
            publisher.Transaction.Value = publisher.ServiceProvider.GetService<CapTransactionBase>();
            var capTrans = publisher.Transaction.Value.Begin(trans, autoCommit);
            return new CapEFDbTransaction(capTrans);
        }
```

**Comment by ShenZZ** [comment]
`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP.RabbitMQ" Version="2.6.0" />
    <PackageReference Include="DotNetCore.CAP.SqlServer" Version="2.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.6" />
  </ItemGroup>
</Project>`

`public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions option) : base(option) { }
        public DbSet<Person> Persons { get; set; }
    }`

`public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<AppDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddCap(x =>
            {
                x.UseEntityFramework<AppDbContext>();
                x.UseRabbitMQ(option => {
                    option.ConnectionFactoryOptions = action =>
                    {
                        Configuration.GetSection("rabbit").Bind(action);
                        action.AuthMechanisms = new List<AuthMechanismFactory>() { new AliyunMechanismFactory() };
                    };
                });
            });

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseMvc();
        }
    }`

`[Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        private readonly ICapPublisher _capBus;
        public ValuesController(ICapPublisher capPublisher)
        {
            _capBus = capPublisher;
        }

        [Route("~/ef/transaction")]
        public IActionResult EntityFrameworkWithTransaction([FromServices]AppDbContext dbContext)
        {
            using (
                var trans = dbContext.Database.BeginTransaction(_capBus, autoCommit: false))
            {
                dbContext.Persons.Add(new Person() { Name = "ef.transaction" });
                _capBus.Publish("sample.rabbitmq.mysql", DateTime.Now);
                dbContext.SaveChanges();
                trans.Commit();
            }
            return Ok();
        }
    }`

**Comment by hmoratopcs** [comment]
@yang-xiaodong Hi, I have the same problem. I have added a new sample to my fork (https://github.com/hmoratopcs/CAP/tree/master/src/DotNetCore.CAP.SqlServer). I'll be glad to make a pull request if you want to merge it.

I get the following exception when browsing to `http://localhost:38447/adonet/transaction` or `http://localhost:38447/ef/transaction`:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot resolve scoped service 'Sample.RabbitMQ.SqlServer.AppDbContext' from root provider.
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at DotNetCore.CAP.SqlServerCapTransaction..ctor(IDispatcher dispatcher, IServiceProvider serviceProvider) in ~\src\DotNetCore.CAP.SqlServer\ICapTransaction.SqlServer.cs:line 32
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in E:\A\_work\482\s\src\mscorlib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 132

```

A related question: Why is `_dbContext?.SaveChanges();` called at the `Commit` method of `SqlServerCapTransaction` but not at `MySqlCapTransaction` and `PostgreSqlCapTransaction`?

**Comment by hmoratopcs** [comment]
Hi @yang-xiaodong, thanks for reopening the issue. 

If I remove the line 

`_dbContext = serviceProvider.GetService(sqlServerOptions.DbContextType) as DbContext;`

from `SqlServerCapTransaction` it works fine for me. However, without that line, the 

`_dbContext?.SaveChanges();` 

which was added on purpose in the following commit loses its effect:

> committed on 25 Aug 2018 https://github.com/dotnetcore/CAP/commit/08ac461b5dd1de0ae328b526d844a8f76726009d#diff-9ce48cd162f0ebe3149fab1677e50fd5R30
> add save change when transaction commit

Do you remember why the `SaveChanges` was needed? Do you think it's safe for me to remove both lines and make a pull request?

**Comment by yang-xiaodong** [comment]
@hmoratopcs 
Hello, thank you for your continued follow-up on this issue. I have recently focused on the version 3.0 features. 
Is this exception only when using EF ?

**Comment by hmoratopcs** [comment]
I've tried to use `UseSqlServer` instead of `UseEntityFramework` at `Startup.cs` and it works, thanks.

**Comment by yang-xiaodong** [comment]
This is a bug and we will fix it in the next version

**Comment by yang-xiaodong** [comment]
v3.0 nuget package is released!
