### ISSUE TITLE
.net core 3.0 dashboard can not load js and css files

### ISSUE THREAD

**Issue by SlientHome** [dotnetcore/CAP#404]
For NetCore 3.0，Dashboard Can't Load Js And Css！

**Comment by MahmoudH96** [comment]
Me too, I am getting 404 for the following URLs:
https://localhost:44311/cap/js260
https://localhost:44311/cap/css260

**Comment by HuUncle** [comment]
I have throw this exception too

**Comment by HuUncle** [comment]
add this code 

![TIM图片20191118153320](https://user-images.githubusercontent.com/19486270/69032984-d6f38d80-0a18-11ea-889d-9800f036aa96.png)

**Comment by yang-xiaodong** [comment]
v3.0 nuget package is released!
