### ISSUE TITLE
关于IIS部署问题

### ISSUE THREAD

**Issue by ShenZZ** [dotnetcore/CAP#406]
#### 关于IIS部署问题 

应用池自动回收时host被关闭. 
这个期间没有任何请求, host就不会被启动,  意味着消息也不会被消费直到过期!

help: 有没有相关解决方案?

**Comment by kisshexuxia** [comment]
我也是IIS部署了webapi,一段时间不运行出现下面错误
warnwarnwarnwarn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer cancelled. --> amq.ctag-Vufflt1TUcUAO8qATD1BoQ
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer cancelled. --> amq.ctag-4-Bei5aQeC6-gBTz0pYFig
: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer cancelled. --> amq.ctag-yW5m53ES5nBB2WRU_frcXA
: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer cancelled. --> amq.ctag-8_ucgJ-Ut2ZOBilE3wkqHg
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer cancelled. --> amq.ctag-74Uke1K49RX-Ks6-jSl1Qw
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer cancelled. --> amq.ctag-STOXlrrqU-sHJ1BLT8Sxfw
: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer cancelled. --> amq.ctag-5frBX4cTDDc-LJ_Y7Fe-Rg
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer cancelled. --> amq.ctag-nyRWdJ1j-mag73F_tvjpEQ
warnwarnwarnwarn: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
      RabbitMQ client connection closed! --> Connection close forced
warnwarn: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
      RabbitMQ client connection closed! --> Connection close forced
: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
      RabbitMQ client connection closed! --> Connection close forced
: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
      RabbitMQ client connection closed! --> Connection close forced
warn: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
      RabbitMQ client connection closed! --> Connection close forced
: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
      RabbitMQ client connection closed! --> Connection close forced
warn: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
      RabbitMQ client connection closed! --> Connection close forced
: DotNetCore.CAP.RabbitMQ.ConnectionChannelPool[0]
      RabbitMQ client connection closed! --> Connection close forced
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer cancelled. --> amq.ctag-CGjQpM6sbKCgd-sUJDlSHQ
warnwarnwarn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer shutdown. --> Goodbye
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer shutdown. --> Goodbye
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer shutdown. --> Goodbye
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer shutdown. --> Connection close forced
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer shutdown. --> Goodbye
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer shutdown. --> Goodbye
: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer shutdown. --> Goodbye
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer shutdown. --> Goodbye
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer shutdown. --> Goodbye
: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer cancelled. --> amq.ctag-rAPBoNlt7zTnKK1gZZ5ppw
warn: DotNetCore.CAP.ConsumerRegister[0]
      RabbitMQ consumer shutdown. --> Connection close forced

**Comment by yang-xiaodong** [comment]
这不属于CAP的问题，建议自行查找解决方案

**Comment by ShenZZ** [comment]
#### 个人总结的解决方案:

1. 官方文档提示 如果使用IIS部署且需要服务一直处于运行状态 可以部署到Windows服务
https://docs.microsoft.com/zh-cn/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice

2. 同上建议也可以部署到 Kubernetes / Service Fabric / Azure Functions中

3. 可以关闭IIS应用程序池的自动回收

4. 前端可以轮询相关服务 比如30分钟请求一次以激活相关服务

**Comment by kisshexuxia** [comment]
谢谢杨老师、麻烦杨老师了。



------------------ 原始邮件 ------------------
发件人: "Sam"<notifications@github.com>; 
发送时间: 2019年10月9日(星期三) 下午2:07
收件人: "dotnetcore/CAP"<CAP@noreply.github.com>; 
抄送: "海里来的孩子"<shaojiefeng@vip.qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [dotnetcore/CAP] 关于IIS部署问题 (#406)




个人总结的解决方案:
  
 
官方文档提示 如果使用IIS部署且需要服务一直处于运行状态 可以部署到Windows服务
 https://docs.microsoft.com/zh-cn/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice
 
 
 
同上建议也可以部署到 Kubernetes / Service Fabric / Azure Functions中
 
 
 
可以关闭IIS应用程序池的自动回收
 
 
 
前端可以轮询相关服务 比如30分钟请求一次以激活相关服务
