### ISSUE TITLE
Concurrent problem with many micro-service instances

### ISSUE THREAD

**Issue by standardcore** [dotnetcore/CAP#41]
Message state should be update before executor invoking subscribe method on message subscriber microservice. A situation will happen when have many micro-service instances (eg. load balancing service start many same micro-services automatly and they are using same database instance) : 
A micro-service  instance is heading to update a message's status to `Processing` after this message has been changed and subscribe method should been invoke already by another micro-service instance, and subscribe method will be invoked again, but should be invoked just once and no more. 
I don't ensure this will cause any bad things or not, but it should invoid by check message update execution's afftected rows count, and break the method in time.

**Comment by yuleyule66** [comment]
I think there will be no this problem, when multiple subscribers subscribe to the same topic's message, so they will be in the same group, message queues are responsible for will only push message to one of them.

Are you doing the test and occur this problem?

**Comment by standardcore** [comment]
I have found this situation would happen.It can be re recurrent.
First I start two micro-service instances that subscribed same message name and two different message group.
Next publish a message with same name and two different group .
Then problem appeared.

**Comment by yuleyule66** [comment]
The different groups will all receive the same message this is expected, the same group will only receive once.

**Comment by HongyanShen** [comment]
@yuleyule66 If a service consists of many instances, updating message's status will cause an exception, for example: **should affect 1 row but affected 0 row actually**

**Comment by yuleyule66** [comment]
@HongyanShen Are you using Entity Framework?

**Comment by yuleyule66** [comment]
communicate with QQ , Closed !
