### ISSUE TITLE
How to use existing rabbitmq queue?

### ISSUE THREAD

**Issue by Alksar** [dotnetcore/CAP#411]
Hello, question in subject.

**Comment by Alksar** [comment]
my existing queue don't use "x-message-ttl" (none).

in source of cap i see that now it is impossible not to set "x-message-ttl". [link](https://github.com/dotnetcore/CAP/blob/843e99420d70eda0c0ce9f02c81c00aef74de80a/src/DotNetCore.CAP.RabbitMQ/RabbitMQConsumerClient.cs#L119).

may be [QueueMessageExpires (ttl)](https://github.com/dotnetcore/CAP/blob/843e99420d70eda0c0ce9f02c81c00aef74de80a/src/DotNetCore.CAP.RabbitMQ/CAP.RabbiMQOptions.cs#L74)  should be nullable filed with possibility dont pass the "x-message-ttl" parameter?

Thanks.

**Comment by yang-xiaodong** [comment]
Not support now , we will support custom headers in the next version.
