### ISSUE TITLE
Support for EntityFramework 3.0

### ISSUE THREAD

**Issue by kKen94** [dotnetcore/CAP#418]
![image](https://user-images.githubusercontent.com/46461611/67850828-7653ed80-fb09-11e9-8842-53e5027c9f5a.png)

I cannot start my project

**Comment by smallswan399** [comment]
That because the current CAP 2.6.0 is working with EF core 2 which don't have CommitAsync
If you are working with EF 3.0 then your code will try to call CommitAsync

**Comment by yang-xiaodong** [comment]
EF 3.0 not supported now , we will support it in next version!

**Comment by kKen94** [comment]
NetCore 3.1 was released one week ago, any updates? :)

**Comment by yang-xiaodong** [comment]
@kKen94  Expected this week, we will release 3.0 preview version.

**Comment by yang-xiaodong** [comment]
v3.0 nuget package is released!
