### ISSUE TITLE
为什么我通过VS2012打不开啊

### ISSUE THREAD

**Issue by CUMTZT** [dotnetcore/CAP#42]
C:\Users\98497\Desktop\CAP-dev_2.0\test\DotNetCore.CAP.Test\DotNetCore.CAP.Test.csproj : error  : 项目的默认 XML 命名空间必须为 MSBuild XML 命名空间。如果项目是用 MSBuild 2003 格式创建的，请将 xmlns="http://schemas.microsoft.com/developer/msbuild/2003" 添加到 <Project> 元素中。如果项目是用旧的 1.0 或 1.2 格式创建的，请将其转换为 MSBuild 2003 格式。  C:\Users\98497\Desktop\CAP-dev_2.0\test\DotNetCore.CAP.Test\DotNetCore.CAP.Test.csproj
这是打开错误的一条。。。。

**Comment by yuleyule66** [comment]
use Visual Studio 2017 15.3

**Comment by themikesam** [comment]
Do this have anysolution to open with Visual Studio 2015?
