### ISSUE TITLE
MySQL Connect Timeout expired exception

### ISSUE THREAD

**Issue by haptear** [dotnetcore/CAP#424]
# 环境
    <PackageReference Include="DotNetCore.CAP" Version="2.6.0" />
    <PackageReference Include="DotNetCore.CAP.Mysql" Version="2.6.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.2.6" />
    <PackageReference Include="Savorboard.CAP.InMemoryMessageQueue" Version="2.6.0" />
# 测试条件
   当开启10个线程间隔时间100毫秒同时发送消息时，会出现大量的mysql的连接并最后导致后期的消息都接收异常。
![image](https://user-images.githubusercontent.com/16282949/68679202-61ac3680-059a-11ea-83c6-310c54ecb4fe.png)
![image](https://user-images.githubusercontent.com/16282949/68679540-09296900-059b-11ea-8e97-1c76ad2e433a.png)

MySql.Data.MySqlClient.MySqlException (0x80004005): Connect Timeout expired.
 ---> System.OperationCanceledException: The operation was canceled.
 C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 46
  .......
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 570
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 443
   at DotNetCore.CAP.MySql.MySqlStorageConnection.StoreReceivedMessage(CapReceivedMessage message)
   at DotNetCore.CAP.ConsumerRegister.StoreMessage(CapReceivedMessage receivedMessage)
   at DotNetCore.CAP.ConsumerRegister.<>c__DisplayClass19_0.<RegisterMessageProcessor>b__0(Object sender, MessageContext messageContext)

# 测试项目
  https://github.com/haptear/TestCapConcurrent  调用start api 参数设置为 线程数10 间隔时间：100  就能重新

**Comment by Sky-nt** [comment]
我个人觉得消息接收异常的问题和MySQL 连接过多这个问题，因为我这两天一直在研究Mysql 连接过多的这个问题，同时也是用CAP发送和接收大量的消息队列进行的处理，CAP倒是挺稳定的，但是Mysql连接数却一直在增加，就算只写个控制台程序然后 EFCore+Pomelo.EntityFrameworkCore.MySql 对Mysql 进行连接，并且并不设置连接池的情况下，它也会出现这种情况，其实就是在你对数据库进行连接时就算没有设置连接池的情况下，它也默认走的是连接池的那种模式，但是却没有最大连接数的限制，也就是说在你高并发的情况下数据库在连接数不够用的时候他就会一直创建连接，并且用完以后并不会释放，而是就像设置了连接池一样进入了池里面并且不会自动释放，也没有最大连接数的限制。（以上是我这两天在无意中遇到高并发的情况下发现的问题，进行研究得出结论。）而且你的错‘ Connect Timeout expired.’ 我最近也遇到了，我觉的是数据库超时，而不是CAP的问题


以上是我个人的一些理解和研究所得出的结论，可能我能力不高，水平有限，所以理解的会有大部分偏差，所以上面那一段仅供参考，并且不保证我说的百分百正确性，但是希望可以帮到你，如果有大佬看到我说的并且觉得是错的话，请大佬在下面给我进行纠正，我将万分感谢

**Comment by haptear** [comment]
我在mysql的连接字符串种设置了连接池的大小限制为50，mysql的连接j监视可以看到最大也是50个，mysql数据库本身的最大连接数设置为200，但是还是一样出现Connect Timeout expired的错误，
![123](https://user-images.githubusercontent.com/16282949/68728557-96ec6f00-0602-11ea-9a8d-3f3100565ea3.png)

**Comment by yang-xiaodong** [comment]
@haptear 请测试一下，不经过CAP直接使用 mysqlconnector 并发请求操作数据库是否能重现此问题

**Comment by cuibty** [comment]
@yang-xiaodong published 和 received 的 ExpiresAt 字段没加索引，在回收的时候，会把整个表锁住。并发的时候会出现锁等待。

https://github.com/dotnetcore/CAP/blob/275b5b5ed1fbdf474994f86d9a207dec3ef4f845/src/DotNetCore.CAP.MySql/ICollectProcessor.MySql.cs#L46

**Comment by yang-xiaodong** [comment]
@cuibty delete非索引字段会锁表，是否有相关资料？

**Comment by haptear** [comment]
@yang-xiaodong 
代码调整为直接操作数据，每秒100条添加没有任何问题
```csharp
Task.Run(async () =>
                {
                    using (var connection = new MySqlConnection(AppDbContext.ConnectionString))
                    {
                        await connection.ExecuteAsync(PrepareSql(), new CapPublishedMessage()
                        {
                            Id = index,
                            Added = DateTime.Now,
                            Content = "{}",
                            ExpiresAt = DateTime.Now.AddDays(1),
                            Name = "datahub.eventbus.notify",
                            Retries = 0,
                            StatusName = "Succeeded"
                        });
                        return;
                    }
                    //await _capPublisher.PublishAsync(LocalGlobalParam.EventBusMessage, message);
                });
```

**Comment by yang-xiaodong** [comment]
@haptear 我看了你测试仓库的代码，https://github.com/haptear/TestCapConcurrent/blob/master/Controllers/TestCapController.cs#L70  你使用的异步发送的 ，但是并没有加 `await`, 请添加一下再进行测试

**Comment by yang-xiaodong** [comment]
@haptear 是否有添加`await`进行测试呢？

**Comment by haptear** [comment]
@yang-xiaodong  我更新了测试代码，使用await调用 还是出现异常

**Comment by yang-xiaodong** [comment]
你使用循环这种测试方法Task.Run 我感觉是有问题的。 使用 wrk 压测是否会出现这个问题呢？

**Comment by haptear** [comment]
确定是环境问题
