### ISSUE TITLE
Table lock when collector expired data for mysql

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnetcore/CAP#425]
This issue is raised from #424, @cuibty indicates that when reclaiming mysql expired data, the table lock is caused when ExpiresAt field is not set index.

此问题引发自 #424，@cuibty 指出在回收mysql过期数据时，由于  ExpiresAt 字段未设置索引会导致表锁问题。

**Comment by yang-xiaodong** [comment]
@cuibty 

According to official, deleting a non-indexed field does not cause a table lock.  docs at here:

https://dev.mysql.com/doc/refman/8.0/en/innodb-locks-set.html
		
> DELETE FROM ... WHERE ... sets an exclusive next-key lock on every record the search encounters. However, only an index record lock is required for statements that lock rows using a unique index to search for a unique row.

**Comment by haptear** [comment]
@yang-xiaodong 
把IStorageTransaction.MySql.cs下的UpdateMessage方法注释了，就没有出现问题，由此可推测应该是时update和insert的并发时锁导致。
```chsarp
 public void UpdateMessage(CapPublishedMessage message)
        {
            return;
            if (message == null)
            {
                throw new ArgumentNullException(nameof(message));
            }
            
            var sql =
                $"UPDATE `{_prefix}.published` SET `Retries` = @Retries,`Content`= @Content,`ExpiresAt` = @ExpiresAt,`StatusName`=@StatusName WHERE `Id`=@Id;";
            _dbConnection.Execute(sql, message);
        }
```

**Comment by cuibty** [comment]
@yang-xiaodong 在 expiresat 未加索引时，复现此问题。

会话1
 set autocommit = 0 -- 手动提交事务
 delete from `cap.published` where expiresat < '2019-11-13 13:52:45';
此时会话1，一直不提交事务。

会话2
此时在会话2中，执行 update 的语句将出现 `LOCK WAIT` 。

使用如下语句将可以查看正在执行在事务。
SELECT * FROM `information_schema`.`INNODB_TRX`;

![Snipaste_2019-11-13_14-06-27](https://user-images.githubusercontent.com/12811343/68737590-dd4fc700-061e-11ea-8daf-1e425b0df08c.png)

参考资料：http://www.thinkphp.cn/topic/41577.html

**Comment by yang-xiaodong** [comment]
@cuibty 
根据官方描述，在使用 `DELETE FROM ... WHERE ` 语句删除**未进行索引**的字段时，会使用 `next-key` 锁进行记录的锁定，有关 `next-key` 锁的更多信息可以参考这里的文档。
 https://dev.mysql.com/doc/refman/8.0/en/innodb-locking.html#innodb-next-key-locks

我大概看了下，是系统根据索引的叶节点的一个开闭范围，针对数据列是数字的话可能是一个前后范围，我们当前的是日期列，具体怎么计算的我还没有搞太清楚 ，但肯定不是锁定整个表。

无论如何，我认为此处在日期列添加索引总是有益的，你愿意提交一个 PR 来改进此问题吗？ 非常感谢

**Comment by haptear** [comment]
@yang-xiaodong @cuibty  按照上面的方法，在published和received表中对ExpiresAt添加索引，
使用 https://github.com/haptear/TestCapConcurrent 项目进行测试，还是报错。
```sql
CREATE TABLE `cap.published` (
  `Id` bigint(20) NOT NULL,
  `Version` varchar(20) DEFAULT NULL,
  `Name` varchar(200) NOT NULL,
  `Content` longtext,
  `Retries` int(11) DEFAULT NULL,
  `Added` datetime NOT NULL,
  `ExpiresAt` datetime DEFAULT NULL,
  `StatusName` varchar(40) NOT NULL,
  PRIMARY KEY (`Id`),
  KEY `IX_ExpiresAt` (`ExpiresAt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by yang-xiaodong** [comment]
@haptear 你说的问题请在另外你开的issue中讨论。

当前问题已解决，关闭

**Comment by sheng-jie** [comment]
@yang-xiaodong @cuibty  当时添加索引，没有考虑向后兼容的问题吗，直接在创建表脚本中加索引，对之前创建的CAP表无用？创建索引时，也应该先判断是否存在，不存在则创建。
