### ISSUE TITLE
Question about how to using RabbitMQ

### ISSUE THREAD

**Issue by haoas** [dotnetcore/CAP#433]
现在cap使用rabbitmq，是和queue绑定的？如果服务a是发布者，服务b既是发布者，也是a的订阅者，服务b 的订阅和发布可以使用不同的队列吗？

**Comment by yang-xiaodong** [comment]
你的理解可能有问题。

CAP屏蔽了底层的消息传输，我们讨论应该是基于上层ＣＡＰ的使用方式以及概念来进行。

现在你提的问题，既有底层这种和具体ＭＱ有关系的绑定，又有上层发布订阅这种逻辑概念的使用方式，所以我无法理解你的意思。

**Comment by yang-xiaodong** [comment]
no response , closed!
