### ISSUE TITLE
What's the lifetime of subscriber instance created by CAP in asp.net core?

### ISSUE THREAD

**Issue by virtualbiz** [dotnetcore/CAP#438]
Transient? Scoped?
I'm asking because I want to know how I could pass the dependent object to my subscribers? For example, if the subscriber itself is Scoped, I don't need to pass the IServiceScopeFactory. Instead I can directly inject my Scoped service into the subscriber constructor.

**Comment by yang-xiaodong** [comment]
CAP will create scoped lifetime before calling subscriber instance , so register the lifetime according to the needs of your other methods without [CapSubscribe]

**Comment by virtualbiz** [comment]
Did you mean [CapSubscribe] and explicit registration via services.Add<xxx> are mutually exclusive?

**Comment by yang-xiaodong** [comment]
No, A service method may include many methods, it may include a CAP subscription method or other business code methods. 
I mean when registering a service into DI, you can register according to the needs of these business methods.

**Comment by virtualbiz** [comment]
So if I simply use the default configuration, using [CapSubscribe] instead of explicit registration, all subscriber object instances will be Scoped, right?

**Comment by yang-xiaodong** [comment]
You must explicit registration, [CapSubscribe] does not register automatically Except in Controller

**Comment by virtualbiz** [comment]
I see. Thanks a lot.
