### ISSUE TITLE
Autofac can not resolve ICapSubscribe?

### ISSUE THREAD

**Issue by LEEJLU** [dotnetcore/CAP#439]
>  //option 1 : NOT work
> //builder.RegisterType<`CapSubscribe`>().As<`ICapSubscribe`>();
> 
>  var serviceCollection = new ServiceCollection();
> 
> //option 2 : Works fine
> //serviceCollection.AddTransient<`ICapSubscribe`, `CapSubscribe`>();
> 
> serviceCollection.AddCap(x =>
> {
>    x.UseEntityFramework<ApplicationDbContext>();
>    x.UseRabbitMQ("localhost");
>    x.UseDashboard();
> });
> builder.Populate(serviceCollection);

**Comment by yang-xiaodong** [comment]
see https://github.com/dotnetcore/CAP/issues/224#issuecomment-472330886
