### ISSUE TITLE
为什么mq消息会这样接收?

### ISSUE THREAD

**Issue by 3151036158** [dotnetcore/CAP#440]
![image](https://user-images.githubusercontent.com/57855444/69719464-8502e400-114b-11ea-94d7-19f9c34a27fb.png)
是不是跟这个有关系
warn: DotNetCore.CAP.Processor.MessageNeedToRetryProcessor[1]
      Get messages of type 'CapPublishedMessage' failed. Retrying...
System.MissingMethodException: Method not found: 'System.Collections.Async.IAsyn
cEnumerable`1<!!0> System.Collections.Generic.IEnumerableExtensions.ToAsyncEnume
rable(System.Collections.Generic.IEnumerable`1<!!0>, Boolean)'.
   at DotNetCore.CAP.InMemoryStorage.InMemoryStorageConnection.GetPublishedMessa
gesOfNeedRetry()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine
](TStateMachine& stateMachine)
   at DotNetCore.CAP.InMemoryStorage.InMemoryStorageConnection.GetPublishedMessa
gesOfNeedRetry()
   at DotNetCore.CAP.Processor.MessageNeedToRetryProcessor.GetSafelyAsync[T](Fun
c`1 getMessagesAsync)

**Comment by 3151036158** [comment]
为什么发2条丢一条

**Comment by 3151036158** [comment]
在家里     变成发三条收到一条  
![image](https://user-images.githubusercontent.com/57855444/69721622-3572e700-1150-11ea-8afb-b239a41c40db.png)

**Comment by 3151036158** [comment]
我今天试试看能找出是什么问题不 ,参考文档  Diagnostics 提供一组功能使我们能够很方便的可以记录在应用程序运行期间发生的关键性操作以及他们的执行时间等，使管理员可以查找特别是生产环境中出现问题所在的根本原因。

**Comment by yang-xiaodong** [comment]
请提供环境信息。 版本，配置，发送和接收的样例代码，如果可能请提供测试repo

**Comment by 3151036158** [comment]
https://github.com/dotnetcore/CAP/issues/63 正解

**Comment by cocosip** [comment]
我们在使用中遇到了同样的异常信息。
CAP使用的 Kafka+ MemoryStorage
我们测试了.net core 3.0, 3.1, 2.2 的web项目。在3.0+的web项目上都会抛出该异常。在2.2的web项目上正常运行。 在控制台项目中,没有捕获到异常。
