### ISSUE TITLE
support delayqueue(rabbitmq) in next version?

### ISSUE THREAD

**Issue by sd797994** [dotnetcore/CAP#442]
你好，我想了解一下官方有预期在下一个版本中对延迟队列进行支持吗？
我们目前采用CAP作为我们的事件总线，但是很多业务场景中需要订阅端延迟消费消息（例如在订单创建30分钟内如果未支付将自动作废订单）
如果采用cap订阅接受消息并将指令传入作业系统(hangfire或类似)进行轮询显然在开销上是不太乐观的。
       目前我们的做法是通过自定义一个“预延迟”交换机将CAP交换机作为“x-dead-letter-exchange”绑定上去，
       通过发送消息到“预延迟”交换机等待超时后发送死信给CAP来实现的延迟队列。目前我的担心是基础框架随着CAP版本升级，我们相应的代码也要调整，
       我希望官方是否可以考虑在下一个迭代周期中考虑添加延迟消费机制(rabbitmq)？谢谢！

**Comment by yang-xiaodong** [comment]
AMQP协议默认是没有消息延迟功能的，RabbitMQ利用`x-dead-letter-exchange`也是它的一个扩展功能，但是这并不属于消息队列的职责范围，CAP是基于消息队列上层提供的抽象，所以这种特定MQ提供功能我们一般不考虑。

另外你说的 `采用cap订阅接受消息并将指令传入作业系统(hangfire或类似)进行轮询显然在开销上是不太乐观的` 我不太认同，就是因为系统中有很多场景需要才更需要引入作业调度框架，延迟只是调度框架的一个功能，难道你们没有需要运行定时任务的场景吗？如果有那么还是需要引入调度框架 ，因为这种功能本身就是属于调度范畴了。

我想你们目前利用 `'x-message-ttl` 和 `x-dead-letter-exchange` 共同来实现的这个需求，但是这两个属性都是在创建队列的时候指定的参数，就像你的举例 (`在订单创建30分钟内如果未支付将自动作废订单`)，那么一般情况下不同订单的关闭时间是不一样的，比如如果购买了促销商品可能是15分钟关闭，其他的可能是1个小时又或者是几天, 这样一个业务是不是要创建很多个队列呢？如果系统中这种关闭事件是动态的，你又如何处理呢？

**Comment by sd797994** [comment]
感谢杨总回复， 是我之前没有考虑清楚，因为是临时插进来的需求所以没有多加考虑就最先认为应该上延迟队列在事件总线这里来处理。后来自己也觉得不太符合设计要求就主动关闭问题了，再次感谢
