### ISSUE TITLE
 Cap retrying database connection problem

### ISSUE THREAD

**Issue by zhujiancc** [dotnetcore/CAP#444]
if database connection  is invalid ,  cap retrying  too crazy , 
make other normal server hang up
![image](https://user-images.githubusercontent.com/19665595/69928715-7889dd00-14f7-11ea-89f4-ed7cad0ac143.png)

you can use a invalid conn to repetition the problem

**Comment by yang-xiaodong** [comment]
Thanks for your reporting, we will optimize this in the next version

**Comment by yang-xiaodong** [comment]
v3.0 nuget package is released!
