### ISSUE TITLE
Add consumer qos option for rabbitmq

### ISSUE THREAD

**Issue by woshiyongkai** [dotnetcore/CAP#445]
I see that the message confirming is manual. If so, why not add peak clipping?
And enable it by RabbitmqOptions.

**Comment by yang-xiaodong** [comment]
What is `peak clipping`?  any docs or links about  this feature?

**Comment by woshiyongkai** [comment]
Haha,this word is better "Peak shaving".  like this :
```
//before BasicConsume
if(_rabbitMQOptions.EnablePeakShaving)
        _channel.BasicQos(0, _rabbitMQOptions.PrefethCount, false);
_channel.BasicConsume(_queueName, false, consumer);
```

**Comment by yang-xiaodong** [comment]
Temporarily closed, consider whether support in future versions

**Comment by yang-xiaodong** [comment]
Sincee RabbitMQ configuration supports global configuration, so we don’t consider supporting it now.

https://www.rabbitmq.com/consumer-prefetch.html#default-limit
