### ISSUE TITLE
MySql Connect Timeout expired exception in linux

### ISSUE THREAD

**Issue by 3223554** [dotnetcore/CAP#451]
部署环境：k8s
dotnet core skd、runtime：2.2
基础设施：kafka、mysql
部署pod的资源：cpu:300m,内存：256M
施压程序：jmeter 施压200并发
施压代码：为官方demo
施压版本：2.5.1
![被压测代码](https://user-images.githubusercontent.com/16113293/70588546-0e182180-1c08-11ea-9cdf-7b6080f9bd86.png)

由于使用生产环境 经常造成节点的pod，假死问题，影响客户使用，我们进行了全方面的压测，最终排查到是在cap里面中的问题

在未修复的情况下压测结果
![原版压测结果](https://user-images.githubusercontent.com/16113293/70588474-d14c2a80-1c07-11ea-8cc8-6c9b5932e179.png)

控制台输出的异常
![控制台输出](https://user-images.githubusercontent.com/16113293/70588704-8d0d5a00-1c08-11ea-80f9-809bcdfd6403.png)

qps：平均只有12.4/s 最小响应时间217ms 最大响应时间60003ms 平均响应时间：5789ms

后续排查问题发现
![原版](https://user-images.githubusercontent.com/16113293/70588558-1a9c7a00-1c08-11ea-87b9-e3850323c2e1.png)
在发送消息时，使用了同步调用异步代码，讲此段修改为
![图片](https://user-images.githubusercontent.com/16113293/70588590-33a52b00-1c08-11ea-99d5-1fc1e63ed1f0.png)
异步执行
压测结果
![修改后](https://user-images.githubusercontent.com/16113293/70588617-4c154580-1c08-11ea-9063-c0c3afeb1e26.png)
qps：平均在535 最低响应时间为373ms 最大响应时间 6694ms 平均响应时间为 373ms

**Comment by 3223554** [comment]
2.6.1还未测试 
如果存在同样的肯定希望官方修复下，不然以后升级不了
还有一个问题 希望topic与消费者的名称 中间的连接符可以自定义 目前是固定的“.”号  但是阿里云的kafka是不能创建包含"." 号的名称

**Comment by yang-xiaodong** [comment]
2.6.1版本这块代码有调整，能测试下是否可以复现么？

**Comment by 3223554** [comment]
@yang-xiaodong 你的意思是 让我再压下2.6吗

**Comment by yang-xiaodong** [comment]
> @yang-xiaodong 你的意思是 让我再压下2.6吗

是的

>希望topic与消费者的名称 中间的连接符可以自定义 目前是固定的“.”号 但是阿里云的kafka是不能创建包含"." 号的名称
你指的是哪个地方？ kafka的消费者名称就是topic啊

**Comment by 3223554** [comment]
@yang-xiaodong 我知道。我的意思是 中间的连接符可以 自定义。目前  好像都是点号  阿里云创建队列的时候 名称不能 包含点号

**Comment by 3223554** [comment]
@yang-xiaodong 我们目前是手动的把点号去掉了

**Comment by 3223554** [comment]
@yang-xiaodong 下午的时候 我对2.6 压一下 施压结果 我发到这里

**Comment by 3223554** [comment]
压测2.6 依然存在这个问题
施压前提条件和文中第一栏一致
cap版本：2.6.0
压测结果：
![2 6 0旧版压测结果](https://user-images.githubusercontent.com/16113293/70596815-c1414480-1c21-11ea-85ca-e15e62b7de74.png)
问题代码：
![2 6 0没修改](https://user-images.githubusercontent.com/16113293/70596853-d4ecab00-1c21-11ea-8ac4-3eddf5c74e3a.png)
![2 6 0没修改2](https://user-images.githubusercontent.com/16113293/70596860-d9b15f00-1c21-11ea-9b53-73feb2502726.png)

修改为：
![2 6 0修改1](https://user-images.githubusercontent.com/16113293/70596874-e2099a00-1c21-11ea-8a9c-9e51298bbe4a.png)
![2 6 0修改2](https://user-images.githubusercontent.com/16113293/70596877-e46bf400-1c21-11ea-9906-48ff61a4c4a2.png)
修改后压测结果
![2 6 0修改后](https://user-images.githubusercontent.com/16113293/70596898-efbf1f80-1c21-11ea-9daf-189608fb2051.png)
这个问题的本质就是 异步代码中调用了同步代码，同步代码又调用了异步代码 导致了上下文死锁了

@yang-xiaodong

**Comment by 3223554** [comment]
还有两个需求需要你们看能不能支持
1、同一条消息，同一个GROUP，不要反复接收（如果判断出来已经接收过，就不要写入数据库，这个当kafka不正常时，同一条消息会反复接收）
2、消费者 Group=option.group+'.'+version,中间的'.'可以自定义

**Comment by yang-xiaodong** [comment]
@3223554 你好，我这边也压测了一下，没有出现你说的问题。

环境：.net core 2.2,  windows 10,   cap v2.6 ,   mysql 5.7 , rabbitmq
施压工具：wrk  
参数如下：
```
wrk -c 200 -t 4 -d 60  http://localhost:5000
```

新建的 asp.net core 2.2 webapi 项目

**Startup.cs** 

```cs
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddCap(opt =>
        {
            opt.UseMySql("Server=localhost;Database=testcap;UserId=root;Password=123123;");
            opt.UseRabbitMQ("localhost");
        });

        services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        app.UseMvc(routes =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}/{id?}");
        });
    }
}
```

**HomeController.cs**

```
    public class HomeController : Controller
    {
        private readonly ICapPublisher _capPublisher;
        private readonly Random _random = new Random();

        public HomeController(ICapPublisher capPublisher)
        {
            _capPublisher = capPublisher;
        }

        public async Task<IActionResult> Index()
        {
            await _capPublisher.PublishAsync("FooDto", new FooDto() { Id = _random.Next(10000), Bar = "test string" });

            return Ok();
        }
    }

    public class FooDto
    {
        public int Id { get; set; }

        public string Bar { get; set; }
    }
```

---

压测时间一分钟，并发200，4个线程

和你的环境不一样的是，因为我是 windows 所以使用的RabbitMQ，另外是在windows 运行的，这应该不影响结果。

这个是RabbitMQ管理控制台看到的吐屯量截图：

![image](https://user-images.githubusercontent.com/8205994/70621319-42193400-1c54-11ea-99f5-6afc35539eab.png)

测试结果截图：

![image](https://user-images.githubusercontent.com/8205994/70621367-5b21e500-1c54-11ea-9863-fd224ea5a97f.png)

数据库截图：

![image](https://user-images.githubusercontent.com/8205994/70621392-6aa12e00-1c54-11ea-8093-418ce41aca33.png)

程序运行截图 :

![image](https://user-images.githubusercontent.com/8205994/70621459-9a503600-1c54-11ea-911e-34ba646c346f.png)

**Comment by 3223554** [comment]
你试下部署在linux下 要linux 才能重现

**Comment by yang-xiaodong** [comment]
为了还原你说的死锁问题，我又进行了如下测试：

**HomeController.cs**

```cs
        public IActionResult Index()
        {
            //场景还原
            SyncMethod();

            return Ok();
        }

        public void SyncMethod()
        {
            Task.Run(async () => await AsyncMethod());
        }

        public async Task AsyncMethod()
        {
            using (var connection = new MySqlConnection("Server=localhost;Database=testcap;UserId=root;Password=123123;"))
            {
                await connection.ExecuteAsync("insert into test(id,name) values(1,'test name')");
            }
        }
```

压测结果：

![image](https://user-images.githubusercontent.com/8205994/70622275-86a5cf00-1c56-11ea-9e84-34c58fc0ead7.png)

没有出现你说的死锁等情况，你说的 `异步代码中调用了同步代码，同步代码又调用了异步代码 导致了上下文死锁了` 我并不太赞同，只有发生了线程切换才有可能会造成你说的情况，我们这里使用Task.Run并不会发生线程切换

**Comment by 3223554** [comment]
你可以用linux 尝试下呀
还有就是我发现 同步方式也有问题
也是把 wait.getResuft 换成了你下面这种写法 才没有问题

**Comment by yang-xiaodong** [comment]
@3223554 请问你是同一个实例，边发送边消费吗？ 还是单独只发送？

**Comment by 3223554** [comment]
只发送 没有消费 
就是压的demo代码

**Comment by 3223554** [comment]
我们是用的docker k8s 但是我觉得我用linux就可以重现 我们之前自己封装rpc框架的时候 碰到过类似的问题 也是部署到交付测试环境 才暴露出来的 我们本地开发用的windows环境

**Comment by yang-xiaodong** [comment]
嗯，感谢反馈，我明天找个linux测试下。

我们线上也是k8s, 没有遇到过你说的问题，可能是我们并发量还达不到吧。

你们现在qps大概多少出现的？

**Comment by 3223554** [comment]
他的异常方式 抛出来 就是这样啊 并发连接数应该不高 我用的是我们交付测试环境测试的 目前压测因为确实是这个情况 施压200并发 直接出现了 还不是施压一段时间后出现的

**Comment by yang-xiaodong** [comment]
@3223554 你好，我使用 3.0 版本在 linux 重现了
```
"Host 'xxx' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'"
```
这里是我这里首先出现的异常，然后就是 Connection Timeout， 原因我推测是 Task.Run 造成的 MySql 连接被占用完毕进而引发超时。至于 Windows 为什么复现不了具体原因还未知。 

我们将在 v3.0  修复此问题，感谢你的反馈。

**Comment by 3223554** [comment]
同步方法也有问题  我改了之后 引发出另外一个mysql  连接已被使用的问题  目前还在排查是哪里的问题 到时候再联系你们

**Comment by 3223554** [comment]
@yang-xiaodong 还有就是我说的那两个需求 你看啥时候加入到版本计划中去  
1、同一条消息，同一个GROUP，不要反复接收（如果判断出来已经接收过，就不要写入数据库，这个当kafka不正常时，同一条消息会反复接收）
2、消费者 Group=option.group+'.'+version,中间的'.'可以自定义
第二条我看了下 也有其他开发者提了 主要是云厂商的kafka 创建消费者或者topic的时候 不能用.号

**Comment by yang-xiaodong** [comment]
> 1、同一条消息，同一个GROUP，不要反复接收（如果判断出来已经接收过，就不要写入数据库，这个当kafka不正常时，同一条消息会反复接收）

这个不会加，需要幂等性地方，需要消费者自己保证，框架无法保证。

> 2、消费者 Group=option.group+'.'+version,中间的'.'可以自定义

这个我们评估下

**Comment by 3223554** [comment]
@yang-xiaodong 好的 非常感谢

**Comment by yang-xiaodong** [comment]
@3223554 你反馈的这个问题原因我排查出来了，不是CAP的问题，之所以你加了await不再出现是因为这种方式降低了对数据库的并发能力。

原因和我预想的一样，是由于 MySqlConnector 组件在你没有指定连接池的情况下，默认是100个连接，当你的并发超过此阈值的时候，则会引发超时的异常。你的压测可以尝试将并发降低到100以下测试就不会出现这个问题了，或者你可以在连接字符串指定 `MaximumPoolSize` 来设置默认线程池的大小。

另一个原因可能是你的数据库服务器上没有空闲的连接了，你可以使用  `SHOW STATUS LIKE 'Threads_connected' ` 命令或 `SELECT @@max_connections` 来查看你是否达到了数据库的最大连接数限制。

**Comment by 3223554** [comment]
linux连接字符串将连接池大小扩大 就不会出现这个问题了吗？

**Comment by 3223554** [comment]
![50并发](https://user-images.githubusercontent.com/16113293/70779860-8d038a80-1dbf-11ea-9bc6-ab49fcf4a0b0.png)
我施压了50并发 还是有一样的问题

**Comment by yang-xiaodong** [comment]
> 2、消费者 Group=option.group+'.'+version,中间的'.'可以自定义

在 v3.0 你现在可以通过重写 `SetSubscribeAttribute` 来做到这一点
https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs#L141

**Comment by Sky-nt** [comment]
https://github.com/dotnetcore/CAP/issues/424

**Comment by 3223554** [comment]
我最终还是换成了 同步调用同步代码
异步就异步到底 才没有问题
我们结合ormlite 在使用同步发送消息的时候 会出现  sql已经提交 或者是 sqlreadder 未关闭的问题
同步方法中调用mysql同步的执行方法  压测与业务功能测试均通过
