### ISSUE TITLE
If the handler is not completed the message does not come again

### ISSUE THREAD

**Issue by fzakharov** [dotnetcore/CAP#453]
I don’t know if this is a bug or some settings need to be tweaked.

![stop_service](https://user-images.githubusercontent.com/10251241/70702292-6b8f9980-1d00-11ea-904f-21ecf9294f20.png)

1. Put a breakpoint inside an empty handler
2. When a message is received, just stop service/debugging
3. Start the service again
4. Only newly sent messages will be received

Expected: The interrupted message should come again because the handler was not completed

**Comment by yang-xiaodong** [comment]
Because the application is stopped, success or failure cannot be captured to continue subsequent tasks.

When the application starts again, the retry processor will query the message to continue processing (the query rule is the message 4 minutes ago)

**Comment by fzakharov** [comment]
Thanks for the answer!
1. But I do not receive that message repeatedly. Is it lost?
2. If the message is taken from the queue, is it marked as processed immediately? Even if the handler did not work?

Is consumer-side reprocessing also provided through storage?
Just in this case .UseInMemoryStorage () is used;

**Comment by yang-xiaodong** [comment]
1.  Yes , because you are using in-memory storage, it will disappear after the application is stopped.
2.  After the message is received from the queue, the first step is persisted and then ack to message queue, the last step is to execute the subscribe method.

**Comment by fzakharov** [comment]
And what will happen if we have several instances of the same service launched, but look at one queue and one database?
I mean the case of scaling
And with one of the messages the same situation will happen, the service will be turned off.

**Comment by yang-xiaodong** [comment]
I don't understand what you mean. When a service has two instances, only one instance will receive the message. Because of they using the same database, the message will be processed normally.
