### ISSUE TITLE
关于接收失败重试的问题。

### ISSUE THREAD

**Issue by QishengRan** [dotnetcore/CAP#454]
第一个问题，这段代码类型匹配有问题
var executeParameters = new object[parameterDescriptors.Count];
                for (var i = 0; i < parameterDescriptors.Count; i++)
                {
                    if (parameterDescriptors[i].IsFromCap)
                    {
                        executeParameters[i] = new CapHeader(message.Headers);
                    }
                    else
                    {
                        **executeParameters[i] = message.Value;**
                    }
                }
当我订阅的消息是一个具体的类型的时候，比如：
CheckReceivedMessage(Member member)
这里就会抛异常，JObject不能转换为指定的类型

第二个问题，消息过期时间默认太短，不能配置
 var retryBehavior = RetryBehavior.DefaultRetry;
var retries = ++message.Retries;
message.ExpiresAt = message.Added.AddSeconds(retryBehavior.RetryIn(retries));
这个过期时间就只有几分钟，如果我消费的时候异常了，隔一会儿就把过期消息清理掉了，导致消息很容易丢失。

**Comment by yang-xiaodong** [comment]
你测试的是3.0的代码吗？
1. 消息接收第一步就是验证类型是否能成功反序列化，不会走到你贴图的这个位置。
2. 成功消息默认1天，失败默认15天

**Comment by QishengRan** [comment]
我用的是最新的代码，下的源码调试的

**Comment by yang-xiaodong** [comment]
3.0 还没有发布啊，你是怎么用的？

**Comment by QishengRan** [comment]
你说net core还是CAP的？

**Comment by QishengRan** [comment]
我直接下载的CAP的源码测试的

**Comment by yang-xiaodong** [comment]
我指的是CAP，今天下午才将3.0合并到master分支的，都还没有对外发布

**Comment by QishengRan** [comment]
哦，那用的是之前的线上的吧。
我测试的就是订阅处理默认失败，然后我看数据库里面过期时间很短，我把时间手动延迟1天后，重启应用，走到4分钟后重试逻辑的时候序列化又出问题了。
3.0解决这些问题了吗？

**Comment by yang-xiaodong** [comment]
肯定是你的问题哪个地方搞错了，2.6都非常多人用了已经发布几个月了，这种基础的东西有问题肯定早就发现处理了。

**Comment by QishengRan** [comment]
message.ExpiresAt = message.Added.AddSeconds(retryBehavior.RetryIn(retries));
DefaultRetryCount = 3;
            DefaultRetryInThunk = retries =>
                (int) Math.Round(Math.Pow(retries - 1, 4) + 3 + _random.Next(30) * retries);
这个代码没错吧，默认三次重试，过期时间就几分钟

**Comment by QishengRan** [comment]
public object Value { get; }
Message的Value是object类型
 executeParameters[i] = message.Value
这里赋值的话，如果我定义了一个Person类型，直接赋值是肯定会报错的，需要转型才行，你们的测试代码都是基本类型，比如DateTime，string这种

**Comment by yang-xiaodong** [comment]
https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/Internal/IMessageSender.Default.cs#L100
