### ISSUE TITLE
引发的异常:“System.TypeLoadException”(位于 DotNetCore.CAP.dll 中) “System.TypeLoadException”类型的未经处理的异常在 DotNetCore.CAP.dll 中发生  Could not load type 'DotNetCore.CAP.IConsumerClientFactory' from assembly 'DotNetCore.CAP, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by JaneConan** [dotnetcore/CAP#457]
引发的异常:“System.TypeLoadException”(位于 DotNetCore.CAP.dll 中) “System.TypeLoadException”类型的未经处理的异常在 DotNetCore.CAP.dll 中发生  Could not load type 'DotNetCore.CAP.IConsumerClientFactory' from assembly 'DotNetCore.CAP, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by yang-xiaodong** [comment]
你的issue很符合这篇文章描述的 https://zhuanlan.zhihu.com/p/25795393， 不好意思暂时关闭！

建议先百度学习如何向开源项目提交issue

**Comment by JaneConan** [comment]
> 你的issue很符合这篇文章描述的 https://zhuanlan.zhihu.com/p/25795393 不好意思暂时关闭！
> 
> 建议先百度学习如何向开源项目提交issue

再开一下吧，刚刚没整理，不好意思

**Comment by JaneConan** [comment]
请问能解答一下吗？谢谢
