### ISSUE TITLE
类库中的Controller无法订阅消息

### ISSUE THREAD

**Issue by nick4** [dotnetcore/CAP#458]
发现一个消息订阅问题，我使用的是asp.net core 3.0，我的将Controller封装在类库中，订阅消息接收失败，未有任何提示，即使继承了ICapSubscribe，也是一样

**Comment by luqizheng** [comment]
services.AddControllers();
 services.AddControllersWithViews();

这样也不行吗？

**Comment by cocosip** [comment]
降级到2.2应该就可以了,目前 CAP还不兼容3.0

**Comment by AmayerGogh** [comment]
我发现不在启动项目的程序集下就不会订阅
