### ISSUE TITLE
  Consistency of received table

### ISSUE THREAD

**Issue by wangronghua** [dotnetcore/CAP#462]
private async Task<(bool, OperateResult)> ExecuteWithoutRetryAsync(MediumMessage message, ConsumerExecutorDescriptor descriptor, CancellationToken cancellationToken)
        {
            if (message == null)
            {
                throw new ArgumentNullException(nameof(message));
            }

            cancellationToken.ThrowIfCancellationRequested();

            try
            {
                var sp = Stopwatch.StartNew();

                await InvokeConsumerMethodAsync(message, descriptor, cancellationToken);

                sp.Stop();

                await SetSuccessfulState(message);//Invokeconsumermethodasync and here are not in a transaction. If invokeconsumermethodasync succeeds, setsuccessfullstate throws an exception, and then retries. Is this the case?

                _logger.ConsumerExecuted(sp.Elapsed.TotalMilliseconds);

                return (false, OperateResult.Success);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"An exception occurred while executing the subscription method. Topic:{message.Origin.GetName()}, Id:{message.DbId}");

                return (await SetFailedState(message, ex), OperateResult.Failed(ex));
            }
        }

**Comment by yang-xiaodong** [comment]
https://zhuanlan.zhihu.com/p/25795393

**Comment by wangronghua** [comment]
https://github.com/dotnetcore/CAP/blob/51afa0127d0f01ffcae8bd08ada91535568518c0/src/DotNetCore.CAP/Internal/ISubscribeDispatcher.Default.cs#L98

**Comment by wangronghua** [comment]
If the error is reported here and the modification is successful and failed, but the business is executed correctly, will there be a consistency problem here?
