### ISSUE TITLE
Possible problems with messages when retries are exceeded

### ISSUE THREAD

**Issue by wangronghua** [dotnetcore/CAP#463]
If the consumer fails to find a handler or retries more than once, the expiration time will be set to 15 minutes. Then the system mechanism will delete the expired messages regularly. What will happen if the messages that are not successfully executed are deleted? Why is it so designed here?

**Comment by yang-xiaodong** [comment]
Please provide your environment before reporting

**Comment by yang-xiaodong** [comment]
No response , close
