### ISSUE TITLE
Can not find function "BeginTransaction"

### ISSUE THREAD

**Issue by cysnet** [dotnetcore/CAP#465]
[HttpGet("pdb")]
        public IActionResult GetDb()
        {
            using (var trans = _dbContext.Database.BeginTransaction(_capBus, autoCommit: true))
            {
                //业务代码

                _capBus.Publish("xxx.services.show.time", DateTime.Now);
            }
            return Ok();
        }

**Comment by cysnet** [comment]
BeginTransaction  method is not overloaded with two parameters

**Comment by yang-xiaodong** [comment]
You need import `DotNetCore.CAP` namespace
