### ISSUE TITLE
SqlServer LIKE Command with dapper

### ISSUE THREAD

**Issue by colinin** [dotnetcore/CAP#470]
Use dapper to query statements with LIKE syntax. Parameterized queries cannot be the same as ordinary parameters. The problem code is here:
https://github.com/dotnetcore/CAP/blob/1c43afb00eedf9996e129eca407721848d14968a/src/DotNetCore.CAP.SqlServer/IMonitoringApi.SqlServer.cs#L82

**Comment by yang-xiaodong** [comment]
PR is welcome

**Comment by yang-xiaodong** [comment]
Fixed in v3.0, nuget package is released!
