### ISSUE TITLE
Mock ICapPublisher when there is a transaction in the tested method

### ISSUE THREAD

**Issue by jvandewync** [dotnetcore/CAP#471]
Hello!

I'm trying to mock an `ICapPublisher` for unit testing a method where a transaction is used to do some database operations and to send messages. However, since the method [BeginTransaction](https://github.com/dotnetcore/CAP/blob/aaecabe58976ef078d77e6678cad7608c5368043/src/DotNetCore.CAP.PostgreSql/ICapTransaction.PostgreSql.cs#L141) is trying to get the service of type `CapTransactionBase`, I'm struggling to find a solution. Would it be better if `BeginTransaction` tried to get a service of type `ICapTransaction`? (The service uses PostgreSQL as a storage, and unit tests are done using Sqlite in-memory).

Thanks in advance.

**Comment by yang-xiaodong** [comment]
Thank you for your feedback, this is a place that has been ignored for a long time, we will replace it with `ICapTransaction` in the v3.0
