### ISSUE TITLE
CAP3.0.0版本发生sqlserver链接不释放问题

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/CAP#477]
问题版本:CAP3.0.0
运行数据库:sqlserver2016
问题描述:在运行一段时间时间发生大量sleeping链接不释放,CMD值为AWAITING COMMAND,随着时间增长导致上升到100条之后,导致EF也相应报错
An exception occurred while iterating over the results of a query for context type 'ChySystem.EFCore.ChyContext'.
System.InvalidOperationException: Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.
查看SQL语句 ===> sp_who '登录名'

我也曾经以为自身使用EF未释放导致,直到我采用了x.UseInMemoryStorage()之后,数据库链接能正常释放了

经过测试,发现无论使用x.UseSqlServer()或者x.UseEntityFramework<DBContext>();都不能与EF连接复用,貌似CAP死死占用链接而不释放

**Comment by yang-xiaodong** [comment]
Thanks for your feedback,  We found a disponse bug when get the received message from db.

We have fixed it in `3.0.1-preview-95233114`, and you can get it from nuget in a few minutes
