### ISSUE TITLE
Dashboard discovry does not working

### ISSUE THREAD

**Issue by a641545621** [dotnetcore/CAP#479]
.net core 3.1版本 3.1
同时启动两个程序,不同的节点端口 连接不同的数据库. 有时候无法访问面板 访问后服务器列表有时候有数据 有时候没有  查看consul 数据清空.
![(JD 1{758EI0AQWKA4SX4BH](https://user-images.githubusercontent.com/33652128/72052452-290dac80-3300-11ea-9455-d38daace60a5.png)
![1578559563(1)](https://user-images.githubusercontent.com/33652128/72052457-2b700680-3300-11ea-8b57-5fa27345ea42.jpg)
![_C5${~}H` GMAV XL%OWOQG](https://user-images.githubusercontent.com/33652128/72052468-2f038d80-3300-11ea-997e-0104ed438ede.png)

**Comment by yang-xiaodong** [comment]
Hello, I can't reproduce your issue in CAP version 3.0, here is my configuration

```c#

services.AddCap(x =>
{
    x.UseMySql(Configuration.GetValue<string>("ConnectionString"));
    x.UseRabbitMQ("localhost");
    x.UseDashboard();
    x.UseDiscovery(_ =>
    {
        _.DiscoveryServerHostName = "localhost";
        _.DiscoveryServerPort = 8500;
        _.CurrentNodeHostName = Configuration.GetValue<string>("ASPNETCORE_HOSTNAME");
        _.CurrentNodePort = Configuration.GetValue<int>("ASPNETCORE_PORT");
        _.NodeId = Configuration.GetValue<string>("NodeId");
        _.NodeName = Configuration.GetValue<string>("NodeName");
    });
});
```
Consul 1.6.2:

```shell
consul agent -dev
```

Windows  10,  ASP.NET Core 3.1: 
```shell
set ASPNETCORE_HOSTNAME=localhost&& set ASPNETCORE_PORT=5001&& dotnet run --urls=http://localhost:5001 NodeId=1 NodeName=CAP-1 ConnectionString="Server=localhost;Database=aaa;UserId=xxx;Password=xxx;"
set ASPNETCORE_HOSTNAME=localhost&& set ASPNETCORE_PORT=5002&& dotnet run --urls=http://localhost:5002 NodeId=2 NodeName=CAP-2 ConnectionString="Server=localhost;Database=bbb;UserId=xxx;Password=xxx;"
```

**Comment by yang-xiaodong** [comment]
No response, close

**Comment by a641545621** [comment]
单个服务是没有问题的,当我尝试多个服务,用consul做服务发现,运行两个服务时  有一个会出现问题.
![image](https://user-images.githubusercontent.com/33652128/72657451-7fa17780-39df-11ea-8833-7f17e3e25110.png)
![image](https://user-images.githubusercontent.com/33652128/72657480-d0b16b80-39df-11ea-885a-cd8e4b9cadd0.png)
这个3-3的服务 启动后 到服务列表切换 就会出现错误日志,consul信息被清楚 然后数据清0
这个3的服务 可以自由切换
这两个服务,单独运行的时候是正常的...一起运行 就出现异常
