### ISSUE TITLE
[NullReferenceException ] cap2.6 in dotnetcore 3.0

### ISSUE THREAD

**Issue by young717** [dotnetcore/CAP#486]
This exception causes the consumer to lose contact with rabbitmq and will not reconnect

exception info :
```
### CAP shutdown!
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetCore.CAP.ConsumerHandler.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
```

Is it dotnet core 3.0 incompatible with cap 2.6 ?    
if i update cap to 3.1 , is it will be repaired?

**Comment by HuangZhiwei97** [comment]
你应该升级你的框架到3.1

**Comment by yang-xiaodong** [comment]
CAP v3.0 is not compatible with CAP v2.x

There is no 3.1 version of CAP. Do you mean.net core 3.1?

**Comment by yang-xiaodong** [comment]
No response, close
