### ISSUE TITLE
Publish 是3.0版本 Subscribe 2.6 版本不能相互使用？

### ISSUE THREAD

**Issue by HuangZhiwei97** [dotnetcore/CAP#487]
本地项目使用的CAP是3.0，本地Publish消息，本地订阅消息，是能接收到消息的。但是与另一个使用CAP2.6的项目进行互通时，Subscribe方2.6版本接受不到消息

**Comment by yang-xiaodong** [comment]
3.0 is not compatible with 2.0

**Comment by HuangZhiwei97** [comment]
我的项目是.Net Core3.1使用的CAp3.0，对方是.Net Core2.2使用CAP2.6

**Comment by yang-xiaodong** [comment]
see v3.0.0 release log

https://github.com/dotnetcore/CAP/releases/tag/v3.0.0

**Comment by HuangZhiwei97** [comment]
touche..Net Core 2.X  project support CAP3.0？

**Comment by HuangZhiwei97** [comment]
or My .Net Core3.1 project support CAP2.6？ Can  .Net Core3.1 use CAP2.6？
