### ISSUE TITLE
Validate multiple consumer threads is expected ( ConsumerThreadCount  configuration)

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnetcore/CAP#492]
Copied from  https://github.com/dotnetcore/CAP/issues/484#issuecomment-574931403

>  I've tryied to reproduce with version 3.0.1-preview-94915444 and 3.0.1-preview-95233114. In both cases it is not throwing exceptions anymore, but the behavior with te concurrent subscribers its the same. Only 1 and sometimes 2 subscribers are running concurrently. The other 3 or 4 seem to not be working.
> 
> Could you provide us an example? Just the subscriber implementation to test the concurrency will be enough.

**Comment by flzxsqcysyhljt** [comment]
多个消费者未公平分配消息，不同的消息队列配置不一样。下面举例rabbitmq：
```csharp
public void Listening(TimeSpan timeout, CancellationToken cancellationToken)
{
        Connect();

        var consumer = new EventingBasicConsumer(_channel);
        consumer.Received += OnConsumerReceived;
        consumer.Shutdown += OnConsumerShutdown;
        consumer.Registered += OnConsumerRegistered;
        consumer.Unregistered += OnConsumerUnregistered;
        consumer.ConsumerCancelled += OnConsumerConsumerCancelled;

        _channel.BasicQos(0, 1, true);//添加公平分配配置
        _channel.BasicConsume(_queueName, false, consumer);

        while (true)
        {
            cancellationToken.ThrowIfCancellationRequested();
            cancellationToken.WaitHandle.WaitOne(timeout);
        }

        // ReSharper disable once FunctionNeverReturns
    }
```

**Comment by yang-xiaodong** [comment]
Hello @franribera  @flzxsqcysyhljt, 

This issue fixed in perview version `3.0.3-preview-98619331`.

If this project helps you, Could please give a star ?

**Comment by flzxsqcysyhljt** [comment]
Of course@yang-xiaodong

**Comment by franribera** [comment]
@yang-xiaodong it works as expected. Thanks for fixing it.
This is a nice project, I will give you a star.
I suggest you to improve the documentation. The UX of your website and adding more samples, like a workerservice example, consele app,.. Not ASP examples only!

God job!
