### ISSUE TITLE
How to ignore retry caused by some exception such as primary key conflict, I usually use primary key conflict to ensure idempotence during insert operation

### ISSUE THREAD

**Issue by dingsongjie** [dotnetcore/CAP#493]
How to ignore retry caused by some exception such as primary key conflict, I usually use primary key conflict to ensure idempotence during insert operation.I hope these messages can become faild messages directly instead of trying to retry multiple times

**Comment by yang-xiaodong** [comment]
Add `try catch` at your consumer
```C#
try
{
    //Your code
}
catch (SqlException e )
{
    if (e.Number == primary key conflict code)
    {
            //ignore
    }
   
}
```

**Comment by dingsongjie** [comment]
```cs
try
{
    //Your code
}
catch (SqlException e )
{
    if (e.Number == primary key conflict code)
    {
            //ignore
    }
   
}
```
The above code will make consumers consume normally instead of generating a Fail.
I just want ignore retry  when some special exception happens

**Comment by yang-xiaodong** [comment]
The above code just ignore the sqlexception of the exception code is primary key conflict, can you get it?

Just catch your focus exception and ignore it!
