### ISSUE TITLE
deserialization error in CAP

### ISSUE THREAD

**Issue by lsy520** [dotnetcore/CAP#494]
Environment:
.net core 2.2
CAP 2.6.0
Mysql 5.7.21
Kafka 2.11-1.0.0

Dto:
public class TbLifeCycleRelation_Version
    {
        public long SlaveId { get; set; }
        public string Name { get; set; }
        public string IdentityNo { get; set; }
        public long TbLifeCycleId { get; set; }
        public string SourceProcessNo { get; set; }
        public string Source { get; set; }
        public bool IsSourceEmpower { get; set; }
        public bool IsSourceError { get; set; }
        public string TargetProcessNo { get; set; }
        public string Target { get; set; }
        public bool IsTargetEmpower { get; set; }
        public bool IsTargetError { get; set; }
        public string LifeCycleRuleJson { get; set; }
        public long EnterpriseId { get; set; }
        public string EnterpriseNumber { get; set; }
        public string EnterpriseName { get; set; }
        public DateTime CreateTime { get; set; } = DateTime.Now;
    }

cap.received:
{"SlaveId": 81,"Name": "测试","TbLifeCycleId": 19,"SourceProcessNo": "190001003","Source": "1","IsSourceEmpower": true,"IsSourceError": false,"TargetProcessNo": "190026002","Target": "2","IsTargetEmpower": false,"IsTargetError": false,"LifeCycleRuleJson": "[{\"LifeCycleRuleType\":1,\"Source\":{\"NodeType\":2,\"Content\":\"shengchan\"},\"Target\":{\"NodeType\":2,\"Content\":\"ershou\"},\"Condition\":\"and\",\"Regular\":\"\"}]","EnterpriseId": 1,"EnterpriseNumber": "190026","EnterpriseName": "上汽大众汽车有限公司","CreateTime": "2019-12-19T11:18:46","Id": 0,"IdentityNo": "AAAA02001170001"}

Receiver:
[CapSubscribe("cds.master.tblifecyclerelation_version")]
        public async Task CheckReceivedMessage(TbLifeCycleRelation_Version request)
        {
            
        }

question:
Accept the event successfully, but do not get the parameters what is the reason?

**Comment by yang-xiaodong** [comment]
what is the received message status in table?

**Comment by lsy520** [comment]
Succeeded

**Comment by yang-xiaodong** [comment]
The status `Sccceeded` means that the consumer method has been executed,  you need to check your log.

If you can't find the reason, I suggest you change a name(topic）and try again
