### ISSUE TITLE
消息处理方法重复提交

### ISSUE THREAD

**Issue by tengsirboy** [dotnetcore/CAP#496]
1，运行环境
      ![image](https://user-images.githubusercontent.com/12180822/72729049-a6bb9d00-3bc9-11ea-83a0-885597c7ab0a.png)

2，问题还原
     发送消息方法=》接收消息方法，等待一段时间后（第一次未出现，可以再重复执行发送消息方法=》接收消息方法流程），RabbitMQ会循环推送一条同样的消息多次

**Comment by yang-xiaodong** [comment]
You need to provide :
1、Environment and versions
2、Publish Code
3、Logs and message status in table

**Comment by yang-xiaodong** [comment]
No response
