### ISSUE TITLE
Use Autofac register ICapSubscribe cannot work

### ISSUE THREAD

**Issue by BrisWhite** [dotnetcore/CAP#497]
Env:
.Net Core 3.0(.Net Core 2.2)
CAP 3.0.1(CAP 2.6.0)

Steps:
1. Add 'CapConsumer' like this:
![微信截图_20200121162337](https://user-images.githubusercontent.com/5007541/72787413-d40c5780-3c6a-11ea-8371-a6eeb3825969.png)

2. Add 'ApplicationModule' like this:
![微信截图_20200121162359](https://user-images.githubusercontent.com/5007541/72787422-dbcbfc00-3c6a-11ea-8667-eaf7cddc649a.png)

3. Input sth in 'ConfigureServices' like this:
![微信截图_20200121162411](https://user-images.githubusercontent.com/5007541/72787677-56951700-3c6b-11ea-9e24-16723df347c6.png)

4. Start your app and then go to your rabbitmq dashboard,click 'Queues' tab,and got nothing.

If I directly add CAP as refrence,it's ok!!!

**Comment by yang-xiaodong** [comment]
Please DON'T USE SCREENSHOTS !!

**Comment by yang-xiaodong** [comment]
https://github.com/dotnetcore/CAP/issues/224#issuecomment-472330886
