### ISSUE TITLE
Diagnostics event data object error

### ISSUE THREAD

**Issue by yuyixg** [dotnetcore/CAP#504]
Shoud be `CapEventDataSubStore` here ？

https://github.com/dotnetcore/CAP/blob/557c314258c284e7bd35f7165859506a4b7677dd/src/DotNetCore.CAP/Internal/IConsumerRegister.Default.cs#L302

**Comment by yang-xiaodong** [comment]
Thank you for your report.

By the way, the standard formating and description and code connection can help author to find the problem faster. I hope that you can pay attention on this later.

**Comment by yang-xiaodong** [comment]
Fixed in version 3.0.2
