### ISSUE TITLE
Dashboard details page no error messages

### ISSUE THREAD

**Issue by yuyixg** [dotnetcore/CAP#505]
Publish message error  dashboard no error messages，but 2.6 there is an error message。
Use Kafka as the component

Retry sending succeeded, but the details page  failed

**Comment by yang-xiaodong** [comment]
What do you mean "no error messages" ?

**Comment by yang-xiaodong** [comment]
For performance reasons, we canceled writing the error message to the message content, and in some cases we would be write the message to the header

**Comment by yang-xiaodong** [comment]
This feature has been implemented
