### ISSUE TITLE
CAP2.6 version  can not publish message right away

### ISSUE THREAD

**Issue by HuangZhiwei97** [dotnetcore/CAP#506]
两个不同的项目，一个推送消息，一个接受消息。两者用的是同一个rabbitMQ。在项目中通过代码的推送，另一个项目不能实时接受。通过进入项目的CAP 控制面板点击消息重新发送，另一个项目能够接受到。
请问是CAP2.6版本有什么变动吗。

**Comment by yang-xiaodong** [comment]
How can I  replication your issue?

The changes of version you can see the relase log at here:
https://github.com/dotnetcore/CAP/releases

**Comment by yang-xiaodong** [comment]
No response , close
