### ISSUE TITLE
Hiding intrusive logs

### ISSUE THREAD

**Issue by kKen94** [dotnetcore/CAP#507]
![image](https://user-images.githubusercontent.com/46461611/74342600-07de2700-4daa-11ea-9f0d-9bf806c67985.png)

It is possible to all of these logs?

**Comment by yang-xiaodong** [comment]
appsettings.Development.json 
```
{
  "Logging": {
    "LogLevel": {
      "DotNetCore.CAP.Processor.TransportCheckProcessor": "Information"
    }
  }
}
```
