### ISSUE TITLE
How to configure the number of concurrent consumption?

### ISSUE THREAD

**Issue by flzxsqcysyhljt** [dotnetcore/CAP#508]
推荐System.Threading.Tasks.Dataflow库中的ActionBlock替代BlockingCollection，提高消息的处理能力。特别是消息处理比较耗时时，严重影响系统的处理能力

**Comment by yang-xiaodong** [comment]
Processing speed is limited by various aspects, such as database IO, consumer processing time and so on.

If you are willing to sacrifice the sequential of the messages, the CAP provides a `ConsumerTheraderCount` configuration item that allows multiple consumers to be connected to the Transport at the same time.

System.Threading.Tasks.Dataflow has been obsolete, and the performance of the new Channel.Threading.Channels is better. It is worth mentioning that the current processing bottleneck is far from the upper limit of the BlockingCollection.

**Comment by flzxsqcysyhljt** [comment]
ConsumerThreadCount 增加的是消费者接受消息的实例并不负责处理。消息是由Dispatcher处理，而Dispatcher又是单例，处理能力并未增加。
`private async Task Processing()
        {
            try
            {
                foreach (var message in _receivedMessageQueue.GetConsumingEnumerable(_cts.Token))
                {
                    //此处逐个处理消息，当对消息没有顺序要求时影响处理性能;比如一个消息处理需要10分钟，三个就需要30分钟;
                    await _executor.DispatchAsync(message.Item1, message.Item2, _cts.Token);
                }
            }
            catch (OperationCanceledException)
            {
                
            }
        }`
[另外附上关于System.Threading.Tasks.Dataflow并行库的官方文档，该库是.netcore的一部分只是未集成到框架中，详见官方文档](https://docs.microsoft.com/zh-cn/dotnet/api/system.threading.tasks.dataflow?view=netcore-3.1)
顺便附上建议的代码
`public class ParallelDispatcher : IDispatcher, IDisposable
    {
        private readonly CancellationTokenSource _cts = new CancellationTokenSource();
        private readonly IMessageSender _sender;
        private readonly ISubscribeDispatcher _executor;
        private readonly ILogger<ParallelDispatcher> _logger;

        private readonly ActionBlock<MediumMessage> _publishedMessageQueue;

        private readonly ActionBlock<(MediumMessage, ConsumerExecutorDescriptor)> _receivedMessageQueue;

        public ParallelDispatcher(ILogger<ParallelDispatcher> logger,
            IMessageSender sender,
            ISubscribeDispatcher executor)
        {
            _logger = logger;
            _sender = sender;
            _executor = executor;

            _publishedMessageQueue = new ActionBlock<MediumMessage>(Sending, new ExecutionDataflowBlockOptions
            {
                CancellationToken = _cts.Token,
                MaxDegreeOfParallelism = 5,//可以作为配置参数
                EnsureOrdered = true//可以作为配置参数
            });
            _receivedMessageQueue = new ActionBlock<(MediumMessage, ConsumerExecutorDescriptor)>(Processing, new ExecutionDataflowBlockOptions
            {
                CancellationToken = _cts.Token,
                MaxDegreeOfParallelism = 10,//可以作为配置参数
                EnsureOrdered = false //可以作为配置参数
            });
        }

        public void EnqueueToPublish(MediumMessage message)
        {
            _publishedMessageQueue.Post(message);
        }

        public void EnqueueToExecute(MediumMessage message, ConsumerExecutorDescriptor descriptor)
        {
            _receivedMessageQueue.Post((message, descriptor));
        }

        public void Dispose()
        {
            _cts.Cancel();
        }

        private async Task Sending(MediumMessage message)
        {
            try
            {
                var result = await _sender.SendAsync(message);
                if (!result.Succeeded)
                {
                    _logger.MessagePublishException(message.Origin.GetId(), result.ToString(), result.Exception);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, $"An exception occurred when sending a message to the MQ. Id:{message.DbId}");
            }
        }

        private async Task Processing((MediumMessage, ConsumerExecutorDescriptor) message)
        {
            await _executor.DispatchAsync(message.Item1, message.Item2, _cts.Token);
        }
    }`

**Comment by yang-xiaodong** [comment]
releated issue : #492

**Comment by flzxsqcysyhljt** [comment]
多个消费者未公平分配消息，不同的消息队列配置不一样。下面举例rabbitmq：
   public void Listening(TimeSpan timeout, CancellationToken cancellationToken)
        {
            Connect();

            var consumer = new EventingBasicConsumer(_channel);
            consumer.Received += OnConsumerReceived;
            consumer.Shutdown += OnConsumerShutdown;
            consumer.Registered += OnConsumerRegistered;
            consumer.Unregistered += OnConsumerUnregistered;
            consumer.ConsumerCancelled += OnConsumerConsumerCancelled;

            _channel.BasicQos(0, 1, true);//添加公平分配配置
            _channel.BasicConsume(_queueName, false, consumer);

            while (true)
            {
                cancellationToken.ThrowIfCancellationRequested();
                cancellationToken.WaitHandle.WaitOne(timeout);
            }

            // ReSharper disable once FunctionNeverReturns
        }

**Comment by yang-xiaodong** [comment]
> 多个消费者未公平分配消息，不同的消息队列配置不一样
@flzxsqcysyhljt 
Please open a new issue focus on this , so that we can at a single thread to discuss.

Your can reference [here](https://guides.github.com/features/mastering-markdown/) to learn how to use markdown, your issue format is  is highly de-normalized.

Close this issue, we will focus the topic on #492

**Comment by yang-xiaodong** [comment]
@flzxsqcysyhljt  Are you testing the synchronization method like this ?

```cs
private void Processing()
{
    try
    {

        foreach (var message in _receivedMessageQueue.GetConsumingEnumerable(_cts.Token))
        {
            _executor.DispatchAsync(message.Item1, message.Item2, _cts.Token);
        }
    }
    catch (OperationCanceledException)
    {
        // expected
    }
}
```

**Comment by flzxsqcysyhljt** [comment]
不是，异步下测试。我有个定时报表服务发现了严重的延迟才定位该问题
