### ISSUE TITLE
分布式下重试重复消费

### ISSUE THREAD

**Issue by gowei710** [dotnetcore/CAP#511]
分布式场景下重试消息，消息可能会存在不同节点下重复消费
        private async Task ProcessReceivedAsync(IDataStorage connection, ProcessingContext context)
        {
            context.ThrowIfStopping();

            var messages = await GetSafelyAsync(connection.GetReceivedMessagesOfNeedRetry);

            foreach (var message in messages)
            {
                await _subscribeDispatcher.DispatchAsync(message);

                await context.WaitAsync(_delay);
            }
        }

**Comment by yang-xiaodong** [comment]
This is as expected, consumers need to guarantee idempotence
