### ISSUE TITLE
No message received，Sending a message is normal

### ISSUE THREAD

**Issue by lsy520** [dotnetcore/CAP#512]
![image](https://user-images.githubusercontent.com/35556626/75135440-7c0aba00-571c-11ea-892a-90e4784e2df5.png)

**Comment by lsy520** [comment]
![QQ图片20200224154944](https://user-images.githubusercontent.com/35556626/75135677-4a462300-571d-11ea-9572-96488828d938.png)

**Comment by yang-xiaodong** [comment]
closed by https://zhuanlan.zhihu.com/p/25795393
