### ISSUE TITLE
Schema creation

### ISSUE THREAD

**Issue by kKen94** [dotnetcore/CAP#514]
Does the library provide creation of cap schema itself?

Today I changed my db (docker sql server), and when i try to send message:

```
One or more errors occurred. (Invalid object name 'cap.Published'.)
```

I'm sure that once it did, but now schema is not created

```
services
                .AddCap(x =>
                {
                    x.DefaultGroup = $"cap.queue.{version}.{machine}.{domain}";
                    x.UseEntityFramework<TContext>();
                    x.UseRabbitMQ(options =>
                    {
                        options.HostName = configuration["RabbitMQ:HostName"];
                        options.UserName = configuration["RabbitMQ:UserName"];
                        options.Password = configuration["RabbitMQ:Password"];
                        options.VirtualHost = configuration["RabbitMQ:VirtualHost"];
                        options.Port = Convert.ToInt32(configuration["RabbitMQ:Port"]);
                        options.ExchangeName = $"cap.router.{version}.{machine}.{domain}";
                    });
                });
```

**Comment by yang-xiaodong** [comment]
When the application starts, the script detects if it has a schema and attempts to create it.

You can test if the script works in your SQL Server

https://github.com/dotnetcore/CAP/blob/c3ec6e84c9880bbf66197379a99ccac7d974f579/src/DotNetCore.CAP.SqlServer/IStorageInitializer.SqlServer.cs#L54-L57

**Comment by kKen94** [comment]
Thank you, my fault.
After checking that the script was working,
knowing that the library works made me realize that in my migrations I use ICapPublisher before the library initialization.
