### ISSUE TITLE
您好,请问将来能否在MQ消息写数据库时提供读写分离的配置

### ISSUE THREAD

**Issue by wjire** [dotnetcore/CAP#516]
x.UseSqlServer(s =>
                {
                    s.ConnectionString =
                        "Data Source=localhost;Initial Catalog=nCoV;Persist Security Info=True;User ID=sa;Password=1";                 
                });
您好,请问这里将来能否提供读写分离的配置...拿我自己来说,数据库连接一直是两个,一个读,一个写.

**Comment by yang-xiaodong** [comment]
Hello, we do not intend to implement this feature.
For database read-write separation, you can achieve it through database middleware, which is a better solution.
You can also do this by rewriting the related query method.

**Comment by wjire** [comment]
thank you,你的话我完全能看懂,就是写不出来.哈哈
