### ISSUE TITLE
If I inject ICapPublisher into my Sqlserver DbContext class,an exception is thrown

### ISSUE THREAD

**Issue by AndyChenzheng** [dotnetcore/CAP#518]
By reading the original code, found in ConfigureSqlServerOptions in the configure method, in analytical DbContext, rely on the analysis of other classes when use the OPtion < SqlServerOptions >, while OPtion < SqlServerOptions > haven't initialization is complete, cause an exception

**Comment by yang-xiaodong** [comment]
closed by https://zhuanlan.zhihu.com/p/25795393

**Comment by AndyChenzheng** [comment]
你好：
&nbsp; &nbsp; &nbsp;我不太理解你的意思，我在下载的dotnetcore原码中测试依然是报错，我只是在AppDbContext中注入了ICapPublisher，运行时就异常。因为我想在AppDbContext中使用到ICapPublisher我该如何解决这个问题？






------------------ 原始邮件 ------------------
发件人:&nbsp;"Savorboard"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月4日(星期三) 晚上8:25
收件人:&nbsp;"dotnetcore/CAP"<CAP@noreply.github.com&gt;;
抄送:&nbsp;"陈政"<405643529@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dotnetcore/CAP] If I inject ICapPublisher into my Sqlserver DbContext class,an exception is thrown (#518)




Closed #518.

**Comment by yang-xiaodong** [comment]
Using EventBus in DbContext is not the right behavior, so we are not going to change it
