### ISSUE TITLE
how dapper user works?

### ISSUE THREAD

**Issue by zanpen2000** [dotnetcore/CAP#52]
```
        [Route("publish")]
        public async Task<IActionResult> PublishMessage()
        {
            const string cstr = "Data Source=192.168.0.250;Initial Catalog=CapDemo;User ID=sa;Password=123123;";

            var sql1 = new System.Data.SqlClient.SqlConnection(cstr);
            await _publisher.PublishAsync("CapDemo", new Person { Name = "老张", Age = 30 }, sql1);

            var sql2 = new System.Data.SqlClient.SqlConnection(cstr);
            await _publisher.PublishAsync("CapDemo.Service", new Person { Name = "老李", Age = 40 }, sql2);

            return Ok();
        }
```

should I create a instance of SqlConnection when publish a message ?

**Comment by yuleyule66** [comment]
No, just create one SqlConnection in an action.

**Comment by zanpen2000** [comment]
@yuleyule66 But When I use one SqlConnection , I got a "NullReferenceException", code like below:

`
        [Route("publish")]
        public async Task<IActionResult> PublishMessage()
        {
            const string cstr = "Data Source=192.168.0.250;Initial Catalog=CapDemo;User ID=sa;Password=123123;";

            var sql1 = new System.Data.SqlClient.SqlConnection(cstr);
            await _publisher.PublishAsync("CapDemo", new Person { Name = "老张", Age = 30 }, sql1);

            // var sql2 = new System.Data.SqlClient.SqlConnection(cstr);
            await _publisher.PublishAsync("CapDemo.Service", new Person { Name = "老李", Age = 40 }, sql1);

            return Ok();
        }
`

Then I got:
`
NullReferenceException: Object reference not set to an instance of an object.
System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource<DbConnectionInternal> retry)
System.Data.SqlClient.SqlConnection.Open()
DotNetCore.CAP.Abstractions.CapPublisherBase.PrepareConnectionForAdo(IDbConnection dbConnection, IDbTransaction dbTransaction) in CapPublisherBase.cs
-
        private void PrepareConnectionForAdo(IDbConnection dbConnection, IDbTransaction dbTransaction)
        {
            DbConnection = dbConnection ?? throw new ArgumentNullException(nameof(dbConnection));
            if (DbConnection.State != ConnectionState.Open)
            {
                IsCapOpenedConn = true;
                DbConnection.Open();
            }
            DbTransaction = dbTransaction;
            if (DbTransaction == null)
            {
                IsCapOpenedTrans = true;
                DbTransaction = dbConnection.BeginTransaction(IsolationLevel.ReadCommitted);
DotNetCore.CAP.Abstractions.CapPublisherBase.PublishAsync<T>(string name, T contentObj, IDbConnection dbConnection, string callbackName, IDbTransaction dbTransaction) in CapPublisherBase.cs
-
        }
        public Task PublishAsync<T>(string name, T contentObj, IDbConnection dbConnection,
            string callbackName = null, IDbTransaction dbTransaction = null)
        {
            CheckIsAdoNet(name);
            PrepareConnectionForAdo(dbConnection, dbTransaction);
            var content = Serialize(contentObj, callbackName);
            return PublishWithTransAsync(name, content);
        }
DemoA.Controllers.ValuesController+<PublishMessage>d__2.MoveNext() in ValuesController.cs
-
            const string cstr = "Data Source=192.168.0.250;Initial Catalog=CapDemo;User ID=sa;Password=123123;";
            var sql1 = new System.Data.SqlClient.SqlConnection(cstr);
            await _publisher.PublishAsync("CapDemo", new Person { Name = "老张", Age = 30 }, sql1);
            // var sql2 = new System.Data.SqlClient.SqlConnection(cstr);
            await _publisher.PublishAsync("CapDemo.Service", new Person { Name = "老李", Age = 40 }, sql1);
            return Ok();
        }
        [NonAction]
        [CapSubscribe("CapDemo")]
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
`

**Comment by yuleyule66** [comment]
Upgrading CAP version to `2.1.0-preview-26231671`, I modified part of the `ICapPublish` interface about publishing message with ADO.NET , and here is a sample code :

```
    [Route("~/publishWithTransactionUsingAdonet")]
    public async Task<IActionResult> PublishMessageWithTransactionUsingAdonet([FromServices]ICapPublisher publisher)
    {
        var connectionString = "";
        using (var sqlConnection = new SqlConnection(connectionString))
        {
            sqlConnection.Open();
            using (var sqlTransaction = sqlConnection.BeginTransaction())
            {
                // 此处填写你的业务代码，通常情况下，你可以将业务代码使用一个委托传递进来进行封装该区域代码。

                publisher.Publish("xxx.services.account.check", new Person { Name = "Foo", Age = 11 }, sqlTransaction);

                sqlTransaction.Commit();
            }
        }
        return Ok();
    }
```

**Comment by zanpen2000** [comment]
En, Thank you for your time, It's very helpful!
