### ISSUE TITLE
3.0无法支持异构系统消息

### ISSUE THREAD

**Issue by yuyixg** [dotnetcore/CAP#520]
3.0 无法支持异构系统消息，2.6可以，目前只能从修改此DotNetCore.CAP.Kafka程序集才能达到要求，能否增加一个消息适配接口？

**Comment by yang-xiaodong** [comment]
Please describe your issue in detail

**Comment by yuyixg** [comment]
异构系统的消息格式各种各样的，目前cap要求消息头里面必须有两个信息，一个为MessageId，另一个是MessageName，如果是老旧系统或者其他非cap系统那么这两个消息头肯定是不存在的，目前无法很简单的兼容这种消息，但是在cap2.6 中是可以转换的。

**Comment by yang-xiaodong** [comment]
3.0 的消息对消息结构是没有限制的，所以更加灵活。另外，我们删除了v2.6中的消息适配器。
消息头在是我们用来对消息进行识别的，如果没有将无法正常工作。
在异构系统中，消息头是需要约定的一致的。

如果是旧系统无法修改代码的情况下，你可以简单的通过写一个消费者程序将消息转换然后重新投递到新队列的方式来做到这一点。
