### ISSUE TITLE
Auto Delete

### ISSUE THREAD

**Issue by kpinneo** [dotnetcore/CAP#521]
Not really an issue, but our app creates hundreds of queue's and it would be nice to be able to declare the subscribing queue using the following:
// Change for self deleting queues
//_channel.QueueDeclare(_queueName, durable: true, exclusive: false, autoDelete: false, arguments: arguments);
_channel.QueueDeclare(_queueName);

**Comment by yang-xiaodong** [comment]
We need to keep the queue is durable  to avoid message lost,  you can customize the interface `IConsumerClient` to your needs
