### ISSUE TITLE
Cap cannot be consumed

### ISSUE THREAD

**Issue by ThereIsNoName0** [dotnetcore/CAP#523]
在使用cap时，发布者与订阅者同时存在，此时发布一条信息，可以直接被消费。问题：删除订阅者，再次发布一条数据，订阅失败，此时将订阅者加上，之后在仪表盘上再次加入消费队列时，一直无法被消费，这是为什么？

When using cap, the publisher and the subscriber exist at the same time. At this time, a piece of information can be published and consumed directly. Problem: delete the subscriber and publish a piece of data again. If the subscription fails, add the subscriber,After that, when the consumption queue is added again on the dashboard, it can't be consumed all the time. Why?

**Comment by yang-xiaodong** [comment]
No logs , no codes , no version , no environment,  based on your information you provided, I have to say I don't know!

**Comment by yang-xiaodong** [comment]
No Response , Closed!
