### ISSUE TITLE
ICapPublisher transaction & Is Subscription also a singleton?

### ISSUE THREAD

**Issue by JonFly** [dotnetcore/CAP#526]
大大你好, 我看了好几个CAP版本的文档,  里面提到ICapPublisher已经被设定成了单例, 在任何地方通过构造函数注入都可以安全使用, 那么多次发布消息的情况下, ICapPublisher对象的事务会不会有冲突呀.
比如: 数据服务类A,  构造方法中注入了ICapPublisher,    在A类的Update方法中using了DbContext, 同时将事务对象进行赋值, 类似如下:

`
using (var dbTransaction = await DbContext.BeginTransactionAsync())
                        {
                            CapPublisher.Transaction.Value = CapPublisher.ServiceProvider.GetService<ICapTransaction>();
                            var capTransaction = CapPublisher.Transaction.Value.Begin(dbTransaction, false);
                            //todo 执行具体实体更新业务....

                            CapPublisher.Publish("里面来一次", "...");
                            await DbContext.SaveChangesAsync();
                            capTransaction.Commit();
                        }
                        CapPublisher.Publish("在外面再来一次", "...");`

在using中进行的那次消息发布, 会和DbContext保持一个事务, 那么外面那一次会不会重新开一个事务?  只是不能和上面那一个using中的事务保持一致性而已吗?
如果部署成线上的服务, 会有较大的并发, ICapPublisher不断游走在"里面来一次" 和 "外面再来一次", 因为其是单例的原因, 事务方面会造成干扰吗?

第二个问题是关于Subscription的问题, 比如API收到一个GET请求, 如果有个类注入为Scoped的, 类似.NET的HttpContext, 再这次请求的过程中都保持为同一个, 直到请求结束,  而如果将一个方法加上了订阅的特性, 一旦收到订阅, 订阅本身属于一个Scoped吗? 还是说也是单例的? 

问题有点多, 烦请大大有时间的时候解答, 感激不尽...

**Comment by yang-xiaodong** [comment]
1、CAP使用 AsyncLocal 来存储事务
2、在执行消费者方法时，CAP会打开一个Scope来执行注入
