### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by crodling** [dotnetcore/CAP#527]
打开解决方案后，编译直接报错

error MSB3086: 任务未能使用 SdkToolsPath“”或注册表项“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.2\WinSDK-NetFx40Tools-x86”找到“al.exe”。请确保已设置 SdkToolsPath，在 SdkToolsPath 之下的相应处理器特定位置存在该工具，并且已安装 Microsoft Windows SDK

**Comment by yang-xiaodong** [comment]
Please see the build badges
