### ISSUE TITLE
Repeated query and delivery of messages

### ISSUE THREAD

**Issue by cysnet** [dotnetcore/CAP#530]
How to ensure that querying message tables and sending messages will not be duplicated when distributed systems use CAP

PS:中文
程序多开并在使用CAP时，如何保证查询消息表和发送消息不会重复。

**Comment by yang-xiaodong** [comment]
We only reread the failed message table and send it under abnormal conditions. If there are multiple instances reading the error message at the same time, it may theoretically lead to repeated delivery. In any case if you is sensitive to the message repeatability that you need to guarantee the idempotence.
