### ISSUE TITLE
when the message is not json,cap will always retry. never stop

### ISSUE THREAD

**Issue by duospeak** [dotnetcore/CAP#531]
If the message content can not be deseriaized,cap will try again and again. And every time will fail,it will never stop.

I fund these codes : DotNetCore.CAP.Internal.ConsumerRegister.RegisterMessageProcessor(), but why it doesn't work for this
```c#
 try
                    {
                        if (!canFindSubscriber)
                        {
                            var error = $"Message can not be found subscriber. Name:{name}, Group:{group}. {Environment.NewLine} see: https://github.com/dotnetcore/CAP/issues/63";
                            var ex = new SubscriberNotFoundException(error);

                            TracingError(tracingTimestamp, transportMessage, client.BrokerAddress, ex);

                            throw ex;
                        }

                        var type = executor.Parameters.FirstOrDefault(x => x.IsFromCap == false)?.ParameterType;
                        message = await _serializer.DeserializeAsync(transportMessage, type);
                    }
                    catch (Exception e)
                    {
                        transportMessage.Headers.Add(Headers.Exception, nameof(SerializationException) + "-->" + e.Message);
                        var dataUri = $"data:{transportMessage.Headers[Headers.Type]};base64," + Convert.ToBase64String(transportMessage.Body);
                        message = new Message(transportMessage.Headers, dataUri);
                    }

                    if (message.HasException())
                    {
                        var content = StringSerializer.Serialize(message);

                        _storage.StoreReceivedExceptionMessage(name, group, content);

                        client.Commit(sender);

                        TracingAfter(tracingTimestamp, transportMessage, _serverAddress);
                    }
                    else
                    {
                        var mediumMessage = _storage.StoreReceivedMessage(name, group, message);
                        mediumMessage.Origin = message;

                        client.Commit(sender);

                        TracingAfter(tracingTimestamp, transportMessage, _serverAddress);

                        _dispatcher.EnqueueToExecute(mediumMessage, executor);
                    }
```

如果 消息不能被反序列化(例如消息是一个字符串xxxx，而不是{Content:""}这种标准json格式 )，那么这个消息会被一直重试，而每次都报错，且并不会停止。 当不是用CAP发送消息，且消息格式不规范时，会导致这种死循环。
我在 DotNetCore.CAP.Internal.ConsumerRegister.RegisterMessageProcessor() 这个函数中，注意到了有反序列化异常时的处理代码，但似乎不是一直都起作用。 我发现，{"Content":"xxxx"}这种情况(消息可以被反序列化，但是content对应的字符串并不能被反序列化为指定对象)时会当作异常数据处理的；但如果消息是字符串(如assdfdfds，消息本身不能被反序列化)时，这个消息会被作为正常状态存储，因此会被重试，但每次重试都报错  且重试永远不会停止。

![image](https://user-images.githubusercontent.com/12929129/77735166-05c3e500-7045-11ea-86bc-443260b4e72f.png)

![image](https://user-images.githubusercontent.com/12929129/77734578-e8dae200-7043-11ea-82a5-f99199610fbe.png)

**Comment by yang-xiaodong** [comment]
The event message payload is similar to the HTTP request protocol, and it includes a header and a body. When we persist the message to the database, we need to serialize it in a certain format, so that we can restore the message to the original content when deserializing, instead of just storing the body information.

**Comment by duospeak** [comment]
I hnow what you mean,I quite agree with you about this.  
I mean that if the producer send a wrong message,then the cap consumers will have a problem.

**Comment by duospeak** [comment]
> The event message payload is similar to the HTTP protocol, it includes a header and a body. When we persist the message to the database, we need to serialize it in a certain format, so that we can recover the message to the original when deserializing, instead of just persist the message body.

I hnow what you mean,I quite agree with you about this.
I mean that if the producer send a wrong message,then the cap consumers will have a problem.

**Comment by yang-xiaodong** [comment]
see: https://cap.dotnetcore.xyz/user-guide/zh/cap/messaging/#_3
