### ISSUE TITLE
kafka 消息队列订阅 其他平台程序发布的消息问题（The given key 'cap-msg-type' was not present in the dictionary）

### ISSUE THREAD

**Issue by kbso** [dotnetcore/CAP#532]
第一次使用，CAP ，订阅其他平台程序发布的消息，报了 The given key 'cap-msg-type' was not present in the dictionary. 这个错误，通过 配置 CustomHeaders，发现一个程序只能订阅一个topic
conf.CustomHeaders = kafkaResult => new List<KeyValuePair<string, string>>
                    {
                    
                        new KeyValuePair<string, string>("cap-msg-type", "ContactModel"),
                        //cap-msg-name
                       // new KeyValuePair<string, string>("cap-msg-name", "a2c.account.dev"),
                    };

通过 debug 源码发现，消息在订阅的时候，会通过 cap-msg-name 去invoke 订阅的handle,
此 cap-msg-name is null,所以导致订阅未执行，报错。
通过修改源码，在订阅监听中，增加设置 cap-msg-name ，解决了我的问题。
**请问作者是否是个bug,这样修改是否正确?**
修改的class:
KafkaConsumerClient
修改的监听方法：
` public void Listening(TimeSpan timeout, CancellationToken cancellationToken)
        {
            Connect();

            while (true)
            {
                var consumerResult = _consumerClient.Consume(cancellationToken);

                if (consumerResult.IsPartitionEOF || consumerResult.Value == null) continue;

                var headers = new Dictionary<string, string>(consumerResult.Headers.Count);
                foreach (var header in consumerResult.Headers)
                {
                    var val = header.GetValueBytes();
                    headers.Add(header.Key, val != null ? Encoding.UTF8.GetString(val) : null);
                }
                headers.Add(Messages.Headers.Group, _groupId);

                if (_kafkaOptions.CustomHeaders != null)
                {
                    var customHeaders = _kafkaOptions.CustomHeaders(consumerResult);
                    foreach (var customHeader in customHeaders)
                    {
                        headers.Add(customHeader.Key, customHeader.Value);
                    }
                }

               ###  //此处为添加的代码    添加topic 给 header
                if (headers.ContainsKey(Messages.Headers.MessageName))
                    headers[Messages.Headers.MessageName] = consumerResult.Topic;
                else
                    headers.Add(Messages.Headers.MessageName, consumerResult.Topic);
               ###  //此处为添加的代码    
                var message = new TransportMessage(headers, consumerResult.Value);

                OnMessageReceived?.Invoke(consumerResult, message);
            }
            // ReSharper disable once FunctionNeverReturns
        }`

**Comment by yang-xiaodong** [comment]
see: https://cap.dotnetcore.xyz/user-guide/zh/cap/messaging/#_3

**Comment by kbso** [comment]
谢谢，还是要通读用户手册。
