### ISSUE TITLE
CAP  UseDashboard 

### ISSUE THREAD

**Issue by WuPanFeng** [dotnetcore/CAP#540]
启用 Dashboard  后点击“服务器”菜单，会报错

本地环境：
Net Core 3.1 

CAP环境：
 DotNetCore.CAP   3.0.3
DotNetCore.CAP.Dashboard 3.0.3
DotNetCore.CAP.RabbitMQ 3.0.3
DotNetCore.CAP.SqlServer 3.0.3
点击前
![1](https://user-images.githubusercontent.com/8175717/78655302-67633980-78f8-11ea-84cb-f6b55c2924f5.png)
点击后路径为：http://172.16.40.120:9980/Cap/nodes
直接报错：网络连接错误！
控制台显示日志：
[17:51:10 ERR] Connection id "0HLUQR2PE1OFD", Request id "0HLUQR2PE1OFD:00000079": An unhandled exception was thrown by the application.
System.Collections.Generic.KeyNotFoundException: The given key 'cap.node' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DotNetCore.CAP.Dashboard.DashboardRoutes.<>c.<.cctor>b__2_8(DashboardContext x)
   at DotNetCore.CAP.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at DotNetCore.CAP.DashboardMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

期盼回复！感谢！！！

**Comment by yang-xiaodong** [comment]
Please show your configuraiton

**Comment by WuPanFeng** [comment]
配置在： setup.cs
方法：public void ConfigureServices(IServiceCollection services)
配置详情：
` services.AddCap(config =>
            {
                config.ConsumerThreadCount = 1;

                config.UseSqlServer(Configuration.GetConnectionString("CAPConnection"));
                config.UseRabbitMQ(opt =>
                {
                    opt.HostName = Configuration["RabbitMQ:HostName"];
                    opt.Port = int.Parse(Configuration["RabbitMQ:Port"]);
                    if (!string.IsNullOrEmpty(Configuration["RabbitMQ:UserName"]))
                    {
                        opt.UserName = Configuration["RabbitMQ:UserName"];
                    }
                    if (!string.IsNullOrEmpty(Configuration["RabbitMQ:Password"]))
                    {
                        opt.Password = Configuration["RabbitMQ:Password"];
                    }
                    if (!string.IsNullOrEmpty(Configuration["RabbitMQ:VirtualHost"]))
                    {
                        opt.VirtualHost = Configuration["RabbitMQ:VirtualHost"];
                    }
                });

                if (!string.IsNullOrEmpty(Configuration["RabbitMQ:FailedRetryCount"]))
                {
                    config.FailedRetryCount = int.Parse(Configuration["RabbitMQ:FailedRetryCount"]);
                }
                if (!string.IsNullOrEmpty(Configuration["RabbitMQ:DefaultGroup"]))
                {
                    config.DefaultGroup = Configuration["RabbitMQ:DefaultGroup"];
                }
                config.UseDashboard();
            });`

appsettings配置如下:
`  "RabbitMQ": {
    "HostName": "172.16.40.228",
    "Port": 5672,
    "UserName": "ticket",
    "Password": "ticket",
    "VirtualHost": "/",
    "FailedRetryCount": "",
    "DefaultGroup": ""
  },`

**Comment by yang-xiaodong** [comment]
You need to configure `UseDiscovery`,  see https://github.com/dotnetcore/CAP/issues/479#issuecomment-574716060

**Comment by WuPanFeng** [comment]
感谢回复！！！
看了你发的#479，按照他的配置尝试了一下。
我的配置如下：

`   config.UseDashboard();
                config.UseDiscovery(x =>
                {
                    x.DiscoveryServerHostName = "localhost";
                    x.DiscoveryServerPort = 9990;
                    x.CurrentNodeHostName = "localhost";
                    x.CurrentNodePort = 9980;
                    x.NodeId = "_NodeId";
                    x.NodeName = "_NodeName";
                });`
其中 9980为我netcore 服务运行起来的端口
还是出现了网络连接错误！

**Comment by yang-xiaodong** [comment]
Can't reproduction, closed!
