### ISSUE TITLE
Kafka consumer group does not works in CAP v3.0+

### ISSUE THREAD

**Issue by wangyuzhu** [dotnetcore/CAP#541]
In CAP v3.0 + version, when there are multiple consumer groups in Kafka Transport, sometimes only one consumer group can receive messages normally.

**Comment by wangyuzhu** [comment]
大神，空了把Nuget的包更新一下啊，坐等Nuget上的CAP

**Comment by yang-xiaodong** [comment]
Fixed in version `3.0.4-preview-103991021`
