### ISSUE TITLE
FailedThresholdCallback could not be invoke when the FailedRetryCount value is greater than three

### ISSUE THREAD

**Issue by usama-azakaw** [dotnetcore/CAP#542]
FailedThresholdCallback is not getting invoked when the FailedRetryCount value is greater than 3

                x.FailedRetryCount = 10;
                x.FailedRetryInterval = 60;

**Comment by usama-azakaw** [comment]
@yang-xiaodong your thoughts ??

**Comment by yang-xiaodong** [comment]
I have been busy recently and have not had time to investigate this issue, I will check it this weekend

**Comment by yang-xiaodong** [comment]
Hello @usama-azakaw , 

Hello, I cannot reproduce your issue. The fourth (and subsequent) retry is triggered 4 minutes after the message is added to the database. Is the `retries` of the database the same as the `FailedRetryCount` you configured?

**Comment by usama-azakaw** [comment]
Hi @yang-xiaodong 

Thanks for your response!

Yes initially at the time of configuration I set the **FailedRetryCount** to 50  , after failing for 50 times I can see the value set to 51 in database but FailedThresholdCallback never gets fired

**Comment by yang-xiaodong** [comment]
What caused the failure? publisher or consumer?  Is the type conversion exception or the consumer method call failed?

**Comment by LouieGuo** [comment]
I have this problem, too, FailedThresholdCallback could not be invoke  on consumer

**Comment by LouieGuo** [comment]
the type conversion exception，such as "SerializationException-->Error converting value"

**Comment by LouieGuo** [comment]
sorry . FailedThresholdCallback could be invoke。It's  OK

**Comment by yang-xiaodong** [comment]
Missing response, close this issue, please reopen if necessary
