### ISSUE TITLE
RabbitMQ client connection closed! --> Connection close forced

### ISSUE THREAD

**Issue by wch66** [dotnetcore/CAP#543]
Hello, I use rabbitmq in my service, sometimes it suddenly disconnects. Don't know why? Note: my service is an asp.netcore web application hosted in IIS.
![bdb6fb2afb052a1dfd4f50b52c765a1](https://user-images.githubusercontent.com/36251958/79111289-d2a48400-7dae-11ea-9a3e-a7d1eb6a24d7.png)

**Comment by yang-xiaodong** [comment]
This is due to the recycling of IIS application pool, which is not a issue of CAP.
