### ISSUE TITLE
cap数据丢失

### ISSUE THREAD

**Issue by kaiyangyang** [dotnetcore/CAP#544]
场景：有一个SocketServer，SocketServer里面的操作就是获取客户端发送的数据然后使用Publish发布数据。启动两个客户端连接SocketServer，都定时5分钟向SocketServer发送数据，两个客户端发送的数据不交叉,确定数据是Publish了的，一段时候后数据库publish表出现部分数据丢失，数据库使用SQLserver，消息队列使用RabbitMQ
![image](https://user-images.githubusercontent.com/34677136/79176818-d62e1e80-7e33-11ea-83b2-d2c88812ee1b.png)

**Comment by yang-xiaodong** [comment]
你提供的信息噪音太多，另外你只是描述你的问题，并没有提供CAP的日志或异常以及MQ的日志等信息这些是我需要的，所以我并不能帮助到你。

**Comment by kaiyangyang** [comment]
![image](https://user-images.githubusercontent.com/34677136/79199429-92550c80-7e67-11ea-8340-18f441291f60.png)
rabbitmq日志，cap无异常日志。

就是循环每隔1s publish一条数据

**Comment by yang-xiaodong** [comment]
I can't investigate, closed
