### ISSUE TITLE
How the dashboard's resources can be used properly in the scenario of the Nginx virtual path?

### ISSUE THREAD

**Issue by JaneConan** [dotnetcore/CAP#545]
When we use Nginx, we want to reverse the proxy port number through a virtual path, 
which we can access through, 

for example, 
"http://localhost/{Nginx virtual path}/" 

through the DNC's request forwarding mechanism.

BT, 

We wanted to also access CAP's dashboard through this path, 
for example by setting PathMatch as "cap",

that is, 
accessing "http://localhost/{Nginx virtual path}/cap" 

and we found that static resources could not be accessed properly.

What should we do, thank you?

**Comment by yang-xiaodong** [comment]
This does not seem to be a problem with CAP, I think you need to configure static resources in Nginx configuration
