### ISSUE TITLE
skywalking结合CAP从发布到消费，无法监控全链路

### ISSUE THREAD

**Issue by LouieGuo** [dotnetcore/CAP#546]
@yang-xiaodong, hello, skywalking结合CAP，从发布到消费，我这边无法监控到全链路，是需要特定配置吗？
![image](https://user-images.githubusercontent.com/29138525/79475080-cd0e9e80-8039-11ea-97eb-f98b006c7065.png)

**Comment by yang-xiaodong** [comment]
please show  your environment and configuraiton.

**Comment by yang-xiaodong** [comment]
Issue is transfer to https://github.com/SkyAPM/SkyAPM-dotnet/issues/293
