### ISSUE TITLE
DotNetCore.CAP.Internal.SubscriberExecutionFailedException: Unable to cast object of type 'System.String' to type 'System.Guid'.

### ISSUE THREAD

**Issue by tohkinzhu** [dotnetcore/CAP#547]
The subscribe method can be executed correctly once I published the message in the first time, But I got this issue when CAP retries to execute my Subscribe, this is the Content below：

`{"Headers":{"cap-callback-name":null,"cap-msg-id":"1251519262930919424","cap-msg-name":"PackageApi.ShopeeTrackingNumberError","cap-msg-type":"System.Guid","cap-senttime":"2020/4/18 22:33:39 +08:00","cap-corr-id":"1251519262930919424","cap-corr-seq":"0","cap-msg-group":"cap.queue.PackApiInternal.v1"},"Value":"f2ca935f-c3de-3a7b-bfdb-39f4982cea2c"}`

 Version="3.0.3"  MYSQL

Thanks

**Comment by yang-xiaodong** [comment]
Thanks for your feedback,  this is a bug and we will fixed it in version 3.0.4.

_PS: Can you give a star?_

**Comment by tohkinzhu** [comment]
嗯 老早之前就star过了 感谢老铁的贡献
