### ISSUE TITLE
start subscriberService listen client without a Microsoft.Hosting.IHost ?

### ISSUE THREAD

**Issue by vivid216** [dotnetcore/CAP#549]
- now i maintenance an old WinForm application , and plan use CAP as an Consumer client to receive other microservice broadcast events !  i define a new self-Managed ServiceCollection() for dependencyInjection,  so there is no Ihost.start()  method execute.  after register  AddCap() and BuildServiceProvider(), i run a Applicaiton.Run(new Form()) start a winform app. 

   so finally, a subscriberService can't be triggered, an look up 'DotNetCore.CAP.Internal.IBootstrapper' has **not** been registered.  i think when i register AddCap() method, the code  `services.AddHostedService<Bootstrapper>();` may can't be registered or invoke start ?  so, how to run a CAP register in an winform app ? thanks a lot !

**Comment by yang-xiaodong** [comment]
we are not support .NET Framework
