### ISSUE TITLE
How to output error messages(ExceptionMessage) in the Message Content on the dashboard?

### ISSUE THREAD

**Issue by JaneConan** [dotnetcore/CAP#552]
How to output error messages in the Message Content on the dashboard?

**Comment by yang-xiaodong** [comment]
This feature was temporarily disabled in version 3.0 for performance reasons

**Comment by JaneConan** [comment]
Thx~ bt, how can i show some message when it makes the error? we can by callback? how can i use that~

**Comment by yang-xiaodong** [comment]
This feature has been implemented

**Comment by JaneConan** [comment]
thank you very much♥
