### ISSUE TITLE
Is there only one way to increase subscribers by starting multiple projects?

### ISSUE THREAD

**Issue by zhenlei520** [dotnetcore/CAP#555]
I want to ask is there any way without increasing the number of cases can increase consumer services, in the process of using usual found after using Cap leads to message queuing, producers are far greater than the consumer, can produce news piled up, but I don't want to start again temporarily multiple services, whether through simple configuration in the same service to expand the amount of a message consumer

**Comment by yang-xiaodong** [comment]
I don't konw what do you mean ` increasing the number of cases `?

Are your want to know this featuer ?
https://cap.dotnetcore.xyz/user-guide/zh/cap/configuration/#consumerthreadcount

**Comment by zhenlei520** [comment]
yes  ConsumerThreadCount  thank you

**Comment by zhenlei520** [comment]
yes  ConsumerThreadCount  thank you
