### ISSUE TITLE
Subscribe to multiple message types per topic

### ISSUE THREAD

**Issue by jblackburn21** [dotnetcore/CAP#556]
Hi, we're using this library for pub/sub with kafka as our broker. We have everything running successfully, but I haven't been able to successfully subscribe to multiple message types per topic.

Given this example, we have a users topic, and publish UserCreated and UserUpdated events. The publish side is working as expected, and the messages have a cap-msg-type header with the corresponding type.

```
public abstract class UserEvent
{
    protected UserEvent(Guid userId, string name, DateTime createdOn)
    {
        Name = name;
        CreatedOn = createdOn;
        UserId = userId;
    }

    public Guid UserId { get; }
    
    public string Name { get; }
    
    public DateTime CreatedOn { get; }
}

public class UserCreated : UserEvent
{
    public UserCreated(Guid userId, string name, DateTime createdOn) : base(userId, name, createdOn) { }
    
    public static UserCreated Create(string name) => new UserCreated(Guid.NewGuid(), name, DateTime.Now);
}

public class UserUpdated : UserEvent
{
    public UserUpdated(Guid userId, string name, DateTime createdOn) : base(userId, name, createdOn) { }
    
    public static UserUpdated Create(Guid userId, string name) => new UserUpdated(userId, name, DateTime.Now);
}
```

However, on the subscribe side, I would like to have individual handlers for each message type.

```
public interface IHandleEvent<in TEvent> : ICapSubscribe
{
    Task Handle(TEvent @event);
}

public class UserCreatedHandler : IHandleEvent<UserCreated>
{
    private readonly ILogger<UserCreatedHandler> _logger;

    public UserCreatedHandler(ILogger<UserCreatedHandler> logger) => _logger = logger;

    [CapSubscribe("cap.kafka.sqlserver")]
    public Task Handle(UserCreated @event)
    {
        _logger.LogInformation($"Handled UserCreated with Id {@event.UserId}");
        
        return Task.CompletedTask;
    }
}

public class UserUpdatedHandler : IHandleEvent<UserUpdated>
{
    private readonly ILogger<UserUpdatedHandler> _logger;

    public UserUpdatedHandler(ILogger<UserUpdatedHandler> logger) => _logger = logger;

    [CapSubscribe("cap.kafka.sqlserver")]
    public Task Handle(UserUpdated @event)
    {
        _logger.LogInformation($"Handled UserUpdated with Id {@event.UserId}");
        
        return Task.CompletedTask;
    }
}
```

In this example, I want 2 subscribers for the same topic, and have the messages routed by type, but I don't see a mechanism in the library to support this. Only the first subscriber handles all messages types, and the groups concept doesn't really fit here.

Based on this it looks like my options are to provide an impl for IConsumerRegister and IConsumerServiceSelector, or to have a single CAP handler for each topic, and have another mechanism to route specific message types. Have you ran into this, or have a recommendation on how to approach this?

Also, thank you for this great lib.

**Comment by yang-xiaodong** [comment]
Hello,

CAP does not read the type of message content for routing. On the contrary, as long as your subscribed message can be deserialized correctly, even if it is different from the sender of the message type, it also can be accepted. This scenario is very common in cross-service .

In response to your question, I suggest you take one of two ways.

* Use different topics for different operations, namely `cap.kafka.sqlserver.usercreated` and `cap.kafka.sqlserver.userupdated`

* Use the topic `cap.kafka.sqlserver`, but add a type to your UserEvent, and then you control the routing. E.g
```cs
[CapSubscribe ("cap.kafka.sqlserver")]
public Task Handle (UserEvent @event)
{
     if (@event.Type == "UserCreate") 
     {
         HandleUserCreated (@event);
     } 
     else if (@event.Type == "UserUpdated") 
     {
         HandleUserUpdated (@event);
     }
}
```
At present, `cap-msg-type` header it is just a record, it has not been used in actual use.

In your scenario, you may be able to use this header for routing without add the type to your UserEvent class

**Comment by jblackburn21** [comment]
Thank you for the suggestions.
