### ISSUE TITLE
ISerializer的SerializeAsync问题

### ISSUE THREAD

**Issue by luoxinliu** [dotnetcore/CAP#560]
我想实现ISerializer
正常情况下读取SerializeAsync没问题
问题是：
如果是应用重启，再从mysql读取之前未同步的数据，SerializeAsync方法读取的message.Value 的值是Newtonsoft.Json.Linq.JObject对象，不符合预期
而且StringSerializer这个类也不能注入
Newtonsoft.Json.Linq.JObject占用大量内存无法正常释放

**Comment by yang-xiaodong** [comment]
duplicate of #547
