### ISSUE TITLE
Can't receive message in .Net Core Console app

### ISSUE THREAD

**Issue by hjonwy** [dotnetcore/CAP#566]
Hi, 

I can't receive message in a Console app, following is my source code. 
BTW, I can receive message in a WebAPI app, any comments or suggestion?

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            IConfigurationBuilder configBuilder = new ConfigurationBuilder();
            configBuilder.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
            var config = configBuilder.Build();

            IServiceCollection services =  new ServiceCollection();
            services.AddTransient<IMyService, MyService>();
            services.AddLogging(builder =>
            {
                builder.AddConfiguration(config.GetSection("Logging"));
                builder.AddConsole();
            });
            
            services.AddCap(x => {
                x.UseMySql("server=localhost;port=3306;user id=root;password=Abc_123@johnhu;database=mydatabase2;charset=utf8mb4;ConnectionReset=false;");
                x.UseRabbitMQ(options => {
                    options.UserName = "guest";
                    options.Password = "guest";
                    options.HostName = "localhost";
                    options.VirtualHost = "/";
                });
            });

            IServiceProvider serviceProvider = services.BuildServiceProvider();
            ICapPublisher eventBus = serviceProvider.GetService<ICapPublisher>();

            Console.ReadLine();
        }
        
    }

    public interface IMyService
    {
        void TestFunc(DateTime value);
    }

    public class MyService : IMyService, ICapSubscribe
    {
        [CapSubscribe("com.johnhu.message", Group="Group2")]
        public void TestFunc(DateTime value)
        {
            Console.WriteLine($"MyService Handled message com.johnhu.message, {value}");
        }
    }

**Comment by yang-xiaodong** [comment]
CAP relies on IHostedService to start the service, and we recommend you use WorkerService.

If it's a console application, you need to start it manually
```
serviceProvider.GetService<IBootstrapper>().BootstrapAsync(cancelToken);
```

**Comment by hjonwy** [comment]
Thanks, switched to use WorkService project instead of console project, all works fine.
