### ISSUE TITLE
如何把subscriber的topic做成从配置文件读取

### ISSUE THREAD

**Issue by suxi** [dotnetcore/CAP#57]
我的系统的各个业务系统是由各种语言开发的,不方便直接在各个系统中直接嵌入CAP库.
所以我考虑做一个类似代理服务的模块,subcriber使用同步方式去调用各个系统的api来完成消息通知.
为了在各个系统的消息需求增加或变化的时候,这个代理模块的代码保持相对稳定,希望能通过本地配置文件来注册topoic而不是用[CapSubscriber()]方式.
目前的思路是仿造ISubscriber接口方式增加一 个ICustomerSubscriber接口,然后把所有注册的topic消息用一个函数在处理,这个函数再根据消息的topic名去调用不同的业务系统api.
因为是第一次使用asp.net core,对自定义services不是很了解,可否请教从哪个类入手修改最合适.

**Comment by yuleyule66** [comment]
你这样用代理的方式可能有很多问题。

首先，CAP用来保证分布式事务的前提是首先需要集成本地事务的持久化消息的，这样可以保证消息在业务代码执行期间消息是肯定能够存储成功的。然后CAP通过ICapPublisher接口发送消息，这个消息格式是有一定要求的，要不然在接收到之后反序列化可能会出问题。 订阅这一块也是有和Dashboard功能配合的，如果你不使用[CapSubscriber()]这样方式那么Dashboard这里的订阅列表功能也需要修改。

你的这个需求，我建议你直接封装一下MQ客户端简单实现即可。

**Comment by suxi** [comment]
publisher这块我准备为各个系统提供对应语言的sdk来实现发送的本地事务保护.
subscriber这块因为各个系统涉及各个部门,sdk的开发和维护量有点大,权衡下来就是用同步方法,失败就重发的方式来保证通知的可靠性
dashboard这块可以先不使用
主要是想知道如何在runtime时为consumerclient注册topic,请指教.

**Comment by jjjjj10231023** [comment]
我这样描述你的需求是否恰当：
有几个不同语言开发的系统，这些系统间需要相互传递消息，消息的类型可能会变化（有未知可能）。消息的传递想通过一个asp.net core 的系统中转。
不明白的地方：消息有实时性要求如何？
感觉不能完全理解你的需求，也行是知识不够

**Comment by yuleyule66** [comment]
@suxi MQ的客户端似乎不能在运行时增加Consumer哦？

**Comment by suxi** [comment]
@jjjjj10231023 差不多是这样的需求,不过publish侧我会提供sdk给各个系统,subsribe侧我希望用代理方式进行中转,当然一个业务系统会有一个独立的代理为它服务,没有很强的实时性需求,因为eventbus本来已经是异步了.
@yuleyule66 可能说运行时不够准确,是在asp.netcore setup的时候,读取配置的topic信息,并绑定到指定的ISubscribeService的某个method(目前简单处理,选第一个)上.目前我已经完成这个功能,现在正在看怎么把topic还有messageid转给这个函数来提供中转必要的参数.

**Comment by suxi** [comment]
功能已实现

**Comment by vasile-cuzmin** [comment]
> Function has been implemented

How can I do that?
