### ISSUE TITLE
Pass SqlConnection to UseSqlServer method

### ISSUE THREAD

**Issue by pozy** [dotnetcore/CAP#573]
Hi
In my scenario I need to use SQL Server as a storage database with custom `DbConnection` created earlier by my application. Unfortunately method
``CapOptionsExtensions.UseSqlServer(this CapOptions options, string connectionString)``
accepts only connection string, which I can't use.

Is there any workaround for this issue? I tried to figure out from source code if using `DbConnection` is possible, but I haven't found any way to do that.

If it's indeed not possible now, have you considered adding support for custom `DbConnection`s? I could try to create a PR myself, but I wanted to know if it will be welcomed :).

Cheers

**Comment by yang-xiaodong** [comment]
Hello @pozy ,

After discussion, we do not intend to add this feature, because DbConnection is not a feature that most people need and will cause a lot of changes.

**Comment by pozy** [comment]
Ok, thanks for the info:). I'll try to find other solution.
