### ISSUE TITLE
can not be found subscriber 和 kafka 多消费者问题

### ISSUE THREAD

**Issue by lijinchengpro** [dotnetcore/CAP#576]
public class ConsumerController : Controller
    {
        [NonAction]
        [CapSubscribe("test", Group ="g1")]
        public void ReceiveMessage(DateTime time)
        {
            Console.WriteLine("g1 message time is:" + time);
        }

        [NonAction]
        [CapSubscribe("test", Group = "g2")]
        public void ReceiveMessage2(DateTime time)
        {
            Console.WriteLine("g2 message time is:" + time);
        }

        [NonAction]
        [CapSubscribe("test", Group = "g3")]
        public void ReceiveMessage3(DateTime time)
        {
            Console.WriteLine("g3 message time is:" + time);
        }

       [NonAction]
        [CapSubscribe("test", Group ="g4")]
        public void ReceiveMessage(DateTime time)
        {
            Console.WriteLine("g4 message time is:" + time);
        }
    }

1. 再将topicName由test.show.time改成test之后，且rabbitmq已删除g4.v1队列，exchange也无相关绑定，无论切换rabbitmq和kafka都出现以下错误，参考issues63无果
DotNetCore.CAP.Internal.SubscribeDispatcher[0]
      Message (Name:test.show.time,Group:g4.v1) can not be found subscriber
see: https://github.com/dotnetcore/CAP/issues/63
2.  使用kafka，topicName在原先test.show.time时，只有一个group被消费，无法多个group被同时消费，切换到rabbitmq可正常同时消费

**Comment by yang-xiaodong** [comment]
closed by https://zhuanlan.zhihu.com/p/25795393
