### ISSUE TITLE
Recommend to create a new independent extension project for efcore dependency

### ISSUE THREAD

**Issue by xiangxiren** [dotnetcore/CAP#577]
Currently, dapper and efcore are both referenced. If you use one of the other ORM frameworks in your project, you rely on three at the same time. Therefore, I recommend migrating the dependency on the efcore to a new extension project that can be referenced by the consumer separately. Even, I recommend removing the dependency on dapper and using native ado.net to store and read messages. Of course, it's just a suggestion.

**Comment by yang-xiaodong** [comment]
Would you like to submit a PR that replaces dapper with ado.net?

**Comment by yang-xiaodong** [comment]
New feature has been release with nuget package `3.1.0-preview-108719052`
