### ISSUE TITLE
Cannot insert duplicate key in object 'Cap.Published'

### ISSUE THREAD

**Issue by WillPhoenixLiu** [dotnetcore/CAP#579]
Sometimes we have these exceptions in our prod environment.
System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_Cap.Published'. Cannot insert duplicate key in object 'Cap.Published'. The duplicate key value is (1268468068502446080).

This error makes it don't send message to Queue. Do you have any retry policy when these kind of exception happens?

**Comment by yang-xiaodong** [comment]
see https://github.com/dotnetcore/CAP/issues/294
