### ISSUE TITLE
Is this a typo? (DefaultGroup should be mapped to ConsumerGroupId in Kafka, NOT TopicName)

### ISSUE THREAD

**Issue by fudiwei** [dotnetcore/CAP#585]
As I read the documentation, I noticed that there is a section describes how to configure.

> https://cap.dotnetcore.xyz/user-guide/en/cap/configuration/

There is a saying like this: 

> `DefaultGroup`
> 
> Default: `cap.queue.{assembly name}`
> 
> The default consumer group name, corresponding to different names in different Transports, you can customize this value to customize the names in Transports for easy viewing.
> 
> **Mapping**
> 
> Map to `Queue Names` in RabbitMQ.
> Map to `Topic Name` in Apache Kafka.
> Map to `Subscription Name` in Azure Service Bus.

In my mind, this option might be the default of the attribute property named `Group`. So I tried to read the related source codes.

https://github.com/dotnetcore/CAP/blob/ce07c555b29ee86bfe02e56ab5233257b4eaf873/src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs#L146-L156
https://github.com/dotnetcore/CAP/blob/6f61c4c3f4d60f695f2111c070e75cd37ecad1e1/src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs#L23-L27
https://github.com/dotnetcore/CAP/blob/6f61c4c3f4d60f695f2111c070e75cd37ecad1e1/src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs#L107-L116

> https://github.com/dotnetcore/CAP/#subscribe-group
> The concept of a subscription group is similar to that of a consumer group in Kafka.

I think this is a typo. By rights, it should be defined in this words: 

**Map to `Consumer Group Id` in Apache Kafka.** (NOT `Topic Name`)

-----

当我阅读文档时，我注意到有一个描述配置的章节。

> 文档地址：https://cap.dotnetcore.xyz/user-guide/zh/cap/configuration/

文档中有一段话是这样写的：

> `DefaultGroup`
> 默认值：`cap.queue.{程序集名称}`
> 
> 默认的消费者组的名字，在不同的 Transports 中对应不同的名字，可以通过自定义此值来自定义不同 Transports 中的名字，以便于查看。
> 
> **映射**
> 在 RabbitMQ 中映射到 `Queue Names`。
> 在 Apache Kafka 中映射到 `Topic Name`。
> 在 Azure Service Bus 中映射到 `Subscription Name`。

在我的理解里，这个配置是作为 `Group` 这一个特性属性的默认值的，以避免多个消费者消费到同样的消息。因此我阅读里有关的源代码（见上面英文版本）。

> https://github.com/dotnetcore/CAP/blob/master/README.zh-cn.md#%E8%AE%A2%E9%98%85%E8%80%85%E7%BB%84
> 订阅者组的概念类似于 Kafka 中的消费者组。

我觉得这里有一个笔误，正确的说法应该是：

> 在 Apache Kafka 中映射到 `Consumer Group Id`（而不是 `Topic Name`）。

**Comment by yang-xiaodong** [comment]
Yes,  would you like to submit a PR to fix it ?

**Comment by fudiwei** [comment]
See [PR-586](https://github.com/dotnetcore/CAP/pull/586).

**Comment by yang-xiaodong** [comment]
Docs site has been updated , Thank you.
