### ISSUE TITLE
Has the version isolation feature become invalid?

### ISSUE THREAD

**Issue by yuyixg** [dotnetcore/CAP#590]
1. Can the same topic version isolation in Canary deployment be provided?
2. From the code point of view, the message version is not attached to the message body through the message header, can it only be isolated by the Topic?

**Comment by yang-xiaodong** [comment]
The version isolation provided by CAP is not used for canary deployment. You can customize the header to implement the function of canary deployment for business feature.

To be precise, it is similar to multiple versions of WebApi v1, v2, v3 etc, each version has a different code version, they implement routing through the gateway, and provide external services at the same time. In CAP, we provide the Version configuration options  to do this.

For example, in the Kubernets cluster, different versions use different namespaces, they work at the same time, but are sharing database resources.

**Comment by yuyixg** [comment]
Thank you for your answer.

I strongly agree with you that if the framework can provide middleware code insertion logic, it may make the code more maintainable

Currently it can only be achieved through different namespaces
