### ISSUE TITLE
How do You configure multiple MQ services（clusters）

### ISSUE THREAD

**Issue by 380086154** [dotnetcore/CAP#592]
`public void ConfigureServices(IServiceCollection services)
{
    // ...

    services.AddCap(x =>
    {
        x.UseRabbitMQ(opt=>
        {
            //RabbitMQOptions
        });
        // x.UseXXX ...
    });
}`

`services.AddCap(x =>
{
    x.UseRabbitMQ(o =>
    {
        o.HostName = "localhost";
        o.ConnectionFactoryOptions = opt => { 
            //rabbitmq client ConnectionFactory config
        };
    });
});`

This is an example from the https://cap.dotnetcore.xyz 

let me know how to configure multiple services. 

PS: 
`  "RabbitMQOptions": {
    "Port": 5672,
    "VirtualHost": "xxx",
    "UserName": "xxx",
    "Password": "xxx",
    **"Hosts": [ "192.168.100.134:5672","192.168.100.135:5672" ]**
  }`

tks.

**Comment by yang-xiaodong** [comment]
https://github.com/dotnetcore/CAP/issues/389#issuecomment-525315168
