### ISSUE TITLE
请问有更详细的有关事务的例子吗？

### ISSUE THREAD

**Issue by 10463082** [dotnetcore/CAP#60]
比如回滚和提交，补偿操作等？

**Comment by yuleyule66** [comment]
请先学习分布式事务 :
[http://www.cnblogs.com/savorboard/p/distributed-system-transaction-consistency.html](http://www.cnblogs.com/savorboard/p/distributed-system-transaction-consistency.html)
然后阅读CAP wiki :
[https://github.com/dotnetcore/CAP/wiki](https://github.com/dotnetcore/CAP/wiki)

设为关闭，如果还有其他问题，请 reopen。
