### ISSUE TITLE
Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection

### ISSUE THREAD

**Issue by bingowu0708** [dotnetcore/CAP#601]
你好，更新至netcore 3.1版本使用SqlServer并用ADO.net进行连接发布消息时报“Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'.”错误。

var transactionKey = ((SqlConnection) dbTransaction.Connection).ClientConnectionId;

**Comment by yang-xiaodong** [comment]
Duplicate of  #570
