### ISSUE TITLE
Add configuration to support stopping default retries

### ISSUE THREAD

**Issue by xy00869474** [dotnetcore/CAP#604]
could you add a configuration to cancel the 3 times retrying  immediately when messages consumed or sent failure?

**Comment by yang-xiaodong** [comment]
Please describe the reason you need to add the options, we will evaluate it

**Comment by xy00869474** [comment]
my interface is complex and  runs slowly,it always runs failure in a period of time beacuse of the network environment is bad or the third part interface that i calls in my program break off.
i wish my interface runs after the FailedRetryInterval when it failed.

**Comment by yang-xiaodong** [comment]
Is it because your network is unstable, so you need this feature to reduce execution failures?

This reason cannot support us to add configuration items

**Comment by xy00869474** [comment]
The subscriber may access the deadlock database resource,it cannot success in a short period of time.
The default immediate retries may increase the database pressure, beacusa the interval is too short.

**Comment by yang-xiaodong** [comment]
So this is caused by your program bug, it is expected, if you don’t want to retry, you can use try catch warp the error to make it successful

**Comment by xy00869474** [comment]
But i want the subscriber try again later and is not  immediate,if i try catch warp the error,it may not retry.
