### ISSUE TITLE
use Rabbitmq push message from CAP，but do not push message success ,database show the message status is schedule

### ISSUE THREAD

**Issue by Hugo-Ho** [dotnetcore/CAP#605]
这是.NET Core打印出来的日志
![image](https://user-images.githubusercontent.com/52446959/87045963-1b8f9b80-c22b-11ea-8491-f49c7e6a52e1.png)

**Comment by Hugo-Ho** [comment]
这是一直滞留在数据库显示schedule的消息
![QQ浏览器截图20200709211030](https://user-images.githubusercontent.com/52446959/87046369-b2f4ee80-c22b-11ea-8636-6cfab424e324.png)

**Comment by Hugo-Ho** [comment]
还有一个问题想咨询，cap的使用是否会和RabbitMQ .NET Client的nuget组件有冲突，我发现使用cap后不能再使用这个组件包来处理RabbitMQ的发布订阅

**Comment by Hugo-Ho** [comment]
使用Rabbitmq.net client获取队列消息就会报异常：Method not found: 'Byte[] RabbitMQ.Clien t.BasicGetResult.get_Body()'.
其实之前我已经发现使用RabbitMQ.Clien5.1.2以上版本就会影响CAP的消息发送，感觉两者之间是否存在冲突？？
![image](https://user-images.githubusercontent.com/52446959/87056921-da05ed00-c238-11ea-919f-ec2d91a23405.png)

**Comment by xiangxiren** [comment]
> 使用Rabbitmq.net client获取队列消息就会报异常：Method not found: 'Byte[] RabbitMQ.Clien t.BasicGetResult.get_Body()'.
> 其实之前我已经发现使用RabbitMQ.Clien5.1.2以上版本就会影响CAP的消息发送，感觉两者之间是否存在冲突？？
> ![image](https://user-images.githubusercontent.com/52446959/87056921-da05ed00-c238-11ea-919f-ec2d91a23405.png)
确保你引用的DotNetCore.CAP.RabbitMQ版本依赖的RabbitMQ.Client版本和你项目中单独引用的RabbitMQ.Client版本是否一致？

**Comment by yang-xiaodong** [comment]
Reference : https://github.com/dotnetcore/CAP/pull/575

**Comment by BartNSTCL** [comment]
Just a head-up about future breakage, RabbitMQ.Client 7.0.0.-alpha.2 Doesn't use IModel, changed to IChannel.
https://github.com/rabbitmq/rabbitmq-dotnet-client/discussions/1456

**Comment by yang-xiaodong** [comment]
> Just a head-up about future breakage, RabbitMQ.Client 7.0.0.-alpha.2 Doesn't use IModel, changed to IChannel.只是关于未来损坏的提醒，RabbitMQ.Client 7.0.0.-alpha.2 不使用 IModel，更改为 IChannel。 [rabbitmq/rabbitmq-dotnet-client#1456兔子q/rabbitmq-dotnet-client#1456](https://github.com/rabbitmq/rabbitmq-dotnet-client/discussions/1456)

Thanks for your head-up
