### ISSUE TITLE
Cap Dashboard : The given key 'cap.node' was not present in the dictionary

### ISSUE THREAD

**Issue by galabaoche** [dotnetcore/CAP#609]
browse other Tab normally, but when click `Servers` tap return 500 error.
service capture message :  the given key 'cap.node' was not present in the dictionary

**Comment by galabaoche** [comment]
cap version 3.0.4

**Comment by xiangxiren** [comment]
Has been fixed in 3.1.0-preview-111117527 #600

**Comment by galabaoche** [comment]
ok, thanks
