### ISSUE TITLE
mongo db query is incorrect

### ISSUE THREAD

**Issue by shanerogers** [dotnetcore/CAP#612]
Hey I've created a PR - https://github.com/dotnetcore/CAP/pull/611
I want to look at using this in our environment and keen to get this issue fixed. As we don't really want to have to use the dashboard to retry messages.
Thanks,

**Comment by shanerogers** [comment]
@yang-xiaodong Can you please take a look at this for a merge and include in a new pre-release in Nuget? Currently this is a show stopper for me to use in our real solution. Currently I've got a local copy of this class.

**Comment by shanerogers** [comment]
`
 services .AddCap(capOptions =>
                {                
                    capOptions.UseRabbitMQ( "xxx");
                    capOptions.UseMongoDB(dbOptions =>
                    {
                        dbOptions.DatabaseName = "XXX";
                        dbOptions.PublishedCollection = "Outbox.Publish";
                        dbOptions.ReceivedCollection = "Outbox.Received";
                    });
                });

    // temp: fix mongo db query issue.
    services.AddSingleton<IDataStorage, MongoDbDataStorage>();`

**Comment by yang-xiaodong** [comment]
Fixed in perview version `3.1.0-preview-112250362` , Thank you
