### ISSUE TITLE
Define partials on CapSubscibe

### ISSUE THREAD

**Issue by pascal89** [dotnetcore/CAP#613]
Hi,
I'm quite interested in the idea to be able to define partial topic subscriptions, to be able to group (topic) subscriptions within a single class. Next up I've defined an example to get the idea:

```csharp
[CapSubscribe("customers")]
public class CustomersCapController : ICapSubscibe
{
    [CapSubscribe(".create", isPartial: true)]
    public Task HandleCreationAsync(Customer customer)
    {
    }

    [CapSubscribe(".update", isPartial: true)]
    public Task HandleUpdateAsync(Customer customer)
    {
    }
}
```

With the `isPartial:true` you'd define that this topic part should be combined with the one defined on the class. This will then result in a subscription on `customer.create` for the first method.

What I'd like to achieve is to be able to make a base crud controller class where I'd define the crud operation endpoints (from the message queue point of view). So with the methods described in the example but then with a generic model. Then in the child class only need to define the `CapSubscribe` annotation on the class definition to prefix the topics with the collection name.

I'd like to propose this to be a new feature for a future release and I'd like to create a pull request for an implementation if desired.

**Comment by yang-xiaodong** [comment]
HI, 
Sorry for the delayed response. It sounds good, just like MVC routing. PR is welcome, thanks.

**Comment by pascal89** [comment]
Hi,
Thanks for merging my PR. Would you like to publish a pre-release including this change?

**Comment by yang-xiaodong** [comment]
Sure ,version `3.1.0-preview-112969177`  has been include this changes.

Thanks for your PR
