### ISSUE TITLE
Multiple publishAsync do not rollback if one fails

### ISSUE THREAD

**Issue by Henery309** [dotnetcore/CAP#614]
Hi, thanks for the awesome library works really well. 

I've noticed an issue when publishing multiple messages (3 messages in 1 call). Appears that cap is  committing transaction when ever the PublishAsync message is called and if we have multiple PublishAsync the subsequent PublishAsync  is run in another transaction (My assumption please correct me if I am wrong.). If an error occurs during second PublishAsync(timeout etc) call the second message will be lost.

**Example**
I am publishing 3 messages within the begin transaction as seen below. When the first message is published successfully cap updates the message status to successful after service bus ack (as expected). Once cap is done with the first message, it moves to the second message. Cap starts of by inserting the second message into the published table. If this fails, we lose the second and third message.

**Possible Solution**
- The publishAsync should accept multiple messages and insert all the message into the published table within the same transaction. 
- This will guarantee that we will not lose any message if ack update fails. 
- Then 1 by 1 or in batch it should publish the messages to Service bus.
- This solution will be ideal when you want to publish 1-5 message within the same request. If anyone wants to send 1 million messages then they should really be looking into batch solution instead of cap. 

**Work Around**
Following is the workaround that I am currently using.
- 1 - Add all 3 messages into 1 single message and publish that when request occurs
- 2 - Use Azure Service bus trigger in azure function to listen to the message 
- 3 - Within azure functions generate three messages and publish them again to azure service bus using batch.
- 4 - Now the consumers of the messages can listen and complete their task. All three messages have their own consumers. 

```
// Code omitted that updates entities.	
				
await using (_dbContext.Database.BeginTransaction(_capPublisher, true))
{                    
    await _jobDbContext.SaveChangesAsync(cancellationToken);
    
    // Publish Message 1                   
    await _capPublisher.PublishAsync(message1.MessageName, message1, cancellationToken: cancellationToken);
	
   // Publish Message 2
   await _capPublisher.PublishAsync(message2.MessageName, message1, cancellationToken: cancellationToken);
   
   // Publish Message 3
   await _capPublisher.PublishAsync(message3.MessageName, message1, cancellationToken: cancellationToken);
}
```

**Comment by yang-xiaodong** [comment]
When starting a transaction, set `autoCommit` to `false` and the transaction will be controlled by you, for example:

```C#
using (var trans = dbContext.Database.BeginTransaction(_capPublisher, autoCommit: false))
{
    // Publish Message 1                   
    await _capPublisher.PublishAsync(message1.MessageName, message1, cancellationToken: cancellationToken);

    // Publish Message 2
    await _capPublisher.PublishAsync(message2.MessageName, message1, cancellationToken: cancellationToken);

    // Publish Message 3
    await _capPublisher.PublishAsync(message3.MessageName, message1, cancellationToken: cancellationToken);

    await dbContext.SaveChangesAsync(cancellationToken);

    trans.Commit();
}
```

**Comment by Henery309** [comment]
thanks that did the trick.
