### ISSUE TITLE
如何关闭数据库数据自动定期清理

### ISSUE THREAD

**Issue by kisshexuxia** [dotnetcore/CAP#615]
CAP 版本2.6
设置SucceedMessageExpiredAfter目的是 设置处理成功的数据在数据库中保存的时间（秒），为保证系统新能，数据会定期清理。
  x.SucceedMessageExpiredAfter = 24 * 3600;

但是实际项目中往往出现在定期清理的时候，数据正在插入造成死锁。有没有参数关闭自动清理。难道只能把这个实际设置的长点吗？
我想清理自己晚上空余时间定时去删除好了。

**Comment by yang-xiaodong** [comment]
Version 2.6 is no longer supported, please use the latest version
