### ISSUE TITLE
Expires At - 1 hour or 1 day?

### ISSUE THREAD

**Issue by captmomo** [dotnetcore/CAP#623]
In the docs;

Data Cleanup¶
There is an ExpiresAt field in the database message table indicating the expiration time of the message. When the message is sent successfully, status will be changed to Successed, and ExpiresAt will be set to 1 hour later.

However, when I check the database, it is 1day. The startup configuration also show 1 day.

![image](https://user-images.githubusercontent.com/25576022/89444917-09027680-d785-11ea-8ef4-acc4879f34bd.png)

**Comment by yang-xiaodong** [comment]
where is the docs links?  

https://cap.dotnetcore.xyz/user-guide/zh/cap/configuration/#succeedmessageexpiredafter
here is right

**Comment by captmomo** [comment]
https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#data-cleanup
