### ISSUE TITLE
Upgrade Microsoft.Azure.ServiceBus to latest

### ISSUE THREAD

**Issue by Henery309** [dotnetcore/CAP#628]
Hi Looks like the DotNetcore.CAP.AzureServiceBus project is using outdated Microsoft.Azure.ServiceBus  package.
Currently it's using 3.0.4, latest version available is 4.1.4. The 3.0.4 version is using outdated System.IdentityModel.Tokens.Jwt package. Would you like me to create a pull request with the updated version?

**Comment by yang-xiaodong** [comment]
Hi @Henery309 ,
Sure, Thanks

**Comment by Henery309** [comment]
Hi Looks like you have already updated the nuget packages and updated version is in 3.1.0 preview. When do you plan to release 3.1.0?

Thanks for this awesome library love it 👍. Really appreciate the effort you have put in this.

**Comment by yang-xiaodong** [comment]
Hi @Henery309 ,  Version 3.1.0 has been released!
