### ISSUE TITLE
MatchPath  无效

### ISSUE THREAD

**Issue by clayzhangwl** [dotnetcore/CAP#630]
自定义的 MatchPath  路径没有起作用

// 注册节点到  
				x.UseDiscovery(d =>
				{
					d.MatchPath = "/mycap";
					d.DiscoveryServerHostName = "localhost";
					d.DiscoveryServerPort = 8500;
					d.CurrentNodeHostName = "localhost";
					d.CurrentNodePort = 5000;
					d.NodeId = "1";
					d.NodeName = "Zhaoxi.RabbmitMQ";
				});

**Comment by luoyunchong** [comment]
借楼说下，3.1.0-preview-112969177 有问题， 下面是示例，消息无法接收到。可以发个新的预览版替代他。

[CAP.zip](https://github.com/dotnetcore/CAP/files/5068128/CAP.zip)

**Comment by yang-xiaodong** [comment]
This issue is set to backlog, we will  verification it in the future

**Comment by yang-xiaodong** [comment]
Hello, we have provided the MatchPath option for consul in version 5.1 to help solve this problem. If there are other problems, please feedback.
