### ISSUE TITLE
In the Linux environment, how to set the dashboard to display Chinese.

### ISSUE THREAD

**Issue by xiangxiren** [dotnetcore/CAP#631]

**Comment by yang-xiaodong** [comment]
We detect according to the browser language and do not support manual set it

**Comment by xiangxiren** [comment]
But my browser language setting is Chinese. When debugging locally, the dashboard displays Chinese. But after deploying to the linux server, it is displayed in English.

**Comment by yang-xiaodong** [comment]
Fixed in version `3.1.0-preview-114160390`
