### ISSUE TITLE
cann't change publish or sub table name for sqlserver

### ISSUE THREAD

**Issue by zhuang1125** [dotnetcore/CAP#632]
cann't change publish or sub table name for sqlserver.  the table name is hard coding at sql text.

master:  CAP/src/DotNetCore.CAP.SqlServer/IStorageInitializer.SqlServer.cs
line 60:   CREATE TABLE [{schema}].[Received](
line  70：  CONSTRAINT [PK_{schema}.Received] PRIMARY KEY CLUSTERED
line 79： CREATE TABLE [{schema}].[Published](
line 88：  CONSTRAINT [PK_{schema}.Published] PRIMARY KEY CLUSTERED

**Comment by yang-xiaodong** [comment]
@xiangxiren Would you like to fix this bug?

**Comment by xiangxiren** [comment]
Isn’t the table name always hard-coded? Only Schema configurable.

**Comment by yang-xiaodong** [comment]
@xiangxiren  User can override the GetTableName method to custom table name
```
public virtual string GetReceivedTableName()
```

**Comment by zhuang1125** [comment]
ok，this is a bug，fixed。
