### ISSUE TITLE
Getting error "Unknown topic or partition" after cap kafka upgrading to 3.1.0

### ISSUE THREAD

**Issue by cocosip** [dotnetcore/CAP#635]
Environment
- dotnet : 3.1 +
- cap version: v 3.1.0
- kafka server version: 2.3

> Since cap upgrade to v.3.1.0 ,the app will get a error "Unknown topic or partition" . See https://github.com/confluentinc/confluent-kafka-dotnet/issues/1366  .  CAP shoud adjust some code ?

**Comment by yang-xiaodong** [comment]
Looks like we need re-enable with `AllowAutoCreateTopics` in next version, but as the issue describes, this may not completely solve the error, and it need further investigation

**Comment by yang-xiaodong** [comment]
Fixed in `3.1.1-preview-115802637`
