### ISSUE TITLE
Actofac使用CAP时报错

### ISSUE THREAD

**Issue by GeorGeWzw** [dotnetcore/CAP#636]
![企业微信截图_20200820165419](https://user-images.githubusercontent.com/46982191/90750663-ba69e600-e307-11ea-81e0-06dc7a826c88.png)
![企业微信截图_20200820165434](https://user-images.githubusercontent.com/46982191/90750666-bb9b1300-e307-11ea-838a-ebd73fba48c5.png)
![企业微信截图_20200820165443](https://user-images.githubusercontent.com/46982191/90750669-bc33a980-e307-11ea-8cda-830aa3bcea42.png)
![企业微信截图_20200820165453](https://user-images.githubusercontent.com/46982191/90750672-bccc4000-e307-11ea-9753-dee833ddeafe.png)
![企业微信截图_20200820170817](https://user-images.githubusercontent.com/46982191/90750675-bd64d680-e307-11ea-8327-c3fcf235e5eb.png)

**Comment by yang-xiaodong** [comment]
请不要使用截图，请提供环境信息，请尽量使用英文。

closed by https://zhuanlan.zhihu.com/p/25795393
