### ISSUE TITLE
When I use cap under Autofac: An exception was thrown while activating λ:Microsoft.Extensions.Hosting.IHostedService[] -> DotNetCore.CAP.Internal.Bootstrapper -> λ:DotNetCore.CAP.Internal.IProcessingServer[] -> DotNetCore.CAP.Internal.ConsumerRegister

### ISSUE THREAD

**Issue by GeorGeWzw** [dotnetcore/CAP#637]
When I use cap under Autofac:
An exception was thrown while activating λ:Microsoft.Extensions.Hosting.IHostedService[] -> DotNetCore.CAP.Internal.Bootstrapper -> λ:DotNetCore.CAP.Internal.IProcessingServer[] -> DotNetCore.CAP.Internal.ConsumerRegister

Here is the configuration code：
services.AddCap(x =>
{
x.UseEntityFramework<KyriosDbContext>();
x.UseRabbitMQ(x =>
{
x.HostName = "10.1.40.199";
x.UserName = "mokai";
x.Password = "mokai";
});
});

**Comment by GeorGeWzw** [comment]
The problem has been solved because my own rabbitmq version is too high

**Comment by penjay** [comment]
Hi，Where is the version requirement?
