### ISSUE TITLE
 I'd like to ask if there is excessive concurrency testing?

### ISSUE THREAD

**Issue by luesheng** [dotnetcore/CAP#642]
services.TryAddSingleton<ICapPublisher, CapPublisher>();

 why not ? 

services.TryAddScoped<ICapPublisher, CapPublisher>();

At the moment when the transaction is released, the business logic code of other methods will not be abnormal?

**Comment by yang-xiaodong** [comment]
docs at here: https://www.cnblogs.com/savorboard/p/cap-2-6.html#icappublisher-%E9%BB%98%E8%AE%A4%E4%B8%BA%E5%8D%95%E4%BE%8B
