### ISSUE TITLE
3.0.4 升级到 3.1.0 报错

### ISSUE THREAD

**Issue by jiffei** [dotnetcore/CAP#643]
1、_capBus.Publish(...) 报：MySqlParameter objects may be stored

2、
```
services.AddCap(x =>
{
    .....
    x.ConsumerThreadCount = 20;  // 有此行代码报错：None of the specified endpoints were reachable
    x.UseDashboard();
});
```

.net core 版本：3.1
使用的是 Rabbit Mq 和 Mysql

**Comment by yang-xiaodong** [comment]
You need to confirm whether Pomelo.EntityFrameworkCore.MySql is used, if so, please return to version 3.0.4

**Comment by jiffei** [comment]
谢谢杨大神~
