### ISSUE TITLE
Publishing multiple messages in the same transaction throws an exception

### ISSUE THREAD

**Issue by zivfuture** [dotnetcore/CAP#645]
I use CAP to publish integration event.  but i failed.  Component  are  Mmssql2012 with Dapper & Rabbitmq,
here is the code:
```
public async Task<int> AddProduct(Product entity)
        {
            var Id = 0;
            using (SqlConnection conn = new SqlConnection(option.ConnectionStrings.DefaultConnection))
            {
                using(var transaction = conn.BeginTransaction(publisher, autoCommit:true))
                {
                    var sql = "INSERT INTO Products(Code,Name,Description,xxx) VALUES(@Code,@Name,@Description,); SELECT @@IDENTITY";
                    Id = await conn.ExecuteScalarAsync<int>(sql, entity, transaction);   //use dapper to save the data.
                    //send message
                    entity.IntegrationEvents.ForEach(async e => await publisher.PublishAsync(e.RouteKey, e.Event));
                }
                return Id;    //   Got the new id number and return it  then  i got the error as blow.
            }
        }
```
this is the error stack infomation.  where am i wrong?
```
    DotNetCore.CAP.SqlServer.DbConnectionExtensions.ExecuteNonQuery(System.Data.IDbConnection, string, System.Data.IDbTransaction, object[])
    DotNetCore.CAP.SqlServer.SqlServerDataStorage.StoreMessage(string, DotNetCore.CAP.Messages.Message, object)
    DotNetCore.CAP.Internal.CapPublisher.Publish<T>(string, T, System.Collections.Generic.IDictionary<string, string>)
    DotNetCore.CAP.Internal.CapPublisher.Publish<T>(string, T, string)
    DotNetCore.CAP.Internal.CapPublisher.PublishAsync.AnonymousMethod__0()
    System.Threading.Tasks.Task.InnerInvoke()
    System.Threading.Tasks.Task..cctor.AnonymousMethod__274_0(object)
    System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, object)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, object)
    ...
```

**Comment by zivfuture** [comment]
I  figured out.  can you fix it?
````
public async Task<int> AddProduct(Product entity)
{
    var Id = 0;
    using (SqlConnection conn = new SqlConnection(option.ConnectionStrings.DefaultConnection))
    {
        using(var transaction = conn.BeginTransaction(publisher, autoCommit:true))
        {
            var sql = "INSERT INTO Products(Code,Name,Description,xxx) VALUES(@Code,@Name,@Description,); SELECT @@IDENTITY";
            Id = await conn.ExecuteScalarAsync<int>(sql, entity, transaction);   //use dapper to save the data.


            //here must synchronous !!!...................   async /await  will  failed
            entity.IntegrationEvents.ForEach(async e => await publisher.PublishAsync(e.RouteKey, e.Event));
        }
        return Id;  
    }
}
``

**Comment by yang-xiaodong** [comment]
Would you want to find the problem and fix it? I can't fix this problem quickly because I don't have SQL Server now

**Comment by zivfuture** [comment]
@yang-xiaodong   hm...   I already told you where the bug is.   wait for you to fix it.
```
//here must synchronous !!!...................   async/await  will  fail and throw the exception.
entity.IntegrationEvents.ForEach(e => publisher.Publish(e.RouteKey, e.Event));
```

**Comment by yang-xiaodong** [comment]
@zivfuture Please provide your environment info, Thanks

**Comment by xiangxiren** [comment]
> @yang-xiaodong hm... I already told you where the bug is. wait for you to fix it.
> 
> ```
> //it worked .   here must synchronous !
> entity.IntegrationEvents.ForEach(e => publisher.Publish(e.RouteKey, e.Event));
> 
> //wrong . we will get an error.
> entity.IntegrationEvents.ForEach(async e => await publisher.PublishAsync(e.RouteKey, e.Event));
> ```

Use foreach instead of ForEach.

**Comment by zivfuture** [comment]
@yang-xiaodong 
"Set autoCommit: false and submit manually."
I have done as you said.  got same error.     
Here should be a bug.

@xiangxiren 
"Use foreach instead of ForEach."  it worked.    why?

**Comment by xiangxiren** [comment]
> @yang-xiaodong
> "Set autoCommit: false and submit manually."
> I have done as you said before. got same error.
> Here should be a bug.
> 
> @xiangxiren
> "Use foreach instead of ForEach." it worked. why?

What the ForEach method receives is an Action delegate parameter. Even if you mark it with async and await, the actual operation result will not be what you think.
![image](https://user-images.githubusercontent.com/12774053/92190054-b656d000-ee92-11ea-8a72-ad18a4949538.png)

The output results in the figure are not ordered. And each execution may be randomly sorted.

You can implement an extension method yourself to achieve your purpose.

![image](https://user-images.githubusercontent.com/12774053/92190232-2e24fa80-ee93-11ea-8fc4-55b5c357708d.png)

**Comment by zivfuture** [comment]
@xiangxiren   thanks very much!
