### ISSUE TITLE
Add ZeroMQ support 

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnetcore/CAP#655]
Hello , 

This is a survey item, if you want us to provide official support for ZeroMQ, please vote under this issue.

ZeroMQ: 
https://zeromq.org/

**Comment by yang-xiaodong** [comment]
#652 Is a unmerged community implementation

**Comment by maikebing** [comment]
_CAP如何实现 多消费者 负载均衡， 比如:一万条数据按照处理能力均分给多个消费者，并且每条消息只给一个消费者，绝对不给第二个消费者。_ 

我使用 RabbitMQ 作为消息队列， 可以实现。 但是 使用  ZeroMQ  未能实现，这方面内容能给予指点吗？

**Comment by maikebing** [comment]
[samples.zip](https://github.com/dotnetcore/CAP/files/5178389/samples.zip)

**Comment by maikebing** [comment]
RabbitMQ  是按照这篇文章搭建的   https://www.jianshu.com/p/14ffe0f3db94

**Comment by maikebing** [comment]
背景补充: 之所以使用 ZeroMQ  是因为NetMQ  都是C#写的，没有任何依赖， 比如我的IoTSharp项目在龙芯服务器内， 我不需要安装 其他语言编写的  消息队列服务等， 单实例也能完成工作，数个实例也能通过 CAP进行 协调工作。

**Comment by yang-xiaodong** [comment]
> _CAP如何实现 多消费者 负载均衡， 比如:一万条数据按照处理能力均分给多个消费者，并且每条消息只给一个消费者，绝对不给第二个消费者。_
> 
> 我使用 RabbitMQ 作为消息队列， 可以实现。 但是 使用 ZeroMQ 未能实现，这方面内容能给予指点吗？

This is a feature provided by RabbitMQ. Exchange will route messages to one or more queues that match the conditions and keep the same weight. In fact, when RabbitMQ has a fixed number of consumers, it always routes in order.

**Comment by yang-xiaodong** [comment]
@maikebing  I have no idea about ZeroMQ

**Comment by maikebing** [comment]
So, kafka, too?

**Comment by maikebing** [comment]
我新增了两种zeromq 的实现， 一种是  pub-sub  另一种是  push-pull  ，   后者可以实现我上述的方法。

**Comment by maikebing** [comment]
move to https://github.com/maikebing/CAP.Extensions

**Comment by yang-xiaodong** [comment]
This support has been provided by the community, thanks @maikebing
