### ISSUE TITLE
does cap support delay queue？

### ISSUE THREAD

**Issue by csabc** [dotnetcore/CAP#665]
when i query db,it return nothing,but
i am sure that,it would return data after several hours. when i get nonthing,i need
publish a delay queue excute after 1 hour until it returns sm data. but cap doesn't support delay queue currently. how to do?thanks!

**Comment by yang-xiaodong** [comment]
You can use CAP with Quartz.NET or Hangfire

**Comment by csabc** [comment]
in some cases,cap is running on microserver A,hangfire is running on microserver B,cap has  handed event,but no hangfire server runs on server A. cap
 needs to  a delay queue to process some task... I think there is no need to also run a hangfire service on microserver A.

**Comment by yang-xiaodong** [comment]
It depends on how you use Hangfire, you can also integrate Hangfire and CAP together, and then use CAP to perform the delayed action of the callback
