### ISSUE TITLE
"Unable to cast object" exception was thrown

### ISSUE THREAD

**Issue by dima-zhemkov** [dotnetcore/CAP#666]
Hello,

If there are several assemblies with subscribers "Unable to cast object of type" exception randomly occurs.

In my particular case it was
`Unable to cast object of type
 'BL.Settings.Handlers.EventHandler' to type
 'BL.Communications.Handlers.SettingsChangedEventHandler'.`

The problem is in this line of code of the `SubscribeInvoker` class:
`var executor = _executors.GetOrAdd(methodInfo.MetadataToken, x => ObjectMethodExecutor.Create(methodInfo, context.ConsumerDescriptor.ImplTypeInfo));`

You rely on uniqueness of the `methodInfo.MetadataToken` value but it's not unique in this case.
According to a [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.metadatatoken?view=netcore-3.1), MetadataToken is a value which, in combination with `Module`, uniquely identifies a metadata element.

I came up with the following solution
`var key = $"{methodInfo.Module.Name}_{methodInfo.MetadataToken}";`
`var executor = _executors.GetOrAdd(key, x => ObjectMethodExecutor.Create(methodInfo, context.ConsumerDescriptor.ImplTypeInfo));`

**Comment by yang-xiaodong** [comment]
It looks good, would you like to submit a PR?

**Comment by dima-zhemkov** [comment]
Will do later today
