### ISSUE TITLE
Question:How to manually trigger reconsumption

### ISSUE THREAD

**Issue by ajdwfnhaps** [dotnetcore/CAP#67]
像这种情况，如何可以手动让它立即重新消费？我选了所有，然后点“重新消费”按钮，没反应？

![image](https://user-images.githubusercontent.com/11205717/33478160-513c44d2-d6c3-11e7-8aab-175891870270.png)

**Comment by yuleyule66** [comment]
你这两条消息应该是由于某种原因失败了，重新消费也是将消息状态修改为Scheduled

**Comment by ajdwfnhaps** [comment]
但是这两条消息会一直在“执行中”的列表里，过期时间是：in 7982 years，状态一直是Scheduled，我查了我的错误日志也没有任何错误信息，而且我查了数据库的数据，这两条消息其实是已经消息成功的了，不知道为啥会一直在“执行中”列表里显示？

**Comment by yuleyule66** [comment]
@ajdwfnhaps 更新到 `2.1.2-preview-29226626` 版本，再点重新消费，应该没问题了。

**Comment by ajdwfnhaps** [comment]
Thanks,got it
