### ISSUE TITLE
[Q] Initial synchronisation of data owned by another microservice

### ISSUE THREAD

**Issue by adlanelm** [dotnetcore/CAP#672]
Hi guys,

I am considering using CAP to synchronise data across microservices, before I commit to it I have a question.

Background:
* ServiceA owns data in TableA
* ServiceB needs to maintain its own copy of TableA. 
* ServiceC already has an up-to-date copy of TableA.

Goal:
I need to perform initial synchronisation of ServiceA.TableA -> ServiceB.TableA without bothering ServiceC.

Question:
How would you go about this using CAP?

**Comment by yang-xiaodong** [comment]
Hello,

CAP cannot monitor database tables. You need to use CDC in ServiceA and then send the message to CAP and subscribe in ServiceB.
