### ISSUE TITLE
Execute ReConsume exception from dashboard

### ISSUE THREAD

**Issue by alvin-su** [dotnetcore/CAP#674]
DotNetCore.CAP.DefaultSubscriberExecutor[0]                                                                             An exception occurred while executing the subscription method. Topic:inno.capBus.Adv, Id:1309078057219731456      DotNetCore.CAP.SubscriberNotFoundException: Message can not be found subscriber. name:inno.capBus.Adv, group:cap.queue.capconsumer.v1, content:{"Id":"5f6c75913614c21ae00bc79f","Timestamp":"2020-09-24T18:31:45.2543145+08:00","Content":"{\"Id\":1,\"IsEnable\":0,\"Name\":\"测试\",\"Remark\":null,\"ParentModelId\":null}","CallbackName":null}                      see: https://github.com/dotnetcore/CAP/issues/63                                                                          at DotNetCore.CAP.DefaultSubscriberExecutor.InvokeConsumerMethodAsync(CapReceivedMessage receivedMessage, CancellationToken cancellationToken) in C:\projects\cap\src\DotNetCore.CAP\ISubscribeExecutor.Default.cs:line 177                     at DotNetCore.CAP.DefaultSubscriberExecutor.ExecuteWithoutRetryAsync(CapReceivedMessage message, CancellationToken cancellationToken) in C:\projects\cap\src\DotNetCore.CAP\ISubscribeExecutor.Default.cs:line 93

**Comment by yang-xiaodong** [comment]
refer to  #63

**Comment by alvin-su** [comment]
我发送端是一个实例，订阅端是一个实例，都指向了一个数据库，是这个问题造成的吗？

**Comment by yang-xiaodong** [comment]
Yes, Refer [FAQ](https://cap.dotnetcore.xyz/user-guide/zh/samples/faq/) to learn "How to use the same database for different applications?"

**Comment by alvin-su** [comment]
放在同一个实例中还是不行，报相同的错误，发送端代码：
 public async Task<IActionResult> Privacy()
        {
            await _capBus.PublishAsync("inno.capBus.Adv", new W_Model()
            {
                Id = 1,
                Name = "测试"
            });
            return View();
        }
订阅端代码：
 [NonAction]
        [CapSubscribe("inno.capBus.Adv")]
        public void ReceiveMessage(W_Model p)
        {
            Console.WriteLine($"message is:{p.Name}");
        }

**Comment by alvin-su** [comment]
解决了，我是用的EF 连接的数据库，两个实例连接同一个数据库，只要把订阅端程序，指定一下DefaultGroup 为发送端的名称就可以了。
