### ISSUE TITLE
Like to add Subscription at runtime

### ISSUE THREAD

**Issue by hilkenan** [dotnetcore/CAP#676]
I would like to add Subscriptions for routing keys at runtime, and add an EventHandler, insted of using CanSubscribe Attribute. Is there a way to do that?

**Comment by wificlub-code** [comment]
public class CustomConsumerServiceSelector : ConsumerServiceSelector
    {
        public CustomConsumerServiceSelector(IServiceProvider serviceProvider) : base(serviceProvider)
        { 
        }

        protected override IEnumerable<ConsumerExecutorDescriptor> FindConsumersFromInterfaceTypes(IServiceProvider provider)
        {
            var executorDescriptorList = new List<ConsumerExecutorDescriptor>();
            executorDescriptorList.AddRange(base.FindConsumersFromInterfaceTypes(provider));

            var eventHandlerTypeInfo = typeof(IIntegrationEventHandler).GetTypeInfo();

            foreach (var service in ServiceCollectionExtensions.ServiceCollection.Where(o => o.ImplementationType != null && o.ServiceType != null))
            {

                //TODO:
            }
            return executorDescriptorList;
        }
    }

    public interface IIntegrationEventHandler<in TIntegrationEvent> : IIntegrationEventHandler
       where TIntegrationEvent : class
    {
        Task HandleAsync(TIntegrationEvent @event);
    }

    public interface IIntegrationEventHandler
    {
    }

**Comment by yang-xiaodong** [comment]
Hi @hilkenan 
Subscription at runtime is not currently supported
