### ISSUE TITLE
Support for GCP PubSub

### ISSUE THREAD

**Issue by Henery309** [dotnetcore/CAP#680]
Hi would love to see integration with Google cloud PubSub. 
https://cloud.google.com/pubsub this is a highly available and auto scalable alternative to azure service bus and kafka, aws.

C# SDK:
https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.PubSub.V1/index.html

Pubsub Documentation
https://cloud.google.com/pubsub/docs

**Comment by yang-xiaodong** [comment]
Hello, 

The work is in progress at `support/gcp-pubsub` branch, any PR is welcome

Thanks

**Comment by yang-xiaodong** [comment]
Hello,

Since GCP does not support multiple topics attached to one subscription,  so we cannot support it at now.

close the issue.
