### ISSUE TITLE
Possible to keep messages ordered when received

### ISSUE THREAD

**Issue by cog-ab** [dotnetcore/CAP#683]
Is there any in built mechanism, setting or way to make sure messages are received in order, FIFO.
If messages are published very close to each other it seems they can be received in incorrect order.
Thanks

**Comment by yang-xiaodong** [comment]
This is true for any message-based architecture. It depends on how you consume your messages. If there is a single consumer instance, the messages are sequential. If there are multiple consumers, the order cannot be strictly guaranteed.
