### ISSUE TITLE
与 SqlSugar5 事务关联后，使用异步方法（PublishAsync）发送消息，数据库连接不能被复用，超出最大连接数

### ISSUE THREAD

**Issue by luesheng** [dotnetcore/CAP#684]
1、使用同步方法 Publish，正常被释放
2、使用异步方法 PublishAsync，数据库连接不能被复用，超出最大连接数

 psql: FATAL: sorry, too many clients already

------------------------------
代码如下：
-----------------------------
            var sugarOptions = new ConnectionConfig
            {
                ConnectionString = _configuration.GetConnectionString("PostgreSQL"),
                DbType = SqlSugar.DbType.PostgreSQL,
                IsAutoCloseConnection = true,
                InitKeyType = InitKeyType.Attribute
            };

            var _sugarClient = new SqlSugarClient(sugarOptions)
            {
                Aop =
                {
                     OnLogExecuting = (sql, pars) =>
                     {
                         Console.WriteLine(sql + "\r\n" + JsonConvert.SerializeObject(pars.ToDictionary(it => it.ParameterName, it => it.Value)));
                         Console.WriteLine();
                     }
                }
            };

            if (_sugarClient.Ado.Transaction == null)
            {
                _sugarClient.Ado.Transaction = _sugarClient.Ado.Connection.BeginTransaction(_capPublisher, false).DbTransaction as IDbTransaction;
            }

            var tjs_blc_purse = new SimpleClient<tjs_blc_purse>(_sugarClient);

            var purseTo = tjs_blc_purse.GetById(0);

            purseTo.balance += 10;

            var purseResult = tjs_blc_purse.Update(e => new tjs_blc_purse
            {
                balance = purseTo.balance

            }, e => e.purse_id == purseTo.purse_id);

            await _capPublisher.PublishAsync("kafka.sub", 10, "kafka.callback");
            
             //_capPublisher.Publish("kafka.sub", 10, "kafka.callback"); 
            
            _capPublisher.Transaction?.Value?.Commit();

            _capPublisher.Transaction?.Value?.Dispose();

            _sugarClient.Ado.Transaction = null;

            _sugarClient.Ado.Dispose();

**Comment by yang-xiaodong** [comment]
Hello, thanks for your feedback, can this issue be reproduced without using SqlSugar?

**Comment by yang-xiaodong** [comment]
No response, close
