### ISSUE TITLE
按照帮助文档描述的过程尝试过程遇到问题

### ISSUE THREAD

**Issue by anlem12** [dotnetcore/CAP#69]
1、直接用 _capBus.Publish("sample.rabbitmq.mysql", DateTime.Now);发布了一条消息（数据库published表也只有一条），在订阅的地方设置了断点等了几十秒后才接受到消息，并且一直在接受这条消息（数据库received表中417条记录）。

此除延迟是什么原因？是不是只要一接受到消息就要删除这条消息就行了？
2、用了事务又发布了一条消息（published表等了几十秒状态是成功），但是（received表增加了8条记录）
为什么事务和问题1在received表增加的记录数量不一样？

3、published表中状态都成功了，received表中状态为：Enqueued。系统没有中断

**Comment by yuleyule66** [comment]
请提供以下信息：
1、提供环境说明
2、如果可能，提供一份Demo

**Comment by anlem12** [comment]
rabbitmq版本
https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.7.0/rabbitmq-server-3.7.0.exe

操作系统win10 x64

Demo

http://a.bartender.xin/a.zip

------------------------------------------------------
rabbitmq默认安装好后没有做任何配置

麻烦帮忙看下是什么情况，谢谢

**Comment by yuleyule66** [comment]
你好，这几天一直在忙。

我刚才运行了你的示例程序，一切正常。
你可以升级一下CAP最新的预览版本，然后清空published,received 表，再试一下呢。

关闭此issue，如果还有其他问题，可以 reopen。
