### ISSUE TITLE
Memory is not reclaimed of InMemoryMessageQueue 

### ISSUE THREAD

**Issue by MrChuJiu** [dotnetcore/CAP#691]
## 写了一个DEMO 测试CAP的队列 消费能不能满足现有项目需求
项目最高内存占用近6个G，生产和消费完成后 稳定在3个G的样子 观察了半小时 也没有下降的趋势
### 代码情况：
![image](https://user-images.githubusercontent.com/31230864/96962426-5519b780-1539-11eb-80d7-1f7ef181d477.png)
![image](https://user-images.githubusercontent.com/31230864/96962392-4206e780-1539-11eb-82bb-e554cbe11b30.png)
### 运行情况：
![61BMB%VQ%~VUVA}_MK)@Z26](https://user-images.githubusercontent.com/31230864/96962471-71b5ef80-1539-11eb-9725-9e7f1a4f5ba6.png)

**Comment by yang-xiaodong** [comment]
Hello, Thanks for your feedback.

Would you like to investigate this issue?

**Comment by MrChuJiu** [comment]
@yang-xiaodong  我不知道如何解决这个问题，和他发生的原因，所以希望作者查一下问题

**Comment by yang-xiaodong** [comment]
@xiangxiren Do you have any time to investigate for this?

**Comment by MrChuJiu** [comment]
我也在查看源码 想要找到问题

**Comment by yang-xiaodong** [comment]
Fixed in version `3.1.2-preview-120490779`
