### ISSUE TITLE
你好，CAP能否跨语言使用？

### ISSUE THREAD

**Issue by VictorShadow89** [dotnetcore/CAP#70]
你好，CAP能否跨语言使用？
因为我看到是用rabbitmq和kafka的，java应该能互动吧

**Comment by yuleyule66** [comment]
你好，基于消息队列的通讯是可以跨语言的，但是CAP目前并没有Java版本，如果Java要使用的话，需要自己写一套。
我们之前公司项目就是 .NET 和 Java 跨语言使用的， .NET 使用的CAP，但是Java那边的CAP并未开源。

关闭issue，如果还有其他问题，可以reopen

**Comment by VictorShadow89** [comment]
嗯，那这个实用性就不是特别大了，因为现在项目基本都是跨语言平台的。如果用存粹的消息通信，是无所谓的，但是因为CAP封装了一层，导致消息解析的时候可能难度会加大，这就要对CAP内部消息处理机制要很清楚了

**Comment by yuleyule66** [comment]
为什么解析消息会复杂呢？ 就是包装了一层而已。
