### ISSUE TITLE
Error occurred when I run the sample code 

### ISSUE THREAD

**Issue by lqkankan** [dotnetcore/CAP#701]
It's my first time to learn CAP, I download the main repository and try to run the sample project [**Sample.RabbitMQ.SqlServer**],
everything looks fine when I debug the sample but it cannot subscribe any messages.

Setup.cs is look like this
![image](https://user-images.githubusercontent.com/13253727/97525402-b03c2600-19e1-11eb-9e17-a79cb976089f.png)

SqlServer  database is in my local.

I send request to the test controller http://localhost:5000/without/transaction, rabbitMQ just receive the message, but sample code just encounter an error which looks like this.

![image](https://user-images.githubusercontent.com/13253727/97525569-1032cc80-19e2-11eb-94bc-c2859b41d6e1.png)

an object null exception throw out, so I add a '?' to try to make it pass, but another exception occurred, from the failure page of dashboard I can see the error
![image](https://user-images.githubusercontent.com/13253727/97525812-a8c94c80-19e2-11eb-810b-7b339081b902.png)

seems the type of message was wrong, below is what I find while debugging.
![image](https://user-images.githubusercontent.com/13253727/97525900-e4641680-19e2-11eb-930c-80ebbd494bb2.png)

The Value looks like a type of Base64, I'm sure that it's a json in [cap].[Published] table of sqlserver database, but it's Base64 in  [Received] table

Please help.

**Comment by yang-xiaodong** [comment]
Hello , This is a sample code error, we have fixed it.

The issue error indicates that the data type published needs to be converted for consumer data type

**Comment by xiangxiren** [comment]
Maybe you should update your code, you can check this issue #695

**Comment by lqkankan** [comment]
> Hello , This is a sample code error, we have fixed it.
> 
> The issue error indicates that the data type published needs to be converted for consumer data type

it fixed,  the sample code run successfully. thanks. I will continue my learning 👍
