### ISSUE TITLE
cap  PublishAsync method  report an error

### ISSUE THREAD

**Issue by alvin-su** [dotnetcore/CAP#702]
"ExceptionMessage": {"Source": null,
"Message": "Attempt by method 'DotNetCore.CAP.RabbitMQ.RabbitMQPublishMessageSender.PublishAsync(System.String, System.String)' to access method 'RabbitMQ.Client.Framing.BasicProperties..ctor()' failed.",
"InnerMessage": "Attempt by method 'DotNetCore.CAP.RabbitMQ.RabbitMQPublishMessageSender.PublishAsync(System.String, System.String)' to access method 'RabbitMQ.Client.Framing.BasicProperties..ctor()' failed."

**Comment by yang-xiaodong** [comment]
closed by https://zhuanlan.zhihu.com/p/25795393
