### ISSUE TITLE
Is there a way to add extra fields in the message header without intruding the business code?

### ISSUE THREAD

**Issue by Mingwei-zhang** [dotnetcore/CAP#703]
你好：
在微服务业务调用链过程中会在Header中添加很多信息，这部分如果做统一的处理的话就不会侵入到实际的业务开发过程中，让业务开发人员即取即用即可，所以需要一个Aop埋点处理，所以想能否为消息接收或发送时的CapHeader埋个统一处理的Aop点。
例如Action的执行前后，或是一个可供重写的处理函数

**Comment by yang-xiaodong** [comment]
Hello, you can use the Diagnostics feature supported by CAP to implement AOP functionality.

You can refer to this library to learn how to use:

https://github.com/SkyAPM/SkyAPM-dotnet/blob/master/src/SkyApm.Diagnostics.CAP

**Comment by Mingwei-zhang** [comment]
Diagnostics 不适合用在这种场景，它是异步的，这种业务场景需要Aop同步处理的手段。

**Comment by yang-xiaodong** [comment]
Hello, Diagnostics is not asynchronous. Similar to what you said, the tracking system still needs to carry context in the message, and in this way the information is injected into the header
