### ISSUE TITLE
Message can not be found subscriber. Sequentially error occurs.

### ISSUE THREAD

**Issue by truongmin** [dotnetcore/CAP#705]
Hi, I've got this error while setting CAP to my projects:

- Two projects use different databases
- They use same queue called 'dcs.sales.v1'. The default group is set : 'config.DefaultGroup = "dcs.sales";
- Project A publish message to 'update.user.point'
- Project A does not subscribe to any topic
- Project B subscribe to 'update.user.info'
- Project B subscribe to 'sync.parameter'

When Project A publish message to 'update.user.point', I got error from its console.

When calling cap.publish function, I sequentially get Message can not be found subscriber error. The first message is sent and subscribed, everything was find. But the second fails. And keep going like that.

1. Success -> 2. Failed -> 3. Success -> 4. Failed

I put my CapSubcribe in the controller.

I've completely check and unbind all topics before starting up the project after reading https://github.com/dotnetcore/CAP/issues/63 issue, but still doesn't work.

May be I'm similar to these issues:

https://github.com/dotnetcore/CAP/issues/258
https://github.com/dotnetcore/CAP/issues/100

But I'm not sure what's the meaning of your comment

```
Group相同只会收到一次。
Group不同是广播。

记住这个就行了。
其他的你需要检查一下RabbitMQ的绑定设置。
```

![image](https://user-images.githubusercontent.com/8234787/97795687-9e55bf80-1c3b-11eb-9564-e67adf6c1917.png)

Please help. thank you.

**Comment by yang-xiaodong** [comment]
Hello ,

Because you use the same queue (GroupName) in different applications, CAP will think that you have deployed multiple instances of a single application, and the message will be load balanced among multiple instances, so you will get Message can not be found subscriber errors

**Comment by truongmin** [comment]
Thank you @yang-xiaodong. Changed the group name so each service has one separated queue and everything works fine.
