### ISSUE TITLE
question about channel write failed in Dispatcher

### ISSUE THREAD

**Issue by gongjunbing** [dotnetcore/CAP#706]
## Environment
- dotnet : 3.1.5
- cap version: v 3.0.4
- mq: rabbit mq
- db: MySQL 5.7
### In Dispatcher
```C#
// Dispatcher
public void EnqueueToExecute(MediumMessage message, ConsumerExecutorDescriptor descriptor)
{
    _receivedChannel.Writer.TryWrite((message, descriptor));
}
```
### In ConsumerRegister
```C#
// ConsumerRegister
var mediumMessage = _storage.StoreReceivedMessage(name, group, message);
mediumMessage.Origin = message;

client.Commit(sender);

TracingAfter(tracingTimestamp, transportMessage, _serverAddress);

_dispatcher.EnqueueToExecute(mediumMessage, executor);
```

### In NeedRetry 
```C#
private async Task<IEnumerable<MediumMessage>> GetMessagesOfNeedRetryAsync(string tableName)
{
    var fourMinAgo = DateTime.Now.AddMinutes(-4).ToString("O");
    var sql =
        $"SELECT `Id`,`Content`,`Retries`,`Added` FROM `{tableName}` WHERE `Retries`<{_capOptions.Value.FailedRetryCount} " +
        $"AND `Version`='{_capOptions.Value.Version}' AND `Added`<'{fourMinAgo}' AND (`StatusName` = '{StatusName.Failed}' OR `StatusName` = '{StatusName.Scheduled}') LIMIT 200;";

    await using var connection = new MySqlConnection(_options.Value.ConnectionString);
    var result = connection.ExecuteReader(sql, reader =>
    {
        var messages = new List<MediumMessage>();
        while (reader.Read())
        {
            messages.Add(new MediumMessage
            {
                DbId = reader.GetInt64(0).ToString(),
                Origin = _serializer.Deserialize(reader.GetString(1)),
                Retries = reader.GetInt32(2),
                Added = reader.GetDateTime(3)
            });
        }

        return messages;
    });

    return result;
}
```
## Issue
if message written store successfully and mq also commit,but write _receivedChannel.Writer.TryWrite() execute failed return false,and then the cosumer will not execute。The event execution status in received table remains Scheduled and Retry is 0 for execution until it is discovered by the NeedRetry Task  4 minutes later.The event is then executed successfully.

如果消息往 *received* 表中写入成功 并且 mq 也提交了 ack 回执，但是 *_receivedchannel.write.trywrite()* 执行失败返回 false ，那么消费者将不会执行。此时，*received* 表中的 *StatusName* 字段值还是 *Scheduled*、Retry 字段值为0，直到 4 分钟后被 NeedRetry 任务发现为止。然后成功执行该事件。

## Example
received table content field value like this 
```JSON
{"Headers":{"cap-callback-name":null,"cap-msg-id":"1322833613058371584","cap-msg-name":"login.success","cap-msg-type":"LoginEvents","cap-senttime":"2020/11/1 17:31:25 +08:00","cap-corr-id":"1322833613058371584","cap-corr-seq":"0","cap-msg-group":"cap.queue.login.v2"},"Value":{"id":"2071171122"}}
```

**Comment by yang-xiaodong** [comment]
Hello,

Yes, But it will fail only when the parent Channel write is completed. This situation does not exist in CAP

```C#
public override bool TryWrite(T item)
{
    UnboundedChannel<T> parent = _parent;
    while (true)
    {
        AsyncOperation<T> blockedReader = null;
        AsyncOperation<bool> waitingReadersTail = null;
        lock (parent.SyncObj)
        {
            // If writing has already been marked as done, fail the write.
            parent.AssertInvariants();
            if (parent._doneWriting != null)
            {
                return false;
            }

            // If there aren't any blocked readers, just add the data to the queue,
            // and let any waiting readers know that they should try to read it.
            // We can only complete such waiters here under the lock if they run
            // continuations asynchronously (otherwise the synchronous continuations
            // could be invoked under the lock).  If we don't complete them here, we
            // need to do so outside of the lock.
            if (parent._blockedReaders.IsEmpty)
            {
                parent._items.Enqueue(item);
                waitingReadersTail = parent._waitingReadersTail;
                if (waitingReadersTail == null)
                {
                    return true;
                }
                parent._waitingReadersTail = null;
            }
            else
            {
                // There were blocked readers.  Grab one, and then complete it outside of the lock.
                blockedReader = parent._blockedReaders.DequeueHead();
            }
        }

        if (blockedReader != null)
        {
            // Complete the reader.  It's possible the reader was canceled, in which
            // case we loop around to try everything again.
            if (blockedReader.TrySetResult(item))
            {
                return true;
            }
        }
        else
        {
            // Wake up all of the waiters.  Since we've released the lock, it's possible
            // we could cause some spurious wake-ups here, if we tell a waiter there's
            // something available but all data has already been removed.  It's a benign
            // race condition, though, as consumers already need to account for such things.
            ChannelUtilities.WakeUpWaiters(ref waitingReadersTail, result: true);
            return true;
        }
    }
}
```

**Comment by gongjunbing** [comment]
Thank you for your reply.But I think It could happen and that's probably a bug
This happens when ConsumerThreadCount>1 is configured.I think this is due to multithreaded concurrent operation writes,So I try to set SingleWriter to true,and then this situation was resolved.
```C#
_receivedChannel = Channel.CreateUnbounded<(MediumMessage, ConsumerExecutorDescriptor)>(new UnboundedChannelOptions { SingleWriter = true });
```
Originally, my production environment was single-machine deployment, which was always stable. Considering that the business might be under pressure, I tried *ConsumerThreadCount* and distributed multi-open, which not only led to the above situation, but also triggered repeated consumption due to the concurrent execution of the 4-minute retry mechanism. I have been looking for this problem for a long time.And the 4-minute retry mechanism also has a repeat consumption problem (in the case of distributed over-open)

原来我生产环境都是单机部署，它一直很稳定，考虑业务可能出现压力就试了下*ConsumerThreadCount*和分布式多开，不仅导致了上面说的这个情况，并且因为有4分钟重试机制并发执行触发了重复消费，找了好久这个问题。而且4分钟重试机制也存在重复消费问题（在分布式多开情况下）

**Comment by yang-xiaodong** [comment]
How do you determine that ` _receivedchannel.write.trywrite() `  execute failed, I just want to know how you are sure this is the caused reason

**Comment by yang-xiaodong** [comment]
Hello @xiangxiren ,

I think we need to verify whether `UnboundedChannel` exhibits unexpected behavior when `ConsumerThreadCount` is greater than 1 without using ` SingleWriter = true`.

https://github.com/dotnetcore/CAP/blob/a1fc03320016b293baa7db52c277931027280af6/src/DotNetCore.CAP/Processor/IDispatcher.Default.cs#L38

**Comment by gongjunbing** [comment]
unfortunately,I'm not sure that's was caused it.because I've set `SingleWriter = true` but `StatusName=Scheduled`  task also exist in table.
I'm a little dizzy, And I can't understand how this could have happened without any exception

**Comment by gongjunbing** [comment]
Although the frequency is very low

**Comment by tohkinzhu** [comment]
![image](https://user-images.githubusercontent.com/26783496/99057066-348fcb00-25d6-11eb-886e-b67fd8c463e8.png)

not sure if my issue related to this one. I got more than 10k+ Scheduled rows in the database.
My ConsumerThreadCount value is 20 and the application is live in the k8s. (5 pods)
I'd like to know why these data have not been re-executed and consumed?
最近发现双11依赖表里一堆收到的状态是Scheduled的数据没被消费，版本都是3.04，想问下原因是什么？

cap version: v 3.0.4
mq: rabbit mq
db: MySQL 8.0

**Comment by yang-xiaodong** [comment]
Hello @tohkinzhu  @gongjunbing 
It seems that this problem is caused by slow consumption, can you be sure of this?

**Comment by yang-xiaodong** [comment]
No  response, close

**Comment by lhysrc** [comment]
自从改用 Channel 后就一直有这个问题，请问你们有解决方法吗？@tohkinzhu @gongjunbing
我自己的内部队列又改回 ConcurrentQueue 了，不知道是容量不够造成等待还是如何。

**Comment by yang-xiaodong** [comment]
We improved this behavior in version 7.0, now default not pre-fetch to memory
