### ISSUE TITLE
Kafka+MySql performance investigation

### ISSUE THREAD

**Issue by lkd3063601** [dotnetcore/CAP#707]
使用mysql+kafka模式。用JMeter模拟1W数据2秒启动100个线程，循环100次，JMeter界面8s左右请求完毕，然后查看消费端，消费的很慢1s就三四十条左右，应该是发送端发送的慢，和这个测试基本一样  #416

**Comment by lkd3063601** [comment]
![QQ截图20201103163624](https://user-images.githubusercontent.com/15059204/97963810-ae63cf80-1df2-11eb-98b5-e716cafc616b.png)
![Uploading QQ截图20201103164127.png…]()

**Comment by lkd3063601** [comment]
![QQ截图20201103163624](https://user-images.githubusercontent.com/15059204/97964205-5b3e4c80-1df3-11eb-9601-b3d0dc8e2c11.png)
![QQ截图20201103164127](https://user-images.githubusercontent.com/15059204/97964238-672a0e80-1df3-11eb-8b30-c8670e2d2643.png)

**Comment by yang-xiaodong** [comment]
Hello @lkd3063601,

Would you like to investigate this issue?

**Comment by lkd3063601** [comment]
> 你好@ lkd3063601，
> 
> 您想调查这个问题吗？

这种情况，是什么原因呢

**Comment by yang-xiaodong** [comment]
@lkd3063601  因为这是开源项目每个人都可以参与其中，就是你愿不愿意参与调查这个问题。如果不愿意我们可能会设为积压或延期调查因为其优先级较低。

**Comment by yang-xiaodong** [comment]
Hello @lkd3063601 

Please report your configuration information, such as Kafka version, MySql version, CAP version, and the configuration information of your machine running the benchmark, thanks

**Comment by lkd3063601** [comment]
> Hello @lkd3063601
> 
> Please report your configuration information, such as Kafka version, MySql version, CAP version, and the configuration information of your machine running the benchmark, thanks

kafka 版本：1.0.1
MySQL版本：5.7
CAP版本：3.1.1
电脑cpu：i7-8700,内存：16G

**Comment by yang-xiaodong** [comment]
Hello , In order to ensure the reliability of the message, CAP use the [`Basic Producer`](https://github.com/confluentinc/confluent-kafka-dotnet#basic-producer-examples)  provided byconfluent-kafka, in which the message sent will be confirmed and waited.

I did a benchmark test without additional code, and it only has 125 records/s on my machine.

**Comment by yang-xiaodong** [comment]
We recommend that in scenarios that do not require transactions and have a lot of concurrency, use batch sending directly instead of going through CAP
