### ISSUE TITLE
CapOptions configure in different portal

### ISSUE THREAD

**Issue by cocosip** [dotnetcore/CAP#708]
I‘m try to use `cap` in `ABP` framework , when  create `cap` as a module, the code looks bad .  The `CapOptions` can only be in one place for initialization.  [CapOptions code](https://github.com/dotnetcore/CAP/blob/f6588441fc148fb15d62f8ff5a58207d2398ac12/src/DotNetCore.CAP/CAP.ServiceCollectionExtensions.cs#L66)

When try to configure options in different module, it not work well.

```c#
services.Configure<CapOptions>(options=>{
    options.UseKafka(...);
    options.UseMySql(...)
});

services.AddCap(options=>{    });
```
I think the configuration and the dependency injection should be separated , otherwise extensions would be very difficult.
Thank you !

**Comment by yang-xiaodong** [comment]
Hello, CAP is an independent library. You can get information about the integration of CAP and Abp here.

https://github.com/EasyAbp/Abp.EventBus.CAP

**Comment by cocosip** [comment]
> Hello, CAP is an independent library. You can get information about the integration of CAP and Abp here.
> 
> https://github.com/EasyAbp/Abp.EventBus.CAP

I've seen this project ,  it does not meet our scenario .  and this project writing rules that do not meet the ABP

**Comment by yang-xiaodong** [comment]
Hello, I'm sorry I can't help you, I think this problem need youself to solve it

**Comment by yang-xiaodong** [comment]
releated issue #616
