### ISSUE TITLE
CAP3.1.1 Table Received inserted two records while consumming each message

### ISSUE THREAD

**Issue by ChiliJJ** [dotnetcore/CAP#710]
大神你好~
最近搭建消息平台用到了CAP，但是2.6.0升级到3.1.1之后，观察到cap.Rececived表中，每消费一个Message，就多出一个状态为Scheduled的记录，并且发现这两条记录的Group不一致，Scheduled的记录一直不变，ExpiresAt为空，求指点！

状态为Succeeded的记录数据如下：
{
"Headers":{
"cap-callback-name":null,
"cap-msg-id":"1323550406461415424",
"cap-corr-id":"1323550406461415424",
"cap-corr-seq":"0",
"cap-msg-name":"cap.msg.queue",
"cap-msg-type":"String",
"cap-senttime":"2020/11/3 16:59:41 +08:00",
"cap-msg-group":"cap.queue.messageplatform.v1"
},
"Value":"{\"MessageType\":\"GP\",\"ProgramName\":\"ServiceWarning\",\"ToUser\":\"Wuyq\",\"GMsgContent\":\"你好！\"}"
}
状态为Scheduled的记录数据是Succeeded记录中的Value，如下：
"Value":"{\"MessageType\":\"GP\",\"ProgramName\":\"ServiceWarning\",\"ToUser\":\"Wuyq\",\"GMsgContent\":\"你好！\"}"
}

**Comment by yang-xiaodong** [comment]
see the breaking change in version 3.0 
https://github.com/dotnetcore/CAP/releases/tag/v3.0.0

**Comment by ChiliJJ** [comment]
> see the breaking change in version 3.0
> https://github.com/dotnetcore/CAP/releases/tag/v3.0.0

有注意到消息格式的变化，消费也是成功的，只是每次消费会多出一条Scheduled的记录，意思是publish的参数处理不当导致？

**Comment by yang-xiaodong** [comment]
It looks like there are parts of your system that have not been upgraded.

If you need to open this issue at any time.

**Comment by ChiliJJ** [comment]
> It looks like there are parts of your system that have not been upgraded.
> 
> If you need to open this issue at any time.

Thanks, already OK.  Maybe that's because I  used the same database to test v2.6.0 and v3.1.1.
