### ISSUE TITLE
Question about the Rent/Return logic of "DotNetCore.CAP.RabbitMQ.ConnectionChannelPool".

### ISSUE THREAD

**Issue by redochenzhen** [dotnetcore/CAP#715]
It confuses me when I'm reading the source code of "DotNetCore.CAP.RabbitMQ.ConnectionChannelPool". The Rent/Return logic shows that the quantity of rented-out channels can reach much higher than '_maxSize'(it will create new one when there's no one left in the queque). Is this a bug or by design?

**Comment by yang-xiaodong** [comment]
Hello, 

I did not understand what you mean,  `_count` represents the number of `Model` in the current pool, and will waits when the number in the pool is greater than the threshold (default pool size).

https://github.com/dotnetcore/CAP/blob/5cf83af13e7ba5f5bcafe6f12d358e16cb390575/src/DotNetCore.CAP.RabbitMQ/IConnectionChannelPool.Default.cs#L47-L57

**Comment by redochenzhen** [comment]
Hey! Firstly thanks for your reply!
Let me make myself clear:
Initial state: _count = 0; _maxSize = 15; nothing in _pool
https://github.com/dotnetcore/CAP/blob/5cf83af13e7ba5f5bcafe6f12d358e16cb390575/src/DotNetCore.CAP.RabbitMQ/IConnectionChannelPool.Default.cs#L144-L158
Return method shows that the only chance to increase _count is succeeding to return a channel.
OK, let's consider such a situation:
Before any channel returned back, lots of requests (let's say 20) try to rent one each.
https://github.com/dotnetcore/CAP/blob/5cf83af13e7ba5f5bcafe6f12d358e16cb390575/src/DotNetCore.CAP.RabbitMQ/IConnectionChannelPool.Default.cs#L47-L57
https://github.com/dotnetcore/CAP/blob/5cf83af13e7ba5f5bcafe6f12d358e16cb390575/src/DotNetCore.CAP.RabbitMQ/IConnectionChannelPool.Default.cs#L119-L133
As the Rent method shows, _count will away be 0 (no thread spin waits) and _pool will walys stay empty (try dequeque fails, always create a new channel). Finally, there will be 20 channels in use, breaking the limitation that max size is 15.

**Comment by yang-xiaodong** [comment]
@redochenzhen I understand your question now, but I don't think it needs to be fixed.

I did a benchmark test and it was almost impossible to create a lot of channels

**Comment by redochenzhen** [comment]
Can the count of pool (_count) reach a relatively considerable size (like 5 or more) in your benchmark?
In my test, there is aways only one thread sending message (without considering MessageNeedToRetryProcessor). A single channel in pool is rented and returned serially, which results that the _count is always 1.

**Comment by yang-xiaodong** [comment]
@redochenzhen 

Yes, same here. In order to ensure the order of sending, we queued the messages. I think this is a place for optimization.

When users want to send faster and are not sensitive to the order of messages, we can provide options like `ConsumerThreadCount` to provide higher performance.

Let me know what you think?

**Comment by redochenzhen** [comment]
@yang-xiaodong
If you allow parallel sending, the phenomenon we talked at the top of this issue will occur.

Yes, message order and parallel seem not compatible. Maybe we can provide some mechanism to ensure the sequence of a pack of messages, and packs go parallelly not affecting each other.
But then, this proposal seems no so necessary.

**Comment by redochenzhen** [comment]
I think this issue can be closed now.
