### ISSUE TITLE
is there anyway to ack rabbitmq message by myself

### ISSUE THREAD

**Issue by szg** [dotnetcore/CAP#716]
if i want to reject a message,and i want to consumer it later,i need to throw an exception,like that 

`  [CapSubscribe("queueName")]

  public async Task SubscribeAsync(string message)

  {

        throw new Exception("i don't want to ack message");

 }`

**Comment by redochenzhen** [comment]
I don't think you can do this in a CAP 'Subscriber'. Maybe 'RabbitMQ.Client' can help to work around.

'

**Comment by yang-xiaodong** [comment]
If you do not ack the message, you will not be able to receive subsequent messages unless you use the dead letter queue.

CAP is designed to be flexible, it will automatically retry and eventually consistency.
