### ISSUE TITLE
Cap Discovery Service Check Failed

### ISSUE THREAD

**Issue by zqlovejyc** [dotnetcore/CAP#719]
At present, the problem I have encountered is that the current service uses the HTTPS protocol, but after configuring capdiscoveryoptions, the service health check fails. The cap uses HTTP for health check. Is there any good solution

**Comment by yang-xiaodong** [comment]
You can customize the  `INodeDiscoveryProvider` to do this

**Comment by zqlovejyc** [comment]
thank you
