### ISSUE TITLE
请问这个可以做单机版的事件总线和事务处理吗？

### ISSUE THREAD

**Issue by aqa510415008** [dotnetcore/CAP#72]
因为公司项目的前期不大，所以不需要进行分布式部署，但是我希望使用里面的事件总线，如果后期需要扩展就可以直接增加分布式基础设施就可以了，不知道这个行不行

**Comment by yuleyule66** [comment]
你好，可以的。

**Comment by aqa510415008** [comment]
@yuleyule66 现在好像没有实现吧？

**Comment by yuleyule66** [comment]
我想我应该对这个项目更加了解。 建议你先看一下wiki。

关闭此issue，如果还有其他问题，可以reopn.
