### ISSUE TITLE
关于多租户的问题

### ISSUE THREAD

**Issue by ztzsws1** [dotnetcore/CAP#723]
你好 杨总，

我们的多租户方案是共享应用、通过数据库隔离的方案。 在运行时， 通过TenanId 组装不同的连接字符串， 然后Build 不同的DBContext。 
现在的cap并不适用于现在的方案， 没有办法为每个租户创建独立的消息队列 以及 独立的存储。
如果只有一个消息队列， 并且用公共的数据库， 来receive和 publish表（不与租户数据库放到一起）的话， 那么业务逻辑和消息的事务怎么解决？ 租户过多， 消息过多， 会不会导致消息阻塞？

谢谢

**Comment by yang-xiaodong** [comment]
Currently does not support separate database 

Close this issue, regarding multi-tenant support, we will have a unified discussion into #699
