### ISSUE TITLE
Can we create the required topics for kafka?

### ISSUE THREAD

**Issue by rogeryamato** [dotnetcore/CAP#732]
this is a question that our ops team can't enable auto create topic for Kafka...the pic is as below:
@![Screenshot_20201204_114304](https://user-images.githubusercontent.com/6090972/101119397-33c2e580-3626-11eb-9508-9914a06b7e91.jpg)
so can we do that in cap?

**Comment by yang-xiaodong** [comment]
Hello,

CAP creates an independent topic for each publish name. If you create it manually, there will be a lot of work.

I don't have a good solution, I think it may be necessary to adjust the code to send all messages to one topic.

**Comment by rogeryamato** [comment]
ok, thanks.. close issue
