### ISSUE TITLE
Question about version options

### ISSUE THREAD

**Issue by 786744873** [dotnetcore/CAP#733]
我想请教一下groupId的v1是怎么来的，因为我在程序中明明设置的是不带v1的，结果出现了v1
![image](https://user-images.githubusercontent.com/24601648/101128341-624abb80-363a-11eb-9d10-488ff1245f66.png)
![image](https://user-images.githubusercontent.com/24601648/101128354-6bd42380-363a-11eb-8dba-bf7c27ef5065.png)

**Comment by yang-xiaodong** [comment]
See release blog: https://www.cnblogs.com/savorboard/p/cap-2-4.html
