### ISSUE TITLE
Environment: Mysql Kafka release data no problem, but as long as the monitor will lead to Kafka collapse

### ISSUE THREAD

**Issue by aqa510415008** [dotnetcore/CAP#74]
Environment: Mysql Kafka release data no problem, but as long as the monitor will lead to Kafka collapse

**Comment by aqa510415008** [comment]
After an error Kafka can not start again, you need to delete the instance of Zookeeper in order to start Kafka,

**Comment by yuleyule66** [comment]
Please provide some environmental information of CAP.  I need to know what's your real problems ?
The information includes the version of CAP and OS version and the sample code or some exception log.

If your kafka can not start , I think this is not CAP's issue

**Comment by aqa510415008** [comment]
Kafka的版本：1.0.0
CAP的版本：2.1.2
1、在没有使用CAP，按照官方的操作是可以实现功能的
2、在使用CAP的发布功能，通过官方的客户端接受是可以的
3、当使用CAP的监听功能时，就马上崩溃
CAP错误：
![image](https://user-images.githubusercontent.com/28291464/34334210-7b527f24-e97f-11e7-8cd1-a60057c68aa0.png)
Kafka日志：
[server.log](https://github.com/dotnetcore/CAP/files/1585436/server.log)
[state-change.log](https://github.com/dotnetcore/CAP/files/1585437/state-change.log)

**Comment by aqa510415008** [comment]
因为 JDK是32 位的，所以导致Kafka一直在报错。现在问题解决了
