### ISSUE TITLE
.Net 5 Support

### ISSUE THREAD

**Issue by newketom** [dotnetcore/CAP#745]
Current version is not support .net 5, there is any support plan？

**Comment by leftjoinandinnerjoin** [comment]
**i have the same question.** @yang-xiaodong

**Comment by xiangxiren** [comment]
The code has been merged, but it is not yet packaged. #727

**Comment by yang-xiaodong** [comment]
@newketom 

I want to know what problems you have encountered in .NET 5?

I created an ASP.NET Core 5.0 project and everything works fine

**Comment by yang-xiaodong** [comment]
@newketom @leftjoinandinnerjoin  Any response?

**Comment by newketom** [comment]
we used Azure service bus does not work based .Net 5

![image](https://user-images.githubusercontent.com/56467036/102763368-83d6d180-43b4-11eb-924f-b9ea0b3c9d53.png)
![image](https://user-images.githubusercontent.com/56467036/102763726-0b244500-43b5-11eb-94ac-bf0bf9be5bf3.png)

**Comment by yang-xiaodong** [comment]
It seems to have nothing to do with .NET 5, Can you create a new issue?

**Comment by newketom** [comment]
but the same demo code dose not work based .Net 5, so i think some cap package components not support .net 5

**Comment by yang-xiaodong** [comment]
It seems that the error is caused by not found the subscribers, let's discuss in the new thread
