### ISSUE TITLE
Azure service bus throw exception "Operation is not valid" used .net 5

### ISSUE THREAD

**Issue by newketom** [dotnetcore/CAP#746]
DotNetCore.CAP.Internal.ConsumerRegister[0]
      Operation is not valid due to the current state of the object.
      System.InvalidOperationException: Operation is not valid due to the current state of the object.
         at Microsoft.Azure.ServiceBus.Amqp.AmqpSubscriptionClient.OnGetRulesAsync(Int32 top, Int32 skip)
         at Microsoft.Azure.ServiceBus.SubscriptionClient.GetRulesAsync()
         at DotNetCore.CAP.AzureServiceBus.AzureServiceBusConsumerClient.Subscribe(IEnumerable`1 topics)
         at DotNetCore.CAP.Internal.ConsumerRegister.<>c__DisplayClass17_0.<Start>b__0()

![image](https://user-images.githubusercontent.com/56467036/102766172-aff45180-43b8-11eb-95ea-c49b95950d2c.png)

**Comment by newketom** [comment]
#745

**Comment by yang-xiaodong** [comment]
Hello @newketom ,

Because my Azure Service Bus subscription has expired, this issue cannot be verified now.

Would you like to check this issue?

**Comment by newketom** [comment]
I applied for an azure connection string，and it has been sent to your email “yangxiaodong1214@126.com”

**Comment by yang-xiaodong** [comment]
Hello, thanks for you test connection string.

The Azure Service Bus Client version used by CAP 3.1.x version seems to have a bug. After my test, please use the latest NuGet package in your project to solve this error.

Add 5.1.0 version package to your csproj file: 
```
<PackageReference Include="Microsoft.Azure.ServiceBus" Version="5.1.0" />
```

We have updated the version of ServiceBus in the master branch, but it has not been released yet

**Comment by newketom** [comment]
ok tkx!
