### ISSUE TITLE
Issue about lost subscribe in rabbitmq

### ISSUE THREAD

**Issue by rogeryamato** [dotnetcore/CAP#748]
For our requirement we want set 1 subscribers in one microservice and other microservice will publish data to this microservice.
So we implementation code like this:

For subscribers in project A:
  ```
[CapSubscribe("EventDelivery")]
 public void SendEvents(EventDeliveryModel eventDeliveryModel)
 {
} 
```
And publish in proiect B:
```
 public CpvEventGeneratorService(
     
            ICapPublisher capPublisher)
        {
            this.capPublisher = capPublisher;
        }   

public void PostProductExpUpdate(object payload)
        { 
var post = new EventDeliveryModel
            {
                Topic = "CPV",
                Name = "CPVItemExceptions",
                Content = new List<object>(),
                Destinations = new List<object>(),
                Importance = "Medium",
                Title = "CPVItemExceptions",
                Description = "All item level high risks from CPV",
                Payload = payload.ToJsonString(),
                Publisher = "GURUCPV"
            };

            capPublisher.Publish("EventDelivery", post);
}
```
And we can see 2 data has been send, but in Received table, there is no data in it, and we try to monitor rbbitmq it seems no data is in query.

And we retry publish by using dashboard, some times 1 message will received.

Please help us for this issue.

We using same CAP DB and Rabbitmq for different microservice. So is this issue because of this? And how to implementation out requirement?

Thanks.

**Comment by yang-xiaodong** [comment]
Hello, if your different microservices want to use the same database, you need to use different tables to store messages.

Our FAQ lists the solution to this issue, you can find it here

https://cap.dotnetcore.xyz/user-guide/en/samples/faq/

see : How to use the same database for different applications?

**Comment by rogeryamato** [comment]
@yang-xiaodong  Thanks for your help..
