### ISSUE TITLE
CAP is a great tool to work with RabbitMQ, but it looks only supporting aspnetcore. How do I use it in a Console App?

### ISSUE THREAD

**Issue by trumhemcut** [dotnetcore/CAP#75]

**Comment by yuleyule66** [comment]
In the .net core console application, you can use it like : 

![qq 20180102094407](https://user-images.githubusercontent.com/8205994/34472655-95058a60-efa1-11e7-8b08-c9e88b6f3f5e.png)

The class you subscribe to needs to inherit `ICapSubscribe` interface, and add it to IOC container.

**Comment by trumhemcut** [comment]
Great, thanks for this! It works for now.

**Comment by qgxcry** [comment]
![image](https://user-images.githubusercontent.com/13807716/56078695-b5e11380-5e1d-11e9-9ae5-9d749a5a96c3.png)

How to Pass stoppingToken param？ @yang-xiaodong
