### ISSUE TITLE
.net framework4.7.2 是否支持 cap

### ISSUE THREAD

**Issue by cnkker** [dotnetcore/CAP#750]
.net framework 4.7.2 提供了依赖项注入支持
是否可以使用CAP？

**Comment by yang-xiaodong** [comment]
Not support .NET Framework, but you can try it

**Comment by cnkker** [comment]
> Not support .NET Framework, but you can try it

我试了，可以发送消息，是无法注册接收

**Comment by cnkker** [comment]
> Not support .NET Framework, but you can try it

示例（Sample）
https://github.com/cnkker/CAP/tree/master/samples/Sample.NetFrameWrok

源代码（Source code） IConsumerServiceSelector.Default.cs 106行，修改为（Modify）  Assembly entryAssembly = (new StackTrace().GetFrames() ?? Array.Empty<StackFrame>()).Last().GetMethod().Module.Assembly;

可以在.Net framework4.7.2上完美运行
