### ISSUE TITLE
How to manually try again

### ISSUE THREAD

**Issue by lantongxue** [dotnetcore/CAP#753]
How to manually try again.

I don't want to try again when there is an exception. I want to try a message manually

Is it to rebuild a queue or other ways

**Comment by yang-xiaodong** [comment]
You can use the dashboard 

https://cap.dotnetcore.xyz/user-guide/en/monitoring/dashboard/

**Comment by lantongxue** [comment]
> You can use the dashboard
> 
> https://cap.dotnetcore.xyz/user-guide/en/monitoring/dashboard/

I know the dashboard, but is there any API that can be use?

**Comment by yang-xiaodong** [comment]
Why do you want to use API?  Retry is automatic

**Comment by lantongxue** [comment]
> Why do you want to use API? Retry is automatic

Because the queue results need to be notified to the specified service

And I know the execution result of the queue (true/false)

So. if the queue results is "false", i want to got the "false" and notify instead of throwing an exception

And try again the queue.

**Comment by yang-xiaodong** [comment]
I don't konw you what you want to do, but I think it's a design mistake. Notification of the result of consumer execution should be part of the business logic and should not be handled as an exception or depends on retry

**Comment by lantongxue** [comment]
> I don't konw you what you want to do, but I think it's a design mistake. Notification of the result of consumer execution should be part of the business logic and should not be handled as an exception or depends on retry

Yes, that's what it means

**Comment by yang-xiaodong** [comment]
Sure, closed!
