### ISSUE TITLE
Unable to cast object of type 'ExcuteTaskHandler' to type 'BatchCouponCreateEventHandler'.

### ISSUE THREAD

**Issue by liunianmoshi** [dotnetcore/CAP#757]
```
DotNetCore.CAP.Internal.SubscriberExecutionFailedException: Unable to cast object of type 'MarketingManagement.EventHandler.ExcuteTaskHandler' to type 'MarketingManagement.EventHandler.BatchCouponCreateEventHandler'.
```

An exception occurred while executing the subscription method. Topic:EventTransport.Marketing.ExcuteTaskEto, Id:1346449171092946944
.net core 生产环境突然出现大量这种错误，导致消息消费失败，数据库是一个微服务模块对应一个cap的数据库，目前看publish和received都有成功的记录，但是实际上都没有处理成功，消息队列用的是rabbitmq, 使用的是cap2.3版本，
麻烦作者看看帮忙看看怎么回事？我们碰到这种情况需要怎么排查问题？

**Comment by yang-xiaodong** [comment]
As the title describes, this is a type cast exception
