### ISSUE TITLE
Kafka good way to ignore self produced messages

### ISSUE THREAD

**Issue by kvandake** [dotnetcore/CAP#763]
I have an application whose multiple instances can run.

Each instance has producer and consumer. Some instance request data by sending message using producer API and other's are supposed to receive the message through consumer API.

now because there is only one topic on which data is being exchange and each instance is producer and consumer for the same topic, the same instance gets the self created message. this is kind of expected behavior.

What is the efficient way to ignore the self created messages on the given application instance?

**Comment by xiangxiren** [comment]
What's your purpose in doing this？

**Comment by kvandake** [comment]
I have two servers where I can change some property in orders. I created the topic called **orders**. And I have logic for messages through [JsonSubTypes](https://github.com/manuc66/JsonSubTypes). For example, First server creates an message with content:
```cs

// consumer for first server
public class FirstServer_OrderConsumer : ICapSubscribe
{
    [CapSubscribe("orders", Group = "FirstServer")]
    public async Task Handle(OrderCmdMessage message)
    {
    }
}

// consumer for second server
public class SecondServer_OrderConsumer : ICapSubscribe
{
    [CapSubscribe("orders", Group = "SecondServer")]
    public async Task Handle(OrderCmdMessage message)
    {
    }
}

// message for topic "orders"
public class OrderCmdMessage
{
  // data for the message
  public OrderCmdMessageData Data {get;set;}
}

// abstract data for the message
public abstract class OrderCmdMessageData 
{
}

// dynamic data for the message
[JsonSubtypes.KnownSubType(typeof(OrderCmdMessageData<APayload>), "A")]
[JsonSubtypes.KnownSubType(typeof(OrderCmdMessageData<BPayload>), "B")]
public class OrderCmdMessageData<TPayload> : OrderCmdMessageData 
{
   // separate key for JsonSubTypes
   public string Event {get;set;}

   // payload for specific message
   public TPayload Payload {get;set;}
}
```

Second server receives this message, and first server receives too... But I want to ignore this message for first server, because it is message`s owner.

**Comment by xiangxiren** [comment]
need help @yang-xiaodong

**Comment by yang-xiaodong** [comment]
> Second server receives this message, and first server receives too.

This is by design, The message is sent and received in isolation, and the consumer does not know where the message was sent from self service.

If your business needs it, I suggest you add the  producer metadata in the message header when sending and exclude such messages when consuming

**Comment by kvandake** [comment]
Thank you! I used a header of the message for identify message. If a message will be from a producer the server skip the message.
