### ISSUE TITLE
CAP性能问题咨询

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/CAP#766]
目前我有个需求就是想用CAP来实现双写(MSSQL,ES)操作
制造产线环境,每天请求量写入大概是120万条记录左右,因为是自动化产线作业,每个时段请求量是很平均,大概每秒要处理10-15条记录,如果采用CAP(MQ+MSSQL2016)用来处理,每条请求通过CAP分发分别写入MSSQL和ES,不知道CAP能不能支撑,因为我没有看到相关CAP性能测试文章,想咨询下作者这边面问题

**Comment by bao2314483** [comment]
补充下,因为我看到CAP大概逻辑是接到消息->消息记录数据库->插入MQ队列->消费消息->插入消费记录数据库并且更新对应消息记录处理状态,涉及操作比较多,所以不知道CAP处理峰值在多少

**Comment by yang-xiaodong** [comment]
性能这个问题受多方因素影响，方案选型建议还是根据自己实际情况进行实测，别人的结果和结论并不一定是准的，所以不要图省事自己动手吧。

关闭这个issue.
