### ISSUE TITLE
Are there more ways to subscribe?

### ISSUE THREAD

**Issue by EzrealJ** [dotnetcore/CAP#767]
Hello, Mr. Yang

I found your project from the NCC organization, thank you for your contribution to the open source ecosystem。
Before starting, I briefly reviewed the documentation.
Briefly describe my usage scenario.I want to use it as a library for message publishing and subscription. The main reason I chose it is to support multiple queues and storage. This feature allows me to switch queues and storage without changing too much code in the future.The subscription methods I see in the document now are all implemented using Attribute, but I want to subscribe to a lot of messages and have no rules. I need to read the configuration file to delegate the subscription. Is there any other way to delegate the subscription? For example, a configuration method similar to Fluent Api.Or should I implement IConsumerServiceSelector by myself? But it is in the Internal folder.

杨老板早上好
我从NCC找到CAP项目，感谢你对开源生态做出的贡献。
我简单的看过文档。
大概说一下我的应用场景。我想用它作为消息发布订阅的库,我选择它的主要原因是支持多种队列和存储,这种特性可以让我以后从容的切换队列和存储而不用更改太多的代码。现在我在文档中看到的订阅方式，都是使用Attribute来实现，但我要订阅的消息比较多且没什么规律，需要从配置文件读取来委派订阅，请问是否有其它方式可以委派订阅？比如类似FluentApi的配置方式?或者说我应该自己实现IConsumerServiceSelector？但它在Internal文件夹下
@yang-xiaodong

**Comment by yang-xiaodong** [comment]
Yes, you can override `FindConsumersFromInterfaceTypes` as you needed

https://github.com/dotnetcore/CAP/blob/83d623ca88eb8a8797f86aa83309ce523975ef7a/src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs#L80

**Comment by EzrealJ** [comment]
Thank you for your prompt reply
