### ISSUE TITLE
控制台咋调用PublishAsync

### ISSUE THREAD

**Issue by 7685780** [dotnetcore/CAP#769]
控制台咋调用PublishAsync?

**Comment by yang-xiaodong** [comment]
closed by https://zhuanlan.zhihu.com/p/25795393

**Comment by zhangzw218** [comment]
捕获一个被怼的帖子，https://gitee.com/zzwtx/abp-event-rabbit-mqdemo.git 这里面有三个项目，其中CapConsole的项目，发布和订阅实例都有，你可以看看。@7685780
