### ISSUE TITLE
Cap Dashboard Js syntax issue

### ISSUE THREAD

**Issue by ajdwfnhaps** [dotnetcore/CAP#77]
Hi:
Dashboard Js （src/DotNetCore.CAP/Dashboard/Content/js/cap.js），第374行多了个逗号，导致较低版本的浏览器Js报错，部分Dashboard 功能无法使用

![image](https://user-images.githubusercontent.com/11205717/35145079-798e02dc-fd41-11e7-91df-8eb5a540b9fc.png)

去掉这个逗号可兼容低版本的浏览器也能正常使用

**Comment by yuleyule66** [comment]
Yes, Thanks for your feekback. 
I will fix it later.

**Comment by yuleyule66** [comment]
fixed in version `preview-33191223`
