### ISSUE TITLE
多租户问题

### ISSUE THREAD

**Issue by d4ilys** [dotnetcore/CAP#770]
您好有两个问题
1.ORM使用的是使用的是Freesql  IdleBus来实现多租户，通过每次请求的HTTP header token来获取数据库连接信息，来获取IFreesql操作对象，而cap项目初始化的时候就要指定数据库，请问这种如何解决。
2.一个服务cap如何做事务，例如我创建一个订单的操作，需要往报表库中同步，那么这样我必须创建一个报表服务，我想在订单服务中保证订单和报表库的事务如何实现。

**Comment by yang-xiaodong** [comment]
Not support mutil-tenancy

Closed, Ask questions in #699 of mutil-tenancy so that we can collect questions in same thread

**Comment by BraveJJJ** [comment]
> 您好有两个问题 1.ORM使用的是使用的是Freesql IdleBus来实现多租户，通过每次请求的HTTP header token来获取数据库连接信息，来获取IFreesql操作对象，而cap项目初始化的时候就要指定数据库，请问这种如何解决。 2.一个服务cap如何做事务，例如我创建一个订单的操作，需要往报表库中同步，那么这样我必须创建一个报表服务，我想在订单服务中保证订单和报表库的事务如何实现。

I wonder if this can be done? Open two transactions at the same time, and if one of them has a problem, both are rolled back
