### ISSUE TITLE
Failed turning to scheduled

### ISSUE THREAD

**Issue by pekugur34** [dotnetcore/CAP#773]
Hi, we have a micro-service system with RabbitMq - Cap. We have approx. 400.000 events waiting to be processed in queue.
When we manual re-execute, some of the failed events get scheduled again. And we cannot process the whole queue.

Our config below:

`
            services.AddCap(x =>
            {
                x.FailedRetryInterval = 6000;
                var retryCount = 5;
                if (!string.IsNullOrEmpty(configuration[nameof(IInfrastructureSettings.EventBusRetryCount)]))
                {
                    retryCount = int.Parse(configuration[nameof(IInfrastructureSettings.EventBusRetryCount)]);
                }
                x.UseEntityFramework<TDbContext>(c =>
                {
                    if (options != null)
                    {
                        if (options.UseCustomCapSchema)
                        {
                            c.Schema = options.CapSchema;
                        }
                    }
                });
                //x.UseSqlServer(configuration[nameof(IInfrastructureSettings.ConnectionString)]);
                x.UseRabbitMQ((rabbitOptions) =>
                {
                    if (!string.IsNullOrEmpty(configuration[nameof(IInfrastructureSettings.EventBusConnection)]))
                    {
                        rabbitOptions.HostName = configuration[nameof(IInfrastructureSettings.EventBusConnection)];
                    }
                    if (!string.IsNullOrEmpty(configuration[nameof(IInfrastructureSettings.EventBusUserName)]))
                    {
                        rabbitOptions.UserName = configuration[nameof(IInfrastructureSettings.EventBusUserName)];
                    }
                    if (!string.IsNullOrEmpty(configuration[nameof(IInfrastructureSettings.EventBusPassword)]))
                    {
                        rabbitOptions.Password = configuration[nameof(IInfrastructureSettings.EventBusPassword)];
                    }
                });
                if (!string.IsNullOrEmpty(configuration[nameof(IInfrastructureSettings.SubscriptionClientName)]))
                {
                    x.DefaultGroup = configuration[nameof(IInfrastructureSettings.SubscriptionClientName)];
                }
                x.UseDashboard();
                x.FailedRetryCount = retryCount;
                x.FailedThresholdCallback = (type, name, content) =>
                {
                    Console.WriteLine($@"A message of type {type} failed after executing {x.FailedRetryCount} several times, requiring manual troubleshooting. Message name: {name}, message body: {content}");
                };
                // Register to Consul
                // x.UseDiscovery(d =>
                // {
                //     d.DiscoveryServerHostName = "localhost";
                //     d.DiscoveryServerPort = 8500;
                //     d.CurrentNodeHostName = "localhost";
                //     d.CurrentNodePort = 5800;
                //     d.NodeId = 1;
                //     d.NodeName = "CAP No.1 Node";
                // });
            })
            .AddMessagePacker<RodosMessagePacker>();
`

Any help is appreciated.
Thanks.

**Comment by yang-xiaodong** [comment]
Hello,

Based on the information you provided, I cannot judge the problem you are facing without the log.

It is recommended that you check if RabbitMQ is healthy and the consumer code is correct.

**Comment by pekugur34** [comment]
Hi,

Ok we found out we had an endless loop problem in one of our events - event handlers. We solved the problem.

Thanks again.
