### ISSUE TITLE
This SqlTransaction has completed; it is no longer usable

### ISSUE THREAD

**Issue by winlj** [dotnetcore/CAP#774]
This SqlTransaction has completed; it is no longer usable
.net5.0
cap3.1.2
使用了sqlsugar最新版本

**Comment by yang-xiaodong** [comment]
Hello, this repo currently does not provide support service for third-party ORM components other than EF

**Comment by winlj** [comment]
> Hello, this repo currently does not provide support service for third-party ORM components other than EF

以前旧版本的都支持呀，不会出现冲突？这个什么时候可以支持呢？请教了。
