### ISSUE TITLE
After receiving the message processing, but the processing fails, how to try again

### ISSUE THREAD

**Issue by dengyangxi** [dotnetcore/CAP#777]
After receiving the message processing, but the processing fails, how to try again ？

1.   ------------------------------------------------------------------------------
 Custom business logic failed
 Operation on the database, but an error occurred  
 I want to process this message again after an interval of 30 seconds
 Try to process 5 times
2.   -------------------------------------------------------------------------------
Or whether there is a response mechanism to call a cap method after processing 
(for example: CAP.Success () or CAP.Fail () ）.
If the cap does not receive the success() callback, it will receive the message again after 30 seconds . 

`

      [CapSubscribe("cap.queue.net.core.order.web.v1")]
        public void HandleOrder(string data, [FromCap]CapHeader header)
        { 
          // Custom business logic failed
          //   Operation on the database, but an error occurred  
          //   I want to process this message again after an interval of 30 seconds
          //  Try to process 5 times
          
           try
            {
                int i=0,j =  0;
                var c = i / j;
            }
            catch (Exception ex)
            {
                // Ideal state : 
                // fail ： Try again in 30 seconds，  Try 5 times 
                CAP.Fail();
            }
          
             Console.WriteLine(data); 
        } 
`

**Comment by yang-xiaodong** [comment]
Please refer to the documentation

https://cap.dotnetcore.xyz/user-guide/zh/cap/messaging/#_7

**Comment by dengyangxi** [comment]
> Please refer to the documentation
> 
> https://cap.dotnetcore.xyz/user-guide/zh/cap/messaging/#_7

Consumption retrying

When the consumer receives the message, it will execute the consumer method, and when there is an exception in executing the consumer method, it will try again. This retrying strategy is the same as the send retrying above.

How can consumers inform cap that the business processing fails and needs to be tried again?  
such as：
[CapSubscribe("cap.queue.net.core.order.web.v1")]
    public object HandleOrder(string data, [FromCap]CapHeader header)
    { 
                **return new {   IsSuccess = true };       // Successfully processed
                return new {   IsSuccess = false };     // Processing failed**
 }

**Comment by yang-xiaodong** [comment]
> How can consumers inform cap that the business processing fails and needs to be tried again?
Just throw an exception

**Comment by dengyangxi** [comment]
**The problem has been solved. Thank you.**
   
   
[CapSubscribe("cap.queue.net.core.order.web.v1")]
public void HandleOrder(string data, [FromCap]CapHeader header)
{
          // retry 
           **throw new Exception("Processing failed 。message . . . . ");** 
}
