### ISSUE TITLE
控制台项目，请问一下为什么方法被订阅成功但是却不进断点，在MVC项目里订阅就能进入断点

### ISSUE THREAD

**Issue by xiazhaoxiao** [dotnetcore/CAP#778]
再别的项目上发布了一个topic，再新建一个控制台项目订阅，订阅成功了，但是不进入断点。
![微信图片_20210204145002](https://user-images.githubusercontent.com/40377520/106855857-97d25a80-66f8-11eb-9265-476c528155aa.png)

**Comment by xiazhaoxiao** [comment]
在打印那里拼接几个字符就可以了Console.WriteLine(“123”+name);

**Comment by zhangzw218** [comment]
求教，楼主还在么，能否帮忙提供一个控制台的Demo，我不知道应该怎么绑定Cap。
`

        static void Main(string[] args)
        {
            var services = new ServiceCollection();
            services.AddTransient<HelloService>();
            services.AddTransient<ICapSubscribe, SubscriberService>();
            services.AddCap(capOptions =>
            {
                capOptions.UseRabbitMQ(mqOptions =>
                {
                    mqOptions.HostName = "192.168.60.8";
                    mqOptions.Port = 5672;
                    mqOptions.UserName = "admin";
                    mqOptions.Password = "zzw1236547890";
                    mqOptions.ExchangeName = "Cap_Exchange_Demo";
                });
                capOptions.UseMySql("server=192.168.60.8;port=3306;user=root;password=123456;database=Demo3;persist security info=True;Allow User Variables=True;Charset=utf8;");
            });
            var hello = services.BuildServiceProvider().GetService<HelloService>();
            hello.SayHello();
            Console.ReadLine();
        }
`

在mqOptions里面断点无效，没进来，SubscriberService是我写的一个订阅服务，也没有效果。
检查RabbitMQ，没有交换机和队列。
有人可以指点一下么，非常感谢。
我写了个Demo：https://gitee.com/zzwtx/abp-event-rabbit-mqdemo.git 其中有个CapEventRabbitMQDemo项目，有人帮忙看看么。

**Comment by xiazhaoxiao** [comment]
，注入用services.AddSingleton<SubscriberService>();试试

**Comment by xiazhaoxiao** [comment]
services.AddSingleton(SubscriberService);

**Comment by zhangzw218** [comment]
@xiazhaoxiao 不行，我网络上找到了一个范例，控制台里面，也要实例化一个HostBuilder，才能正常监听Cap，算是解决了我的问题
