### ISSUE TITLE
这个CAP是支持单体系统的CAP总线还是分布式的系统的事务也可自动提交？

### ISSUE THREAD

**Issue by mockte** [dotnetcore/CAP#781]
抱歉，英文欠佳。

我看过这份CAP的使用说明，好像是集成在一个项目中可以这么使用。但如何说，整个平台的API是分成多个解决方案项目去开发的，分布式部署的，比如API（A、B、C）。使用这个CAP，一个闭环流程，A这边发起了，之后又调用了B，最后调用C后整个事务流程结束，如果ABC引用了CAP且用了同一个MQ，能确保数据的最终一致性么？所以我不明白这个CAP如果只是针对单体应用的，意义何在？

**Comment by yang-xiaodong** [comment]
please see: https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/subscribe-events#designing-atomicity-and-resiliency-when-publishing-to-the-event-bus
