### ISSUE TITLE
DashBoard NullReferenceException

### ISSUE THREAD

**Issue by HoboCY** [dotnetcore/CAP#782]
I used EasyAbp.EventBus.CAP 4.1.1 and DotNetCore.CAP 3.1.2
But when I open the '/cap' URL, the program throws an NullReferenceException
![image](https://user-images.githubusercontent.com/31683826/108153993-28586400-7117-11eb-9b0c-eaf034f802f1.png)
![image](https://user-images.githubusercontent.com/31683826/108154030-373f1680-7117-11eb-938d-b655cbc0ef09.png)
![image](https://user-images.githubusercontent.com/31683826/108154082-4b831380-7117-11eb-94d5-0db4a206c4c3.png)

**Comment by yang-xiaodong** [comment]
Hello,

We do not directly provide support for ABP, you can refer to this repo to get help or ask questions

see: https://github.com/EasyAbp/Abp.EventBus.CAP
