### ISSUE TITLE
Multiple databases, single solution

### ISSUE THREAD

**Issue by vmenge** [dotnetcore/CAP#783]
Hello :-)
Been using CAP in a project and really like it so far. I was wondering, is there a recommended way to deal with using CAP with multiple databases _within a single solution_? (single ASP.NET Core solution with multiple projects inside of it, each project with its own database).

**Comment by yang-xiaodong** [comment]
Hello,

Is each project in your solution an Web API project?  You can use different databases in every web api project

**Comment by vmenge** [comment]
Hey Yang!
In my solution there's only one Web API project, all the other ones are class libs with their own database.

**Comment by yang-xiaodong** [comment]
Hi, We currently do not support sharding data to multiple databases, if you use ProxySQL it will be a good solution!

**Comment by vmenge** [comment]
I'll take a look into it, thanks Yang!
Any thoughts on having a separate instances of IServiceCollection and IServiceProvider per classlib? That way I could have multiple instances of CAP running in the same ASP.NET Core project. Would that cause any issues with CAP itself?

**Comment by yang-xiaodong** [comment]
Ah, Sounds good, although it looks a little dirty, but this is the easiest way to solve your problem.

If you are interested, welcome to submit a PR to support multiple databases ( You know I means not separate instances of IServiceCollection), and this seems to also solve applications that use databases to isolate multi-tenant scenarios, but I think it may require a lot of changes to the code.

What do you think?

**Comment by vmenge** [comment]
Hey Yang, I'm definitely up for it as I really enjoy CAP and the design choices you made, but I'm really out of time at the moment. I'll give it a shot eventually if no has tackled it later on 😊
