### ISSUE TITLE
Only MySqlParameter objects may be stored

### ISSUE THREAD

**Issue by liangfangyin** [dotnetcore/CAP#784]
CAP使用Mysql发布信息时候报 “”Only MySqlParameter objects may be stored“”错误，下面是具体的代码，使用_capBus.Publish时候报错，请问如何解决：

var db = new SqlSugarExtension().GetInstance();
            using (var connection = (MySqlConnection)db.Ado.Connection)
            {
                using (var transaction = connection.BeginTransaction(_capBus, autoCommit: false))
                {
                    if (connection.State != ConnectionState.Open)
                    {
                        connection.Open();
                    }

                    db.Ado.Transaction = (IDbTransaction)transaction.DbTransaction;//这行很重要
                    db.Insertable<Test>(new Test()
                    {
                        names = DateTime.Now.Ticks.ToString()
                    }).ExecuteCommand();

                    _capBus.Publish("Sample.RabbitMQ.MySql", new Test()
                    {
                        names = DateTime.Now.Ticks.ToString()
                    });

                    transaction.Commit();
                }
            }

**Comment by yang-xiaodong** [comment]
Hello, there is no support service integrated with third-party components. 

You can refer to the example, If you find a problem with the example, welcome feedback
