### ISSUE TITLE
custom Discovery

### ISSUE THREAD

**Issue by qzwzqty** [dotnetcore/CAP#785]
你好，我想要自定义一个服务发现，但是IDiscoveryProviderFactory是internal的，而且默认的DiscoveryProviderFactory里面是直接new的一个DiscoveryProvider。有其他办法实现吗？谢了。

**Comment by yang-xiaodong** [comment]
Hello,

We have changed the `IDiscoveryProviderFactory` access level of to public

**Comment by qzwzqty** [comment]
@yang-xiaodong  thx
