### ISSUE TITLE
Broker Unreachable problem

### ISSUE THREAD

**Issue by 397419** [dotnetcore/CAP#787]
I checked the source code and found a problem in the file "CAP.RabbitMQOptions.cs":
public string MessageTTL { get; set; } = "864000000";
the correct code must be:
public int MessageTTL { get; set; } = 864000000;
otherwise Consumer can not connect the MQ and throw exception "Broker Unreachable ".

**Comment by yang-xiaodong** [comment]
Hello , 

Thanks for your feedback,  We have changed `MessageTTL` to int type.

**Comment by yang-xiaodong** [comment]
Preview version `5.0.0-preview-131679580 ` released to nuget
