### ISSUE TITLE
How to register to Consul with acl token

### ISSUE THREAD

**Issue by cnkker** [dotnetcore/CAP#789]
My Consul has acl tokens, how do I set them up?

 x.UseDiscovery(_ =>
    {
        _.DiscoveryServerHostName = "localhost";
        _.DiscoveryServerPort = 8500;
        _.CurrentNodeHostName = Configuration.GetValue<string>("ASPNETCORE_HOSTNAME");
        _.CurrentNodePort = Configuration.GetValue<int>("ASPNETCORE_PORT");
        _.NodeId = Configuration.GetValue<string>("NodeId");
        _.NodeName = Configuration.GetValue<string>("NodeName");
    });

**Comment by yang-xiaodong** [comment]
We do not currently provide a configuration item for ACL Token, and according to the documentation it sounds like `CONSUL_HTTP_TOKEN ` environment variable could be used as an alternative.

see : https://www.consul.io/commands/acl/token
