### ISSUE TITLE
Can we use CAP without storing messages to Database?

### ISSUE THREAD

**Issue by trumhemcut** [dotnetcore/CAP#79]
I can see it takes benefits store messages to database, but will it make the process slower since we want to use RabbitMQ to fire&forget in many cases?

**Comment by yuleyule66** [comment]
CAP is designed to maintain data consistency across Microservice or SOA, it depending on the ACID nature of the database to ensure message reliability. If you leave the database, then this solution is only a message queue client encapsulation, it does not make sense, maybe your scene does not require CAP, just send and receive messages only

**Comment by trumhemcut** [comment]
Agree, storage is needed for enterprise level. Thanks
