### ISSUE TITLE
MySql.Data.MySqlClient.MySqlException:“Only MySqlParameter objects may be stored”

### ISSUE THREAD

**Issue by wnttmk** [dotnetcore/CAP#790]
`                // 使用MYSQL 作为消息持久化存储
                options.UseMySql(options =>
                {
                    // 数据库连接
                    options.ConnectionString = "server=127.0.0.1;Allow User Variables=True;port=3306;uid =root;password=123456;persistsecurityinfo=True;database=CapDemoDB";

                    // 当前分布式前点的表头 MainWeb_Table1
                    options.TableNamePrefix = "MainWeb";
                });`

_capBus.Publish("AAA", DateTime.Now);

这里报错。是不是还需要第三方组件支持？？

**Comment by wnttmk** [comment]
我找到问题了。我创建的连接是走的MySql.Data。但是这里面的支持使用的是MySqlConnector。

有什么问题可以解决这个问题吗？？？

**Comment by yang-xiaodong** [comment]
see #126
