### ISSUE TITLE
The setting of ClientProvidedName not working

### ISSUE THREAD

**Issue by pangfd** [dotnetcore/CAP#791]
When I set the ClientProvidedName of rabbitmq to  "Test.Module.CapMqConsumer"，it did not change to what I expected and still used the default name.

My Code：

       services.AddCap(x =>
            {
                x.UseSqlServer(_appConfiguration["Cap:PersistentDb"]);
                x.UseRabbitMQ(option =>
                {
                    option.ConnectionFactoryOptions = (op) => {
                        op.ClientProvidedName = "Test.Module.CapMqConsumer";
                    };
......

**Comment by yang-xiaodong** [comment]
Hello , 
The  `ConnectionFactoryOptions `  option is provided by RabbitMQClient , Would you like to investigate this problem?

**Comment by pangfd** [comment]
Thanks for your reply !
It works well if I use the RabbitMQClient directly.
In addition, the version of RabbitMQClient package is 6.2.1

![image](https://user-images.githubusercontent.com/32212258/109745818-63768f00-7c0f-11eb-9a46-4810c0a53582.png)

![image](https://user-images.githubusercontent.com/32212258/109745583-109cd780-7c0f-11eb-8166-49c93eecee03.png)

**Comment by yang-xiaodong** [comment]
Fixed in version `5.0.0-preview-132124922`
