### ISSUE TITLE
Problems with Dashboard Authorization based on HttpContext

### ISSUE THREAD

**Issue by mviegas** [dotnetcore/CAP#792]
I'm having a problem using Authorization based on HttpContext with the current Dashboard middleware.

I have an OpenId auth by default on my application. Based on that, I created the following custom auth filter to retrieve if the user is authenticated via HttpContext:

```csharp
public class CapDashboardAuthorizationFilter : IDashboardAuthorizationFilter
    {
        public Task<bool> AuthorizeAsync(DashboardContext context)
        {
            var httpContextAccessor = context.RequestServices.GetRequiredService<IHttpContextAccessor>();
            
            return Task.FromResult(httpContextAccessor.HttpContext.User.Identity.IsAuthenticated);
        }
    }
```
However, it is no working. The IsAuthenticated property is always false, even when I have a user that has actually already logged in. 

After further investigation, I found the following code:

https://github.com/dotnetcore/CAP/blob/ea1639f3622baaf6d985af111c4f208fd3839658/src/DotNetCore.CAP.Dashboard/CAP.DashboardMiddleware.cs#L71

```csharp
app.UseCapDashboard();

next(app);
```

Here is my belief: since there is the following `IStartupFilter` referenced above, the `DashboardMiddleware` is called before the other Middlewares inside the application (such as `app.UseAuthorization()` and `app.UseAuthentication()`). 

Thus, the `HttpContext.User.Identity.IsAuthenticated` property will always be false under the custom Authorization filter as shown above.

With that in mind, some questions here:

- Shouldn't this middleware be called manually under the `Configure(IApplicationBuilder app)` so that we could take advantage of other middlewares, such as native Authentication and Authorization, logging, custom telemetry, etc, i.e., manually called without placing an `IStartupFilter` the way that it is today.
- Still, if the use of the `IStartupFilter` should stay like so by design, shouldn't the `app.UseCapDashboard()` be called _after_ the `next(app)`, on the above code?
- Is there any other way to use ASP.NET auth middlewares with the Cap Dashboard?

I'm glad to help to solve this issue via a PR, if we come to a conclusion that it might be needed.

**Comment by yang-xiaodong** [comment]
Hello,

Thanks your feedback, I agree with your belief,  welcome to submit a PR

**Comment by mviegas** [comment]
@yang-xiaodong here is the PR. Feel free to discuss anything regarding it:

 https://github.com/dotnetcore/CAP/pull/793

**Comment by mviegas** [comment]
Closing this issue since the PR was merged.

**Comment by mviegas** [comment]
@yang-xiaodong last question: do you have a plan of a release with this PR via Nuget package?

**Comment by yang-xiaodong** [comment]
Preview version `5.0.0-preview-131679580 ` released to nuget
