### ISSUE TITLE
Confluent.Kafka.ConsumeException: Broker: Unknown topic or partition

### ISSUE THREAD

**Issue by 3ldar** [dotnetcore/CAP#795]
Hi,
I'm trying to use DotnetCore.CAP with kafka. I have the following configuration : 
```csharp
 services.AddCap(build =>
            {
                build.UseDashboard();
                build.ConsumerThreadCount = 10;
                build.UseKafka(r =>
                {
                    r.Servers = config.KafkaUrl;
                    r.MainConfig.Add("allow.auto.create.topics", "true");
                });
                build.UsePostgreSql(r =>
                {
                    r.ConnectionString = config.ConnectionStrings.AppDb;
                    r.Schema = config.CapSchema;
                });

            });
```
And package versions like below :
```xml
<PackageReference Include="Confluent.Kafka" Version="1.6.2" />
<PackageReference Include="DotNetCore.CAP" Version="5.0.0-preview-131679580" />
<PackageReference Include="DotNetCore.CAP.Dashboard" Version="5.0.0-preview-131679580" />
<PackageReference Include="DotNetCore.CAP.Kafka" Version="5.0.0-preview-131679580" />
<PackageReference Include="DotNetCore.CAP.PostgreSql" Version="5.0.0-preview-131679580" />
```

There is a config for `Confluent.Kafka` consumer to allow topic creation when it doesn't exist on consumer registration time. I've tried to configure the CAP in the same way with adding the below line :
```csharp
  r.MainConfig.Add("allow.auto.create.topics", "true");
```
But it seems it has no effect. Are there any workarounds for this or am I doing it wrong?

**Comment by yang-xiaodong** [comment]
This is a known issue,  releated issue #744

please refer to: confluentinc/confluent-kafka-dotnet#1366

**Comment by 3ldar** [comment]
> This is a known issue, releated issue #744
> 
> please refer to: [confluentinc/confluent-kafka-dotnet#1366](https://github.com/confluentinc/confluent-kafka-dotnet/issues/1366)

Ah thank you for the quick reply, I came across that before. But didn't read it to the bottom. Can you please confirm that Cap will keep listening even if this exception occurs?

**Comment by yang-xiaodong** [comment]
> Can you please confirm that Cap will keep listening even if this exception occurs?

I forgot if I have verified this behavior,  it only appears on the first startup, I think you can test it

**Comment by 3ldar** [comment]
Hi again,
I have tested the above scenario and I can confirm that if a subscriber subscribes before the topic creation it becomes unusable. You need to restart the application after the first publication of that event occurred.

**Comment by 3ldar** [comment]
Thanks, It's really appreciated. I would be happy to contribute to this issue if I could but have no time these days.
