### ISSUE TITLE
Multiple message-types for one consumer

### ISSUE THREAD

**Issue by ashish-g-lahane** [dotnetcore/CAP#799]
Currently, even though the producers can produce messages of different types on the same topic/Queue, the consumer can only receive messages of one type. 

I'm interested in ordered delivery of relevent messages using Kafka as the transport. So that the same consumer can consume the relelvent messages. The handlers will be different, no doubt, but the Kafka Consumer should be the same. 

For instance, consider the scenario where I get messages of following types:

TradeCreated 
{
TradeId,
StockSymbol,
Timestamp,
Volume
:
:
}

TradeAmended
{
TradeId,
Volume,
Timestamp,
:
:
}

TradeDeleted
{
TradeId,
Timestamp,
:
}

These messages must be processed in order for the same tradeId, no matter what. And only way to do it using Kafka as the transport. No other transport can give me order guarantee (I mean messaging middlewares like RabbitMQ). 

I can certainly use KafkaFlow as a library which allows this precisely. But it doesn't implement the Outbox feature. Hence this request. 

https://github.com/Farfetch/kafka-flow/wiki 

Is it possible to support the multiple message-types for 1 consumer (with or without Kafka-Flow)?

**Comment by yang-xiaodong** [comment]
Hello, sorry for the delayed reply.

The producer of CAP is not based on type, which means that consumers can consume as long as the type can be successfully converted when subscribing.

For example, if the producer sends a DateTime value, then the consumer can use String or Dynamic or JsonElement to receive. 
Sample code:
```C#

// Producer
await _capBus.PublishAsync("sample.rabbitmq.mysql", DateTime.Now);

// Consumer 1
[CapSubscribe("sample.rabbitmq.mysql")]
public void Subscriber(string p)
{
    Console.WriteLine($@"{DateTime.Now} Subscriber invoked, Info: {p}");
}

or

// Consumer 2
[CapSubscribe("sample.rabbitmq.mysql")]
public void Subscriber(dynamic p)
{
    Console.WriteLine($@"{DateTime.Now} Subscriber invoked, Info: {p}");
}

even or 

// Consumer 3
[CapSubscribe("sample.rabbitmq.mysql")]
public void Subscriber(System.Text.Json.JsonElement p)
{
    Console.WriteLine($@"{DateTime.Now} Subscriber invoked, Info: {p.GetDateTime()}");
}

```

All this can work normally.
