### ISSUE TITLE
Throw exception when PublishAsync

### ISSUE THREAD

**Issue by trumhemcut** [dotnetcore/CAP#80]
My config at Startup.cs
```csharp
            services.AddDbContext<TradeBotDbContext>(ServiceLifetime.Transient);

            services.AddCap(cap =>
            {
                cap.UseEntityFramework<TradeBotDbContext>();
                cap.UseRabbitMQ(Configuration["CAP:RabbitMQ:HostName"]);
            });
            services.AddTransient<ICapPublisher, CapPublisher>();
            services.AddMvc();
            services.AddSingleton<IHostedService, TradeBotService>();
```
Then, Just simply call this in the Service

```await CapPublisher.PublishAsync("test", new { Message = "Hello World" });```

And it throws the exception ```The transaction operation cannot be performed because there are pending requests working on this transaction.``` sometimes.

It throws here:
```csharp
        private void ClosedCap()
        {
            if (IsCapOpenedTrans)
            {
                DbTransaction.Commit(); // THROW WHEN CALLING HERE
                DbTransaction.Dispose();
            }
            if (IsCapOpenedConn)
                DbConnection.Dispose();
        }
```

I'm using SQL Server on Linux as the storage

UPDATED:
Trying with the Postgres and it says:
```A command is already in progress: INSERT INTO Cap.[Published] ([Name],[Content],[Retries],[Added],[ExpiresAt],[StatusName])VALUES(@Name,@Content,@Retries,@Added,@ExpiresAt,@StatusName)```

**Comment by yuleyule66** [comment]
How do you call this `PublishAsync` method?

Are you using a loop call in an action like:
```cs
public async Task<IActionResult> TestSent()
{
    for(int  i=0;i<10000;i++){
        await CapPublisher.PublishAsync("test", new { Message = "Hello World" });
    }
}
```
Or are you calling repeatedly with the http api test tool?

`wrk -c 20 -d 20 http://localhost:5000/api/testsend`
```cs
[Route("~/api/testsend")]
public async Task<IActionResult> TestSent()
{
    await CapPublisher.PublishAsync("test", new { Message = "Hello World" });
}
```

**Comment by trumhemcut** [comment]
I'm using the loop as the first block you described. This is my code
```csharp
while (true)
{
    try
    {
        if (CapPublisher != null)
            await CapPublisher.PublishAsync("test", new { Message = "Hello World" });
        // more code here ...
        await Task.Delay(1300);
    }
    catch (Exception ex)
    {
        // ...
    }
}
```

**Comment by yuleyule66** [comment]
Hi, @trumhemcut  
  I have fixed this problem and release the version of v2.1.3.

**Comment by trumhemcut** [comment]
that looks good, thanks @yuleyule66 !
