### ISSUE TITLE
How to use multi ICapPublisher instance?

### ISSUE THREAD

**Issue by a121984376** [dotnetcore/CAP#800]
for example
i have a rabbitMQ instace.
I want to use ICapPublisher  publish different message with different Exchange.
 the first Exchange to publish orderMessage
the scond Exchange to publish paymentMessage
the third Exchange to publish other message

**Comment by yang-xiaodong** [comment]
Why do you need to use multiple Exchanges, CAP only supports Topic type Exchanges, so there is no point in having multiple Exchanges

**Comment by a121984376** [comment]
> Why do you need to use multiple Exchanges, CAP only supports Topic type Exchanges, so there is no point in having multiple Exchanges

in micro-serice, 
there  many different domain  ,may team, use different  Exchange~
![image](https://user-images.githubusercontent.com/15758574/111585664-9b2e2b00-87fa-11eb-8cec-2ed958d779ab.png)

**Comment by yang-xiaodong** [comment]
I don't think it makes sense to isolate different domains in the same project.

In the event-based architecture, subscribers do not need to care about where the message comes from, and producers do not need to know who will consume the event. This is precisely how loose coupling can be achieved.

The use of Exchange not only needs to be specified when producing messages, but also needs to be specified when subscribing, which completely violates this principle.

see:  https://en.wikipedia.org/wiki/Event-driven_architecture

>   An Event Emitter does not know the consumers of the event, it does not even know if a consumer exists, and in case it exists, it does not know how the event is used or further processed.
