### ISSUE TITLE
question of subscribe group

### ISSUE THREAD

**Issue by a121984376** [dotnetcore/CAP#801]
I  want to use MessageQueue, not Pub/Sub.
for example: one producer, many consumer, 
one message  consume  by one  consumer.
--------------------------------------------------------
our projects run docker under k8s. and use HPA(Horizontal Pod Autoscaler),
that means ,   some   pods  consume  the same one message.
thats horrible.

**Comment by yang-xiaodong** [comment]
I think you may be mistaken, only one of multiple identical instances will be able to receive the message if they are in the same consumer group.

see: https://github.com/dotnetcore/CAP#subscribe-group
