### ISSUE TITLE
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces'

### ISSUE THREAD

**Issue by inginheiiro** [dotnetcore/CAP#803]
Hi,

trying to use your Sql Server Sample with EF 5.0.4.
![image](https://user-images.githubusercontent.com/19993596/111646548-a7fe4f00-87f9-11eb-9901-0fb797b0e17d.png)
could you please update the project to latest EF Core?

**Comment by yang-xiaodong** [comment]
Fixed in  `5.0.0-preview-132888327`, all nuget package  are upgrade to the latest version
