### ISSUE TITLE
When do you can release the .net 5 Versio of CAP? (a message from nuget by Andreas)

### ISSUE THREAD

**Issue by alexinea** [dotnetcore/CAP#804]
*This is a message from nuget by Andreas.*

> User hilki1 <andreas.h\*\*\*\*n@h\*\*\*\*nit.ch> sends the following message to the owners of Package 'DotNetCore.CAP 5.0.0-preview-132888327'.

Hi

When do you can release the .net 5 Versio of CAP? Thx in Advance.

Andreas

**Comment by yang-xiaodong** [comment]
Hello, Version 5.0 was released a few minutes ago
