### ISSUE TITLE
AutoCreateTopic doesn`t use a ssl configuration from KafkaOptions

### ISSUE THREAD

**Issue by kvandake** [dotnetcore/CAP#809]
When I try connect with ssl in kafka, I caught some error. I inspected the source code and a found a bug. AutoCreateTopic class doesn`t use a ssl configuration from KafkaOptions.

Inspect line - https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.Kafka/IProcessingServer.AutoCreateTopic.cs#L34

**Comment by yang-xiaodong** [comment]
Issue was fixed in 5.0.1 and released to NuGet a few minutes ago
