### ISSUE TITLE
Is it possible to allow multiple subscribers ? 

### ISSUE THREAD

**Issue by MahmoudSamir101** [dotnetcore/CAP#813]
Hello there,

I have a web application that resides behind a network load balancer, we have three nodes, **CAP** is used to persist **singalr** messages between these nodes.

What we have is when a message published from a node we need the remaining nodes to consume that message and broadcast again through **signalr** hubs, the current situation is when one of the nodes consumed the message the status of the message in the **Received** table becomes successful, so remaining nodes can't consume that message again.

How can I make that possible, the messages would be marked as successful when all nodes consume them.

I'm using **SqlServer** as storage with **InMemoryQueue**, as there is a limitation to use a real message queue solution in my case. 

Thanks for the good and helpful project.

**Comment by yang-xiaodong** [comment]
Hello,

When node consumers are in different groups, they will receive messages at the same time, refer to https://github.com/dotnetcore/CAP#subscribe-group


>  messages would be marked as successful when all nodes consume them

We are currently unable to do this, there is no communication between nodes

**Comment by MahmoudSamir101** [comment]
Thanks for the clarification
