### ISSUE TITLE
Guidance using CAP with non-CAP RabbitMQ Producers

### ISSUE THREAD

**Issue by flipdoubt** [dotnetcore/CAP#818]
I have reviewed [CAP documentation](https://cap.dotnetcore.xyz/user-guide/en/getting-started/quick-start/) and [samples](https://github.com/dotnetcore/CAP/tree/master/samples) but have not found guidance on using CAP to integrate with other systems that use RabbitMQ but not CAP. Here are my questions:
1. My app needs to exchange messages (produce AND consume) with other systems using RabbitMQ. Is this scenario not recommended?
2. Are there any examples showing this anywhere?
3. Can I use CAP in a client that does not have access to storage? Part of my can access storage, but another part will be deployed to a DMZ without access to a database. Can that app send and receive messages using InMemory storage while the other part uses a database?
4. Is there a better place to ask these kinds of usage questions, like a Slack or Gitter channel? I saw nothing in readme.md and would have asked on Stackoverflow but there doesn't seem to be much [CAP content there](https://stackoverflow.com/search?q=RabbitMQ+CAP).

**Comment by flipdoubt** [comment]
After some research, I find the code samples can publish to a non-CAP RabbitMQ consumer but does not consume messages sent from a non-CAP RabbitMQ producer, like the RabbitMQ Management tool. How would a CAP consumer need to be configured to consume messages from the RabbitMQ Management tool? 

Samples only appear to consume messages with CAP headers such as those shown below:

property | value
-- | --
cap-callback-name | undefined
cap-corr-id | 1377800954706747392
cap-corr-seq | 0
cap-msg-id | 1377800954706747392
cap-msg-name | sample.console.showtime
cap-msg-type|DateTime
cap-msg-send|2021-04-01 9:52:00 PM -04:00

Are these required?

**Comment by flipdoubt** [comment]
Based on the [Heterogeneous system integration](https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/#heterogeneous-system-integration) section, it appears the sender **does need to set those CAP headers**. Can someone confirm this statement?

If the answer is yes, does that mean we cannot extend the system to intercept a message without `cap-msg-name` and create a corresponding header that uses the routing key for that value? Any suggestions on how to do that?

**Comment by yang-xiaodong** [comment]
> Does need to set those CAP headers. Can someone confirm this statement?

Yes, the consumer needs to ensure that the necessary information is in the message header.

> We cannot extend the system to intercept a message,  create a corresponding header that uses the routing key for that value

Do you mean that you need to consume messages from other systems, and you cannot modify the producer to add message headers?

**Comment by flipdoubt** [comment]
@yang-xiaodong, thanks for answering! 

> Do you mean that you need to consume messages from other systems, and you cannot modify the producer to add message headers?

Yes, we can modify some of the producers to include CAP headers but not all producers. We are just one application in an ecosystem of applications that integrate via RabbitMQ.

I was able to subscribe to messages published by the RabbitMQ Management tool by adding the `cap-msg-name` header. Any guidance on setting up a wildcard subscription on the desired topic exchanges, adding the  `cap-msg-name` header, and re-enqueueing it with the CAP header?

**Comment by yang-xiaodong** [comment]
Hello @flipdoubt ，

We added the `CustomHeaders` configuration item in RabbitMQ options, but before this feature was only available in Kafka options.

Now you can use it to customize the Header to add the necessary infomation, the following is an example:

```
  x.UseRabbitMQ(aa =>
  {
      aa.HostName = "xxxx";
      aa.UserName = "xxxx";
      aa.Password = "xxxx";
      aa.CustomHeaders = e => new List<KeyValuePair<string, string>>
      {
          new KeyValuePair<string, string>(Headers.MessageId, SnowflakeId.Default().NextId().ToString()),
          new KeyValuePair<string, string>(Headers.MessageName, e.RoutingKey),
      };
  });
```

Would you like to submit a PR to us to update our documentation and describe this feature?

**Comment by yang-xiaodong** [comment]
I have released a preview package (version `5.0.2-preview-134636747`) containing this feature to Nuget and you can test it.

**Comment by flipdoubt** [comment]
@yang-xiaodong, sure, I would love to contribute. It will take a bit of experimentation to see if this meets my needs.

I have a couple of questions:

1. Are you saying this custom headers feature adds CAP headers to inbound messages that do not have CAP headers?
2. Is [bdfd101](https://github.com/dotnetcore/CAP/commit/bdfd1016e61394f603da1a84ab8567a42bf740d9) really the only relevant change?

**Comment by yang-xiaodong** [comment]
Thank you for helping us improve the documentation, if you have any questions, please feel free to put it here.

> Are you saying this custom headers feature adds CAP headers to inbound messages that do not have CAP headers?

Yes, it is.

> Is bdfd101 really the only relevant change?

Yes, this is the change made

**Comment by flipdoubt** [comment]
I [forked](https://github.com/flipdoubt/CAP) and verified this **will** suit our needs by customizing the [Sample.ConsoleApp](https://github.com/dotnetcore/CAP/compare/master...flipdoubt:master) to use custom headers. Two questions:

1. As for modifying the docs, do you want me to customize the [messaging](https://github.com/flipdoubt/CAP/blob/master/docs/content/user-guide/en/cap/messaging.md) and [RabbitMQ](https://github.com/flipdoubt/CAP/blob/master/docs/content/user-guide/en/transport/rabbitmq.md) files? Do you want me to add a sample project with custom headers? (I've never contributed to a Github project so I'm (a) unsure of myself and (b) excited.
2. I'm aware of #336 for registering with different attributes, but is there a similar way of supplying my own interface to use in place of `ICapSubscribe`?

**Comment by yang-xiaodong** [comment]
1. No need to add sample projects, just in
In the "heterogeneous-system-integration" chapter, describe how to use this feature to consume messages without headers.

2. As in the answer in https://github.com/dotnetcore/CAP/issues/336#issuecomment-489380712, you can customize the `FindConsumersFromInterfaceTypes` by overriding this method.

**Comment by flipdoubt** [comment]
Submitted pull request #830.
