### ISSUE TITLE
the Processing type data

### ISSUE THREAD

**Issue by dlancerzz** [dotnetcore/CAP#82]
I found some data StatusName = 'Processing' was not sent to Kafka, they will be re-sent?
![image](https://user-images.githubusercontent.com/10334519/35380124-518ec5da-01f3-11e8-8a5d-51538441c74d.png)

**Comment by yuleyule66** [comment]
The status "Processing" means that the CAP is processing the currently sent or received message, and if the processing is successful, the message status is marked as "Scuccess" and will be re-tried if the processing fails. But if you stop the application at this time, then the database will be left in this state of the message, you need to manually process at the Dashboard.

**Comment by dlancerzz** [comment]
Can I deal with the code?

**Comment by yuleyule66** [comment]
Yes , you can change the StatusName to 'Scheduled' with sql

**Comment by dlancerzz** [comment]
ok,thanks
