### ISSUE TITLE
Program cannot start normally with Kafka transport

### ISSUE THREAD

**Issue by ctlyh3059** [dotnetcore/CAP#823]
Using environment: win10 + NETCORE 5.0 + vs2019+CAP5.0.1sourcecode,

using With Kafka, the program stops. But using nuget's cap5.0 is no problem.

**Comment by ctlyh3059** [comment]
There is also a problem, JSON parsing error, in the DotNetCore.CAP.Serialization. jsonutf8serializer should be replaced with Newtonsoft.Json Otherwise, jsonexception -- > the JSON value could not be converted to Newtonsoft.Json.Linq .JToken. Path: $ | LineNumber: 0 | BytePositionInLine: 1.

**Comment by yang-xiaodong** [comment]
Hello,

This is a bug introduced by version 5.0.1

**Comment by yang-xiaodong** [comment]
Issue was fixed in 5.0.1 and released to NuGet a few minutes ago
