### ISSUE TITLE
JSON parsing error

### ISSUE THREAD

**Issue by ctlyh3059** [dotnetcore/CAP#825]
There is also a problem, JSON parsing error, in the DotNetCore.CAP.Serialization. jsonutf8serializer should be replaced with Newtonsoft.Json Otherwise, jsonexception -- > the JSON value could not be converted to Newtonsoft.Json.Linq .JToken. Path: $ | LineNumber: 0 | BytePositionInLine: 1.

**Comment by yang-xiaodong** [comment]
closed by https://zhuanlan.zhihu.com/p/25795393
