### ISSUE TITLE
GetNextPublishedMessageToBeEnqueuedAsync Function Error

### ISSUE THREAD

**Issue by BennetWang** [dotnetcore/CAP#83]
Before we exceute the 'connection.Execute("SELECT LAST_INSERT_ID(0)");',We must manual open  the dbconnection 'connection.Open();'
That is because the LAST_INSERT_ID function is based on the connection and the Execute function of the dapper is closed when the connection is closed before executed.so,we cannot guarantee that we get the same connection.

**Comment by yuleyule66** [comment]
I don't quite understand what you mean, why you want to exceute the `connection.Execute("SELECT LAST_INSERT_ID(0)")` , and what's the error of  `GetNextPublishedMessageToBeEnqueuedAsync` method ?

**Comment by BennetWang** [comment]
我说中文吧。就是LAST_INSERT_ID是连接级别的，那么你如何保证GetNextPublishedMessageToBeEnqueuedAsync这个方法执行两遍不会取到同一条的数据？首先.NET内置了一个连接池，每次open去线程池取连接。如果两次执行更新查询都是同一个连接，但是执行置空LAST_INSERT_ID是另外一个连接，那是不是就会出现重复数据了。。我今天测试了很多次，都出现了这个问题。同一个消息，在queue这张表中生成多条数据。

**Comment by BennetWang** [comment]
Dapper的方法是每次执行完执行会判断原先的连接是否开启，如果是关闭，那么它就会帮你关闭掉。所以，
connection.Execute("SELECT LAST_INSERT_ID(0)");
await connection.QueryFirstOrDefaultAsync<CapPublishedMessage>(sql);
这两句代码不一定是同一个连接。所以我在前面加了 connection.Open();

**Comment by BennetWang** [comment]
不好意思哦，我采用的是MySql，你看一下MySqlStorageConnection这个类。这个是其中的一个方法。

**Comment by BennetWang** [comment]
我采用的是MySql，你看一下MySqlStorageConnection这个类。这个是其中的一个方法。

**Comment by yuleyule66** [comment]
Yes, you are right.

I looked at the Dapper source code, if the connection is opened by Dapper then Dapper will be close the connection after Execute. This may result in the execution of `LAST_INSERT_ID` not the same connection as executing SQL statements.

I will fix this issue later, thanks for your report.

**Comment by yuleyule66** [comment]
version `2.1.4-preview-33704197`  fixed this bug.
