### ISSUE TITLE
How to serialize Mongo model in Cap

### ISSUE THREAD

**Issue by Guan9hong** [dotnetcore/CAP#833]
I using GeoJsonObjectModel and GeoJson Serializer from Mongo .net driver. I don't know how to use it in Cap? You can help me implement it. 

I Using Publish PublishAsync<Type> Serializer works very well, but In a project that I subscribing, it get error:
```
NotSupportedException-->Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'MongoDB.Driver.GeoJsonObjectModel.GeoJsonMultiPolygon`1[MongoDB.Driver.GeoJsonObjectModel.GeoJson2DCoordinates]'. Path: $.geomtry | LineNumber: 0 | BytePositionInLine: 108."

```

**Comment by yang-xiaodong** [comment]
Hello, 

I have no idea about GeoJson Serializer, It doesn't seem to have anything to do with CAP

**Comment by Guan9hong** [comment]
> Hello,
> 
> I have no idea about GeoJson Serializer, It doesn't seem to have anything to do with CAP

I know, but I mean how can I implement serialization base on type in CAP?

**Comment by yang-xiaodong** [comment]
Here's a reference that might help you

https://stackoverflow.com/questions/60806942/c-sharp-mongodb-geojsonpoint-json-object

**Comment by Guan9hong** [comment]
> Here's a reference that might help you
> 
> https://stackoverflow.com/questions/60806942/c-sharp-mongodb-geojsonpoint-json-object

I can serialize and deserialize in Publisher Application, but Get error when receiving Message from Cap.

**Comment by Guan9hong** [comment]
> Here's a reference that might help you
> 
> https://stackoverflow.com/questions/60806942/c-sharp-mongodb-geojsonpoint-json-object

I can Serialize and Deserialize normally when I get data from the database, push data into the database and  push data to CAP as well. But when I received data from Cap, there was an error.

**Comment by yang-xiaodong** [comment]
I konw , This is because `GeoJsonMultiPolygon` does not have  a parameterless constructor, and `System.Text.Json` does not provide support for it

**Comment by Guan9hong** [comment]
> I konw , This is because `GeoJsonMultiPolygon` does not have a parameterless constructor, and `System.Text.Json` does not provide support for it

In Application that using Mongo, I'm using BsonSerializer to add custom Serializer to deal with Geojson, but I don't know how Mongo can do that.

**Comment by yang-xiaodong** [comment]
Maybe you can try version 3.1.2, we replaced Newtonsoft.Json with System.Text.Json in version 5.0. As far as I know, Newtonsoft.Json does  support a parameterless constructor

**Comment by yang-xiaodong** [comment]
https://cap.dotnetcore.xyz/user-guide/zh/cap/serialization/

You can reference our docs to see how to customize serialization, docs may be outdated

**Comment by Guan9hong** [comment]
> https://cap.dotnetcore.xyz/user-guide/zh/cap/serialization/
> 
> You can reference our docs to see how to customize serialization, docs may be outdated

I dont see branch 3.1.2. You didn't save the branch. I'm trying from nuget.

**Comment by Guan9hong** [comment]
> https://cap.dotnetcore.xyz/user-guide/zh/cap/serialization/
> 
> You can reference our docs to see how to customize serialization, docs may be outdated

It work, but get null data from geometry property. Can you share me the code

**Comment by Guan9hong** [comment]
Oh sorry, I see the code from tags.

**Comment by Guan9hong** [comment]
a lot thing to do, seem that Newtonsoft can't serialize Geojson.
