### ISSUE TITLE
Add dapr suport

### ISSUE THREAD

**Issue by araxis** [dotnetcore/CAP#836]

**Comment by yang-xiaodong** [comment]
Why do we need dapr? What can dapr offer us?

**Comment by araxis** [comment]
Dapr is a portable, serverless, event-driven runtime that makes it easy for developers to build resilient, stateless and stateful microservices that run on the cloud and edge and embraces the diversity of languages and developer frameworks.
https://github.com/dapr/dapr

if add support for pub/sub component ,it means that add support for every pub/sub support that dapr support it

**Comment by yang-xiaodong** [comment]
Dapr is a framework, and CAP is a library, I think they have different application scenarios. Dapr is neither a storage nor a message queue, so why use its Pub/Sub function to deliver messages again?

**Comment by araxis** [comment]
first sorry for may bad english  .maybe  I can't explain it correctly.
dapr pub/sub support multiple message brokers , in fact dapr pub/sub abstract use of message brokers .
it means that you can change your broker without change your code.
on other hand ,outbox message pattern  used to separate  local transaction from out of transaction actions,here pub/sub componet.so if CAP just add support for cap client, actually  dapr's users has no worry about undelaying message brokers mechanism.
again a am very very sorry for my awful wording.

**Comment by yang-xiaodong** [comment]
Hello, I am sorry to tell you that we have no plans to support Dapr.

If you wish, you can create a CAP extension project, we are happy to link the project to our document.
