### ISSUE TITLE
How to add AOP on consumer side

### ISSUE THREAD

**Issue by huang619915854** [dotnetcore/CAP#837]
请问,如何在CapSubscribe 消费着 方法 加上AOP，因为我需要在方法前后做扩展
目前在控制器里面加上了[NonAction]特许，使用自带的过滤器以及中间件都不能够拦截成功

**Comment by yang-xiaodong** [comment]
see https://cap.dotnetcore.xyz/user-guide/zh/samples/castle.dynamicproxy/
