### ISSUE TITLE
kafka发送消息成功无法接受到消费信息

### ISSUE THREAD

**Issue by knowyi** [dotnetcore/CAP#838]
你好，我使用的最新版本的CAP 5.0.1 Publish消息正常 
但是在消费的方法里接受不到消息 请问是什么问题，这是消费的方法

![image](https://user-images.githubusercontent.com/7392434/115371853-ec1baf80-a1fc-11eb-90ac-e4a9e0009289.png)

![image](https://user-images.githubusercontent.com/7392434/115371495-9b0bbb80-a1fc-11eb-9ccb-1b0d30fd7f39.png)

**Comment by knowyi** [comment]
注册的是否有问题
![image](https://user-images.githubusercontent.com/7392434/115372024-12d9e600-a1fd-11eb-9a21-2a24196be50f.png)

**Comment by knowyi** [comment]
![image](https://user-images.githubusercontent.com/7392434/115373452-7a446580-a1fe-11eb-965d-9b57966d3ef3.png)
Publish 以后 kafka里数据能接收到

**Comment by knowyi** [comment]
Broker: Unknown topic or partition 日志报错

**Comment by knowyi** [comment]
Broker: Unknown topic or partition 日志报错 我看5.0版本公告写解决了这个问题，请问是怎么怎么处理的
![image](https://user-images.githubusercontent.com/7392434/115382790-a9aba000-a207-11eb-8634-6a18aa194632.png)

**Comment by knowyi** [comment]
Broker: Unknown topic or partition 日志报错 我看5.0版本公告写解决了这个问题，请问是怎么处理的，是不是我写的有问题？
![image](https://user-images.githubusercontent.com/7392434/115382894-c5af4180-a207-11eb-8c03-2a1492c8f0c7.png)

**Comment by xiangxiren** [comment]
Please see #795

**Comment by knowyi** [comment]
> Please see #795

我并没有看到应该如何解决这个问题

**Comment by xiangxiren** [comment]
@yang-xiaodong It seems that you removed the previous submission again
![image](https://user-images.githubusercontent.com/12774053/115485370-26319380-a287-11eb-9330-08070fafaf33.png)

**Comment by knowyi** [comment]
@xiangxiren 我现在需要做什么 可以暂时先解决这个问题吗？

**Comment by yang-xiaodong** [comment]
@xiangxiren  The code was refactored [here](https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs#L37)

@knowyi   Did you try our example (Sample.Kafka.PostgreSql)  that the Topic cannot be created automatically on the first run?

**Comment by knowyi** [comment]
> @xiangxiren The code was refactored [here](https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs#L37)
> 
> @knowyi Did you try our example (Sample.Kafka.PostgreSql) that the Topic cannot be created automatically on the first run?

@yang-xiaodong I haven't tried example (Sample.Kafka.PostgreSql) . I'll try later

**Comment by xiangxiren** [comment]
> @xiangxiren The code was refactored [here](https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.Kafka/KafkaConsumerClient.cs#L37)
> 
> @knowyi Did you try our example (Sample.Kafka.PostgreSql) that the Topic cannot be created automatically on the first run?
got it

**Comment by yang-xiaodong** [comment]
@knowyi  Hello, Do you have any further information?

**Comment by yang-xiaodong** [comment]
No response, closed!

**Comment by knowyi** [comment]
> @knowyi Hello, Do you have any further information?

Sample doesn't have this problem, but my own project still has this error. At present, I have changed to rabbitmq, but Kafka still has problems

**Comment by knowyi** [comment]
@yang-xiaodong @xiangxiren 目前测试下来sample也有问题 Unknown topic or partition 请问目前是怎么解决

**Comment by yang-xiaodong** [comment]
@knowyi 目前我无法复现你的描述的问题， 请提供详细步骤。

以下是我的测试视频：

https://youtu.be/hv1FKb4u9EM

**Comment by knowyi** [comment]
> @knowyi 目前我无法复现你的描述的问题， 请提供详细步骤。
> 
> 以下是我的测试视频：
> 
> https://youtu.be/hv1FKb4u9EM
> 
> 视频中可以看到，我使用了一个新的Topic `sample.kafka.postgrsql-foo` , 在发送和消费的过程中，并没有出现异常

视频我一会看一下 我的测试基本和 #744 一样

**Comment by yang-xiaodong** [comment]
#744 这个问题我们在5.0+的版本中已经改进，如果你还有问题，请提供详细的信息给到我们，包括测试代码，测试步骤，环境信息，版本信息等。

如果只是说有问题，而不愿提供进一步信息，我们无法进行调查，记住这是一个开源项目，每个人都可以参与，我们也没有为你服务的义务

**Comment by knowyi** [comment]
> #744 这个问题我们在5.0+的版本中已经改进，如果你还有问题，请提供详细的信息给到我们，包括测试代码，测试步骤，环境信息，版本信息等。
> 
> 如果只是说有问题，而不愿提供进一步信息，我们无法进行调查，记住这是一个开源项目，每个人都可以参与，我们也没有为你服务的义务

目前我使用的是CAP 5.0..1 项目是net5,0 操作系统windows10 开发环境
测试代码和步骤我整理一下稍后提供 我不确定是不是因为之前说合并代码的问题 导致的5.0+版本有问题 我只是觉得我这个问题 可能别人也会遇到，并不觉得你们有义务为我提供服务

![image](https://user-images.githubusercontent.com/7392434/116180743-03522400-a74c-11eb-90de-80f1a43434c0.png)
![image](https://user-images.githubusercontent.com/7392434/116180991-6348ca80-a74c-11eb-9368-5df47889f9eb.png)
