### ISSUE TITLE
InvalidCastException after adding CAP to existing, multi-project solution

### ISSUE THREAD

**Issue by flipdoubt** [dotnetcore/CAP#839]
After adding `DotNeteCore.Cap.SqlServer` to our solution where other projects reference other packages, using EF Core 5.0.2 to insert records from non-CAP code succeeds and then produces the error shown below. I see that they point to different folders in my local nuget cache but I do not know how to unify the references because I have no code that directly references 2.0.1 or 2.1.2.

Can you suggest how I can unify the references? Is there some way to disable `DiagnosticObserver` or prevent it from interfering with EF Core?
```
TYPE: System.InvalidCastException
MSG: [A]Microsoft.Data.SqlClient.SqlConnection cannot be cast to [B]Microsoft.Data.SqlClient.SqlConnection.
Type A originates from 'Microsoft.Data.SqlClient, Version=2.0.20168.4, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5' in the context 'Default' at location 'C:\Users\me\.nuget\packages\microsoft.data.sqlclient\2.0.1\
runtimes\win\lib\netcoreapp3.1\Microsoft.Data.SqlClient.dll'.
Type B originates from 'Microsoft.Data.SqlClient, Version=2.0.20168.4, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5' in the context 'Default' at location 'C:\Users\me\.nuget\packages\microsoft.data.sqlclient\2.1.2\runtimes\win\lib\netcoreapp3.1\Microsoft.Data.
SqlClient.dll'.
   at DotNetCore.CAP.SqlServer.Diagnostics.DiagnosticObserver.OnNext(KeyValuePair`2 evt) in C:\projects\cap\src\DotNetCore.CAP.SqlServer\Diagnostics\DiagnosticObserver.cs:line 41
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.Data.SqlClient.SqlClientDiagnosticListenerExtensions.WriteTransactionCommitAfter(SqlDiagnosticListener this, Guid operationId, IsolationLevel isolationLevel, SqlConnection connection, SqlInternalTransac
tion transaction, String operation) in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlClientDiagnosticListenerExtensions.cs:line 253
   at Microsoft.Data.SqlClient.SqlTransaction.Commit() in H:\tsaagent1\_work\21\s\src\Microsoft.Data.SqlClient\netcore\src\Microsoft\Data\SqlClient\SqlTransaction.cs:line 182
   at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit()
```

**Comment by xiangxiren** [comment]
Maybe you should refer to the same EFCore as the dependency version of DotNetCore.CAP.SqlServer

**Comment by flipdoubt** [comment]
@xiangxiren, thanks for the reply. I just tried that and got the same error. The problem appears to be that I reference `Microsoft.EntityFrameworkCore.SqlServer`, which references the older 'Microsoft.Data.SqlClient 2.0.1`. Even EF Core 5.0.5 references  'Microsoft.Data.SqlClient 2.0.1`.

**Comment by flipdoubt** [comment]
I don't use CAP with EF Core, so I tried downgrading to `DotNetCore.Cap.SqlServer 3.1.2` which uses `Microsoft.Data.SqlClient 2.0.1`. This appears to fix my issue, though I'm still testing.

**Comment by yang-xiaodong** [comment]
Hello David,

It seems that this is due to the conflict caused by `Microsoft.EntityFrameworkCore.SqlServer` and `DotNetCore.CAP.SqlServer` use different versions of `Microsoft.Data.SqlClient`.

In theory, referencing the new version of `Microsoft.Data.SqlClient` in the project can resolve the conflict. If you can’t solve this problem, we can consider downgrading Microsoft.Data.SqlClient to 2.0.1

**Comment by flipdoubt** [comment]
Our project that uses `Microsoft.EntityFrameworkCore.SqlServer 5.0.4` now references `Microsoft.Data.SqlClient 2.1.2` explicitly, though it does not use it, and still gets the `System.InvalidCastException` "at DotNetCore.CAP.SqlServer.Diagnostics.DiagnosticObserver.OnNext(KeyValuePair`2 evt) in C:\projects\cap\src\DotNetCore.CAP.SqlServer\Diagnostics\DiagnosticObserver.cs:
line 41."

I suspect we get this error due to the fact that we dynamically load each of these projects as plugins that implement interfaces from a shared contracts library. We use other components that reference older versions, like [Serilog MSSqlServer](https://github.com/serilog/serilog-sinks-mssqlserver) which depends on `Microsoft.Data.SqlClient >= 1.1.3` but have never had this problem until we added `DotNetCore.CAP.SqlServer`. Odd that it only occurs after a "write transaction" that does not even involve CAP.

Curious as to why  `Microsoft.EntityFrameworkCore.SqlServer 5.0.4` does not use `Microsoft.Data.SqlClient 2.1.2` and what this version gives CAP that 2.0.1 does not. Any insights?

It would be great if you considered downgrading if 2.1.2 doesn't provide new functionality other than "latest and greatest".

**Comment by yang-xiaodong** [comment]
Hello David,

We have downgraded `Microsoft.Data.SQLClient` to 2.0.1, you can try with the preview version `5.0.2-preview-136113481`.

Thanks for your feedback

**Comment by flipdoubt** [comment]
@yang-xiaodong, tested and confirmed it works with `5.0.2-preview-136113481`.
