### ISSUE TITLE
Why you don't use Generic type for Message?

### ISSUE THREAD

**Issue by Guan9hong** [dotnetcore/CAP#840]
I think that using a Generic type in the Value attribute would be better for Serialize. I'm trying to do that and improve serialization to integrated with MongoDB Serializer.

**Comment by yang-xiaodong** [comment]
The consumer type is dynamically metadata, so generics cannot be used.

see https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/Internal/ISubscribeInvoker.Default.cs#L66

**Comment by Guan9hong** [comment]
I can use a Generic ConsumerContext<T> and implement InvokeAsync<T>

**Comment by Guan9hong** [comment]
The limitation of this approach is that we need to use sparate Dispatcher and CapPublisher for each T generic type.

**Comment by Guan9hong** [comment]
> Due to your brief description, I can't know exactly how you are going to do it now.
> 
> If your improvement is reasonable, welcome to submit a PR, now I close this issue

Year, I'm trying to make a strong type Value attribute of the Message.

**Comment by Guan9hong** [comment]
@yang-xiaodong  Do you want to join my private Repo, sorry because I can't public them yet, If you see that is reasonable I will pork and make a pull requestt.

**Comment by Guan9hong** [comment]
I have invited you to my projet.

**Comment by yang-xiaodong** [comment]
You'd better submit a PR so that we can compare and check what you have changed

**Comment by Guan9hong** [comment]
> You'd better submit a PR so that we can compare and check what you have changed

pls review my code https://github.com/Guan9hong/CAP
