### ISSUE TITLE
The Use of Multiple Databases for Multi-Queue

### ISSUE THREAD

**Issue by omeerkorkmazz** [dotnetcore/CAP#841]
In the CAP workflow, when the system is configured once, the publisher/subscriber works with a defined configuration. However, in different cases, we can want to use various configurations for multi-queue in the same project (especially for the producer). 

In our case, I would like to use CAP in my API which consists of different modules (e.g, product, order, shipment). Here, instead of using one huge database for all kinds of messages, I would like to separate the databases for each module in order to manage them easily (e.g., ProductQueueDB, OrderQueueDB). 

How can we handle this situation? Can I specifically configure injected `ICapPublisher` i.e., can the publisher work as an original RabbitMQ client?

The primitive solution might be;

- `ICapPublisher<TConfiguration>` where `TConfiguration` consists of all functionalities that normally provided in `ServiceCollections`.

**Comment by yang-xiaodong** [comment]
Sounds similar to #783, for reference

**Comment by omeerkorkmazz** [comment]
@yang-xiaodong thanks for your quick reply! I missed this one. Sorry for the repetition.
