### ISSUE TITLE
round-robin or broadcasting: with same group different topic in two separate apps?

### ISSUE THREAD

**Issue by figofan** [dotnetcore/CAP#848]
If two apps share the same group but different topic, it seems the message is distributed in a round robin manner instead of broadcasting to them both, and being handled by the app with matched topic & being discarded by the other app with unmatched topic, can you confirm if round-robin  is the right behavior in this case?

**Comment by yang-xiaodong** [comment]
Hello,

This behavior is determined by Transport, and the consumer group corresponds to the different feature provided by Transport.

In RabbitMQ, Group corresponds to queue name.

In Kafka, Group will correspond to consumer group id.
