### ISSUE TITLE
Register ICapPublisher with an existing transaction

### ISSUE THREAD

**Issue by thisispaulsmith** [dotnetcore/CAP#849]
Following on from this example....

```
using (var trans = dbContext.Database.BeginTransaction(_capBus, autoCommit: false)) 
     { 
         dbContext.Persons.Add(new Person() { Name = "ef.transaction" }); 
  
         for (int i = 0; i < 1; i++) 
         { 
             _capBus.Publish("sample.rabbitmq.mysql", DateTime.Now); 
         } 
  
         dbContext.SaveChanges(); 
  
         trans.Commit(); 
     } 
```

If there is already a transaction. How do you add `ICapPublisher` to it. The extension methods assume you're starting the transaction at the point of adding. Something like the following.

```
_capBus.Publish("sample.rabbitmq.mysql", DateTime.Now, existingTrans); 
```

I've raised a similar issue in the past but it was closed. The fact that `ICapPublisher` is a singleton is problematic and Transaction is AsyncLocal as it doesn't work well with multiple calls with async/await.

I've created a sample repo highlighting the above.

https://github.com/thisispaulsmith/captransaction

**Comment by yang-xiaodong** [comment]
Cannot add ICapPublisher to an existing transaction, because we need to know when the transaction is committed to allow CAP to flush messages to transport

**Comment by thisispaulsmith** [comment]
You would still know when the transaction was commited as it would still be commited as it was before? You just need a reference to the actual transaction? Or am I being stupid?

**Comment by yang-xiaodong** [comment]
> You just need a reference to the actual transaction? Or am I being stupid?

Yes, I can reference the actual transaction, but we need some kind of notification mechanism to tell us the status change of the transaction. In SQL Server, we use Diagnostics to monitor the transaction submission, but this cannot be done in other databases.

Therefore, the commit action of the transaction needs to be handed over to the CAP, which I did not see in your sample code

https://github.com/thisispaulsmith/captransaction/blob/c6eaf5ce3953e25febff242bc78b37bb9bf6b78f/src/CapTrans/Infrastructure/MediatR/TransactionBehaviour.cs#L38

**Comment by yang-xiaodong** [comment]
Hello, I got your point.

Because in the asynchronous context, AsyncLocal flow cannot pass values to the parent, see: https://stackoverflow.com/questions/37306203/how-to-make-asynclocal-flow-to-siblings

So we need to assign values externally, the sample code is probably like this.

```C#
public class TransactionBehaviour<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>
{
    private readonly MyDbContext _dbContext;
    private readonly ICapPublisher _cap;

    public TransactionBehaviour(MyDbContext context, ICapPublisher cap)
    {
        _dbContext = context ?? throw new ArgumentException(nameof(MyDbContext));
        _cap = cap;
    }

    public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
    {
        var response = default(TResponse);

        var strategy = _dbContext.Database.CreateExecutionStrategy();

        await strategy.ExecuteAsync(async () =>
        {
            var currentTransaction = await _dbContext.Database.BeginTransactionAsync(cancellationToken);
            _cap.Transaction.Value = ActivatorUtilities.CreateInstance<SqlServerCapTransaction>(_cap.ServiceProvider);
            var capTrans = _cap.Transaction.Value.Begin(currentTransaction, false);

            response = await next();

            await _dbContext.SaveChangesAsync(cancellationToken);
            await capTrans.CommitAsync(cancellationToken);

            capTrans.Dispose();
        });

        return response;
    }
}
```

Changing the life cycle of ICapPublisher to Scoped helps to solve this problem, but we are not able to do so at the moment, because many of our users are already using it based on the singleton pattern.

Please feel free to put any better suggestions here, thank you

**Comment by thisispaulsmith** [comment]
It would be pretty straight forward to have an opt in approach to the scoped registration as opposed to the singleton.

When adding cap just setting something like ```options.UseScoped = true ``` which would adjust the registration accordingly?

**Comment by yang-xiaodong** [comment]
We will consider your suggestion, but this is not only an option of `UseScoped=true` but also a lot of associated code changes.

Currently we do not provide a BeginTransactionAsync function to support asynchrony. You can use a synchronous function to start a transaction, which will solve your problem.

I set this issue as backlog so that we can consider improvements in the future.

**Comment by thisispaulsmith** [comment]
Without this is it really hampers the use of cap in anything but the most simple scenarios. No one should be managing transactions every time they do some data access.

I've tried creating my own publisher but can't access some of the required internals. I don't particularly want to fork the repo.

Creating an alternative publisher alongside `ICapPublisher.default.cs` say `ICapPublisher.Scoped.cs' and registering that when oped in.
