### ISSUE TITLE
使用DotNetCore.CAP.SqlServer，Schema不能设置特殊符号的值

### ISSUE THREAD

**Issue by tirongaws** [dotnetcore/CAP#85]
schema设置了 **my.cap**
```csharp
capOptions.UseEntityFramework<AppDbContext>(opts => opts.Schema = "my.cap");
```
会出如下错
>System.Data.SqlClient.SqlException: 'Invalid object name 'my.cap.Published'.  

应该是因为`SqlServerStorage.CreateDbTablesScript`方法中

```
BEGIN
	EXEC('CREATE SCHEMA {schema}')
END;
```
把上面 **{schema}** 改成 **[{schema}]**，应该就可以了

**Comment by yuleyule66** [comment]
fixed in version `2.1.4-preview-34848409`
