### ISSUE TITLE
Document: Add database diagram on readme page 

### ISSUE THREAD

**Issue by maulik-modi** [dotnetcore/CAP#853]
Database diagram showing *schema and sample records of Outbox* and supporting tables is required for wider adoption and lower the barrier. https://github.com/dotnetcore/CAP. we use https://dbeaver.io/download/ community edition for database diagram.

**Comment by yang-xiaodong** [comment]
Hello,
I don't quite understand what you mean,
Here is the structure of the database table we created https://cap.dotnetcore.xyz/user-guide/en/storage/general/#storage-data-structure, do you mean we need to provide a database diagram for two tables?

**Comment by maulik-modi** [comment]
@yang-xiaodong , I did not know there are two tables only. I have been using Rebus in my projects but it lacks Outbox support.

Here's tables from Rebus: 
string queueTableName = "RebusMessages",
            string sagaDataTableName = "RebusSaga",
            string sagaIndexTableName = "RebusSagaIndex",
            string subscriptionsTableName = "RebusSubscriptions",
            string timeoutTableName = "RebusTimeouts",
            string dataBusTableName = "RebusDataBus",

https://github.com/rebus-org/Rebus.Recipes/blob/master/Rebus.Recipes/Configuration/SqlServerRebusConfigurationExtensions.cs
