### ISSUE TITLE
SubscriberExecutionFailedException --> An exception was thrown while activating

### ISSUE THREAD

**Issue by penjay** [dotnetcore/CAP#855]
A large amount of messages is abnormal, Rabbitmq server version: 3.8.14
Query Issue, there is a similar question saying is that the Rabbitmq version is too high, but I didn't see where to indicate which version of Rabbitmq you need to use.

![image](https://user-images.githubusercontent.com/23008915/117231736-65004580-ae52-11eb-8a1c-84deb46be470.png)

![image](https://user-images.githubusercontent.com/23008915/117231648-34b8a700-ae52-11eb-9a01-aa9ac34b8cb1.png)

One of the messages， Message Content：
{
	-"Headers": {
		"cap-callback-name": null,
		"cap-msg-id": "1390124177075834880",
		"cap-corr-id": "1390124177075834880",
		"cap-corr-seq": "0",
		"cap-msg-name": "shop.product.changed",
		"cap-msg-type": "CapQueue`1",
		"cap-senttime": "5/6/2021 10:00:05 AM +08:00",
		"cap-msg-group": "product.v1",
		"cap-exception": "SubscriberExecutionFailedException-->An exception was thrown while activating HD.Application.ShopApp -> HD.Services.ShopBankAccountService -> HD.Repositories.Implement.ShopBankRepository."
	},
	-"Value": {
		"QueueId": "03b896a9-86b0-4730-8cb4-44cda1dbe26d",
		"Data": 10276
	}
}

**Comment by penjay** [comment]
#637

**Comment by yang-xiaodong** [comment]
Hello , Please report your exception stack log. Looks like an exception when instantiating HD.Application.ShopApp

**Comment by penjay** [comment]
> Hello , Please report your exception stack log. Looks like an exception when instantiating HD.Application.ShopApp

Sorry, after careful finding is dependencyresolver error, but I don't know why I have no problem locally.
code：
// var env = DependencyResolver.Current.GetService<IWebHostEnvironment>();

**Comment by xiangxiren** [comment]
Is there a dependencyresolver in. Net 5?
