### ISSUE TITLE
CAP document

### ISSUE THREAD

**Issue by horseznguyen** [dotnetcore/CAP#856]
Hi,

I read through the CAP document, so I have a few questions :

1. How do CAP load balance consumers across machines? 
2. I have a customer so I deployed it to many instances, do CAP ensure one instance to process message? 
3. When CAP published the message from the database to Broker Message, we have these choices:
- Publish the integration event right after committing the transaction and use another local transaction to mark the events in the table as being published
- Use the table as a kind of queue. A separate application thread or process queries the integration event table, publishes the events to the event bus, and then uses a local transaction to mark the events as published.
Which CAP choice in this situation?

**Comment by yang-xiaodong** [comment]
Hello, 

Let me answer your question,

> How do CAP load balance consumers across machines?

This is to take advantage of the features provided by the message queue. For example, Kakfa, when multiple consumers are in the same Group, only one can receive messages to achieve load balancing, and other message queues are similar.

> I have a customer so I deployed it to many instances, do CAP ensure one instance to process message?

Yes, refer the previous answer.

> When CAP published the message from the database to Broker Message, we have these choices:

The SQL that records the message event and the SQL of the business operation are in the same transaction, and we push the message to the message queue after the transaction is successfully committed.

**Comment by horseznguyen** [comment]
Hi @yang-xiaodong 

Thank you very much for your answer.

> The SQL that records the message event and the SQL of the business operation are in the same transaction, and we push the message to the Broker after the transaction is successfully committed. Push events to the Broker no longer need to use transactions, when it fails, it will retry, when it success, it will mark message to published.

If the number of messages is large, the user has to wait for the messages to be sent to the Broker (the messages are temporarily stored in memory after the transaction is successfully committed). Is there a way to improve this processing, for example, a separate application thread to handle this in the background in order for to user not to have to await.?

**Comment by yang-xiaodong** [comment]
At present, as you said, the message is temporarily stored in the memory queue and pushed to the Broker by a separate thread, the user does not need to wait

**Comment by horseznguyen** [comment]
Hi @yang-xiaodong 

Does CAP support SAGA or any planning to implement the SAGA pattern in the future?

**Comment by yang-xiaodong** [comment]
No, using Saga requires users to have a correct understanding of it and reasonably split the business process, and then use the flowchart to describe and generate json to let the program execute. Obviously, the entire processing process needs to be monitored, which is a complicated work.
Currently you can manually organize the state process rules in each service instead of focusing on the entrance.

If you need this feature, you can consider MassTransit, but I think it lacks monitoring features.

**Comment by horseznguyen** [comment]
Hi @yang-xiaodong 

![image](https://user-images.githubusercontent.com/28267489/117605019-fccaa000-b180-11eb-9b5f-8b63b4f2f128.png)

Does CAP support a type of transaction like that? , I cannot find Begin method in the current version.

**Comment by yang-xiaodong** [comment]
https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.MySql/ICapTransaction.MySql.cs#L104

**Comment by yang-xiaodong** [comment]
I think you are using CAP incorrectly. CAP is mainly used to process business scenarios that include transactions.

For your scenario, I suggest you use the client to directly connect to the Broker and send in batches
