### ISSUE TITLE
OpenTelemtry Contrib for CAP

### ISSUE THREAD

**Issue by devgig** [dotnetcore/CAP#858]
We have decided to switch from MT to CAP for distributing data with events.  One thing that CAP lacks that we like is OpenTelemetry Contribs.  https://opentelemetry.io/.  
https://www.nuget.org/packages/OpenTelemetry.Contrib.Instrumentation.MassTransit/1.0.0-beta1
Have you looked into adding this ability to CAP so we can get end to end tracing through events?  If you not have it, we are planning on building it and would appreciate any guidance.

**Comment by yang-xiaodong** [comment]
Hello,

I have checked the diagnostic events provided by MT [here](https://masstransit-project.com/advanced/monitoring/diagnostic-source.html#available-diagnostic-events). `Saga` and `Courier` are not provided by CAP, and other events have corresponding in CAP.

You can find the events provided by CAP [here](https://cap.dotnetcore.xyz/user-guide/en/monitoring/diagnostics/#diagnostics-events), I don’t know much about opentelemetry, but what I can provide is an example I did for OpenTracing three years ago

https://github.com/yang-xiaodong/OpenTracing.Contrib.CAP

We have been directly supporting SkyWalking, please refer to our implementation in SkyWalking

https://github.com/SkyAPM/SkyAPM-dotnet/tree/master/src/SkyApm.Diagnostics.CAP

Welcome your PR!
Thanks
