### ISSUE TITLE
Throw "Object must implement IConvertible." when converting to a string.

### ISSUE THREAD

**Issue by gdlcf88** [dotnetcore/CAP#865]
![image](https://user-images.githubusercontent.com/30018771/117929092-f843ea00-b32e-11eb-9064-c7abb1ed2ff2.png)
![image](https://user-images.githubusercontent.com/30018771/117929233-25909800-b32f-11eb-80d5-7fc12b226c79.png)
![image](https://user-images.githubusercontent.com/30018771/117929258-2aede280-b32f-11eb-98e0-192812ff777e.png)

https://github.com/EasyAbp/EShop/blob/4d9d410f70c86ea286df27d1027336f8065dd499/modules/EasyAbp.EShop.Payments/src/EasyAbp.EShop.Payments.Domain/EasyAbp/EShop/Payments/Payments/PaymentSynchronizer.cs#L160

This happened after I updated to CAP 5.0+ by using https://github.com/EasyAbp/Abp.EventBus.CAP.

**Comment by yang-xiaodong** [comment]
Hello, You should report the issue to [Abp.EventBus.CAP](https://github.com/EasyAbp/Abp.EventBus.CAP) repository,  We only deal with direct CAP related issues here

**Comment by gdlcf88** [comment]
After https://github.com/dotnetcore/CAP/commit/e5607f09f184b23e6c33330c568c9082fd49c8d9#diff-06b0b1ce6bb0a834493bbdafd8a44a4ea322aeb9a724581ab39597051aa51269, the CAP begins to use System.Text.Json, which is not good at deserializing JSON to complex types, I use AbpHybridJsonSerializer to implement CAP's ISerializer, so the problem is solved now.

[AbpJsonSerializer](https://github.com/EasyAbp/Abp.EventBus.CAP/blob/a358abc19e053c5754d7295750a148d81eafbb78/src/EasyAbp.Abp.EventBus.CAP/AbpJsonSerializer.cs)
