### ISSUE TITLE
Support for topic regex pattern

### ISSUE THREAD

**Issue by vhbfnet** [dotnetcore/CAP#871]
Hi,
When we use cap with "x.UseKafka(...)", it is possible to subscribe to multiple topics as below or with regex ?

`[CapSubscribe("*.customer.created")]`

kafka already implements topic regex pattern
https://github.com/dpkp/kafka-python/blob/68c8fa4ad01f8fef38708f257cb1c261cfac01ab/kafka/consumer/group.py#L717

**Comment by yang-xiaodong** [comment]
Hello, 

your request has been supported, and now you can specify `*` or `#` on topic for bulk subscription,

Rules reference:

https://www.rabbitmq.com/tutorials/tutorial-five-python.html

**Comment by yang-xiaodong** [comment]
Fixed in 5.1.0-preview-138879827

**Comment by vhbfnet** [comment]
Hello,

Great it works nicely thanks
