### ISSUE TITLE
Bootstrap Listener

### ISSUE THREAD

**Issue by giorgilekveishvili-meama** [dotnetcore/CAP#873]
As I see there is no way to get information when bootstrapping finishes , for example I want to add default data when server start ups and Immediately publish this data , Cap might not be started at this point so I loose data . One way is to call BootstrapAsync , but I think its better to have Event when bootstrapping finishes.

**Comment by yang-xiaodong** [comment]
Are you using CAP in a console application or ASP.NET Core?

**Comment by giorgilekveishvili-meama** [comment]
Asp.net Core

**Comment by giorgilekveishvili-meama** [comment]
Added PR for functionality - https://github.com/dotnetcore/CAP/pull/874

**Comment by yang-xiaodong** [comment]
>  I want to add default data when server start ups and Immediately publish this data, Cap might not be started at this point so I loose data

I don't particularly understand what you mean. Sending a message is not directly related to whether the CAP is started or not. CAP startup is mainly used to consume messages

**Comment by giorgilekveishvili-meama** [comment]
If message publishes until Cap Bootstrapping is finished , it does not send message (With RabbitMQ) nor store it in storage , So my point is to have state callbacks like (Cap Started , Storage  Init Failed , Succeeded and etc) , to subscribe this callback and make action when we are sure that CAP is started please check pr https://github.com/dotnetcore/CAP/pull/874

**Comment by yang-xiaodong** [comment]
> If message publishes until Cap Bootstrapping is finished , it does not send message (With RabbitMQ) nor store it in storage

The `publish` method will directly call Storage for persistence. Can you explain the lost message scenario in detail? 

https://github.com/dotnetcore/CAP/blob/b96af5372de00fbbb966f663f9e0ec9e3d85c852/src/DotNetCore.CAP/Internal/ICapPublisher.Default.cs#L110

In addition, I think this is not a wide-ranging requirement, because CAP and the host program are started together. Ideally, a health check should report whether the host is available.

**Comment by giorgilekveishvili-meama** [comment]
I have docker-compose file where are all,  services with MSSQL Image , sometimes when I first time run docker-compose  and calling publish method  ` _storage.StoreMessage(name, message, transaction.DbTransaction)` fails 

>   invalid object name cap.publish

This means that   [`transaction.AddToSent(mediumMessage);`](https://github.com/dotnetcore/CAP/blob/b96af5372de00fbbb966f663f9e0ec9e3d85c852/src/DotNetCore.CAP/Internal/ICapPublisher.Default.cs#L114) -> Is not called and not queued for message , which is (as i think ) loosen message.

**Comment by yang-xiaodong** [comment]
This is by design, If your database service is unavailable, the message should not be sent.

In addition, you should not put MSSQL and applications using Docker-compose together. The database is a basic service and needs to be prepared in advance.
