### ISSUE TITLE
Add options for unicode encoding for System.Text.Json

### ISSUE THREAD

**Issue by zhh2017** [dotnetcore/CAP#875]
5.0版本使用 System.Text.Json进行json序列化后，中文默认会被Unicode编码(问题参考：https://www.cnblogs.com/dudu/p/11562019.html)，
1、是否可以指定序列化方法，Newtonsoft.Json 或 System.Text.Json；
2、使用 System.Text.Json情况下，如何解决Unicode编码问题

**Comment by xiangxiren** [comment]
CAP里序列化默认是使用的UTF8。
https://github.com/dotnetcore/CAP/blob/5c22096056f03897ba52efbd5c7b2ed6cacf03e9/src/DotNetCore.CAP/Serialization/ISerializer.JsonUtf8.cs

**Comment by yaodaibao** [comment]
你好，VS版本16.9.4，Net5， 5.0.3版本的DotNetCore.CAP.Kafka 中文默认也会被Unicode编码
一个简单的aspnet core api示例
        [HttpGet]
        public void Get()
        {
            _capPublisher.Publish("logstash", "测试信息");
        }


Published表里面的Content信息
{"Headers":{"cap-callback-name":null,"cap-msg-id":"1394576188706271232","cap-corr-id":"1394576188706271232","cap-corr-seq":"0","cap-msg-name":"logstash","cap-msg-type":"String","cap-senttime":"2021/5/18 16:50:48 \u002B08:00"},"Value":"\u6D4B\u8BD5\u4FE1\u606F"}

**Comment by yaodaibao** [comment]
> CAP里序列化编码默认是使用的UTF8。
> https://github.com/dotnetcore/CAP/blob/5c22096056f03897ba52efbd5c7b2ed6cacf03e9/src/DotNetCore.CAP/Serialization/ISerializer.JsonUtf8.cs
> 
> 能否提供一下你的测试环境配置及示例

你好，VS版本16.9.4，Net5， 5.0.3版本的DotNetCore.CAP.Kafka 中文默认也会被Unicode编码
一个简单的aspnet core api示例
[HttpGet]
public void Get()
{
_capPublisher.Publish("logstash", "测试信息");
}

Published表里面的Content信息
{"Headers":{"cap-callback-name":null,"cap-msg-id":"1394576188706271232","cap-corr-id":"1394576188706271232","cap-corr-seq":"0","cap-msg-name":"logstash","cap-msg-type":"String","cap-senttime":"2021/5/18 16:50:48 \u002B08:00"},"Value":"\u6D4B\u8BD5\u4FE1\u606F"}

**Comment by yang-xiaodong** [comment]
Fixed in 5.1.0-preview-138879827
