### ISSUE TITLE
Sharded database support

### ISSUE THREAD

**Issue by alewmt** [dotnetcore/CAP#878]
Hi!
Does CAP supports reliable outbox with a sharded database? All data affected by a single transaction always resides on one shard and it is necessary that CAP also uses this shard to work with messages and does not use distributed transaction.

**Comment by yang-xiaodong** [comment]
Can you explain what is sharded database and your understanding of distributed transactions？

**Comment by alewmt** [comment]
I mean [this](https://en.wikipedia.org/wiki/Shard_(database_architecture)) and [this](https://en.wikipedia.org/wiki/Distributed_transaction)
I can decide which database shard to use by user id, but what does working with CAP look like in this case?

**Comment by yang-xiaodong** [comment]
Not support sharded database, this ability provided by the database, CAP is a library and not use XA to impl distributed transaction.
 
Architecture here:
https://github.com/dotnetcore/CAP#architecture-overview
