### ISSUE TITLE
同时引用MySql PostgreSql SqlServer的包， CapOptionsExtensions.UseEntityFramework无法使用

### ISSUE THREAD

**Issue by tirongaws** [dotnetcore/CAP#88]
MySql PostgreSql SqlServer的库中对CapOptions都进行了EntityFramework的扩展，
扩展方法都是`UseEntityFramework`
命名空间都是` Microsoft.Extensions.DependencyInjection`
当同时应用 MySql PostgreSql SqlServer库，UseEntityFramework就无法使用

**Comment by yuleyule66** [comment]
设计如此，没有考虑一个应用多个CAP库的情况

**Comment by tirongaws** [comment]
UseEntityFramework<TContext>如果直接改成 UseMySql<TContext>、UsePostgreSql<TContext>、UseSqlServer<TContext>，我觉得也挺清楚的，毕竟有TContext的约束就能知道是用EF

**Comment by tirongaws** [comment]
我开发的应用需要同时支持SQL Server和MySQL，虽然可以绕着解决，不过也是比较痛苦的

**Comment by yuleyule66** [comment]
@tirongaws 正常情况下，不会有人这么用啊。。。

**Comment by yuleyule66** [comment]
同使支持并不代表会同时使用两个库， 你们是同时使用两个数据库？

**Comment by tirongaws** [comment]
不会同时用两个库，是想通过配置来做的  
可能通过代码分支来做更好，我也有点犹豫

**Comment by tirongaws** [comment]
如果用配置的方式，虽然不会同时用，但是库都是引用了，这样就比较头疼了

**Comment by yuleyule66** [comment]
做成两个项目呀，提供nuget出去就行了

**Comment by tirongaws** [comment]
不管设计如何，从代码角度讲 UseEntityFramework这个扩展方法命名还是有瑕疵的
使用UseXXXEntityFramework似乎更好
