### ISSUE TITLE
Autofac registration is not convenient enough

### ISSUE THREAD

**Issue by WillardHan** [dotnetcore/CAP#884]
Then register your class that implements ISubscriberService in Startup.cs

public void ConfigureServices(IServiceCollection services)
{
    //Note: The injection of services needs before of `services.AddCap()`
    services.AddTransient<ISubscriberService,SubscriberService>();

    services.AddCap(x=>
    {
        //...
    });

这里的ISubscriberService注册必须在AddCap之前，而Autofac的注册是写在ConfigureContainer里的，也就是在ConfigureServices执行完了之后才会注册，所以我想依靠Autofac去批量注册是行不通，所以只能靠.net core自带的DI去批量注册了，稍微有点不方便。

**Comment by yang-xiaodong** [comment]
Hello , You can override the `FindConsumersFromInterfaceTypes` method to custom consumer lookup

https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs#L71

**Comment by yang-xiaodong** [comment]
你好，我们已经在5.1.4版本中支持从程序集中注册消费者，见 https://github.com/dotnetcore/CAP/issues/993
