### ISSUE TITLE
Add support for OpenTelemetry

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnetcore/CAP#885]
According to the proposal of #858, currently we have provided support for SkyWalking, and then we need to consider whether to provide direct support for OpenTelemetry

#### Reference link:

Opentelemetry client:
https://github.com/open-telemetry/opentelemetry-dotnet

.NET Metrics :
https://github.com/dotnet/designs/blob/main/accepted/2021/System.Diagnostics/Metrics-Design.md

**Comment by devgig** [comment]
Any updates on Open Telemetry support?

**Comment by modabas** [comment]
Open telemetry support would be great.

**Comment by yang-xiaodong** [comment]
Fixed in v6.0
