### ISSUE TITLE
The service receives the message twice

### ISSUE THREAD

**Issue by kvandake** [dotnetcore/CAP#886]
Hello!

When I use two instance of the service (kubernates) the service processed a message twice because each instance of the service receives produced messages from storage.
Do I must use [discover function](https://cap.dotnetcore.xyz/user-guide/en/monitoring/consul/)?

1. any version
2. Storage - Postgres
3. Kubernates with two instance of service

**Comment by yang-xiaodong** [comment]
Hello, this is an unexpected behavior, you need to confirm that your two instances are in the same Group?

**Comment by yang-xiaodong** [comment]
No response , close
