### ISSUE TITLE
Pending message has not been deleted from buffer list in SQL Server

### ISSUE THREAD

**Issue by sanmuTHINK** [dotnetcore/CAP#889]
using (var transction = connection.BeginTransaction(_cap))
                {
                    await _cap.PublishAsync("test", param);
throw new Exception("xxx");
                              }
这种情况 publish消息之后的业务出现错误，出现事务rollback，但是 _bufferList 并不会移除消息。 导致 正常commit之后本应移除的，会继续EnqueueToPublish。
设计如此吗? 应该如何去处理. 
1. 重写 Dispose(),在里面rollback() 
2. 在 DiagnosticObserver 增加WriteTransactionRollbackAfter 去移除_bufferList  是否可以???

**Comment by yang-xiaodong** [comment]
In fact, we will delete the pending message from the buffer list when the transaction commit fails. 

Is it not working properly now?  Can you help us test if this is working properly, thank you!

https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.SqlServer/Diagnostics/DiagnosticObserver.cs#L54

**Comment by yang-xiaodong** [comment]
@sanmuTHINK  Any feedback?

**Comment by sanmuTHINK** [comment]
我测试环境是 sqlserver+Dapper .测试OK的.&nbsp;


问题：


sqlserver 使用连接池的情况.
&nbsp; 事务RollBack()时, 但是并没有移除 持久化消息队列_bufferList， 此时 connection释放到 连接池;
&nbsp;下次在连接池取connection时 ,会获取上次connection. 导致 _bufferList 里的数据多了上次未移除的。




方案：
1. 禁用连接池
2.rollback时 移除_bufferList


以下是我的思路:


1. ICapTransaction.Sqlserver 175行 BeginTransaction()&nbsp;返回 IDbTransaction对象.&nbsp;其他数据库 BeginTransaction()&nbsp;返回ICapTransaction对象.&nbsp;
这个是否是个BUG? 我修改了此处


2. 事务提交之后,增加一个已提交事务Completed=true;&nbsp;Dispose()时 , 如果 !Completed 则增加Rollback().&nbsp;
&nbsp;DiagnosticObserver 就能得到 Microsoft.Data.SqlClient.WriteTransactionRollbackAfter 这个key。 从而对_bufferList 移除消息队列。


&nbsp;我是菜鸟， 代码仅供参考 ，无需合并。&nbsp;&nbsp;


期待大佬能有更优秀的代码 ，更新解决这个问题。&nbsp;&nbsp;










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/CAP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月26日(星期三) 下午4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/CAP] Pending message has not been deleted from buffer list in SQL Server (#889)





 
@sanmuTHINK  Any feedback?

**Comment by yang-xiaodong** [comment]
我用中文吧，我感觉你没有明白我的意思。 
我是指 SqlErrorCommitTransactionMicrosoft 这个事件的判断条件被触发吗？ 理论上应该事务提交失败了会进到这个判断条件里面来，然后这个里面会移除_bufferList中未被发布的消息

**Comment by sanmuTHINK** [comment]
感谢大佬回复. 我英文不自信,怕描述不清


我的事务AutoCommit=false , 事务内出现异常, 并没有触发commit(),&nbsp;
断点调试,发现没有触发 SqlErrorCommitTransactionMicrosoft。 所以我才会发现这个问题 .&nbsp;


我看SqlClient 源码 ,WriteTransactionCommitError也是只在commit()时触发&nbsp; .








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dotnetcore/CAP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月26日(星期三) 晚上8:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dotnetcore/CAP] Pending message has not been deleted from buffer list in SQL Server (#889)





 
我用中文吧，我感觉你没有明白我的意思。
 我是指 SqlErrorCommitTransactionMicrosoft 这个事件的判断条件被触发吗？ 理论上应该事务提交失败了会进到这个判断条件里面来，然后这个里面会移除_bufferList中未被发布的消息

**Comment by yang-xiaodong** [comment]
你好，感谢反馈，这是一个bug。

目前已经在  https://github.com/dotnetcore/CAP/commit/3f590dc848447c0c4d9508c11a0bba33c55f650e 中修复，最好是在连接关闭的时候清理buffer, 感谢你提交的PR

**Comment by yang-xiaodong** [comment]
Fixed in 5.1.0-preview-138879827
