### ISSUE TITLE
CapSubscribe Group Not Work 

### ISSUE THREAD

**Issue by s995203** [dotnetcore/CAP#89]
Group not working when use kafka
It's always DoSomthing1 or DoSomthing2

        [CapSubscribe("users.added", Group = "user.doSomthing1")]
        public void DoSomthing1(User user)
        {
            // somthing here...
        }

        [CapSubscribe("users.added", Group = "user.doSomthing2")]
        public void DoSomthing2(User user)
        {
            // somthing here...
        }

I think it's because async task use same setting object, and not lock correctly

DotNetCore.CAP.Kafka.KafkaConsumerClient

        private void InitKafkaClient()
        {
            _kafkaOptions.MainConfig["group.id"] = _groupId;

            var config = _kafkaOptions.AsKafkaConfig();
            _consumerClient = new Consumer<Null, string>(config, null, StringDeserializer);
            _consumerClient.OnConsumeError += ConsumerClient_OnConsumeError;
            _consumerClient.OnMessage += ConsumerClient_OnMessage;
            _consumerClient.OnError += ConsumerClient_OnError;
        }

Maybe should be

        private void InitKafkaClient()
        {
            lock (_kafkaOptions)
            {
                _kafkaOptions.MainConfig["group.id"] = _groupId;

                var config = _kafkaOptions.AsKafkaConfig();
                _consumerClient = new Consumer<Null, string>(config, null, StringDeserializer);
                _consumerClient.OnConsumeError += ConsumerClient_OnConsumeError;
                _consumerClient.OnMessage += ConsumerClient_OnMessage;
                _consumerClient.OnError += ConsumerClient_OnError;
            }
        }

Or what have I misunderstood?

**Comment by yuleyule66** [comment]
Thanks for your report, I will check it later.

**Comment by yuleyule66** [comment]
@s995203  I agree with you. 
Because of KafkaOptions is a singleton, so there may be a thread safety issue here.
I will fixed it , thanks again.
