### ISSUE TITLE
Cap library help

### ISSUE THREAD

**Issue by BBanoth** [dotnetcore/CAP#890]
Sorry if i am asking dumb questions.

After going through docs i understand that CAP is used in some service which produces events, cap will store the events in the 
database and publishes the message to Message Broker and consume the events from Message Broker.

All the code(Storage, publishing and subscribing) is included in one service which might not need all the functionality.

In my case, service will just produce events, it will not use subscription part.

Can anyone suggest me on the below structure.

ServiceA - produces events and stores in db.
ConsoleApp1(background) - Reads the events from db and publishes to Message Broker.
ConsoleApp2(background) - Subscribes to Message Broker and consumes the events.

Now if i want to use CAP here, I will need 
           1.  CAP.Storage package to save data in **ServiceA**
           2.  CAP.Publisher package to only read the events table and publishes to Message Broker in **ConsoleApp1**
           3.  CAP.Subscriber package to consume events from Message Broker in **ConsoleApp2**

Is this kind of approach is good ? If yes how can i use CAP to achieve it ?

**Comment by yang-xiaodong** [comment]
Hello,

After the CAP is stored in the DB, the message will be placed in the buffer area instead of being read from the DB again, so why not put the behavior of ConsoleApp1 directly in ServiceA ?
