### ISSUE TITLE
When are database storage tables created?

### ISSUE THREAD

**Issue by zemien** [dotnetcore/CAP#892]
We are using SQL Server as our storage option.

We are having an issue whereby the cap tables are not being created, but at the same time no exception is being thrown.

I would like to understand when the tables are created in the app lifecycle? Is it:

1. during startup, as soon as I call .UseSqlServer()?
2. At the point of receiving or publishing the first message?
3. … or some other time?

we are still on CAP 2.6 but hopefully that behaviour hasn’t changed much. 

And is there a way to turn on internal debugging?

Thank you.

**Comment by yang-xiaodong** [comment]
Hello, 

Database table created at startup, you can view the script here

https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.SqlServer/IStorageInitializer.SqlServer.cs#L36
