### ISSUE TITLE
cap.dotnetcore.xyz is not accessible and not Https

### ISSUE THREAD

**Issue by usamakhalil86** [dotnetcore/CAP#897]
http://cap.dotnetcore.xyz/ is nort accessible.

please host the docs on accessible domain and use ssl

**Comment by xiangxiren** [comment]
I can access normally

**Comment by yang-xiaodong** [comment]
Hello, 

The site is working fine, see https://www.webpagetest.org/result/210601_AiDcYD_a4240b2aab4582fa67f01237f8b4a0b0/
