### ISSUE TITLE
Time from Added (Published) to Added(Received) is long

### ISSUE THREAD

**Issue by KayakFisher205** [dotnetcore/CAP#899]
I have a simple class setup to Subscribe to the Messages which connect to RabbitMQ. I have procedures for each message type. The partial code is below.
Watching the program run and monitoring the database, there is a delay from publishing to 'processing'. Its easy to see by the Added fields of the Published and Received table. Below is a screen shot. There is somewhere between a 4 or 5 min delay. I couldn't find a setting to set a schedule to look for messages to processes. I was thinking when subscribing, any new messages auto trigger a call. I wasn't sure if I need to name each procedure different, put each one in their own class and set those classes as individual Transients or now. For the project I'm working on, I need at least 1 minute response from publishing to receiving. I wasn't sure if that was how RabbitMQ was set, something I was going wrong, or just have CAP Works. 

![image](https://user-images.githubusercontent.com/71768711/120346884-668e2380-c2c1-11eb-849a-0f3fd2f0e561.png)

**Program.cs snippet**
services.AddCap(x =>
                {
                    //console app does not support dashboard
                    x.FailedRetryCount = 5;
                    x.FailedThresholdCallback = failed =>
                    {
                        var logger = failed.ServiceProvider.GetService<ILogger<Program>>();
                        logger.LogError($@"A message of type {failed.MessageType} failed after executing {x.FailedRetryCount} several times, 
                        requiring manual troubleshooting. Message name: {failed.Message.GetName()}");
                    };
                    x.UseSqlServer(f =>
                    {
                        f.ConnectionString = "Removed for Security";
                    });
                    x.UseRabbitMQ(z =>
                    {
                        z.HostName = "Removed for Security";
                        z.UserName = "Removed for Security";
                        z.Password = "Removed for Security";
                        z.ExchangeName = "Removed for Security";
                    });
                });

**Class**
    public class ProgramLogReceiver : IProgramLogReceiver, ICapSubscribe
    {

        private readonly ILogger<ProgramLogReceiver> _logger;

        public ProgramLogReceiver(ILogger<ProgramLogReceiver> logger)
        {
            _logger = logger;
        }

        [CapSubscribe("CasterReport")]
        public void CasterReport(PsiSend value)
        {
            Console.WriteLine($"CasterReport- Message_ID:{value.Message_IdAuto}");
            _logger.Log(LogLevel.Debug, value.Message_IdAuto.ToString());
        }

        [CapSubscribe("CasterStatus")]
        public void CasterStatus(PsiSend value)
        {
            Console.WriteLine($"CasterStatus- Message_ID:{value.Message_IdAuto}");
            _logger.Log(LogLevel.Debug, value.Message_IdAuto.ToString());
        }

**Comment by KayakFisher205** [comment]
I forgot to add, this a run with a program that runs all the time, so I wasn't sure it I to have the program run and shutdown on a schedule.

**Comment by KayakFisher205** [comment]
I have been today. If the publisher is running in one program (winform
calling an transient class) and the subscriber in a console app (same
machine), it's just about 4.1 minutes from publish to subscriber receiving.
I added a transient class within the console app and with the publisher
code. When the publisher runs, almost immediately the subscriber runs. Both
projects connects to the same set of tables on the same database. RabbitMQ
runs on a remote machine and both projects point to the same exchange. I
have not see any sample code with the publisher and subscriber being
separate but from the models that's how I would expect it. It's quite
possible I've set up something wrong but so far, I haven't found it.

**Comment by yang-xiaodong** [comment]
> Can you confirm that your consumer execution takes a lot of time

I mean the execution time of the subscription method, But now it seems to be due to the message sent by the retrying process, It will pick up and send the message 4 minutes after it is added to the database

If your publisher or subscriber is not in ASP.NET Core, you need to using `BootstrapAsync()` to start a long-running background process,  see the https://github.com/dotnetcore/CAP/issues/860#issuecomment-838020712

**Comment by KayakFisher205** [comment]
I have that in the subscriber console app. Does it need to be in the
publisher too, if it's separate? If so, I can try that tomorrow.

**Comment by yang-xiaodong** [comment]
Publisher not need `BootstrapAsync()`,  so I created a .net core WinForm application to test and it works without delay.

Here is my code:

**Program.cs**

```C#
static class Program
{
    public const string ConnectionString = "server=xxx;port=xxx;database=cap;UserId=xxx;Password=xxx;";

    /// <summary>
    ///  The main entry point for the application.
    /// </summary>
    [STAThread]
    static void Main()
    {
        Application.SetHighDpiMode(HighDpiMode.SystemAware);
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);

        var services = new ServiceCollection();
        services.AddLogging();
        services.AddCap(x =>
        {
            x.UseMySql(ConnectionString);
            x.UseRabbitMQ(opt =>
            {
                opt.ConnectionFactoryOptions = factory =>
                {
                    factory.UserName = "xxx";
                    factory.Password = "xxx";
                    factory.HostName = "xxx";
                };
            });
        });

        services.AddTransient<Form1>();

        var sp = services.BuildServiceProvider();

        Application.Run(sp.GetRequiredService<Form1>());
    }
}
```

**Form1.cs**

```C#
public partial class Form1 : Form
{
    private readonly ICapPublisher _capPublisher;

    public Form1(ICapPublisher _capPublisher)
    {
        this._capPublisher = _capPublisher;
        InitializeComponent();
    }

    private void button1_Click(object sender, EventArgs e)
    {
        _capPublisher.Publish("sample.rabbitmq.mysql", DateTime.Now);
    }
}
```

**Comment by KayakFisher205** [comment]
Maybe I figured out my issue.

In my publisher, I had 
                var psiMessage = new PsiSend();
                psiMessage.Id = id;
                psiMessage.MessageType = messageType;
                psiMessage.MessageArea = messageArea;
                psiMessage.MessageTime = DateTimeOffset.Now;
                
using var connection = new SqlConnection("Server=xxx;Database=xxx;User ID=readwrite;Password=xxx");
                using var transaction = connection.BeginTransaction(_capPublisher);
                // This is where you would do other work that is going to persist data to your database
                _capPublisher.Publish(queueName, psiMessage);
                transaction.Commit();

The row in [cap].[Published] would we written, but the StatusName would be Scheduled. After 4 minutes, the Subscriber would receive the message and it was marked succeeded.

The procedure for the publish is just a void, called by a BackgroundWorker every minute. I decided to remove the Publish command to its own procedure and I removed the transaction like below:

public async void PublishPsiMessage(string type, PsiSend psiMessage)
        {
            await _capPublisher.PublishAsync(type, psiMessage);
        }

In this case, the publisher and subscriber performed quickly, less than .1 sec. I don't know if I misunderstood the correct way or if there is some strange bug that I was triggering.

In any case, I think its working for me now. Thank you for your help.

You can close this at your leisure.

**Comment by yang-xiaodong** [comment]
In SQL Server, if use the transaction feature to send messages, you need to use `BootstrapAsync` to start the background thread . This is because we use the Diagnostic Listener to subscribe to the transaction commit event and publish the message. 

https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.SqlServer/Diagnostics/IProcessingServer.DiagnosticRegister.cs#L30
