### ISSUE TITLE
The message FailedRetryCount does not increase when raised SubscriberNotFoundException

### ISSUE THREAD

**Issue by DillonHuang** [dotnetcore/CAP#90]
消息订阅失败了，尝试的时候，如果发生异常
`DotNetCore.CAP.Internal.SubscriberNotFoundException`
Retries没有增加，这样这个消息就会一直被尝试发给订阅者

不知道是不是特意这么设计的

**Comment by yuleyule66** [comment]
这个不是特意设计的，这是一个Bug，稍后我会修复它。

谢谢你的反馈。

**Comment by yuleyule66** [comment]
closed, fixed in version 2.1.4.
