### ISSUE TITLE
Minor problems in Load testing of CAP

### ISSUE THREAD

**Issue by albertopm19** [dotnetcore/CAP#902]
Hi,

we are load testing cap to include it in our services.

The librarys is great !!! but we are found some problem load testing....

When we generate millions of events, we have found timeout errors in IMonitoringApi.SqlServer.cs

We have changed this to raise Comand Timeout.

IDbConnection.Extensions.cs

In ExecuteReader and ExecuteScalar we changed:

After  using var command = connection.CreateCommand();
we add            command.CommandTimeout = 300;

And it Works!!!

We don't know if there is a better way of change this adding one more option to cap to control command timeout??.

Thanks!!!

**Comment by yang-xiaodong** [comment]
Hello,

Usually the timeout option can be configured in the database connection string

https://mysqlconnector.net/connection-options/#DefaultCommandTimeout

**Comment by albertopm19** [comment]
thanks for your reply perhaps is true in MySql but in SqlServer I haven't found the way to put this in the connection string

**Comment by yang-xiaodong** [comment]
It looks like that `Microsoft.Data.SqlClient` is already supported  `Command Timeout`

https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/tests/FunctionalTests/SqlConnectionTest.cs#L729

https://erikej.github.io/sqlclient/2020/10/26/sqlclient-commandtimeout-preview.html

**Comment by albertopm19** [comment]
you guys are incredible :)  thanks for your quick support !!!

Yes i have tried this but my config is: 

 services.AddCap(x =>
            {
                x.UseEntityFramework<AppDbContext>();
                //x.UseRabbitMQ("");
                x.UseKafka("mykafkaserver.es:xxxx");
                x.UseDashboard(opt => {
                    opt.PathMatch = "/cap";
                    opt.PathBase = Configuration["PATH_BASE"];
                });
                x.FailedRetryCount = 5;
                x.ConsumerThreadCount = 2;
                x.ProducerThreadCount = 5;
                x.FailedThresholdCallback = failed =>
                {
                    var logger = failed.ServiceProvider.GetService<ILogger<Startup>>();
                    logger.LogError($@"A message of type {failed.MessageType} failed after executing {x.FailedRetryCount} several 
                    times, 
                        requiring manual troubleshooting. Message name: {failed.Message.GetName()}");
                };
                //x.JsonSerializerOptions.Encoder = JavaScriptEncoder.Create(UnicodeRanges.All);
            });

We are using entity framework and if we put in the connection string this option: 
"Data Source=192.168.0.205,30877;Initial Catalog=pruebacap;Persist Security Info=True;User ID=sa;Password=xxxxxxxxxx;Command Timeout=300"

we have this error:

◢ | $exception | {System.ArgumentException: Keyword not supported: 'command timeout'.    at Microsoft.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)    at Microsoft.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)    at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString)    at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)    at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions&amp; userConnectionOptions)    at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)    at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value)    at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetDbConnection(DatabaseFacade databaseFacade)    at DotNetCore.CAP.ConfigureSqlServerOptions.Configure(SqlServerOptions options) in C:\apps\pruebas\CAP-master\CAP-master\src\DotNetCore.CAP.SqlServer\CAP.SqlServerOptions.cs:line 36    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)    at Microsoft.Extensions.Options.OptionsManager`1.&lt;&gt;c__DisplayClass5_0.&lt;Get&gt;b__0()    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)} | System.ArgumentException

**Comment by albertopm19** [comment]
Sorry I didn't see your comment: The Command Timeout feature is supported in Microsoft.Data.SqlClient version 2.1.0, CAP currently uses 2.0.1, Need to reference high version assembly

I'm testing now.....

**Comment by albertopm19** [comment]
ok, I tested and now works very well.  with

"Data Source=192.168.0.205,30877;Initial Catalog=pruebacap;Persist Security Info=True;User ID=sa;Password=xxxxxxxxxx;Command Timeout=300"

In my service i added Microsoft.Data.SqlClient 2.13 

I will test to improve timings adding indexes (I have now 5-6 million of records :))

Thank you very much ¡¡¡¡ :)
