### ISSUE TITLE
How to verify that consumerthreadcount works

### ISSUE THREAD

**Issue by knowyi** [dotnetcore/CAP#903]
Hello, I want to open more consumer terminals to improve parallel efficiency. I set consumerthreadcount, but it doesn't seem to work. I don't see multiple consumers in the tool
![image](https://user-images.githubusercontent.com/7392434/120991724-7d96af00-c7b4-11eb-961d-55f602dd2f43.png)

[captest.zip](https://github.com/dotnetcore/CAP/files/6607589/captest.zip)

**Comment by knowyi** [comment]
![image](https://user-images.githubusercontent.com/7392434/120992679-6a381380-c7b5-11eb-926f-00916b9878d1.png)
From the execution result, the serial execution is not parallel

**Comment by knowyi** [comment]
![image](https://user-images.githubusercontent.com/7392434/120993018-bd11cb00-c7b5-11eb-9dca-d2c6c16abff8.png)
This is the code I set. The test code has been uploaded

**Comment by yang-xiaodong** [comment]
Since consumers are in the same consumer group, it depends on how the default kafka partitioner routes messages to different partitions. CAP uses snowflake to generate kafka keys by default.

**Comment by knowyi** [comment]
I have another question. I have deployed the same application on two machines for testing and sent 1000 pieces of data in batches, but all consumption is only on one machine. When I close one server application, another server can consume. Is this the problem of setting

**Comment by knowyi** [comment]
@yang-xiaodong I have another question. I have deployed the same application on two machines for testing and sent 1000 pieces of data in batches, but all consumption is only on one machine. When I close one server application, another server can consume. Is this the problem of setting

**Comment by knowyi** [comment]
> > Is this the problem of setting
> 
> No, when the number of consumers is greater than the number of partitions, some consumer will be idle

@yang-xiaodong So I can improve throughput by adjusting the number of partitions, right?

**Comment by yang-xiaodong** [comment]
Yes

**Comment by knowyi** [comment]
I got it，thank you @yang-xiaodong
