### ISSUE TITLE
Dashboard - Misspelling

### ISSUE THREAD

**Issue by KayakFisher205** [dotnetcore/CAP#904]
In the 5.1.0 Version, the name in the header is misspelled (CAP Dashbaord). I found it was spelled that way in Navigation.vue, and in the app.c7691be8.js
![Screenshot 2021-06-07 121124](https://user-images.githubusercontent.com/71768711/121061486-82923900-c789-11eb-950e-f41c8e4d944b.png)

**Comment by yang-xiaodong** [comment]
Fixed in `5.1.1-preview-140603701`
