### ISSUE TITLE
[Feature request] Middleware for Subscribers

### ISSUE THREAD

**Issue by matt-psaltis** [dotnetcore/CAP#905]
Hi,

We're using CAP with Kafka messaging. When creating ICapSubscribers, we would like to automatically wrap the Handle method in a Entity Framework Transaction scope so that message handlers do not need to add as much boilerplate code. So far I haven't found an elegant way of introducing additional pre and post steps into the subscriber execution pipeline without using proxies or compile time decorators.

Does this functionality already exist or is this a new feature request?

**Comment by yang-xiaodong** [comment]
Hello, Is the subscribe filter what you need?

https://github.com/dotnetcore/CAP/pull/894

**Comment by matt-psaltis** [comment]
Wow timing! That looks like it will do the trick thank you! Would you consider switching the Method signatures on ISubscribeFilter to be async?

Cheers.

**Comment by matt-psaltis** [comment]
The ISubscribeFilter works well for wrapping the subscription handler in a transaction scope. We would also like to add Idempotency concepts to the ISubscribeFilter which would require returning a value from the OnSubscribeExecuting method so that https://github.com/dotnetcore/CAP/blob/55cc2c0a3fefca4c171233b6c67d3441035fa314/src/DotNetCore.CAP/Internal/ISubscribeInvoker.Default.cs#L103 does not execute.

Is this something you would be open to a PR for including a signature change to ISubscribeFilter?

Example:

```
public enum SubscribeFilterResult {
   Continue = 0,
   Abort
}

public interface ISubscribeFilter {
  ValueTask<SubscribeFilterResult> OnSubscribeExecutingAsync(ExecutingContext context, CancellationToken cancellationToken);
  ValueTask OnSubscribeExecutedAsync(ExecutingContext context, CancellationToken cancellationToken);
  ValueTask OnSubscribeExceptionAsync(ExecutingContext context, CancellationToken cancellationToken);
}
```

**Comment by yang-xiaodong** [comment]
You can use class-scoped variables to store the OnSubscribeExecuting return value, which is thread-safe.

You can throw an exception in OnSubscribeExecuting to terminate subscriber execution, and set ExceptionHandled = true in OnSubscribeException
