### ISSUE TITLE
Authentication dashboard.

### ISSUE THREAD

**Issue by horseznguyen** [dotnetcore/CAP#906]
Hi,

When After upgrading from 5.0.3 to 5.1.0, I cannot find IDashboardAuthorizationFilter class to configure authentication.

![Untitled](https://user-images.githubusercontent.com/28267489/121838333-c8a74980-cd01-11eb-8d8c-94b193dcf724.png)

How to configure it?

**Comment by yang-xiaodong** [comment]
Hello, we have used the new Dashboard in 5.1.0, but we have not had time to update our documentation.

In version 5.1.1, we have followed the authentication way of ASP.NET Core and provided authentication based on AuthenticationScheme. You can view the example here.  

https://github.com/dotnetcore/CAP/tree/master/samples/Sample.Dashboard.Auth

**Comment by yang-xiaodong** [comment]
Fixed in `5.1.1-preview-140603701`

**Comment by horseznguyen** [comment]
Hi @yang-xiaodong,

In my project, I'm using Token-Base authentication to handle authentication so how to configure dashboard authentication with the current one.

**Comment by yang-xiaodong** [comment]
Hello, 

You can see https://github.com/dotnetcore/CAP/blob/master/samples/Sample.Dashboard.Auth/MyDashboardAuthenticationHandler.cs#L26
and
https://cap.dotnetcore.xyz/user-guide/en/monitoring/dashboard/#custom-authentication

Simply put, define your Scheme, then customize the AuthenticationHandler for this Scheme, and handle the work in `HandleAuthenticateAsync()`
