### ISSUE TITLE
Increase processing flow for message `Processing` state about the message process tiemout

### ISSUE THREAD

**Issue by DillonHuang** [dotnetcore/CAP#91]
消息statusname=Failed时，会被重新处理
如果是statusname=Processing就不会，是不是对Processing设置一个Timeout
这样的会把 statusname=Processing 并且timeout了的消息再处理一次

**Comment by yuleyule66** [comment]
我稍后会考虑一下你的这个提议。 
谢谢反馈

**Comment by yuleyule66** [comment]
@DillonHuang 近期准备开发这个特性了
