### ISSUE TITLE
DotnetCAP > Subscribers sometimes do not consume and queue is accumulating.

### ISSUE THREAD

**Issue by omeerkorkmazz** [dotnetcore/CAP#918]
Hi @yang-xiaodong,

We sometimes face a likely edge-case problem. We have consumers that developed via dotnet core web API. They are served on the cloud with CI/CD pipeline.

We made a deployment a week ago and everything was fine. However, our consumers that listen to RabbitMQ started to stop consuming suddenly. We still publish the messages successfully. We also see the messages in the queues when monitoring the RabbitMQ Management Dashboard (e.g, message rates and queued messages). 

The only solution for this problem is _**to rebuild and redeploy**_ them. Then, they again consume the messages successfully. In addition, we analyzed the errors thrown by DotnetCAP, but we could not find the core problem exactly.

![Screen Shot 2021-06-23 at 22 21 59](https://user-images.githubusercontent.com/29013117/123159047-362b4680-d475-11eb-834d-6edfaa934d06.png)

Do you have any idea about this problem? What do you think if we upgrade the DotnetCAP version to 5.1.0?

Our configurations
Consumers: Dotnetcore 5.0 WebAPI
DotnetCAP: version 5.0.3

**Comment by yang-xiaodong** [comment]
Hi @hetaoos, What do you think about this issue?

**Comment by hetaoos** [comment]
@omeerkorkmazz Hi, the problem is similar to #861.
how many connections are in the **Connections** tab of RabbitMQ Management Dashboard?
The figure below is the correct state, each node has only one connection, and each connection has multiple channels. 
![image](https://user-images.githubusercontent.com/1094462/123187809-6f8fa080-d4cd-11eb-8294-46bea77eb786.png)

**Comment by omeerkorkmazz** [comment]
hi @hetaoos,

Thank you so much for your reply. We recognized that we have lots of connections. The reason was regarding the dependency injection lifetime. We changed lifetime to **_singleton_** and the problem was solved.
