### ISSUE TITLE
When Consumers have a lot of unread messages, readiness and liveness give not 200 status code to kubernates

### ISSUE THREAD

**Issue by kvandake** [dotnetcore/CAP#919]
Our services restart every time when the service will start and read a lot of unread messages from kafka, because the service gives not 200 status code to kubernates and kubernates restart the service. After that all repeat. Our message from kafka don`t have errors, but takes a lot of CPU, memory.

Consumers: ASP.NET Core
DotnetCAP: version 5.0.3

**Comment by kvandake** [comment]
May be move consumers to HostedService?

**Comment by yang-xiaodong** [comment]
What is your question?   "takes a lot of CPU, memory" or "not 200 status code to kubernates" ?

**Comment by kvandake** [comment]
The messages from kafka are processed before the service starts.

**Comment by kvandake** [comment]
When the messages are processing, kubernates try to send readiness and liveness and get not 200 status code.

**Comment by kvandake** [comment]
My question - Can move consumers to Hosted Service?

**Comment by yang-xiaodong** [comment]
In ASP.NET Core, CAP uses `services.AddHostedService<Bootstrapper>();` to register to run in the background

**Comment by yang-xiaodong** [comment]
If you want to delay the start of CAP manually, you can do this

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddCap(x =>
    {
         // ...
    });

    var hostDescriptor = services.FirstOrDefault(x => x.ServiceType == typeof(IHostedService) 
    && x.ImplementationType.IsAssignableTo(typeof(IBootstrapper)));
    if (hostDescriptor != null)
    {
        services.Remove(hostDescriptor);
    }
}
```

```cs
public void Configure(IApplicationBuilder app)
{
    Task.Run(async () => {
        await Task.Delay(5000);
        await app.ApplicationServices.GetRequiredService<IBootstrapper>().BootstrapAsync(default);
    });
    // ...
}
```
