### ISSUE TITLE
version 5.1.0 cap/health 404

### ISSUE THREAD

**Issue by wwwu** [dotnetcore/CAP#920]
cap/health => cap/api/health  
Caused failed health check

https://github.com/dotnetcore/CAP/blob/c19a9988efde4bca83ec0d742c0b0de1b9379248/src/DotNetCore.CAP.Dashboard/CAP.BuilderExtension.cs#L42
https://github.com/dotnetcore/CAP/blob/55a2dcf028834f23d5799fe7ef51228cfe739971/src/DotNetCore.CAP.Dashboard/NodeDiscovery/INodeDiscoveryProvider.Consul.cs#L80

**Comment by wwwu** [comment]
由于INodeDiscoveryProvider原来的实现会依赖internal class CapCache
自己实现一个INodeDiscoveryProvider，无法使用CapCache，可能会造成一些小问题

**Comment by yang-xiaodong** [comment]
Would you like to submit a PR to fix it? @wwwu

**Comment by wwwu** [comment]
#921 @yang-xiaodong
