### ISSUE TITLE
大数据大业务异步消息处理问题

### ISSUE THREAD

**Issue by pzx60** [dotnetcore/CAP#922]
问题需求描述：
       使用cap rabbitmq  大量PublishAsync消息后，
       由于消费端业务处理速度不快导致CAP cap.received表中累积很多数据状态为Scheduled，
       只要代码一重新发布导致重试cap时定时扫描状态为Scheduled的数据执行业务消费的时特别慢
       如果消费端开了多台机器，会导致走重试机制时重复消费，有什么解决方法

**Comment by yang-xiaodong** [comment]
You can use `ConsumerThreadCount` option to start multiple threads. If this does not solve your problem, please make sure you use CAP in the correct scenario.

see: https://www.cnblogs.com/savorboard/p/cap-5-1.html#4890911

**Comment by pzx60** [comment]
> 您可以使用`ConsumerThreadCount`选项启动多个线程。如果这不能解决您的问题，请确保您在正确的场景中使用 CAP。
> 
> 见：[https](https://www.cnblogs.com/savorboard/p/cap-5-1.html#4890911) : [//www.cnblogs.com/savorboard/p/cap-5-1.html#4890911](https://www.cnblogs.com/savorboard/p/cap-5-1.html#4890911)

好的，那开启多个线程消费试一下，现在主要的问题是数据量太大了，消费端速度跟不上发布端.

**Comment by yang-xiaodong** [comment]
In addition, ensure that your consumers have executed for a long time

**Comment by pzx60** [comment]
> 另外，确保你的消费者已经执行了很长时间

你好，咨询下，如果我消费端开启了多个，数据库大量消息的状态为Scheduled，如果走了重试机制，是不是会导致重复消费问题

**Comment by yang-xiaodong** [comment]
Yes, if there are multiple instances, please ensure that consumers guarantees idempotence
