### ISSUE TITLE
what is the purpose of switch button in dashboard?

### ISSUE THREAD

**Issue by giorgilekveishvili-meama** [dotnetcore/CAP#925]
I have set up Node discovery with consule , every service passed health checks and all nodes are visible in CAP Dashboard, however when i click switch button it just highlights row and reloads page  is this right behaviour?

**Comment by yang-xiaodong** [comment]
Click the Switch button to switch to the target node, CAP will use a proxy to get the data of the node you switched to.

https://cap.dotnetcore.xyz/user-guide/en/monitoring/consul/

**Comment by giorgilekveishvili-meama** [comment]
when I switch , it still does not show published and succeeded messages of that node server

**Comment by yang-xiaodong** [comment]
Hello, Can you show your configuraiton, on my test it works well.

https://youtu.be/pI4f0UUfDYE

**Comment by giorgilekveishvili-meama** [comment]
```csharp
   var name = Dns.GetHostName(); // get container id
            var ip = Dns.GetHostEntry(name).AddressList.FirstOrDefault(x => x.AddressFamily == AddressFamily.InterNetwork);
            capOptions.UseDiscovery(d =>
            {
                d.MatchPath = "/check";
                d.DiscoveryServerHostName = configuration.GetValue<string>(DockerVariables.ConsulServer);
                d.DiscoveryServerPort = configuration.GetValue<int>(DockerVariables.ConsulServerPort);
                d.CurrentNodeHostName = ip.MapToIPv4().ToString();
                d.CurrentNodePort = 80;
                d.NodeId = $"{configuration.GetValue<string>(ASPVariables.ConsulServiceId)}-CAP";
                d.NodeName = $"{configuration.GetValue<string>(ASPVariables.ConsulServiceName)}";
            });
   ```
Lets take example of my two service , Identity.API and Company.API
Images:
[both services in consul](https://i.ibb.co/NC9P12b/Screenshot-2021-07-02-at-16-00-13.png)
[Example of service detail in consul company](https://i.ibb.co/2dv5Zqs/Screenshot-2021-07-02-at-16-00-17.png)

**Comment by yang-xiaodong** [comment]
Do you configure `capOptions.UseDashbaord(...)` ?  and the `PathMatch` of the dashboard option and the `MatchPath` of the discovery option are the same value?

**Comment by yang-xiaodong** [comment]
Please use the latest version (`5.1.1-preview-141622241`), I realized that we fixed a bug(#921) about health check six days ago.

**Comment by giorgilekveishvili-meama** [comment]
I changed packages and now i get exception on dashboard

ObjectDisposedException: Cannot access a disposed object. Object name: 'FileBufferingReadStream'.
Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ThrowIfDisposed()
Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.set_Position(long value)
Common.Logging.Services.Abstrations.RequestBodyCheckStrategy.GetRequestBodyAsync(HttpRequest request) in RequestBodyCheckStrategy.cs
Common.Logging.Services.Implementions.DefaultRequestBodyStrategy.GetRequestBodyWithoutSensitiveDataAsync(HttpRequest request) in DefaultRequestBodyStrategy.cs
Common.Logging.Services.Implementions.LoggerService.GetRequestBodyByContentTypeAsync(HttpRequest request) in LoggerService.cs
Common.Logging.Services.Implementions.LoggerService.LogAsync(string shortMessage, string FullMessage, LogType logtype) in LoggerService.cs
Common.Middlewares.Middlewares.AuthenticationMiddleware.InvokeAsync(HttpContext httpContext, ILoggerService loggerService, IAuthenticatedCompaniesService authenticationWithCompaniesService) in AuthenticationMiddleware.cs
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by yang-xiaodong** [comment]
This exception does not seem to be related to CAP

**Comment by giorgilekveishvili-meama** [comment]
this exception happens when i click switch button and node id is assigned to cookie

**Comment by yang-xiaodong** [comment]
Hello, we can't reproduce your issue,  I close now. 

You can use the source code to debug to help us track the issue or submit a PR to help improve
