### ISSUE TITLE
Question about consumer group in microservice

### ISSUE THREAD

**Issue by suichuan** [dotnetcore/CAP#926]
您好,同一个微服务部署了多份,都要收到广播信息,订阅者组要怎么设置呢,[CapSubscribe("xxx.services.show.time", Group = "group1" )]  Group并不能设置动态值或随机值,望解答

**Comment by yang-xiaodong** [comment]
通常情况下，一个服务拥有多个实例是只需要其中一个实例来消费消息的。如果你的场景特殊，你可以在实例启动时，通过向 DefaultGroupName 选项中指定动态值（如环境变量）来达到这一目的。

Normally, a service has multiple instances and there is only one instance is needed to consume messages. If your scenario is special, you can achieve this goal by specifying dynamic values (such as environment variables) in the DefaultGroupName option when the instance startup.

```
services.AddCap(x =>
  {
      // DefaultGroupName  默认值为程序集名称，你可以在此指定
      x.DefaultGroupName = Environment.GetEnvironmentVariable("Group");
  });
```

友情提醒：请再次确认你的需求设计是否合理，因为在我看来这个需求是不合理的。

**Comment by neozhu** [comment]
随机动态 在Publish/Subscribe 确实不多见，一个发布多个订阅这本身就是支持的

**Comment by alexpee** [comment]
Hi , I have a subscriber service that running in multiple concurrent replica in K8s environment. If these replica instances are subscribing to the same topic and using same group id, can we guarantee the message will only be picked up by only one instance and process once only? Should I de-couple the listener to a singleton backgrounder process to avoid the racing condition?

Thank you

**Comment by yang-xiaodong** [comment]
>  Should I de-couple the listener to a singleton backgrounder process to avoid the racing condition?

I'm not understand what you mean?

**Comment by alexpee** [comment]
> > Should I de-couple the listener to a singleton backgrounder process to avoid the racing condition?
> 
> I'm not understand what you mean?

Is it better to run only one subscriber instance instead of multiple concurrently?

**Comment by yang-xiaodong** [comment]
No, decide whether to use multiple instances according your needs.

If you have the new question, please open a new issue so that we can focus on the issues discussed in this thread
