### ISSUE TITLE
After posting a large number of messages in a short time, the memory is not reclaimed

### ISSUE THREAD

**Issue by lxy0038** [dotnetcore/CAP#927]
使用官方Demo（net5.0, DotNetCore.CAP_5.1.0  RabbitMQ 3.8.11），部署到Docker中,在持续大并发发布消息一段时间后，停止发布消息。

问题：内存没有下降，CPU已经下降了。

**Comment by yang-xiaodong** [comment]
.NET Core 的服务器GC机制是这样的，短时间大量的内存申请，需要较长的时间回收。 请展示你的内存分配数据，以便于我们分析。 
请查看  https://github.com/dotnetcore/CAP/issues/816#issuecomment-813996571

**Comment by lxy0038** [comment]
监控的结果是对象MediumMessaged没有及时释放。
![m123](https://user-images.githubusercontent.com/6733487/124409969-0258f680-dd7c-11eb-8ce5-eed155989305.png)
![m1234](https://user-images.githubusercontent.com/6733487/124409971-038a2380-dd7c-11eb-8119-4a8ccb0358a2.png)

**Comment by yang-xiaodong** [comment]
@lxy0038 贴一下你的测试方式已经发布的代码

**Comment by lxy0038** [comment]
@yang-xiaodong  发布Order微服务的Docker的命令，dockerfile在代码里。 其他的项目也是类似的
docker build -t  order.service.image .
docker run -dit -p 5201:80 --name  order.service  order.service.image;


源码地址：https://github.com/lxy0038/MicroServiceDemo.git

![20210705134316](https://user-images.githubusercontent.com/6733487/124424426-94bbc300-dd99-11eb-8a8a-caeaf76e466c.png)
![20210705134434](https://user-images.githubusercontent.com/6733487/124424430-971e1d00-dd99-11eb-954d-80082bc7463f.png)

**Comment by yang-xiaodong** [comment]
你好，根据我的测试，没有问题哈。

我看你的截图，G1 G2 中有大量未回收，我推测内存中还有数据正在处理。

以下是我的监控数据，右键查看大图。

![image](https://user-images.githubusercontent.com/8205994/124452988-7fef2780-ddb9-11eb-8aa3-fbe73b65317a.png)

**Comment by yang-xiaodong** [comment]
你可以将访问修饰符改成 `public` ， 然后写一个 action 来打印数量，验证内存中数据是否都处理完。如果处理完了数量应该为 0

![image](https://user-images.githubusercontent.com/8205994/124453767-4965dc80-ddba-11eb-939c-02a8c462d2de.png)

**Comment by yang-xiaodong** [comment]
这张为最终快照内部的对象占用，一共 8.14M 的 .NET 对象.

![image](https://user-images.githubusercontent.com/8205994/124454614-45868a00-ddbb-11eb-9379-5faeee913281.png)

**Comment by yang-xiaodong** [comment]
在刚发送完毕后1.7G内存占用的进程，在一段事件后变为 68M

![image](https://user-images.githubusercontent.com/8205994/124455133-ca71a380-ddbb-11eb-851a-5e6fff06ee84.png)

**Comment by neozhu** [comment]
> 这张为最终快照内部的对象占用，一共 8.14M 的 .NET 对象.
> 
> ![image](https://user-images.githubusercontent.com/8205994/124454614-45868a00-ddbb-11eb-9379-5faeee913281.png)

what monitoring tools you are using to analyze memory?

**Comment by yang-xiaodong** [comment]
@neozhu  dotMemory : https://www.jetbrains.com/dotmemory/

**Comment by lxy0038** [comment]
@yang-xiaodong 你好，请问下你使用的测试代码方便提供吗？ 你是在那个环境下测试的？windown?linux?

**Comment by yang-xiaodong** [comment]
示例：[Sample.RabbitMQ.MySql](https://github.com/dotnetcore/CAP/tree/master/samples/Sample.RabbitMQ.MySql)
环境：Windows 10, RabbitMQ 3.8.2 ,  MariaDb 10.3
压力测试: wrk

压测脚本：`wrk -t 4 -c 100 -d 60 http://192.168.2.2:5000/without/transaction`

```
root@yxd-server03:~# wrk -t 4 -c 100 -d 60 http://192.168.2.2:5000/without/transaction
Running 1m test @ http://192.168.2.2:5000/without/transaction
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    55.45ms   75.74ms   1.25s    95.55%
    Req/Sec   559.49    256.84     1.50k    68.49%
  132296 requests in 1.00m, 11.61MB read
Requests/sec:   2202.65
Transfer/sec:    197.89KB
```

**Comment by lxy0038** [comment]
@yang-xiaodong  我在centos 7.0环境下进行压测，还是会出现内存泄漏的问题。在压测的过程中内存一直在涨。停止压测并且所有消息已消费，内存也没有释放。 请协助排查。
示例：Sample.RabbitMQ.MySql
环境：centos 7.0, RabbitMQ 3.8.11 , Mysql 8.0,docker 
压力测试: jmeter

![1](https://user-images.githubusercontent.com/6733487/124706463-e2ffcc00-df29-11eb-93b5-85d3fe51af81.png)

**Comment by yang-xiaodong** [comment]
这个我没办法协助你排查哈，我已经排查过了。只能你自己排查，项目都是开源的，你觉得代码哪里有问题可以指出

**Comment by yang-xiaodong** [comment]
@lxy0038 我突然意识到你可能对内存泄漏有一些误解，内存保持在一个范围是一个正常的行为，这是由复杂的GC回收策略决定的。

你可能认为程序启动后是100M内存，然后运行完一段任务之后内存还要回到100M才算是没有泄露。这个理解是错误的，最简单的是你可以新建一个控制台程序，然后循环创建一个对象N次来查看你循环之前和循环之后的内存值就明白了。

所以要测试内存是否泄露，要看内存值是否一直增长而不会减少最终导致OOM，图形的话是一个线性增加图形。

回到当前的用例，你可以在 Docker 启动时设置 --memory 参数为某个固定值，然后使用 jmeter 以一定的速率（不能太高否则会积压到内存）来长时间发送消息，看会不会导致内存溢出。 当然你要保证你的消费速度跟得上，要不然会出现消息挤压导致OOM。 你可以测试一晚上的时间，来观察内存会不会OOM就明白了。

写了这么长，希望你能明白。

**Comment by yang-xiaodong** [comment]
@lxy0038 试一下5.1.1版本，我们做了流控，会限制内存增长，但是并发会降低
