### ISSUE TITLE
How to get message details when the failure reaches the threshold count

### ISSUE THREAD

**Issue by carldai0106** [dotnetcore/CAP#929]
Hi guys,
Maybe this is a new requirement;
Is there a way when retries reached the limit , we can get  id from cap.published or cap.received. 
so I can got the message if the retries is reached the limit. then (Myself logic) I can sent a email or sms to staff to manual this message.
I already to get message id using ISubscribeFilter or CapHeader, but it is useless. It is a published message id, I want to get subscribed message id. 
Hope we can get id from publish or subscribe. Maybe we can use it to both.

**Comment by yang-xiaodong** [comment]
You can use `FailedThresholdCallback` option to get the message info

see https://cap.dotnetcore.xyz/user-guide/en/cap/configuration/#failedthresholdcallback

**Comment by carldai0106** [comment]
thanks, I got it.

**Comment by carldai0106** [comment]
I test this way, but it just got published id from subscriber. Could it expose subscribe id? When I got the sms or email, I can use the subscribe message id to get this record.

**Comment by xiangxiren** [comment]
In the header of the received message, there is the id of the published message.

**Comment by xiangxiren** [comment]
In the header of the received message, there is the id of the published message.

**Comment by carldai0106** [comment]
![image](https://user-images.githubusercontent.com/12929041/124424938-6db1c100-dd9a-11eb-8041-da6eecd64c2a.png)

**Comment by carldai0106** [comment]
![image](https://user-images.githubusercontent.com/12929041/124425000-86ba7200-dd9a-11eb-905c-99ae75548109.png)

**Comment by carldai0106** [comment]
![image](https://user-images.githubusercontent.com/12929041/124425207-d305b200-dd9a-11eb-8a49-361ad5edfdef.png)

**Comment by yang-xiaodong** [comment]
We do not plan to improve this feature for now, you can do this by adding a business number to the message header
