### ISSUE TITLE
How can I change the Exchange Type of rabbitmq?

### ISSUE THREAD

**Issue by icemount** [dotnetcore/CAP#930]
By default, the Exchange Type of rabbitmq is “topic”, but sometimes we need to use "direct" exchange type. It seems no way to change it currently. When we need to do system Integration by MQ with other system, we cannot suppose the other system to use "topic" exchange. So how can I do with such scenario?

**Comment by yang-xiaodong** [comment]
Since we need to take advantage of the features of Topic Exchange Type, so we don't support change the Exchange Type.
