### ISSUE TITLE
Make CAP more extensible

### ISSUE THREAD

**Issue by Kation** [dotnetcore/CAP#937]
If a framework use CAP as a component, developer will get confused in some scene.
First, make CAP accept multiple `IConsumerServiceSelector`. It's only accept one now.
There will be a conflict when developer have it's own `IConsumerServiceSelector`.
https://github.com/dotnetcore/CAP/blob/2e8256cd7d2d6415af51f1ca1b183d38ae7a8357/src/DotNetCore.CAP/Internal/MethodMatcherCache.cs#L15-L19

Second, make CAP accpet multiple `ISubscribeInvoker`.  It's only accept one now too.
https://github.com/dotnetcore/CAP/blob/2e8256cd7d2d6415af51f1ca1b183d38ae7a8357/src/DotNetCore.CAP/Internal/ISubscribeDispatcher.Default.cs#L31-L42
It could be a `Order` property and a `Match` method defined in `ISubscribeInvoker` for locate which `ISubscribeInvoker` will be use.
https://github.com/dotnetcore/CAP/blob/2e8256cd7d2d6415af51f1ca1b183d38ae7a8357/src/DotNetCore.CAP/Internal/ISubscribeDispatcher.Default.cs#L168-L176

Then CAP can use hybrid with many framework and developer`s custom code.

**Comment by yang-xiaodong** [comment]
Cap use `TryAddSingleton` register to the container, so you can add the custom `IConsumerServiceSelector` at the before.

```
services.TryAddSingleton<IConsumerServiceSelector, ConsumerServiceSelector>();
```
Or  you can override the `FindConsumersFromInterfaceTypes` or `FindConsumersFromControllerTypes`  to extend the custom logic

**Comment by Kation** [comment]
@yang-xiaodong I means there need more than one `IConsumerServiceSelector` in the project both need to work.
Override can extend default `ConsumerServiceSelector` only. If developer has its own `IConsumerServiceSelector`, there is no way to make two `IConsumerServiceSelector` work togather without additional codes.

**Comment by yang-xiaodong** [comment]
Why need two IConsumerServiceSelector ?  what's the scenario?

**Comment by Kation** [comment]
I want developer can use third frameworks that use CAP and his own custom logic hybrid. They don't need to face a situation where their have to choose one.

**Comment by yang-xiaodong** [comment]
What is the relationship between the third-party framework and CAP? Why do you need a third-party framework instead of using CAP directly?

**Comment by Kation** [comment]
For example, I have my own `IConsumerServiceSelector`.
https://github.com/Kation/ComBoost/blob/528fc40791c2b5561508ac760d066890a546b729/src/Wodsoft.ComBoost.Distributed.CAP/DomainConsumerServiceSelector.cs#L9-L34

And custom `ConsumerExecutorDescriptor`.
https://github.com/Kation/ComBoost/blob/528fc40791c2b5561508ac760d066890a546b729/src/Wodsoft.ComBoost.Distributed.CAP/DomainConsumerExecutorDescriptor.cs#L12-L42

So I also have to make a custom `ISubscribeInvoker`.
https://github.com/Kation/ComBoost/blob/528fc40791c2b5561508ac760d066890a546b729/src/Wodsoft.ComBoost.Distributed.CAP/DomainSubscribeInvoker.cs#L13-L34

With these, I can use CAP in my framework and make developer most insensitive.
Server side:
https://github.com/Kation/ComBoost/blob/528fc40791c2b5561508ac760d066890a546b729/test/Wodsoft.ComBoost.Distributed.CAP.Test/DistributedEventTest.cs#L21-L40
Handle domain event and bridging publish to CAP.
Client side:
https://github.com/Kation/ComBoost/blob/528fc40791c2b5561508ac760d066890a546b729/test/Wodsoft.ComBoost.Distributed.CAP.Test/DistributedEventTest.cs#L51-L74
Handle distributed domain event.

**Comment by yang-xiaodong** [comment]
If you are developing a framework, then you should encapsulate CAP instead of letting users use it directly. The framework is based on IConsumerServiceSelector to extend and open its own interface, just like users who use CAP do not need to know RabbitMQ.

Now I close this issue
