### ISSUE TITLE
Question about message idempotence

### ISSUE THREAD

**Issue by chaiziqi** [dotnetcore/CAP#94]
您好，非常感谢您的贡献，我英文不好使用汉语说了，了解CAP后有个疑问，之前从文档中也看到消费端接口要幂等设计，我的疑问是可能产生重复投递或者重复消费的情况吗，有的话是在哪个环节什么原因会出现？据我目前的思考，cap在发送端和消费端都有本地事务表保证一致性，发生重复消费应该只能出现在消息重复投递的情况吧，采用RabbitMQ的事务不能规避吗？如下引用CAP文档：
```
5.4 重试
重试在实现分布式事务中具有重要作用，CAP 中会针对发送失败或者执行失败的消息进行重试。在整个 CAP 的设计过程中有以下几处采用的重试策略。

① 消息发送重试

在消息发送过程中，当出现 Broker 宕机或者连接失败的情况亦或者出现异常的情况下，这个时候 CAP 会对发送的重试，重试策略为默认 15 次失败重试，当15次过后仍然失败时，CAP会将此消息状态标记为失败。

② 消息消费重试

当 Consumer 接收到消息时，会执行消费者方法，在执行消费者方法出现异常时，会进行重试。这个重试策略和 ① 是相同的。

③ 失败消息重试

CAP 会定期针对 ① 和 ② 中状态为“失败的”消息进行重试，CAP会对他们进行重新“入队(Enqueue)”，入队时会将消息中的重试次数标记为0，状态置为 Enqueued。
```
上述内容3中提到，当消费端始终失败，CAP会将该消息重新入队，这里是不是一个可能导致该消息被多次投递的原因？

期待您的解答，感谢！

**Comment by yuleyule66** [comment]
你好，最近版本已经不会对失败的消息进行重新入队列了，重试的次数上线也调整为了100次，当100次失败后消息会标记为失败，文档最近在重新整理以及国际化工作。

不过可以在Dashboard手工对失败的消息进行重新发送，这个时候消息会重新进行“入队(Enqueue)”。

需要保证幂等性是因为 Broker 在宕机然后进行恢复的时候可能会重复投递，另外一种情况就是消费着在消费的过程中发生了宕机这个时候可能方法执行完成但是并没有进行Confirm操作，有可能会进行重复消费的情况。

**Comment by chaiziqi** [comment]
您提到的消费者在过程发生宕机可能导致Confirm失败，是指从RabbitMQ读取消息到本地事务表的阶段发生Confirm失败对吗？那么CAP中从RabbitMQ读取消息到本地事务表时是否会校验本地事务表已存在而直接进行幂等操作呢（没有考虑这么做带来的消息处理能力降低多少）？如果没有实现的话，从文档上了解CAP会定时清理本地事务表以减少性能风险，这是不是一个与cap没有直接实现幂等读取的原因？

**Comment by yuleyule66** [comment]
CAP 没有实现幂等有以下几个原因 ：   以下都是接收端

**1、消息写入成功了，但是此时执行Consumer方法失败了**

执行Consumer方法失败的原因有非常多，我如果不知道具体的场景盲目进行重试或者不进行重试都是不正确的选择。
举个例子：假如消费者为扣款服务，如果是执行扣款成功了，但是在写扣款日志的时候失败了，此时CAP会判断为消费者执行失败，进行重试。如果客户端自己没有保证幂等性，框架对其进行重试，这里势必会造成多次扣款出现严重后果。

**2、执行Consumer方法成功了，但是又收到了同样的消息**

此处场景也是可能存在的，假如开始的时候Consumer已经执行成功了，但是由于某种原因如 Broker 宕机恢复等，又收到了相同的消息，CAP 在收到Broker消息后会认为这个是一个新的消息，会对 Consumer再次执行，由于是新消息，此时 CAP 也是无法做到幂等的。

**3、目前的数据存储模式无法做到幂等**

由于CAP存消息的表对于成功消费的消息会于1个小时后删除，所以如果对于一些历史性消息无法做到幂等操作。 历史性指的是，假如 Broker由于某种原因维护了或者是人工处理的一些消息。

**4、业界做法**

许多基于事件驱动的框架都是要求 用户 来保证幂等性操作的，比如 ENode, RocketMQ 等等...

**Comment by yuleyule66** [comment]
Related issue : https://github.com/dotnetcore/CAP/issues/29

**Comment by chaiziqi** [comment]
@yuleyule66 感谢详细的解答，之前考虑cap能否实现幂等是因为设计接受一套遗留系统改造，原系统接口不是幂等设计，导致重构起来比较尴尬。
