### ISSUE TITLE
Recent change for friendly messages means that In-Memory testing is more difficult.

### ISSUE THREAD

**Issue by matt-psaltis** [dotnetcore/CAP#940]
In relation to this change:
https://github.com/dotnetcore/CAP/blame/ac350871702987cc1d69ebb5ee8eb12d7bb8a928/src/DotNetCore.CAP/Internal/IBootstrapper.Default.cs#L122

Previously, I could create an in-memory CAP test using just:

```
            services.AddCap(options =>
            {
                options.DefaultGroupName = config.ServiceName;
                options.UseInMemoryStorage();
            });
```

The above change mandates the inclusion of a transport. Would it be possible to publish the CAP Test namespace so that we have easy access to the In Memory Fake transport and accompanying classes so that in-memory testing is still easy.

Thanks!

**Comment by yang-xiaodong** [comment]
Hello,

There is a in-memory transport under my repository. 

https://github.com/yang-xiaodong/Savorboard.CAP.InMemoryMessageQueue
https://www.nuget.org/packages/Savorboard.CAP.InMemoryMessageQueue

Can this be supported for testing?
