### ISSUE TITLE
Does transaction control have connection pool implementation

### ISSUE THREAD

**Issue by berkerdong** [dotnetcore/CAP#941]
using (var connection = new SqlConnection("ConnectionString"))
{
}

For transaction control like this, you need to create a database connection each time. For a process database like PostgreSQL, it costs a lot to create a connection each time. Is there a better way?

**Comment by yang-xiaodong** [comment]
The database driver has connection pooling capabilities

https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling
https://www.npgsql.org/doc/connection-string-parameters.html#pooling
https://mysqlconnector.net/connection-options/#connection-pooling-options
