### ISSUE TITLE
Dashboard search bug, unable to search Chinese

### ISSUE THREAD

**Issue by berkerdong** [dotnetcore/CAP#942]
![image](https://user-images.githubusercontent.com/36178221/125380234-7589ea80-e3c4-11eb-8308-8a6f4807c25a.png)

The search box here can only retrieve English, but it is invalid when inputting Chinese

![image](https://user-images.githubusercontent.com/36178221/125379925-014f4700-e3c4-11eb-822b-6e5555dfcba8.png)

![image](https://user-images.githubusercontent.com/36178221/125380039-2ba10480-e3c4-11eb-93c3-d57d9c686e36.png)

If such a content contains Chinese, there will be no result

![image](https://user-images.githubusercontent.com/36178221/125380123-483d3c80-e3c4-11eb-98f4-630dd2179dfb.png)

**Comment by yang-xiaodong** [comment]
Hello @xiangxiren , Do you have time to investigate this issue ?

**Comment by xiangxiren** [comment]
Unable to reproduce.
![image](https://user-images.githubusercontent.com/12774053/125409767-d201ff80-e3ee-11eb-8501-4769a75e0e3e.png)
![image](https://user-images.githubusercontent.com/12774053/125409801-daf2d100-e3ee-11eb-9d60-2de8c9cd0b26.png)
![image](https://user-images.githubusercontent.com/12774053/125409828-e2b27580-e3ee-11eb-9bd4-1651ff78a009.png)
![image](https://user-images.githubusercontent.com/12774053/125409866-eb0ab080-e3ee-11eb-98ff-b6d634b92e0a.png)

**Comment by xiangxiren** [comment]
Please provide your environment configuration.
For example: database type.

**Comment by StratosBlue** [comment]
The default serializer - JsonUtf8Serializer based on JsonSerializer will encode Chinese, just like:
"张三" -> "\u5F20\u4E09"
MySql will not decode the value.

Set JsonSerializerOptions.Encoder value with System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping can cancel the encoding. Whether there will be other impacts?

**Comment by berkerdong** [comment]
> Please provide your environment configuration.
> For example: database type.

Hello, My cap settings are as follows

options.UseInMemoryMessageQueue();
options.UseInMemoryStorage();

**Comment by xiangxiren** [comment]
Set up the encoder.
options.JsonSerializerOptions.Encoder = JavaScriptEncoder.Create(UnicodeRanges.All);

**Comment by berkerdong** [comment]
> Set up the encoder.
> options.JsonSerializerOptions.Encoder = JavaScriptEncoder.Create(UnicodeRanges.All);

Thank you very much. This setup successfully solved my problem
