### ISSUE TITLE
After the failure of the message, how to manually try again, there are methods, can be called through the code

### ISSUE THREAD

**Issue by berkerdong** [dotnetcore/CAP#943]
If the execution of a consumption message method fails completely, after repairing the internal execution code of the method, is there any way to cycle through the failed consumption message before execution? For example, after querying the wrong record in the received table, is there any way for the interface to try these operations again.

https://cap.dotnetcore.xyz/user-guide/en/cap/messaging/

This document page does not find the relevant manual call method，
After the failure of the message, how to manually try again, there are methods, can be called through the code

**Comment by yang-xiaodong** [comment]
The retry of the failure message is automatic, if the FailedThreshold has been reached, you can update the Retries field of the database table to continue retrying

**Comment by berkerdong** [comment]
Understood, thank you very much for your answer
