### ISSUE TITLE
Using in redis cluster，Exceptin:CROSSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by cdefg198** [dotnetcore/CAP#944]
When using DotNetCore.CAP.RedisStreams，If use  redis cluster, two exception messages are generated,

`Category: DotNetCore.CAP.RedisStreams.RedisStreamManager
EventId: 0

Redis error when trying read consumer group cap.queue.ms.capconsumer.v1

Exception: 
StackExchange.Redis.RedisServerException: CROSSSLOT Keys in request don't hash to the same slot
   at DotNetCore.CAP.RedisStreams.RedisStreamManager.TryReadConsumerGroup(String consumerGroup, StreamPosition[] positions, CancellationToken token)
`
`Category: DotNetCore.CAP.RedisStreams.AsyncLazyRedisConnection
EventId: 0

Server replied with error, CROSSSLOT Keys in request don't hash to the same slot, for endpoint:127.0.0.1:6390
`

if single redis,no problem.
Can you tell me the correct configuration？
Tanks.

**Comment by cdefg198** [comment]
`Category: DotNetCore.CAP.RedisStreams.RedisStreamManager
EventId: 0

Redis error when trying read consumer group cap.queue.ms.capconsumer.v1`

**Comment by yang-xiaodong** [comment]
This is because the key is not in the same hash slot, @MahmoudSamir101 Do you know is there anything we need to improve?

**Comment by MahmoudSamir101** [comment]
@yang-xiaodong it is true, we can use keys with a hash tag to ensure multiple keys are located in the same shard, I'll try to apply it in the week end

@cdefg198 appreciate if you can post the whole exception details with stack trace

**Comment by cdefg198** [comment]
@MahmoudSamir101 
Hi MahmoudSamir101,
I can only get this error message.
`
Category: DotNetCore.CAP.RedisStreams.RedisStreamManager
EventId: 0

Redis error when trying read consumer group workflow.cap.v1

Exception: 
StackExchange.Redis.RedisServerException: CROSSSLOT Keys in request don't hash to the same slot
   at DotNetCore.CAP.RedisStreams.RedisStreamManager.TryReadConsumerGroup(String consumerGroup, StreamPosition[] positions, CancellationToken token)
`
and
`
Category: DotNetCore.CAP.RedisStreams.AsyncLazyRedisConnection
EventId: 0

Server replied with error, CROSSSLOT Keys in request don't hash to the same slot, for endpoint:127.0.0.1:6390
`
Thanks.

**Comment by MahmoudSamir101** [comment]
@yang-xiaodong  I pushed the required changes for fixing the issue, the main solution is dependent on determining the hash slot of message name before consuming, as we are grouping messages based on their hash slot and reading them from Redis streams per hash slot to avoid cross slot reading.
 
The commit was merged to the master directly without PR, I am not sure why this happened, so please advise.

**Comment by yang-xiaodong** [comment]
@MahmoudSamir101   Thanks, I'll release a preview nuget package later.

The maintainer can directly push the code to the master branch without PR,  you can create a feature or bugfix branch to push and then submit a PR to merge into the master branch

**Comment by MahmoudSamir101** [comment]
@yang-xiaodong do you want me to do it like that or you can review it directly?

**Comment by yang-xiaodong** [comment]
@MahmoudSamir101  It's best to create a feature branch  and then create a PR to merge into the master for review

**Comment by MahmoudSamir101** [comment]
@yang-xiaodong PR #949 created, I reverted my commit to the master branch

**Comment by yang-xiaodong** [comment]
Fixed in `5.1.2-preview-143176668`
