### ISSUE TITLE
Problems in configuring SSL with rabbitmq

### ISSUE THREAD

**Issue by berkerdong** [dotnetcore/CAP#945]
![image](https://user-images.githubusercontent.com/36178221/125487396-81341b8c-0e21-4a23-b020-2d6638a74f65.png)
![image](https://user-images.githubusercontent.com/36178221/125487456-62f8a63c-48db-4974-a112-164e72ca17c6.png)

After configuring SSL for my rabbitmq service, I use the rabbitmq.client driver. When configuring the connection information, there is a SSL configuration item, which can be used normally in the test module. However, no SSL related parameters are found in the cap's connection configuration item for rabbitmq. How do I operate?

![image](https://user-images.githubusercontent.com/36178221/125488512-3966d2d9-3a8d-402e-8f6c-95cb08b3251b.png)

There are no SSL settings related documents

**Comment by yang-xiaodong** [comment]
see https://cap.dotnetcore.xyz/user-guide/en/transport/rabbitmq/#connectionfactory-options

**Comment by berkerdong** [comment]
> see https://cap.dotnetcore.xyz/user-guide/en/transport/rabbitmq/#connectionfactory-options

![image](https://user-images.githubusercontent.com/36178221/125549191-e32618c2-fdfc-4eda-9c6c-1107a66ebde7.png)

Thank you very much. It seems that this is OK. I will do a test in the test environment later. If there is no problem, I will close the issues at that time

**Comment by berkerdong** [comment]
The problem has been solved successfully. Thank you very much.
