### ISSUE TITLE
https://cap.dotnetcore.xyz/  内容严重滞后

### ISSUE THREAD

**Issue by lmxin123** [dotnetcore/CAP#946]
想问问，cap发布新版本的时候，可以同步更新 https://cap.dotnetcore.xyz/ 上的文档内容吗？或者在 https://cap.dotnetcore.xyz/的文档上标上发布的时间，以及适用的版本。非常感谢

**Comment by yang-xiaodong** [comment]
This is an open source project. When a new version is released, we try to ensure the timeliness of the document, but this is not guaranteed, so welcome to submit a PR to help improve
