### ISSUE TITLE
Question: Wrap this library using clean architecture principles & Subscriber fault tolerance and resiliency questions

### ISSUE THREAD

**Issue by maulik-modi** [dotnetcore/CAP#948]
Clean architecture requires hiding technology/framework dependent components behind an interface. This means, we do not directly reference this package in all our codebase in Application service layer.

Q-1: Any recommendation on how to hide ICapPublisher and CapSubscribe attributes e.g. Microsoft provides IMemoryCache or IDistributedCache that does not have any reference to framework/technology and can be referenced in business layer and specific implementation details can be injected in startup e.g Rediscache, SQL cache
Q-2: Is there any way to Pick, Lock and Remove message(as in Azure service bus) after message is **successfully** handled by subscriber
Q-3: How to Pick, Lock and move **FAILED** message to Error Queue that cannot be handled by subscriber - e.g. invalid message content 
Q-4: What is the best way to configure **MaxRetryAttempt**?

**Comment by mviegas** [comment]
Q-1: If you follow either the Clean or Hexagonal Architecture simples, a solution would be to have an abstracted contract like IMessageBus with a PublishAsync method exposed to your Application Layer, then on your Infrastructure Layer an implementation that injects the ICapPublisher.

To follow a similar approach for subscriptions, you could implement your own ConsumerSelector. Check the issue #336 for more details on this.

**Comment by yang-xiaodong** [comment]
Hello, Now let me answer your question

 **Mateus** has already answered Q-1, let me answer the remaining questions

Q-2:  As the EventBus level, CAP aims to abstract of the transport. If you need to use some of the features of the specific transport (such as the delayed message of RabbitMQ), we recommend that you customize it.

Q-3: When the message processing fails, it will automatically retry and if the failed message reaches the retires value threshold, the `FailedThresholdCallback` option will be triggered, then you can route/republish the message to a separate topic in the callback or take other processing methods, such as sending email.

Q-4: It depends on your tolerance for errors. The default setting is that failed message retry interval is 60 seconds (the first three retries are immediate), you can set it with the `FailedRetryInterval` options.

**Comment by maulik-modi** [comment]
Thanks @yang-xiaodong and @mviegas 
Q-2

> As the EventBus level, CAP aims to abstract of the transport. If you need to use some of the features of the specific transport (such as the delayed message of RabbitMQ), we recommend that you customize it.

I found that 
[AzureServiceBusConsumerClient.cs](https://github.com/dotnetcore/CAP/blob/8289e5066ad91e3d21f13f08021aaf7626de25fb/src/DotNetCore.CAP.AzureServiceBus/AzureServiceBusConsumerClient.cs#L203 ) and
[ITransport.AzureServiceBus.cs](https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP.AzureServiceBus/ITransport.AzureServiceBus.cs)
are  INTERNAL or SEALED classes 
```
    internal sealed class AzureServiceBusConsumerClient : IConsumerClient
    internal class AzureServiceBusTransport : ITransport
```
Do you recommend to fork a project from DotNetCore.CAP.AzureServiceBus?

**Comment by yang-xiaodong** [comment]
@maulik-modi Yes, Create your ConsumerClient through `IConsumerClientFactory`
