### ISSUE TITLE
Question about benchmark

### ISSUE THREAD

**Issue by ClearRipples** [dotnetcore/CAP#95]

**Comment by yuleyule66** [comment]
please provider your environment and configuration.

**Comment by ClearRipples** [comment]
![image](https://user-images.githubusercontent.com/4170686/37390819-432e3120-27a4-11e8-87a2-4393a28919d0.png)
跑了一下，应该是这里的订阅的 callback 有问题，实际在初始化的时候，kafka 上订阅的应该是 topics 才能通过也就是 CapSubscribe("wl.yxd.test.callback") 改成 CapSubscribe("wl.yxd.test")

**Comment by ClearRipples** [comment]
另外还有一个问题，如果对于大数据量的 published 和 subscribe 对于数据库的压力会不会很高？看到有很对的读写操作

**Comment by ClearRipples** [comment]
这个有做过并发的测试不

**Comment by yuleyule66** [comment]
@ClearRipples  上面就是我做的测试啊。。你可以自己测一下
