### ISSUE TITLE
Migrate to Azure.Messaging.ServiceBus from Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by maulik-modi** [dotnetcore/CAP#950]
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md

**Comment by yang-xiaodong** [comment]
Hello @maulik-modi ,

Would you like to create a PR for this? Since my Azure subscription has expired, so I can't perform the migration test.

**Comment by thisispaulsmith** [comment]
This has been closed as completed bit it isn't?

**Comment by yang-xiaodong** [comment]
@thisispaulsmith  No,Since no one was interested in this and submitted a PR for a long time,so we closed issue, would you like to do it?
