### ISSUE TITLE
How can I get all Messsage from a exchange without checking route

### ISSUE THREAD

**Issue by QuanJingHong** [dotnetcore/CAP#953]
Is there any way I can use Cap to receive all messages from multiple exchanges, with each exchange bound to different Queues.

For example:
Exchange A, A bind with queues name: a,b,c,d
Exchange B, B bind with queues name: e,f,g

I want to get all messages from Exchange A, B in Cap.

How can I do that.

**Comment by yang-xiaodong** [comment]
CAP does not support multiple exchange and only provide support for Topic types

**Comment by QuanJingHong** [comment]
> CAP does not support multiple exchange and only provide support for Topic types

Can I get message from one exchange, that exchange bind with more than one queue?

**Comment by QuanJingHong** [comment]
plsss, can you explain to me the Routing key mechanism in Cap, how can I use it.

**Comment by yang-xiaodong** [comment]
https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-topic
