### ISSUE TITLE
How to use Group (queue name)?

### ISSUE THREAD

**Issue by QuanJingHong** [dotnetcore/CAP#954]
I see here you use Group, Group will be used as Queue name in Rabbit MQ. But I don't know how to set a group. Can you describe this? Thanks.

```
protected virtual void SetSubscribeAttribute(TopicAttribute attribute)
        {
            var prefix = !string.IsNullOrEmpty(_capOptions.GroupNamePrefix)
                ? $"{_capOptions.GroupNamePrefix}."
                : string.Empty;
            //attribute.Group = $"{prefix}{attribute.Group ?? _capOptions.DefaultGroupName}.{_capOptions.Version}";
            var version = _capOptions.Version == "v1" ? "" : "." + _capOptions.Version;

            var defaultGroup = $"{prefix}{attribute.Group ?? _capOptions.DefaultGroupName}" + version;

            //attribute.Group = !string.IsNullOrEmpty(_capOptions.GroupName) ? _capOptions.GroupName : defaultGroup;
            attribute.Group =  defaultGroup;
        }
```

```
using (var client = _consumerClientFactory.Create(matchGroup.Key))
                            {
                                _serverAddress = client.BrokerAddress;

                                RegisterMessageProcessor(client);

                                client.Subscribe(topicIds);

                                client.Listening(_pollingDelay, _cts.Token);
                            }```

**Comment by xiangxiren** [comment]
https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/CAP.Options.cs #L34

**Comment by xiangxiren** [comment]
https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/CAP.Options.cs#L34

**Comment by xiangxiren** [comment]
https://github.com/dotnetcore/CAP/blob/3c155ce7d66029f11178e4a450fee16708e62538/src/DotNetCore.CAP/CAP.Options.cs#L33-L36

**Comment by QuanJingHong** [comment]
Can I set Group for CapAtribute?

**Comment by xiangxiren** [comment]
> Can I set Group for CapAtribute?

https://github.com/dotnetcore/CAP/blob/3c155ce7d66029f11178e4a450fee16708e62538/samples/Sample.RabbitMQ.SqlServer/Controllers/ValuesController.cs#L77-L84

**Comment by QuanJingHong** [comment]
> > Can I set Group for CapAtribute?
> 
> https://github.com/dotnetcore/CAP/blob/3c155ce7d66029f11178e4a450fee16708e62538/samples/Sample.RabbitMQ.SqlServer/Controllers/ValuesController.cs#L77-L84

what the version number you are using, I don't see a set group variable in capSubscriber's constructor. I just added my own code.

**Comment by xiangxiren** [comment]
The Group attribute is in the parent class TopicAttribute.
https://github.com/dotnetcore/CAP/blob/3c155ce7d66029f11178e4a450fee16708e62538/src/DotNetCore.CAP/CAP.Attribute.cs#L12
https://github.com/dotnetcore/CAP/blob/3c155ce7d66029f11178e4a450fee16708e62538/src/DotNetCore.CAP/Internal/TopicAttribute.cs#L33-L38
