### ISSUE TITLE
BUG: CancellationTokenSource was null when restart!

### ISSUE THREAD

**Issue by QuanJingHong** [dotnetcore/CAP#955]
when I receive a message from a non-cap publisher, then at the OnConsumerReceived header customer is added to the message. The message is then passed to the RegisterMessageProcessor function.

At the SelectBestCandidate function, the debugger reports _cts was null:

![https://i.imgur.com/NzyH6AQ.png](https://i.imgur.com/NzyH6AQ.png)

The cause of the error could be the MatchWildcardUsingRegex function.

i try with case

key: document.pdf
red.Name: ```^doccument\\.[0-9-zA-Z]+$```

if (Regex.IsMatch(key, red.Name, RegexOptions.Singleline))
                 {
                     return red.Descriptor;
  }

above function returns false

**Comment by yang-xiaodong** [comment]
dupliacte of #952
