### ISSUE TITLE
Multiple exchange, queue for CAP.Rabbit?

### ISSUE THREAD

**Issue by QuanJingHong** [dotnetcore/CAP#958]
I have implemented a function for Cap.Rabbit. The implement allows Cap.Rabbit can publish to any Exchange, Queue, Routing, and CAP.Rabbit can subscribe and listen to any Exchange, Queue Routing. Is that function in line with Cap's orientation? Can I create a PR?

**Comment by yang-xiaodong** [comment]
Hello,
CAP aims to abstract of the transport and adapting more native feature mappings for each transport does not fit our roadmap.

**Comment by li-zheng-hao** [comment]
hello, can you share your implementation version code? I also need multiple exchange support
