### ISSUE TITLE
How to Subscribe message by CAP from non-CAP rabbitMQ producer

### ISSUE THREAD

**Issue by Vincentyiu** [dotnetcore/CAP#964]
Env:
.net core 3.1
CAP 5.0.2

Producer :

```C#
using (var connection = factory.CreateConnection())
{
    using (var channel = connection.CreateModel())
    {
        var properties = channel.CreateBasicProperties();
        properties.Persistent = true;
        properties.Headers = new Dictionary<string, object>()
        {
            {"cap-msg-name","XXX.XX.Services.MQ.Test" },
            {"cap-msg-id",Guid.NewGuid().ToString() },
            { "table","zzzzz" }
        }; 

        var msg = Encoding.UTF8.GetBytes("Message: name");
        channel.BasicPublish(exchange: string.Empty
            , routingKey: "cap.queue.test.msg.v1"
            , basicProperties: properties
            , mandatory: false
            , body: msg);
    }
}
```
Subscribe:

```C#
[Route("Postxxx")]
[HttpPost]
[CapSubscribe("XXX.XX.Services.MQ.Test")]
public async Task<IActionResult> Postxxx(string str, [FromCap] CapHeader header)
```

ErrorLog:
```
{"Headers":{"cap-msg-name":"XXX.XX.Services.MQ.Test","cap-msg-id":"270cb497-72f2-4fa5-bd1c-1ccd314f087b","table":"zzzzz","remark":"18","cap-msg-group":"cap.queue.test.msg.v1","cap-exception":"JsonException--\u003E\u0027M\u0027 is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0."},"Value":"data:UnknownType;base64,TWVzc2FnZTogbmFtZQ=="}
```

**Comment by xiangxiren** [comment]
see https://cap.dotnetcore.xyz/user-guide/en/transport/rabbitmq/#customheaders-options

**Comment by yang-xiaodong** [comment]
Please use `JsonSerializer.SerializeToUtf8Bytes` to serialize the message, refer to https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/Serialization/ISerializer.JsonUtf8.cs#L22

下次提issue请把代码格式排版调整好，真的没有任何心情来看这种issue，现在我已经帮调整了

**Comment by Vincentyiu** [comment]
> Please use `JsonSerializer.SerializeToUtf8Bytes` to serialize the message, refer to https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/Serialization/ISerializer.JsonUtf8.cs#L22
> 
> 下次提issue请把代码格式排版调整好，真的没有任何心情来看这种issue，现在我已经帮调整了

thx for the help,i fix the producer code like this,it works.

`
var msg = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(null, new JsonSerializerSettings() { StringEscapeHandling = StringEscapeHandling.EscapeNonAscii }));
`
