### ISSUE TITLE
InMemoryStorage.DeleteExpiresAsync cause in Infinite Retry

### ISSUE THREAD

**Issue by Linc-li** [dotnetcore/CAP#965]
Hi,

Version is CAP 3.1.2.
Our application has occurred following error:
[38;5;0007m2021-07-23 15:54:58[0m[38;5;0008m [[0m[38;5;0011mWRN[0m[38;5;0008m] [[0m[38;5;0007mDotNetCore.CAP.Processor.InfiniteRetryProcessor[0m[38;5;0008m] [0m[38;5;0015mProcessor '[0m[38;5;0045m"DotNetCore.CAP.Processor.CollectorProcessor"[0m[38;5;0015m' failed. Retrying...[0m
[38;5;0015mSystem.NullReferenceException: Object reference not set to an instance of an object.
[0m[38;5;0007m   at DotNetCore.CAP.InMemoryStorage.InMemoryStorage.<>c__DisplayClass14_0.<DeleteExpiresAsync>b__2(MemoryMessage x)
[0m[38;5;0007m   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
[0m[38;5;0007m   at System.Linq.Enumerable.EnumerablePartition`1.MoveNext()
[0m[38;5;0007m   at DotNetCore.CAP.InMemoryStorage.InMemoryStorage.DeleteExpiresAsync(String table, DateTime timeout, Int32 batchCount, CancellationToken token)
[0m[38;5;0007m   at DotNetCore.CAP.Processor.CollectorProcessor.ProcessAsync(ProcessingContext context)
[0m[38;5;0007m   at DotNetCore.CAP.Processor.InfiniteRetryProcessor.ProcessAsync(ProcessingContext context)
[0m[38;5;0007m2021-07-23 15:55:00[0m[38;5;0008m [[0m[38;5;0007mDBG[0m[38;5;0008m] [[0m[38;5;0007mDotNetCore.CAP.Processor.CollectorProcessor[0m[38;5;0008m] [0m[38;5;0015mCollecting expired data from table: PublishedMessages[0m
[38;5;0007m2021-07-23 15:55:00[0m[38;5;0008m [[0m[38;5;0007mDBG[0m[38;5;0008m] [[0m[38;5;0007mDotNetCore.CAP.Processor.CollectorProcessor[0m[38;5;0008m] [0m[38;5;0015mCollecting expired data from table: ReceivedMessages[0m
[38;5;0007m2021-07-23 15:55:00[0m[38;5;0008m [[0m[38;5;0011mWRN[0m[38;5;0008m] [[0m[38;5;0007mDotNetCore.CAP.Processor.InfiniteRetryProcessor[0m[38;5;0008m] 

Do you know how to fix it?

Look forward to your reply.

**Comment by Linc-li** [comment]
This issue is already fixed?

**Comment by xiangxiren** [comment]
Please provide your environment and configuration. And provide your steps to reproduce. In addition, can you provide an exception message that is not garbled?

**Comment by Linc-li** [comment]
This is an online production exception, currently online product is install CAP 3.1.2.
When asp.net core job is running at back ground, in sometime which outbreak this issue.
All time is retry to delete the publish message and receive message var. 
After delete all the pod in K8 server, this error is gone.

**Comment by xiangxiren** [comment]
Use DotNetCore.CAP.InMemoryStorage in production? Is this reasonable?

**Comment by Linc-li** [comment]
User memory storage is considering performance issue, memory storage is more fast the redis or sql

**Comment by xiangxiren** [comment]
When the Pod stops, isn't all the data lost?

**Comment by Linc-li** [comment]
Yes, but it is low chance.

**Comment by xiangxiren** [comment]
I have no idea about your question. You need Yang @yang-xiaodong 's help.

**Comment by yang-xiaodong** [comment]
We no longer provide support for version 3.1.2,  you need to investigate this problem yourself. If this is a bug, you can improve it by customizing `IDataStorage` interface

**Comment by Linc-li** [comment]
I will upgrade CAP version later in online product.
However in my local environment,

There are some error like:
2021-07-29 11:51:27 [WRN] [DotNetCore.CAP.Processor.TransportCheckProcessor] Transport connection is unhealthy, reconnection...

2021-07-29 11:51:27 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] RabbitMQ consumer cancelled. --> amq.ctag-E_BZqn_l94rZxz2_Ej6lWg

2021-07-29 11:51:27 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] RabbitMQ consumer shutdown. --> Goodbye

2021-07-29 11:51:27 [INF] [DotNetCore.CAP.Internal.ConsumerRegister] RabbitMQ consumer registered. --> amq.ctag-fWBvcO-R1g__-BY03g1hvw

Which is printing a lot, how could we solve this?

**Comment by yang-xiaodong** [comment]
Close this issue, Questions are followed up in #966
