### ISSUE TITLE
Rabbitmq consuemr shutdown reconnection warning message

### ISSUE THREAD

**Issue by Linc-li** [dotnetcore/CAP#966]
Hi,

When we send a message to application, out break an exception, then whole consumer crashed down, the error as follow:
XXX.YYYY.Common.Exceptions.WAApplicationException: Error pre-processing work order CWOC202107271245362346 request. See inner exception for details

```

2021-07-27 00:46:13 [DBG] [XXXXX.Classic.WAMQClient.BusObserverSubject] Entering notifyObservers

2021-07-27 00:46:13 [DBG] [XXXXX.Classic.WAMQClient.BusObserverSubject] Header message type: "WOMFAILED"

2021-07-27 00:54:54 [DBG] [DotNetCore.CAP.Internal.SubscribeDispatcher] Consumer executed. Took: 558373.1628 ms.

2021-07-27 00:54:54 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] RabbitMQ consumer cancelled. --> amq.ctag-OmyvHFqQPVvYY9ANyyDZCw

2021-07-27 00:54:54 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] RabbitMQ consumer shutdown. --> End of stream

2021-07-27 00:54:55 [ERR] [DotNetCore.CAP.Processor.Dispatcher] An exception occured while publishing a message, reason:Failed : . message id:1419929275177967616

DotNetCore.CAP.Internal.PublisherSentFailedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=0, text='End of stream', classId=0, methodId=0, cause=System.IO.EndOfStreamException: Reached the end of the stream. Possible authentication failure.

   at RabbitMQ.Client.Impl.InboundFrame.ReadFrom(Stream reader, Byte[] frameHeaderBuffer)

   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()

   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()

---> RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=0, text='End of stream', classId=0, methodId=0, cause=System.IO.EndOfStreamException: Reached the end of the stream. Possible authentication failure.

   at RabbitMQ.Client.Impl.InboundFrame.ReadFrom(Stream reader, Byte[] frameHeaderBuffer)

   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()

   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()

   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)

   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)

   at RabbitMQ.Client.Framing.Impl.Model._Private_ConfirmSelect(Boolean nowait)

   at RabbitMQ.Client.Impl.ModelBase.ConfirmSelect()

   at RabbitMQ.Client.Impl.AutorecoveringModel.ConfirmSelect()

```

Do you know how to fix it?
Thanks,
Linc

**Comment by yang-xiaodong** [comment]
Please report your environemnt and configuration ?

**Comment by Linc-li** [comment]
Device specifications
Device name	DESKTOP-H1NUG3A
Processor	Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz   2.11 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	D10EA68A-A37A-47C9-AF30-008486FD9ECB
System type	64-bit operating system, x64-based processor
Windows specifications
Edition	Windows 10 Pro
Version	21H1
OS build	19043.1110

**Comment by Linc-li** [comment]
Hi,

Any progress? Waiting for solution.

Look forward to your reply.
Thanks,
Linc

**Comment by xiangxiren** [comment]
https://stackoverflow.com/questions/61884733/rabbitmq-tls-authentication

The error message here is consistent with yours.
```
The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=0, text='End of stream', classId=0, methodId=0, cause=System.IO.EndOfStreamException: Reached the end of the stream. Possible authentication failure.
```

**Comment by yang-xiaodong** [comment]
@Linc-li  Please report the and configuration?

```
.NET Core (with version) :

CAP Version :
Transport (with version) :
Storage (with version) :
Startup.cs configuration of CAP:
```

**Comment by Linc-li** [comment]
.NET Core (with version) :5.0
CAP Version :5.1.2
Transport (with version) :
Storage (with version) :
No sure transport and storage.
Package list is as follow:
<PackageReference Include="DotNetCore.CAP" Version="5.1.2" />
    <PackageReference Include="DotNetCore.CAP.RabbitMQ" Version="5.1.2" />
    <PackageReference Include="DotNetCore.CAP.SqlServer" Version="5.1.2" />
    <PackageReference Include="DotNetCore.CAP.AmazonSQS" Version="5.1.2" />
    <PackageReference Include="DotNetCore.CAP.AzureServiceBus" Version="5.1.2" />
    <PackageReference Include="DotNetCore.CAP.InMemoryStorage" Version="5.1.2" />
    <PackageReference Include="DotNetCore.CAP.Kafka" Version="5.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Savorboard.CAP.InMemoryMessageQueue" Version="5.1.1" />
Startup.cs configuration of CAP:

UseInMemoryStorage
UseRabbitMQ
FailedRetryCount = 0

**Comment by RiverLi** [comment]
@yang-xiaodong @xiangxiren   The problem was duplicated in Visual Studio 2019 debugging the application(connecting to the rabbitmq docker container). We could not do tls config. It is rabbitmq docker container. Everything is set up already. We could not change to any rabbitmq setting. 
Meanwhile the problem was not duplicated without debugging( Running the application directly). One information you may want to know is that the debugging application and non-debugging application connect to the same rabbitmq docker container using IP and port.
Our worry is that it may happen again in the future in the more important environments. The result was bad. Because the application was running but stopped to receive messages. We had to restart the application manually.
The rabbitmq image we used is rabbitmq:3-management-alpine. It has a management portal at 15672 port.
Please see what more information you need to duplicate and resolve the problem?

**Comment by Linc-li** [comment]
So this issue only happen in Docker container?

**Comment by Linc-li** [comment]
So why cosumer always shutdown by itself? Do we have any solution to fix it?

**Comment by RiverLi** [comment]
A new disconnection event:
<before this is our log>
2021-07-30 04:25:38 [DBG] [DotNetCore.CAP.Internal.SubscribeDispatcher] Consumer executed. Took: 603.0244 ms.
2021-07-30 07:09:51 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] RabbitMQ consumer cancelled. --> amq.ctag-NAF4ZSgEv3PTLXhKG0ruRQ
2021-07-30 07:09:51 [WRN] [DotNetCore.CAP.Internal.ConsumerRegister] RabbitMQ consumer shutdown. --> Unexpected Exception
We checked the rabbitmq. The connection was lost.
Not sure whether the exception is the same as the issue here. The result is the same. Rabbitmq connection was lost.

**Comment by yang-xiaodong** [comment]
Hello,
I have released `5.1.3-preview-144669387` to NuGet a few minutes ago, please confirm whether this issue is fixed?

**Comment by yang-xiaodong** [comment]
Is there any feedback?

**Comment by Linc-li** [comment]
Hi team,

Currently error stopping printing, and when I shut down the rabbitmq, then start the rabbitmq, our job can reconnect to rabbitmq.

But when I first send a message, which CAP will throw an exception said channel is closed already, I have checked code in RabbitMQTransport.cs

public Task<OperateResult> SendAsync(TransportMessage message)
        {
            IModel channel = null;
            try
            {
                **channel = _connectionChannelPool.Rent();** ////// This connection pool should clean up when reconnect to rabbitmq server, to avoid to get a closed channel.

                channel.ConfirmSelect();

                var props = channel.CreateBasicProperties();
                props.DeliveryMode = 2;
                props.Headers = message.Headers.ToDictionary(x => x.Key, x => (object) x.Value);
                
                channel.ExchangeDeclare(_exchange, RabbitMQOptions.ExchangeType, true);

                channel.BasicPublish(_exchange, message.GetName(), props, message.Body);

                channel.WaitForConfirmsOrDie(TimeSpan.FromSeconds(5));

                _logger.LogDebug($"RabbitMQ topic message [{message.GetName()}] has been published.");

                return Task.FromResult(OperateResult.Success);
            }
            catch (Exception ex)
            {
                var wrapperEx = new PublisherSentFailedException(ex.Message, ex);
                var errors = new OperateError
                {
                    Code = ex.HResult.ToString(),
                    Description = ex.Message
                };

                return Task.FromResult(OperateResult.Failed(wrapperEx, errors));
            }
            finally
            {
                if (channel != null)
                {
                    var returned = _connectionChannelPool.Return(channel);
                    if (!returned)
                    {
                        channel.Dispose();
                    }
                }
            }
        }

**Comment by yang-xiaodong** [comment]
@Linc-li  See
https://github.com/dotnetcore/CAP/blob/2f63b707fb2b0082e546e8b3497d091a4f35120a/src/DotNetCore.CAP.RabbitMQ/IConnectionChannelPool.Default.cs#L145
