### ISSUE TITLE
[Question] Does CAP preserve ordering of messages?

### ISSUE THREAD

**Issue by viktor-nikolaev** [dotnetcore/CAP#971]
Could not find the answer in the doc, so sorry for opening the ticket/

We use kafka + postgresql, will a subscriber receive messages in the same order as they were sent? What if we failed (exception, etc) while consuming a message, will it block the processing of other messages?

**Comment by xiangxiren** [comment]
Order cannot be guaranteed

**Comment by viktor-nikolaev** [comment]
@xiangxiren thanks,
Order cannot be guaranteed even in the "happy" path? ie when nothing has failed and all messages been processed successfully?

**Comment by xiangxiren** [comment]
> @xiangxiren thanks,
> Order cannot be guaranteed even in the "happy" path? ie when nothing has failed and all messages been processed successfully?

Yes, there is no guarantee that the order is absolutely correct.

**Comment by yang-xiaodong** [comment]
Actually, "happy" path can guarantee the order, when broker or consumer fails, it cannot guaranteed

**Comment by xiangxiren** [comment]
> Actually, "happy" path can guarantee the order, when broker or consumer fails, it cannot guaranteed

Can the order of message confirmation be guaranteed after the business logic is processed?

**Comment by yang-xiaodong** [comment]
> Can the order of message confirmation be guaranteed after the business logic is processed?

Yes, it's sequential in memory
