### ISSUE TITLE
 Broker: Group authorization failed

### ISSUE THREAD

**Issue by knowyi** [dotnetcore/CAP#972]
hi，我测试环境使用自己搭建的kafka没有问题，生产使用阿里云的kafka报错 Broker: Group authorization failed，请问要做什么设置吗
![image](https://user-images.githubusercontent.com/7392434/128991706-a428f987-99ff-4bde-94a3-8f7c55c4e1e2.png)

**Comment by yang-xiaodong** [comment]
Hello, we do not provide support for this, please contact the provider

**Comment by knowyi** [comment]
@yang-xiaodong 你好 那如果我想设置Consumer Group 应该如何设置？

**Comment by yang-xiaodong** [comment]
> @yang-xiaodong 你好 那如果我想设置Consumer Group 应该如何设置？

https://github.com/dotnetcore/cap#subscribe-group
