### ISSUE TITLE
Can open the ability to customize the interval to delete expired message

### ISSUE THREAD

**Issue by HengzheLi** [dotnetcore/CAP#973]
for now, CollectorProcessor seem is the one which is resposible to clean the expired message. And the interval is harded code to 5 minutes. Can it be customized?

**Comment by yang-xiaodong** [comment]
Hello,

Thanks for your feedback, we will support the interval options in the next version.

**Comment by yang-xiaodong** [comment]
Fixed in version 5.1.3
