### ISSUE TITLE
DotNetCore.CAP.Dashboard类库在5.x中能否支持netstandard2.1呢

### ISSUE THREAD

**Issue by jakey188** [dotnetcore/CAP#974]
现在DotNetCore.CAP.Dashboard在5.x只支持net5.0能否支持netstandard2.1呢,因为现在有很多项目还在使用netcoreapp3.1

**Comment by yang-xiaodong** [comment]
No, Dashboard is implemented based on ASP.NET Core middleware

**Comment by jakey188** [comment]
如果是使用了nginx或者其他代理之后Dashboard对于资源资源请求文件(js,css)的路径不支持,而且是使用的绝对路径/,我看了5.x之后是支持配置的。
