### ISSUE TITLE
Dashboard - Getting the Stats refresh rate

### ISSUE THREAD

**Issue by KayakFisher205** [dotnetcore/CAP#979]
When watching the Dashboard, the call to cap/api/stats is running every 3-4 seconds. Is it possible to adjust the refresh to be like 30 seconds or longer? Since this is making a call to the SQL Server on another machine, I'd like to reduce the traffic and I don't need basically real time data.

I'm running version 5.1.3.

**Comment by yang-xiaodong** [comment]
Dashboard is only used to view data for a short time. The request for this stats comes from the call of the browser. This will stop when you close the page.
