### ISSUE TITLE
is there any method or extension allow me use typed message publish and subscribe?

### ISSUE THREAD

**Issue by Eilyyyy** [dotnetcore/CAP#98]
if is possible to publish and subscribe event like this ?
 ```
    public interface ICapSubscribe<in T> : ICapSubscribe
    {
        Task Handle(T message);
    }
```
```
    public class TestHandle : ICapSubscribe<TestEvent>
    {
        public Task Handle(TestEvent message)
        {
            Console.WriteLine(message.Message);
            return Task.CompletedTask;
        }
    }
````
```
    public class TestEvent
    {
        public string Message { get; set; }
    }
```
and i can publish event like this `_publisher.PublishAsync(new TestEvent())`
and the routing key just as type name, in this example is `TestEvent`.

i try to implement the interface of 'IConsumerServiceSelector' but it's internal and i found that `ConsumerExecutorDescriptor` `ConsumerContext` all is internal, seems like i have no way to replace the implement of subscribe discovery.
is there any idea to achieve this ?
thank you.

**Comment by yuleyule66** [comment]
Thanks for your proposal, I will consider this later.

**Comment by yuleyule66** [comment]
Hello, 

After a long time of feedback, we think that using a strongly typed subscribe interface would reduce the flexibility of application. 

Sometimes, strong typing can make us make fewer mistakes, but it's not always good. In CAP we can't ask consumers to use the same data type as the sender. Instead, they only need to be able to guarantee that these objects can be properly deserialized and they can bring a lot of flexibility. For example, you don't need to create a separate consumer class, and you can easily integrate it into the current Controller and Services.

I hope the above is useful to you, I am willing to listen to your opinion, let me konw if you have any questions.  😃

**Comment by yang-xiaodong** [comment]
https://github.com/dotnetcore/CAP/tree/master/samples/Sample.RabbitMQ.SqlServer.DispatcherPerGroup/TypedConsumers

Here is an example of typed consumer
