### ISSUE TITLE
Do you have any plan to support NATS Stream?

### ISSUE THREAD

**Issue by ChangYinHan** [dotnetcore/CAP#980]
As it's mentioned, do you have any plan to support NATS Streaming? I want to use CAP with NTAS Streaming in my project.

https://docs.nats.io/nats-streaming-concepts/intro

**Comment by yang-xiaodong** [comment]
Duplicate of #595 

Supported at v5.0, see  https://cap.dotnetcore.xyz/user-guide/en/transport/nats/
