### ISSUE TITLE
Are there any plans to support NATS Jetstream?

### ISSUE THREAD

**Issue by artem-avanesov** [dotnetcore/CAP#983]

**Comment by yang-xiaodong** [comment]
Hello,

Thanks for your feedback, I thinks it's a very good feature, compared with Request/Response mode JetStream seems to be more symbolic of our needs, but it seems that it is still in [Beta status](https://github.com/nats-io/nats.net#jetstream) for .net client. We hope that JetStream can be used to replace the current implementation when appropriate.

If someone wants to make a PR on this, that would be great.

https://docs.nats.io/jetstream/jetstream
https://github.com/nats-io/nats.net#jetstream
