### ISSUE TITLE
How to resolve this error?

### ISSUE THREAD

**Issue by miloshen** [dotnetcore/CAP#984]
**Application startup exception
      Method 'Start' in type 'DotNetCore.CAP.Dashboard.NodeDiscovery.ConsulProcessingNodeServer' from assembly 'DotNetCore.CAP.Dashboard, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
      System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.**

I didn't use cap dashboard,but it reported the error above.

**Comment by yang-xiaodong** [comment]
Hello, how do we reproduce this problem, please report your steps

**Comment by miloshen** [comment]
Thanks for you reply, I have two backend apps that use the same configuration on CAP, the first works,but when I deploy anthoer one,It will report this error even I did'n use dashboard.

**Comment by miloshen** [comment]
Thanks for you reply, I have two backend apps that use the same configuration on CAP, the first works,but when I deploy anthoer one,It will report this error even I did'n use dashboard.

**Comment by yang-xiaodong** [comment]
If your two back-end applications have the same configuration, according to the description, you should have enabled multiple instances of the same service. This seems strange, one is normal and one is exception.

**Comment by miloshen** [comment]
Both are working now after I removed the DotNetCore.CAP.Dashboard NuGet package.
