### ISSUE TITLE
Getting "System.NullReferenceException" on publish action when upgrade package higher than 5.1.0

### ISSUE THREAD

**Issue by eymenkhater** [dotnetcore/CAP#985]
Hello there!
Currently using DotNetCore.CAP version 5.1.0. We have multiple Mongo DB for the cap in a single API and resolved multiple database connections by wrapping **ICapPublisher** (#783).

In 5.1.0 version of DotNetCore.CAP everything is fine but the dashboard is unstable for Mongo DB. So we decided to upgrade to any stable version (which them 5.1.1,5.1.2 or 5.1.3) to be able to access the dashboard.

We tried and tested sample registration usage for any version higher than 5.1.0. Publishing is successful. Nothing exception.  But when wrapping **ICapPublisher** getting **NullReferenceException**. The record of publishing action flagged scheduled on the database. 

**The following error:**

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetCore.CAP.Processor.Dispatcher.EnqueueToPublish(MediumMessage message)
   at DotNetCore.CAP.Internal.CapPublisher.Publish[T](String name, T value, IDictionary`2 headers)
   at DotNetCore.CAP.Internal.CapPublisher.Publish[T](String name, T value, String callbackName)
   at DotNetCore.CAP.Internal.CapPublisher.<>c__DisplayClass12_0`1.<PublishAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
```

**Our ICapPublisher Wrapper**

    public interface IFarmazonCapPublisher : ICapPublisher
    {

    }

    internal class FarmazonCapPublisher : IFarmazonCapPublisher
    {
        private readonly ICapPublisher _capPublisher;
        public IServiceProvider ServiceProvider { get; init; }
        public FarmazonCapPublisher(FarmazonCapSettings farmazonCapSettings)
        {
            var services = new ServiceCollection();
            services.AddLogging(q =>
            {
                q.AddConsole();
                q.AddDebug();
            });
            services.AddCap(cap =>
            {
                cap.UseDashboard();
                cap.UseMongoDB(opt =>
                {
                    opt.DatabaseName = farmazonCapSettings.MongoDataBaseName;
                    opt.DatabaseConnection = farmazonCapSettings.MongoDBConnectionStrings;
                });

                cap.UseRabbitMQ(z =>
                {
                    z.UserName = farmazonCapSettings.RabbitMQConnectionStrings.Split('|')[0];
                    z.Password = farmazonCapSettings.RabbitMQConnectionStrings.Split('|')[1];
                    z.HostName = farmazonCapSettings.RabbitMQConnectionStrings.Split('|')[2];
                });
            });

            ServiceProvider = services.BuildServiceProvider();
            _capPublisher = ServiceProvider.GetRequiredService<ICapPublisher>();
        }

        public AsyncLocal<ICapTransaction> Transaction => _capPublisher.Transaction;

        public void Publish<T>(string name, T contentObj, string callbackName = null)
        {
            _capPublisher.Publish(name, contentObj, callbackName);
        }

        public void Publish<T>(string name, T contentObj, IDictionary<string, string> headers)
        {
            _capPublisher.Publish(name, contentObj, headers);
        }

        public async Task PublishAsync<T>(string name, T contentObj, string callbackName = null, CancellationToken cancellationToken = default)
        {
            await _capPublisher.PublishAsync(name, contentObj, callbackName, cancellationToken);
        }

        public async Task PublishAsync<T>(string name, T contentObj, IDictionary<string, string> headers, CancellationToken cancellationToken = default)
        {
            await _capPublisher.PublishAsync(name, contentObj, headers, cancellationToken);
        }
    }

**The wrapper registration in Startup.cs**

        public static IServiceCollection AddFarmazonCAPPublisher(this IServiceCollection services, IConfiguration configuration)
        {
            configuration.Bind("FarmazonCapSettings", _farmazonCapSettings);
            services.AddSingleton(_farmazonCapSettings);

            services.AddSingleton<IFarmazonCapPublisher, FarmazonCapPublisher>(q => new FarmazonCapPublisher(_farmazonCapSettings));

            services.AddHealthChecks().AddCheck<FarmazonCapHealthCheck>("Farmazon.Publisher.CAP");

            return services;
        }

**Dependencies:**

```
  <ItemGroup>
    <PackageReference Include="DotNetCore.CAP" Version="5.1.3" />
    <PackageReference Include="DotNetCore.CAP.Dashboard" Version="5.1.3" />
    <PackageReference Include="DotNetCore.CAP.MongoDB" Version="5.1.3" />
    <PackageReference Include="DotNetCore.CAP.RabbitMQ" Version="5.1.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="5.0.6" />
  </ItemGroup>
```

**Comment by yang-xiaodong** [comment]
Hello,

I think this may be caused by the change made in #936. We put the initialization of Channel in the `Start` method, so when the background thread is not started with `IBootstrapper`, the Channel object will not be initialized.

**Comment by omeerkorkmazz** [comment]
Hi @yang-xiaodong,

Sorry for commenting on the closed issue but I have the same problem with @eymenkhater. Since there is no support for multiple CapOptions in the same project, we use a basic **"wrapper"** which is a T generic implementation to use ICapPublisher with different configurations. It really helps us to publish events with different configurations in the same solution!

There are news enhancements we would like to use but, we cannot upgrade the CAP from 5.1.0 to the new ones. Since we apply this **"wrapper"** logic, for all versions where version > 5.1.0, we get this null object reference exception. Because of this issue, I cannot use the SubscribeFilter, too (version problem). 

Do you know the exact reason for this problem? If you may explain it, we can try to solve it in our code, or if possible, could you please fix this problem, we can then use new releases :)

**Comment by yang-xiaodong** [comment]
Hi @omeerkorkmazz 

Need to start Bootstrapper for initialization, like console app,  just add the following code :

```
ServiceProvider.GetRequiredService<IBootstrapper>().BootstrapAsync();
```

**Comment by omeerkorkmazz** [comment]
Hi again @yang-xiaodong,

Thanks for your response! It solves the issue. However, when the project builds for the first time and publishes the first message, it sometimes throws an object null reference coming from EnqueueToPublish. I just want you to know :)

My last question is about this bug. As you mentioned that this is broken, after your feature development, will you fix this issue in the coming releases? It will be really nice if possible so that we don't need to write some additional code :) Thanks.

**Comment by yang-xiaodong** [comment]
It may be that the first message was received before the startup was completed. Do you wait for the startup to complete in your constructor?
```
 ServiceProvider.GetRequiredService<IBootstrapper>().BootstrapAsync().Wait();
```

**Comment by omeerkorkmazz** [comment]
> It may be that the first message was received before the startup was completed. Do you wait for the startup to complete in your constructor?
> 
> ```
>  ServiceProvider.GetRequiredService<IBootstrapper>().BootstrapAsync().Wait();
> ```

Yeap! After I sent a comment 30 minutes ago, I noticed that the bootstrapping is async :) Now, it works!
