### ISSUE TITLE
不使用构造函数注入发送消息失败:Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by EmilyEdna** [dotnetcore/CAP#986]
你好首先我在项目使用使用MSDI获取服务的时候得到的ICapPublisher返回未将对象引用到实例。
1.第一步将msdi放在一个IOC管理类
```
        private static ServiceProvider _provider;

        public static void Init(ServiceProvider provider)
        {
            _provider = provider;
        }
        public static T GetService<T>()
        {
            return _provider.GetRequiredService<T>();
        }
```
然后从`GetService<T>()`里面获取
`ICapPublisher publisher = IocManager.GetService<ICapPublisher>();`
当使用`publisher`发送消息时候得到异常如下：
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=DotNetCore.CAP
  StackTrace:
   at DotNetCore.CAP.Processor.Dispatcher.EnqueueToPublish(MediumMessage message) in D:\Project\CAP\src\DotNetCore.CAP\Processor\IDispatcher.Default.cs:line 75
```
查看 `_publishedChannel` 发现此对象是null值。
当然在使用构造函数获取对象时不会出现这个问题。

**Comment by xiangxiren** [comment]
https://github.com/dotnetcore/CAP/blob/df9a8cdd38bb38ce46636f69021aa368ecd68c45/samples/Sample.ConsoleApp/Program.cs#L30-32

**Comment by EmilyEdna** [comment]
> https://github.com/dotnetcore/CAP/blob/df9a8cdd38bb38ce46636f69021aa368ecd68c45/samples/Sample.ConsoleApp/Program.cs#L30-L32

我是用使用的API项目，并不是控制台，并且在源代码里面
```
            //Startup and Hosted 
            services.AddSingleton<Bootstrapper>();
            services.AddHostedService(sp => sp.GetRequiredService<Bootstrapper>());
            services.AddSingleton<IBootstrapper>(sp => sp.GetRequiredService<Bootstrapper>());

            return new CapBuilder(services);
``` 
使用的这段代码在初始化

**Comment by xiangxiren** [comment]
_publishedChannel 为null，是因为没有没有执行`Dispatcher`中的`Start`方法。而`Start`方法的调用最终是由`Bootstrapper`的`BootstrapAsync`。
所以你要确保程序启动时`Bootstrapper`的`BootstrapAsync`方法会被正确的执行。

**Comment by EmilyEdna** [comment]
在系统初始化构建的时候`Dispatcher`中的`Start`是被执行过的，如果没有被执行通过构造函数获取到的`ICapPublisher`里面的的私有字段`_publishedChannel `是`null`值，相反我通过构造函数去获取`_publishedChannel `并不是`null`值，我也怀疑是否我的CAP配置有问题，以下实我的CAP配置。
```
 public static IServiceCollection RegistCap(this IServiceCollection services)
        {
            services.AddCap(opt =>
            {
                opt.UseMongoDB(Configuration.GetConnectionString("Mongo"));
                opt.UseRabbitMQ(t =>
                {
                    t.HostName = Configuration["RabbitMQ:HostName"];
                    t.Port = Configuration["RabbitMQ:Port"].AsInt();
                    t.VirtualHost = Configuration["RabbitMQ:VirtualHost"];
                    t.UserName = Configuration["RabbitMQ:Name"];
                    t.Password = Configuration["RabbitMQ:Pwd"];
                });
                opt.UseDashboard();
            });
            return services;
        }
```

**Comment by EmilyEdna** [comment]
> _publishedChannel 为null，是因为没有没有执行`Dispatcher`中的`Start`方法。而`Start`方法的调用最终是由`Bootstrapper`的`BootstrapAsync`。
> 所以你要确保程序启动时`Bootstrapper`的`BootstrapAsync`方法会被正确的执行。

在系统初始化构建的时候`Dispatcher`中的`Start`是被执行过的，如果没有被执行通过构造函数获取到的`ICapPublisher`里面的的私有字段`_publishedChannel`是`null`值，相反我通过构造函数去获取`_publishedChannel`并不是`null`值，我也怀疑是否我的CAP配置有问题，以下是我的CAP配置。
```
 public static IServiceCollection RegistCap(this IServiceCollection services)
     {
            services.AddCap(opt =>
            {
                opt.UseMongoDB(Configuration.GetConnectionString("Mongo"));
                opt.UseRabbitMQ(t =>
                {
                    t.HostName = Configuration["RabbitMQ:HostName"];
                    t.Port = Configuration["RabbitMQ:Port"].AsInt();
                    t.VirtualHost = Configuration["RabbitMQ:VirtualHost"];
                    t.UserName = Configuration["RabbitMQ:Name"];
                    t.Password = Configuration["RabbitMQ:Pwd"];
                });
                opt.UseDashboard();
            });
            return services;
        }
```

**Comment by xiangxiren** [comment]
> 在系统初始化构建的时候`Dispatcher`中的`Start`是被执行过的，如果没有被执行通过构造函数获取到的`ICapPublisher`里面的的私有字段`_publishedChannel`是`null`值，相反我通过构造函数去获取`_publishedChannel`并不是`null`值，我也怀疑是否我的CAP配置有问题，以下是我的CAP配置。
> 
> ```
>  public static IServiceCollection RegistCap(this IServiceCollection services)
>      {
>             services.AddCap(opt =>
>             {
>                 opt.UseMongoDB(Configuration.GetConnectionString("Mongo"));
>                 opt.UseRabbitMQ(t =>
>                 {
>                     t.HostName = Configuration["RabbitMQ:HostName"];
>                     t.Port = Configuration["RabbitMQ:Port"].AsInt();
>                     t.VirtualHost = Configuration["RabbitMQ:VirtualHost"];
>                     t.UserName = Configuration["RabbitMQ:Name"];
>                     t.Password = Configuration["RabbitMQ:Pwd"];
>                 });
>                 opt.UseDashboard();
>             });
>             return services;
>         }
> ```

能不能提供完整的测试代码？

**Comment by EmilyEdna** [comment]
> > 系统-在初始化构建的时候`Dispatcher`中的`Start`的英文被执行过的，没有如果被执行通过构造函数电子杂志到的`ICapPublisher`里面的的私有字段`_publishedChannel`的英文`null`值，我相反通过构造函数去电子杂志`_publishedChannel`并不是`null`值，我也怀疑是否我的CAP配置有问题，以下是我的CAP配置。
> > ```
> >  public static IServiceCollection RegistCap(this IServiceCollection services)
> >      {
> >             services.AddCap(opt =>
> >             {
> >                 opt.UseMongoDB(Configuration.GetConnectionString("Mongo"));
> >                 opt.UseRabbitMQ(t =>
> >                 {
> >                     t.HostName = Configuration["RabbitMQ:HostName"];
> >                     t.Port = Configuration["RabbitMQ:Port"].AsInt();
> >                     t.VirtualHost = Configuration["RabbitMQ:VirtualHost"];
> >                     t.UserName = Configuration["RabbitMQ:Name"];
> >                     t.Password = Configuration["RabbitMQ:Pwd"];
> >                 });
> >                 opt.UseDashboard();
> >             });
> >             return services;
> >         }
> > ```
> 
> 能不能提供完整的测试代码？

[CapTest.zip](https://github.com/dotnetcore/CAP/files/7043256/CapTest.zip)

**Comment by xiangxiren** [comment]
```
IocManager.service = services.BuildServiceProvider();
```
`IocManager`里的`ServiceProvider`跟应用程序的根容器根本就不是同一个实例。通过它们拿到的任意类型实例也不会相同。

**Comment by EmilyEdna** [comment]
> ```
> IocManager.service = services.BuildServiceProvider();
> ```
> 
> `IocManager`里的`ServiceProvider`跟应用程序的根容器根本就不是同一个实例。通过它们拿到的任意类型实例也不会相同。

Ok明白了谢谢解答.
