### ISSUE TITLE
Question aboutt message reception and consumption

### ISSUE THREAD

**Issue by hzr1348** [dotnetcore/CAP#99]
services.AddCap(x =>
            {
                x.UseEntityFramework<AppDbContext>();
                x.UseKafka("localhost:9092");
                x.UseDashboard();
                _x.DefaultGroup = "test3";_
                
                //x.UseDiscovery(d =>
                //{
                //    d.DiscoveryServerHostName = "localhost";
                //    d.DiscoveryServerPort = 8500;
                //    d.CurrentNodeHostName = "localhost";
                //    d.CurrentNodePort = 5820;
                //    d.NodeName = "CAP 2号节点";
                //});
            }).AddMessagePacker<MyMessagePacker>();
            services.AddMvc();

斜体处，当改成默认组也就是不赋值的时候，再重起应用就会收到重复已经处理的消息，而改成test4或者其他自定义组名就不会

**Comment by yuleyule66** [comment]
"当默认组转向自定义组时，会重复收到消息" This is expectantly!

"而自定义组1改成自定义组2就不会" Maybe you didn't send some messages to "自定义组1".

You need to see if the data in the Kafka is in line with expectations.

**Comment by Basil1991** [comment]
@yuleyule66 
第1次.设置两个方法的Attr为默认group（空），收到1个消息 ---正常
第2次.设置两个相同group（非空），收到1个消息                  --- 正常
第3次.设置两个不同的group，收到2个消息                             ---正常
第4次.将3的两个group改变groupName，收不到消息             ---正常
第5次.将3的两个groupName改成默认group(空)，收到两次   ---不正常（期望结果应该和4一样收不到吧，因为未设置的状态应该是给默认值）

Recieve表的数据，
Id 3为第1次，
Id 4，5为第2次，
Id 6为第3次，
第4次为空，
Id 7，8为第5次

3	nds.tools.user.msgtest	cap.queue.webapp2	{"Id":"5ab0702853eb644724ab6d9f","Timestamp":"2018-03-20T10:21:28.4025712+08:00","Content":"message","CallbackName":null}	0	2018-03-20 10:21:36	2018-03-21 10:21:47	Succeeded
4	nds.tools.user.msgtest	g1	{"Id":"5ab0709853eb6447c06d0b6d","Timestamp":"2018-03-20T10:23:20.8050674+08:00","Content":"message","CallbackName":null}	0	2018-03-20 10:23:28	2018-03-21 10:23:37	Succeeded
5	nds.tools.user.msgtest	g1	{"Id":"5ab0714a53eb64345c35bf03","Timestamp":"2018-03-20T10:26:18.9752847+08:00","Content":"message","CallbackName":null}	0	2018-03-20 10:26:25	2018-03-21 10:26:37	Succeeded
6	nds.tools.user.msgtest	g2	{"Id":"5ab0714a53eb64345c35bf03","Timestamp":"2018-03-20T10:26:18.9752847+08:00","Content":"message","CallbackName":null}	0	2018-03-20 10:26:25	2018-03-21 10:26:39	Succeeded
7	nds.tools.user.msgtest	cap.queue.webapp2	{"Id":"5ab0709853eb6447c06d0b6d","Timestamp":"2018-03-20T10:23:20.8050674+08:00","Content":"message","CallbackName":null}	0	2018-03-20 10:29:47	2018-03-21 10:30:02	Succeeded
8	nds.tools.user.msgtest	cap.queue.webapp2	{"Id":"5ab0714a53eb64345c35bf03","Timestamp":"2018-03-20T10:26:18.9752847+08:00","Content":"message","CallbackName":null}	0	2018-03-20 10:29:48	2018-03-21 10:30:02	Succeeded

**Comment by yuleyule66** [comment]
@Basil1991  你是提问者吗?

**Comment by Basil1991** [comment]
@yuleyule66 不是，早上测试了一下发现的疑问，和提问者的问题相似。

**Comment by yuleyule66** [comment]
@Basil1991  请新开一个issue，提供你的版本以及环境配置信息

**Comment by hzr1348** [comment]
@yuleyule66 详细测试了下

**Comment by hzr1348** [comment]
@yuleyule66 详细测试了下

**Comment by hzr1348** [comment]
@yuleyule66 详细测试了下，确实如你所说，但是现在有一个问题就是kafka产生的临时数据很多(tmp\kafka-logs)，测试短短几个用例就1G多了。这在实际生产环境中也是这种暴涨速度的话，估计服务器很难撑得住。

**Comment by yuleyule66** [comment]
windows上的kafka不太清楚，我在linux上使用的，感觉还好不会有那么多。 另外你是 logs 目录占用空间大还是 kafka-logs 目录占用空间大？

**Comment by hzr1348** [comment]
是kafka-logs
我在测试时，当我发布消息的时候日志基本都是暴涨，基本几个消息就瞬间几百M了，后续会有回落，不知道后续并发高的情况下日志的增长情况如何
后续我使用压测工具看下
现在日志量在1个G多一点

**Comment by yuleyule66** [comment]
ok，关闭issue。 如果发现是cap的问题，可以 reopen
