### ISSUE TITLE
The registered dbcontext is servicelifetime.scoped  When the message is subscribed, the dbcontext obtained by different subscriptions is the same instance, resulting in an error

### ISSUE THREAD

**Issue by girvs** [dotnetcore/CAP#994]
The registered dbcontext is servicelifetime.scoped

When the message is subscribed, the dbcontext obtained by different subscriptions is the same instance, resulting in an error

A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097
913.

    public class CreateRegisteredUserEventBusHandler : IIntegrationEventHandler<CreateRegisteredUserEvent>
    {
        private readonly ILocker _locker;
        private readonly ILogger<CreateRegisteredUserEventBusHandler> _logger;
        private readonly IMediatorHandler _bus;
        private readonly DomainNotificationHandler _notifications;

        public CreateRegisteredUserEventBusHandler(
           ILocker locker,
           ILogger<CreateRegisteredUserEventBusHandler> logger
       )
        {
            _locker = locker ?? throw new ArgumentNullException(nameof(locker));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _bus = EngineContext.Current.Resolve<IMediatorHandler>();
            _notifications =
                (DomainNotificationHandler)EngineContext.Current.Resolve<INotificationHandler<DomainNotification>>();
        }

        /// <summary>
        /// 事件执行
        /// </summary>
        /// <returns></returns>
        [CapSubscribe(nameof(CreateRegisteredUserEvent))]
        public Task Handle(CreateRegisteredUserEvent @event, [FromCap] CapHeader header, CancellationToken cancellationToken)
        {
            //需要重新设置身份认证头
            EngineContext.Current.ClaimManager.CapEventBusReSetClaim(header);
            var cacheBaseConfig = EngineContext.Current.GetAppModuleConfig<CacheConfig>();

            _locker.PerformActionWithLock(@event.Id.ToString(),
                TimeSpan.FromMinutes(cacheBaseConfig.CacheBaseConfig.DefaultCacheTime),
                async () =>
                {
                    _logger.LogInformation($"接收到事件，开始处理：{@event.Id}");

                    var command = new CreateRegisteredUserCommand(@event.UserName,
                                                                  @event.UserPassword.ToMd5(),
                                                                  @event.ContactNumber,
                                                                  @event.CardId
            );

                     await _bus.SendCommand(command);

                    _logger.LogInformation($"接收到事件，处理结束：{@event.Id}");
                });

            return Task.CompletedTask;
        }
    }

**Comment by yang-xiaodong** [comment]
How do we reproduce this problem?
Please do not include irrelevant code in the content

**Comment by yang-xiaodong** [comment]
No response, closed!
