### ISSUE TITLE
The queue has faked death

### ISSUE THREAD

**Issue by gnsilence** [dotnetcore/CAP#997]
Program running properly,Queue always receiving,But it doesn't receive,Restart the message queue,Will receive normally

![76$4DMQAIBS6)6T@Q`83{5N](https://user-images.githubusercontent.com/18021366/132440914-691520d6-1a54-4ea5-b6fe-721e92377828.png)

![OVKCZKGR)4671WQB`F(93AN](https://user-images.githubusercontent.com/18021366/132440942-c76e952c-5dec-45db-9fab-745c2904b0c5.png)

**Comment by yang-xiaodong** [comment]
Based on the information you provided, we are unable to conduct an investigation. Please describe your problem in detail and provide steps that can be reproduced

**Comment by gnsilence** [comment]
> Based on the information you provided, we are unable to conduct an investigation. Please describe your problem in detail and provide steps that can be reproduced

It's normal use,Or, how do I query the execution log,

**Comment by yang-xiaodong** [comment]
Please provide the  following information:

CAP Version :
Transport :
Storage :
Configuration :
Steps to reproducce :

**Comment by yang-xiaodong** [comment]
No response, closed!
