### ISSUE TITLE
Lambda Api - Queues and Topics not created for SQS 

### ISSUE THREAD

**Issue by rlefflerElite** [dotnetcore/CAP#999]
When sending and receiving messages using SQS locally, everything works great.  When I deploy to an AWS lambda as a aspnet core web api project, the queues and subscriptions are not created, and no messages are sent or received.  I have added permissions from lambda to SQS and SNS.  I set the CAP log level to DEBUG and it is not showing any errors.  Does anyone have any idea what might be the case?  Or is there extra logging that I can use to figure out why the queues are not being created?

`  services.AddCap(capOptions =>
            {
                capOptions.Version = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");

                capOptions.UseAmazonSQS(opts =>
                {
                    opts.Credentials = new BasicAWSCredentials("XXXXX", "XXXXXX");
                    opts.Region = Amazon.RegionEndpoint.USEast1;
                });

                capOptions.UseInMemoryStorage();
                capOptions.FailedThresholdCallback = (FailedInfo) =>
                {
                    Console.WriteLine(FailedInfo.Message?.Value);
                };
            });`

and here is one of my controllers

` 
[Route("api/[controller]")]
    [ApiController]
    public class MessageListenerController : ControllerBase
    {
        private readonly ICapPublisher _capPublisher;

        public MessageListenerController(ICapPublisher capPublisher)
        {
            _capPublisher = capPublisher;
        }

        [NonAction]
        [CapSubscribe("elite.message.get")]
        public async Task GetMessageAsync(dynamic model)
        {
            Console.WriteLine("We got a message via CAP on a labmda!!!!!!!!!!!!!");
            Console.WriteLine(JsonConvert.SerializeObject(model));
        }

        [HttpGet("send")]
        public async Task SendAsync()
        {
            Console.WriteLine("Sending message via cap from server 1");
            await _capPublisher.PublishAsync("elite.message2.get", "Hello I am sending this to you");
            Console.WriteLine("Message sent via cap from server 1");
        }
    }
}`

and here is a controller on another lambda api

` 
[Route("api/[controller]")]
    [ApiController]
    public class MessageListenerController : ControllerBase
    {
        private readonly ICapPublisher _capPublisher;

        public MessageListenerController(ICapPublisher capPublisher)
        {
            _capPublisher = capPublisher;
        }

        [NonAction]
        [CapSubscribe("elite.message2.get")]
        public async Task GetMessageAsync(dynamic model)
        {
            Console.WriteLine("We got a message via CAP on a labmda!!!!!!!!!!!!!");
            Console.WriteLine(JsonConvert.SerializeObject(model));
        }

        [HttpGet("send")]
        public async Task SendAsync()
        {
            Console.WriteLine("Sending message via cap from server 2");
            await _capPublisher.PublishAsync("elite.message.get", "Hello I am sending this to you");
            Console.WriteLine("Message sent via cap from server 2");
        }
    }
}`

Any help would be appreciated.  I love cap, but it would be great if I could use it in this scenario.

Thanks

**Comment by yang-xiaodong** [comment]
Hello,
CAP needs a background thread to run for a long running with broker, which is inconsistent with Lambda's scenes
